### ISSUE TITLE
espnet/nets/chainer_backend/e2e_asr.py has bug

### ISSUE THREAD

**Issue by boystray** [espnet/espnet#1038]
when I run egs/an4/asr1$ ./run.sh --backend chainer, there is a error

stage 4: Network Training
run.pl: job failed, log is in exp/train_nodev_chainer_train_mtlalpha1.0/train.log

the following is exp/train_nodev_chainer_train_mtlalpha1.0/train.log
 `^[[JException in main training loop: unsupported operand type(s) for *: 'float' and 'NoneType'
Traceback (most recent call last):
  File "/media/boystray/two/githome/espnet/tools/venv/lib/python3.7/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/media/boystray/two/githome/espnet/espnet/nets/chainer_backend/rnn/training.py", line 111, in update
    self.update_core()
  File "/media/boystray/two/githome/espnet/espnet/nets/chainer_backend/rnn/training.py", line 91, in update_core
    loss = optimizer.target(*x) / self.accum_grad
  File "/media/boystray/two/githome/espnet/tools/venv/lib/python3.7/site-packages/chainer/link.py", line 294, in __call__
    out = forward(*args, **kwargs)
  File "/media/boystray/two/githome/espnet/espnet/nets/chainer_backend/e2e_asr.py", line 119, in forward
    self.loss = alpha * loss_ctc + (1 - alpha) * loss_att
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/media/boystray/two/githome/espnet/egs/an4/asr1/../../../espnet/bin/asr_train.py", line 380, in <module>
    main(sys.argv[1:])
  File "/media/boystray/two/githome/espnet/egs/an4/asr1/../../../espnet/bin/asr_train.py", line 365, in main
    train(args)
  File "/media/boystray/two/githome/espnet/espnet/asr/chainer_backend/asr.py", line 358, in train
    trainer.run()
  File "/media/boystray/two/githome/espnet/tools/venv/lib/python3.7/site-packages/chainer/training/trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "/media/boystray/two/githome/espnet/tools/venv/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/media/boystray/two/githome/espnet/tools/venv/lib/python3.7/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/media/boystray/two/githome/espnet/espnet/nets/chainer_backend/rnn/training.py", line 111, in update
    self.update_core()
  File "/media/boystray/two/githome/espnet/espnet/nets/chainer_backend/rnn/training.py", line 91, in update_core
    loss = optimizer.target(*x) / self.accum_grad
  File "/media/boystray/two/githome/espnet/tools/venv/lib/python3.7/site-packages/chainer/link.py", line 294, in __call__
    out = forward(*args, **kwargs)
  File "/media/boystray/two/githome/espnet/espnet/nets/chainer_backend/e2e_asr.py", line 119, in forward
    self.loss = alpha * loss_ctc + (1 - alpha) * loss_att
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'`

then i found source code in espnet/nets/chainer_backend/e2e_asr.py
       # 4. attention loss
        if self.mtlalpha == 1:
            loss_att = None
            acc = None
        else:
            loss_att, acc = self.dec(hs, ys)
        self.acc = acc
        alpha = self.mtlalpha
        self.loss = alpha * loss_ctc + (1 - alpha) * loss_att

when self.mtlalpha == 1,then loss_att is None,so self.loss = alpha * loss_ctc + (1 - alpha) * loss_att will report error "TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'"

**Comment by boystray** [comment]
i found the code in espnet/nets/chainer_backend/e2e_asr.py is changed 
the origin code is correct
        if alpha == 0:
            self.loss = loss_att
        elif alpha == 1:
            self.loss = loss_ctc
        else:
            self.loss = alpha * loss_ctc + (1 - alpha) * loss_att

**Comment by Fhrozen** [comment]
Thank you for the report.
I just submitted a PR to solve this issue. (#1039)

**Comment by kan-bayashi** [comment]
Fixed in #1039
