### ISSUE TITLE
multi gpu lm training throws CUDA out of memory exception

### ISSUE THREAD

**Issue by fanlu** [espnet/espnet#1075]
There was an out of memory exception thrown when I use lm.yaml and lm_large.yaml in librispeech egs with multi gpu=4.
```
Exception in main training loop: CUDA out of memory. Tried to allocate 19.62 MiB (GPU 2; 22.38 GiB total capacity; 21.01 GiB already allocated; 10.06 MiB free; 634.29 MiB cached)                                   
Traceback (most recent call last):
  File "/mnt/cfs1/asr/users/fanlu/miniconda3/lib/python3.7/site-packages/chainer/training/trainer.py", line 316, in run                                                                                              
    update()
  File "/mnt/cfs1/asr/users/fanlu/miniconda3/lib/python3.7/site-packages/chainer/training/updaters/standard_updater.py", line 175, in update                                                                         
    self.update_core()
  File "/mnt/cfs1/asr/users/fanlu/espnet/espnet/lm/pytorch_backend/lm.py", line 277, in update_core
    loss.backward()  # Backprop
  File "/mnt/cfs1/asr/users/fanlu/miniconda3/lib/python3.7/site-packages/torch/tensor.py", line 102, in backward                                                                                                     
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/mnt/cfs1/asr/users/fanlu/miniconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward                                                                                           
    allow_unreachable=True)  # allow_unreachable flag
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/mnt/cfs1/asr/users/fanlu/espnet/espnet/bin/lm_train.py", line 156, in <module>
    main(sys.argv[1:])
  File "/mnt/cfs1/asr/users/fanlu/espnet/espnet/bin/lm_train.py", line 150, in main
    train(args)
  File "/mnt/cfs1/asr/users/fanlu/espnet/espnet/lm/pytorch_backend/lm.py", line 416, in train
    trainer.run()
  File "/mnt/cfs1/asr/users/fanlu/miniconda3/lib/python3.7/site-packages/chainer/training/trainer.py", line 349, in run                                                                                              
    six.reraise(*exc_info)
  File "/mnt/cfs1/asr/users/fanlu/miniconda3/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/mnt/cfs1/asr/users/fanlu/miniconda3/lib/python3.7/site-packages/chainer/training/trainer.py", line 316, in run                                                                                              
    update()
  File "/mnt/cfs1/asr/users/fanlu/miniconda3/lib/python3.7/site-packages/chainer/training/updaters/standard_updater.py", line 175, in update                                                                         
    self.update_core()
  File "/mnt/cfs1/asr/users/fanlu/espnet/espnet/lm/pytorch_backend/lm.py", line 277, in update_core
    loss.backward()  # Backprop
  File "/mnt/cfs1/asr/users/fanlu/miniconda3/lib/python3.7/site-packages/torch/tensor.py", line 102, in backward                                                                                                     
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/mnt/cfs1/asr/users/fanlu/miniconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward                                                                                           
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 19.62 MiB (GPU 2; 22.38 GiB total capacity; 21.01 GiB already allocated; 10.06 MiB free; 634.29 MiB cached)                                                      
# Accounting: time=746 threads=1
# Finished at Sun Aug 11 14:58:25 CST 2019 with status 1
```

**Comment by alpha19881007** [comment]
ensure your sentence length not too long, may be small than 128/256

**Comment by fanlu** [comment]
There is a same problem is egs tedlium3 too.And there was no problem in single gpu before.So Maybe It's a new bug in multi gpu recipe.

**Comment by kan-bayashi** [comment]
Could you check whether it works with small batchsize?
In multi-gpu case, we automatically increase `batchsize = batchsize * ngpu`.

**Comment by fanlu** [comment]
Yes.I have changed the batchsize from 512 to 256/128/32. There are exists the same problem also.

**Comment by kan-bayashi** [comment]
Thank you. There might be a bug.
We will investigate.

**Comment by ShigekiKarita** [comment]
I could reproduce this bug in TED-LIUM3. Because I tested multi GPU LM in AN4, I haven't met this problem. I suspect that this issue is related to chainer trainer because I just simply added `torch.nn.DataParallel` in the standard way. So I will create chainer-less `lm_train.py` for checking that.

**Comment by kan-bayashi** [comment]
Maybe this is related to following part
https://github.com/espnet/espnet/blob/8fdd8e96b0896d97a63ab74ceb1cbc01c7652778/espnet/lm/pytorch_backend/lm.py#L265-L270

The final loss calculation is conducted on only main gpu.

**Comment by ShigekiKarita** [comment]
Hmm, if so, this should be a pytorch bug. Maybe we can create the smallest example to reproduce this memory leak in multi GPUs to submit an issue to pytorch.
