### ISSUE TITLE
Warp-ctc request for cuda_ver in CPU standalone. (Enable Warp-ctc Issues?)

### ISSUE THREAD

**Issue by Fhrozen** [espnet/espnet#1088]
@jnishi  from the update (@ysk24ok) to warp-ctc, it request for cuda version even when there is a CPU-only pc. 

The output is:
```
Torch was not built with CUDA support, not building warp-ctc GPU extensions.
Traceback (most recent call last):
  File "setup.py", line 66, in <module>
    get_torch_version(), get_cuda_version())
  File "setup.py", line 55, in get_cuda_version
    proc = Popen(['nvcc', '--version'], stdout=PIPE, stderr=PIPE)
  File "/home/nelson/docstrings/tools/venv/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/home/nelson/docstrings/tools/venv/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nvcc': 'nvcc'
```
https://github.com/espnet/warp-ctc/blob/4209ce47774b54f6e72a9be99c98bdd7d4843a78/pytorch_binding/setup.py#L65-L66

It will be better to set to:
```python
if enable_gpu: 
    tag = 'cuda{}'.format(get_cuda_version())
else:
    tag = 'cpu'
package_name = 'warpctc_pytorch{}_{}'.format(
    get_torch_version(), tag)

```
or similar

* BTW, I am not sure if it is possible to enable issues in espnet/warp-ctc.

**Comment by sw005320** [comment]
> * BTW, I am not sure if it is possible to enable issues in espnet/warp-ctc.

Done.

**Comment by Fhrozen** [comment]
Moved to warp-ctc issues.
