### ISSUE TITLE
Faster recognizing

### ISSUE THREAD

**Issue by robothubtokyo** [espnet/espnet#1136]
We tested recog_wav.sh with GPU, and confirmed that GPU can decode faster than CPU.
Are there any ways to accelerate recognizing when we use GPU ?

**Comment by kan-bayashi** [comment]
I listed up general tips to make decoding faster:
- Use small beam size (of course this is the trade off with the performance)
- Make model smaller (of course this is the trade off with the performance)
- Use subword units to reduce the length outputs
- Use FP16 decoding (available with `--dtype float16` and `--api v2`)

**Comment by ShigekiKarita** [comment]
And also `ctc_weight=0.0` (and `lm_weight=0.0`) also speeds up because ctc/lm decoding is slow, while it degrades accuracy.

**Comment by robothubtokyo** [comment]
Thank you.
We tested
>- Use FP16 decoding (available with --dtype float16 and --api v2)

and got an error.
The log is here.
`\# asr_recog.py --config conf/decode.yaml --ngpu 1 --backend pytorch --debugmode 1 --verbose 1 --recog-json decode/2019-08-25T001300.407Z/dump/data.json --result-label decode/2019-08-25T001300.407Z/result.json --model exp/train_nodup_sp_pytorch_train/results/model.acc.best --api v2 --dtype float16 --rnnlm exp/train_rnnlm_pytorch_lm/rnnlm.model.best 
\# Started at Sun Aug 25 00:13:02 UTC 2019
\#
2019-08-25 00:13:02,467 (asr_recog:141) WARNING: CUDA_VISIBLE_DEVICES is not set.
2019-08-25 00:13:02,467 (asr_recog:152) INFO: python path = (None)
2019-08-25 00:13:02,467 (asr_recog:157) INFO: set random seed = 1
2019-08-25 00:13:02,467 (asr_recog:165) INFO: backend = pytorch
/espnet/tools/venv/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
2019-08-25 00:13:03,514 (recog:30) WARNING: experimental API for custom LMs is selected by --api v2
2019-08-25 00:13:03,515 (deterministic_utils:24) INFO: torch type check is disabled
2019-08-25 00:13:03,515 (asr_utils:328) INFO: reading a config file from exp/train_nodup_sp_pytorch_train/results/model.json
2019-08-25 00:13:03,515 (asr:292) INFO: reading model parameters from exp/train_nodup_sp_pytorch_train/results/model.acc.best
/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/_reduction.py:49: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))
2019-08-25 00:13:03,833 (font_manager:1341) INFO: generated new fontManager
2019-08-25 00:13:04,305 (asr_utils:328) INFO: reading a config file from exp/train_rnnlm_pytorch_lm/model.json
2019-08-25 00:13:04,540 (recog:85) INFO: Decoding device=cuda, dtype=torch.float16
2019-08-25 00:13:06,830 (recog:95) INFO: (1/1) decoding 2019-08-25T001300.407Z
2019-08-25 00:13:07,002 (beam_search:273) INFO: max output length: 37
2019-08-25 00:13:07,002 (beam_search:274) INFO: min output length: 0
Traceback (most recent call last):
  File "/espnet/egs/csj/asr1/../../../espnet/bin/asr_recog.py", line 191, in <module>
    main(sys.argv[1:])
  File "/espnet/egs/csj/asr1/../../../espnet/bin/asr_recog.py", line 174, in main
    recog_v2(args)
  File "/espnet/espnet/asr/pytorch_backend/recog.py", line 99, in recog_v2
    nbest_hyps = beam_search(x=enc, maxlenratio=args.maxlenratio, minlenratio=args.minlenratio)
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/espnet/espnet/nets/beam_search.py", line 285, in forward
    part_scores, part_states = self.score_partial(hyp, part_ids, x)
  File "/espnet/espnet/nets/beam_search.py", line 158, in score_partial
    scores[k], states[k] = d.score_partial(hyp.yseq, ids, hyp.states[k], x)
  File "/espnet/espnet/nets/scorers/ctc.py", line 68, in score_partial
    presub_score, new_st = self.impl(y.cpu(), ids.cpu(), state)
  File "/espnet/espnet/nets/ctc_prefix_score.py", line 154, in __call__
    xs = self.x[:, cs]
IndexError: index 9223231297218904063 is out of bounds for axis 1 with size 3261
\# Accounting: time=5 threads=1
\# Ended (code 1) at Sun Aug 25 00:13:07 UTC 2019, elapsed time 5 seconds`

**Comment by ShigekiKarita** [comment]
I suspect that this kind of IndexError was caused by nan input in torch.topk.  And fp16 is easily caused nan by overflow. I wonder if apex.amp could be used in decoding (we currently use it only in training).
