### ISSUE TITLE
Dataloader is killed (v.0.6.0)

### ISSUE THREAD

**Issue by Fhrozen** [espnet/espnet#1185]
I am training iwslt19/asr1 with the last v.0.6.0 and I am getting this error when I try to train different  networks at the same time:

```
# asr_train.py --config conf/train_4.yaml --preprocess-conf conf/specaug.yaml --ngpu 2 --backend pytorch --outdir exp/train_lc.rm_pytorch_train_4_bpe5000_specaug/results --tensorboard-dir tensorboard/train_lc.rm_pytorch_train_4_bpe5000_specaug --debugmode 1 --dict data/lang_1spm/train_bpe5000_units_lc.rm.txt --debugdir exp/train_lc.rm_pytorch_train_4_bpe5000_specaug --minibatches 0 --seed 1 --verbose 0 --resume --train-json dump/train/deltafalse/data_bpe5000.lc.rm.json --valid-json dump/dev/deltafalse/data_bpe5000.lc.rm.json
# Started at Sun Sep  8 16:04:39 JST 2019
#
/home/i19_nelsonyalta/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/_reduction.py:49: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))
2019-09-08 16:04:40,980 (asr_train:296) WARNING: Skip DEBUG/INFO messages
2019-09-08 16:05:08,025 (io_utils:59) WARNING: [Experimental feature] Some preprocessing will be done for the mini-batch creation using Transformation(
    0: TimeWarp(max_time_warp=5, inplace=True, mode=PIL)
    1: FreqMask(F=30, n_mask=2, replace_with_zero=False, inplace=True)
    2: TimeMask(T=40, n_mask=2, replace_with_zero=False, inplace=True))
2019-09-08 16:05:08,038 (io_utils:59) WARNING: [Experimental feature] Some preprocessing will be done for the mini-batch creation using Transformation(
    0: TimeWarp(max_time_warp=5, inplace=True, mode=PIL)
    1: FreqMask(F=30, n_mask=2, replace_with_zero=False, inplace=True)
    2: TimeMask(T=40, n_mask=2, replace_with_zero=False, inplace=True))
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
^@ESC[JException in main training loop: DataLoader worker (pid 4946) is killed by signal: Bus error. 
Traceback (most recent call last):
  File "/home/i19_nelsonyalta/espnet/tools/venv/lib/python3.7/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/home/i19_nelsonyalta/espnet/espnet/asr/pytorch_backend/asr.py", line 209, in update
    self.update_core()
  File "/home/i19_nelsonyalta/espnet/espnet/asr/pytorch_backend/asr.py", line 178, in update_core
    loss = data_parallel(self.model, x, range(self.ngpu)).mean() / self.accum_grad
  File "/home/i19_nelsonyalta/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 183, in data_parallel
    inputs, module_kwargs = scatter_kwargs(inputs, module_kwargs, device_ids, dim)
  File "/home/i19_nelsonyalta/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 35, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "/home/i19_nelsonyalta/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 28, in scatter
    return scatter_map(inputs)
  File "/home/i19_nelsonyalta/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 15, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/home/i19_nelsonyalta/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 13, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/home/i19_nelsonyalta/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/parallel/_functions.py", line 89, in forward
    outputs = comm.scatter(input, target_gpus, chunk_sizes, ctx.dim, streams)
  File "/home/i19_nelsonyalta/espnet/tools/venv/lib/python3.7/site-packages/torch/cuda/comm.py", line 148, in scatter
    return tuple(torch._C._scatter(tensor, devices, chunk_sizes, dim, streams))
  File "/home/i19_nelsonyalta/espnet/tools/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 274, in handler
    _error_if_any_worker_fails()
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/home/i19_nelsonyalta/espnet/egs/iwslt19/asr1/../../../espnet/bin/asr_train.py", line 362, in <module>
    main(sys.argv[1:])
  File "/home/i19_nelsonyalta/espnet/egs/iwslt19/asr1/../../../espnet/bin/asr_train.py", line 349, in main
    train(args)
  File "/home/i19_nelsonyalta/espnet/espnet/asr/pytorch_backend/asr.py", line 540, in train
    trainer.run()
  File "/home/i19_nelsonyalta/espnet/tools/venv/lib/python3.7/site-packages/chainer/training/trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "/home/i19_nelsonyalta/espnet/tools/venv/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/i19_nelsonyalta/espnet/tools/venv/lib/python3.7/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/home/i19_nelsonyalta/espnet/espnet/asr/pytorch_backend/asr.py", line 209, in update
    self.update_core()
  File "/home/i19_nelsonyalta/espnet/espnet/asr/pytorch_backend/asr.py", line 178, in update_core
    loss = data_parallel(self.model, x, range(self.ngpu)).mean() / self.accum_grad
  File "/home/i19_nelsonyalta/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 183, in data_parallel
    inputs, module_kwargs = scatter_kwargs(inputs, module_kwargs, device_ids, dim)
  File "/home/i19_nelsonyalta/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 35, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "/home/i19_nelsonyalta/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 28, in scatter
    return scatter_map(inputs)
  File "/home/i19_nelsonyalta/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 15, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/home/i19_nelsonyalta/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 13, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/home/i19_nelsonyalta/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/parallel/_functions.py", line 89, in forward
    outputs = comm.scatter(input, target_gpus, chunk_sizes, ctx.dim, streams)
  File "/home/i19_nelsonyalta/espnet/tools/venv/lib/python3.7/site-packages/torch/cuda/comm.py", line 148, in scatter
    return tuple(torch._C._scatter(tensor, devices, chunk_sizes, dim, streams))
  File "/home/i19_nelsonyalta/espnet/tools/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 274, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 4946) is killed by signal: Bus error. 
# Accounting: time=47 threads=1
```
I am using : `n-iter-processes: 4` to speed up, i tried in a different in a pc with two training in simultaneous and have no problem. 4 training in simultaneous seems problematic.
@ShigekiKarita @bobchennan

**Comment by bobchennan** [comment]
Do you have any memory limitation? Do you run it with Docker?

**Comment by bobchennan** [comment]
According to https://github.com/pytorch/pytorch/issues/5040 PIL resize requires a lot of shared memory. You can try to remove specaug preprocessing to see if the problem exists. If you are using docker specify `--shm-size 50G`

**Comment by Fhrozen** [comment]
Well, I am using kind of docker (kubernetes pod) with 256Gb and 24 cpus, I can only run 2 training with `n-iter-processes: 4`, the other two has not this option. and works by now.

**Comment by Fhrozen** [comment]
Ok, I just checked, another training just get killed. to i am only trying now with 1 `n-iter-processes: 4` and the others without it.

**Comment by bobchennan** [comment]
Try to specify `--shm-size 50G`.

Also try to run without `--preprocess-conf conf/specaug.yaml` to check if it is the problem of PIL.

**Comment by fanlu** [comment]
I have met the same problem with --preprocess-conf ""
```
./run.sh --stage 4 --stop_stage 4 --ngpu 4 --preprocess_config "" --n_iter_processes 4 --train_config conf/tuning/train_pytorch_transformer_bb.yaml --verbose 1 --train_set train_sp_trim
```

**Comment by qmpzzpmq** [comment]
I had this issue as well. please set n-iter-processes to zero
there is some discussion, https://forums.fast.ai/t/runtimeerror-dataloader-worker-is-killed-by-signal/31277/8
 I guess it is a bug of pytorch
