### ISSUE TITLE
Bug in rnn-transducer

### ISSUE THREAD

**Issue by Masao-Someki** [espnet/espnet#1198]
I tried to run the script of rnn-transducer, but there is a bug at decoding process.
```error_log
# asr_recog.py --config conf/decode.yaml --ngpu 0 --backend pytorch --debugmode 1 --verbose 0 --batchsize 0 --recog-json dump/eval1/deltafalse/split32utt/data.1.json --result-label exp/train_nodup_sp_pytorch_train/decode_eval1_decode_lm/data.1.json --model exp/train_nodup_sp_pytorch_train/results/model.last10.avg.best --rnnlm exp/train_rnnlm_pytorch_lm/rnnlm.model.best
# Started at Tue Sep 17 16:08:45 JST 2019
#
2019-09-17 16:08:48,229 (asr_recog:140) WARNING: Skip DEBUG/INFO messages
2019-09-17 16:09:03,451 (e2e_asr_transducer:138) WARNING: Subsampling is not performed for vgg*. It is performed in max pooling layers at CNN.
Shape of ytu: torch.Size([3262]) # I add this line for debug
Value of ytu[0]: tensor(-0.0689) # I add this line for debug
Traceback (most recent call last):
  File "/home/m_someki/workspace4/espnet/egs/csj/asr1/../../../espnet/bin/asr_recog.py", line 196, in <module>
    main(sys.argv[1:])
  File "/home/m_someki/workspace4/espnet/egs/csj/asr1/../../../espnet/bin/asr_recog.py", line 184, in main
    recog(args)
  File "/work4/m_someki/espnet/espnet/asr/pytorch_backend/asr.py", line 656, in recog
    nbest_hyps = model.recognize(feat, args, train_args.char_list, rnnlm)
  File "/work4/m_someki/espnet/espnet/nets/pytorch_backend/e2e_asr_transducer.py", line 344, in recognize
    y = self.dec.recognize_beam(h[0], recog_args, rnnlm)
  File "/work4/m_someki/espnet/espnet/nets/pytorch_backend/rnn/decoders_transducer.py", line 278, in recognize_beam
    beam_hyp['score'] += recog_args.lm_weight * rnnlm_scores[0][ytu[k]]
RuntimeError: tensors used as indices must be long or byte tensors
```

**Comment by Masao-Someki** [comment]
Stage 0-4 have successfully processed, but only stage 5 has the error.

**Comment by b-flo** [comment]
Hi,

Thanks for the report! Sorry forgot to change the LM part, instead of:

`beam_hyp['score'] += recog_args.lm_weight * rnnlm_scores[0][ytu[k]]`

It should be this: 

`beam_hyp['score'] += recog_args.lm_weight * rnnlm_scores[0][k]`

**Comment by Masao-Someki** [comment]
Okay, thank you!
