### ISSUE TITLE
import librosa get OSError

### ISSUE THREAD

**Issue by kaituoxu** [espnet/espnet#1301]
Hi, after I pass `make check_install`, I got below import error when I tried to train models. After `apt-get install libsndfile1-dev`, this error gone. Maybe need to fix this problem in related install scripts. Thx.

```
>>> import librosa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/Project/espnet/tools/venv/lib/python3.7/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/home/Project/espnet/tools/venv/lib/python3.7/site-packages/librosa/core/__init__.py", line 124, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "/home/Project/espnet/tools/venv/lib/python3.7/site-packages/librosa/core/audio.py", line 10, in <module>
    import soundfile as sf
  File "/home/Project/espnet/tools/venv/lib/python3.7/site-packages/soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found
```

**Comment by kan-bayashi** [comment]
Thank you for your report.
We will add the library as a pre-requirement in README.
