### ISSUE TITLE
Error in decoding using a GPU

### ISSUE THREAD

**Issue by vlad-winter** [espnet/espnet#1339]
Hi,

I'm running the LibriSpeech recipe. Up to stage 4, all went well. Next, I run stage 5:

`./run_orig.sh --backend pytorch --stage 5 --ngpu 1 --verbose 0`

with this configuration decode.yaml:

`batchsize: 4
beam-size: 4
ctc-weight: 0.0
lm-weight: 0.0
maxlenratio: 0.0
minlenratio: 0.0
penalty: 0.0
`

I modified the run.sh file to run the decoding on the GPU:

`
 
        # use CPU for decoding
        ngpu=1

        # set batchsize 0 to disable batch decoding
        ${decode_cmd} JOB=1:${nj} ${expdir}/${decode_dir}/log/decode.JOB.log \
            asr_recog.py \
            --config ${decode_config} \
            --ngpu ${ngpu} \
            --backend ${backend} \
            --batchsize 0 \
            --recog-json ${feat_recog_dir}/split${nj}utt/data_${bpemode}${nbpe}.JOB.json \
            --result-label ${expdir}/${decode_dir}/data.JOB.json \
            --model ${expdir}/results/${recog_model}  \
            --rnnlm ${lmexpdir}/${lang_model}
`

And I do get the GPU going (the VRAM is used almsot entirely and the utilization is close to 100%) and training. A few minutes after it starts, however, it fails with this log:

`
stage 5: Decoding
best val scores = [0.29418091 0.29366009 0.29363559 0.29312183 0.29223559]
selected epochs = [124 145 114 135  93]
average over ['exp/train_clean_100_pytorch_train_specaug/results/snapshot.ep.124', 'exp/train_clean_100_pytorch_train_specaug/results/snapshot.ep.145', 'exp/train_clean_100_pytorch_train_specaug/results/snapshot.ep.114', 'exp/train_clean_100_pytorch_train_specaug/results/snapshot.ep.135', 'exp/train_clean_100_pytorch_train_specaug/results/snapshot.ep.93']
average over ['exp/train_rnnlm_pytorch_lm_unigram31/snapshot.ep.1', 'exp/train_rnnlm_pytorch_lm_unigram31/snapshot.ep.2', 'exp/train_rnnlm_pytorch_lm_unigram31/snapshot.ep.3', 'exp/train_rnnlm_pytorch_lm_unigram31/snapshot.ep.4']
2019-11-05 10:24:00,416 (splitjson:40) INFO: /home/vlad/projects/espgpu/espnet/tools/venv/bin/python3 /home/vlad/projects/espgpu/espnet/egs/librispeech/asr1/../../../utils/splitjson.py --parts 32 dump/test_clean/deltafalse/data_unigram31.json
2019-11-05 10:24:00,462 (splitjson:52) INFO: number of utterances = 2620
bash: line 1: 21475 Killed                  ( asr_recog.py --config conf/decode.yaml --ngpu 1 --backend pytorch --batchsize 0 --recog-json dump/test_clean/deltafalse/split32utt/data_unigram31.21.json --result-label exp/train_clean_100_pytorch_train_specaug/decode_test_clean_model.val5.avg.best_decode_lm/data.21.json --model exp/train_clean_100_pytorch_train_specaug/results/model.val5.avg.best --rnnlm exp/train_rnnlm_pytorch_lm_unigram31/rnnlm.last6.avg.best --api v2 ) 2>> exp/train_clean_100_pytorch_train_specaug/decode_test_clean_model.val5.avg.best_decode_lm/log/decode.21.log >> exp/train_clean_100_pytorch_train_specaug/decode_test_clean_model.val5.avg.best_decode_lm/log/decode.21.log
bash: line 1: 21491 Killed                  ( asr_recog.py --config conf/decode.yaml --ngpu 1 --backend pytorch --batchsize 0 --recog-json dump/test_clean/deltafalse/split32utt/data_unigram31.18.json --result-label exp/train_clean_100_pytorch_train_specaug/decode_test_clean_model.val5.avg.best_decode_lm/data.18.json --model exp/train_clean_100_pytorch_train_specaug/results/model.val5.avg.best --rnnlm exp/train_rnnlm_pytorch_lm_unigram31/rnnlm.last6.avg.best --api v2 ) 2>> exp/train_clean_100_pytorch_train_specaug/decode_test_clean_model.val5.avg.best_decode_lm/log/decode.18.log >> exp/train_clean_100_pytorch_train_specaug/decode_test_clean_model.val5.avg.best_decode_lm/log/decode.18.log
`

So it seems to kill some of the processes (not all though), but the decoding stage fails. 
I've tried to run it with --api v2, but it also failed.

Any ideas why?

**Comment by ahmedalbahnasawy** [comment]
change from --api v2 to api v1

**Comment by vlad-winter** [comment]
Batchsize was set to 0, and I tried both with v1 and v2.

**Comment by kan-bayashi** [comment]
Could you try to reduce nj and increase batchsize (e.g. nj=1 batchsize=16).

**Comment by vlad-winter** [comment]
I've tried to reduce it to 16, it didn't work. 
I'll try with 8 and 4.

**Comment by kan-bayashi** [comment]
This is because in the case of 16, 16 processes will be running on a single GPU, causing OOM error.
If you use job scheduler command backend `queue or slurm`, it is better to change `${decode_cmd}` to `${cuda_cmd} -gpu 1`.

**Comment by vlad-winter** [comment]
Thanks, I'll try and update.

**Comment by vlad-winter** [comment]
I ran with this conf:

`   
# 
    nj=1
    pids=() # initialize pids
    for rtask in ${recog_set}; do
    (
        decode_dir=decode_${rtask}_${recog_model}_$(basename ${decode_config%.*})_${lmtag}
        feat_recog_dir=${dumpdir}/${rtask}/delta${do_delta}

        # split data
        splitjson.py --parts ${nj} ${feat_recog_dir}/data_${bpemode}${nbpe}.json

        #### use CPU for decoding
        ngpu=1

        # set batchsize 0 to disable batch decoding
        ${decode_cmd} JOB=1:${nj} ${expdir}/${decode_dir}/log/decode.JOB.log \
            asr_recog.py \
            --config ${decode_config} \
            --ngpu ${ngpu} \
            --backend ${backend} \
            --batchsize 16 \
            --recog-json ${feat_recog_dir}/split${nj}utt/data_${bpemode}${nbpe}.JOB.json \
            --result-label ${expdir}/${decode_dir}/data.JOB.json \
            --model ${expdir}/results/${recog_model}  \
            --rnnlm ${lmexpdir}/${lang_model}

        score_sclite.sh --bpe ${nbpe} --bpemodel ${bpemodel}.model --wer true ${expdir}/${decode_dir} ${dict}
`


But the job fail. The log:


`
# 
2019-11-07 06:08:00,575 (asr_utils:407) INFO: reading a config file from exp/train_clean_100_pytorch_train_specaug/results/model.json
2019-11-07 06:08:00,576 (asr_init:141) INFO: reading model parameters from exp/train_clean_100_pytorch_train_specaug/results/model.val5.avg.best
/home/vlad/projects/espgpu/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/_reduction.py:49: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))
2019-11-07 06:08:02,331 (asr_utils:407) INFO: reading a config file from exp/train_rnnlm_pytorch_lm_unigram31/model.json
2019-11-07 06:08:02,831 (io_utils:59) WARNING: [Experimental feature] Some preprocessing will be done for the mini-batch creation using Transformation(
    0: TimeWarp(max_time_warp=5, inplace=True, mode=PIL)
    1: FreqMask(F=30, n_mask=2, replace_with_zero=False, inplace=True)
    2: TimeMask(T=40, n_mask=2, replace_with_zero=False, inplace=True))
Traceback (most recent call last):
  File "/home/vlad/projects/espgpu/espnet/egs/librispeech/asr1/../../../espnet/bin/asr_recog.py", line 207, in <module>
    main(sys.argv[1:])
  File "/home/vlad/projects/espgpu/espnet/egs/librispeech/asr1/../../../espnet/bin/asr_recog.py", line 189, in main
    recog(args)
  File "/home/vlad/projects/espgpu/espnet/espnet/asr/pytorch_backend/asr.py", line 770, in recog
    nbest_hyps = model.recognize_batch(feats, args, train_args.char_list, rnnlm=rnnlm)
  File "/home/vlad/projects/espgpu/espnet/espnet/nets/asr_interface.py", line 76, in recognize_batch
    raise NotImplementedError("Batch decoding is not supported yet.")
NotImplementedError: Batch decoding is not supported yet.

`

**Comment by rai4** [comment]
@vlad-winter 
`nbest_hyps = model.recognize_batch(feats, args, train_args.char_list, rnnlm=rnnlm)`

The transformer model's recognize_batch function was executed because the decode batch size was not zero. However, the recognize_batch function is not yet implemented. Run decode batch size 0.
