### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for E2E

### ISSUE THREAD

**Issue by zhazl** [espnet/espnet#1373]
同一个环境venv下执行多个解码操作，出现
  warnings.warn(warning.format(ret))
Traceback (most recent call last):
  File "espnet/egs/hkust/asr1/../../../espnet/bin/asr_recog.py", line 166, in <module>
    main(sys.argv[1:])
  File "espnet/egs/hkust/asr1/../../../espnet/bin/asr_recog.py", line 154, in main
    recog(args)
  File "espnet/espnet/asr/pytorch_backend/asr.py", line 495, in recog
    torch_load(args.model, model)
  File "espnet/espnet/asr/asr_utils.py", line 370, in torch_load
    model.load_state_dict(model_state_dict)
  File "espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for E2E:
    Missing key(s) in state_dict: "encoder.embed.out.1.pe", "decoder.embed.1.pe".

有谁出现过这样的问题嘛？求指教

**Comment by ahmedalbahnasawy** [comment]
you are loading incorrect model, ensure that recog_model argument is the path of your ASR model

**Comment by zhazl** [comment]
Model path is correct. It had been tested successfully only using environ "venv" once.
🧐






------------------ Original ------------------

**Comment by ahmedalbahnasawy** [comment]
@zhazl sounds good

**Comment by MNCTTY** [comment]
I have the same issue with ru_open_stt models
