### ISSUE TITLE
Issue with Stage 3 (https://github.com/espnet/espnet/pull/818/files)

### ISSUE THREAD

**Issue by takeofuture** [espnet/espnet#1482]
I just want to report the error for this 818
(https://github.com/espnet/espnet/pull/818/files)
After I managed to run until Stage 2 (language model training) 
But I got error on Stage 3 right before finishing epoch one 
```
# asr_train.py --ngpu 1 --config conf/train_asr.yaml --backend pytorch --outdir exp/asr_/results --tensorboard-dir tensorboard/asr_ --debugmode 1 --dict data/lang_char/train_960_units.txt --debugdir exp/asr_ --minibatches 0 --verbose 0 --resume --train-json dump/train_clean_100/data.json --valid-json dump/dev/data.json 
~~
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/takeo/espnet/espnet/utils/dataset.py", line 33, in __getitem__
    return self.transform(self.data[idx])
  File "/home/takeo/espnet/espnet/asr/pytorch_backend/asr.py", line 509, in <lambda>
    dataset=TransformDataset(valid, lambda data: converter([load_cv(data)])),
  File "/home/takeo/espnet/espnet/asr/pytorch_backend/asr.py", line 258, in __call__
    xs, ys = batch[0]
ValueError: too many values to unpack (expected 2)
# Accounting: time=1516 threads=1
# Ended (code 1) at Sat Dec 28 19:35:58 UTC 2019, elapsed time 1516 seconds
```
I wonder why error contains chainer even I select backend=pytorch
Anyhow,
I commented out and change output location in the original asrtts/run.sh 

```
#scratch=/mnt/scratch06/tmp/baskar/espnet_new/features
#scratch=data_scr
nnet_dir=exp/xvector_nnet_1a
#mkdir -p $scratch
#if [ ${stage} -le -1 ] && [ ${stop_stage} -ge -1 ]; then
#    echo "stage -1: Tmp space allocation"
#    local/make_symlink_dir.sh --tmp-root $scratch/$fbankdir $fbankdir
#    local/make_symlink_dir.sh --tmp-root $scratch/$feat_tr_dir $feat_tr_dir
#    local/make_symlink_dir.sh --tmp-root $scratch/$feat_tr_p_dir $feat_tr_p_dir
#    local/make_symlink_dir.sh --tmp-root $scratch/$feat_tr_up_dir $feat_tr_up_dir
#    local/make_symlink_dir.sh --tmp-root $scratch/$feat_dt_dir $feat_dt_dir
#    local/make_symlink_dir.sh --tmp-root $scratch/$feat_ev_dir $feat_ev_dir
#fi
```
and change in Stage 1
```
        text2token.py -s 1 -n 1 data/${train_set}/text | cut -f 2- -d" " | tr " " "\n" \
        | sort | uniq | grep -v -e '^\s*$' | awk '{print $0 " " NR+1}' >> ${dict}
```
to 
```
        text2token.py -s 1 -n 1 data/${train_set}/text | cut -f 2- -d" " | tr " " "\n" \
        | sort | uniq | grep -v -e '^\s*$' | awk '{print $0 " " NR+1}' >> ${nlsyms}
```
I keep debuging, but if you have any clue, highly appreciated!
Thank you!

**Comment by takeofuture** [comment]
I just resolved this 
It was simply  slightly different core code in espnet/espnet
By replacing espnet/espnet from this branch (pull request)
It works, but it seems to quite a bit of changes from current main codes

**Comment by sw005320** [comment]
Yes, this is an experimental function and has a lot of changes. Making this PR to more regular espnet function is one of our important future work.

**Comment by takeofuture** [comment]
Just report what I encounter after I attempt to apply 
https://github.com/creatorscan/espnet/tree/asrtts3-v0.7.0
to jsut without x-vector parts

Issue with passing arguments from run.sh 
via 
espnet/bin/asrtts_train.py
to
espnet/nets/pytorch_backend/e2e_asrtts.py
```
    def __init__(self, idim, odim, args, predictor=None, loss_fn=None, rnnlm=None,
                 softargmax=False, asr2tts=False, reporter=None):
        super(E2E, self).__init__()
        self.etype = args.etype
        self.verbose = args.verbose
        self.char_list = args.char_list
        self.outdir = args.outdir
        self.space = args.sym_space
        self.blank = args.sym_blank
        self.predictor = predictor
        self.loss_fn = loss_fn
        #self.use_speaker_embedding = args.use_speaker_embedding
        self.use_speaker_embedding = False
        #self.n_samples_per_input = args.n_samples_per_input
        self.n_samples_per_input = 5
        #self.policy_gradient = args.policy_gradient
        self.policy_gradient = True
        #self.sample_scaling = args.sample_scaling
        self.sample_scaling = 0.1
        self.softargmax = softargmax
        #self.generator = args.generator
        self.generator = "tts"
        self.asr2tts = asr2tts
        self.rnnlm = rnnlm
        #self.rnnloss = args.rnnloss
        self.rnnloss = None
        self.reporter = reporter
        #self.update_asr_only = args.update_asr_only
        self.update_asr_only = True
        # below means the last number becomes eos/sos ID
        # note that sos/eos IDs are identical
        self.sos = odim - 1
        self.eos = odim - 1
```
as well as
esp_asrtts/espnet/nets/pytorch_backend/e2e_tts.py
```
    def __init__(self, idim, odim, args):
        super(Tacotron2, self).__init__()
        # store hyperparameters
        self.idim = idim
        self.odim = odim
        self.spk_embed_dim = args.spk_embed_dim
        self.embed_dim = args.embed_dim
        self.elayers = args.elayers
        self.eunits = args.eunits
        self.econv_layers = args.econv_layers
        self.econv_filts = args.econv_filts
        self.econv_chans = args.econv_chans
        self.dlayers = args.dlayers
        self.dunits = args.dunits
        self.prenet_layers = args.prenet_layers
        self.prenet_units = args.prenet_units
        self.postnet_layers = args.postnet_layers
        self.postnet_chans = args.postnet_chans
        self.postnet_filts = args.postnet_filts
        self.adim = args.adim
        self.aconv_filts = args.aconv_filts
        self.aconv_chans = args.aconv_chans
        self.cumulate_att_w = args.cumulate_att_w
        self.use_batch_norm = args.use_batch_norm
        self.use_concate = args.use_concate
        #self.dropout = args.dropout
        self.dropout = 0.2
        #self.zoneout = args.zoneout
        self.zoneout = 0.1
        self.reduction_factor = args.reduction_factor
        self.atype = args.atype
        self.use_cbhg = args.use_cbhg
```

I hardcoded the values in 
train_pytorch_transformer.yaml
and train_asrtts.yaml
, but still I get some error looks like some mismatch of NameSpace Variables

```
2020-01-24 02:12:24,964 (asrtts:374) WARNING: Only Disney is frozen

Traceback (most recent call last):
  File "/home/takeo/AILab/esp_asrtts/egs/jsut/asrtts/../../../espnet/bin/asrtts_train.py", line 439, in <module>
    main(sys.argv[1:])
  File "/home/takeo/AILab/esp_asrtts/egs/jsut/asrtts/../../../espnet/bin/asrtts_train.py", line 427, in main
    train(args)
  File "/home/takeo/AILab/esp_asrtts/espnet/asr/pytorch_backend/asrtts.py", line 382, in train
    loss_fn = load_tacotron_loss(args.tts_model_conf, args.tts_model, args, sa_reporter)
  File "/home/takeo/AILab/esp_asrtts/espnet/nets/pytorch_backend/e2e_asrtts.py", line 103, in load_tacotron_loss
    reporter=reporter
  File "/home/takeo/AILab/esp_asrtts/espnet/nets/pytorch_backend/e2e_asrtts.py", line 57, in TacotronRewardLoss
    torch_load(tts_model_file, tacotron2)
  File "/home/takeo/AILab/esp_asrtts/espnet/asr/asr_utils.py", line 517, in torch_load
    model.load_state_dict(model_state_dict)
  File "/home/takeo/AILab/esp_asrtts/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Tacotron2:
 Missing key(s) in state_dict: "dec.prenet.0.0.weight", "dec.prenet.1.0.weight", "dec.postnet.0.0.weight", "dec.postnet.0.1.weight", "dec.postnet.0.1.bias", "dec.postnet.0.1.running_mean", "dec.postnet.0.1.running_var", "dec.postnet.1.0.weight", "dec.postnet.1.1.weight", "dec.postnet.1.1.bias", "dec.postnet.1.1.running_mean", "dec.postnet.1.1.running_var", "dec.postnet.2.0.weight", "dec.postnet.2.1.weight", "dec.postnet.2.1.bias", "dec.postnet.2.1.running_mean", "dec.postnet.2.1.running_var", "dec.postnet.3.0.weight", "dec.postnet.3.1.weight", "dec.postnet.3.1.bias", "dec.postnet.3.1.running_mean", "dec.postnet.3.1.running_var", "dec.postnet.4.0.weight", "dec.postnet.4.1.weight", "dec.postnet.4.1.bias", "dec.postnet.4.1.running_mean", "dec.postnet.4.1.running_var".
 Unexpected key(s) in state_dict: "taco2_loss.bce_criterion.pos_weight", "dec.prenet.prenet.0.0.weight", "dec.prenet.prenet.0.0.bias", "dec.prenet.prenet.1.0.weight", "dec.prenet.prenet.1.0.bias", "dec.postnet.postnet.0.0.weight", "dec.postnet.postnet.0.1.weight", "dec.postnet.postnet.0.1.bias", "dec.postnet.postnet.0.1.running_mean", "dec.postnet.postnet.0.1.running_var", "dec.postnet.postnet.0.1.num_batches_tracked", "dec.postnet.postnet.1.0.weight", "dec.postnet.postnet.1.1.weight", "dec.postnet.postnet.1.1.bias", "dec.postnet.postnet.1.1.running_mean", "dec.postnet.postnet.1.1.running_var", "dec.postnet.postnet.1.1.num_batches_tracked", "dec.postnet.postnet.2.0.weight", "dec.postnet.postnet.2.1.weight", "dec.postnet.postnet.2.1.bias", "dec.postnet.postnet.2.1.running_mean", "dec.postnet.postnet.2.1.running_var", "dec.postnet.postnet.2.1.num_batches_tracked", "dec.postnet.postnet.3.0.weight", "dec.postnet.postnet.3.1.weight", "dec.postnet.postnet.3.1.bias", "dec.postnet.postnet.3.1.running_mean", "dec.postnet.postnet.3.1.running_var", "dec.postnet.postnet.3.1.num_batches_tracked", "dec.postnet.postnet.4.0.weight", "dec.postnet.postnet.4.1.weight", "dec.postnet.postnet.4.1.bias", "dec.postnet.postnet.4.1.running_mean", "dec.postnet.postnet.4.1.running_var", "dec.postnet.postnet.4.1.num_batches_tracked".
# Accounting: time=4 threads=1
# Ended (code 1) at Fri Jan 24 02:12:25 UTC 2020, elapsed time 4 seconds
```

**Comment by takeofuture** [comment]
Ex. In train_asrtts.yaml
use-speaker-embedding: false  # minues sign not under line
But in espnet/nets/pytorch_backend/e2e_asrtts.py
it uses args.use_speaker_embedding (under line not minus)
So some passing variables mismatch hapens as well as mismatch of variables

**Comment by xcrpkuss** [comment]
> 是的，这是一项实验功能，并且有很多更改。使此PR具有更常规的espnet功能是我们未来的重要工作之一。

When stage3: LM Preparation begin, it happened an error:
"run.pl: job failed, log is in exp/train_rnnlm_chainer_lm_word100/train.log"
and log said:
"bash: line 1: lm_train.py: command not found"
But I can find lm_train.py in espnet/bin/，how can I change this road?
