### ISSUE TITLE
Input frame lengths become shorter.....

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#15]
@ShigekiKarita 

old kaldi io
```
2017-12-15 18:52:53,217 (e2e_asr_attctc:770) INFO: VGG2L input lengths: [1162 1162 1162 1162 1162 1162 1162 1162 1162 1162 1162 1162 1162 1162 1162]
2017-12-15 18:52:54,578 (e2e_asr_attctc:699) INFO: BLSTMP input lengths: [291 291 291 291 291 291 291 291 291 291 291 291 291 291 291]
2017-12-15 18:52:55,201 (e2e_asr_attctc:239) INFO: CTC input lengths:  [291 291 291 291 291 291 291 291 291 291 291 291 291 291 291]
2017-12-15 18:52:55,201 (e2e_asr_attctc:240) INFO: CTC output lengths: [147 133 136 130 150 140 143 128 139 146 154 130 144 104 135]
2017-12-15 18:52:56,377 (e2e_asr_attctc:244) INFO: ctc loss:878.386901855
2017-12-15 18:52:56,382 (e2e_asr_attctc:427) INFO: Decoder input lengths:  [291 291 291 291 291 291 291 291 291 291 291 291 291 291 291]
2017-12-15 18:52:56,383 (e2e_asr_attctc:428) INFO: Decoder output lengths: [148 134 137 131 151 141 144 129 140 147 155 131 145 105 136]
2017-12-15 18:52:58,724 (e2e_asr_attctc:456) INFO: att loss:549.235229492
2017-12-15 18:52:58,748 (e2e_asr_attctc:471) INFO: groundtruth[0]: FOR CHRISTMAS LAST YEAR HE GAVE ALL SEVENTY EMPLOYEES VIDEOCASSETTE RECORDERS AND SET UP A FREE VIDEO LIBRARY WITH ONE THOUSAND FIVE HUNDRED MOVIES<eos>
```

new kaldi io
```
2017-12-15 18:59:11,724 (e2e_asr_attctc:770) INFO: VGG2L input lengths: [784 784 784 784 784 784 784 784 784 784 784 784 784 784 784]
2017-12-15 18:59:12,722 (e2e_asr_attctc:699) INFO: BLSTMP input lengths: [196 196 196 196 196 196 196 196 196 196 196 196 196 196 196]
2017-12-15 18:59:13,120 (e2e_asr_attctc:239) INFO: CTC input lengths:  [196 196 196 196 196 196 196 196 196 196 196 196 196 196 196]
2017-12-15 18:59:13,120 (e2e_asr_attctc:240) INFO: CTC output lengths: [147 133 136 130 150 140 143 128 139 146 154 130 144 104 135]
2017-12-15 18:59:13,879 (e2e_asr_attctc:244) INFO: ctc loss:630.451171875
2017-12-15 18:59:13,885 (e2e_asr_attctc:427) INFO: Decoder input lengths:  [196 196 196 196 196 196 196 196 196 196 196 196 196 196 196]
2017-12-15 18:59:13,885 (e2e_asr_attctc:428) INFO: Decoder output lengths: [148 134 137 131 151 141 144 129 140 147 155 131 145 105 136]
2017-12-15 18:59:24,061 (e2e_asr_attctc:456) INFO: att loss:549.195800781
2017-12-15 18:59:25,978 (e2e_asr_attctc:471) INFO: groundtruth[0]: FOR CHRISTMAS LAST YEAR HE GAVE ALL SEVENTY EMPLOYEES VIDEOCASSETTE RECORDERS AND SET UP A FREE VIDEO LIBRARY WITH ONE THOUSAND FIVE H
UNDRED MOVIES<eos>

```

**Comment by ShigekiKarita** [comment]
oh. I will check the usage of new kaldi_io again.

**Comment by kan-bayashi** [comment]
Hi. I tried voxforge recipe.
It works, but maybe due to this problem, the performace decreased.
```
# old version
        "validation/main/loss": 44.54685974121094,
        "main/loss": 8.515864372253418,
        "main/loss_ctc": 12.448214530944824,
        "iteration": 3700,
        "eps": 1e-08,
        "main/loss_att": 4.583513259887695,
        "validation/main/loss_att": 32.93996810913086,
        "elapsed_time": 11491.847963809967,
        "epoch": 11,
        "validation/main/acc": 0.8781912922859192,
        "main/acc": 0.9845150113105774,
        "validation/main/loss_ctc": 56.15373992919922
# new version
        "validation/main/loss": 154.50262451171875,
        "main/loss": 135.95709228515625,
        "main/loss_ctc": 191.64755249023438,
        "iteration": 3700,
        "eps": 1e-14,
        "main/loss_att": 80.26673126220703,
        "validation/main/loss_att": 110.86762237548828,
        "elapsed_time": 8474.819000005722,
        "epoch": 11,
        "validation/main/acc": 0.5316960215568542,
        "main/acc": 0.6676390767097473,
        "validation/main/loss_ctc": 198.1376495361328
```

**Comment by kan-bayashi** [comment]
`asr_recog.py` does not work.
```
# asr_recog.py --gpu -1 --recog-feat "ark,s,cs:apply-cmvn --norm-vars=true data/tr_it/cmvn.ark scp:data/dt_it/split32utt/1/f
eats.scp ark:- |" --recog-label data/dt_it/data.json --result-label exp/tr_it_vggblstmp_e4_subsample1_2_2_1_1_unit320_proj32
0_d1_unit300_location_aconvc10_aconvf100_mtlalpha0.5_adadelta_bs30_mli800_mlo150/decode_dt_it_beam20_eacc.best_p0_len0.0-0.8
/data.1.json --model exp/tr_it_vggblstmp_e4_subsample1_2_2_1_1_unit320_proj320_d1_unit300_location_aconvc10_aconvf100_mtlalp
ha0.5_adadelta_bs30_mli800_mlo150/results/model.acc.best --model-conf exp/tr_it_vggblstmp_e4_subsample1_2_2_1_1_unit320_proj
320_d1_unit300_location_aconvc10_aconvf100_mtlalpha0.5_adadelta_bs30_mli800_mlo150/results/model.conf --beam-size 20 --penal
ty 0 --maxlenratio 0.8 --minlenratio 0.0
CUDA_VISIBLE_DEVICES set to NoDevFiles, unsetting it...
2017-12-16 22:03:42,353 (asr_recog:68) WARNING: Skip DEBUG/INFO messages
2017-12-16 22:03:42,353 (asr_recog:71) INFO: python path = /work3/t_hayashi/work/espnet_debug/egs/voxforge/asr1/../../../src
/nets/:/work3/t_hayashi/work/espnet_debug/egs/voxforge/asr1/../../../src/utils/:/work3/t_hayashi/work/espnet_debug/egs/voxfo
rge/asr1/../../../src/bin/:
2017-12-16 22:03:42,353 (asr_recog:74) INFO: chainer version = 3.2.0
2017-12-16 22:03:42,354 (asr_recog:81) INFO: chainer seed = 1
2017-12-16 22:03:42,354 (asr_recog:85) INFO: reading a model config file fromexp/tr_it_vggblstmp_e4_subsample1_2_2_1_1_unit320_proj320_d1_unit300_location_aconvc10_aconvf100_mtlalpha0.5_adadelta_bs30_mli800_mlo150/results/model.conf
2017-12-16 22:03:42,356 (asr_recog:89) INFO: ARGS: beam_size: 20
2017-12-16 22:03:42,356 (asr_recog:89) INFO: ARGS: debugmode: 1
2017-12-16 22:03:42,356 (asr_recog:89) INFO: ARGS: gpu: -1
2017-12-16 22:03:42,356 (asr_recog:89) INFO: ARGS: maxlenratio: 0.8
2017-12-16 22:03:42,356 (asr_recog:89) INFO: ARGS: minlenratio: 0.0
2017-12-16 22:03:42,356 (asr_recog:89) INFO: ARGS: model: exp/tr_it_vggblstmp_e4_subsample1_2_2_1_1_unit320_proj320_d1_unit300_location_aconvc10_aconvf100_mtlalpha0.5_adadelta_bs30_mli800_mlo150/results/model.acc.best
2017-12-16 22:03:42,357 (asr_recog:89) INFO: ARGS: model_conf: exp/tr_it_vggblstmp_e4_subsample1_2_2_1_1_unit320_proj320_d1_unit300_location_aconvc10_aconvf100_mtlalpha0.5_adadelta_bs30_mli800_mlo150/results/model.conf
2017-12-16 22:03:42,357 (asr_recog:89) INFO: ARGS: penalty: 0.0
2017-12-16 22:03:42,357 (asr_recog:89) INFO: ARGS: recog_feat: ark,s,cs:apply-cmvn --norm-vars=true data/tr_it/cmvn.ark scp:data/dt_it/split32utt/1/feats.scp ark:- |
2017-12-16 22:03:42,357 (asr_recog:89) INFO: ARGS: recog_label: data/dt_it/data.json
2017-12-16 22:03:42,357 (asr_recog:89) INFO: ARGS: result_label: exp/tr_it_vggblstmp_e4_subsample1_2_2_1_1_unit320_proj320_d1_unit300_location_aconvc10_aconvf100_mtlalpha0.5_adadelta_bs30_mli800_mlo150/decode_dt_it_beam20_eacc.best_p0_len0.0-0.8/data.1.json
2017-12-16 22:03:42,357 (asr_recog:89) INFO: ARGS: seed: 1
2017-12-16 22:03:42,357 (asr_recog:89) INFO: ARGS: verbose: 1
2017-12-16 22:03:42,357 (asr_recog:92) INFO: reading model parameters fromexp/tr_it_vggblstmp_e4_subsample1_2_2_1_1_unit320_proj320_d1_unit300_location_aconvc10_aconvf100_mtlalpha0.5_adadelta_bs30_mli800_mlo150/results/model.acc.best
2017-12-16 22:03:42,358 (e2e_asr_attctc:118) WARNING: Subsampling is not performed for vgg*. It is performed in max pooling layers at CNN.
2017-12-16 22:03:42,358 (e2e_asr_attctc:119) INFO: subsample: 1 1 1 1 1
2017-12-16 22:03:43,905 (e2e_asr_attctc:641) INFO: Use CNN-VGG + BLSTMP for encoder
apply-cmvn --norm-vars=true data/tr_it/cmvn.ark scp:data/dt_it/split32utt/1/feats.scp ark:-
Traceback (most recent call last):
  File "/work3/t_hayashi/work/espnet_debug/egs/voxforge/asr1/../../../src/bin/asr_recog.py", line 131, in <module>
ERROR (apply-cmvn[5.2.206~1-9e764]:Write():kaldi-matrix.cc:1255) Failed to write matrix to stream

[ Stack-Trace: ]

kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
kaldi::MatrixBase<float>::Write(std::ostream&, bool) const
kaldi::KaldiObjectHolder<kaldi::Matrix<float> >::Write(std::ostream&, bool, kaldi::Matrix<float> const&)
kaldi::TableWriterArchiveImpl<kaldi::KaldiObjectHolder<kaldi::Matrix<float> > >::Write(std::string const&, kaldi::Matrix<float> const&)
kaldi::TableWriter<kaldi::KaldiObjectHolder<kaldi::Matrix<float> > >::Write(std::string const&, kaldi::Matrix<float> const&) const
main
__libc_start_main
apply-cmvn() [0x447029]

WARNING (apply-cmvn[5.2.206~1-9e764]:Write():util/kaldi-holder-inl.h:55) Exception caught writing Table object.
WARNING (apply-cmvn[5.2.206~1-9e764]:Write():util/kaldi-table-inl.h:1057) Write failure to standard output
ERROR (apply-cmvn[5.2.206~1-9e764]:Write():util/kaldi-table-inl.h:1515) Error in TableWriter::Write

[ Stack-Trace: ]

kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
kaldi::TableWriter<kaldi::KaldiObjectHolder<kaldi::Matrix<float> > >::Write(std::string const&, kaldi::Matrix<float> const&) const
main
__libc_start_main
apply-cmvn() [0x447029]

WARNING (apply-cmvn[5.2.206~1-9e764]:Close():util/kaldi-table-inl.h:1089) Error closing stream: wspecifier is ark:-
ERROR (apply-cmvn[5.2.206~1-9e764]:~TableWriter():util/kaldi-table-inl.h:1539) Error closing TableWriter [in destructor].

[ Stack-Trace: ]

kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
kaldi::TableWriter<kaldi::KaldiObjectHolder<kaldi::Matrix<float> > >::~TableWriter()
main
__libc_start_main
apply-cmvn() [0x447029]

    main()
  File "/work3/t_hayashi/work/espnet_debug/egs/voxforge/asr1/../../../src/bin/asr_recog.py", line 98, in main
    reader = lazy_io.read_dict_scp(args.recog_feat)
  File "/work3/t_hayashi/work/espnet_debug/src/utils/lazy_io.py", line 31, in read_dict_scp
    (key,rxfile) = line.decode().split(' ')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 43: ordinal not in range(128)
# Accounting: begin_time=1513429404
# Accounting: end_time=
# Accounting: time=-1513429404 threads=1
# Finished at Sat Dec 16 22:03:47 JST 2017 with status 1
```

**Comment by ShigekiKarita** [comment]
@sw005320 @kan-bayashi I'm stack in installing kaldi-python, especially boost-python part. Could you tell me your boost version?? I'm using boost 1.65.1 now.

**Comment by ShigekiKarita** [comment]
I've just solved that problem when I configure boost as follows:
``` console
$ cd ./boost_1_65_1
$ source ~/miniconda2/bin/activate espnet
$ ./bootstrap.sh --with-libraries=python --with-python=python --with-python-version=2.7
$ ./b2 --with-python -j4
```

**Comment by ShigekiKarita** [comment]
I finally figure out what is wrong. That is Python's lambda. It is beyond my understanding http://math.andrej.com/2009/04/09/pythons-lambda-is-broken/

I rewrite lazy_io.py much simpler without lambda as follows (NOTE: kaldi_io_py is a alias for kaldi-io-for-python)
``` python
from kaldi_io_py import open_or_fd, read_mat


class ScpLazyDict(object):
    def __init__(self, rxfile_dict):
        self.rxfile_dict = rxfile_dict

    def __getitem__(self, item):
        return read_mat(self.rxfile_dict[str(item)])


def read_dict_scp(file_or_fd):
    """ generator(key,mat) = read_mat_scp(file_or_fd)
    Returns generator of (key,matrix) tuples, read according to kaldi scp.
    file_or_fd : scp, gzipped scp, pipe or opened file descriptor.
    Iterate the scp:
    for key,mat in kaldi_io.read_mat_scp(file):
     ...
    Read scp to a 'dictionary':
    d = { key:mat for key,mat in kaldi_io.read_mat_scp(file) }
    """
    fd = open_or_fd(file_or_fd)
    d = dict()
    try:
        for line in fd:
            # for example
            # key: 'sergiopin-20160506-gqk-it-1135'
            # rxfile : '/espnet/egs/voxforge/asr1/fbank/raw_fbank_pitch_all_it.10.ark:45527891\n'
            (key,rxfile) = str(line).split(' ')
            d[key] = rxfile  # e.g., 
    finally:
        if fd is not file_or_fd : fd.close()
    return ScpLazyDict(d)
```

here is a test code with voxforge scp 
``` python
# coding: utf-8
import numpy
import kaldi_io
import kaldi_io_py
import lazy_io

train_scp = "scp:egs/voxforge/asr1/data/tr_it/feats.scp"

r1 = kaldi_io_py.read_mat_scp(train_scp)
r2 = kaldi_io.RandomAccessBaseFloatMatrixReader(train_scp)
r3 = lazy_io.read_dict_scp(train_scp)

for k, v1 in r1:
    k = str(k)
    print(k)
    v2 = r2[k]
    v3 = r3[k]
    assert v1.shape == v2.shape
    assert v1.shape == v3.shape
    numpy.testing.assert_allclose(v1, v2, atol=1e-5)  # NOTE
    numpy.testing.assert_allclose(v1, v3, atol=0)
```

I have no idea why the outputs of kaldi-python and kaldi-io-python are different in atol=1e-5.
But these plot looks not bad.

- kaldi-python
![kio](https://user-images.githubusercontent.com/6745326/34072539-7203e0e8-e2cc-11e7-9eff-f1dc2932d4db.png)

- kaldi-io-for-python
![kip](https://user-images.githubusercontent.com/6745326/34072540-75ecf2b2-e2cc-11e7-9edb-206f4a4d4b87.png)

**Comment by ShigekiKarita** [comment]
I also rerun voxforge exp

+ with kaldi_io

```
INFO: VGG2L input lengths: [686 
686 686 686 686 686 686 686 686 686 686 686 686 686 686 686 686 686
 686 686 686 686 686 686 686 686 686 686 686 686]
2017-12-17 02:53:00,188 (e2e_asr_attctc:699) INFO: BLSTMP input lengths: [172 172 172 172 172 172 172 172 172 172 172 172 172 172 172 172 172 172
 172 172 172 172 172 172 172 172 172 172 172 172]
2017-12-17 02:53:03,748 (e2e_asr_attctc:239) INFO: CTC input lengths:  [172 172 172 172 172 172 172 172 172 172 172 172 172 172 172 172 172 172
 172 172 172 172 172 172 172 172 172 172 172 172]
2017-12-17 02:53:03,748 (e2e_asr_attctc:240) INFO: CTC output lengths: [ 64  70 109  87  84  60  72  71  79  65  62  75  67  67  78  61  74  63
  76  64  66  85  74  63  79  97  61  69  83  72]
2017-12-17 02:53:09,234 (e2e_asr_attctc:244) INFO: ctc loss:468.530914307
2017-12-17 02:53:09,236 (e2e_asr_attctc:427) INFO: Decoder input lengths:  [172 172 172 172 172 172 172 172 172 172 172 172 172 172 172 172 172 172
 172 172 172 172 172 172 172 172 172 172 172 172]
2017-12-17 02:53:09,237 (e2e_asr_attctc:428) INFO: Decoder output lengths: [ 65  71 110  88  85  61  73  72  80  66  63  76  68  68  79  62  75  64
  77  65  67  86  75  64  80  98  62  70  84  73]
2017-12-17 02:53:14,027 (e2e_asr_attctc:456) INFO: att loss:268.310546875
2017-12-17 02:53:14,028 (e2e_asr_attctc:471) INFO: groundtruth[0]: LO LEGHERÒ COSÍ BENE CHE NON POTRÀ FARE IL PIÚ PICCOLO MOVIMENTO<eos>
2017-12-17 02:53:14,028 (e2e_asr_attctc:472) INFO: prediction [0]: R<blank>WX<blank>1ÒG1ZÀXTÀÀNXÚÚÚÚÚTT1ÚÚÚWGÚGÚEÒXZBBZÚÚKÚPÚÚÚNP11P1SX1WWÚ11WJJ
```

+ with lazy_io

```
2017-12-17 02:49:21,257 (e2e_asr_attctc:770) INFO: VGG2L input lengths: [686 
686 686 686 686 686 686 686 686 686 686 686 686 686 686 686 686 686
 686 686 686 686 686 686 686 686 686 686 686 686]
2017-12-17 02:49:39,507 (e2e_asr_attctc:699) INFO: BLSTMP input lengths: [172 172 172 172 172 172 172 172 172 172 172 172 172 172 172 172 172 172
 172 172 172 172 172 172 172 172 172 172 172 172]
2017-12-17 02:49:43,159 (e2e_asr_attctc:239) INFO: CTC input lengths:  [172 172 172 172 172 172 172 172 172 172 172 172 172 172 172 172 172 172
 172 172 172 172 172 172 172 172 172 172 172 172]
2017-12-17 02:49:43,159 (e2e_asr_attctc:240) INFO: CTC output lengths: [ 64  70 109  87  84  60  72  71  79  65  62  75  67  67  78  61  74  63
  76  64  66  85  74  63  79  97  61  69  83  72]
2017-12-17 02:49:48,906 (e2e_asr_attctc:244) INFO: ctc loss:468.530914307
2017-12-17 02:49:48,909 (e2e_asr_attctc:427) INFO: Decoder input lengths:  [172 172 172 172 172 172 172 172 172 172 172 172 172 172 172 172 172 172
 172 172 172 172 172 172 172 172 172 172 172 172]
2017-12-17 02:49:48,909 (e2e_asr_attctc:428) INFO: Decoder output lengths: [ 65  71 110  88  85  61  73  72  80  66  63  76  68  68  79  62  75  64
  77  65  67  86  75  64  80  98  62  70  84  73]
2017-12-17 02:49:53,527 (e2e_asr_attctc:456) INFO: att loss:268.310546875
2017-12-17 02:49:53,528 (e2e_asr_attctc:471) INFO: groundtruth[0]: LO LEGHERÒ COSÍ BENE CHE NON POTRÀ FARE IL PIÚ PICCOLO MOVIMENTO<eos>
2017-12-17 02:49:53,528 (e2e_asr_attctc:472) INFO: prediction [0]: R<blank>WX<blank>1ÒG1ZÀXTÀÀNXÚÚÚÚÚTT1ÚÚÚWGÚGÚEÒXZBBZÚÚKÚPÚÚÚNP11P1SX1WWÚ11WJJ
```

I will test asr_recog.py after this training. As @kan-bayashi reported,  there seems to be some unicode problems in previous code.

**Comment by sw005320** [comment]
Thanks Shigeki.
Once you finish it, please PR it.

**Comment by ShigekiKarita** [comment]
@sw005320 if you are OK, please close this issue
