### ISSUE TITLE
New argument `embed_unit` in language model breaks an4 recipe

### ISSUE THREAD

**Issue by qmeeus** [espnet/espnet#1638]
Following [this commit](https://github.com/espnet/espnet/commit/943c9933fc047133a1ba8adc07be79957416316e):
```
Traceback (most recent call last):
  File "/users/spraak/qmeeus/spchdisk/repos/espnet/espnet/bin/asr_recog.py", line 208, in <module>
    main(sys.argv[1:])
  File "/users/spraak/qmeeus/spchdisk/repos/espnet/espnet/bin/asr_recog.py", line 190, in main
    recog(args)
  File "/esat/spchdisk/scratch/qmeeus/repos/espnet/espnet/asr/pytorch_backend/asr.py", line 664, in recog
    len(word_dict), rnnlm_args.layer, rnnlm_args.unit, rnnlm_args.embed_unit))
AttributeError: 'Namespace' object has no attribute 'embed_unit'
```
This is happening for recipe `an4/asr1` but I suspect that it is causing more issues in other recipes

**Comment by sw005320** [comment]
Did it happen even you train it from scratch?

**Comment by qmeeus** [comment]
No you are right, when trained from scratch the error disappears, thanks for the pointer !
