### ISSUE TITLE
installation error at bandmat

### ISSUE THREAD

**Issue by michael1b** [espnet/espnet#1642]
Hi, I'm trying to install `espnet` with the following command

```
make KALDI=~/kaldi/ PYTHON=~/.pyenv/versions/3.6.8/envs/espnet_env/bin/python3.6 CUPY_VERSION='' -j 4
```
And came across this error

```
Collecting bandmat>=0.7
  Using cached bandmat-0.7.tar.gz (364 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/michael-perc/espnet/tools/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hly80m0j/bandmat/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hly80m0j/bandmat/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-hly80m0j/bandmat/pip-egg-info
         cwd: /tmp/pip-install-hly80m0j/bandmat/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hly80m0j/bandmat/setup.py", line 10, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Makefile:55: recipe for target 'espnet.done' failed
make: *** [espnet.done] Error 1
```

I installed the `numpy` package and checked if it was successful just by opening python and importing the library. But when I ran the same command above, I still get the same error. Please help, I don't know what I missed.

PS. I'm following this installation guide: [LINK](https://espnet.github.io/espnet/installation.html)

**Comment by sw005320** [comment]
Could you test it without `PYTHON=~/.pyenv/versions/3.6.8/envs/espnet_env/bin/python3.6`? This option is intended for the system python.

**Comment by rdevans0** [comment]
I am also getting this issue with a system installed python and the default installation guide.

Make command:
```
cd espnet/tools
make KALDI=~/inst/kaldi PYTHON=/usr/bin/python3.6

    ...

    Collecting bandmat>=0.7
      Downloading bandmat-0.7.tar.gz (364 kB)
         |████████████████████████████████| 364 kB 57.2 MB/s 
        ERROR: Command errored out with exit status 1:
         command: /home/rdevans/tmp/espnet/tools/venv/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eo1114da/bandmat/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eo1114da/bandmat/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-eo1114da/bandmat/pip-egg-info
             cwd: /tmp/pip-install-eo1114da/bandmat/
        Complete output (5 lines):
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-install-eo1114da/bandmat/setup.py", line 10, in <module>
            import numpy as np
        ModuleNotFoundError: No module named 'numpy'


```

System configuration:
```
uname -a; cat /etc/lsb-release; python -V; python3 -V; python3.6 -V

    Linux MyComputer 4.4.0-171-generic #200-Ubuntu SMP Tue Dec 3 11:04:55 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=16.04
    DISTRIB_CODENAME=xenial
    DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
    Python 2.7.12
    Python 3.5.2
    Python 3.6.10
```

**Comment by rdevans0** [comment]
I've circumvented this issue by manually installing numpy in the venv before main installation. It looks like there is an issue where using a non-default python leads to not installing numpy first from from the setup_requirements (setup.py). 

Temporary fix:
```
sudo apt-get install python3.6 python3.6-dev   # python3.6-dev is also required
cd espnet/tools
make KALDI=~/inst/kaldi PYTHON=/usr/bin/python3.6 venv
. venv/bin/activate
pip install numpy
deactivate
make KALDI=~/inst/kaldi PYTHON=/usr/bin/python3.6
```

**Comment by sw005320** [comment]
Thanks for your TIPS.
We could not fully support all environments (especially system python since it highly depends on their own environments), and recommend `conda` based installation instead.

**Comment by michael1b** [comment]
> Could you test it without `PYTHON=~/.pyenv/versions/3.6.8/envs/espnet_env/bin/python3.6`? This option is intended for the system python.

Ah, if I do this then it will proceed with the `conda`-based installation.

And if I do the same thing that rdevans0 did:

`make KALDI=/path/to/kaldi PYTHON=/usr/bin/python3.6`

I get the same problem. It seems that if I identify the locally-installed python, the packages are still downloaded into the `/usr/bin/python3.6` in the `espnet` directory. However that same directory does not include `numpy`. As a work-around, I copied the numpy-related directory from my locally-installed python to the python directory in `espnet` and the installation proceeded.

I was able to try the `asr` and `tts` demos. Example below

```
michael-perc@michaelperc-Aspire-E5-575:~/espnet/egs/ljspeech/tts1$ echo "THIS IS A DEMO" > example.txt
michael-perc@michaelperc-Aspire-E5-575:~/espnet/egs/ljspeech/tts1$ ../../../utils/synth_wav.sh example.txt 
--2020-03-06 11:38:08--  https://drive.google.com/uc?export=download&id=13DR-RB5wrbMqBGx_MC655VZlsEq52DyS
Resolving drive.google.com (drive.google.com)... 172.217.194.102, 172.217.194.101, 172.217.194.139, ...
Connecting to drive.google.com (drive.google.com)|172.217.194.102|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: 'decode/download/ljspeech.transformer.v1/xYtMp7..tar.gz'

decode/download/ljspeech.transformer.v1/xYtMp7..ta     [ <=>                                                                                                             ]   3.24K  --.-KB/s    in 0s      

2020-03-06 11:38:09 (15.8 MB/s) - 'decode/download/ljspeech.transformer.v1/xYtMp7..tar.gz' saved [3316]


gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3316    0  3316    0     0   6865      0 --:--:-- --:--:-- --:--:--  6851
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   408    0   408    0     0    886      0 --:--:-- --:--:-- --:--:--   886
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100  106M    0  106M    0     0  3664k      0 --:--:--  0:00:29 --:--:-- 3972k
conf/tuning/train_pytorch_transformer.v1.yaml
conf/decode.yaml
data/train_no_dev/cmvn.ark
exp/train_no_dev_pytorch_train_pytorch_transformer.v1/results/model.last1.avg.best
exp/train_no_dev_pytorch_train_pytorch_transformer.v1/results/model.json
data/lang_1char/train_no_dev_units.txt
Sucessfully downloaded zip file from https://drive.google.com/open?id=13DR-RB5wrbMqBGx_MC655VZlsEq52DyS
stage 0: Data preparation
/home/michael-perc/espnet/egs/ljspeech/tts1/../../../utils/data2json.sh --trans_type char decode/example/data decode/download/ljspeech.transformer.v1/data/lang_1char/train_no_dev_units.txt
stage 2: Decoding
stage 3: Synthesis with Griffin-Lim
apply-cmvn --norm-vars=true --reverse=true decode/download/ljspeech.transformer.v1/data/train_no_dev/cmvn.ark scp:decode/example/outputs/feats.scp ark,scp:decode/example/outputs_denorm/feats.ark,decode/example/outputs_denorm/feats.scp 
LOG (apply-cmvn[5.5.660~1-6a21b]:main():apply-cmvn.cc:159) Applied cepstral mean and variance normalization to 1 utterances, errors on 0
/home/michael-perc/espnet/egs/ljspeech/tts1/../../../utils/convert_fbank.sh --nj 1 --cmd run.pl --fs 22050 --fmax  --fmin  --n_fft 1024 --n_shift 256 --win_length  --n_mels 80 --iters 64 decode/example/outputs_denorm decode/example/log decode/example/wav
Succeeded creating wav for outputs_denorm

Synthesized wav: decode/example/wav/example.wav

Finished
stage 4: Synthesis with Neural Vocoder
--2020-03-06 11:38:52--  https://drive.google.com/uc?export=download&id=1tv9GKyRT4CDsvUWKwH3s_OfXkiTi0gw7
Resolving drive.google.com (drive.google.com)... 172.217.194.100, 172.217.194.138, 172.217.194.113, ...
Connecting to drive.google.com (drive.google.com)|172.217.194.100|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://doc-10-30-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/s93qu70a90qba4rg1477hr92t58tj5h0/1583465925000/04214513489132088126/*/1tv9GKyRT4CDsvUWKwH3s_OfXkiTi0gw7?e=download [following]
Warning: wildcards not supported in HTTP.
--2020-03-06 11:38:54--  https://doc-10-30-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/s93qu70a90qba4rg1477hr92t58tj5h0/1583465925000/04214513489132088126/*/1tv9GKyRT4CDsvUWKwH3s_OfXkiTi0gw7?e=download
Resolving doc-10-30-docs.googleusercontent.com (doc-10-30-docs.googleusercontent.com)... 142.250.4.132, 2404:6800:4003:c06::84
Connecting to doc-10-30-docs.googleusercontent.com (doc-10-30-docs.googleusercontent.com)|142.250.4.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: 'decode/download/ljspeech.parallel_wavegan.v1/qC1PtZ..tar.gz'

decode/download/ljspeech.parallel_wavegan.v1/qC1Pt     [                 <=>                                                                                             ]  14.89M  4.22MB/s    in 3.6s    

2020-03-06 11:38:58 (4.09 MB/s) - 'decode/download/ljspeech.parallel_wavegan.v1/qC1PtZ..tar.gz' saved [15609641]

ljspeech.parallel_wavegan.v1/
ljspeech.parallel_wavegan.v1/stats.h5
ljspeech.parallel_wavegan.v1/checkpoint-400000steps.pkl
ljspeech.parallel_wavegan.v1/config.yml
Sucessfully downloaded zip file from https://drive.google.com/open?id=1tv9GKyRT4CDsvUWKwH3s_OfXkiTi0gw7
Collecting parallel-wavegan
  Downloading parallel_wavegan-0.3.1.post1.tar.gz (37 kB)
Collecting torch>=1.0.1
  Downloading torch-1.4.0-cp36-cp36m-manylinux1_x86_64.whl (753.4 MB)
     |████████████████████████████████| 753.4 MB 11 kB/s 
Requirement already satisfied: setuptools>=38.5.1 in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from parallel-wavegan) (45.2.0)
Requirement already satisfied: librosa>=0.7.0 in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from parallel-wavegan) (0.7.2)
Requirement already satisfied: soundfile>=0.10.2 in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from parallel-wavegan) (0.10.3.post1)
Requirement already satisfied: tensorboardX>=1.8 in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from parallel-wavegan) (2.0)
Requirement already satisfied: matplotlib>=3.1.0 in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from parallel-wavegan) (3.2.0)
Requirement already satisfied: PyYAML>=3.12 in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from parallel-wavegan) (5.3)
Requirement already satisfied: tqdm>=4.26.1 in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from parallel-wavegan) (4.43.0)
Requirement already satisfied: kaldiio>=2.14.1 in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from parallel-wavegan) (2.15.1)
Collecting h5py>=2.10.0
  Downloading h5py-2.10.0-cp36-cp36m-manylinux1_x86_64.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 60 kB/s 
Collecting yq>=2.10.0
  Downloading yq-2.10.0-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: scipy>=1.0.0 in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from librosa>=0.7.0->parallel-wavegan) (1.3.3)
Requirement already satisfied: numpy>=1.15.0 in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from librosa>=0.7.0->parallel-wavegan) (1.18.1)
Requirement already satisfied: audioread>=2.0.0 in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from librosa>=0.7.0->parallel-wavegan) (2.1.8)
Requirement already satisfied: joblib>=0.12 in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from librosa>=0.7.0->parallel-wavegan) (0.14.1)
Requirement already satisfied: numba>=0.43.0 in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from librosa>=0.7.0->parallel-wavegan) (0.48.0)
Requirement already satisfied: decorator>=3.0.0 in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from librosa>=0.7.0->parallel-wavegan) (4.4.2)
Requirement already satisfied: resampy>=0.2.2 in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from librosa>=0.7.0->parallel-wavegan) (0.2.2)
Requirement already satisfied: six>=1.3 in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from librosa>=0.7.0->parallel-wavegan) (1.14.0)
Requirement already satisfied: scikit-learn!=0.19.0,>=0.14.0 in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from librosa>=0.7.0->parallel-wavegan) (0.22.2.post1)
Requirement already satisfied: cffi>=1.0 in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from soundfile>=0.10.2->parallel-wavegan) (1.14.0)
Collecting protobuf>=3.8.0
  Downloading protobuf-3.11.3-cp36-cp36m-manylinux1_x86_64.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 3.2 kB/s 
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from matplotlib>=3.1.0->parallel-wavegan) (2.4.6)
Requirement already satisfied: python-dateutil>=2.1 in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from matplotlib>=3.1.0->parallel-wavegan) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from matplotlib>=3.1.0->parallel-wavegan) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from matplotlib>=3.1.0->parallel-wavegan) (0.10.0)
Collecting argcomplete>=1.8.1
  Downloading argcomplete-1.11.1-py2.py3-none-any.whl (36 kB)
Collecting xmltodict>=0.11.0
  Downloading xmltodict-0.12.0-py2.py3-none-any.whl (9.2 kB)
Requirement already satisfied: llvmlite<0.32.0,>=0.31.0dev0 in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from numba>=0.43.0->librosa>=0.7.0->parallel-wavegan) (0.31.0)
Requirement already satisfied: pycparser in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from cffi>=1.0->soundfile>=0.10.2->parallel-wavegan) (2.20)
Requirement already satisfied: importlib-metadata<2,>=0.23; python_version == "3.6" in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from argcomplete>=1.8.1->yq>=2.10.0->parallel-wavegan) (1.5.0)
Requirement already satisfied: zipp>=0.5 in /home/michael-perc/espnet/tools/venv/lib/python3.6/site-packages (from importlib-metadata<2,>=0.23; python_version == "3.6"->argcomplete>=1.8.1->yq>=2.10.0->parallel-wavegan) (3.1.0)
Building wheels for collected packages: parallel-wavegan
  Building wheel for parallel-wavegan (setup.py) ... done
  Created wheel for parallel-wavegan: filename=parallel_wavegan-0.3.1.post1-py3-none-any.whl size=41022 sha256=347d0cfce890504ecb21fd7231607f8a331c98ac4b368b72b46f66da007a6fd4
  Stored in directory: /home/michael-perc/.cache/pip/wheels/00/2d/8c/af83cdca08931b0aeca6bea6919e76d40ab614d670eb4f2386
Successfully built parallel-wavegan
ERROR: chainer 6.0.0 has requirement protobuf<3.8.0rc1,>=3.0.0, but you'll have protobuf 3.11.3 which is incompatible.
ERROR: espnet 0.6.2 has requirement h5py==2.9.0, but you'll have h5py 2.10.0 which is incompatible.
Installing collected packages: torch, h5py, argcomplete, xmltodict, yq, parallel-wavegan, protobuf
  Attempting uninstall: torch
    Found existing installation: torch 1.0.0
    Uninstalling torch-1.0.0:
      Successfully uninstalled torch-1.0.0
  Attempting uninstall: h5py
    Found existing installation: h5py 2.9.0
    Uninstalling h5py-2.9.0:
      Successfully uninstalled h5py-2.9.0
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.7.1
    Uninstalling protobuf-3.7.1:
      Successfully uninstalled protobuf-3.7.1
Successfully installed argcomplete-1.11.1 h5py-2.10.0 parallel-wavegan-0.3.1.post1 protobuf-3.11.3 torch-1.4.0 xmltodict-0.12.0 yq-2.10.0
2020-03-06 11:43:24,921 (decode:96) INFO: The feature loaded from decode/example/outputs/feats.scp.
2020-03-06 11:43:25,036 (decode:109) INFO: Loaded model parameters from decode/download/ljspeech.parallel_wavegan.v1/ljspeech.parallel_wavegan.v1/checkpoint-400000steps.pkl.
[decode]: 1it [00:02,  2.62s/it, RTF=1.44]
2020-03-06 11:43:27,696 (decode:142) INFO: Finished generation of 1 utterances (RTF = 1.444).

Synthesized wav: decode/example/wav_wnv/example.wav

Finished
```
