### ISSUE TITLE
Exception occurs in fastspeech tts when set reduction-factor=1

### ISSUE THREAD

**Issue by EsmaeilFarhang** [espnet/espnet#1773]
I try to use knowledge_dist fast speech(fastspeech.v4  and use transformer as a teacher mode), but in below config file when setting `reduction-factor=1` this exception occurs:
config_file:
```
# Config based on train_fastspeech.v2 + postnet.
# This configuration reuqires 1 gpu in the case of each gpu memory = 12GB.
# This configuration assumes that durations and features are already dumped,
# in other words, the training will be followed knowledge distilation manner.
# You need to additionaly specify pretrained teacher model path in `run.sh`
# if you want to use this configuration.

# network architecture related
model-module: espnet.nets.pytorch_backend.e2e_tts_fastspeech:FeedForwardTransformer
adim: 384
aheads: 2
elayers: 6
eunits: 1536
dlayers: 6
dunits: 1536
duration-predictor-layers: 2
duration-predictor-chans: 256
duration-predictor-kernel-size: 3
positionwise-layer-type: conv1d
positionwise-conv-kernel-size: 3
postnet-layers: 5
postnet-filts: 5
postnet-chans: 256
use-batch-norm: True
use-scaled-pos-enc: True
encoder-normalize-before: False
decoder-normalize-before: False
encoder-concat-after: False
decoder-concat-after: False
reduction-factor: 3

# minibatch related
# NOTE: the batch bins are carefully selected so that the average batch size will
# be 32 and it asummes the number of vocabularies is 77 (in phoneme case)
# If you want to use char input instead, you will need to tweak the batch-bin.
batch-sort-key: output # shuffle or input or output
batch-bins: 1921927    # 8 * (566.506 * 80 + 70.538 * 77)
                      # avg batch-size * (mean_out * dim_out + mean_in * dim_in)
                      # 1,636 batches containing from 4 to 37 samples (avg 7 samples).

# training related
transformer-init: pytorch
transformer-warmup-steps: 4000
transformer-lr: 1.0
initial-encoder-alpha: 1.0
initial-decoder-alpha: 1.0
transformer-enc-dropout-rate: 0.1
transformer-enc-positional-dropout-rate: 0.1
transformer-enc-attn-dropout-rate: 0.1
transformer-dec-dropout-rate: 0.1
transformer-dec-positional-dropout-rate: 0.1
transformer-dec-attn-dropout-rate: 0.1
transformer-enc-dec-attn-dropout-rate: 0.1
postnet-dropout-rate: 0.5
duration-predictor-dropout-rate: 0.1
transfer-encoder-from-teacher: false

# optimization related
opt: noam
accum-grad: 8
grad-clip: 1.0
weight-decay: 0.0
patience: 0
epochs: 1000  # 1000 epochs * 1,636 batches / 8 accum-grad = 204,500 iters
use-second-target: true # use precalculated durations

# other
num-iter-processes: 2
save-interval-epoch: 50
```
Exception;
```
[JException in main training loop: The size of tensor a (258) must match the size of tensor b (86) at non-singleton dimension 3
Traceback (most recent call last):
  File "/home/farhang/virtualenvironment/Train_Espnet/lib/python3.6/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/media/Archive3TB/Farhang/code/train_espnet/espnet/tts/pytorch_backend/tts.py", line 170, in update
    self.update_core()
  File "/media/Archive3TB/Farhang/code/train_espnet/espnet/tts/pytorch_backend/tts.py", line 150, in update_core
    loss = self.model(**x).mean() / self.accum_grad
  File "/home/farhang/virtualenvironment/Train_Espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/Archive3TB/Farhang/code/train_espnet/espnet/nets/pytorch_backend/e2e_tts_fastspeech.py", line 446, in forward
    xs, ilens, ys, olens, spembs=spembs, ds=extras, is_inference=False)
  File "/media/Archive3TB/Farhang/code/train_espnet/espnet/nets/pytorch_backend/e2e_tts_fastspeech.py", line 409, in _forward
    zs, _ = self.decoder(hs, h_masks)  # (B, Lmax, adim)
  File "/home/farhang/virtualenvironment/Train_Espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/Archive3TB/Farhang/code/train_espnet/espnet/nets/pytorch_backend/transformer/encoder.py", line 126, in forward
    xs, masks = self.encoders(xs, masks)
  File "/home/farhang/virtualenvironment/Train_Espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/Archive3TB/Farhang/code/train_espnet/espnet/nets/pytorch_backend/transformer/repeat.py", line 18, in forward
    args = m(*args)
  File "/home/farhang/virtualenvironment/Train_Espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/Archive3TB/Farhang/code/train_espnet/espnet/nets/pytorch_backend/transformer/encoder_layer.py", line 60, in forward
    x = residual + self.dropout(self.self_attn(x, x, x, mask))
  File "/home/farhang/virtualenvironment/Train_Espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/Archive3TB/Farhang/code/train_espnet/espnet/nets/pytorch_backend/transformer/attention.py", line 62, in forward
    scores = scores.masked_fill(mask, min_value)
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/media/Archive3TB/Farhang/code/train_espnet/egs/jsut/tts_fast_v4/../../../espnet/bin/tts_train.py", line 185, in <module>
    main(sys.argv[1:])
  File "/media/Archive3TB/Farhang/code/train_espnet/egs/jsut/tts_fast_v4/../../../espnet/bin/tts_train.py", line 179, in main
    train(args)
  File "/media/Archive3TB/Farhang/code/train_espnet/espnet/tts/pytorch_backend/tts.py", line 473, in train
    trainer.run()
  File "/home/farhang/virtualenvironment/Train_Espnet/lib/python3.6/site-packages/chainer/training/trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "/home/farhang/virtualenvironment/Train_Espnet/lib/python3.6/site-packages/six.py", line 696, in reraise
    raise value
  File "/home/farhang/virtualenvironment/Train_Espnet/lib/python3.6/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/media/Archive3TB/Farhang/code/train_espnet/espnet/tts/pytorch_backend/tts.py", line 170, in update
    self.update_core()
  File "/media/Archive3TB/Farhang/code/train_espnet/espnet/tts/pytorch_backend/tts.py", line 150, in update_core
    loss = self.model(**x).mean() / self.accum_grad
  File "/home/farhang/virtualenvironment/Train_Espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/Archive3TB/Farhang/code/train_espnet/espnet/nets/pytorch_backend/e2e_tts_fastspeech.py", line 446, in forward
    xs, ilens, ys, olens, spembs=spembs, ds=extras, is_inference=False)
  File "/media/Archive3TB/Farhang/code/train_espnet/espnet/nets/pytorch_backend/e2e_tts_fastspeech.py", line 409, in _forward
    zs, _ = self.decoder(hs, h_masks)  # (B, Lmax, adim)
  File "/home/farhang/virtualenvironment/Train_Espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/Archive3TB/Farhang/code/train_espnet/espnet/nets/pytorch_backend/transformer/encoder.py", line 126, in forward
    xs, masks = self.encoders(xs, masks)
  File "/home/farhang/virtualenvironment/Train_Espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/Archive3TB/Farhang/code/train_espnet/espnet/nets/pytorch_backend/transformer/repeat.py", line 18, in forward
    args = m(*args)
  File "/home/farhang/virtualenvironment/Train_Espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/Archive3TB/Farhang/code/train_espnet/espnet/nets/pytorch_backend/transformer/encoder_layer.py", line 60, in forward
    x = residual + self.dropout(self.self_attn(x, x, x, mask))
  File "/home/farhang/virtualenvironment/Train_Espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/Archive3TB/Farhang/code/train_espnet/espnet/nets/pytorch_backend/transformer/attention.py", line 62, in forward
    scores = scores.masked_fill(mask, min_value)
RuntimeError: The size of tensor a (258) must match the size of tensor b (86) at non-singleton dimension 3
```
I check the scripts can run with `reduction-factor=3`

**Comment by kan-bayashi** [comment]
This is because your teacher model is trained with `reduction-factor=3`.
You need to use the same `reduction-factor` for both teacher and fastspeech.
