### ISSUE TITLE
install of warpctc_pytorch and warprnnt_pytorch

### ISSUE THREAD

**Issue by zrsjta** [espnet/espnet#1802]
Hi！
when i am trying to install espnet, the installation of warpctc_pytorch and warprnnt_pytorch seems problematic. Here is the information

interpreter: 
`(base) [tyriontian@0b32827b-9545-469b-a768-73fc6c6297ad ~/espnet/espnet/tools]$ which python
~/espnet/espnet/tools/venv/bin/python`

linux os information:
`Linux version 4.14.105-1-tlinux3-0010 (root@TENCENT64.site) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC)) #1 SMP Mon Aug 12 17:13:26 CST 2019`

~/.bashrc:
`CUDAROOT=/usr/local/cuda-10.0

export PATH=$CUDAROOT/bin:$PATH
export LD_LIBRARY_PATH=$CUDAROOT/lib64:$LD_LIBRARY_PATH
export CFLAGS="-I$CUDAROOT/include $CFLAGS"
export CUDA_HOME=$CUDAROOT
export CUDA_PATH=$CUDAROOT`

check installation:
```
(base) [tyriontian@0b32827b-9545-469b-a768-73fc6c6297ad ~/espnet/espnet/tools]$ python check_install.py 
INFO: python version = 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]
INFO: library availableness check start.
INFO: # libraries to be checked = 9
INFO: --> espnet is installed.
INFO: --> kaldiio is installed.
INFO: --> matplotlib is installed.
INFO: --> torch is installed.
INFO: --> chainer is installed.
INFO: --> chainer_ctc is installed.
WARNING: --> warprnnt_pytorch is not installed.
INFO: --> cupy is installed.
WARNING: --> warpctc_pytorch is not installed.
INFO: library availableness check done.
INFO: 7 / 9 libraries are correctly installed.
INFO: please try to setup again and then re-run this script.
```

```
conda list:
libgcc_mutex             0.1                        main    defaults
absl-py                   0.9.0                    pypi_0    pypi
args                      0.1.0                    pypi_0    pypi
asn1crypto                1.3.0                    py37_0    defaults
attrs                     19.3.0                   pypi_0    pypi
audioread                 2.1.8                    pypi_0    pypi
blas                      1.0                         mkl    defaults
bottleneck                1.3.2            py37heb32a55_0    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2020.1.1                      0    defaults
cachetools                4.1.0                    pypi_0    pypi
certifi                   2020.4.5.1               py37_0    defaults
cffi                      1.14.0           py37h2e261b9_0    defaults
chainer                   6.0.0                    pypi_0    pypi
chainer-ctc               1.0                      pypi_0    pypi
chardet                   3.0.4                 py37_1003    defaults
click                     7.1.1                    pypi_0    pypi
clint                     0.5.1                    pypi_0    pypi
cmake                     3.14.0               h52cb24c_0    defaults
conda                     4.8.3                    py37_0    defaults
conda-package-handling    1.6.0            py37h7b6447c_0    defaults
configargparse            1.1                      pypi_0    pypi
cryptography              2.8              py37h1ba5d50_0    defaults
cudatoolkit               10.0.130                      0    defaults
cudnn                     7.6.5                cuda10.0_0    defaults
cupy-cuda100              6.0.0                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.16                  pypi_0    pypi
dataclasses               0.6                      pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
distance                  0.1.3                    pypi_0    pypi
editdistance              0.5.2                    pypi_0    pypi
espnet                    0.7.0                     dev_0    <develop>
espnet-tts-frontend       0.0.0                    pypi_0    pypi
expat                     2.2.6                he6710b0_0    defaults
fastdtw                   0.3.4                    pypi_0    pypi
fastrlock                 0.4                      pypi_0    pypi
ffmpeg                    4.2                  h167e202_0    conda-forge
filelock                  3.0.12                   pypi_0    pypi
freetype                  2.10.1               he06d7ca_0    conda-forge
g2p-en                    2.1.0                    pypi_0    pypi
gmp                       6.2.0                he1b5a44_2    conda-forge
gnutls                    3.6.5             hd3a4fd2_1002    conda-forge
google-auth               1.13.1                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
grpcio                    1.28.1                   pypi_0    pypi
h5py                      2.9.0                    pypi_0    pypi
humanfriendly             8.1                      pypi_0    pypi
idna                      2.9                        py_1    defaults
importlib-metadata        1.6.0                    pypi_0    pypi
inflect                   4.1.0                    pypi_0    pypi
intel-openmp              2020.0                      166    defaults
jaconv                    0.2.4                    pypi_0    pypi
joblib                    0.14.1                   pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
kaldiio                   2.15.1                   pypi_0    pypi
kiwisolver                1.2.0                    pypi_0    pypi
krb5                      1.17.1               h173b8e3_0    defaults
lame                      3.100             h14c3975_1001    conda-forge
languageflow              1.1.13a1                 pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libcurl                   7.69.1               h20c2e04_0    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libiconv                  1.15              h516909a_1006    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
librosa                   0.7.2                    pypi_0    pypi
libssh2                   1.9.0                h1ba5d50_1    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
llvmlite                  0.31.0                   pypi_0    pypi
mad                       0.15.1b              he1b5a44_0    conda-forge
markdown                  3.2.1                    pypi_0    pypi
matplotlib                3.2.1                    pypi_0    pypi
mkl                       2020.0                      166    defaults
mkl-service               2.3.0            py37he904b0f_0    defaults
mkl_fft                   1.0.15           py37ha843d7b_0    defaults
mkl_random                1.1.0            py37hd6b4f25_0    defaults
musdb                     0.3.1                    pypi_0    pypi
museval                   0.3.0                    pypi_0    pypi
nara-wpe                  0.0.7                    pypi_0    pypi
ncurses                   6.2                  he6710b0_0    defaults
nettle                    3.4.1             h1bed415_1002    conda-forge
ninja                     1.9.0            py37hfd86e86_0    defaults
nltk                      3.4.5                    pypi_0    pypi
nnmnkwii                  0.0.20                   pypi_0    pypi
numba                     0.48.0                   pypi_0    pypi
numpy                     1.18.1           py37h4f9e942_0    defaults
numpy-base                1.18.1           py37hde5b4d6_1    defaults
oauthlib                  3.1.0                    pypi_0    pypi
openh264                  1.8.0             hdbcaa40_1000    conda-forge
openssl                   1.1.1f               h7b6447c_0    defaults
pandas                    1.0.3                    pypi_0    pypi
pillow                    7.1.1                    pypi_0    pypi
pip                       20.0.2                   py37_1    anaconda
protobuf                  3.7.1                    pypi_0    pypi
pyaml                     20.4.0                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycosat                   0.6.3            py37h7b6447c_0    defaults
pycparser                 2.20                       py_0    defaults
pyopenssl                 19.1.0                   py37_0    defaults
pyparsing                 2.4.7                    pypi_0    pypi
pyrsistent                0.16.0                   pypi_0    pypi
pysocks                   1.7.1                    py37_0    defaults
pysptk                    0.1.18                   pypi_0    pypi
pystoi                    0.3.3                    pypi_0    pypi
python                    3.7.3                h0371630_0    defaults
python-crfsuite           0.9.6                    pypi_0    pypi
python-dateutil           2.8.1                    pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.0.1           cuda100py37he554f03_0    defaults
pytorch-wpe               0.0.0                    pypi_0    pypi
pytz                      2019.3                   pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
readline                  7.0                  h7b6447c_5    defaults
requests                  2.23.0                   py37_0    defaults
requests-oauthlib         1.3.0                    pypi_0    pypi
resampy                   0.2.2                    pypi_0    pypi
rhash                     1.3.8                h1ba5d50_0    defaults
rsa                       4.0                      pypi_0    pypi
ruamel_yaml               0.15.87          py37h7b6447c_0    defaults
scikit-learn              0.22.2.post1             pypi_0    pypi
scipy                     1.3.3                    pypi_0    pypi
sentencepiece             0.1.85                   pypi_0    pypi
setuptools                46.1.3                   py37_0    anaconda
simplejson                3.17.0                   pypi_0    pypi
six                       1.14.0                   py37_0    defaults
sklearn                   0.0                      pypi_0    pypi
soundfile                 0.10.3.post1             pypi_0    pypi
sox                       14.4.2            h27f72bc_1013    conda-forge
sqlite                    3.31.1               h7b6447c_0    defaults
stempeg                   0.1.8                    pypi_0    pypi
tabulate                  0.8.7                    pypi_0    pypi
tensorboard               2.2.0                    pypi_0    pypi
tensorboard-plugin-wit    1.6.0.post3              pypi_0    pypi
tensorboardx              2.0                      pypi_0    pypi
tk                        8.6.8                hbc83047_0    defaults
torch-complex             0.0.2                    pypi_0    pypi
tqdm                      4.44.1                     py_0    defaults
typeguard                 2.7.1                    pypi_0    pypi
typing                    3.7.4.1                  pypi_0    pypi
typing-extensions         3.7.4.2                  pypi_0    pypi
underthesea               1.1.17                   pypi_0    pypi
unidecode                 1.1.1                    pypi_0    pypi
urllib3                   1.25.8                   py37_0    defaults
warpctc-pytorch10-cuda100 0.1.3                    pypi_0    pypi
warprnnt-pytorch          0.1                      pypi_0    pypi
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.34.2                   py37_0    defaults
x264                      1!152.20180806       h14c3975_0    conda-forge
xz                        5.2.4                h14c3975_4    defaults
yaml                      0.1.7                had09818_2    defaults
zipp                      3.1.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3    defaults
```

though these two library exist in conda list, they cannot be imported:
```
(base) [tyriontian@0b32827b-9545-469b-a768-73fc6c6297ad ~/espnet/espnet/tools]$ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import warpctc_pytorch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tyriontian/espnet/espnet/tools/venv/lib/python3.7/site-packages/warpctc_pytorch/__init__.py", line 6, in <module>
    from ._warp_ctc import *
ImportError: /home/tyriontian/espnet/espnet/tools/venv/lib/python3.7/site-packages/warpctc_pytorch/_warp_ctc.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
>>> import warprnnt_pytorch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tyriontian/espnet/espnet/tools/venv/lib/python3.7/site-packages/warprnnt_pytorch-0.1-py3.7-linux-x86_64.egg/warprnnt_pytorch/__init__.py", line 6, in <module>
    from .warp_rnnt import *
ImportError: /home/tyriontian/espnet/espnet/tools/venv/lib/python3.7/site-packages/warprnnt_pytorch-0.1-py3.7-linux-x86_64.egg/warprnnt_pytorch/warp_rnnt.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
>>> 
```

I run the make file just with the default setting: make KALDI=path/to/kaldi. the kaldi is the latest version and is compiled successfully. There is also some problem with MakeFile when installing bottleneck, but i can install it manually with conda.
It seems that the two dependencies are installed but cannot be used. how can i get through this?  more information would be added if necessary thx!

**Comment by zrsjta** [comment]
`(base) [tyriontian@0b32827b-9545-469b-a768-73fc6c6297ad ~/espnet/espnet/tools]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/dockerdata/home/tyriontian/gcc/gcc-build-9.3.0/bin/../libexec/gcc/x86_64-pc-linux-gnu/9.3.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../gcc-9.3.0/configure --prefix=/home/tyriontian/gcc/gcc-build-9.3.0/ --with-gmp=/home/tyriontian/gcc/gmp-build-6.1.0/ --with-mpfr=/home/tyriontian/gcc/mpfr-build-3.1.4/ --with-mpc=/home/tyriontian/gcc/mpc-build-1.0.3/
Thread model: posix
gcc version 9.3.0 (GCC) `

**Comment by zrsjta** [comment]
I also try to install the warpctc_pytorch but it still does not work.
`(base) [tyriontian@0b32827b-9545-469b-a768-73fc6c6297ad ~/espnet/espnet/tools/warp-ctc]$ pip install warpctc-pytorch10-cuda100
Looking in indexes: https://mirrors.tencent.com/pypi/simple
Requirement already satisfied: warpctc-pytorch10-cuda100 in /dockerdata/home/tyriontian/espnet/espnet/tools/venv/lib/python3.7/site-packages (0.1.3)
(base) [tyriontian@0b32827b-9545-469b-a768-73fc6c6297ad ~/espnet/espnet/tools/warp-ctc]$ ls
CMakeLists.txt  LICENSE  README.md  ci  doc  include  pytorch_binding  src  tests
(base) [tyriontian@0b32827b-9545-469b-a768-73fc6c6297ad ~/espnet/espnet/tools/warp-ctc]$ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import warpctc_pytorch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tyriontian/espnet/espnet/tools/venv/lib/python3.7/site-packages/warpctc_pytorch/__init__.py", line 6, in <module>
    from ._warp_ctc import *
ImportError: /home/tyriontian/espnet/espnet/tools/venv/lib/python3.7/site-packages/warpctc_pytorch/_warp_ctc.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs`

**Comment by sw005320** [comment]
I'm not sure but it might be due to the gcc version due to 

```
Linux version 4.14.105-1-tlinux3-0010 (root@TENCENT64.site) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC)) #1 SMP Mon Aug 12 17:13:26 CST 2019
```

Could you try to use `gcc 4.9+`?
(I noticed that you list `gcc version 9.3.0` in your second post but the installation may use the system gcc)

**Comment by kan-bayashi** [comment]
Could you try this one?
https://github.com/espnet/espnet/issues/1656#issuecomment-601033168
After removing, could you try to install warpctc again?

**Comment by zrsjta** [comment]
> Could you try this one?
> [#1656 (comment)](https://github.com/espnet/espnet/issues/1656#issuecomment-601033168)
> After removing, could you try to install warpctc again?

I tried this but failed. I comment that line in `env.sh` (only one line there exactly), and re-log in my machine. The check_install.py still give the warnings that warpctc_pytorch and warprnnt_pytorch are not installed. I try to delete these two libraries in site-package manually and re-install warpctc_pytorch，the it still cannot be imported. I try to uninstall it by pip and re-install it but still failed. Finally I delete all things except KALDI, and ensure gcc is 9.3.0, cuda is 10.0, then run this makefile `make KALDI=root/to/kaldi` but the results are the same.

**Comment by zrsjta** [comment]
> I'm not sure but it might be due to the gcc version due to
> 
> ```
> Linux version 4.14.105-1-tlinux3-0010 (root@TENCENT64.site) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC)) #1 SMP Mon Aug 12 17:13:26 CST 2019
> ```
> 
> Could you try to use `gcc 4.9+`?
> (I noticed that you list `gcc version 9.3.0` in your second post but the installation may use the system gcc)

it may not be. the gcc is checked before installation by `gcc -v`. and the path of gcc is in my ~/.bashrc 
`export PATH="/home/tyriontian/gcc/gcc-build-9.3.0/bin:/home/tyriontian/gcc/gcc-build-9.3.0/lib:/home/tyriontian/gcc/gcc-build-9.3.0/lib64:$PATH"
export LD_LIBRARY_PATH="/home/tyriontian/gcc/gcc-build-9.3.0/lib:$LD_LIBRARY_PATH"`
Also, there are several insertions in the MakeFile, which would not allow my system gcc(4.8.5), and then the installation cannot get that further
Can we explicitly use the gcc 9.3 in the makefile? do some modification to ensure the gcc version?

**Comment by zrsjta** [comment]
here is the related file in conda:
`(base) [tyriontian@0b32827b-9545-469b-a768-73fc6c6297ad ~/espnet/espnet/tools/venv/lib/python3.7/site-packages]$ ls warp*
warpctc_pytorch:
__init__.py  __pycache__  _warp_ctc.cpython-37m-x86_64-linux-gnu.so  lib

warpctc_pytorch10_cuda100-0.1.3.dist-info:
INSTALLER  METADATA  RECORD  WHEEL  top_level.txt

warprnnt_pytorch-0.1-py3.7-linux-x86_64.egg:
EGG-INFO  warprnnt_pytorch`
i'm not sure if they are installed in right way.

**Comment by zrsjta** [comment]
could be problem be this?
I configure kaldi by cuda8.0 but the espnet is installed by cuda10.0. I don't know if both the ctc and rnnt warpper of pytorch is kaldi-based? if so, that could be the problem.
but when i try to configure kaldi with cuda10.0, it reports:

``***configure failed: CUDA 10_0 does not support g++ (g++-9.3.0).
                 You need g++ < 8.0. ***`

how can this be fixed? or different cuda versions could be used?

**Comment by shunfeichen** [comment]
> could be problem be this?
> I configure kaldi by cuda8.0 but the espnet is installed by cuda10.0. I don't know if both the ctc and rnnt warpper of pytorch is kaldi-based? if so, that could be the problem.
> but when i try to configure kaldi with cuda10.0, it reports:
> 
> ``***configure failed: CUDA 10_0 does not support g++ (g++-9.3.0).
> You need g++ < 8.0. ***`
> 
> how can this be fixed? or different cuda versions could be used?

Hi ,Do you fixed it ? I also have the same problem.

**Comment by ShreyaKhare** [comment]
Did this get solved for any one , facing this issue with cuda 10.0 , torch 1.4
