### ISSUE TITLE
espnet2 can't use batch_type=folded 

### ISSUE THREAD

**Issue by shanguanma** [espnet/espnet#1808]
When I use  master of espnet currently, I will test espnet2  to train asr with transformer configure, 
When I want to get asr_states(e.g: stage 9 of asr.sh ), an error occurred. 

My environment is as follows:
````
cuda:10
python: 3.7.3
torch: 1.0.1
````
transformer configure:
````
# network architecture
# encoder related
encoder: transformer
encoder_conf:
    input_layer: "conv2d"
    num_blocks: 12
    linear_units: 2048
    dropout_rate: 0.1
    output_size: 256  # dimension of attention
    attention_heads: 4
    attention_dropout_rate: 0.0

# decoder related
# decoder related
decoder: transformer
decoder_conf:
    input_layer: "embed"
    num_blocks: 6
    linear_units: 2048
    dropout_rate: 0.1

# hybrid CTC/attention
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

# minibatch related
batch_type: folded
batch_size: 32
init: xavier_uniform  # choices=[      "chainer","xavier_uniform","xavier_normal","kaiming_uniform","kaiming_normal", None,], default : None

# optimization related
accum_grad: 2
grad_clip: 5
patience: none
max_epoch: 100

# optimizer
optim: adam
optim_conf:
    lr:  0.001           # pytorch default
    betas: [0.9, 0.98]  # from https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/transformer/optimizer.py
    eps: 0.000000001    # 1e-9

scheduler: reducelronplateau
scheduler_conf:
    mode: min
    factor: 0.1
    patience: 10
    verbose: false
    threshold: 0.0001
    threshold_mode: rel
    cooldown: 0
    min_lr: 0
    eps: 1.0e-08



# others:
val_scheduler_criterion:
    - valid
    - acc
best_model_criterion:
-  - valid
   - acc
   - max
keep_nbest_models: 10
````
The error log is as follows:
````
# python3 -m espnet2.bin.asr_train --collect_stats true --use_preprocessor true --bpemodel data/token_list/bpe_bpe3000/model.model --token_type bpe --token_list data/token_list/bpe_bpe3000/tokens.txt --non_linguistic_symbols none --train_data_path_and_name_and_type dump/fbank_pitch/train_trn_sp/feats.scp,speech,kaldi_ark --train_data_path_and_name_and_type dump/fbank_pitch/train_trn_sp/text,text,text --valid_data_path_and_name_and_type dump/fbank_pitch/train_dev/feats.scp,speech,kaldi_ark --valid_data_path_and_name_and_type dump/fbank_pitch/train_dev/text,text,text --train_shape_file exp/asr_stats_train_asr_transformer_pytorch_1.0.1_fbank_pitch_bpe/logdir/train.10.scp --valid_shape_file exp/asr_stats_train_asr_transformer_pytorch_1.0.1_fbank_pitch_bpe/logdir/dev.10.scp --fold_length 800 --output_dir exp/asr_stats_train_asr_transformer_pytorch_1.0.1_fbank_pitch_bpe/logdir/stats.10 --config conf/espnet2_conf_nscc_new/training/train_asr_transformer_pytorch_1.0.1.yaml --input_size=83 
# Started at Sat Apr 11 10:09:34 +08 2020
#
/home/users/ntu/tlvu/espnet_v0.7_202004010/espnet/tools/venv/bin/python3 /home/users/ntu/tlvu/espnet_v0.7_202004010/espnet/espnet2/bin/asr_train.py --collect_stats true --use_preprocessor true --bpemodel data/token_list/bpe_bpe3000/model.model --token_type bpe --token_list data/token_list/bpe_bpe3000/tokens.txt --non_linguistic_symbols none --train_data_path_and_name_and_type dump/fbank_pitch/train_trn_sp/feats.scp,speech,kaldi_ark --train_data_path_and_name_and_type dump/fbank_pitch/train_trn_sp/text,text,text --valid_data_path_and_name_and_type dump/fbank_pitch/train_dev/feats.scp,speech,kaldi_ark --valid_data_path_and_name_and_type dump/fbank_pitch/train_dev/text,text,text --train_shape_file exp/asr_stats_train_asr_transformer_pytorch_1.0.1_fbank_pitch_bpe/logdir/train.10.scp --valid_shape_file exp/asr_stats_train_asr_transformer_pytorch_1.0.1_fbank_pitch_bpe/logdir/dev.10.scp --fold_length 800 --output_dir exp/asr_stats_train_asr_transformer_pytorch_1.0.1_fbank_pitch_bpe/logdir/stats.10 --config conf/espnet2_conf_nscc_new/training/train_asr_transformer_pytorch_1.0.1.yaml --input_size=83
[dgx4105] 2020-04-11 10:09:42,987 (fileio:154) ERROR: Error happened with path="exp/asr_stats_train_asr_transformer_pytorch_1.0.1_fbank_pitch_bpe/logdir/train.10.scp", id="sp0.9-ui13f-ui13faz_0101-63916-64870", value="/home/users/ntu/tlvu/scratch/w2020/espnet-recipe/seame_e2e_espnet2/dump/fbank_pitch/org/train_trn_sp/data/raw_fbank_pitch_train_trn_sp.9.ark:651686373"
Traceback (most recent call last):
  File "/home/users/ntu/tlvu/espnet_v0.7_202004010/espnet/tools/venv/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004010/espnet/tools/venv/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004010/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/home/users/ntu/tlvu/espnet_v0.7_202004010/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004010/espnet/espnet2/tasks/abs_task.py", line 842, in main
    cls.main_worker(args)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004010/espnet/espnet2/tasks/abs_task.py", line 964, in main_worker
    **common_iter_kwargs,
  File "/home/users/ntu/tlvu/espnet_v0.7_202004010/espnet/espnet2/tasks/abs_task.py", line 1257, in build_iter_factory
    sort_batch=sort_batch,
  File "/home/users/ntu/tlvu/espnet_v0.7_202004010/espnet/espnet2/tasks/abs_task.py", line 1318, in build_sequence_iter_factory
    min_batch_size=torch.distributed.get_world_size() if distributed else 1,
  File "/home/users/ntu/tlvu/espnet_v0.7_202004010/espnet/espnet2/samplers/build_batch_sampler.py", line 135, in build_batch_sampler
    min_batch_size=min_batch_size,
  File "/home/users/ntu/tlvu/espnet_v0.7_202004010/espnet/espnet2/samplers/folded_batch_sampler.py", line 45, in __init__
    load_num_sequence_text(s, loader_type="csv_int") for s in shape_files
  File "/home/users/ntu/tlvu/espnet_v0.7_202004010/espnet/espnet2/samplers/folded_batch_sampler.py", line 45, in <listcomp>
    load_num_sequence_text(s, loader_type="csv_int") for s in shape_files
  File "/home/users/ntu/tlvu/espnet_v0.7_202004010/espnet/espnet2/utils/fileio.py", line 150, in load_num_sequence_text
    StringIO(v), ndmin=1, dtype=dtype, delimiter=delimiter
  File "/home/users/ntu/tlvu/espnet_v0.7_202004010/espnet/tools/venv/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1159, in loadtxt
    for x in read_data(_loadtxt_chunksize):
  File "/home/users/ntu/tlvu/espnet_v0.7_202004010/espnet/tools/venv/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1087, in read_data
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/home/users/ntu/tlvu/espnet_v0.7_202004010/espnet/tools/venv/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1087, in <listcomp>
    items = [conv(val) for (conv, val) in zip(converters, vals)]
ValueError: invalid literal for int() with base 10: '/home/users/ntu/tlvu/scratch/w2020/espnet-recipe/seame_e2e_espnet2/dump/fbank_pitch/org/train_trn_sp/data/raw_fbank_pitch_train_trn_sp.9.ark:651686373'
# Accounting: time=9 threads=1
# Ended (code 1) at Sat Apr 11 10:09:43 +08 2020, elapsed time 9 seconds
````

**Comment by kamo-naoyuki** [comment]
Thanks, this issue was fixed.
