### ISSUE TITLE
espnet2 CUDA out of memory in small dataset(300hours with perturbation)

### ISSUE THREAD

**Issue by shanguanma** [espnet/espnet#1812]
When   I test espnet2 by espnet master today. I run it with transformer configure at 16GB V100.
when I run it at stage 10 of asr.sh, an error occurred.
The error log is as follows:
[dgx4103:0/3] 2020-04-11 21:53:28,356 (abs_task:1065) INFO: Scheduler: <torch.optim.lr_scheduler.ReduceLROnPlateau object at 0x1542d5ebba20>
[dgx4103:0/3] 2020-04-11 21:53:28,358 (abs_task:1073) INFO: Saving the configuration in exp/asr_train_asr_transformer_pytorch_1.0.1_fbank_pitch_bpe/config.yaml
dgx4103:32250:32250 [0] NCCL INFO NET/Socket : Using [0]enp1s0f1:192.168.41.3<0> [1]ib0:192.168.162.3<0> [2]ib1:192.168.162.13<0> [3]ib2:192.168.162.23<0> [4]ib3:192.168.162.33<0>
dgx4103:32250:32250 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
dgx4103:32250:32250 [0] NCCL INFO NET/IB : Using [0]mlx5_1:1/IB [1]mlx5_3:1/IB [2]mlx5_0:1/IB [3]mlx5_2:1/IB ; OOB enp1s0f1:192.168.41.3<0>
NCCL version 2.4.2+cuda10.0
dgx4103:32252:32252 [2] NCCL INFO NET/Socket : Using [0]enp1s0f1:192.168.41.3<0> [1]ib0:192.168.162.3<0> [2]ib1:192.168.162.13<0> [3]ib2:192.168.162.23<0> [4]ib3:192.168.162.33<0>
dgx4103:32251:32251 [1] NCCL INFO NET/Socket : Using [0]enp1s0f1:192.168.41.3<0> [1]ib0:192.168.162.3<0> [2]ib1:192.168.162.13<0> [3]ib2:192.168.162.23<0> [4]ib3:192.168.162.33<0>
dgx4103:32251:32251 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
dgx4103:32252:32252 [2] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
dgx4103:32251:32251 [1] NCCL INFO NET/IB : Using [0]mlx5_1:1/IB [1]mlx5_3:1/IB [2]mlx5_0:1/IB [3]mlx5_2:1/IB ; OOB enp1s0f1:192.168.41.3<0>
dgx4103:32252:32252 [2] NCCL INFO NET/IB : Using [0]mlx5_1:1/IB [1]mlx5_3:1/IB [2]mlx5_0:1/IB [3]mlx5_2:1/IB ; OOB enp1s0f1:192.168.41.3<0>
dgx4103:32251:32334 [1] NCCL INFO Setting affinity for GPU 1 to 0fffff00,000fffff
dgx4103:32251:32334 [1] NCCL INFO comm 0x149014002330 rank 1 nranks 3 cudaDev 1 nvmlDev 1
dgx4103:32252:32335 [2] NCCL INFO Setting affinity for GPU 2 to 0fffff00,000fffff
dgx4103:32252:32335 [2] NCCL INFO comm 0x152968002330 rank 2 nranks 3 cudaDev 2 nvmlDev 2
dgx4103:32250:32325 [0] NCCL INFO Setting affinity for GPU 0 to 0fffff00,000fffff
dgx4103:32250:32325 [0] NCCL INFO comm 0x15426c002330 rank 0 nranks 3 cudaDev 0 nvmlDev 0
dgx4103:32250:32325 [0] NCCL INFO Channel 00 :    0   1   2
dgx4103:32250:32325 [0] NCCL INFO Channel 01 :    0   2   1
dgx4103:32250:32325 [0] NCCL INFO Channel 02 :    0   1   2
dgx4103:32250:32325 [0] NCCL INFO Channel 03 :    0   2   1
dgx4103:32251:32334 [1] NCCL INFO Ring 00 : 1[1] -> 2[2] via P2P/IPC
dgx4103:32252:32335 [2] NCCL INFO Ring 00 : 2[2] -> 0[0] via P2P/IPC
dgx4103:32250:32325 [0] NCCL INFO Ring 00 : 0[0] -> 1[1] via P2P/IPC
dgx4103:32251:32334 [1] NCCL INFO Ring 01 : 1[1] -> 0[0] via P2P/IPC
dgx4103:32252:32335 [2] NCCL INFO Ring 01 : 2[2] -> 1[1] via P2P/IPC
dgx4103:32250:32325 [0] NCCL INFO Ring 01 : 0[0] -> 2[2] via P2P/IPC
dgx4103:32251:32334 [1] NCCL INFO Ring 02 : 1[1] -> 2[2] via P2P/IPC
dgx4103:32252:32335 [2] NCCL INFO Ring 02 : 2[2] -> 0[0] via P2P/IPC
dgx4103:32250:32325 [0] NCCL INFO Ring 02 : 0[0] -> 1[1] via P2P/IPC
dgx4103:32251:32334 [1] NCCL INFO Ring 03 : 1[1] -> 0[0] via P2P/IPC
dgx4103:32252:32335 [2] NCCL INFO Ring 03 : 2[2] -> 1[1] via P2P/IPC
dgx4103:32250:32325 [0] NCCL INFO Ring 03 : 0[0] -> 2[2] via P2P/IPC
dgx4103:32250:32325 [0] NCCL INFO Using 256 threads, Min Comp Cap 7, Trees disabled
dgx4103:32251:32334 [1] NCCL INFO comm 0x149014002330 rank 1 nranks 3 cudaDev 1 nvmlDev 1 - Init COMPLETE
dgx4103:32250:32325 [0] NCCL INFO comm 0x15426c002330 rank 0 nranks 3 cudaDev 0 nvmlDev 0 - Init COMPLETE
dgx4103:32252:32335 [2] NCCL INFO comm 0x152968002330 rank 2 nranks 3 cudaDev 2 nvmlDev 2 - Init COMPLETE
dgx4103:32250:32250 [0] NCCL INFO Launch mode Parallel
[dgx4103:0/3] 2020-04-11 21:53:28,789 (trainer:197) INFO: 1/20epoch started
[dgx4103:0/3] 2020-04-11 21:53:40,525 (trainer:433) WARNING: The grad norm is nan. Skipping updating the model.
[dgx4103:0/3] 2020-04-11 21:54:38,380 (trainer:460) INFO: 1epoch:train:1-395batch: iter_time=3.828e-04, forward_time=0.049, loss=101.592, loss_att=87.557, loss_ctc=134.339, acc=0.178, backward_time=0.048, optim_step_time=0.040, lr_0=0.001, train_time=0.352
[dgx4103:0/3] 2020-04-11 21:54:40,199 (trainer:433) WARNING: The grad norm is nan. Skipping updating the model.
[dgx4103:0/3] 2020-04-11 21:55:10,611 (trainer:433) WARNING: The grad norm is nan. Skipping updating the model.
[dgx4103:0/3] 2020-04-11 21:55:43,085 (trainer:460) INFO: 1epoch:train:396-790batch: iter_time=5.105e-05, forward_time=0.046, loss=88.482, loss_att=74.988, loss_ctc=119.963, acc=0.221, backward_time=0.049, optim_step_time=0.040, lr_0=0.001, train_time=0.327
[dgx4103:0/3] 2020-04-11 21:56:23,424 (trainer:433) WARNING: The grad norm is nan. Skipping updating the model.
[dgx4103:0/3] 2020-04-11 21:56:48,765 (trainer:460) INFO: 1epoch:train:791-1185batch: iter_time=5.443e-05, forward_time=0.046, loss=89.624, loss_att=76.086, loss_ctc=121.093, acc=0.239, backward_time=0.048, optim_step_time=0.040, lr_0=0.001, train_time=0.333
[dgx4103:0/3] 2020-04-11 21:56:56,923 (trainer:433) WARNING: The grad norm is nan. Skipping updating the model.
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/tools/venv/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/tools/venv/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/espnet2/tasks/abs_task.py", line 1161, in main_worker
    distributed_option=distributed_option,
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/espnet2/train/trainer.py", line 209, in run
    options=trainer_options,
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/espnet2/train/trainer.py", line 382, in train_one_epoch
    loss, stats, weight = model(**batch)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 376, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/espnet2/asr/espnet_model.py", line 115, in forward
    encoder_out, encoder_out_lens = self.encode(speech, speech_lengths)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/espnet2/asr/espnet_model.py", line 191, in encode
    encoder_out, encoder_out_lens, _ = self.encoder(feats, feats_lengths)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/espnet2/asr/encoder/transformer_encoder.py", line 160, in forward
    xs_pad, masks = self.encoders(xs_pad, masks)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/espnet/nets/pytorch_backend/transformer/repeat.py", line 18, in forward
    args = m(*args)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/espnet/nets/pytorch_backend/transformer/encoder_layer.py", line 77, in forward
    x = residual + self.dropout(self.feed_forward(x))
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/espnet/nets/pytorch_backend/transformer/positionwise_feed_forward.py", line 30, in forward
    return self.w_2(self.dropout(torch.relu(self.w_1(x))))
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/dropout.py", line 58, in forward
    return F.dropout(input, self.p, self.training, self.inplace)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/functional.py", line 830, in dropout
    else _VF.dropout(input, p, training))
RuntimeError: CUDA out of memory. Tried to allocate 102.00 MiB (GPU 1; 15.75 GiB total capacity; 14.54 GiB already allocated; 7.75 MiB free; 191.95 MiB cached)
dgx4103:32251:32251 [1] NCCL INFO Destroyed comm 0x149014002330 rank 1
Traceback (most recent call last):
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/tools/venv/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/tools/venv/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/espnet2/tasks/abs_task.py", line 890, in main
    while not ProcessContext(processes, error_queues).join():
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/tools/venv/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 108, in join
    (error_index, exitcode)
Exception: process 1 terminated with exit code 1
# Accounting: time=257 threads=1
# Ended (code 1) at Sat Apr 11 21:57:18 +08 2020, elapsed time 257 seconds

======================================================================================

			Resource Usage on 2020-04-11 21:57:21.109565:

	JobId: 9891833.wlm01  
	Project: 12001458 
	Exit Status: 1
	NCPUs Requested: 60				NCPUs Used: 60
							CPU Time Used: 00:13:40
	Memory Requested: None 				Memory Used: 11294048kb
							Vmem Used: 166498948kb
	Walltime requested: 24:00:00 			Walltime Used: 00:04:24
	
	Execution Nodes Used: (dgx4103:ncpus=30:ngpus=3)+(dgx4104:ncpus=30:ngpus=3)
	
 ======================================================================================

**Comment by kamo-naoyuki** [comment]
Would you show the config and the log about batch_size?
The batch_size is too large simply?

**Comment by shanguanma** [comment]
Sure, the configure is as follows:

# network architecture
# encoder related
encoder: transformer
encoder_conf:
    input_layer: "conv2d"
    num_blocks: 12
    linear_units: 2048
    dropout_rate: 0.1
    output_size: 256  # dimension of attention
    attention_heads: 4
    attention_dropout_rate: 0.0

# decoder related
# decoder related
decoder: transformer
decoder_conf:
    input_layer: "embed"
    num_blocks: 6
    linear_units: 2048
    dropout_rate: 0.1

# hybrid CTC/attention
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

# minibatch related
batch_type: unsorted
batch_size: 32
init: xavier_uniform  # choices=[      "chainer","xavier_uniform","xavier_normal","kaiming_uniform","kaiming_normal", None,], default : None

# optimization related
accum_grad: 2
grad_clip: 5
patience: none
max_epoch: 20

# optimizer
optim: adam
optim_conf:
    lr:  0.001           # pytorch default
    betas: [0.9, 0.98]  # from https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/transformer/optimizer.py
    eps: 0.000000001    # 1e-9

scheduler: reducelronplateau
scheduler_conf:
    mode: min
    factor: 0.1
    patience: 10
    verbose: false
    threshold: 0.0001
    threshold_mode: rel
    cooldown: 0
    min_lr: 0
    eps: 1.0e-08



# others:
val_scheduler_criterion:
    - valid
    - acc
best_model_criterion:
-  - valid
   - acc
   - max
keep_nbest_models: 10

**Comment by kamo-naoyuki** [comment]
Why batch_type=unsorted? It consumes more memory, of course.
See here about batch_type: https://espnet.github.io/espnet/espnet2_training_option.html#change-mini-batch-type
