### ISSUE TITLE
 time_warp of espnet2 occurred an illegal memory access  

### ISSUE THREAD

**Issue by shanguanma** [espnet/espnet#1816]
When I test espnet2 for ASR, I use speaug  technology to train ASR mode with transformer.
But it occurred error. 
My environment is as follows:
cuda: 10.0
python:3.7.3
pytorch version: 1.1.0

The error log is as follows:
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THCUNN/generic/SpatialUpSamplingBicubic.cu line=76 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/tools/venv/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/tools/venv/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/espnet2/tasks/abs_task.py", line 842, in main
    cls.main_worker(args)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/espnet2/tasks/abs_task.py", line 1161, in main_worker
    distributed_option=distributed_option,
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/espnet2/train/trainer.py", line 209, in run
    options=trainer_options,
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/espnet2/train/trainer.py", line 382, in train_one_epoch
    loss, stats, weight = model(**batch)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/espnet2/asr/espnet_model.py", line 115, in forward
    encoder_out, encoder_out_lens = self.encode(speech, speech_lengths)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/espnet2/asr/espnet_model.py", line 182, in encode
    feats, feats_lengths = self.specaug(feats, feats_lengths)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/espnet2/asr/specaug/specaug.py", line 79, in forward
    x, x_lengths = self.time_warp(x, x_lengths)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/espnet2/layers/time_warp.py", line 87, in forward
    x[i][None, : x_lengths[i]], window=self.window, mode=self.mode,
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/espnet2/layers/time_warp.py", line 40, in time_warp
    x[:, :, :center], (warped, x.shape[3]), mode=mode, align_corners=False
  File "/home/users/ntu/tlvu/espnet_v0.7_202004011/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/functional.py", line 2573, in interpolate
    return torch._C._nn.upsample_bicubic2d(input, _output_size(2), align_corners)
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THCUNN/generic/SpatialUpSamplingBicubic.cu:76

The transformer configure is as follows:
# network architecture

specaug: specaug #  specaug,None

specaug_conf:
    apply_time_warp: True
    apply_freq_mask: True
    apply_time_mask: True

# encoder related
encoder: transformer
encoder_conf:
    input_layer: "conv2d"
    num_blocks: 12
    linear_units: 2048
    dropout_rate: 0.1
    output_size: 256  # dimension of attention
    attention_heads: 4
    attention_dropout_rate: 0.0

# decoder related
# decoder related
decoder: transformer
decoder_conf:
    input_layer: "embed"
    num_blocks: 6
    linear_units: 2048
    dropout_rate: 0.1

# hybrid CTC/attention
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

# minibatch related
batch_type: folded
batch_size: 64
init: xavier_uniform  # choices=[      "chainer","xavier_uniform","xavier_normal","kaiming_uniform","kaiming_normal", None,], default : None

# optimization related
accum_grad: 4
grad_clip: 5
patience: none
max_epoch: 100

# optimizer
optim: adam
optim_conf:
    lr:  0.001           # pytorch default
    betas: [0.9, 0.98]  # from https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/transformer/optimizer.py
    eps: 0.000000001    # 1e-9

scheduler: warmuplr     # pytorch v1.1.0+ required, 
                        # choose from 'reducelronplateau', 'lambdalr', 'steplr', 'multisteplr', 'exponentiallr', 'cosineannealinglr', 'noamlr', 'warmuplr', None)
scheduler_conf:
    warmup_steps: 25000

# others:
val_scheduler_criterion:
    - valid
    - acc
best_model_criterion:
-  - valid
   - acc
   - max
keep_nbest_models: 10

**Comment by kamo-naoyuki** [comment]
The error looks a bug of pytorch. Update pytorch to latest.

**Comment by shanguanma** [comment]
OK, I will test it on pytorch=1.4.0, thank you for your reply.

**Comment by shanguanma** [comment]
You are right, I test it on pytorch=1.4.0, it is OK. Thank you very much.

**Comment by kamo-naoyuki** [comment]
@shanguanma Thank you for reporting.
