### ISSUE TITLE
ASR  failure - NotImplementedError: streaming mode is not implemented

### ISSUE THREAD

**Issue by Arafat4341** [espnet/espnet#1820]
I am trying to test pre-trained ASR model. I am getting this error in espnet/asr/pytorch_backend/recog.py:

`NotImplementedError: streaming mode is not implemented`

Full log:
 asr_recog.py --config decode/download/tedlium2.rnn.v1/conf/decode_streaming.yaml --ngpu 0 --backend pytorch --debugmode 1 --verbose 1 --recog-json decode/ex_16000_mono_16bit/dump/data.json --result-label decode/ex_16000_mono_16bit/result.json --model decode/download/tedlium2.rnn.v1/exp/train_trim_sp_pytorch_train4/results/model.acc.best --api v2 --rnnlm decode/download/tedlium2.rnn.v1/exp/train_rnnlm_pytorch_lm_unigram500/rnnlm.model.best 

2020-04-13 02:32:20,272 (asr_recog:162) INFO: python path = (None)
2020-04-13 02:32:20,272 (asr_recog:167) INFO: set random seed = 1
2020-04-13 02:32:20,273 (asr_recog:175) INFO: backend = pytorch
2020-04-13 02:32:21,542 (recog:30) WARNING: experimental API for custom LMs is selected by --api v2
Traceback (most recent call last):
  File "/home/ubuntu/ESPnet/espnet/egs/tedlium2/asr1/../../../espnet/bin/asr_recog.py", line 208, in <module>
    main(sys.argv[1:])
  File "/home/ubuntu/ESPnet/espnet/egs/tedlium2/asr1/../../../espnet/bin/asr_recog.py", line 185, in main
    recog_v2(args)
  File "/home/ubuntu/ESPnet/espnet/espnet/asr/pytorch_backend/recog.py", line 34, in recog_v2
    raise NotImplementedError("streaming mode is not implemented")
NotImplementedError: streaming mode is not implemented

Sorry I am a newbie! Anyone can tell whats going on?!

**Comment by b-flo** [comment]
Hi,

It means streaming mode is not implemented/available yet. `streaming-mode` option should be `None`.

**Comment by Arafat4341** [comment]
I tried to add this option `--streaming-mode None` while running recog_wav.sh but its not a supported option. 
Where should I add this option?

**Comment by b-flo** [comment]
It should be put in your decode config (`streaming-mode: None`).
Btw, if you want to use streaming mode, you should use `--api v1`

**Comment by Arafat4341** [comment]
I used --api v1 option while running recog_wav.sh. It was finished without any error but I didn't get any output! It was a blank output on the console and no result.json file in there. 
Anyways I get results for other models. I am closing this issue! Thanks for your help!
