### ISSUE TITLE
espnet0.6.0 transformer model suport GPU decoding or not?

### ISSUE THREAD

**Issue by zqs01** [espnet/espnet#1848]
Hello everyone, I have a question, when I use Transformer in espnet0.6.0 for GPU decoding, there is an error `RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same` , what I should do to fix this problem? Thanks in advance.

**Comment by kamo-naoyuki** [comment]
Thanks, that's a bug.  Would you show the log?

**Comment by zqs01** [comment]
`# asr_recog.py --config conf/decode.yaml --ngpu 1 --backend pytorch --recog-json dump/test_eval92/deltafalse/split1utt/data.1.json --result-label exp/train_si284_pytorch_kqdot/decode_test_eval92_decode/data.1.json --model exp/train_si284_pytorch_kqdot/results/model.last10.avg.best 
# Started at Fri Apr 17 19:36:33 CST 2020
#
2020-04-17 19:36:34,692 (asr_recog:162) INFO: python path = (None)
2020-04-17 19:36:34,692 (asr_recog:167) INFO: set random seed = 1
2020-04-17 19:36:34,693 (asr_recog:175) INFO: backend = pytorch
2020-04-17 19:36:39,690 (deterministic_utils:24) INFO: torch type check is disabled
2020-04-17 19:36:39,691 (asr_utils:439) INFO: reading a config file from exp/train_si284_pytorch_kqdot/results/model.json
2020-04-17 19:36:39,692 (asr_init:141) WARNING: reading model parameters from exp/train_si284_pytorch_kqdot/results/model.last10.avg.best
/home/qszhu/common/projects/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/_reduction.py:49: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))
2020-04-17 19:36:41,470 (asr:666) INFO: gpu id: [0]
2020-04-17 19:36:43,854 (io_utils:59) WARNING: [Experimental feature] Some preprocessing will be done for the mini-batch creation using Transformation(
    0: Identity())
2020-04-17 19:36:43,854 (asr:685) INFO: (1/333) decoding 440c0401
Traceback (most recent call last):
  File "/home/qszhu/common/projects/espnet/egs/wsj/asr1/../../../espnet/bin/asr_recog.py", line 208, in <module>
    main(sys.argv[1:])
  File "/home/qszhu/common/projects/espnet/egs/wsj/asr1/../../../espnet/bin/asr_recog.py", line 190, in main
    recog(args)
  File "/home/qszhu/common/projects/espnet/espnet/asr/pytorch_backend/asr.py", line 719, in recog
    nbest_hyps = model.recognize(feat, args, train_args.char_list, rnnlm)
  File "/home/qszhu/common/projects/espnet/espnet/nets/pytorch_backend/e2e_asr_transformer.py", line 244, in recognize
    enc_output = self.encode(feat).unsqueeze(0)
  File "/home/qszhu/common/projects/espnet/espnet/nets/pytorch_backend/e2e_asr_transformer.py", line 229, in encode
    enc_output, _ = self.encoder(feat, None)
  File "/home/qszhu/common/projects/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qszhu/common/projects/espnet/espnet/nets/pytorch_backend/transformer/encoder.py", line 123, in forward
    xs, masks = self.embed(xs, masks)
  File "/home/qszhu/common/projects/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qszhu/common/projects/espnet/espnet/nets/pytorch_backend/transformer/subsampling.py", line 46, in forward
    x = self.conv(x)
  File "/home/qszhu/common/projects/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qszhu/common/projects/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/qszhu/common/projects/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qszhu/common/projects/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same
# Accounting: time=11 threads=1
# Ended (code 1) at Fri Apr 17 19:36:44 CST 2020, elapsed time 11 seconds
`
@kamo-naoyuki thank you.

**Comment by kamo-naoyuki** [comment]
@sw005320 v1 decoding seems not to support GPU decode? Is this a bug?
@zqs01 Anyway, you can use v2 api: `--api v2`

**Comment by sw005320** [comment]
It is actually fully supported and faster than v2 (this is the reason that we have to maintain v1 and v2 for now).

@zqs01,
See https://espnet.github.io/espnet/tutorial.html#use-of-gpu
You may need to set `--batchsize 1` (or more)

**Comment by kamo-naoyuki** [comment]
Very confusing. It should raise an error if `--batchsize 0` and `--ngpu 1`, or it's better to change the batch mode if `--ngpu 1`.

**Comment by zqs01** [comment]
@kamo-naoyuki @sw005320  I follow your suggestions, thank you. I add `api: v2` to the `decode.yaml`, then it can decoding on the GPU correctly.
 batchsize: 0
beam-size: 10
penalty: 0.0
maxlenratio: 0.0
minlenratio: 0.0
ctc-weight: 0.0
lm-weight: 0.0
api: v2

**Comment by jinyiyang-jhu** [comment]
> It is actually fully supported and faster than v2 (this is the reason that we have to maintain v1 and v2 for now).
> 
> @zqs01,
> See https://espnet.github.io/espnet/tutorial.html#use-of-gpu
> You may need to set `--batchsize 1` (or more)

For the e2e_st_transformer model, it seems not to support batch decoding yet (I got this error when setting batchsize>=1); however if I set batchsize==0 and ngpu==1 and api==v2, I got the same error as above: "RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same", any suggestion how to solve this problem ? Using CPU for inferencing (translating) seems quite slowly.
