### ISSUE TITLE
'espnet.nets.pytorch_backend.e2e_asr_transformer:E2E' object has no attribute 'serialize'

### ISSUE THREAD

**Issue by david1125222** [espnet/espnet#1899]
Hello, 
When I trained the Transformer model, after an epoch the following error occurred. The training config is modified by the pretrained model  [https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/RESULTS.md#pytorch-large-transformer-with-specaug-4-gpus--transformer-lm-4-gpus](url) and I only reduced the number of layer. 

```
Traceback (most recent call last):
  File "/home/training/r08943020/espnet/egs/librispeech/asr1/../../../espnet/bin/asr_train.py", line 368, in <module>
    main(sys.argv[1:])
  File "/home/training/r08943020/espnet/egs/librispeech/asr1/../../../espnet/bin/asr_train.py", line 355, in main
    train(args)
  File "/home/training/r08943020/espnet/espnet/asr/pytorch_backend/asr.py", line 650, in train
    trainer.run()
  File "/home/training/r08943020/espnet/tools/venv/lib/python3.7/site-packages/chainer/training/trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "/home/training/r08943020/espnet/tools/venv/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/training/r08943020/espnet/tools/venv/lib/python3.7/site-packages/chainer/training/trainer.py", line 319, in run
    entry.extension(self)
  File "/home/training/r08943020/espnet/tools/venv/lib/python3.7/site-packages/chainer/training/extensions/_snapshot.py", line 224, in __call__
    self._make_snapshot(trainer)
  File "/home/training/r08943020/espnet/tools/venv/lib/python3.7/site-packages/chainer/training/extensions/_snapshot.py", line 228, in _make_snapshot
    serialized_target = npz.serialize(target)
  File "/home/training/r08943020/espnet/tools/venv/lib/python3.7/site-packages/chainer/serializers/npz.py", line 79, in serialize
    s.save(obj)
  File "/home/training/r08943020/espnet/tools/venv/lib/python3.7/site-packages/chainer/serializer.py", line 67, in save
    obj.serialize(self)
  File "/home/training/r08943020/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'E2E' object has no attribute 'serialize'
```

**Comment by sw005320** [comment]
Could you show me the config file?

**Comment by david1125222** [comment]
ok~

`# This configuration requires 4 gpus with 12GB memory
accum-grad: 4
adim: 512
aheads: 8
backend: pytorch
batch-bins: 750000
dlayers: 2
dropout-rate: 0.1
dunits: 512
elayers: 4
epochs: 50
eunits: 512
grad-clip: 5
lsm-weight: 0.1
model-module: espnet.nets.pytorch_backend.e2e_asr_transformer:E2E
mtlalpha: 0.3
opt: noam
patience: 0
sortagrad: 0
transformer-attn-dropout-rate: 0.0
transformer-init: pytorch
transformer-input-layer: conv2d
transformer-length-normalized-loss: false
transformer-lr: 10.0
transformer-warmup-steps: 25000`

**Comment by sw005320** [comment]
OK, it looks normal.
Did you train it with a single GPU or multiple GPU?
If you use a multiple GPU, can you try a single GPU?
