### ISSUE TITLE
pytorch GPU memory full error at validation

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#191]
I don't know why, but the pytorch backend uses a lot of GPU memory during validation (**which should not be**), and fails with an error due to the out of memory.
This is a librispeech task, and used to be working without such issues.
Can someone fix it?

```
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Exception in main training loop: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Traceback (most recent call last):hs
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/chainer/training/trainer.py", line 309, in run
    entry.extension(self)
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/chainer/training/extensions/evaluator.py", line 140, in __call__
    result = self.evaluate()
  File "/export/a08/shinji/201707e2e/espnet_dev2/src/asr/asr_pytorch.py", line 77, in evaluate
    self.model(x)
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/export/a08/shinji/201707e2e/espnet_dev2/src/nets/e2e_asr_attctc_th.py", line 117, in forward
    loss_ctc, loss_att, acc = self.predictor(x)
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/export/a08/shinji/201707e2e/espnet_dev2/src/nets/e2e_asr_attctc_th.py", line 297, in forward
    hpad, hlens = self.enc(xpad, ilens)
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/export/a08/shinji/201707e2e/espnet_dev2/src/nets/e2e_asr_attctc_th.py", line 1907, in forward
    xs, ilens = self.enc1(xs, ilens)
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/export/a08/shinji/201707e2e/espnet_dev2/src/nets/e2e_asr_attctc_th.py", line 1951, in forward
    ys, (hy, cy) = bilstm(xpack)
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/torch/nn/modules/rnn.py", line 204, in forward
    output, hidden = func(input, self.all_weights, hx)
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/torch/nn/_functions/rnn.py", line 385, in forward
    return func(input, *fargs, **fkwargs)
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/torch/autograd/function.py", line 328, in _do_forward
    flat_output = super(NestedIOFunction, self)._do_forward(*flat_input)
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/torch/autograd/function.py", line 350, in forward
    result = self.forward_extended(*nested_tensors)
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/torch/nn/_functions/rnn.py", line 294, in forward_extended
    cudnn.rnn.forward(self, input, hx, weight, output, hy)
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/torch/backends/cudnn/rnn.py", line 281, in forward
    fn.reserve = torch.cuda.ByteTensor(reserve_size.value)
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/export/a08/shinji/201707e2e/espnet_dev2/egs/librispeech/asr1/../../../src/bin/asr_train.py", line 205, in <module>
    main()
  File "/export/a08/shinji/201707e2e/espnet_dev2/egs/librispeech/asr1/../../../src/bin/asr_train.py", line 199, in main
    train(args)
  File "/export/a08/shinji/201707e2e/espnet_dev2/src/asr/asr_pytorch.py", line 358, in train
    trainer.run()
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/chainer/training/trainer.py", line 320, in run
    six.reraise(*sys.exc_info())
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/chainer/training/trainer.py", line 309, in run
    entry.extension(self)
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/chainer/training/extensions/evaluator.py", line 140, in __call__
    result = self.evaluate()
  File "/export/a08/shinji/201707e2e/espnet_dev2/src/asr/asr_pytorch.py", line 77, in evaluate
    self.model(x)
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/export/a08/shinji/201707e2e/espnet_dev2/src/nets/e2e_asr_attctc_th.py", line 117, in forward
    loss_ctc, loss_att, acc = self.predictor(x)
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/export/a08/shinji/201707e2e/espnet_dev2/src/nets/e2e_asr_attctc_th.py", line 297, in forward
    hpad, hlens = self.enc(xpad, ilens)
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/export/a08/shinji/201707e2e/espnet_dev2/src/nets/e2e_asr_attctc_th.py", line 1907, in forward
    xs, ilens = self.enc1(xs, ilens)
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/export/a08/shinji/201707e2e/espnet_dev2/src/nets/e2e_asr_attctc_th.py", line 1951, in forward
    ys, (hy, cy) = bilstm(xpack)
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/torch/nn/modules/rnn.py", line 204, in forward
    output, hidden = func(input, self.all_weights, hx)
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/torch/nn/_functions/rnn.py", line 385, in forward
    return func(input, *fargs, **fkwargs)
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/torch/autograd/function.py", line 328, in _do_forward
    flat_output = super(NestedIOFunction, self)._do_forward(*flat_input)
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/torch/autograd/function.py", line 350, in forward
    result = self.forward_extended(*nested_tensors)
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/torch/nn/_functions/rnn.py", line 294, in forward_extended
    cudnn.rnn.forward(self, input, hx, weight, output, hy)
  File "/export/a08/shinji/201707e2e/espnet_dev2/tools/venv/local/lib/python2.7/site-packages/torch/backends/cudnn/rnn.py", line 281, in forward
    fn.reserve = torch.cuda.ByteTensor(reserve_size.value)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
# Accounting: time=1815 threads=1
# Finished at Fri May 25 17:35:47 EDT 2018 with status 1
```

**Comment by kan-bayashi** [comment]
@sw005320 Could you test this patch? (#192)

**Comment by sw005320** [comment]
Thanks! #192 seems to solve this issue. I confirmed it in my setup.
