### ISSUE TITLE
self.device = device   AttributeError: can't set attribute

### ISSUE THREAD

**Issue by jiamliang** [espnet/espnet#1925]
i run librispeech asr sample in a docker container, and i meet the following error. is there any suggestion? Thanks a lot .

Ubuntu 18.04
Python 2.6
pyTorch 1.4.0

2020-05-14 03:41:17,746 (asr_train:549) WARNING: Skip DEBUG/INFO messages
2020-05-14 03:41:19,786 (ctc:34) WARNING: CTC was set to builtin due to PyTorch version.
2020-05-14 03:41:29,654 (io_utils:59) WARNING: [Experimental feature] Some preprocessing will be done for the mini-batch creation using Transformation(
    0: TimeWarp(max_time_warp=5, inplace=True, mode=PIL)
    1: FreqMask(F=30, n_mask=2, replace_with_zero=False, inplace=True)
    2: TimeMask(T=40, n_mask=2, replace_with_zero=False, inplace=True))
2020-05-14 03:41:29,658 (io_utils:59) WARNING: [Experimental feature] Some preprocessing will be done for the mini-batch creation using Transformation(
    0: TimeWarp(max_time_warp=5, inplace=True, mode=PIL)
    1: FreqMask(F=30, n_mask=2, replace_with_zero=False, inplace=True)
    2: TimeMask(T=40, n_mask=2, replace_with_zero=False, inplace=True))

Traceback (most recent call last):
  File "/code/espnet/egs/librispeech/asr1/../../../espnet/bin/asr_train.py", line 622, in <module>
    main(sys.argv[1:])
  File "/code/espnet/egs/librispeech/asr1/../../../espnet/bin/asr_train.py", line 608, in main
    train(args)
  File "/code/espnet/espnet/asr/pytorch_backend/asr.py", line 620, in train
    use_apex=use_apex,
  File "/code/espnet/espnet/asr/pytorch_backend/asr.py", line 171, in __init__
    self.device = device
AttributeError: can't set attribute

**Comment by Fhrozen** [comment]
Is this a container you built by yourself? Usually docker containers built by us should report a problem with the espnet folder in root `/espnet/espnet/<module>`, but yours shows to be executed inside the folder '/code'. I will check this in any case.

**Comment by kamo-naoyuki** [comment]
Chainer=7 is used. Simply you need to down the version to 6.0.0.

**Comment by Fhrozen** [comment]
The interesting part is that Docker containers are built based on the official release. And until now the version has not been modified yet. Therefore, the docker containers still keep the same chainer version (6.0). I suppose that he built a new container based on chainer 7.

**Comment by jiamliang** [comment]
@Fhrozen Yes，i built this image myself . 
@kamo-naoyuki  I install the newest Chainer by pip install.  
 as a workaround, i comment this line :   self.device = device  and it goes on.
but i meet this issue  #1723  at the end of epoch 0 . 
Finaly, I install Chainer 6.0.0  
Thanks all.

**Comment by jiamliang** [comment]
> The interesting part is that Docker containers are built based on the official release. And until now the version has not been modified yet. Therefore, the docker containers still keep the same chainer version (6.0). I suppose that he built a new container based on chainer 7.

will this issue #1723 be fixed soon? I think, it's better to add a requirement/dependance txt.

**Comment by kamo-naoyuki** [comment]
chainer=6.0.0 is requirements. https://github.com/espnet/espnet/blob/master/setup.py#L21
