### ISSUE TITLE
Espnet2 CUDA out of memory for custom dataset

### ISSUE THREAD

**Issue by xforceco** [espnet/espnet#1968]
> Traceback (most recent call last):
  File "/path/tools/venv/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/path/tools/venv/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/path/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/path/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/path/espnet2/tasks/abs_task.py", line 842, in main
    cls.main_worker(args)
  File "/path/espnet2/tasks/abs_task.py", line 1161, in main_worker
    distributed_option=distributed_option,
  File "/path/espnet2/train/trainer.py", line 212, in run
    options=trainer_options,
  File "/path/espnet2/train/trainer.py", line 383, in train_one_epoch
    loss, stats, weight = model(**batch)
  File "/path/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/path/espnet2/asr/espnet_model.py", line 115, in forward
    encoder_out, encoder_out_lens = self.encode(speech, speech_lengths)
  File "/path/espnet2/asr/espnet_model.py", line 191, in encode
    encoder_out, encoder_out_lens, _ = self.encoder(feats, feats_lengths)
  File "/path/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/path/espnet2/asr/encoder/transformer_encoder.py", line 160, in forward
    xs_pad, masks = self.encoders(xs_pad, masks)
  File "/path/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/path/espnet/nets/pytorch_backend/transformer/repeat.py", line 18, in forward
    args = m(*args)
  File "/path/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/path/espnet/nets/pytorch_backend/transformer/encoder_layer.py", line 80, in forward
    x = residual + self.dropout(self.self_attn(x_q, x, x, mask))
  File "/path/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/path/espnet/nets/pytorch_backend/transformer/attention.py", line 68, in forward
    mask, 0.0
RuntimeError: CUDA out of memory. Tried to allocate 214.00 MiB (GPU 0; 10.73 GiB total capacity; 9.57 GiB already allocated; 179.56 MiB free; 9.79 GiB reserved in total by PyTorch)
Accounting: time=4501 threads=1
Ended (code 1) at Mon May 25 13:11:22 2020, elapsed time 4501 seconds

It is strange that `214.00 MiB` can't be allocated when only `9.79 GiB / 10.73 GiB` is used.

I am using aishell `conf/train_asr_transformer.yaml` with only the following modifications
- `batch size: 32` => `2`
- `accum_grad: 2` => `32`
- `batch_type: folded` => `numel`

Other environment details:
- GPU: RTX 2080 Ti
- Pytorch: 1.4.0
- CUDA: 10.0
- espnet: master espnet2

**Comment by kamo-naoyuki** [comment]
When numel mode, batch_size is not referred, but batch_bin is used instead.
See docs: https://espnet.github.io/espnet/espnet2_training_option.html#change-mini-batch-type

**Comment by xforceco** [comment]
> When numel mode, batch_size is not referred, but batch_bin is used instead.
> See docs: https://espnet.github.io/espnet/espnet2_training_option.html#change-mini-batch-type

I see
So is there any recommendation/guideline on how to set it along with `accum_grad`?
Many thanks

**Comment by kamo-naoyuki** [comment]
It's hard to say the recommendation.

Refer the previous recipe, e.g. https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/conf/tuning/train_pytorch_transformer_large_ngpu4.yaml

Personally I set the batch_size/batch_bin to the maximum size as long as the memory is allowed and tune the accum_grad to 2-8.  Basically, too large batch_size/accum_grad gives worse result. Note that warmup_steps should be also tuned according to the batch_size.

**Comment by xforceco** [comment]
It seems it is really non-trivial that a lot of hyper-parameter combinations has to be experimented
Yet thanks for pointing out that `batch_bin`, `accum_grad` and `warmup_steps` have to be tuned altogether
