### ISSUE TITLE
RuntimeError: arguments are located on different GPUs

### ISSUE THREAD

**Issue by psridhar-asapp** [espnet/espnet#2084]
Hi I ran into the following issue when training an RNN-T model with 8 GPUs. Both the encoder and decoder are stacked LSTMs. I asked espnet to report cer/wer. The error always happens at that step. Here is the full stack

Traceback (most recent call last):
  File "/home/psridhar/espnet/egs/lima/asr1/../../../espnet/bin/asr_train.py", line 628, in <module>
    main(sys.argv[1:])
  File "/home/psridhar/espnet/egs/lima/asr1/../../../espnet/bin/asr_train.py", line 614, in main
    train(args)
  File "/home/psridhar/espnet/espnet/asr/pytorch_backend/asr.py", line 833, in train
    trainer.run()
  File "/home/psridhar/espnet/tools/venv/lib/python3.7/site-packages/chainer/training/trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "/home/psridhar/espnet/tools/venv/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/psridhar/espnet/tools/venv/lib/python3.7/site-packages/chainer/training/trainer.py", line 319, in run
    entry.extension(self)
  File "/home/psridhar/espnet/espnet/utils/training/evaluator.py", line 10, in __call__
    ret = super().__call__(trainer)
  File "/home/psridhar/espnet/tools/venv/lib/python3.7/site-packages/chainer/training/extensions/evaluator.py", line 161, in __call__
    result = self.evaluate()
  File "/home/psridhar/espnet/espnet/asr/pytorch_backend/asr.py", line 134, in evaluate
    data_parallel(self.model, x, range(self.ngpu))
  File "/home/psridhar/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 188, in data_parallel
    outputs = parallel_apply(replicas, inputs, module_kwargs, used_device_ids)
  File "/home/psridhar/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home/psridhar/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/home/psridhar/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/psridhar/espnet/espnet/nets/pytorch_backend/e2e_asr_transducer.py", line 426, in forward
    cer, wer = self.error_calculator(hs_pad, ys_pad)
  File "/home/psridhar/espnet/espnet/nets/e2e_asr_common.py", line 305, in __call__
    nbest_hyps = self.dec.recognize_beam(hs_pad[b], self.recog_args)
  File "/home/psridhar/espnet/espnet/nets/pytorch_backend/transducer/rnn_decoders.py", line 268, in recognize_beam
    ytu = F.log_softmax(self.joint(hi, y[0]), dim=0)
  File "/home/psridhar/espnet/espnet/nets/pytorch_backend/transducer/rnn_decoders.py", line 143, in joint
    z = torch.tanh(self.lin_enc(h_enc) + self.lin_dec(h_dec))
  File "/home/psridhar/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/psridhar/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 67, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/psridhar/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/functional.py", line 1354, in linear
    output = input.matmul(weight.t())
RuntimeError: arguments are located on different GPUs at /opt/conda/conda-bld/pytorch_1549636813070/work/aten/src/THC/generic/THCTensorMathBlas.cu:253

**Comment by sw005320** [comment]
I just want to figure out the problem.
Does it happen without cer/wer reporters?
Sorry that we don't fully test the multiple GPU decoding.

**Comment by psridhar-asapp** [comment]
It does not happen without CER/WER reporters. No worries. I'm glad to help debug things. Doing some googling it looks like this is a problem when .to() or cuda() is used improperly 

https://discuss.pytorch.org/t/dataparallel-arguments-are-located-on-different-gpus/42054

Not sure where in the recog step this is happening

**Comment by b-flo** [comment]
Hi,

Sorry didn't see this one. I'll fix that in my PR!

**Comment by b-flo** [comment]
Fixed in #2444. Sorry it took so long.
