### ISSUE TITLE
issue about CHIME4 multi-channel recipe 

### ISSUE THREAD

**Issue by gothiswaysir** [espnet/espnet#2119]
Dear all,

I encountered some problems when I run the latest version of espnet's CHIME4 recipe.

Something went wrong with the data2json.sh, 

> /data_a7/xinyuan/espnet/tools/venv/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
/data_a7/xinyuan/espnet/tools/venv/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import of 'jit' requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
2020-06-28 18:58:24,975 (transformation:147) CRITICAL: Catch a exception from 0th func: Stft(n_fft=400, n_shift=160, win_length=400, window=han,center=True, pad_mode=reflect)
Traceback (most recent call last):
  File "/data_a7/xinyuan/espnet/utils/feat-to-shape.py", line 84, in <module>
    main()
  File "/data_a7/xinyuan/espnet/utils/feat-to-shape.py", line 73, in main
    mat = preprocessing(mat, uttid_list=utt)
  File "/data_a7/xinyuan/espnet/espnet/transform/transformation.py", line 144, in __call__
    xs = [func(x, **_kwargs) for x in xs]
  File "/data_a7/xinyuan/espnet/espnet/transform/transformation.py", line 144, in <listcomp>
    xs = [func(x, **_kwargs) for x in xs]
  File "/data_a7/xinyuan/espnet/espnet/transform/spectrogram.py", line 276, in __call__
    pad_mode=self.pad_mode,
  File "/data_a7/xinyuan/espnet/espnet/transform/spectrogram.py", line 30, in stft
    for ch in range(x.shape[1])
  File "/data_a7/xinyuan/espnet/espnet/transform/spectrogram.py", line 30, in <listcomp>
    for ch in range(x.shape[1])
  File "/data_a7/xinyuan/espnet/tools/venv/lib/python3.7/site-packages/librosa/core/spectrum.py", line 215, in stft
    util.valid_audio(y)
  File "/data_a7/xinyuan/espnet/tools/venv/lib/python3.7/site-packages/librosa/util/utils.py", line 278, in valid_audio
    raise ParameterError('Audio buffer is not Fortran-contiguous. '
librosa.util.exceptions.ParameterError: Audio buffer is not Fortran-contiguous. Use numpy.asfortranarray to ensure Fortran contiguity.

So I went to check the python code, and found a FIXME on line 18 in spectrogram.py
It seems that you have already discovered this bug.  

>  FIXME(kamo): librosa.stft can't use multi-channel?

Since I have installed several versions of espnet on my computer, I checked and it seems that this January version already has this problem. 
It’s been five months, is there a solution now?

Thanks for help

**Comment by gothiswaysir** [comment]
During installation, the default versions are not compatible with each other, so I changed the version of some libraries

> Package                   Version             Location
------------------------- ------------------- -------------------------------
absl-py                   0.9.0
args                      0.1.0
attrs                     19.3.0
audioread                 2.1.8
Bottleneck                1.3.2
brotlipy                  0.7.0
cachetools                4.1.0
certifi                   2020.6.20
cffi                      1.14.0
chainer                   6.0.0
chainer-ctc               1.0
chardet                   3.0.4
click                     7.1.2
clint                     0.5.1
conda                     4.8.3
conda-package-handling    1.7.0
ConfigArgParse            1.2.3
cryptography              2.9.2
cupy-cuda100              6.0.0
cycler                    0.10.0
Cython                    0.29.20
dataclasses               0.6
decorator                 4.4.2
Distance                  0.1.3
editdistance              0.5.2
espnet                    0.8.0               /data_a7/xinyuan/espnet_20.6.28
espnet-tts-frontend       0.0.1
fastdtw                   0.3.4
fastrlock                 0.5
filelock                  3.0.12
g2p-en                    2.1.0
google-auth               1.18.0
google-auth-oauthlib      0.4.1
grpcio                    1.30.0
h5py                      2.9.0
humanfriendly             8.2
idna                      2.9
importlib-metadata        1.7.0
inflect                   4.1.0
jaconv                    0.2.4
joblib                    0.13.2
jsonschema                3.2.0
kaldiio                   2.15.1
kiwisolver                1.2.0
languageflow              1.1.13a1
librosa                   0.7.2
llvmlite                  0.32.1
Markdown                  3.2.2
matplotlib                3.2.2
mkl-fft                   1.1.0
mkl-random                1.1.1
mkl-service               2.3.0
musdb                     0.3.1
museval                   0.3.0
nara-wpe                  0.0.7
nltk                      3.4.5
nnmnkwii                  0.0.20
numba                     0.49.0
numpy                     1.18.5
oauthlib                  3.1.0
pandas                    1.0.5
Pillow                    7.1.2
pip                       20.1.1
protobuf                  3.7.1
pyaml                     20.4.0
pyasn1                    0.4.8
pyasn1-modules            0.2.8
pycosat                   0.6.3
pycparser                 2.20
pyOpenSSL                 19.1.0
pyparsing                 2.4.7
pyrsistent                0.16.0
PySocks                   1.7.1
pysptk                    0.1.18
pystoi                    0.3.3
python-crfsuite           0.9.6
python-dateutil           2.8.1
pytorch-wpe               0.0.0
pytz                      2020.1
PyYAML                    5.3.1
requests                  2.24.0
requests-oauthlib         1.3.0
resampy                   0.2.2
rsa                       4.6
ruamel-yaml               0.15.87
scikit-learn              0.20.3
scipy                     1.5.0
sentencepiece             0.1.86
setuptools                47.3.1.post20200622
simplejson                3.17.0
six                       1.15.0
sklearn                   0.0
SoundFile                 0.10.3.post1
stempeg                   0.1.8
tabulate                  0.8.7
tensorboard               2.2.2
tensorboard-plugin-wit    1.6.0.post3
tensorboardX              1.8
torch                     1.0.1.post2
torch-complex             0.0.3
tqdm                      4.46.1
typeguard                 2.9.1
typing                    3.7.4.1
typing-extensions         3.7.4.2
underthesea               1.1.17
Unidecode                 1.1.1
urllib3                   1.25.9
warpctc-pytorch10-cuda100 0.1.3
warprnnt-pytorch          0.1
Werkzeug                  1.0.1
wheel                     0.34.2
zipp                      3.1.0
