### ISSUE TITLE
TypeError: 'kenlm.State' object is not subscriptable

### ISSUE THREAD

**Issue by astikbiswas** [espnet/espnet#2151]
Hello All,

I have been trying to follow aishell/asr1/run.sh recipe to implement n-gram scorer using kenlm. Everything went fine. However, I have encountered an error during decoding as given below:
 2020-07-03 15:16:48,343 (recog:133) INFO: (1/514) decoding engsot_00002_u00001_engsot
2020-07-03 15:16:48,607 (beam_search:353) INFO: max output length: 54
2020-07-03 15:16:48,607 (beam_search:354) INFO: min output length: 0
Traceback (most recent call last):
  File "/espnet/espnet/bin/asr_recog.py", line 311, in <module>
    main(sys.argv[1:])
  File "/espnet/espnet/bin/asr_recog.py", line 281, in main
    recog_v2(args)
  File "/espnet/espnet/asr/pytorch_backend/recog.py", line 138, in recog_v2
    x=enc, maxlenratio=args.maxlenratio, minlenratio=args.minlenratio
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/espnet/espnet/nets/beam_search.py", line 361, in forward
    best = self.search(running_hyps, x)
  File "/espnet/espnet/nets/beam_search.py", line 321, in search
    states=self.merge_states(states, part_states, part_j),
  File "/espnet/espnet/nets/beam_search.py", line 276, in merge_states
    new_states[k] = d.select_state(part_states[k], part_idx)
  File "/espnet/espnet/nets/scorer_interface.py", line 51, in select_state
    return None if state is None else state[i]
**TypeError: 'kenlm.State' object is not subscriptable**

I did google search but not found any helpful advise. Please advise me how to get rid of that.

The decoding snippet is as per standard format:
${decode_cmd} JOB=1:${nj} ${expdir}/${decode_dir}/log/decode.JOB.log \
            asr_recog.py \
            --config ${decode_config} \
            --ngpu ${ngpu} \
            --backend ${backend} \
            --batchsize 0 \
            --recog-json ${feat_recog_dir}/split${nj}utt/data.JOB.json \
            --result-label ${expdir}/${decode_dir}/data.JOB.json \
            --model ${expdir}/results/${recog_model}  \
            --rnnlm ${lmexpdir}/rnnlm.model.best \
            --ngram-model ${ngramexpdir}/${n_gram}gram.bin \
            --api v2

**Comment by astikbiswas** [comment]
Update: I did encountered this problem only when I choose **--ngram-scorer "part"**. If I set **--ngram-scorer "full"**, it is working fine.

**Comment by sw005320** [comment]
Thanks for your report (and thanks for testing our new function).
@qmpzzpmq, could you take a look at this issue?

**Comment by qmpzzpmq** [comment]
yes, I will check it later. Thanks for you feedback @astikbiswas

**Comment by qmpzzpmq** [comment]
@astikbiswas could you test  --ngram-scorer "part" in aishell egs? I tried it in aishell egs with "part" ngram-scorer, it looks fine.

**Comment by astikbiswas** [comment]
Thanks for response @qmpzzpmq. I did ran an experiment with a subset of aishell data using aishell egs recipe and encountered same problem when using default part option. Decoding log is:
------------------------------------
   # asr_recog.py --config conf/decode.yaml --ngpu 0 --backend pytorch --batchsize 0 --recog-json dump/test/deltafalse/split12utt/data.1.json --result-label exp/train_sp_pytorch_train/decode_test_decode_lm_4/data.1.json --model exp/train_sp_pytorch_train/results/model.last10.avg.best --rnnlm exp/train_rnnlm_pytorch_lm/rnnlm.model.best --ngram-model exp/train_ngram/4gram.bin --api v2 
# Started at Tue Jul  7 06:43:16 SAST 2020
#
2020-07-07 06:43:17,423 (asr_recog:253) INFO: python path = (None)
2020-07-07 06:43:17,423 (asr_recog:258) INFO: set random seed = 1
2020-07-07 06:43:17,423 (asr_recog:269) INFO: backend = pytorch
/espnet/tools/venv/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
/espnet/tools/venv/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import of 'jit' requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
2020-07-07 06:43:36,734 (recog:34) WARNING: experimental API for custom LMs is selected by --api v2
2020-07-07 06:43:36,748 (deterministic_utils:26) INFO: torch type check is disabled
2020-07-07 06:43:36,748 (asr_utils:478) INFO: reading a config file from exp/train_sp_pytorch_train/results/model.json
2020-07-07 06:43:36,774 (asr_init:169) WARNING: reading model parameters from exp/train_sp_pytorch_train/results/model.last10.avg.best
2020-07-07 06:43:37,215 (encoder:131) INFO: encoder self-attention layer type = self-attention
2020-07-07 06:43:38,040 (decoder:112) INFO: decoder self-attention layer type = self-attention
2020-07-07 06:43:39,541 (asr_utils:478) INFO: reading a config file from exp/train_rnnlm_pytorch_lm/model.json
2020-07-07 06:43:40,408 (recog:123) INFO: Decoding device=cpu, dtype=torch.float32
2020-07-07 06:43:40,490 (recog:133) INFO: (1/598) decoding BAC009S0764W0121
2020-07-07 06:43:41,399 (beam_search:353) INFO: max output length: 103
2020-07-07 06:43:41,399 (beam_search:354) INFO: min output length: 0
Traceback (most recent call last):
  File "/espnet/espnet/bin/asr_recog.py", line 311, in <module>
    main(sys.argv[1:])
  File "/espnet/espnet/bin/asr_recog.py", line 281, in main
    recog_v2(args)
  File "/espnet/espnet/asr/pytorch_backend/recog.py", line 138, in recog_v2
    x=enc, maxlenratio=args.maxlenratio, minlenratio=args.minlenratio
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/espnet/espnet/nets/beam_search.py", line 361, in forward
    best = self.search(running_hyps, x)
  File "/espnet/espnet/nets/beam_search.py", line 321, in search
    states=self.merge_states(states, part_states, part_j),
  File "/espnet/espnet/nets/beam_search.py", line 276, in merge_states
    new_states[k] = d.select_state(part_states[k], part_idx)
  File "/espnet/espnet/nets/scorer_interface.py", line 51, in select_state
    return None if state is None else state[i]
**TypeError: 'kenlm.State' object is not subscriptable**
# Accounting: time=27 threads=1
# Ended (code 1) at Tue Jul  7 06:43:43 SAST 2020, elapsed time 27 seconds

**Comment by qmpzzpmq** [comment]
@astikbiswas Could you update to the newest version? It seems already fixed by new ngram batch PR

**Comment by astikbiswas** [comment]
My Espnet version is not older than two week. However I will do as per your suggestion. Thanks @qmpzzpmq .

**Comment by tbright17** [comment]
> @astikbiswas Could you update to the newest version? It seems already fixed by new ngram batch PR

Same issue here. Could you please point to that specific PR? Thanks.

**Comment by qmpzzpmq** [comment]
@tbright17 
https://github.com/espnet/espnet/pull/2066

**Comment by RenJinan** [comment]
I encountered the same problem as you. Have you solved it?

**Comment by astikbiswas** [comment]
@RenJinan if you set --ngram-scorer "full", it should work fine...

**Comment by sw005320** [comment]
@astikbiswas and @qmpzzpmq, do you mean that it still has a problem when `--ngram-scorer "part"`?

**Comment by qmpzzpmq** [comment]
I fix this, after #2066 , both work.

**Comment by sw005320** [comment]
Thanks. I just wanted to confirm it because the same question has been posted several times.

**Comment by kamo-naoyuki** [comment]
@qmpzzpmq  Could you add a unittest for NgramPartScorer?

**Comment by qmpzzpmq** [comment]
Yes, I will, but later.

**Comment by sunnnnnnnny** [comment]
@astikbiswas  hello, I meet the same problem.where is "--ngram-scorer" hyper?

**Comment by astikbiswas** [comment]
@sunnnnnnnny please find the snippet:-

`  asr_recog.py \
            --config ${decode_config} \
            --ngpu ${ngpu} \
            --backend ${backend} \
            --batchsize 0 \
            --recog-json ${feat_recog_dir}/split${nj}utt/data.JOB.json \
            --result-label ${expdir}/${decode_dir}/data.JOB.json \
            --model ${expdir}/results/${recog_model}  \
            --rnnlm ${lmexpdir}/rnnlm.model.best \
            --ngram-model ${ngramexpdir}/${n_gram}gram.bin \
            --ngram-scorer "full" \
            --api v2`

**Comment by cosmo1995** [comment]
same problem with "--ngram-scorer part" . It works fine using "--ngram-scorer full" , but decoding is slower.

**Comment by sunnnnnnnny** [comment]
@astikbiswas  ok,thank you. I see it, i set `ngram-weight =0.0` solve it ,Hhhhhh.

**Comment by astikbiswas** [comment]
Hello,

making ngram scorer weight to 0, does not have any effect on n-gram on the
final output.

**Comment by qmpzzpmq** [comment]
WIP, I found it indeed exists.

**Comment by cosmo1995** [comment]
add 
def select_state(self, state, i):
    return state    
in "ngram.py" solves this problem. 
Is this right?

**Comment by qmpzzpmq** [comment]
@cosmo1995 yes
as https://github.com/espnet/espnet/pull/2299

**Comment by cosmo1995** [comment]
OK, that's fine. I did not see that.
