### ISSUE TITLE
Use GPU decoding but raise CUDA error: all CUDA-capable devices are busy or unavailable

### ISSUE THREAD

**Issue by JiayiFu** [espnet/espnet#2160]
Hi,
    I'm running the LibriSpeech recipe. Up to stage 4, all went well. Next, I run stage 5 for decoding. 
    I modified the run.sh refer to https://espnet.github.io/espnet/tutorial.html#use-of-gpu: 
        1. remove ngpu=0; 2. set batch-size=1 and then run the cmd:`run.sh --stage 5 --ngpu 1 --nj 1`. 
    It failed and returned an error: 

```
      Traceback (most recent call last):
        File "/home/fujiayi/Project/GitHub/espnet/egs/librispeech/asr1_test/../../../espnet/bin/asr_recog.py", line 311, in <module>
          main(sys.argv[1:])
        File "/home/fujiayi/Project/GitHub/espnet/egs/librispeech/asr1_test/../../../espnet/bin/asr_recog.py", line 281, in main
          recog_v2(args)
        File "/usr/local/lib/python3.6/dist-packages/espnet/asr/pytorch_backend/recog.py", line 124, in recog_v2
          model.to(device=device, dtype=dtype).eval()
        File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 425, in to
          return self._apply(convert)
        File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 201, in _apply
          module._apply(fn)
        File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 201, in _apply
          module._apply(fn)
        File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 201, in _apply
          module._apply(fn)
        [Previous line repeated 1 more time]
        File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 223, in _apply
          param_applied = fn(param)
        File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 423, in convert
          return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
      RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
````

But the training stages(stage 3 and 4) can run will so I'm confused why it can't find GPUs in stage 5.
The following is the stage 5 codes in my run.sh:

```
        ngpu=1

        # set batchsize 0 to disable batch decoding
        ${decode_cmd} JOB=1:${nj} ${expdir}/${decode_dir}/log/decode.JOB.log \
            asr_recog.py \
            --config ${decode_config} \
            --ngpu ${ngpu} \
            --backend ${backend} \
            --batchsize 1 \
            --recog-json ${feat_recog_dir}/split${nj}utt/data_${bpemode}${nbpe}.JOB.json \
            --result-label ${expdir}/${decode_dir}/data.JOB.json \
            --model ${expdir}/results/${recog_model}  \
            --api v2
            # --rnnlm ${lmexpdir}/${lang_model} \
```
Can anybody tell me is there any mistakes in my scripts? Thank you!

**Comment by ReinholdM** [comment]
Hi! Have you solved your problem? Did you attempt modifying _batchsize_ in `asr_recog.py`?

**Comment by JiayiFu** [comment]
@ReinholdM No, I haven't solved this problem. I tried to change the batch size to 1 but it still raised the same error. Did you meet the same problem? or do you have any solutions?

**Comment by sw005320** [comment]
`RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable`

It seems that you wrongly used a GPU, which is already occupied by the other job.
Please check the correct usage of using a GPU job.

**Comment by JiayiFu** [comment]
@sw005320 I also think there should be some mistakes with the way of my use. I close this first.

**Comment by Guapi1997** [comment]
> 
> 
> @sw005320 I also think there should be some mistakes with the way of my use. I close this first.

hi, you solve this problem now? I face the  problem, so want to hope some help
