### ISSUE TITLE
espnet2/train/reporter.py causes exception if  accum_grad is not 1

### ISSUE THREAD

**Issue by hchung12** [espnet/espnet#2261]
If accum_grad is not 1,  the number of elements of some keys such as 'optim_step_time' are not equal to the count value.
So, it causes the exception at line 175 of reporter.py

Here is the sample. 
when accum_grad = 2, self.count=2, but the number of 'optim_step_time' items is 1.

defaultdict(<class 'list'>, {'iter_time': [Average(value=0.1262605399970198), Average(value=8.855300256982446e-05)], 'forward_time': [Average(value=0.36080345801019575), Average(value=0.0742439620080404)], 'loss': [WeightedAverage(value=98.05116271972656, weight=64), WeightedAverage(value=327.82421875, weight=64)], 'loss_att': [WeightedAverage(value=27.909347534179688, weight=64), WeightedAverage(value=108.47477722167969, weight=64)], 'loss_ctc': [WeightedAverage(value=261.71539306640625, weight=64), WeightedAverage(value=839.6395263671875, weight=64)], 'acc': [WeightedAverage(value=0.0, weight=64), WeightedAverage(value=0.0, weight=64)], 'backward_time': [Average(value=0.22204561799298972), Average(value=0.20624846100690775)], 'optim_step_time': [Average(value=0.03714967500127386)], 'lr_0': [Average(value=2.2222222222222224e-07)], 'train_time': [Average(value=1.294450648012571)]})

**Comment by kamo-naoyuki** [comment]
Would you show the raw error log?

**Comment by hchung12** [comment]
Here is the raw error log.

Traceback (most recent call last):
  File "/SPL37/bin/espnet/tools/venv/envs/espnet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/SPL37/bin/espnet/tools/venv/envs/espnet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/SPL37/bin/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/SPL37/bin/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/SPL37/bin/espnet/espnet2/tasks/abs_task.py", line 883, in main
    cls.main_worker(args)
  File "/SPL37/bin/espnet/espnet2/tasks/abs_task.py", line 1222, in main_worker
    distributed_option=distributed_option,
  File "/SPL37/bin/espnet/espnet2/train/trainer.py", line 213, in run
    options=trainer_options,
  File "/SPL37/bin/espnet/espnet2/train/trainer.py", line 467, in train_one_epoch
    logging.info(reporter.log_message(-log_interval))
  File "/SPL37/bin/espnet/espnet2/train/reporter.py", line 176, in log_message
    "The registered stats must have same number of values: "
RuntimeError: The registered stats must have same number of values: 463 != 926

**Comment by kamo-naoyuki** [comment]
Thanks.
