### ISSUE TITLE
dependency on missing chainer_ctc.warpctc

### ISSUE THREAD

**Issue by mdeisher** [espnet/espnet#234]
I hope this is not a duplicate of #115.  It is not clear to me.  But asr_train.py fails due to a missing chainer component:

```
# asr_train.py --ngpu 1 --backend chainer --outdir exp/train_trim_vggblstmp_e6_subsample1_2_2_1_1_unit320_proj320_d1_unit300_location_adim320_aconvc10_aconvf100_mtlalpha0.5_ada
delta_bs30_mli800_mlo150/results --debugmode 1 --dict data/lang_1char/train_trim_units.txt --debugdir exp/train_trim_vggblstmp_e6_subsample1_2_2_1_1_unit320_proj320_d1_unit300_
location_adim320_aconvc10_aconvf100_mtlalpha0.5_adadelta_bs30_mli800_mlo150 --minibatches 0 --verbose 0 --resume --train-json dump/train_trim/deltafalse/data.json --valid-json 
dump/dev_trim/deltafalse/data.json --etype vggblstmp --elayers 6 --eunits 320 --eprojs 320 --subsample 1_2_2_1_1 --dlayers 1 --dunits 300 --atype location --adim 320 --aconv-ch
ans 10 --aconv-filts 100 --mtlalpha 0.5 --batch-size 30 --maxlen-in 800 --maxlen-out 150 --opt adadelta --epochs 15 
# Started at Sun Jun 17 05:54:32 PDT 2018
#
2018-06-17 05:54:32,734 (asr_train:146) WARNING: Skip DEBUG/INFO messages
2018-06-17 05:54:32,768 (asr_train:186) WARNING: CUDA_VISIBLE_DEVICES is not set.
Traceback (most recent call last):
  File "/home/mdeisher/espnet-20180613/egs/tedlium/asr1/../../../src/bin/asr_train.py", line 224, in <module>
    main()
  File "/home/mdeisher/espnet-20180613/egs/tedlium/asr1/../../../src/bin/asr_train.py", line 214, in main
    from asr_chainer import train
  File "/home/mdeisher/espnet-20180613/src/asr/asr_chainer.py", line 38, in <module>
    from e2e_asr_attctc import E2E
  File "/home/mdeisher/espnet-20180613/src/nets/e2e_asr_attctc.py", line 21, in <module>
    from chainer_ctc.warpctc import ctc as warp_ctc
ImportError: No module named chainer_ctc.warpctc
# Accounting: time=1 threads=1
# Ended (code 1) at Sun Jun 17 05:54:33 PDT 2018, elapsed time 1 seconds
```
Where does chainer_ctc.warpctc normally come from?

**Comment by sw005320** [comment]
I'm expecting that chainer warp_ctc is not correctly installed at https://github.com/espnet/espnet/blob/master/tools/Makefile#L45
Please move to the `tools` directory, and build chainer warp_ctc again, e.g.,
```
$ cd espnet/tools
$ rm -fr chainer_ctc
$ make chainer_ctc
```

**Comment by mdeisher** [comment]
Thank you!  The problem was that chainer will not compile using gcc version 6.x (default compiler on Ubuntu 16.04).  Setting "export CC=gcc-5" and "export CXX=g++-5" and following your suggestion solved the problem.

**Comment by kan-bayashi** [comment]
It seems to be solved. Close issue.

**Comment by 3139725181** [comment]
expr: syntax error
make: *** No rule to make target 'chainer_ctc'.  Stop.
