### ISSUE TITLE
Specifying SLURM constraints

### ISSUE THREAD

**Issue by picheny-nyu** [espnet/espnet#2417]
Where would I add a set of slurm constraints e.g. constraint="blah" (I work in a heterogenous computing environment and only some of the machines have a high enough level gpu for me to run on).

**Comment by picheny-nyu** [comment]
I got something running but I got  the following error (esg2 ami recipe, 4 gpus). Any idea? 

[lion15:0/4] 2020-09-05 20:04:10,182 (lm:187) INFO: Vocabulary size: 35
Traceback (most recent call last):
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-may142020/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-may142020/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/misc/vlgscratch4/PichenyGroup/picheny/espnet/espnet2/bin/lm_train.py", line 22, in <module>
    main()
  File "/misc/vlgscratch4/PichenyGroup/picheny/espnet/espnet2/bin/lm_train.py", line 18, in main
    LMTask.main(cmd=cmd)
  File "/misc/vlgscratch4/PichenyGroup/picheny/espnet/espnet2/tasks/abs_task.py", line 944, in main
    while not ProcessContext(processes, error_queues).join():
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-may142020/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 108, in join
    (error_index, name)
Exception: process 0 terminated with signal SIGKILL
# Accounting: begin_time=1599350596
# Accounting: end_time=1599350679
# Accounting: time=83 threads=1
# Finished at Sat Sep 5 20:04:39 EDT 2020 with status 1

**Comment by kamo-naoyuki** [comment]
There are many possibilities to kill the process as your log looks, it's impossible to figure out your problem. No one can.

I recommend you:

- Testing single gpu with same setting
- Submitting  not espnet with same setting

This is not problem of espnet, but just setting of Slurm or your machine. I'll close.

**Comment by picheny-nyu** [comment]
Can I just verify that multi gpu support works in espnet for the esg2 recipes? There is a cryptic not in the documentation that it is flakey. 

Also, I think you do this through the distributed training mechanism of pytorch. Is that correct? 

Last, I am also am not sure where to add slurm constraints. In slurm.pl or in slurm.conf? 

Thanks
Michael

**Comment by kan-bayashi** [comment]
See about distributed training: 
https://espnet.github.io/espnet/espnet2_distributed.html

You can modify `slurm.conf`. See:
https://espnet.github.io/espnet/parallelization.html
