### ISSUE TITLE
KeyError: 'validation/main/loss' in Pytorch

### ISSUE THREAD

**Issue by ShigekiKarita** [espnet/espnet#247]
I found that chainer reporter could not work with pytorch (from 0.4.0) anymore.

- testing with an4 (--backend chainer or pytorch 0.3.1.post2 is working)
- commit b2420d8492c7aa21049b8c712e6054e86de368ec (yesterday)
```
/data/work49/skarita/dev/espnet/src/nets/e2e_asr_attctc_th.py:294: UserWarning: volatile was removed and now has no effect. Use `w
ith torch.no_grad():` instead.                                                                                                    
  ys = [to_cuda(self, Variable(torch.from_numpy(y), volatile=True)) for y in ys]                                                  
/data/work49/skarita/dev/espnet/src/nets/e2e_asr_attctc_th.py:302: UserWarning: volatile was removed and now has no effect. Use `w
ith torch.no_grad():` instead.                                                                                                    
  hs = [to_cuda(self, Variable(torch.from_numpy(xx), volatile=True)) for xx in xs]                                                
/data/work49/skarita/dev/espnet/src/nets/e2e_asr_attctc_th.py:381: UserWarning: volatile was removed and now has no effect. Use `w
ith torch.no_grad():` instead.                                                                                                    
  ys = [to_cuda(self, Variable(torch.from_numpy(y), volatile=True)) for y in ys]                                                  
/data/work49/skarita/dev/espnet/src/nets/e2e_asr_attctc_th.py:386: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.  
  hs = [to_cuda(self, Variable(torch.from_numpy(xx), volatile=True)) for xx in xs]                                                
Exception in main training loop: 'validation/main/loss'          
Traceback (most recent call last):                               
  File "/home/skarita/work/dev/espnet/tools/venv/lib/python3.6/site-packages/chainer/training/trainer.py", line 308, in run       
    if entry.trigger(self):     
  File "/home/skarita/work/dev/espnet/tools/venv/lib/python3.6/site-packages/chainer/training/triggers/minmax_value_trigger.py", line 52, in __call__             
    value = float(stats[key])  # copy to CPU                     
Will finalize trainer extensions and updater before reraising the exception.                                                      
Traceback (most recent call last):                               
  File "/data/work49/skarita/dev/espnet/egs/just/asr1/../../../src/bin/asr_train.py", line 224, in <module>                       
    main()                      
  File "/data/work49/skarita/dev/espnet/egs/just/asr1/../../../src/bin/asr_train.py", line 218, in main                           
    train(args)                 
  File "/data/work49/skarita/dev/espnet/src/asr/asr_pytorch.py", line 375, in train                                               
    trainer.run()               
  File "/home/skarita/work/dev/espnet/tools/venv/lib/python3.6/site-packages/chainer/training/trainer.py", line 320, in run       
    six.reraise(*sys.exc_info())
  File "/home/skarita/work/dev/espnet/tools/venv/lib/python3.6/site-packages/six.py", line 693, in reraise                        
    raise value                 
  File "/home/skarita/work/dev/espnet/tools/venv/lib/python3.6/site-packages/chainer/training/trainer.py", line 308, in run       
    if entry.trigger(self):     
  File "/home/skarita/work/dev/espnet/tools/venv/lib/python3.6/site-packages/chainer/training/triggers/minmax_value_trigger.py", line 52, in __call__             
    value = float(stats[key])  # copy to CPU                     
KeyError: 'validation/main/loss'                                 
# Accounting: time=344 threads=1                                 
# Ended (code 1) at 2018年  6月 21日 木曜日 10:22:34 JST, elapsed time 344 seconds 
```

Here are two options for us.
1. find out what is wrong with chainer' callback hell
2. make pytorch script independent from chainer (reporter, iterator)

I prefer the second one because I already prototyped such modules compatible to chainer. it can report plots and iterate over for-loops.

**Comment by ShigekiKarita** [comment]
Accidentally, I fixed the first option in #250.

**Comment by kan-bayashi** [comment]
@ShigekiKarita In my case, reporter is working in pytorch v0.4 (#226)

**Comment by ShigekiKarita** [comment]
So it may be caused by the latest chainer? BTW I would look into your branch (I have not worked on LM parts). Thanks.
