### ISSUE TITLE
ESPnet2 ljspeech TTS error with conf/tuning/train_fastspeech2.yaml

### ISSUE THREAD

**Issue by hchung12** [espnet/espnet#2513]
In egs2/ljspeech/tts1, run.sh succeeded with tuning/train_tacotron2.yaml config, but it caused the following error with conf/tuning/train_fastspeech2.yaml.

Traceback (most recent call last):
  File "/SPL37/bin/espnet/tools/venv/envs/espnet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/SPL37/bin/espnet/tools/venv/envs/espnet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/SPL37/bin/espnet/espnet2/bin/tts_train.py", line 22, in <module>
    main()
  File "/SPL37/bin/espnet/espnet2/bin/tts_train.py", line 18, in main
    TTSTask.main(cmd=cmd)
  File "/SPL37/bin/espnet/espnet2/tasks/abs_task.py", line 932, in main
    cls.main_worker(args)
  File "/SPL37/bin/espnet/espnet2/tasks/abs_task.py", line 1162, in main_worker
    write_collected_feats=args.write_collected_feats,
  File "/SPL37/bin/espnet/tools/venv/envs/espnet/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/SPL37/bin/espnet/espnet2/main_funcs/collect_stats.py", line 72, in collect_stats
    data = model.collect_feats(**batch)
  File "/SPL37/bin/espnet/espnet2/tts/espnet_model.py", line 138, in collect_feats
    durations_lengths=durations_lengths,
  File "/SPL37/bin/espnet/tools/venv/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/SPL37/bin/espnet/espnet2/tts/feats_extract/dio.py", line 113, in forward
    for p, d in zip(pitch, durations)
TypeError: zip argument #2 must support iteration

**Comment by kan-bayashi** [comment]
See https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#fastspeech2-training

**Comment by hchung12** [comment]
Thanks!
