### ISSUE TITLE
Training fails in espnet2 JSUT ASR stage 9

### ISSUE THREAD

**Issue by Co-Graph-Okuda** [espnet/espnet#2618]
**Describe the issue**
Training fails in espnet2 JSUT ASR stage 9

Initially, pip couldn't install llvmlite, so I used easy_install to install llvmlite.
When using llvmlite, I got the error `OSError: Could not load shared object file: libllvmlite.so` in ./run.sh --stage 3.
I gave up using llvmlite and installed `pip install resampy == 0.15 librosa == 0.1.5`.
./run.sh --stage 8 was successful, but --stage 9 gave the following error:
```
  File "/home/sivoice/espnet/tools/venv/lib/python3.6/site-packages/librosa/filters.py", line 238, in mel
    lower = -ramps[i] / fdiff[i]
ValueError: operands could not be broadcast together with shapes (1,257) (0,)
```
I'm getting an error in librosa, but I don't know how to solve it. Please tell me how to resolve.

**Show the `check_install.py` status by using the following command**
```
cd <espnet-root>/tools
. ./activate_python.sh; python3 check_install.py
INFO: 8 / 8 libraries are correctly installed.
```

**Basic environments:**
 - OS information: Linux version 4.15.0-122-generic (buildd@lgw01-amd64-036) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020
 - python version: 3.6.9 [GCC 7.5.0]
 - espnet version: 0.9.4
 - Git hash c1e81983f035923fc0b47a266ec73a292f3e0c43
   - Commit date Wed Sep 30 20:04 2020 +0900
 - torch version: 1.7.0
 
**Environments from `torch.utils.collect_env`:**
e.g.,
```
Collecting environment information...
Torch version: 1.7.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.5 LTS
GCC version: (GCC) 7.5.0
CMake version: version 3.10.2

Python version: 3.6.9
Is CUDA available: Yes
CUDA runtime version: 10.2
GPU models and configuration:
GeForce GTX 1060

Nvidia driver version: 450.80.02
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.3
[pip3] pytorch-wpe==0.0.0
[pip3] torch==1.7.0
[pip3] torch-complex==0.2.0
[pip3] torchvision==0.8.1
[conda] Could not collect
```

**To Reproduce**
Steps to reproduce the behavior by showing us the specific installation commands with their arguments, e.g.,
```
cd <espnet-root>/egs2/jsut/asr1
./run.sh --stage 9 --asr_config conf/train_asr_transformer.yaml
```

**Error logs**
```
2020-11-02T09:12:01 (asr.sh:212:main) ./asr.sh --lang jp --token_type char --feats_type raw --fs 16000 --speed_perturb_factors 0.9 1.0 1.1 --local_data_opts --fs 16000 --asr_config conf/train_asr_conformer.yaml --inference_config conf/decode_transformer.yaml --lm_config conf/train_lm.yaml --train_set tr_no_dev --valid_set dev --test_sets dev eval1 --srctexts data/tr_no_dev/text --audio_format flac --asr_config conf/train_asr_transformer.yaml --stage 9
2020-11-02T09:12:01 (asr.sh:790:main) Stage 9: ASR collect stats: train_set=dump/raw/tr_no_dev_sp, valid_set=dump/raw/dev
2020-11-02T09:12:01 (asr.sh:840:main) Generate 'exp/asr_stats_raw_sp/run.sh'. You can resume the process from stage 9 using this script
2020-11-02T09:12:01 (asr.sh:844:main) ASR collect-stats started... log: 'exp/asr_stats_raw_sp/logdir/stats.*.log'
run.pl: 32 / 32 failed, log is in exp/asr_stats_raw_sp/logdir/stats.*.log
# python3 -m espnet2.bin.asr_train --collect_stats true --use_preprocessor true --bpemodel none --token_type char --token_list data/token_list/char/tokens.txt --non_linguistic_symbols none --cleaner none --g2p none --train_data_path_and_name_and_type dump/raw/tr_no_dev_sp/wav.scp,speech,sound --train_data_path_and_name_and_type dump/raw/tr_no_dev_sp/text,text,text --valid_data_path_and_name_and_type dump/raw/dev/wav.scp,speech,sound --valid_data_path_and_name_and_type dump/raw/dev/text,text,text --train_shape_file exp/asr_stats_raw_sp/logdir/train.1.scp --valid_shape_file exp/asr_stats_raw_sp/logdir/valid.1.scp --output_dir exp/asr_stats_raw_sp/logdir/stats.1 --config conf/train_asr_transformer.yaml --frontend_conf fs=16000 
# Started at Mon Nov  2 09:12:01 JST 2020
#
/home/sivoice/espnet/tools/venv/bin/python3 /home/sivoice/espnet/tools/venv/lib/python3.6/site-packages/espnet2/bin/asr_train.py --collect_stats true --use_preprocessor true --bpemodel none --token_type char --token_list data/token_list/char/tokens.txt --non_linguistic_symbols none --cleaner none --g2p none --train_data_path_and_name_and_type dump/raw/tr_no_dev_sp/wav.scp,speech,sound --train_data_path_and_name_and_type dump/raw/tr_no_dev_sp/text,text,text --valid_data_path_and_name_and_type dump/raw/dev/wav.scp,speech,sound --valid_data_path_and_name_and_type dump/raw/dev/text,text,text --train_shape_file exp/asr_stats_raw_sp/logdir/train.1.scp --valid_shape_file exp/asr_stats_raw_sp/logdir/valid.1.scp --output_dir exp/asr_stats_raw_sp/logdir/stats.1 --config conf/train_asr_transformer.yaml --frontend_conf fs=16000
[salesidolvoice] 2020-11-02 09:12:03,122 (asr:283) INFO: Vocabulary size: 2742
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sivoice/espnet/tools/venv/lib/python3.6/site-packages/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/home/sivoice/espnet/tools/venv/lib/python3.6/site-packages/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/home/sivoice/espnet/tools/venv/lib/python3.6/site-packages/espnet2/tasks/abs_task.py", line 941, in main
    cls.main_worker(args)
  File "/home/sivoice/espnet/tools/venv/lib/python3.6/site-packages/espnet2/tasks/abs_task.py", line 1037, in main_worker
    model = cls.build_model(args=args)
  File "/home/sivoice/espnet/tools/venv/lib/python3.6/site-packages/espnet2/tasks/asr.py", line 289, in build_model
    frontend = frontend_class(**args.frontend_conf)
  File "/home/sivoice/espnet/tools/venv/lib/python3.6/site-packages/espnet2/asr/frontend/default.py", line 69, in __init__
    htk=htk,
  File "/home/sivoice/espnet/tools/venv/lib/python3.6/site-packages/espnet2/layers/log_mel.py", line 49, in __init__
    melmat = librosa.filters.mel(**_mel_options)
  File "/home/sivoice/espnet/tools/venv/lib/python3.6/site-packages/librosa/filters.py", line 238, in mel
    lower = -ramps[i] / fdiff[i]
ValueError: operands could not be broadcast together with shapes (1,257) (0,) 
# Accounting: time=2 threads=1
# Ended (code 1) at Mon Nov  2 09:12:03 JST 2020, elapsed time 2 seconds
```

**Comment by kan-bayashi** [comment]
It seems `librosa == 0.1.5` is too old...

**Comment by Co-Graph-Okuda** [comment]
Thanks, but if install librosa==0.8.0, I'm getting the error `OSError: Could not load shared object file: libllvmlite.so`. If install librosa 2.0 or higher version, it seems like librosa is looking for llvmlite. However, it fails because llvnlite is not installed.

**Comment by kan-bayashi** [comment]
That is not an issue of the ESPnet installation.
Please check the related issue in librosa or llvm github.
https://github.com/librosa/librosa/issues/1116

**Comment by Co-Graph-Okuda** [comment]
Sorry my company does not recommend to use conda.

Solved the llvmlite issue on GPU machine.
If we don't use livmlite, we have to use librosa, but if we use librosa, matrix calculation will be failed, so we have to use livmlite.
We cannot install livmlite with pip. Easy_install is only installed, it is not built and libllvmlite.so is not generated, so we have to install llvm with homebrew.
```
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
```
Just in case, install gcc with homebrew.
```
brew install gcc
```
I could not find llvm version 10, so I installed llvm version 9.
```
brew install llvm@9
```
Set the following environment variables.
```
export PATH='/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin':"$PATH"
export LDFLAGS="-L/home/linuxbrew/.linuxbrew/opt/isl@0.18/lib"
export CPPFLAGS="-I/home/linuxbrew/.linuxbrew/opt/isl@0.18/include"
export PKG_CONFIG_PATH="/home/linuxbrew/.linuxbrew/opt/isl@0.18/lib/pkgconfig"
export LDFLAGS="-L/home/linuxbrew/.linuxbrew/opt/llvm@9/lib"
export CPPFLAGS="-I/home/linuxbrew/.linuxbrew/opt/llvm@9/include"
export LLVM_CONFIG=/home/linuxbrew/.linuxbrew/Cellar/llvm@9/9.0.1_3/bin/llvm-config
```
Finally, I could install llvmlite using pip.
```
pip install llvmlite
```

**Comment by kan-bayashi** [comment]
@Co-Graph-Okuda Thank you for sharing the solution.
This will help someone who has a similar problem.

**Comment by Co-Graph-Okuda** [comment]
You are welcome!
