### ISSUE TITLE
Unable to run any of the cpu docker versions

### ISSUE THREAD

**Issue by gitty-git-git** [espnet/espnet#2651]
**Describe the issue**
I am trying to run the cpu docker version and am unable to. I've tried 3 different versions and all come out with various errors.

**Show the `check_install.py` status by using the following command**
I don't think it applies since I am running the docker version.

**Basic environments:**
I am running Ubuntu 20.04.1 LTS and Docker version 19.03.13, build 4484c46d9d.

**To Reproduce**
Steps to reproduce the behavior by showing us the specific installation commands with their arguments, e.g.,

```
$ ./run.sh --docker-gpu -1 --docker-egs an4/asr1 --ngpu 0
...
...
/espnet/egs/an4/asr1/../../../utils/feat_to_shape.sh --cmd run.pl --nj 1 --filetype  --preprocess-conf  --verbose 0 dump/test/deltafalse/feats.scp data/test/tmp-GUZdu/input_1/shape.scp
stage 3: LM Preparation
WARNING:root:OOV rate = 0.00 %
run.pl: job failed, log is in exp/train_rnnlm_pytorch_lm_word100/train.log
run.sh done.
```
Contents of `train.log`:
```
# lm_train.py --config conf/lm.yaml --ngpu 0 --backend pytorch --verbose 1 --outdir exp/train_rnnlm_pytorch_lm_word100 --tensorboard-dir tensorboard/train_rnnlm_pytorch_lm_word100 --train-label data/local/wordlm
_train/train.txt --valid-label data/local/wordlm_train/valid.txt --test-label data/local/wordlm_train/test.txt --resume --dict data/local/wordlm_train/wordlist_100.txt 
# Started at Sun Nov  8 05:42:41 UTC 2020
#
Traceback (most recent call last):
  File "/espnet/egs/an4/asr1/../../../espnet/bin/lm_train.py", line 284, in <module>
    main(sys.argv[1:])
  File "/espnet/egs/an4/asr1/../../../espnet/bin/lm_train.py", line 204, in main
    model_class = dynamic_import_lm(args.model_module, args.backend)
  File "/espnet/espnet/nets/lm_interface.py", line 82, in dynamic_import_lm
    model_class = dynamic_import(module, predefined_lms.get(backend, dict()))
  File "/espnet/espnet/utils/dynamic_import.py", line 22, in dynamic_import
    m = importlib.import_module(module_name)
  File "/miniconda/envs/espnet/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/espnet/espnet/nets/pytorch_backend/lm/default.py", line 12, in <module>
    from espnet.nets.pytorch_backend.e2e_asr import to_device
  File "/espnet/espnet/nets/pytorch_backend/e2e_asr.py", line 20, in <module>
    from espnet.nets.e2e_asr_common import label_smoothing_dist
  File "/espnet/espnet/nets/e2e_asr_common.py", line 18, in <module>
    from espnet.nets.beam_search_transducer import BeamSearchTransducer
  File "/espnet/espnet/nets/beam_search_transducer.py", line 19, in <module>
    from espnet2.asr.decoder.abs_decoder import AbsDecoder
ModuleNotFoundError: No module named 'espnet2'
# Accounting: time=4 threads=1
# Ended (code 1) at Sun Nov  8 05:42:45 UTC 2020, elapsed time 4 seconds
```
Trying the `esg-2 version` I get a different error:
```
$ ./run.sh --docker-gpu -1 --is-egs2 --docker-egs an4/asr1 --ngpu 0
...
/usr/bin/env: 'python': No such file or directory
run.sh done.
```

I've also tried the local build:
```
$ ./build.sh fully_local cpu
...
...
--2020-11-08 05:51:34--  https://www.openslr.org/resources/4/sctk-2.4.10-20151007-1312Z.tar.bz2
Resolving www.openslr.org (www.openslr.org)... 46.101.158.64
Connecting to www.openslr.org (www.openslr.org)|46.101.158.64|:443... connected.
Unable to establish SSL connection.
Makefile:127: recipe for target 'sctk-2.4.10-20151007-1312Z.tar.bz2' failed
make: *** [sctk-2.4.10-20151007-1312Z.tar.bz2] Error 4
The command '/bin/sh -c cd /kaldi/tools &&     ./extras/install_mkl.sh -sp debian intel-mkl-64bit-2019.2-057 &&     apt-get clean &&     rm -rf /var/lib/apt/lists/* &&     make all &&     rm -r openfst-*/src && 
    ./extras/install_beamformit.sh &&     ./extras/install_irstlm.sh &&     cd /kaldi/src &&     ./configure --shared --use-cuda=no &&     make depend -j${NUM_BUILD_CORES} &&     make -j${NUM_BUILD_CORES} &&    
 find /kaldi/src -name "*.o" -exec rm -f {} \; &&     find /kaldi/src -name "*.o" -exec rm -f {} \;' returned a non-zero code: 2
```

**Error logs**
Paste the error logs. If applicable, add screenshots to help explain your problem.

**Comment by AdolfVonKleist** [comment]
I noticed the same thing this morning, the issue is that the connection www.openslr.org is spotty right now for some reason so this:
```
if [ -d "" ]; then \
	cp -p "/sctk-2.4.10-20151007-1312Z.tar.bz2" .; \
else \
	wget -T 10 https://www.openslr.org/resources/4/sctk-2.4.10-20151007-1312Z.tar.bz2; \
fi
```
is timing out.  It was working intermittently for me for a while, but now I am completely unable to connect.  If you have a copy of the distro lying around or use the source from:

- https://github.com/usnistgov/SCTK

directly, you should be able to get it to run with minor modifications.

**Comment by gitty-git-git** [comment]
Yeah, openslr works on and off. Now I sometimes get: 
```
ln -sf /kaldi/src/nnet2/libkaldi-nnet2.so /kaldi/src/lib/libkaldi-nnet2.so
make[1]: Leaving directory '/kaldi/src/nnet2'
The command '/bin/sh -c cd /kaldi/tools &&     ./extras/install_mkl.sh -sp debian intel-mkl-64bit-2019.2-057 &&     apt-get clean &&     rm -rf /var/lib/apt/lists/* &&     make all &&     rm -r openfst-*/src && 
    ./extras/install_beamformit.sh &&     ./extras/install_irstlm.sh &&     cd /kaldi/src &&     ./configure --shared --use-cuda=no &&     make depend -j${NUM_BUILD_CORES} &&     make -j${NUM_BUILD_CORES} &&    
 find /kaldi/src -name "*.o" -exec rm -f {} \; &&     find /kaldi/src -name "*.o" -exec rm -f {} \;' returned a non-zero code: 2
```

**Comment by AdolfVonKleist** [comment]
I don't see the actual error there.  Not clear what actually went wrong.  Probably one of those steps is failing.

**Comment by AdolfVonKleist** [comment]
It looks like these packages are now being made available directly from the github:

-  https://github.com/kaldi-asr/kaldi/issues/4311#issuecomment-725261830

probably best to update to that if you continue to have problems.
