### ISSUE TITLE
"Operation timed out" in torch.distributed.all_reduce

### ISSUE THREAD

**Issue by Piteryo** [espnet/espnet#2673]
**Describe the bug**
On a custom dataset which is slightly bigger than some default datasets from this repo, there is a problem: when starting new epoch `torch.distributed.all_reduce(iterator_stop, ReduceOp.SUM):372` in `espnet2/train/trainer.py` throws an exception. Restarting the script from the checkpoint of previous epoch works well for one epoch. What can cause this problem?
**Basic environments:**
I'm using 5 Nvidia Tesla V100 GPUs on one node. 
**Error logs**
```
Process SpawnProcess-3:                                                                                                                               
Traceback (most recent call last):                                                                                                                    
  File "/opt/conda/envs/espnet_env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap                                                 
    self.run()                                                                                                                                        
  File "/opt/conda/envs/espnet_env/lib/python3.6/multiprocessing/process.py", line 93, in run                                                         
    self._target(*self._args, **self._kwargs)                                                                                                         
  File "/workspace/espnet_october/espnet2/tasks/abs_task.py", line 1234, in main_worker                                                               
    distributed_option=distributed_option,                                                                                                            
  File "/workspace/espnet_october/espnet2/train/trainer.py", line 210, in run                                                                         
    options=trainer_options,                                                                                                                          
  File "/workspace/espnet_october/espnet2/train/trainer.py", line 372, in train_one_epoch                                                             
    torch.distributed.all_reduce(iterator_stop, ReduceOp.SUM)                                                                                         
  File "/opt/conda/envs/espnet_env/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 911, in all_reduce                        
    work.wait()                                                                                                                                       
RuntimeError: Operation timed out!                                                                                                                    
Process SpawnProcess-4:                                                                                                                               
Traceback (most recent call last):                                                                                                                    
  File "/opt/conda/envs/espnet_env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap                                                 
    self.run()                                                                                                                                        
  File "/opt/conda/envs/espnet_env/lib/python3.6/multiprocessing/process.py", line 93, in run                                                         
    self._target(*self._args, **self._kwargs)                                                                                                         
  File "/workspace/espnet_october/espnet2/tasks/abs_task.py", line 1234, in main_worker                                                               
    distributed_option=distributed_option,                                                                                                            
  File "/workspace/espnet_october/espnet2/train/trainer.py", line 210, in run                                                                         
    options=trainer_options,                                                                                                                          
  File "/workspace/espnet_october/espnet2/train/trainer.py", line 372, in train_one_epoch                                                             
    torch.distributed.all_reduce(iterator_stop, ReduceOp.SUM)                                                                                         
  File "/opt/conda/envs/espnet_env/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 911, in all_reduce                        
    work.wait()                                                                                                                                       
RuntimeError: Operation timed out!
```

**Comment by kamo-naoyuki** [comment]
Several reasons are possible. Bug or connection error. If it's connection error, it's very hard to help for me.
Please show more log. Need for all errors from all processes to detect the reason.

**Comment by Piteryo** [comment]
It seems that setting `multiprocessing_distributed` to `false` fixes this issue.

**Comment by kamo-naoyuki** [comment]
You haven't resolved nothing.
multiprocessing_distributed=false disables distributed training for multi gpus training. It decrease the training speed.

**Comment by kamo-naoyuki** [comment]
Show all error log.

**Comment by panpanli521** [comment]
I run into this error after one epoch is finished, the log is:
```
Process SpawnProcess-4:
Traceback (most recent call last):
  File "/miniconda/envs/espnet/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/miniconda/envs/espnet/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/espnet/espnet2/tasks/abs_task.py", line 1309, in main_worker
    find_unused_parameters=args.unused_parameters,
  File "/espnet/espnet2/train/trainer.py", line 217, in run
    options=trainer_options,
  File "/espnet/espnet2/train/trainer.py", line 384, in train_one_epoch
    torch.distributed.all_reduce(iterator_stop, ReduceOp.SUM)
  File "/miniconda/envs/espnet/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 911, in all_reduce
    work.wait()
RuntimeError: Operation timed out!
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/miniconda/envs/espnet/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/miniconda/envs/espnet/lib/python3.7/multiprocessing/process.py", line 99, in run
   self._target(*self._args, **self._kwargs)
  File "/espnet/espnet2/tasks/abs_task.py", line 1309, in main_worker
    find_unused_parameters=args.unused_parameters,
  File "/espnet/espnet2/train/trainer.py", line 217, in run
    options=trainer_options,
  File "/espnet/espnet2/train/trainer.py", line 384, in train_one_epoch
    torch.distributed.all_reduce(iterator_stop, ReduceOp.SUM)
  File "/miniconda/envs/espnet/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 911, in all_reduce
    work.wait()
RuntimeError: Operation timed out!
Process SpawnProcess-6:
Traceback (most recent call last):
  File "/miniconda/envs/espnet/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/miniconda/envs/espnet/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/espnet/espnet2/tasks/abs_task.py", line 1309, in main_worker
    find_unused_parameters=args.unused_parameters,
  File "/espnet/espnet2/train/trainer.py", line 217, in run
    options=trainer_options,
  File "/espnet/espnet2/train/trainer.py", line 384, in train_one_epoch
    torch.distributed.all_reduce(iterator_stop, ReduceOp.SUM)
  File "/miniconda/envs/espnet/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 911, in all_reduce
    work.wait()
RuntimeError: Operation timed out!
Process SpawnProcess-3:
Traceback (most recent call last):
  File "/miniconda/envs/espnet/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/miniconda/envs/espnet/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/espnet/espnet2/tasks/abs_task.py", line 1309, in main_worker
    find_unused_parameters=args.unused_parameters,
  File "/espnet/espnet2/train/trainer.py", line 217, in run
  options=trainer_options,
  File "/espnet/espnet2/train/trainer.py", line 384, in train_one_epoch
    torch.distributed.all_reduce(iterator_stop, ReduceOp.SUM)
  File "/miniconda/envs/espnet/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 911, in all_reduce
    work.wait()
RuntimeError: Operation timed out!
Process SpawnProcess-7:
Traceback (most recent call last):
  File "/miniconda/envs/espnet/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/miniconda/envs/espnet/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/espnet/espnet2/tasks/abs_task.py", line 1309, in main_worker
    find_unused_parameters=args.unused_parameters,
  File "/espnet/espnet2/train/trainer.py", line 217, in run
    options=trainer_options,
  File "/espnet/espnet2/train/trainer.py", line 384, in train_one_epoch
    torch.distributed.all_reduce(iterator_stop, ReduceOp.SUM)
  File "/miniconda/envs/espnet/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 911, in all_reduce
    work.wait()
RuntimeError: Operation timed out!
Process SpawnProcess-8:
Traceback (most recent call last):
  File "/miniconda/envs/espnet/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/miniconda/envs/espnet/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/espnet/espnet2/tasks/abs_task.py", line 1309, in main_worker
    find_unused_parameters=args.unused_parameters,
  File "/espnet/espnet2/train/trainer.py", line 217, in run
    options=trainer_options,
  File "/espnet/espnet2/train/trainer.py", line 384, in train_one_epoch
    torch.distributed.all_reduce(iterator_stop, ReduceOp.SUM)
  File "/miniconda/envs/espnet/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 911, in all_reduce
    work.wait()
RuntimeError: Operation timed out!
Process SpawnProcess-5:
Traceback (most recent call last):
File "/miniconda/envs/espnet/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/miniconda/envs/espnet/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/espnet/espnet2/tasks/abs_task.py", line 1309, in main_worker
    find_unused_parameters=args.unused_parameters,
  File "/espnet/espnet2/train/trainer.py", line 217, in run
    options=trainer_options,
  File "/espnet/espnet2/train/trainer.py", line 384, in train_one_epoch
    torch.distributed.all_reduce(iterator_stop, ReduceOp.SUM)
  File "/miniconda/envs/espnet/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 911, in all_reduce
    work.wait()
RuntimeError: Operation timed out!
/miniconda/envs/espnet/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 11 leaked semaphores to clean up at shutdown
  len(cache))
Traceback (most recent call last):
  File "/miniconda/envs/espnet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/miniconda/envs/espnet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/espnet/espnet2/tasks/abs_task.py", line 1040, in main
    while not ProcessContext(processes, error_queues).join():
  File "/miniconda/envs/espnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 112, in join
    (error_index, exitcode)
Exception: process 3 terminated with exit code 1
# Accounting: time=5844 threads=1
# Ended (code 1) at Mon Jan 18 15:19:22 UTC 2021, elapsed time 5844 seconds
```
I run `espnet/egs2/librispeech/asr1` and corpus is from `http://www.openslr.org/12/`, the environment is one node with 8 V100 GPU.  @kamo-naoyuki

**Comment by panpanli521** [comment]
dfsfa

**Comment by kamo-naoyuki** [comment]
Need more logs, but probably, a process is stopped

**Comment by kamo-naoyuki** [comment]
Your environment has some problem or a bug of pytorch.
I recommend you trying more small corpus for checking your environment.

**Comment by panpanli521** [comment]
ok, I will have a try. Thank you very much.

**Comment by D-X-Y** [comment]
@panpanli521 did you solved this issue? I met the same issue, where I slightly changed the loss function.
After several iterations not a full epoch, this error occurs

**Comment by duj12** [comment]
This problem may caused by Memory Limit Exceeded
let num_splits_asr be greater than 1, to reduce the number of utts in .scp file loaded per time. 
In my case, total utts' number is about 70 million, i split it into 16 subsets, then this error disappear.

**Comment by ftshijt** [comment]
Just a note for potential issues for future users reaching the issue, I recently also met the issue because I did not have the same keys presented in the stats. So please also make sure that you have the same keys for reduction in the function.
