### ISSUE TITLE
compute-stft-feats.py: 'module' object has no attribute 'BaseFloatMatrixWriter'

### ISSUE THREAD

**Issue by softwarezch** [espnet/espnet#269]
When I ran espnet/utils/compute-stft-feats.py,
I got an error like this:

Traceback (most recent call last):
  File "/../compute-stft-feats.py", line 103, in <module>
    main()
  File "/../../../src/utils/compute-stft-feats.py", line 86, in main
    writer = kaldi_io.BaseFloatMatrixWriter(args.feats_wspecifier)
AttributeError: 'module' object has no attribute 'BaseFloatMatrixWriter'

I checked espnet/tools/kaldi-io-for-python/kaldi_io.py, there is no function named "BaseFloatMatrixWriter", how can I save this problem?
thanks

**Comment by sw005320** [comment]
Sorry, about this.

you may need to 
```
import kaldi_io
```
->
```
import kaldi_io_py
```
Also, change the writing part accordingly.
https://github.com/espnet/espnet/blob/master/src/tts/tts_pytorch.py#L532-L555
will be a good reference.

I'll fix it, but probably it takes time.
