### ISSUE TITLE
CTC loss was 0 when joint training on Ubuntu

### ISSUE THREAD

**Issue by fotwo** [espnet/espnet#270]
Hi all, I have reproduce the result on Centos7.2+cuda8.0, and I also installed the same code on Ubuntu16.04+cuda9.1, everything was ok during installation. However, actually, attention task was ok, while the ctc task loss was 0 all the time during joint ctc/attention training, "mltalpha=0.5". Here is the log file:
```
    {
        "main/loss": 35.740950293540955, 
        "main/loss_ctc": 0.0, 
        "iteration": 100, 
        "eps": 1e-08, 
        "main/loss_att": 71.48190058708191, 
        "elapsed_time": 41.73378896713257, 
        "epoch": 0, 
        "main/acc": 0.11974184565721473
    }, 
    {
        "main/loss": 28.910011546611784, 
        "main/loss_ctc": 0.0, 
        "iteration": 200, 
        "eps": 1e-08, 
        "main/loss_att": 57.82002309322357, 
        "elapsed_time": 81.66535997390747, 
        "epoch": 0, 
        "main/acc": 0.17701563459985487
    }, 
```
The backend is pytorch and I think it is the problem of warp-ctc on Ubuntu? I have not idea of how to fix it, Please help!

**Comment by sw005320** [comment]
Which task are you using? Can you also provide your command line to execute it?

**Comment by fotwo** [comment]
All right, the command lines are:
```
asr_train.py \
--ngpu 2 \
--backend pytorch \
--outdir exp/train_nodup_sp_vggblstmp_e4_subsample1_2_2_1_1_unit500_proj320_d1_unit500_location_aconvc10_aconvf100_mtlalpha0.5_adadelta_bs16_mli800_mlo150/results \
--debugmode 1 \
--dict data/lang_1char/train_nodup_sp_units.txt \
--debugdir exp/train_nodup_sp_vggblstmp_e4_subsample1_2_2_1_1_unit500_proj320_d1_unit500_location_aconvc10_aconvf100_mtlalpha0.5_adadelta_bs16_mli800_mlo150 \
--minibatches 0 \
--verbose 0 \
--resume \
--train-json dump/train_nodup_sp/deltafalse/data.json \
--valid-json dump/train_dev/deltafalse/data.json \
--etype vggblstmp \
--elayers 4 \
--eunits 500 \
--eprojs 320 \
--subsample 1_2_2_1_1 \
--dlayers 1 \
--dunits 500 \
--atype location \
--aconv-chans 10 \
--aconv-filts 100 \
--mtlalpha 0.5 \
--batch-size 16 \
--maxlen-in 800 \
--maxlen-out 150 \
--opt adadelta \
--epochs 15
```

**Comment by sw005320** [comment]
First, can you use `--etype blstmp` instead of `--etype vggblstmp`? The pytorch backend does not support VGG (it does not work for now). Other than that, it looks normal. Year, it seems that it is an issue due to warp-ctc. Can you test it with the chainer backend?

**Comment by fotwo** [comment]
@sw005320 ok, I will try it. Actually, I have reproduced the results on Centos, using `vggblstmp`(it seems this option doesn't evoke an error). Then when it come to Ubuntu, the loss of attention task and the total acc were also ok, only the ctc loss was odd. During decode, I must set the `ctc-weight` to 0, otherwise the cer will be very bad. So have you ever tried warp-ct on Ubuntu successfully? if so, it maybe something wrong during my installation.

**Comment by sw005320** [comment]
Thanks, I want to check whether it happens from pytorch warp-ctc or chainer warp-ctc, or original warp-ctc

> So have you ever tried warp-ct on Ubuntu successfully?

I don't test it....
We should have a result with Ubuntu, and thanks for your note.
@Fhrozen, same things happen in your Ubuntu environment?

**Comment by fotwo** [comment]
@sw005320 hi, I test backend chainer on Ubuntu via debugging. The ctc loss is ok, at least it is not zero.

**Comment by fotwo** [comment]
when using:
```
asr_train.py \
--ctc_type warpctc \
--backend chainer \
# other options.
```
it was terminated with evoking "CTC_STATUS_EXECUTION_FAILED: execution failed"

**Comment by Fhrozen** [comment]
I tried to reproduce your error and I did not have any problem.
I was using a Ubuntu 16.04 OS with Cuda 9.0 and CuDNN 7 and without virtualenv.
The execution command is similar to yours. I also tested with gpu. 

The single line of the error does not explain so much. Could you copy all the paragraph with the error. I think it should start with:
` Traceback (most recent call last): ` and should appear twice (?).

**Comment by fotwo** [comment]
Hi, @Fhrozen . it means you use pytorch backend with `--ctc_type warpctc`, and the ctc_loss is not 0 ?
When using `--ctc_type warpctc --backend chainer`, the error paragraph:
```
Traceback (most recent call last):
  File "/home/tony/pyenvs/work/local/lib/python2.7/site-packages/chainer/training/trainer.py", line 306, in run
    update()
  File "/home/tony/pyenvs/work/local/lib/python2.7/site-packages/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/home/tony/work/work/tools/src/asr/asr_chainer.py", line 76, in update_core
    loss = optimizer.target(x)
  File "/home/tony/work/work/tools/src/nets/e2e_asr_attctc.py", line 78, in __call__
    loss_ctc, loss_att, acc = self.predictor(x)
  File "/home/tony/work/work/tools/src/nets/e2e_asr_attctc.py", line 197, in __call__
    loss_ctc = self.ctc(hs, ys)
  File "/home/tony/work/work/tools/src/nets/e2e_asr_attctc.py", line 353, in __call__
    self.loss = warp_ctc(y_hat, ilens, [cuda.to_cpu(l.data) for l in ys])[0]
  File "/home/tony/pyenvs/work/local/lib/python2.7/site-packages/chainer_ctc/warpctc.py", line 125, in ctc
    return CTC(seq_lengths, labels)(x)
  File "/home/tony/pyenvs/work/local/lib/python2.7/site-packages/chainer/function.py", line 235, in __call__
    ret = node.apply(inputs)
  File "/home/tony/pyenvs/work/local/lib/python2.7/site-packages/chainer/function_node.py", line 258, in apply
    outputs = self.forward(in_data)
  File "/home/tony/pyenvs/work/local/lib/python2.7/site-packages/chainer/function.py", line 135, in forward
    return self._function.forward(inputs)
  File "/home/tony/pyenvs/work/local/lib/python2.7/site-packages/chainer_ctc/warpctc.py", line 77, in forward
    raise e
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/home/tony/work/work/tools/src/bin/asr_train.py", line 224, in <module>
    main()
  File "/home/tony/work/work/tools/src/bin/asr_train.py", line 215, in main
    train(args)
  File "/home/tony/work/work/tools/src/asr/asr_chainer.py", line 476, in train
    trainer.run()
  File "/home/tony/pyenvs/work/local/lib/python2.7/site-packages/chainer/training/trainer.py", line 320, in run
    six.reraise(*sys.exc_info())
  File "/home/tony/pyenvs/work/local/lib/python2.7/site-packages/chainer/training/trainer.py", line 306, in run
    update()
  File "/home/tony/pyenvs/work/local/lib/python2.7/site-packages/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/home/tony/work/work/tools/src/asr/asr_chainer.py", line 76, in update_core
    loss = optimizer.target(x)
  File "/home/tony/work/work/tools/src/nets/e2e_asr_attctc.py", line 78, in __call__
    loss_ctc, loss_att, acc = self.predictor(x)
  File "/home/tony/work/work/tools/src/nets/e2e_asr_attctc.py", line 197, in __call__
    loss_ctc = self.ctc(hs, ys)
  File "/home/tony/work/work/tools/src/nets/e2e_asr_attctc.py", line 353, in __call__
    self.loss = warp_ctc(y_hat, ilens, [cuda.to_cpu(l.data) for l in ys])[0]
  File "/home/tony/pyenvs/work/local/lib/python2.7/site-packages/chainer_ctc/warpctc.py", line 125, in ctc
    return CTC(seq_lengths, labels)(x)
  File "/home/tony/pyenvs/work/local/lib/python2.7/site-packages/chainer/function.py", line 235, in __call__
    ret = node.apply(inputs)
  File "/home/tony/pyenvs/work/local/lib/python2.7/site-packages/chainer/function_node.py", line 258, in apply
    outputs = self.forward(in_data)
  File "/home/tony/pyenvs/work/local/lib/python2.7/site-packages/chainer/function.py", line 135, in forward
    return self._function.forward(inputs)
  File "/home/tony/pyenvs/work/local/lib/python2.7/site-packages/chainer_ctc/warpctc.py", line 77, in forward
    raise e
chainer_ctc.src.warp_ctc.CTCError: CTC_STATUS_EXECUTION_FAILED: execution failed
```
Thanks.

**Comment by Fhrozen** [comment]
Just to confirm, I will like to know which recipe are you using. I tested with voxforge.
With `--backend pytorch --ctc_type warpctc`, the ctc is not zero:
```
{
        "main/loss": 210.09339630126954, 
        "main/loss_ctc": 231.01422760009766, 
        "iteration": 100, 
        "eps": 1e-08, 
        "main/loss_att": 189.17256477355957, 
        "elapsed_time": 100.62332081794739, 
        "epoch": 0, 
        "main/acc": 0.2435916450817478
    }, 
    {
        "main/loss": 187.8331169128418, 
        "main/loss_ctc": 214.7629539489746, 
        "iteration": 200, 
        "eps": 1e-08, 
        "main/loss_att": 160.9032810974121, 
        "elapsed_time": 199.0161759853363, 
        "epoch": 0, 
        "main/acc": 0.3145206625358909
    },
```
When using `--ctc_type warpctc --backend chainer`:
```
{
        "main/loss": 203.49114990234375, 
        "main/loss_ctc": 226.7288055419922, 
        "iteration": 100, 
        "eps": 1e-08, 
        "main/loss_att": 180.25355529785156, 
        "elapsed_time": 124.7856810092926, 
        "epoch": 0, 
        "main/acc": 0.26898226141929626
    }, 
    {
        "main/loss": 183.5249481201172, 
        "main/loss_ctc": 216.84886169433594, 
        "iteration": 200, 
        "eps": 1e-08, 
        "main/loss_att": 150.20103454589844, 
        "elapsed_time": 245.9992392063141, 
        "epoch": 0, 
        "main/acc": 0.3597940504550934
    }
```
I tried several ways to reproduce your error, but it was unsuccessful.  (Even using more GPU memory or incorrect number of gpus).
Just to outline, I am using Ubuntu 16.04, with CUDA 9.0 and no virtualenv. (<=this is irrelevant, I think, I also tried with docker but it executed successfully).

The Log does not give so much detail were the error is generated. `line 77` belong to GPU but not sure if this is exactly related to this.

My only suggestion is to delete warpctc and chainer ctc and build both of them again, if possible try to copy the logs of the installation.
