### ISSUE TITLE
Error of "RuntimeError: Format is invalid" when training csmsc/tts1

### ISSUE THREAD

**Issue by HudsonHuang** [espnet/espnet#2725]
**Describe the bug**
Got RuntimeError: Format is invalid when training csmsc/tts1

**Basic environments:**
 - OS information: Linux 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64
- python version: `3.7.9 (default, Aug 31 2020, 12:42:55)  [GCC 7.3.0]`
- espnet version: `espnet 0.9.5`
- pytorch version: `pytorch 1.7.0`
- Git hash: `1e443b12e2fd95c2adf9c5e1e0a84de02e2ebaaf`
  - Commit date: `Mon Nov 23 12:20:26 2020 -0500`

**Environments from `torch.utils.collect_env`:**
```
Collecting environment information...
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.6 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Clang version: Could not collect
CMake version: version 3.5.1

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti

Nvidia driver version: 450.57
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] numpy==1.19.2
[pip] pytorch-lightning==0.8.5
[pip] pytorch-pretrained-bert==0.6.2
[pip] pytorch-ranger==0.1.1
[pip] pytorch-wpe==0.0.0
[pip] torch==1.7.0
[pip] torch-complex==0.1.2
[pip] torch-optimizer==0.0.1a15
[pip] torch-stft==0.1.4
[pip] torch-stoi==0.1.1
[pip] torchaudio==0.7.0
[pip] torchprofile==0.0.1
[pip] torchstat==0.0.7
[pip] torchtext==0.7.0
[pip] torchvision==0.8.1
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h6bb024c_0
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.2.0            py37h23d657b_0
[conda] mkl_random                1.1.1            py37h0573a6f_0
[conda] numpy                     1.19.2           py37h54aff64_0
[conda] numpy-base                1.19.2           py37hfa32c7d_0
[conda] pytorch                   1.7.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] pytorch-lightning         0.8.5                    pypi_0    pypi
[conda] pytorch-pretrained-bert   0.6.2                    pypi_0    pypi
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.0                    pypi_0    pypi
[conda] torch                     1.5.1                    pypi_0    pypi
[conda] torch-complex             0.1.2                    pypi_0    pypi
[conda] torch-optimizer           0.0.1a15                 pypi_0    pypi
[conda] torch-stft                0.1.4                    pypi_0    pypi
[conda] torch-stoi                0.1.1                    pypi_0    pypi
[conda] torchaudio                0.7.0                    pypi_0    pypi
[conda] torchprofile              0.0.1                    pypi_0    pypi
[conda] torchstat                 0.0.7                    pypi_0    pypi
[conda] torchtext                 0.7.0                    pypi_0    pypi
[conda] torchvision               0.6.1                    pypi_0    pypi
```

**Task information:**
 - Task: TTS
 - Recipe: csmsc
 - ESPnet2

**To Reproduce**
1. cd egs2/csmsc/tts1
2. bash run.sh
3. specify the error log, `dump/raw/org/tr_no_dev/logs/format_wav_scp.*.log`

**Error logs**
- I got error in terminal like this:
```
(base) zhongyihuang@ubuntu:~/workspace/espnet/egs2/csmsc/tts1$ bash run.sh
2020-11-29T03:15:42 (tts.sh:187:main) ./tts.sh --lang zh --feats_type raw --fs 24000 --n_fft 2048 --n_shift 300 --win_length 1200 --token_type phn --cleaner none --g2p pypinyin_g2p_phone --train_config conf/train.yaml --inference_config conf/decode.yaml --train_set tr_no_dev --valid_set dev --test_sets dev eval1 --srctexts data/tr_no_dev/text --audio_format flac
2020-11-29T03:15:46 (tts.sh:275:main) Stage 1: Data preparation for data/tr_no_dev, data/dev, etc.
2020-11-29T03:15:46 (data.sh:16:main) local/data.sh
2020-11-29T03:15:48 (data.sh:39:main) stage -1: Data Download
local/data_download.sh: line 16: then#[: command not found
Already exists. Skip download.
2020-11-29T03:15:48 (data.sh:44:main) stage 0: local/data_prep.sh
2020-11-29T03:40:01 (data.sh:91:main) stage 2: utils/subset_data_dir.sh
utils/subset_data_dir.sh: reducing #utt from 10000 to 200
utils/subset_data_dir.sh: reducing #utt from 200 to 100
utils/subset_data_dir.sh: reducing #utt from 200 to 100
utils/subset_data_dir.sh: reducing #utt from 10000 to 9800
2020-11-29T03:40:04 (data.sh:100:main) Successfully finished. [elapsed=1458s]
2020-11-29T03:40:04 (tts.sh:292:main) Stage 2: Format wav.scp: data/ -> dump/raw/
utils/copy_data_dir.sh: copied data from data/tr_no_dev to dump/raw/org/tr_no_dev
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory dump/raw/org/tr_no_dev
2020-11-29T03:40:06 (format_wav_scp.sh:42:main) scripts/audio/format_wav_scp.sh --nj 32 --cmd run.pl --audio-format flac --fs 24000 --segments data/tr_no_dev/segments data/tr_no_dev/wav.scp dump/raw/org/tr_no_dev
2020-11-29T03:40:08 (format_wav_scp.sh:90:main) [info]: using data/tr_no_dev/segments
run.pl: 32 / 32 failed, log is in dump/raw/org/tr_no_dev/logs/format_wav_scp.*.log
```

- In the log file(dump/raw/org/tr_no_dev/logs/format_wav_scp.*.log), I got this:
```
# pyscripts/audio/format_wav_scp.py --fs 24000 --audio-format flac --segment=dump/raw/org/tr_no_dev/logs/segments.10 data/tr_no_dev/wav.scp dump/raw/org/tr_no_dev/data/format.10
# Started at Sun Nov 29 03:40:08 EST 2020
#
2020-11-29 03:40:14,234 (format_wav_scp:43) INFO: /data3/zhongyihuang/anaconda3/bin/python3 pyscripts/audio/format_wav_scp.py --fs 24000 --audio-format flac --segment=dump/raw/org/tr_no_dev/logs/segments.10 data/tr_no_dev/wav.scp dump/raw/org/tr_no_dev/data/format.10
^M0it [00:00, ?it/s]^M0it [00:00, ?it/s]
loader data/tr_no_dev/wav.scp dump/raw/org/tr_no_dev/logs/segments.10
Traceback (most recent call last):
  File "pyscripts/audio/format_wav_scp.py", line 249, in <module>
    main()
  File "pyscripts/audio/format_wav_scp.py", line 106, in main
    for uttid, (rate, wave) in tqdm(loader):
  File "/data3/zhongyihuang/anaconda3/lib/python3.7/site-packages/tqdm/std.py", line 1171, in __iter__
    for obj in iterable:
  File "/data3/zhongyihuang/anaconda3/lib/python3.7/site-packages/kaldiio/matio.py", line 139, in load_scp_sequential
    fname, separator=separator, segments=segments
  File "/data3/zhongyihuang/anaconda3/lib/python3.7/site-packages/kaldiio/matio.py", line 170, in __init__
    raise RuntimeError("Format is invalid: {}".format(line))
RuntimeError: Format is invalid: 002763 002763 0.3397468035218096

# Accounting: time=6 threads=1
# Ended (code 1) at Sun Nov 29 03:40:14 EST 2020, elapsed time 6 seconds
```

**Comment by HudsonHuang** [comment]
<img width="472" alt="微信截图_20201129172855" src="https://user-images.githubusercontent.com/5734717/100538063-66589100-3268-11eb-8b0c-46604132db72.png">
I found there are many "^M" symbol in "espnet/egs2/csmsc/tts1/data/tr_no_dev/segments".
I try to remove "^M" symbol of the first line and do this manually:

```
pyscripts/audio/format_wav_scp.py --fs 24000 --audio-format flac --segment=dump/raw/org/tr_no_dev/logs/segments.10 data/tr_no_dev/wav.scp dump/raw/org/tr_no_dev/data/format.10
```

And it got no error of  **the first line** but got the same error on  **the second**

**Comment by danpovey** [comment]
That is caused by Windows... look for dos2unix

**Comment by b-flo** [comment]
`^M` is a carriage-return character, which usually indicates a DOS file (whereas UNIX file use a newline as EOL). I'm not familiar with the recipe, is there some conversion done along the line?
Some conversion tool (e.g.: dos2unix, emacs utilities), regexp can be used to remove them.

**Comment by HudsonHuang** [comment]
I ran into the errror when I login a linux server through ssh. But indeed I'm using the [windows terminal](https://github.com/microsoft/terminal) under WIN10 as my console, was that the reason?

**Comment by b-flo** [comment]
> I ran into the errror when I login a linux server through ssh. But indeed I'm using the windows terminal under WIN10 as my console, was that the reason?

I suppose so, doing a quick search in the repo you linked I found some discussions/issues on that. It seems there are some variable which could help. I'll let you do the research and testing from that ;)
Never had such issues with SSH client such as PuTTY

**Comment by kan-bayashi** [comment]
Maybe you forgot to apply nkf.
https://github.com/espnet/espnet/blob/5ee7d98a842abf4bf4279771362e7ef1919bea2f/egs/csmsc/tts1/local/data_download.sh#L23

**Comment by kan-bayashi** [comment]
See also https://github.com/espnet/espnet/issues/1613

**Comment by HudsonHuang** [comment]
> Maybe you forgot to apply nkf.
> https://github.com/espnet/espnet/blob/5ee7d98a842abf4bf4279771362e7ef1919bea2f/egs/csmsc/tts1/local/data_download.sh#L23

This was exactly the reason. I have commented a few lines to skip downloading, including this line, by mistake. 
It works now. Thank you to every one.
