### ISSUE TITLE
Multi GPUs bug of lm training when using pytorch>=1.5

### ISSUE THREAD

**Issue by picheny-nyu** [espnet/espnet#2763]
Trying to run the older AMI egs recipe with 4 GPUs. I ran Nvidia-smi and it shows I have the gpus reserved, but the rnn training recipe is failing (stage 3). Can you help me decipher the output?

And sorry for running into all these problems :-( 

Thanks
Michael

```
# lm_train.py --config conf/lm.yaml --ngpu 4 --backend pytorch --verbose 1 --outdir exp/train_rnnlm_pytorch_lm_word20000 --tensorboard-dir tensorboard/train_rnnlm_pytorch_lm_word20000 --train-label data/local/wordlm_train/train.txt --valid-label data/local/wordlm_train/valid.txt --test-label data/local/wordlm_train/test.txt --resume --dict data/local/wordlm_train/wordlist_20000.txt 
# Started at Mon Dec  7 19:42:09 EST 2020
#
2020-12-07 19:43:20,413 (lm_train:250) INFO: ngpu: 4
2020-12-07 19:43:20,414 (lm_train:253) INFO: python path = (None)
2020-12-07 19:43:20,430 (lm_train:270) INFO: backend = pytorch
2020-12-07 19:43:21,248 (lm:222) INFO: torch version = 1.6.0
2020-12-07 19:43:21,308 (deterministic_utils:26) INFO: torch type check is disabled
2020-12-07 19:43:21,439 (lm_utils:44) INFO: skip dump/load HDF5 because the output dir is not specified
2020-12-07 19:43:21,439 (lm_utils:45) INFO: reading text dataset: data/local/wordlm_train/valid.txt

0it [00:00, ?it/s]
13023it [00:00, 130227.33it/s]
13059it [00:00, 130086.13it/s]
2020-12-07 19:43:21,596 (lm_utils:44) INFO: skip dump/load HDF5 because the output dir is not specified
2020-12-07 19:43:21,596 (lm_utils:45) INFO: reading text dataset: data/local/wordlm_train/train.txt

0it [00:00, ?it/s]
12664it [00:00, 126638.91it/s]
25367it [00:00, 126755.75it/s]
38143it [00:00, 127054.68it/s]
51531it [00:00, 129023.74it/s]
65182it [00:00, 131180.92it/s]
78938it [00:00, 133031.31it/s]
93549it [00:00, 136699.03it/s]
107979it [00:00, 138891.83it/s]
121173it [00:00, 136144.59it/s]
134313it [00:01, 134538.10it/s]
147439it [00:01, 132502.60it/s]
161111it [00:01, 133738.04it/s]
174815it [00:01, 134709.56it/s]
188668it [00:01, 135833.33it/s]
203354it [00:01, 138962.37it/s]
217739it [00:01, 140386.70it/s]
231759it [00:01, 137250.60it/s]
245487it [00:01, 135515.01it/s]
259045it [00:01, 133086.76it/s]
272776it [00:02, 134325.02it/s]
286421it [00:02, 134955.00it/s]
300575it [00:02, 136864.72it/s]
315177it [00:02, 139487.53it/s]
324638it [00:02, 135781.61it/s]
2020-12-07 19:43:25,026 (lm:240) INFO: #vocab = 11886
2020-12-07 19:43:25,026 (lm:241) INFO: #sentences in the training data = 324638
2020-12-07 19:43:25,027 (lm:242) INFO: #tokens in the training data = 2407787
2020-12-07 19:43:25,027 (lm:245) INFO: oov rate in the training data = 0.00 %
2020-12-07 19:43:25,027 (lm:247) INFO: #sentences in the validation data = 13059
2020-12-07 19:43:25,027 (lm:248) INFO: #tokens in the validation data = 94914
2020-12-07 19:43:25,027 (lm:250) INFO: oov rate in the validation data = 1.51 %
2020-12-07 19:43:25,027 (lm:258) INFO: batch size is automatically increased (64 -> 256)
2020-12-07 19:43:25,245 (lm:273) INFO: #iterations per epoch = 1273
2020-12-07 19:43:25,245 (lm:274) INFO: #total iterations = 25460
2020-12-07 19:43:36,971 (lm:290) INFO: writing a model config file to exp/train_rnnlm_pytorch_lm_word20000/model.json
[JException in main training loop: Caught StopIteration in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/espnet/nets/pytorch_backend/lm/default.py", line 104, in forward
    state, loss_batch = self.model(state, x[:, i], t[:, i])
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/espnet/nets/pytorch_backend/lm/default.py", line 249, in forward
    state, self.y = self.predictor(state, *args, **kwargs)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/espnet/nets/pytorch_backend/lm/default.py", line 349, in forward
    for n in range(self.n_layers)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/espnet/nets/pytorch_backend/lm/default.py", line 349, in <listcomp>
    for n in range(self.n_layers)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/espnet/nets/pytorch_backend/lm/default.py", line 341, in zero_state
    p = next(self.parameters())
StopIteration

Traceback (most recent call last):
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/chainer/training/updaters/standard_updater.py", line 175, in update
    self.update_core()
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/espnet/lm/pytorch_backend/lm.py", line 145, in update_core
    loss, nll, count = data_parallel(self.model, (x, t), self.device)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 210, in data_parallel
    outputs = parallel_apply(replicas, inputs, module_kwargs, used_device_ids)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/misc/vlgscratch5/PichenyGroup/picheny/espnet/egs/ami/asr1a/../../../espnet/bin/lm_train.py", line 284, in <module>
    main(sys.argv[1:])
  File "/misc/vlgscratch5/PichenyGroup/picheny/espnet/egs/ami/asr1a/../../../espnet/bin/lm_train.py", line 278, in main
    train(args)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/espnet/lm/pytorch_backend/lm.py", line 380, in train
    trainer.run()
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/chainer/training/trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/chainer/training/updaters/standard_updater.py", line 175, in update
    self.update_core()
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/espnet/lm/pytorch_backend/lm.py", line 145, in update_core
    loss, nll, count = data_parallel(self.model, (x, t), self.device)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 210, in data_parallel
    outputs = parallel_apply(replicas, inputs, module_kwargs, used_device_ids)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
StopIteration: Caught StopIteration in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/espnet/nets/pytorch_backend/lm/default.py", line 104, in forward
    state, loss_batch = self.model(state, x[:, i], t[:, i])
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/espnet/nets/pytorch_backend/lm/default.py", line 249, in forward
    state, self.y = self.predictor(state, *args, **kwargs)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/espnet/nets/pytorch_backend/lm/default.py", line 349, in forward
    for n in range(self.n_layers)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/espnet/nets/pytorch_backend/lm/default.py", line 349, in <listcomp>
    for n in range(self.n_layers)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/espnet-sep032020/lib/python3.7/site-packages/espnet/nets/pytorch_backend/lm/default.py", line 341, in zero_state
    p = next(self.parameters())
StopIteration

# Accounting: time=97 threads=1
# Ended (code 1) at Mon Dec  7 19:43:46 EST 2020, elapsed time 97 seconds
```

**Comment by kamo-naoyuki** [comment]
This is a bug of espnet1, which is not fixed, when using pytorch>=1.5.

**Comment by picheny-nyu** [comment]
Is this something I can fix myself?

**Comment by sw005320** [comment]
@ftshijt is working on it to fix it.
Then, I'll also update the recipe.

**Comment by picheny-nyu** [comment]
Hi all, just wondering if this was fixed - I saw an Arxiv paper on a new code release. I would like to train a librispeech 1000 model and can not do it w/o multiple GPUs in a reasonable amount of time. 

Thanks
Michael

**Comment by sw005320** [comment]
> Hi all, just wondering if this was fixed - I saw an Arxiv paper on a new code release. 

Yes, see #2817, but some issues remain.

> I would like to train a librispeech 1000 model and can not do it w/o multiple GPUs in a reasonable amount of time.

I usually use 4 GPUs to train librispeech 1000h models, and it would take 10days (could be more, but 10 days are enough).

**Comment by picheny-nyu** [comment]
For clarity, the above fixes the python >= 1.5 problem, right?

**Comment by sw005320** [comment]
Oh sorry, I was talking about the other issue.
Please use `pytorch 1.4`.

**Comment by MingjieChen** [comment]
Hello, I still get this error on M-AILAB TTS1 recipe (ESPNET1). 
Is this bug fixed? 
My pytorch version is 1.9


Thanks
