### ISSUE TITLE
Multi Gpus with pytorch backend problem.

### ISSUE THREAD

**Issue by ZhuoranLyu** [espnet/espnet#279]
I am using Pytorch 0.4 with 4 GTX 1080Ti. When I run using pytorch backend and multi gpus, it gives me this error.

`# asr_train.py --ngpu 4 --backend pytorch --outdir exp/tr_en_vggblstmp_e4_subsample1_2_2_1_1_unit320_proj320_d1_unit300_location_aconvc10_aconvf100_mtlalpha0.5_adadelta_bs30_mli800_mlo150/results --debugmode 1 --dict data/lang_1char/tr_en_units.txt --debugdir exp/tr_en_vggblstmp_e4_subsample1_2_2_1_1_unit320_proj320_d1_unit300_location_aconvc10_aconvf100_mtlalpha0.5_adadelta_bs30_mli800_mlo150 --minibatches 0 --verbose 0 --resume --train-json dump/tr_en/deltafalse/data.json --valid-json dump/dt_en/deltafalse/data.json --etype vggblstmp --elayers 4 --eunits 320 --eprojs 320 --subsample 1_2_2_1_1 --dlayers 1 --dunits 300 --atype location --aconv-chans 10 --aconv-filts 100 --mtlalpha 0.5 --batch-size 30 --maxlen-in 800 --maxlen-out 150 --opt adadelta --epochs 100 
# Started at Fri Jul  6 10:05:31 CST 2018
#
2018-07-06 10:05:31,582 (asr_train:146) WARNING: Skip DEBUG/INFO messages
2018-07-06 10:05:31,587 (asr_train:186) WARNING: CUDA_VISIBLE_DEVICES is not set.
2018-07-06 10:05:35,803 (e2e_asr_attctc_th:198) WARNING: Subsampling is not performed for vgg*. It is performed in max pooling layers at CNN.
Exception in main training loop: torch/csrc/autograd/variable.cpp:115: get_grad_fn: Assertion `output_nr == 0` failed.
Traceback (most recent call last):
  File "/home/lvzhuoran/code/espnet-master/tools/venv/local/lib/python2.7/site-packages/chainer/training/trainer.py", line 306, in run
    update()
  File "/home/lvzhuoran/code/espnet-master/tools/venv/local/lib/python2.7/site-packages/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/home/lvzhuoran/code/espnet-master/src/asr/asr_pytorch.py", line 122, in update_core
    loss = 1. / self.num_gpu * self.model(x)
  File "/home/lvzhuoran/code/espnet-master/tools/venv/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lvzhuoran/code/espnet-master/src/asr/asr_pytorch.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/lvzhuoran/code/espnet-master/tools/venv/local/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 124, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/lvzhuoran/code/espnet-master/tools/venv/local/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 65, in parallel_apply
    raise output
Will finalize trainer extensions and updater before reraising the exception.
[JTraceback (most recent call last):
  File "/home/lvzhuoran/code/espnet-master/egs/voxforge/asr1/../../../src/bin/asr_train.py", line 224, in <module>
    main()
  File "/home/lvzhuoran/code/espnet-master/egs/voxforge/asr1/../../../src/bin/asr_train.py", line 218, in main
    train(args)
  File "/home/lvzhuoran/code/espnet-master/src/asr/asr_pytorch.py", line 377, in train
    trainer.run()
  File "/home/lvzhuoran/code/espnet-master/tools/venv/local/lib/python2.7/site-packages/chainer/training/trainer.py", line 320, in run
    six.reraise(*sys.exc_info())
  File "/home/lvzhuoran/code/espnet-master/tools/venv/local/lib/python2.7/site-packages/chainer/training/trainer.py", line 306, in run
    update()
  File "/home/lvzhuoran/code/espnet-master/tools/venv/local/lib/python2.7/site-packages/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/home/lvzhuoran/code/espnet-master/src/asr/asr_pytorch.py", line 122, in update_core
    loss = 1. / self.num_gpu * self.model(x)
  File "/home/lvzhuoran/code/espnet-master/tools/venv/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lvzhuoran/code/espnet-master/src/asr/asr_pytorch.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/lvzhuoran/code/espnet-master/tools/venv/local/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 124, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/lvzhuoran/code/espnet-master/tools/venv/local/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 65, in parallel_apply
    raise output
RuntimeError: torch/csrc/autograd/variable.cpp:115: get_grad_fn: Assertion `output_nr == 0` failed.`

I am using Pytorch 0.4. I googled it and found [this](https://github.com/pytorch/pytorch/issues/7092) link to be useful. 

Thanks,
George.

**Comment by ZhuoranLyu** [comment]
I am afraid this is because of using flatten_parameters with DataParallel.

**Comment by sw005320** [comment]
Thanks for your report. @bobchennan, can you take a look at it?

**Comment by ZhuoranLyu** [comment]
BTW, if I switch to pytorch 0.3.1, everything works fine.

**Comment by sw005320** [comment]
Thanks for your report. Yes, we first implemented it with pytorch 0.3.1, but we do not test it with pytrorch 0.4.0. We'll fix it soon.

**Comment by sw005320** [comment]
#286

**Comment by ZhuoranLyu** [comment]
@sw005320 I think it works no problem now. Thank you for your help.

**Comment by miguelvr** [comment]
still having the same issue, although it only happens during validation (commit c72b0687ebee68f401a72a8fa98998cb87f5642e)

**Comment by miguelvr** [comment]
Shouldn't we be using [DistributedDataParallel](https://pytorch.org/docs/stable/distributed.html#launch-utility) instead of DataParallel?

**Comment by sw005320** [comment]
@kan-bayashi @bobchennan, do you have any ideas?
(I don't have two GPU slots now to test it....)

**Comment by bobchennan** [comment]
Unless you are using multiple nodes to train the system which is not supported yet, you should not use DistributedDataParallel. I am not sure about 0.4 since recently I am using TF.

**Comment by kan-bayashi** [comment]
I will investigate it today.

**Comment by kan-bayashi** [comment]
@ZhuoranLyu Could you test this patch? #294

**Comment by miguelvr** [comment]
@bobchennan DistributedDataParallel works for single nodes and it has been proved to have much better performance than data parallel. Check [this](https://github.com/NVIDIA/sentiment-discovery/blob/master/analysis/scale.md) and [this](https://github.com/SeanNaren/deepspeech.pytorch/issues/211)

**Comment by ZhuoranLyu** [comment]
@kan-bayashi I think it works with no problem now. Thank you for your help. The only problem is that using multi gpus won't accelerate the loss converge too much. On the contrary, the loss can't converge as low as using single gpu. Here is the result. After first epoch, the loss of single gpu is 103 while the loss of multi gpus is 263. There is a huge gap. So I'd better use single gpu to train the model on librispeech. Anyway, thanks a lot.

**Comment by bobchennan** [comment]
@miguelvr interesting to know. Clearly multiprocessing should be better since it potentially avoids GIL problem.

**Comment by ZhuoranLyu** [comment]
@sw005320 Thanks. Another quick question, if I use vggblstmp encoder, shall I set do_delta=true instead of false in the run.sh?

**Comment by sw005320** [comment]
You don't have to. I tested it, and this does not make significant difference.

**Comment by soumith** [comment]
DistributedDataParallel will be much better for RNNs. Please use that if possible, even on single node.

Have a look at our Launch Utility documentation that cleanly describes how to use DistributedDataParallel: https://pytorch.org/docs/stable/distributed.html#launch-utility

You can treat your training script has not getting a split input, which also simplifies your code a lot.

**Comment by ZhuoranLyu** [comment]
@soumith Hi soumith, I tried to use DistributedDataParallel to train the model parallel. However, the problem is that it requires more memory than using DataParallel. Hence I have to reduce the batchsize and then the training time is much longer.

**Comment by kan-bayashi** [comment]
The bug itself is fixed. I will close this issue.
