### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by tjuzsh09** [espnet/espnet#2831]
This error occurs while training:
RuntimeError: CUDA out of memory. Tried to allocate 2.77 GiB (GPU 0; 7.79 GiB total capacity; 6.05 GiB already allocated; 462.94 MiB free; 371.28 MiB cached)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/espnet/lib/python3.6/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/home/ubuntu/espnet-master/espnet/asr/pytorch_backend/asr.py", line 245, in update
    self.update_core()
  File "/home/ubuntu/espnet-master/espnet/asr/pytorch_backend/asr.py", line 207, in update_core
    data_parallel(self.model, x, range(self.ngpu)).mean() / self.accum_grad
  File "/home/ubuntu/anaconda3/envs/espnet/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 204, in data_parallel
    return module(*inputs[0], **module_kwargs[0])
  File "/home/ubuntu/anaconda3/envs/espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/espnet-master/espnet/nets/pytorch_backend/e2e_asr_transformer.py", line 175, in forward
    hs_pad, hs_mask = self.encoder(xs_pad, src_mask)
  File "/home/ubuntu/anaconda3/envs/espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/espnet-master/espnet/nets/pytorch_backend/conformer/encoder.py", line 222, in forward
    xs, masks = self.encoders(xs, masks)
  File "/home/ubuntu/anaconda3/envs/espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/espnet-master/espnet/nets/pytorch_backend/transformer/repeat.py", line 18, in forward
    args = m(*args)
  File "/home/ubuntu/anaconda3/envs/espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/espnet-master/espnet/nets/pytorch_backend/conformer/encoder_layer.py", line 119, in forward
    x_att = self.self_attn(x_q, x, x, pos_emb, mask)
  File "/home/ubuntu/anaconda3/envs/espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/espnet-master/espnet/nets/pytorch_backend/transformer/attention.py", line 199, in forward
    matrix_bd = torch.matmul(q_with_bias_v, p.transpose(-2, -1))
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/home/ubuntu/espnet-master/egs/aishell/asr1/../../../espnet/bin/asr_train.py", line 638, in <module>
    main(sys.argv[1:])
  File "/home/ubuntu/espnet-master/egs/aishell/asr1/../../../espnet/bin/asr_train.py", line 624, in main
    train(args)
  File "/home/ubuntu/espnet-master/espnet/asr/pytorch_backend/asr.py", line 901, in train
    trainer.run()
  File "/home/ubuntu/anaconda3/envs/espnet/lib/python3.6/site-packages/chainer/training/trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "/home/ubuntu/anaconda3/envs/espnet/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/ubuntu/anaconda3/envs/espnet/lib/python3.6/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/home/ubuntu/espnet-master/espnet/asr/pytorch_backend/asr.py", line 245, in update
    self.update_core()
  File "/home/ubuntu/espnet-master/espnet/asr/pytorch_backend/asr.py", line 207, in update_core
    data_parallel(self.model, x, range(self.ngpu)).mean() / self.accum_grad
  File "/home/ubuntu/anaconda3/envs/espnet/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 204, in data_parallel
    return module(*inputs[0], **module_kwargs[0])
  File "/home/ubuntu/anaconda3/envs/espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/espnet-master/espnet/nets/pytorch_backend/e2e_asr_transformer.py", line 175, in forward
    hs_pad, hs_mask = self.encoder(xs_pad, src_mask)
  File "/home/ubuntu/anaconda3/envs/espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/espnet-master/espnet/nets/pytorch_backend/conformer/encoder.py", line 222, in forward
    xs, masks = self.encoders(xs, masks)
  File "/home/ubuntu/anaconda3/envs/espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/espnet-master/espnet/nets/pytorch_backend/transformer/repeat.py", line 18, in forward
    args = m(*args)
  File "/home/ubuntu/anaconda3/envs/espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/espnet-master/espnet/nets/pytorch_backend/conformer/encoder_layer.py", line 119, in forward
    x_att = self.self_attn(x_q, x, x, pos_emb, mask)
  File "/home/ubuntu/anaconda3/envs/espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/espnet-master/espnet/nets/pytorch_backend/transformer/attention.py", line 199, in forward
    matrix_bd = torch.matmul(q_with_bias_v, p.transpose(-2, -1))

This is my error log, someone has a solution to resolve this problem? Thank you very much!

**Comment by sw005320** [comment]
This is simply due to the GPU memory shortage.
Please use a smaller batch size to make training fit in your GPU memory.

**Comment by tjuzsh09** [comment]
Thanks, I use batch-size = 1 in file train.yaml, but the same error occurs, so I need a new gpu?

**Comment by sw005320** [comment]
Which recipe you're using? If you use our bug report template, we can give you more suggestions.

**Comment by tjuzsh09** [comment]
My training set is over 9000 asr data， I am using espnet/aishell，and batch-size = 1 in train.yaml.
environment:
  OS: Ubuntu 16.04
  python version: 3.6
  pytorch version: 1.3.1
  CUDA version: 10.0
  GPU: RTX 2060S
I am a newer to GitHub，and not familiar with the bug report template ，could you give me some instructions？

**Comment by sw005320** [comment]
I think you just include a very long recording for training.
Please use the segmented utterances (less than 20 seconds).

Also, I recommend you to first run some existing recipes and see if it works normally in your setup (say `an4` recipe).
If it's working (I believe it is), then the problem comes from your data.

**Comment by tjuzsh09** [comment]
Thank you for your advice! I tried aishell data and the train was finished.  I have checked my data, some of the recordings are about 15s, do I have to make them segmented?
And I met another problem, decoding stopped while it was not finished. One of the test logs is partly presented here:

# asr_recog.py --config conf/decode.yaml --ngpu 0 --backend pytorch --batchsize 0 --recog-json dump/test/deltafalse/split8utt/data.3.json --result-label exp/train_s
p_pytorch_train/decode_test_decode_lm_4/data.3.json --model exp/train_sp_pytorch_train/results/model.last10.avg.best --rnnlm exp/train_rnnlm_pytorch_lm/rnnlm.model.
best --ngram-model exp/train_ngram/4gram.bin --api v2 
# Started at Mon Jan 18 22:02:32 CST 2021
#
2021-01-18 22:02:32,412 (asr_recog:305) INFO: python path = (None)
2021-01-18 22:02:32,412 (asr_recog:310) INFO: set random seed = 1
2021-01-18 22:02:32,412 (asr_recog:321) INFO: backend = pytorch
2021-01-18 22:02:35,739 (recog:34) WARNING: experimental API for custom LMs is selected by --api v2
2021-01-18 22:02:35,739 (deterministic_utils:26) INFO: torch type check is disabled
2021-01-18 22:02:35,739 (asr_utils:656) INFO: reading a config file from exp/train_sp_pytorch_train/results/model.json
2021-01-18 22:02:35,740 (asr_init:169) WARNING: reading model parameters from exp/train_sp_pytorch_train/results/model.last10.avg.best
2021-01-18 22:02:36,169 (decoder:125) INFO: decoder self-attention layer type = self-attention
2021-01-18 22:02:37,649 (asr_utils:656) INFO: reading a config file from exp/train_rnnlm_pytorch_lm/model.json
2021-01-18 22:02:38,165 (recog:123) INFO: Decoding device=cpu, dtype=torch.float32
.........
2021-01-19 02:24:07,859 (recog:133) INFO: (192/897) decoding BAC009S0769W0325
2021-01-19 02:24:12,490 (beam_search:358) INFO: decoder input length: 98
2021-01-19 02:24:12,516 (beam_search:359) INFO: max output length: 98
2021-01-19 02:24:12,517 (beam_search:360) INFO: min output length: 0
# Accounting: time=15835 threads=1
# Ended (code 137) at Tue Jan 19 02:26:27 CST 2021, elapsed time 15835 seconds

The error information is as follows:  (nj = 8 in run.sh)

run.pl: 7 / 8 failed, log is in exp/train_sp_pytorch_train/decode_test_decode_lm_4/log/decode.*.log
run.pl: 5 / 8 failed, log is in exp/train_sp_pytorch_train/decode_dev_decode_lm_4/log/decode.*.log
./run.sh: 2 background jobs are failed.

**Comment by kan-bayashi** [comment]
It seems out of cpu memory.
Please decrease `nj`.

**Comment by unparalleled-ysj** [comment]
@kan-bayashi I have 3 gpus, the first two are used, how can I specify that my program runs on the third gpu.  thank you !

**Comment by kan-bayashi** [comment]
Please export `CUDA_VISIBLE_DEVICES`.
e.g. `CUDA_VISIBLE_DEVICES=3 ./run.sh`
