### ISSUE TITLE
install error while run make

### ISSUE THREAD

**Issue by Mingrg** [espnet/espnet#2918]
Hi, 
    I want to install the espnet2 by referring https://espnet.github.io/espnet/installation.html#step-2-installation-espnet.
    But when I do the `make` command, this error occurred: 
    (my cuda is 10.2, so I use the 1.5.0 torch version)
```
[SanJunipero@BJ-SJ-SUFAGPU-100-103 tools]$ make
CUDA_VERSION=10.2
. ./activate_python.sh && /data/rd/zhujun/TTS2/espnet/tools/anaconda/envs/zjespnet2/bin/python check_pytorch_cuda_compatibility.py 1.5.0 "10.2" || { echo "Change TH_VERSION or CUDA_VERSION"; exit 1; }
10.2
PYTHON=/data/rd/zhujun/TTS2/espnet/tools/anaconda/envs/zjespnet2/bin/python3
PYTHON_VERSION=Python 3.8.5
IS_CONDA=0
USE_PIP=
TH_VERSION=1.5.0
CONDA_PYTORCH=pytorch=1.5.0 cudatoolkit=10.2
PIP_PYTORCH=torch==1.5.0 -f https://download.pytorch.org/whl/cu102/torch_stable.html
CHAINER_VERSION=6.0.0
PIP_CHAINER=chainer==6.0.0
NO_CUPY=0
. ./activate_python.sh && /data/rd/zhujun/TTS2/espnet/tools/anaconda/envs/zjespnet2/bin/python -m pip install -e "..[recipe]"  # Install editable mode by default
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Obtaining file:///data/rd/zhujun/TTS2/espnet
    ERROR: Command errored out with exit status 1:
     command: /data/rd/zhujun/TTS2/espnet/tools/anaconda/envs/zjespnet2/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/rd/zhujun/TTS2/espnet/setup.py'"'"'; __file__='"'"'/data/rd/zhujun/TTS2/espnet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-qhcia464
         cwd: /data/rd/zhujun/TTS2/espnet/
    Complete output (33 lines):
    WARNING: The repository located at mirrors.aliyun.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.aliyun.com'.
    ERROR: Could not find a version that satisfies the requirement pytest-runner
    ERROR: No matching distribution found for pytest-runner
    Traceback (most recent call last):
      File "/data/rd/zhujun/TTS2/espnet/tools/anaconda/envs/zjespnet2/lib/python3.8/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/data/rd/zhujun/TTS2/espnet/tools/anaconda/envs/zjespnet2/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/data/rd/zhujun/TTS2/espnet/tools/anaconda/envs/zjespnet2/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpmg6g6rpa', '--quiet', 'pytest-runner']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/rd/zhujun/TTS2/espnet/setup.py", line 131, in <module>
        setup(
      File "/data/rd/zhujun/TTS2/espnet/tools/anaconda/envs/zjespnet2/lib/python3.8/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/data/rd/zhujun/TTS2/espnet/tools/anaconda/envs/zjespnet2/lib/python3.8/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/data/rd/zhujun/TTS2/espnet/tools/anaconda/envs/zjespnet2/lib/python3.8/site-packages/setuptools/dist.py", line 686, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/data/rd/zhujun/TTS2/espnet/tools/anaconda/envs/zjespnet2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 766, in resolve
        dist = best[req.key] = env.best_match(
      File "/data/rd/zhujun/TTS2/espnet/tools/anaconda/envs/zjespnet2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "/data/rd/zhujun/TTS2/espnet/tools/anaconda/envs/zjespnet2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1063, in obtain
        return installer(requirement)
      File "/data/rd/zhujun/TTS2/espnet/tools/anaconda/envs/zjespnet2/lib/python3.8/site-packages/setuptools/dist.py", line 745, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/data/rd/zhujun/TTS2/espnet/tools/anaconda/envs/zjespnet2/lib/python3.8/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/data/rd/zhujun/TTS2/espnet/tools/anaconda/envs/zjespnet2/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpmg6g6rpa', '--quiet', 'pytest-runner']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
make: *** [espnet.done] Error 1
```
And I don't know how to do with it, hope you can help me, thanks!

**Comment by kamo-naoyuki** [comment]
> Looking in indexes: http://mirrors.aliyun.com/pypi/simple/

You are using mirror index server. Check your pipyrc or pip.conf

**Comment by Mingrg** [comment]
Hi @kamo-naoyuki,
    Thank you for your reply! And I do not use mirror index server now, the error disappointed!
    But another error occurred:
```
[SanJunipero@BJ-SJ-SUFAGPU-100-103 tools]$ make
CUDA_VERSION=10.2
. ./activate_python.sh && python3 check_pytorch_cuda_compatibility.py 1.5.0 "10.2" || { echo "Change TH_VERSION or CUDA_VERSION"; exit 1; }
10.2
PYTHON=/data/rd/zhujun/espnet/tools/anaconda/envs/espnet/bin/python3
PYTHON_VERSION=Python 3.8.5
IS_CONDA=0
USE_PIP=
TH_VERSION=1.5.0
CONDA_PYTORCH=pytorch=1.5.0 cudatoolkit=10.2
PIP_PYTORCH=torch==1.5.0 -f https://download.pytorch.org/whl/cu102/torch_stable.html
CHAINER_VERSION=6.0.0
PIP_CHAINER=chainer==6.0.0
NO_CUPY=0
. ./activate_python.sh && python3 -m pip install -e "..[recipe]"  # Install editable mode by default
Obtaining file:///data/rd/zhujun/espnet
Requirement already satisfied: setuptools>=38.5.1 in ./anaconda/envs/espnet/lib/python3.8/site-packages (from espnet==0.9.6) (52.0.0.post20210125)
Requirement already satisfied: configargparse>=1.2.1 in ./anaconda/envs/espnet/lib/python3.8/site-packages (from espnet==0.9.6) (1.2.3)
......
......
Requirement already satisfied: pathtools>=0.1.1 in ./anaconda/envs/espnet/lib/python3.8/site-packages (from watchdog<0.10.5,>=0.8.3->wandb->espnet==0.9.6) (0.1.2)
Collecting youtube_dl
  Using cached youtube_dl-2021.1.24.1-py2.py3-none-any.whl (1.9 MB)
Installing collected packages: espnet, youtube-dl, pystoi, nnmnkwii, museval, morfessor, mir-eval, gdown, espnet-model-zoo
  Running setup.py develop for espnet
    ERROR: Command errored out with exit status 1:
     command: /data/rd/zhujun/espnet/tools/anaconda/envs/espnet/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/rd/zhujun/espnet/setup.py'"'"'; __file__='"'"'/data/rd/zhujun/espnet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /data/rd/zhujun/espnet/
    Complete output (3 lines):
    running develop
    running egg_info
    error: [Errno 13] Permission denied
    ----------------------------------------
ERROR: Command errored out with exit status 1: /data/rd/zhujun/espnet/tools/anaconda/envs/espnet/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/rd/zhujun/espnet/setup.py'"'"'; __file__='"'"'/data/rd/zhujun/espnet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
make: *** [espnet.done] Error 1
```
Is there any permission problem? I don't have root permission. Where should I change?

**Comment by Mingrg** [comment]
> > Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
> 
> You are using mirror index server. Check your pipyrc or pip.conf

Thank you so much! It work!
