### ISSUE TITLE
Memory problem

### ISSUE THREAD

**Issue by b-flo** [espnet/espnet#292]
Hi,

I'm currently doing some experiments on end2end approaches for french using your toolkit but I'm facing a weird memory behaviour when training any network using attention mechanism.
Every training I tried end up with an out-of-memory at the same point, even if I try to set up to a tiny batch size or reduce any parameters of the network which could alleviate the related calculation.
I have 3 Titan X (Pascal) of 12GB and the problem is the same using mono or multi GPU with chainer or pytorch as backend.
Interesting enough using batch size below 8 make the GPUs go out-of-memory faster than using batch size of bigger size!

Example using pytorch on a single GPU when training with MTL=0.0, ctc_weight=0.0, and reduced layers and units : 
```
Traceback (most recent call last):                                                                                                                                            
  File "/home/fboye/espnet/egs/ester/asr1/../../../src/bin/asr_train.py", line 224, in <module>                                                                                   
    main()                                                                                                                                                                        
  File "/home/fboye/espnet/egs/ester/asr1/../../../src/bin/asr_train.py", line 218, in main                                                                                       
    train(args)                                                                                                                                                                   
  File "/home/fboye/espnet/src/asr/asr_pytorch.py", line 377, in train                                                                                                            
    trainer.run()                                                                                                                                                                 
  File "/home/fboye/espnet/tools/venv/local/lib/python2.7/site-packages/chainer/training/trainer.py", line 320, in run                                                            
    six.reraise(*sys.exc_info())                                                                                                                                                  
  File "/home/fboye/espnet/tools/venv/local/lib/python2.7/site-packages/chainer/training/trainer.py", line 306, in run                                                            
    update()                                                                                                                                                                      
  File "/home/fboye/espnet/tools/venv/local/lib/python2.7/site-packages/chainer/training/updaters/standard_updater.py", line 149, in update                                       
    self.update_core()                                                                                                                                                            
  File "/home/fboye/espnet/src/asr/asr_pytorch.py", line 122, in update_core                                                                                                      
    loss = 1. / self.num_gpu * self.model(x)                                                                                                                                      
  File "/home/fboye/espnet/tools/venv/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__                                                        
    result = self.forward(*input, **kwargs)                                                                                                                                       
  File "/home/fboye/espnet/src/nets/e2e_asr_attctc_th.py", line 120, in forward                                                                                                   
    loss_ctc, loss_att, acc = self.predictor(x)                                                                                                                                   
  File "/home/fboye/espnet/tools/venv/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__                                                        
    result = self.forward(*input, **kwargs)                                                                                                                                       
  File "/home/fboye/espnet/src/nets/e2e_asr_attctc_th.py", line 336, in forward                                                                                                   
    loss_att, acc = self.dec(hpad, hlens, ys)                                                                                                                                     
  File "/home/fboye/espnet/tools/venv/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__                                                        
    result = self.forward(*input, **kwargs)                                                                                                                                       
  File "/home/fboye/espnet/src/nets/e2e_asr_attctc_th.py", line 1724, in forward                                                                                                  
    att_c, att_w = self.att(hpad, hlen, z_list[0], att_w)                                                                                                                         
  File "/home/fboye/espnet/tools/venv/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__                                                        
    result = self.forward(*input, **kwargs)                                                                                                                                       
  File "/home/fboye/espnet/src/nets/e2e_asr_attctc_th.py", line 793, in forward                                                                                                   
    att_conv + self.pre_compute_enc_h + dec_z_tiled)).squeeze(2)                                                                                                                  
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58                                                                            
# Accounting: time=961 threads=1                                                                                                                                                  
# Ended (code 1) at Thu Jul 12 19:59:44 CEST 2018, elapsed time 961 seconds  
```

My dataset contains longer segments and sentences than most commons dataset but I didn't face any problem using your CTC with big batches or my implementation of your MTL training approach in TensorFlow.

Do you have any idea what could be the problem or what I should check to pinpoint the problem? I tried to reinstall all requirements and espnet, checked all current memory related problems for most of the used libs but I couldn't find anything.

**Comment by sw005320** [comment]
> Every training I tried end up with an out-of-memory at the same point, even if I try to set up to a tiny batch size or reduce any parameters of the network which could alleviate the related calculation.
> I have 3 Titan X (Pascal) of 12GB and the problem is the same using mono or multi GPU with chainer or pytorch as backend.

Can you make sure that the input and output lengths?
`--verbose 1` tells you these information for each minibatch.
The attention mechanism requires (input length x output length) GPU memories, and this GPU out-of-memory issue would be easily happened. If it processes the long sentence, 
I usually remove long sentences that have more than 3000 input frames or 400 characters (see https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/run.sh#L130-L133). 

> Interesting enough using batch size below 8 make the GPUs go out-of-memory faster than using batch size of bigger size!

When we change the minibatch size, the shuffled order would be changed, and that may happen.

> CTC with big batches or my implementation of your MTL training approach in TensorFlow.

Only CTC would not be a bid problem. Also, I'm not familiar with TensorFlow, and I don't have a sense for that.
