### ISSUE TITLE
Stage 5 error in egs/ljspeech/asr1 (phoneme-level)

### ISSUE THREAD

**Issue by lnalborczyk** [espnet/espnet#2931]
**Describe the bug**

I can not get the LJspeech ASR example working at the phonetic level... when replacing "char" by "phn" in run.sh, everything works fine until stage 5, but I get and error during decoding. Here is one of the log file below (`espnet/egs/ljspeech/asr1/exp/phn_train_no_dev_pytorch_train_mtlalpha1.0/decode_phn_dev_decode_ctcweight1.0_lm_word100/log/decode.1.log`).

Any idea why this is happening and how to make it work at the phoneme rather than at the character level?

**Basic environments:**
 - OS information: OS information: Linux 4.15.0-101-generic #102~16.04.1-Ubuntu SMP Mon May 11 11:38:16 UTC 2020 x86_64
 - python version: Python 3.7.9 (default, Aug 18 2020, 06:24:24) [GCC 5.4.0 20160609]
 - espnet version: 0.9.6
 - Git hash [e.g. b88e89fc7246fed4c2842b55baba884fe1b4ecc2]
 - Commit date [e.g. Tue Sep 1 09:32:54 2020 -0400]
 - pytorch version pytorch 1.4.0
 

**Environments from `torch.utils.collect_env`:**

```
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.7 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Tesla P4
Nvidia driver version: 455.23.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.4
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.3

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.0
[pip3] torch==1.4.0
[pip3] torch-complex==0.2.0
[pip3] torch-optimizer==0.1.0
[pip3] torchaudio==0.4.0
[pip3] warpctc-pytorch==0.2.1
[conda] Could not collect
```

**Task information:**
 - Task: ASR
 - Recipe: LJspeech
 - ESPnet1

**To Reproduce**
1. move to a recipe directory, e.g., `cd egs/ljspeech/asr1`
2. execute `./run.sh` (with "phn" rather than "char")
3. specify the error log, e.g., `exp/xxx/yyy.log`

**Error logs**

```
2021-01-26 17:57:39,815 (asr_recog:305) INFO: python path = (None)
2021-01-26 17:57:39,815 (asr_recog:310) INFO: set random seed = 1
2021-01-26 17:57:39,815 (asr_recog:321) INFO: backend = pytorch
2021-01-26 17:57:45,134 (deterministic_utils:26) INFO: torch type check is disabled
2021-01-26 17:57:45,139 (asr_utils:656) INFO: reading a config file from exp/phn_train_no_dev_pytorch_train_mtlalpha1.0/results/model.json
2021-01-26 17:57:45,140 (asr_init:169) WARNING: reading model parameters from exp/phn_train_no_dev_pytorch_train_mtlalpha1.0/results/model.loss.best
2021-01-26 17:57:45,141 (nets_utils:426) INFO: subsample: 1 2 2 1 1
2021-01-26 17:57:45,223 (encoders:298) INFO: BLSTM with every-layer projection for encoder
2021-01-26 17:57:45,418 (asr:918) INFO:  Total parameter of the model = 8170407
2021-01-26 17:57:45,419 (asr_utils:656) INFO: reading a config file from exp/train_rnnlm_pytorch_lm_word100/model.json
Traceback (most recent call last):
  File "/research/crissp/espnet/egs/ljspeech/asr1/../../../espnet/bin/asr_recog.py", line 363, in <module>
    main(sys.argv[1:])
  File "/research/crissp/espnet/egs/ljspeech/asr1/../../../espnet/bin/asr_recog.py", line 341, in main
    recog(args)
  File "/research/crissp/espnet/espnet/asr/pytorch_backend/asr.py", line 965, in recog
    word_rnnlm.predictor, word_dict, char_dict
  File "/research/crissp/espnet/espnet/lm/pytorch_backend/extlm.py", line 129, in __init__
    self.space = subword_dict["<space>"]
KeyError: '<space>'
# Accounting: time=6 threads=1
# Ended (code 1) at Tue Jan 26 17:57:45 CET 2021, elapsed time 6 seconds
```

**Comment by lnalborczyk** [comment]
NB: I also get the same error with the corpus phonetised by myself...

**Comment by kan-bayashi** [comment]
You may not be able to use word LM for phoneme.

**Comment by lnalborczyk** [comment]
Why is that? It seems to work well in other recipes...

**Comment by kan-bayashi** [comment]
Actually there is no ASR recipe using phoneme. Please use char LM.

**Comment by lnalborczyk** [comment]
Thanks for your answer. Sorry if that is a newbie question, but how can I disable the LM?

**Comment by kan-bayashi** [comment]
Remove lm related options here
https://github.com/espnet/espnet/blob/46f1e6b9ea9d2edd002690719e07cc5b97c7e4ac/egs/ljspeech/asr1/run.sh#L225-L229
