### ISSUE TITLE
Exception about Kaldi file format in the CSJ recipe.

### ISSUE THREAD

**Issue by jnishi** [espnet/espnet#295]
Hi.

Would you mind helping me? I run the CSJ script (egs/csj/asr1/run.sh)  with a command below.
`$ ./run.sh --ngpu 2 --batchsize 64 --elayers 4`

However, in the stage 4, an exception is thrown, and training process did not proceed any more.

This is error message which is written in `/egs/csj/asr1/exp/train_nodup_vggblstmp_e4_subsample1_2_2_1_1_unit320_proj320_d1_unit300_location_adim320_aconvc10_aconvf100_mtlalpha0.5_adadelta_bs64_mli800_mlo150/train.log`.

```
Exception in main training loop:
Traceback (most recent call last):
  File "/home/christopher/gitrepos/espnet-1/tools/venv/lib/python2.7/site-packages/chainer/training/trainer.py", line 306, in run
    update()
  File "/home/christopher/gitrepos/espnet-1/tools/venv/lib/python2.7/site-packages/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/home/christopher/gitrepos/espnet-1/src/asr/asr_chainer.py", line 112, in update_core
    x = self.converter(batch)
  File "/home/christopher/gitrepos/espnet-1/src/asr/asr_utils.py", line 58, in converter_kaldi
    feat = kaldi_io_py.read_mat(data[1]['input'][0]['feat'])
  File "/home/christopher/gitrepos/espnet-1/src/utils/kaldi_io_py.py", line 366, in read_mat
    mat = _read_mat_binary(fd)
  File "/home/christopher/gitrepos/espnet-1/src/utils/kaldi_io_py.py", line 378, in _read_mat_binary
    if header.startswith('CM'): return _read_compressed_mat(fd, header)
  File "/home/christopher/gitrepos/espnet-1/src/utils/kaldi_io_py.py", line 413, in _read_compressed_mat
    assert(format == 'CM ') # The formats CM2, CM3 are not supported...
Will finalize trainer extensions and updater before reraising the exception.
```

Is there any method to avoid?

**Comment by jnishi** [comment]
Thank you for comments. I'm going to try it.

I also run the librispeech's recipe, but the error does not happen.

**Comment by jnishi** [comment]
Sorry, I have not run the recipe of librispeech with the current master version. I'm going to run it later.

**Comment by jnishi** [comment]
I tried the librispeech recipe again with current master version. I run it only 1 epoch, but used whole train data. The error did not happen.

**Comment by sas91** [comment]
I faced the same issue recently. Guess this https://github.com/espnet/espnet/pull/319 should solve this issue.
