### ISSUE TITLE
Zenodo Upload "Validation error"

### ISSUE THREAD

**Issue by akreal** [espnet/espnet#2962]
Hello! I've set my `ACCESS_TOKEN` and try to upload a model, but get some "Validation error":

```
./run.sh --stage 14 --skip_upload false
2021-02-12T18:42:08 (asr.sh:220:main) ./asr.sh --lang ru --ngpu 4 --nbpe 100 --max_wav_duration 30 --audio_format flac.ark --asr_config conf/train_asr_conformer.yaml --lm_config conf/train_lm_transformer.yaml --inference_config conf/decode_asr.yaml --train_set train --valid_set dev --test_sets asr_calls_2_val buriy_audiobooks_2_val public_youtube700_val --lm_train_text data/train/text --stage 14 --skip_upload false
2021-02-12T18:42:08 (asr.sh:1322:main) Stage 14: Upload model to Zenodo: exp/asr_train_asr_conformer_raw_ru_bpe100/asr_train_asr_conformer_raw_ru_bpe100_valid.acc.ave.zip
Traceback (most recent call last):
File "/mount/arbeitsdaten45/projekte/asr-4/denisopl/espnet-ru/tools/venv/bin/espnet_model_zoo_upload", line 8, in <module>
sys.exit(main())
File "/mount/arbeitsdaten45/projekte/asr-4/denisopl/espnet-ru/tools/venv/lib64/python3.8/site-packages/espnet_model_zoo/zenodo_upload.py", line 295, in main
upload_espnet_model(**kwargs)
File "/mount/arbeitsdaten45/projekte/asr-4/denisopl/espnet-ru/tools/venv/lib64/python3.8/site-packages/espnet_model_zoo/zenodo_upload.py", line 201, in upload_espnet_model
upload(
File "/mount/arbeitsdaten45/projekte/asr-4/denisopl/espnet-ru/tools/venv/lib64/python3.8/site-packages/espnet_model_zoo/zenodo_upload.py", line 163, in upload
zenodo.update_metadata(r, data)
File "/mount/arbeitsdaten45/projekte/asr-4/denisopl/espnet-ru/tools/venv/lib64/python3.8/site-packages/espnet_model_zoo/zenodo_upload.py", line 80, in update_metadata
raise RuntimeError(r.json()["message"])
RuntimeError: Validation error.
```

Does anybody know what is the problem?

**Comment by sw005320** [comment]
Thanks, @akreal for the report.
I have recently uploaded models (one week ago), and I did not encounter such issues...
Was it stopped always with this error?

**Comment by akreal** [comment]
Yes, I tried several times and it was always this error.

**Comment by kamo-naoyuki** [comment]
Probably, the meta data has some problems. Could you print this value?

https://github.com/espnet/espnet_model_zoo/blob/893a934d260a91238efdc481b10870fda389f98e/espnet_model_zoo/zenodo_upload.py#L76

```python
        print(data)
        r = requests.put(
            f"{self.zenodo_url}/api/deposit/depositions/{deposition_id}",
            params=self.params,
            data=json.dumps(data),
            headers=self.headers,
        )
```

**Comment by kamo-naoyuki** [comment]
Otherwise, could you try with commenting this line?

https://github.com/espnet/espnet_model_zoo/blob/893a934d260a91238efdc481b10870fda389f98e/espnet_model_zoo/zenodo_upload.py#L163

```python
#     zenodo.update_metadata(r, data)
```

**Comment by akreal** [comment]
I tried to print the whole response:
```
{'status': 400, 'message': 'Validation error.', 'errors': [{'field': 'metadata.communities', 'message': 'Invalid communities: espnet'}]}
```

Relevant part of the meta data:
```
'communities': [{'identifier': 'espnet'}]
```

**Comment by kamo-naoyuki** [comment]
@sw005320 Why you deleted espnet community on zenodo? It causes this error.

**Comment by sw005320** [comment]
I actually cannot login to the zenodo.
Something seems to happen.
I’ll try another way.

**Comment by kamo-naoyuki** [comment]
@akreal Now I removed the item from metadata. Please update espnet_model_zoo

```
pip install -U espnet_model_zoo
```

Sorry for the inconvenience.

**Comment by akreal** [comment]
Now it worked. Thanks for you help!
