### ISSUE TITLE
`TypeError: plotfn() takes from 4 to 6 positional arguments but 7 were given` in Transformer-TTS

### ISSUE THREAD

**Issue by KAIMAN0** [espnet/espnet#2984]
**Describe the bug**
TypeError when train the egs/vcc20/vc1_task1/ also in egs/arctic/vc1/

**Conda environments:**
 - OS information: Ubuntu 18.04
 - python version: 3.7
 - espnet version: 0.9.7
 - Git hash [f1ad94ec49ccb61bcfba0175ae234609cee292a8]
   - Commit date [Thu Feb 18 04:09:51 2021 +0000]
 - pytorch version: 1.7.1
 - chainer version: 6.0.0
 
**Task information:**
 - Task: [TTS/VC]
 - Recipe: [vcc20/vc1_task1]
 - ESPnet1

**To Reproduce**
1. `cd egs/vcc20/vc1_task1/`
2. `./run.sh --stop_stage 6 --spk TEF1 --pretrained_model_name tts1`
3. `exp/xxx/train.log`

**Error logs**
> 2021-02-18 17:31:44,511 (tts_train:320) WARNING: Skip DEBUG/INFO messages
^[[JException in main training loop: plotfn() takes from 4 to 6 positional arguments but 7 were given
Traceback (most recent call last):
  File "\~/anaconda3/envs/espnet/lib/python3.7/site-packages/chainer/training/trainer.py", line 319, in run
    entry.extension(self)
  File "\~/Project/espnet/espnet/utils/training/evaluator.py", line 15, in __call__
    tb_logger(trainer)
  File "\~/Project/espnet/espnet/utils/training/tensorboard_logger.py", line 45, in __call__
    self._att_reporter.log_attentions(self._logger, trainer.updater.iteration)
  File "\~/Project/espnet/espnet/nets/pytorch_backend/transformer/plot.py", line 146, in log_attentions
    self.plotfn(self.data_dict, uttid_list, attn_dict, self.outdir, "", log_fig)
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "\~/Project/espnet/egs/vcc20/vc1_task1/../../../espnet/bin/tts_train.py", line 359, in <module>
    main(sys.argv[1:])
  File "\~/Project/espnet/egs/vcc20/vc1_task1/../../../espnet/bin/tts_train.py", line 353, in main
    train(args)
  File "\~/Project/espnet/espnet/tts/pytorch_backend/tts.py", line 555, in train
    trainer.run()
  File "\~/anaconda3/envs/espnet/lib/python3.7/site-packages/chainer/training/trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "\~/anaconda3/envs/espnet/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "\~/anaconda3/envs/espnet/lib/python3.7/site-packages/chainer/training/trainer.py", line 319, in run
    entry.extension(self)
  File "\~/Project/espnet/espnet/utils/training/evaluator.py", line 15, in __call__
    tb_logger(trainer)
  File "\~/Project/espnet/espnet/utils/training/tensorboard_logger.py", line 45, in __call__
    self._att_reporter.log_attentions(self._logger, trainer.updater.iteration)
  File "\~/Project/espnet/espnet/nets/pytorch_backend/transformer/plot.py", line 146, in log_attentions
    self.plotfn(self.data_dict, uttid_list, attn_dict, self.outdir, "", log_fig)
TypeError: plotfn() takes from 4 to 6 positional arguments but 7 were given

**Comment by kan-bayashi** [comment]
Thank you for your report.
I reproduced this error. I will fix it.
