### ISSUE TITLE
"can't set attribute" in lm_train.py

### ISSUE THREAD

**Issue by jimbozhang** [espnet/espnet#3020]
**Describe the bug**
Please check the "To Reproduce" and the "Error logs" parts.

**Basic environments:**
```
- python version: `3.8.6 (default, Oct 27 2020, 09:13:12)  [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]`
- espnet version: `espnet 0.9.7`
- pytorch version: `pytorch 1.4.0`
- Git hash: `7b78b65aa99bac67e2666236c54f78c3301387aa`
  - Commit date: `Thu Feb 25 18:49:26 2021 +0000`
```

**Environments from `torch.utils.collect_env`:**
```
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: CentOS Linux release 7.3.1611 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
CMake version: version 3.18.4

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla V100-PCIE-32GB
GPU 1: Tesla V100-PCIE-32GB
GPU 2: Tesla V100-PCIE-32GB
GPU 3: Tesla V100-PCIE-32GB
GPU 4: Tesla V100-PCIE-32GB
GPU 5: Tesla V100-PCIE-32GB
GPU 6: Tesla V100-PCIE-32GB
GPU 7: Tesla V100-PCIE-32GB

Nvidia driver version: 450.51.06
cuDNN version: Probably one of the following:
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.0
[pip3] torch==1.4.0
[pip3] torch-complex==0.2.0
[pip3] torch-optimizer==0.1.0
[pip3] torchaudio==0.4.0
```

**Task information:**
 - Task: ASR
 - Recipe: librispeech
 - ESPnet1

**To Reproduce**
1. move the libirispeech recipe directory: `cd egs/librispeech/asr1`
2. execute `run.sh`, without any extra arguments
3. the error log: `exp/train_rnnlm_pytorch_lm_unigram5000_ngpu8/train.log`

**Error logs**
```
# lm_train.py --config conf/lm.yaml --ngpu 8 --backend pytorch --verbose 1 --outdir exp/train_rnnlm_pytorch_lm_unigram5000_ngpu8 --tensorboard-dir tensorboard/train_rnnlm_pytorch_lm_unigram5000_ngpu8 --train-label data/local/lm_train_unigram5000/train.txt --valid-label data/local/lm_train_unigram5000/valid.txt --resume --dict data/lang_char/train_960_unigram5000_units.txt --dump-hdf5-path data/local/lm_train_unigram5000
# Started at Fri Feb 26 14:07:05 CST 2021
#
2021-02-26 14:07:06,373 (lm_train:254) INFO: ngpu: 8
2021-02-26 14:07:06,373 (lm_train:257) INFO: python path = (None)
2021-02-26 14:07:06,377 (lm_train:274) INFO: backend = pytorch
2021-02-26 14:07:07,477 (lm:223) INFO: torch version = 1.4.0
2021-02-26 14:07:07,478 (deterministic_utils:26) INFO: torch type check is disabled
2021-02-26 14:07:17,731 (lm_utils:40) INFO: loading binary dataset: data/local/lm_train_unigram5000/valid.txt.h5
2021-02-26 14:07:17,774 (lm_utils:40) INFO: loading binary dataset: data/local/lm_train_unigram5000/train.txt.h5
2021-02-26 14:08:45,924 (lm:241) INFO: #vocab = 5002
2021-02-26 14:08:45,924 (lm:242) INFO: #sentences in the training data = 40699491
2021-02-26 14:08:45,925 (lm:243) INFO: #tokens in the training data = 1022396479
2021-02-26 14:08:45,925 (lm:244) INFO: oov rate in the training data = 0.00 %
2021-02-26 14:08:45,925 (lm:248) INFO: #sentences in the validation data = 5542
2021-02-26 14:08:45,925 (lm:249) INFO: #tokens in the validation data = 128689
2021-02-26 14:08:45,925 (lm:250) INFO: oov rate in the validation data = 0.00 %
2021-02-26 14:08:45,925 (lm:258) INFO: batch size is automatically increased (32 -> 256)
2021-02-26 14:09:15,590 (lm:274) INFO: #iterations per epoch = 191667
2021-02-26 14:09:15,590 (lm:275) INFO: #total iterations = 9583350
2021-02-26 14:09:15,614 (encoder:151) INFO: encoder self-attention layer type = self-attention
2021-02-26 14:09:19,447 (lm:291) INFO: writing a model config file to exp/train_rnnlm_pytorch_lm_unigram5000_ngpu8/model.json
2021-02-26 14:09:19,459 (lm:298) WARNING: num. model params: 53,712,522 (num. trained: 53,712,522 (100.0%))

2021-02-26 14:09:19,461 (lm:337) INFO: gpu_id: [0, 1, 2, 3, 4, 5, 6, 7]   # I made this log line for debugging
2021-02-26 14:09:19,461 (lm:119) INFO: device: [0, 1, 2, 3, 4, 5, 6, 7]   # I made this log line for debugging

Traceback (most recent call last):
  File "/home/zj/src/espnet/egs/librispeech/asr1/../../../espnet/bin/lm_train.py", line 288, in <module>
    main(sys.argv[1:])
  File "/home/zj/src/espnet/egs/librispeech/asr1/../../../espnet/bin/lm_train.py", line 282, in main
    train(args)
  File "/home/zj/src/espnet/espnet/lm/pytorch_backend/lm.py", line 338, in train
    updater = BPTTUpdater(
  File "/home/zj/src/espnet/espnet/lm/pytorch_backend/lm.py", line 120, in __init__
    self.device = device
AttributeError: can't set attribute
# Accounting: time=147 threads=1
# Ended (code 1) at Fri Feb 26 14:09:32 CST 2021, elapsed time 147 seconds
```

**Comment by jimbozhang** [comment]
Interim solution: downgrade `chainer` from v7.7.0 to v6.0.0.
Final solution: modify the codes to fit the latest version's chainer.
