### ISSUE TITLE
espnet2 AISHELL training use my own Dataset in Stage 9: ASR collect stats

### ISSUE THREAD

**Issue by BarryKCL** [espnet/espnet#3129]
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 35, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.6/dist-packages/espnet2/train/collate_fn.py", line 42, in __call__
    not_sequence=self.not_sequence,
  File "/usr/local/lib/python3.6/dist-packages/espnet2/train/collate_fn.py", line 94, in common_collate_fn
    tensor = pad_list(tensor_list, pad_value)
  File "/usr/local/lib/python3.6/dist-packages/espnet/nets/pytorch_backend/nets_utils.py", line 59, in pad_list
    pad[i, : xs[i].size(0)] = xs[i]
RuntimeError: expand(torch.FloatTensor{[114320, 2]}, size=[114320]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)

# Accounting: time=36 threads=1
# Ended (code 1) at Fri Apr  2 12:35:41 CST 2021, elapsed time 36 seconds

**Comment by BarryKCL** [comment]
duo to dual channel audio.
