### ISSUE TITLE
Error in the **d.download_and_unpack(tag) of 

### ISSUE THREAD

**Issue by AMG222** [espnet/espnet#3166]
**Describe the issue**
Hi, I have a problem when I try to dowload the files in this instruction **d.download_and_unpack(tag)
Please help

```
cd <espnet-root>
python eje.py
Where eje.py is:
Begin OF eje.py FILE
#@title Choose English model { run: "auto" }

lang = 'English'
fs = 22050 #@param {type:"integer"}
tag = 'kan-bayashi/ljspeech_conformer_fastspeech2' #@param ["kan-bayashi/ljspeech_tacotron2", "kan-bayashi/ljspeech_fastspeech", "kan-bayashi/ljspeech_fastspeech2", "kan-bayashi/ljspeech_conformer_fastspeech2"] {type:"string"}
vocoder_tag = "ljspeech_parallel_wavegan.v1" #@param ["ljspeech_parallel_wavegan.v1", "ljspeech_full_band_melgan.v2", "ljspeech_multi_band_melgan.v2"] {type:"string"}

import time
import torch
from espnet_model_zoo.downloader import ModelDownloader
from espnet2.bin.tts_inference import Text2Speech
from parallel_wavegan.utils import download_pretrained_model
from parallel_wavegan.utils import load_model
d = ModelDownloader()
text2speech = Text2Speech(
    **d.download_and_unpack(tag),
    device="cuda",
    # Only for Tacotron 2
    threshold=0.5,
    minlenratio=0.0,
    maxlenratio=10.0,
    use_att_constraint=False,
    backward_window=1,
    forward_window=3,
    # Only for FastSpeech & FastSpeech2
    speed_control_alpha=1.0,
)
text2speech.spc2wav = None  # Disable griffin-lim
# NOTE: Sometimes download is failed due to "Permission denied". That is 
#   the limitation of google drive. Please retry after serveral hours.
vocoder = load_model(download_pretrained_model(vocoder_tag)).to("cuda").eval()
vocoder.remove_weight_norm()

# decide the input sentence by yourself
print(f"Input your favorite sentence in {lang}.")
x = input()

# synthesis
with torch.no_grad():
    start = time.time()
    wav, c, *_ = text2speech(x)
    wav = vocoder.inference(c)
rtf = (time.time() - start) / (len(wav) / fs)
print(f"RTF = {rtf:5f}")

# let us listen to generated samples
from IPython.display import display, Audio
display(Audio(wav.view(-1).cpu().numpy(), rate=fs))

End OF eje.py FILE
```

**Basic environments:**
 - OS information: Windows 10 x64
 - python version: 3.9.4
 - espnet version: 0.9.9

```
**Error logs**
https://zenodo.org/record/4036268/files/tts_train_conformer_fastspeech2_raw_phn_tacotron_g2p_en_no_space_train.loss.ave
Traceback (most recent call last):
  File "D:\Proyecto\trabajo\espnet\eje.py", line 16, in <module>
    **d.download_and_unpack(tag),
  File "D:\Python3_9\lib\site-packages\espnet_model_zoo\downloader.py", line 290, in download_and_unpack
    filename = self.download(url, quiet=quiet)
  File "D:\Python3_9\lib\site-packages\espnet_model_zoo\downloader.py", line 267, in download
    raise RuntimeError(f"Failed to download file: {url}")
RuntimeError: Failed to download file: https://zenodo.org/record/4036268/files/tts_train_conformer_fastspeech2_raw_phn_tacotron_g2p_en_no_space_train.loss.ave.zip?download=1
```

**Comment by kan-bayashi** [comment]
zenodo seems down. Please retry several hours later.

**Comment by AMG222** [comment]
OMG Thanks, How I can execute the final part for use it without Internet conexion?

**Comment by AMG222** [comment]
But in the colab runs well

**Comment by kan-bayashi** [comment]
> How I can execute the final part for use it without Internet conexion?

Of course you need the internet connection.
If not, please download it manually and use it.

**Comment by kan-bayashi** [comment]
You can pass these arguments manually.
https://github.com/espnet/espnet/blob/e4a0018eeb408440fb2b40cb5b1130ac64c475fa/espnet2/bin/tts_inference.py#L54-L55

**Comment by AMG222** [comment]
And wich arguments I need to use I'm confused

**Comment by kan-bayashi** [comment]
`train_config` and `model_file`.

**Comment by AMG222** [comment]
And where are they? now I have this only to say hello world
import soundfile
import time
import torch
from espnet_model_zoo.downloader import ModelDownloader
from espnet2.bin.tts_inference import Text2Speech
from parallel_wavegan.utils import download_pretrained_model
from parallel_wavegan.utils import load_model
text2speech = Text2Speech("config.yml", "model.pth")
wav = text2speech("Hello World")[0]
soundfile.write("out.wav", wav.numpy(), text2speech.fs, "PCM_16")

**Comment by kan-bayashi** [comment]
I could not understand your question.
I assume that you cannot use the internet connection in your env.
1. Download https://zenodo.org/record/4036268/files/tts_train_conformer_fastspeech2_raw_phn_tacotron_g2p_en_no_space_train.loss.ave.zip?download=1
2. Locate the file in your python env and unzip it.
3. Edit your code to specify the `traing_config` and `model_path` instead of `**d.download...`.

**Comment by AMG222** [comment]
Aaaaa thank you

**Comment by AMG222** [comment]
With this code
```
#@title Choose English model { run: "auto" }
tag = 'kan-bayashi/ljspeech_conformer_fastspeech2' #@param ["kan-bayashi/ljspeech_tacotron2", "kan-bayashi/ljspeech_fastspeech", "kan-bayashi/ljspeech_fastspeech2", "kan-bayashi/ljspeech_conformer_fastspeech2"] {type:"string"}
vocoder_tag = "ljspeech_parallel_wavegan.v1" #@param ["ljspeech_parallel_wavegan.v1", "ljspeech_full_band_melgan.v2", "ljspeech_multi_band_melgan.v2"] {type:"string"}

import time
import torch
from espnet_model_zoo.downloader import ModelDownloader
from espnet2.bin.tts_inference import Text2Speech
from parallel_wavegan.utils import download_pretrained_model
from parallel_wavegan.utils import load_model
d = ModelDownloader()
text2speech = Text2Speech(
    train_config = "config.yaml", 
    model_file = "train.loss.ave_5best.pth",
    device="cuda",
    # Only for Tacotron 2
    #threshold=0.5,
    #minlenratio=0.0,
    #maxlenratio=10.0,
    #use_att_constraint=False,
    #backward_window=1,
    #forward_window=3,
    # Only for FastSpeech & FastSpeech2
    speed_control_alpha=1.0,
)
text2speech.spc2wav = None  # Disable griffin-lim
# NOTE: Sometimes download is failed due to "Permission denied". That is 
#   the limitation of google drive. Please retry after serveral hours.
vocoder = load_model(download_pretrained_model(vocoder_tag)).to("cuda").eval()
vocoder.remove_weight_norm()

lang = 'English'
print(f"Input the number of fs (recomended 22050).")
fs = input() #@param {type:"integer"}
# decide the input sentence by yourself
print(f"Input your favorite sentence in {lang}.")
x = input()

# synthesis
with torch.no_grad():
    start = time.time()
    wav, c, *_ = text2speech(x)
    wav = vocoder.inference(c)
rtf = (time.time() - start) / (len(wav) / fs)
print(f"RTF = {rtf:5f}")

# let us listen to generated samples
from IPython.display import display, Audio
display(Audio(wav.view(-1).cpu().numpy(), rate=fs))
```
I obtain this
```
Traceback (most recent call last):
  File "D:\Proyecto\trabajo\espnet\eje.py", line 12, in <module>
    text2speech = Text2Speech(
  File "D:\Proyecto\trabajo\espnet\espnet2\bin\tts_inference.py", line 70, in __init__
    model, train_args = TTSTask.build_model_from_file(
  File "D:\Proyecto\trabajo\espnet\espnet2\tasks\abs_task.py", line 1769, in build_model_from_file
    model = cls.build_model(args)
  File "D:\Proyecto\trabajo\espnet\espnet2\tasks\tts.py", line 292, in build_model
    normalize = normalize_class(**args.normalize_conf)
  File "D:\Proyecto\trabajo\espnet\espnet2\layers\global_mvn.py", line 41, in __init__
    stats = np.load(stats_file)
  File "D:\Python3_9\lib\site-packages\numpy\lib\npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'exp\\tts_train_tacotron2_raw_phn_tacotron_g2p_en_no_space\\decode_tacotron2_teacher_forcing_train.loss.best\\stats\\train\\feats_stats.npz'
```

**Comment by AMG222** [comment]
Where this should save? or I neet to hear it in the moment.
