### ISSUE TITLE
Error in Chainer RNNLM language model training.

### ISSUE THREAD

**Issue by jnishi** [espnet/espnet#317]
When I run the script of CSJ recipe without `--ngpu` option, error occured.
```
2018-07-27 22:33:54,922 (lm_chainer:145) INFO: chainer version = 4.3.0
2018-07-27 22:33:54,923 (lm_chainer:150) INFO: chainer seed = 1
2018-07-27 22:33:54,923 (lm_chainer:158) INFO: chainer type check is disabled
2018-07-27 22:33:54,923 (lm_chainer:170) WARNING: cudnn is not available
2018-07-27 22:34:00,204 (lm_chainer:181) INFO: #vocab = 5939
2018-07-27 22:34:00,204 (lm_chainer:182) INFO: #words in the training data = 6666818
2018-07-27 22:34:00,204 (lm_chainer:183) INFO: #words in the validation data = 6666818
2018-07-27 22:34:00,204 (lm_chainer:184) INFO: #iterations per epoch = 744
2018-07-27 22:34:00,204 (lm_chainer:185) INFO: #total iterations = 29762
Traceback (most recent call last):
  File "/home/christopher/gitrepos/espnet-1/egs/csj/asr1/../../../src/bin/lm_train.py", line 131, in <module>
    main()
  File "/home/christopher/gitrepos/espnet-1/egs/csj/asr1/../../../src/bin/lm_train.py", line 122, in main
    train(args)
  File "/home/christopher/gitrepos/espnet-1/src/lm/lm_chainer.py", line 242, in train
    x, t = convert.concat_examples(batch, gpu_id)
UnboundLocalError: local variable 'gpu_id' referenced before assignment
# Accounting: time=17 threads=1
# Ended (code 1) at Fri Jul 27 22:34:01 UTC 2018, elapsed time 17 seconds
```

This may be because `gpu_id` is defined [here](https://github.com/espnet/espnet/blob/master/src/lm/lm_chainer.py#L199) , but it does not executed when `gpu_id` equals to 0.

**Comment by kan-bayashi** [comment]
Fixed #379
