### ISSUE TITLE
I need necessarily a Nvidia GPU to use espnet?

### ISSUE THREAD

**Issue by AMG222** [espnet/espnet#3188]
**Describe the issue**
I'm using a VMware to try my program that works in my machine Windows but in virtual machine don't appear the GPU like Nvidia. I want to use it in this SO, exists one way to use it without a Nvidia GPU?

**Basic environments:**
 - OS information: Debian10 x64
 - python version: 3.9
 - espnet version: 9.9.0
 
You can obtain them by the following command
```
>python main.py
Where main.py is a copy of the colab for a local machine
```
**Error logs**
```
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    speed_control_alpha=1.0,
  File "/home/netipc/Documents/espnet/espnet2/bin/tts_inference.py", line 71, in __init__
    train_config, model_file, device
  File "/home/netipc/Documents/espnet/espnet2/tasks/abs_task.py", line 1774, in build_model_from_file
    model.to(device)
  File "/home/netipc/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/home/netipc/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/netipc/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/netipc/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 430, in _apply
    self._buffers[key] = fn(buf)
  File "/home/netipc/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/netipc/.local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 170, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

**Comment by Fhrozen** [comment]
You can find the instructions at: https://espnet.github.io/espnet/espnet2_tutorial.html#instruction-for-run-sh for each flag. But `--ngpu 0` should do the work.

**Comment by AMG222** [comment]
How I don't have the utils/parse_options.sh file
And with
```
python3 main.py --ngpu 0 
```
Print the same error

**Comment by Fhrozen** [comment]
Is that main.py from any recipe of ESPnet, or did you implement it yourself?. In case of self-implementation, remember to set `device="cpu"`, when calling `Text2Speech` from https://github.com/espnet/espnet/blob/master/espnet2/bin/tts_inference.py
https://github.com/espnet/espnet/blob/55160fc20c48686808cbdf208919e668e3b1451a/espnet2/bin/tts_inference.py#L41

**Comment by AMG222** [comment]
Ok, Thank you so much now it's working. I write the device="cpu" in Text2Speech as you say
