### ISSUE TITLE
TTS training with fastspeech2 - error in stage 5 for LJspeech corpus

### ISSUE THREAD

**Issue by Tirthankar-iiitb** [espnet/espnet#3211]
**Describe the bug**
The command:
./run.sh --stage 5 --stop-stage 5
is giving an error of which the last few lines are shown below:
...
File "/root/espnet/espnet2/tts/feats_extract/dio.py", line 116, in forward
    durations = durations * self.reduction_factor
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

**Basic environments:**
 - OS information: [e.g., Ubuntu 18.04]
 - python version: [3.7.10]
 - espnet version: [ espnet 0.9.9]
 - pytorch version [pytorch 1.8.0]
 - NVIDIA Tesla V100-PCIE-32GB
 

**Task information:**
 - Task: [TTS]
 - Recipe: [ljspeech]
 - ESPnet2

**To Reproduce**
1. move to a recipe directory, e.g., `cd egs2ljspeech/tts1`
2. execute  ./run.sh --stage 5 --stop-stage 5

**Error logs**
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/espnet/espnet2/bin/tts_train.py", line 22, in <module>
    main()
  File "/root/espnet/espnet2/bin/tts_train.py", line 18, in main
    TTSTask.main(cmd=cmd)
  File "/root/espnet/espnet2/tasks/abs_task.py", line 976, in main
    cls.main_worker(args)
  File "/root/espnet/espnet2/tasks/abs_task.py", line 1193, in main_worker
    write_collected_feats=args.write_collected_feats,
  File "/root/.virtualenvs/espmarg/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/espnet/espnet2/main_funcs/collect_stats.py", line 72, in collect_stats
    data = model.collect_feats(**batch)
  File "/root/espnet/espnet2/tts/espnet_model.py", line 138, in collect_feats
    durations_lengths=durations_lengths,
  File "/root/.virtualenvs/espmarg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/espnet/espnet2/tts/feats_extract/dio.py", line 116, in forward
    durations = durations * self.reduction_factor
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

**Comment by kan-bayashi** [comment]
You need to specify `--teacher_dumpdir`.
See https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/tts1/README.md#how-to-run

**Comment by Tirthankar-iiitb** [comment]
Thanks. This really helps.On Thu, 13 May 2021 at 6:03 AM, Tomoki Hayashi ***@***.***> wrote:
You need to specify --teacher_dumpdir.
See https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/tts1/README.md#how-to-run

?You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
