### ISSUE TITLE
ERROR: Could not build wheels for fairscale which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by mikaizhu** [espnet/espnet#3218]
**Describe the bug**

i am using these command to build espnet!

```
conda create -n asr python=3.8

conda activate asr

conda install -c anaconda cudatoolkit=10.2

conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=10.2 -c pytorch

sudo apt-get install gcc
sudo apt-get install cmake
sudo apt-get install sox
sudo apt-get install libsndfile1-dev
sudo apt-get install ffmpeg
sudo apt-get install flac

cd espnet/tools

CONDA_TOOLS_DIR=$(dirname ${CONDA_EXE})/..

./setup_anaconda.sh ${CONDA_TOOLS_DIR} asr 3.8.8

make TH_VERSION=1.8.0 CUDA_VERSION=10.2
```

**Basic environments:**
 - OS information: [Linux zwl-desktop 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux]
 - python version: [3.8.0]
 - espnet version: [0.9.9]
 - pytorch version [1.8.0]
 

```
Collecting environment information...
PyTorch version: 1.8.0
Is debug build: No
CUDA used to build PyTorch: 10.2

GCC version: (GCC) 9.3.0
CMake version: version 3.16.3

Python version: 3.8.8
Is CUDA available: Yes
CUDA runtime version: 10.2

Nvidia driver version: 460

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.8.0
[pip3] torch-complex==0.2.1
[pip3] torchaudio==0.8.0a0+a751e1d
[pip3] torchvision==0.9.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              hfd86e86_1    anaconda
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.2.0           h06a4308_296
[conda] mkl-service               2.3.0            py38h27cfd23_1
[conda] mkl_fft                   1.3.0            py38h42c9631_2
[conda] mkl_random                1.2.1            py38ha9443f7_2
[conda] numpy                     1.20.1           py38h93e21f0_0
[conda] numpy-base                1.20.1           py38h7d8b39e_0
[conda] pytorch                   1.8.0           py3.8_cuda10.2_cudnn7.6.5_0    pytorch
[conda] pytorch-wpe               0.0.1                    pypi_0    pypi
[conda] torch-complex             0.2.1                    pypi_0    pypi
[conda] torchaudio                0.8.0                      py38    pytorch
[conda] torchvision               0.9.0                py38_cu102    pytorch
```

**Error logs**

when i run make TH_VERSION=1.8.0 CUDA_VERSION=10.2, it went wrong:

```
ERROR: Command errored out with exit status 1:
   command: /home/zwl/miniconda3/envs/asr/bin/python3 /home/zwl/miniconda3/envs/asr/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmps3ha9x5s
       cwd: /tmp/pip-install-efvv7qtf/fairscale_c4f951244ec9423f979e7ff9cf23ead6
ninja: build stopped: subcommand failed.
  Traceback (most recent call last):
    File "/tmp/pip-build-env-3_5gxw9u/overlay/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1667, in _run_ninja_build
      subprocess.run(
    File "/home/zwl/miniconda3/envs/asr/lib/python3.8/subprocess.py", line 516, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/home/zwl/miniconda3/envs/asr/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
      main()
    File "/home/zwl/miniconda3/envs/asr/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/zwl/miniconda3/envs/asr/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-3_5gxw9u/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 221, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-3_5gxw9u/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-3_5gxw9u/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 258, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-3_5gxw9u/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 59, in <module>
      setuptools.setup(
    File "/tmp/pip-build-env-3_5gxw9u/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/zwl/miniconda3/envs/asr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/zwl/miniconda3/envs/asr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/zwl/miniconda3/envs/asr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-3_5gxw9u/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/zwl/miniconda3/envs/asr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/zwl/miniconda3/envs/asr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/zwl/miniconda3/envs/asr/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/zwl/miniconda3/envs/asr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/zwl/miniconda3/envs/asr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-3_5gxw9u/overlay/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/home/zwl/miniconda3/envs/asr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/tmp/pip-build-env-3_5gxw9u/overlay/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
      build_ext.build_extensions(self)
    File "/home/zwl/miniconda3/envs/asr/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/home/zwl/miniconda3/envs/asr/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-build-env-3_5gxw9u/overlay/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
      _build_ext.build_extension(self, ext)
    File "/home/zwl/miniconda3/envs/asr/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
      objects = self.compiler.compile(sources,
    File "/tmp/pip-build-env-3_5gxw9u/overlay/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 529, in unix_wrap_ninja_compile
      _write_ninja_file_and_compile_objects(
    File "/tmp/pip-build-env-3_5gxw9u/overlay/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1354, in _write_ninja_file_and_compile_objects
      _run_ninja_build(
    File "/tmp/pip-build-env-3_5gxw9u/overlay/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
      raise RuntimeError(message) from e
  RuntimeError: Error compiling objects for extension
  ----------------------------------------
  ERROR: Failed building wheel for fairscale
Failed to build fairscale
ERROR: Could not build wheels for fairscale which use PEP 517 and cannot be installed directly
```

**Comment by marcoyang1998** [comment]
Try `pip install --no-build-isolation fairscale`. It worked for me.

**Comment by mikaizhu** [comment]
> Try `pip install --no-build-isolation fairscale`. It worked for me.

thanks, Do you mean that just install this module directly with pip? 

i run this command and the same issue come out:

```
Failed to build fairscale
ERROR: Could not build wheels for fairscale which use PEP 517 and cannot be installed directly
```

**Comment by mikaizhu** [comment]
i solved this problem by using command below:
- git clone git@github.com:facebookresearch/fairscale.git
- cd fairscale
- pip install -ve .
- cd /espnet/tools
- make TH_VERSION=1.8.0 CUDA_VERSION=10.2
