### ISSUE TITLE
Trying to run multiple TTS inferences at the same time fails

### ISSUE THREAD

**Issue by salomao-andrade** [espnet/espnet#3222]
I have recently started to try to implement text-to-speech synthesis with espnet library in my project and have succesfully generated individual audio files from loaded models. If I load two different models, I have no issue with parallel inferences, but if I attempt to generate two parallel syntheses using the same model, one of the synthesis is cancelled and I get the following error:

-one of the requests to my synthesis endpoint cancels once the other one is sent with the message:
transfer closed with outstanding read data remaining
-one of the files returns with 0kb and the other one is generated successfully

-my python application returns the following error:
 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/conda/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/conda/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/opt/conda/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/opt/conda/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/opt/conda/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/opt/conda/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.8/site-packages/starlette/routing.py", line 44, in app
    await response(scope, receive, send)
  File "/opt/conda/lib/python3.8/site-packages/starlette/responses.py", line 228, in __call__
    await run_until_first_complete(
  File "/opt/conda/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in run_until_first_complete
    [task.result() for task in done]
  File "/opt/conda/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in <listcomp>
    [task.result() for task in done]
  File "/opt/conda/lib/python3.8/site-packages/starlette/responses.py", line 220, in stream_response
    async for chunk in self.body_iterator:
  File "/opt/conda/lib/python3.8/site-packages/starlette/concurrency.py", line 54, in iterate_in_threadpool
    yield await run_in_threadpool(_next, iterator)
  File "/opt/conda/lib/python3.8/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/opt/conda/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.8/site-packages/starlette/concurrency.py", line 46, in _next
    return next(iterator)
  File "/neural-server/app/cpqd_tts_neural_server/endpoints/rest/synthesize.py", line 197, in generate_streaming
    yield from get_engine().text_to_speech(text, voice)
  File "/opt/conda/lib/python3.8/site-packages/cpqd_tts_neural_engine/neural_base.py", line 81, in text_to_speech
    yield sintese(v_config['conf'], v_config['name'], txt, self.device)
  File "/opt/conda/lib/python3.8/site-packages/cpqd_tts_neural_engine/neural_base.py", line 151, in sintese
    wav, c, *_ = voice_conf['text2speech'](text, spembs=spembs)  # Inferencia (Tacotron)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/espnet2/bin/tts_inference.py", line 151, in __call__
    outs, outs_denorm, probs, att_ws = self.model.inference(
  File "/opt/conda/lib/python3.8/site-packages/espnet2/tts/espnet_model.py", line 206, in inference
    outs, probs, att_ws = self.tts.inference(text=text, **kwargs, **decode_config)
  File "/opt/conda/lib/python3.8/site-packages/espnet2/tts/tacotron2.py", line 426, in inference
    outs, probs, att_ws = self.dec.inference(
  File "/opt/conda/lib/python3.8/site-packages/espnet/nets/pytorch_backend/tacotron2/decoder.py", line 564, in inference
    att_c, att_w = self.att(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/espnet/nets/pytorch_backend/rnn/attentions.py", line 378, in forward
    c = torch.sum(self.enc_h * w.view(batch, self.h_length, 1), dim=1)
RuntimeError: shape '[1, 16, 1]' is invalid for input of size 120

should parallel syntheses work with one model, or is this not supported?

**Comment by kan-bayashi** [comment]
Sorry for the late reply.
I do not fully understand your situation.
Do you use the instance of the model to generate the speech in parallel?
Since the model make some cache in the model, it will cause the problem.
Why don't you replicate the instance instead of the use of the same instanance?

**Comment by salomao-andrade** [comment]
We are working with synthesis using CPU, and we had thought to load one instance of a model at initialization and execute inferences in different threads using the same model. From what I understand, the correct way would be to have one instance of the model per thread, even if I have 36 CPU cores available? Would I have to load the same model 36 times?

**Comment by kan-bayashi** [comment]
I think so.

**Comment by salomao-andrade** [comment]
Thank you for your reply, we will have to rethink our approach then
