### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 86.00 MiB 

### ISSUE THREAD

**Issue by mirishkarganesh** [espnet/espnet#3288]
Hi folks,

Following is the log for the issue which I am facing. Can someone please help out in solving this issue?

/home/asr/anaconda3/envs/esp/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:61: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
Exception in main training loop: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/asr/anaconda3/envs/esp/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/asr/anaconda3/envs/esp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/asr/espnet/espnet/nets/pytorch_backend/e2e_asr_transformer.py", line 192, in forward
    loss_att = self.criterion(pred_pad, ys_out_pad)
  File "/home/asr/anaconda3/envs/esp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/asr/espnet/espnet/nets/pytorch_backend/transformer/label_smoothing_loss.py", line 61, in forward
    kl = self.criterion(torch.log_softmax(x, dim=1), true_dist)
  File "/home/asr/anaconda3/envs/esp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/asr/anaconda3/envs/esp/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 365, in forward
    return F.kl_div(input, target, reduction=self.reduction)
  File "/home/asr/anaconda3/envs/esp/lib/python3.8/site-packages/torch/nn/functional.py", line 1968, in kl_div
    reduced = torch.kl_div(input, target, reduction_enum)
RuntimeError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 10.73 GiB total capacity; 9.68 GiB already allocated; 47.56 MiB free; 9.82 GiB reserved in total by PyTorch)

Traceback (most recent call last):
  File "/home/asr/anaconda3/envs/esp/lib/python3.8/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/home/asr/espnet/espnet/asr/pytorch_backend/asr.py", line 240, in update
    self.update_core()
  File "/home/asr/espnet/espnet/asr/pytorch_backend/asr.py", line 204, in update_core
    data_parallel(self.model, x, range(self.ngpu)).mean() / self.accum_grad
  File "/home/asr/anaconda3/envs/esp/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 207, in data_parallel
    outputs = parallel_apply(replicas, inputs, module_kwargs, used_device_ids)
  File "/home/asr/anaconda3/envs/esp/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/asr/anaconda3/envs/esp/lib/python3.8/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/home/asr/espnet/espnet/bin/asr_train.py", line 644, in <module>
    main(sys.argv[1:])
  File "/home/asr/espnet/espnet/bin/asr_train.py", line 630, in main
    train(args)
  File "/home/asr/espnet/espnet/asr/pytorch_backend/asr.py", line 945, in train
    trainer.run()
  File "/home/asr/anaconda3/envs/esp/lib/python3.8/site-packages/chainer/training/trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "/home/asr/anaconda3/envs/esp/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/asr/anaconda3/envs/esp/lib/python3.8/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/home/asr/espnet/espnet/asr/pytorch_backend/asr.py", line 240, in update
    self.update_core()
  File "/home/asr/espnet/espnet/asr/pytorch_backend/asr.py", line 204, in update_core
    data_parallel(self.model, x, range(self.ngpu)).mean() / self.accum_grad
  File "/home/asr/anaconda3/envs/esp/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 207, in data_parallel
    outputs = parallel_apply(replicas, inputs, module_kwargs, used_device_ids)
  File "/home/asr/anaconda3/envs/esp/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/asr/anaconda3/envs/esp/lib/python3.8/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/asr/anaconda3/envs/esp/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/asr/anaconda3/envs/esp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/asr/espnet/espnet/nets/pytorch_backend/e2e_asr_transformer.py", line 192, in forward
    loss_att = self.criterion(pred_pad, ys_out_pad)
  File "/home/asr/anaconda3/envs/esp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/asr/espnet/espnet/nets/pytorch_backend/transformer/label_smoothing_loss.py", line 61, in forward
    kl = self.criterion(torch.log_softmax(x, dim=1), true_dist)
  File "/home/asr/anaconda3/envs/esp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/asr/anaconda3/envs/esp/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 365, in forward
    return F.kl_div(input, target, reduction=self.reduction)
  File "/home/asr/anaconda3/envs/esp/lib/python3.8/site-packages/torch/nn/functional.py", line 1968, in kl_div
    reduced = torch.kl_div(input, target, reduction_enum)
RuntimeError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 10.73 GiB total capacity; 9.68 GiB already allocated; 47.56 MiB free; 9.82 GiB reserved in total by PyTorch)

# Accounting: time=4215 threads=1
# Ended (code 1) at Sun Jun 13 22:04:07 IST 2021, elapsed time 4215 seconds

**Comment by sw005320** [comment]
It seems that this is due to the shortage of GPU memory. 
Please reduce the batchsize or use smaller models to make it fit with your GPU.

**Comment by arunbaby0** [comment]
@sw005320 I am also facing the same issue. For me, this is happening only while decoding. The ASR model trained perfectly well on the 8 x V100(16GB) GPUs.(using SWBD config) 
While decoding 2 of the 8 decode (Stage 12) streams are failing. Is there any optimisation that can be done at decode time for this?

**Comment by sw005320** [comment]
Can you reduce the beam size then?
Also, we could not decode very long sentences (say longer than 20 seconds).
Please use VAD or other segmentation tools to chop the audio.

**Comment by arunbaby0** [comment]
Thanks for the response. 

I tried with reduced beam size. It worked for some files. But some longer files, it failed. 

But it works fine in the CPU decode mode perfectly fine.

**Comment by sw005320** [comment]
Year, this is the current limitation of our vanilla beam search with long audios due to the memory consumptions... (especially it is critical for transformer/conformer)
We have internal code to deal with some VADs internally, and we may release it in some timing upon requests.
But the most efficient (economic) way is to use external VAD or whatever.
