### ISSUE TITLE
Error in ASR task in stage 9

### ISSUE THREAD

**Issue by lin-nerd** [espnet/espnet#3314]
I use ESPnet2 in ASR task on my dataset, I got a Internal process exited INFO in stage 9.

- python version: 3.8.5 
- espnet version: espnet 0.9.9
- pytorch version: pytorch 1.4.0

log is:

Traceback (most recent call last):
  File "/home/user/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/home/user/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/home/user/espnet/espnet2/tasks/abs_task.py", line 976, in main
    cls.main_worker(args)
  File "/home/user/espnet/espnet2/tasks/abs_task.py", line 1166, in main_worker
    collect_stats(
  File "/home/user/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/user/espnet/espnet2/main_funcs/collect_stats.py", line 55, in collect_stats
    for iiter, (keys, batch) in enumerate(itr, 1):
  File "/home/user/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/user/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/user/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/user/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/user/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/user/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 35, in fetch
    return self.collate_fn(data)
  File "/home/user/espnet/espnet2/train/collate_fn.py", line 38, in __call__
    return common_collate_fn(
  File "/home/user/espnet/espnet2/train/collate_fn.py", line 94, in common_collate_fn
    tensor = pad_list(tensor_list, pad_value)
  File "/home/user/espnet/espnet/nets/pytorch_backend/nets_utils.py", line 59, in pad_list
    pad[i, : xs[i].size(0)] = xs[i]
RuntimeError: expand(torch.FloatTensor{[102173, 2]}, size=[102173]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)

[user] 2021-06-22 16:40:52,213 (internal:139) INFO: Internal process exited
# Accounting: time=4 threads=1

**Comment by lin-nerd** [comment]
It's duo to dual channel audio.
