### ISSUE TITLE
Is it possible for espnet training from the break point instead of training from initial?

### ISSUE THREAD

**Issue by Subohao** [espnet/espnet#3327]
Hi, thanks for developing such cool toolkits!
As the title
While training ASR task, I met some problem (I think it's at the final several batches or iterations).
The problem is due to the batch normalization in the convolution,
It always shows that
"expected more than 1 value per channel when training, got input size [1, 4, 1]",
and then the training will shut down.
I guess the problem might be the last batch would be only one data left?
I want to ask two questions below:
1. Is there a drop last option in the config or option that we could set?
2. Is it possible for espnet training ASR model from breaking point instead of training from initial iteration?

Thank you for helping me!

**Comment by sw005320** [comment]
I have never had such issues.
Is it in espnet1 or espnet2?
Could you put a detailed error message?
Also, can you change the batch size?

> 1. Is there a drop last option in the config or option that we could set?

No, we don't have such an option.

> 2. Is it possible for espnet training ASR model from breaking point instead of training from initial iteration?

Yes, we have an option to output a snapshot per N iterations instead of per epoch.
espnet1
```
  --save-interval-iters SAVE_INTERVAL_ITERS
                        Save snapshot interval iterations (default: 0)
```
espnet2
```
  --num_iters_per_epoch NUM_ITERS_PER_EPOCH
                        Restrict the number of iterations for training per epoch (default: None)
```

**Comment by Subohao** [comment]
Hi, I'm using espnet1 now, and the error mssg is below:
```
Exception in main training loop: Caught ValueError in replica 2 on device 2.
Original Traceback (most recent call last):
  File "/opt/espnet/tools/anaconda/envs/espnet/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/opt/espnet/tools/anaconda/envs/espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/espnet/espnet/nets/pytorch_backend/e2e_asr_transformer.py", line 179, in forward
    hs_pad, hs_mask = self.encoder(xs_pad, src_mask)
  File "/opt/espnet/tools/anaconda/envs/espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/espnet/espnet/nets/pytorch_backend/conformer/encoder.py", line 239, in forward
    xs, masks = self.encoders(xs, masks)
  File "/opt/espnet/tools/anaconda/envs/espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/espnet/espnet/nets/pytorch_backend/transformer/repeat.py", line 18, in forward
    args = m(*args)
  File "/opt/espnet/tools/anaconda/envs/espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/espnet/espnet/nets/pytorch_backend/conformer/encoder_layer.py", line 136, in forward
    x = residual + self.dropout(self.conv_module(x))
  File "/opt/espnet/tools/anaconda/envs/espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/espnet/espnet/nets/pytorch_backend/conformer/convolution.py", line 75, in forward
    x = self.activation(self.norm(x))
  File "/opt/espnet/tools/anaconda/envs/espnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/espnet/tools/anaconda/envs/espnet/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 81, in forward
    exponential_average_factor, self.eps)
  File "/opt/espnet/tools/anaconda/envs/espnet/lib/python3.6/site-packages/torch/nn/functional.py", line 1666, in batch_norm
    raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 4, 1])
```
I have tried to change to different batch size, but the result seems to be the same.

In my train.yaml the related settings are:
```
accum-grad: 4
adim: 4
aheads: 2
backend: pytorch
batch-size: 4
maxlen-in: 512
maxlen-out: 150
dlayers: 2
dropout-rate: 0.1
dunits: 4
elayers: 2
epochs: 1
eunits: 4
```
Thanks for replying the second question, I have tried to save that.
Appreciate that a lot!

**Comment by Subohao** [comment]
According to some similar [bugs](https://github.com/espnet/espnet/issues/2169),
I thought it would be the problem in the data parallel, and then I tried to switch the pytorch version to 1.4.0,
but the error still there.
Also, according to this [information](https://discuss.pytorch.org/t/error-in-torch-nn-dataparallel/64164), I think this would be more close to the question at the first time which is about the last batch.
Since I use 4 GPUs to train the model, I set the accum-grad to 4. 
I could not increase the batch size due to the memory issue, if I set a lower accum-grad with larger batch size, the code would automatically increase the accum-grad to 4.
Is there any solution to this kind of bug?
