### ISSUE TITLE
I could not see 'model.json' of tacotron2 in arctic/vc1.

### ISSUE THREAD

**Issue by Sumi-Sumi** [espnet/espnet#3331]
**Describe the bug**
There is not a 'model.json' of tacotron2 of arctic/vc1.
I downloaded using `pretrained_model_download.sh`.
I could see `model.json` of vtn_tts_pt in tar.gz but I could not see `model.json` of taco2_tts_pt in tar.gz.
I had same result manually install from url of google drive written in `pretrained_model_download.sh`
Do you forget it ? or I should use any `model.json` in arctic/tts1?

**To Reproduce**
1. move to a recipe directory, e.g., `cd egs/arctic/vc1`
2. execute `run.sh` with specific arguments, e.g., `run.sh --stop_stage 4 --norm_name judy --pretrained_model m_ailabs.judy.taco2_tts_pt ...(and any pram)...`
3. specify the error log, e.g., `exp/clb_slt_pytorch_taco2_tts_pt/train.log`

**Error logs**
2021-07-02 10:10:12,376 (asr_init:253) WARNING: model(s) found for pre-initialization
Traceback (most recent call last):
  File "/workspace/espnet/egs/arctic/vc1/../../../espnet/bin/vc_train.py", line 368, in <module>
    main(sys.argv[1:])
  File "/workspace/espnet/egs/arctic/vc1/../../../espnet/bin/vc_train.py", line 362, in main
    train(args)
  File "/workspace/espnet/espnet/vc/pytorch_backend/vc.py", line 308, in train
    model = load_trained_modules(idim, odim, args, TTSInterface)
  File "/workspace/espnet/espnet/asr/pytorch_backend/asr_init.py", line 260, in load_trained_modules
    model_state_dict = get_trained_model_state_dict(model_path)
  File "/workspace/espnet/espnet/asr/pytorch_backend/asr_init.py", line 201, in get_trained_model_state_dict
    idim, odim, args = get_model_conf(model_path, conf_path)
  File "/workspace/espnet/espnet/asr/asr_utils.py", line 693, in get_model_conf
    with open(model_conf, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'downloads/m_ailabs.judy.taco2_tts_pt/m_ailabs.judy.taco2_tts_pt/model.json'

**Comment by unilight** [comment]
Hi @Sumi-Sumi , thank you for reporting it! You are right, I forgot to put model.json... I have uploaded a fixed version. Could you try to redownload it and try again? Thanks!

**Comment by Sumi-Sumi** [comment]
Thank you your work!
I try it.
I close this issue.
