### ISSUE TITLE
Commonvoice fails due to issue in Pillow 8.3.0

### ISSUE THREAD

**Issue by blokje** [espnet/espnet#3337]
**Describe the bug**
Pillow 8.3.0 introduces and issue which affect (at least) the commonvoice egs

During some investigation I found the following github issue with the same problem and suggested solution. It seems that Pillow 8.3.0 is triggering this issue.

- https://github.com/tensorflow/tensorflow/issues/46840
- https://github.com/python-pillow/Pillow/issues/5571

Installing any other version than 8.3.0 solved the problem

`pip install "pillow!=8.3.0"`

**Basic environments:**
 - OS information: `Linux gpu03 5.4.0-1051-azure #53~18.04.1-Ubuntu SMP Fri Jun 18 22:32:58 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- python version: `3.6.9 (default, Jan 26 2021, 15:33:00)  [GCC 8.4.0]`
- espnet version: `espnet 0.10.0`
- pytorch version: `pytorch 1.8.0`

**Environments from `torch.utils.collect_env`:**
Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 9.1.85
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 470.42.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.8.0
[pip3] torch-complex==0.2.1
[pip3] torch-optimizer==0.1.0
[pip3] torchaudio==0.8.0
[conda] Could not collect

**Task information:**
 - Task: ASR
 - Recipe: Commonvoice
 - ESPnet1

**To Reproduce**
1. move to a recipe directory, `cd egs/commonvoice/asr1`
2. execute `run.sh --lang fy-NL`. The errors is introduced in step 4.
3. specify the error log, e.g., `exp/train_fy_NL_pytorch_train_specaug/train.log`

**Error logs**
```
2021-07-06 07:03:34,018 (asr_train:563) WARNING: Skip DEBUG/INFO messages
2021-07-06 07:03:34,434 (ctc:37) WARNING: CTC was set to builtin due to PyTorch version.
2021-07-06 07:03:34,435 (argument:79) WARNING: Using legacy_rel_pos and it will be deprecated in the future.
2021-07-06 07:03:34,435 (argument:84) WARNING: Using legacy_rel_selfattn and it will be deprecated in the future.
2021-07-06 07:03:37,098 (asr:503) WARNING: num. model params: 43,133,522 (num. trained: 43,133,522 (100.0%))
2021-07-06 07:03:39,043 (io_utils:59) WARNING: [Experimental feature] Some preprocessing will be done for the mini-batch creation using Transformation(
    0: TimeWarp(max_time_warp=5, inplace=True, mode=PIL)
    1: FreqMask(F=30, n_mask=2, replace_with_zero=False, inplace=True)
    2: TimeMask(T=40, n_mask=2, replace_with_zero=False, inplace=True))
2021-07-06 07:03:39,052 (io_utils:59) WARNING: [Experimental feature] Some preprocessing will be done for the mini-batch creation using Transformation(
    0: TimeWarp(max_time_warp=5, inplace=True, mode=PIL)
    1: FreqMask(F=30, n_mask=2, replace_with_zero=False, inplace=True)
    2: TimeMask(T=40, n_mask=2, replace_with_zero=False, inplace=True))
2021-07-06 07:03:39,086 (transformation:138) CRITICAL: Catch a exception from 0th func: TimeWarp(max_time_warp=5, inplace=True, mode=PIL)
Exception in main training loop: __array__() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/opt/espnet/tools/venv/lib/python3.6/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/opt/espnet/espnet/asr/pytorch_backend/asr.py", line 235, in update
    self.update_core()
  File "/opt/espnet/espnet/asr/pytorch_backend/asr.py", line 183, in update_core
    batch = train_iter.next()
  File "/opt/espnet/espnet/utils/dataset.py", line 58, in next
    ret = next(self.iter)
  File "/opt/espnet/tools/venv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/opt/espnet/tools/venv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/espnet/tools/venv/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/espnet/tools/venv/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/espnet/espnet/utils/dataset.py", line 33, in __getitem__
    return self.transform(self.data[idx])
  File "/opt/espnet/espnet/asr/pytorch_backend/asr.py", line 627, in <lambda>
    dataset=TransformDataset(train, lambda data: converter([load_tr(data)])),
  File "/opt/espnet/espnet/utils/io_utils.py", line 188, in __call__
    return_batch[x_name], uttid_list, **self.preprocess_args
  File "/opt/espnet/espnet/transform/transformation.py", line 135, in __call__
    xs = [func(x, **_kwargs) for x in xs]
  File "/opt/espnet/espnet/transform/transformation.py", line 135, in <listcomp>
    xs = [func(x, **_kwargs) for x in xs]
  File "/opt/espnet/espnet/transform/spec_augment.py", line 61, in __call__
    return super().__call__(x)
  File "/opt/espnet/espnet/transform/functional.py", line 37, in __call__
    return self.func(x, **self.kwargs)
  File "/opt/espnet/espnet/transform/spec_augment.py", line 35, in time_warp
    x[:warped] = left
Will finalize trainer extensions and updater before reraising the exception.
```

**Comment by sw005320** [comment]
Thanks, @blokje!
I just made a PR.

**Comment by sw005320** [comment]
It seems that pillow 8.3.1 (fixed version) becomes the default installation version.
So, I think this problem will not happen. I'll close this issue for now.
But thanks @blokje for your report.
