### ISSUE TITLE
Unexpected key(s) error on transfer learning from pretrained JSUT model

### ISSUE THREAD

**Issue by zzxiang** [espnet/espnet#3341]
I'm trying to do transfer learning from the pretrained 'kan-bayashi/jsut_conformer_fastspeech2_accent_with_pause' model downloaded from the following link:

https://zenodo.org/record/4436448/files/tts_train_conformer_fastspeech2_tacotron2_teacher_raw_phn_jaconv_pyopenjtalk_accent_with_pause_train.loss.ave.zip?download=1

Following the [README in egs2/TEMPLATE folder](https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/README.md), I created my own `run.sh` and `local/data.sh`. The `run.sh` was basically copied from [`egs2/jsut/tts1/run.sh`](https://github.com/espnet/espnet/blob/master/egs2/jsut/tts1/run.sh) with some modifications:

```
#!/usr/bin/env bash
# Set bash to 'debug' mode, it will exit on :
# -e 'error', -u 'undefined variable', -o ... 'error in pipeline', -x 'print commands',
set -e
set -u
set -o pipefail

fs=24000
n_fft=2048
n_shift=300
win_length=1200

opts="--audio_format wav "

train_set=train
valid_set=validation
test_sets="validation test"

train_config=conf/train_conformer_fastspeech2.yaml
inference_config=conf/decode_fastspeech.yaml

train_args="--init_param /home/sshu/tts_train_conformer_fastspeech2_tacotron2_teacher_raw_phn_jaconv_pyopenjtalk_accent_with_pause_train.loss.ave/exp/tts_train_conformer_fastspeech2_tacotron2_teacher_raw_phn_jaconv_pyopenjtalk_accent_with_pause/train.loss.ave_5best.pth"

g2p=pyopenjtalk_accent_with_pause

./tts.sh \
    --lang jp \
    --feats_type fbank \
    --fs "${fs}" \
    --n_fft "${n_fft}" \
    --n_shift "${n_shift}" \
    --win_length "${win_length}" \
    --token_type phn \
    --cleaner jaconv \
    --g2p "${g2p}" \
    --train_config "${train_config}" \
    --train_args "${train_args}" \
    --inference_config "${inference_config}" \
    --train_set "${train_set}" \
    --valid_set "${valid_set}" \
    --test_sets "${test_sets}" \
    --srctexts "/home/sshu/corpus/jsut/filelists/text.espnet" \
    ${opts} "$@"
```

However, running `run.sh` failed at stage 5 with the following RuntimeError:

```
[spsy-ml] 2021-07-07 18:59:09,236 (abs_task:1153) INFO: Loading pretrained params from /home/sshu/tts_train_conformer_fastspeech2_tacotron2_teacher_raw_phn_jaconv_pyopenjtalk_accent_with_pause_train.loss.ave/exp/tts_train_conformer_fastspeech2_tacotron2_teacher_raw_phn_jaconv_pyopenjtalk_accent_with_pause/train.loss.ave_5best.pth
Traceback (most recent call last):
  File "/home/sshu/anaconda3/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/sshu/anaconda3/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sshu/espnet/espnet2/bin/tts_train.py", line 22, in <module>
    main()
  File "/home/sshu/espnet/espnet2/bin/tts_train.py", line 18, in main
    TTSTask.main(cmd=cmd)
  File "/home/sshu/espnet/espnet2/tasks/abs_task.py", line 994, in main
    cls.main_worker(args)
  File "/home/sshu/espnet/espnet2/tasks/abs_task.py", line 1154, in main_worker
    load_pretrained_model(
  File "/home/sshu/espnet/espnet2/torch_utils/load_pretrained_model.py", line 111, in load_pretrained_model
    obj.load_state_dict(dst_state)
  File "/home/sshu/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1406, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ESPnetTTSModel:
	Unexpected key(s) in state_dict: "feats_extract.logmel.melmat", "normalize.mean", "normalize.std", "pitch_normalize.mean", "pitch_normalize.std", "energy_normalize.mean", "energy_normalize.std". 
```

It seems that the keys in the pretrained model don't match what are expected by the source code of ESPnet.

Investigating the `meta.yaml` file of the pretrained model, I found that the model was generated using ESPnet v0.8.0:

```
espnet: 0.8.0
files:
  model_file: exp/tts_train_conformer_fastspeech2_tacotron2_teacher_raw_phn_jaconv_pyopenjtalk_accent_with_pause/train.loss.ave_5best.pth
python: "3.7.3 (default, Mar 27 2019, 22:11:17) \n[GCC 7.3.0]"
timestamp: 1610543773.910821
torch: 1.5.1
yaml_files:
  train_config: exp/tts_train_conformer_fastspeech2_tacotron2_teacher_raw_phn_jaconv_pyopenjtalk_accent_with_pause/config.yaml
```

But the version I used for transfer learning was the latest version of master branch. Maybe that's reason, so I'm now trying to perform transfer learning with ESPnet v0.8.0. However, the installation of v0.8.0 has not succeeded yet.

Is there any other workaround suggested? Please help.

Thanks in advance.

**Comment by kan-bayashi** [comment]
You cannot specify the `--init_param` for stage 5.
https://github.com/espnet/espnet/tree/master/egs2/jvs/tts1
To train the fastspeech2, you need to prepare the `durations` at first.
Please try the fine-tuneing of tacotron2 or transformer at first.

**Comment by zzxiang** [comment]
Thank you @kan-bayashi ! I'll try transfer learning of tacotron2 first.

**Comment by zzxiang** [comment]
I got good result by

1. fine-tuning with `kan-bayashi/jsut_tts_train_tacotron2_raw_phn_jaconv_pyopenjtalk_accent_with_pause`
2. and then with `kan-bayashi/jsut_tts_train_conformer_fastspeech2_tacotron2_teacher_raw_phn_jaconv_pyopenjtalk_accent_with_pause`

Thank you very much!!
