### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by PabloPeso** [espnet/espnet#3365]
Hi,

I tried to get the Docker running locally following the instructions here https://espnet.github.io/espnet/docker.html but I get the following error:

```
Traceback (most recent call last):
  File "/miniconda/envs/espnet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/miniconda/envs/espnet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/espnet/espnet2/bin/asr_train.py", line 2, in <module>
    from espnet2.tasks.asr import ASRTask
  File "/espnet/espnet2/tasks/asr.py", line 51, in <module>
    from espnet2.tasks.abs_task import AbsTask
  File "/espnet/espnet2/tasks/abs_task.py", line 30, in <module>
    import wandb
ModuleNotFoundError: No module named 'wandb'
```

The steps to reproduce this issue is by running this from the espnet/docker folder 
```
./run.sh  --is-egs2 --docker-egs librispeech/asr1 --docker-folders /Datasets/LibriSpeech --ngpu 4
```
and the last commit on the local repo is e60d1786879839234cf3db8aad1f71af6f93333d

Is this a known issue? Could you help solving the issue?

Thanks for your help.

**Comment by Fhrozen** [comment]
Yes, the problem is with the update of the docker containers. 
I will fix them an upload to fix this issue.

**Comment by PabloPeso** [comment]
Thanks @Fhrozen for looking into this. Do you know approximately when you would be able to upload a fix?

**Comment by Fhrozen** [comment]
Currently working on this, I am having issues with the size of the container, so no current ETA.
If you are in a hurry, you could try building the containers `local` or `fully_local`

**Comment by PabloPeso** [comment]
Thanks @Fhrozen for your advise. I followed your suggestion and I built the container using `fully_local` following the instructions in  https://espnet.github.io/espnet/docker.html. However I noticed two things:

1. The size of the image is very large 543GB, is this expected?
```
REPOSITORY           TAG                                           IMAGE ID       CREATED         SIZE
espnet/espnet        gpu-cuda10.1-cudnn7-u18-local-user-xxx   bd956174d394   2 days ago      543GB
```
2. I seem to encounter an error when moving to Stage 9. Any suggestion on how to solve this issue?
```
2021-07-30T15:20:35 (asr.sh:864:main) Stage 9: ASR collect stats: train_set=dump/raw/train_960_sp, valid_set=dump/raw/dev
2021-07-30T15:20:36 (asr.sh:914:main) Generate 'exp/asr_stats_raw_en_bpe5000_sp/run.sh'. You can resume the process from stage 9 using this script
2021-07-30T15:20:36 (asr.sh:918:main) ASR collect-stats started... log: 'exp/asr_stats_raw_en_bpe5000_sp/logdir/stats.*.log'
run.pl: 32 / 32 failed, log is in exp/asr_stats_raw_en_bpe5000_sp/logdir/stats.*.log
# python3 -m espnet2.bin.asr_train --collect_stats true --use_preprocessor true --bpemodel data/en_token_list/bpe_unigram5000/bpe.model --token_type bpe --token_list data/en_token_list/bpe_unigram5000/tokens.txt --non_linguistic_symbols none --cleaner none --g2p none --train_data_path_and_name_and_type dump/raw/train_960_sp/wav.scp,speech,sound --train_data_path_and_name_and_type dump/raw/train_960_sp/text,text,text --valid_data_path_and_name_and_type dump/raw/dev/wav.scp,speech,sound --valid_data_path_and_name_and_type dump/raw/dev/text,text,text --train_shape_file exp/asr_stats_raw_en_bpe5000_sp/logdir/train.1.scp --valid_shape_file exp/asr_stats_raw_en_bpe5000_sp/logdir/valid.1.scp --output_dir exp/asr_stats_raw_en_bpe5000_sp/logdir/stats.1 --config conf/tuning/train_asr_conformer7_n_fft512_hop_length256.yaml --frontend_conf fs=16k 
# Started at Fri Jul 30 15:20:36 2021
#
Traceback (most recent call last):
  File "/miniconda/envs/espnet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/miniconda/envs/espnet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/espnet/espnet2/bin/asr_train.py", line 2, in <module>
    from espnet2.tasks.asr import ASRTask
  File "/espnet/espnet2/tasks/asr.py", line 40, in <module>
    from espnet2.asr.frontend.default import DefaultFrontend
  File "/espnet/espnet2/asr/frontend/default.py", line 14, in <module>
    from espnet2.layers.log_mel import LogMel
  File "/espnet/espnet2/layers/log_mel.py", line 1, in <module>
    import librosa
  File "/miniconda/envs/espnet/lib/python3.7/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/miniconda/envs/espnet/lib/python3.7/site-packages/librosa/core/__init__.py", line 6, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "/miniconda/envs/espnet/lib/python3.7/site-packages/librosa/core/audio.py", line 8, in <module>
    import soundfile as sf
  File "/miniconda/envs/espnet/lib/python3.7/site-packages/soundfile.py", line 17, in <module>
    from _soundfile import ffi as _ffi
  File "/miniconda/envs/espnet/lib/python3.7/site-packages/_soundfile.py", line 2, in <module>
    import _cffi_backend
ImportError: libffi.so.7: cannot open shared object file: No such file or directory
# Accounting: time=2 threads=1
# Ended (code 1) at Fri Jul 30 15:20:38 2021, elapsed time 2 seconds
run.sh done.
```

Thanks for your help.

**Comment by Fhrozen** [comment]
Thank for the details.
1. 534G?? No, It is extremely large. Something when too wrong. Try to check for the additional containers. In total it should not have any bigger than 15G. 
2. You may need to install libffi-dev, or check that you are using `sox` installed using conda.
