### ISSUE TITLE
How to use the module "s3prl_frontend"?

### ISSUE THREAD

**Issue by teinhonglo** [espnet/espnet#3419]
**Describe the bug**
I am trying to run the **aishell asr1 recipe** in **espnet2** with the following **s3prl_frontend** config file copied from [the config of wsj recipe](https://github.com/espnet/espnet/blob/master/egs2/wsj/asr1/conf/tuning/train_asr_conformer_s3prlfrontend_hubert.yaml): 

I have already run `installers/install_s3prl.sh` and `installers/install_fairseq.sh`. 
But I get the errors show in Error logs section.
Any document, readme or suggestion can help me to reproduce it?

Many thanks,
Tien-Hong

**Basic environments:**
 - OS information: `Linux 4.15.0-142-generic #146~16.04.1-Ubuntu SMP Tue Apr 13 09:27:15 UTC 2021 x86_64`
 - python version: `3.8.11 (default, Aug  3 2021, 15:09:35)  [GCC 7.5.0]`
 - espnet version: `espnet 0.10.0`
 - Git hash `4f94f5bdc67b722c7fb04601b3b705d972bbce64`
   - Commit date Fri Aug 6 13:48:44 2021 -0400
 - pytorch version: `pytorch 1.8.1`

**Environments from `torch.utils.collect_env`:**
```
Collecting environment information...
PyTorch version: 1.8.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.6 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Clang version: Could not collect
CMake version: version 3.5.1

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 440.82
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.0
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.0
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.6.0.21
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.7.1.3
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] pytorch-lightning==1.4.1
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.8.1
[pip3] torch-complex==0.2.1
[pip3] torch-optimizer==0.1.0
[pip3] torch-stoi==0.1.2
[pip3] torchaudio==0.8.1
[pip3] torchmetrics==0.4.1
[pip3] torchvision==0.9.1
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               10.2.89              h8f6ccaa_8    conda-forge
[conda] mkl                       2021.3.0           h06a4308_520    defaults
[conda] mkl-service               2.4.0            py38h497a2fe_0    conda-forge
[conda] mkl_fft                   1.3.0            py38h42c9631_2    defaults
[conda] mkl_random                1.2.2            py38h1abd341_0    conda-forge
[conda] numpy                     1.20.3           py38hf144106_0    defaults
[conda] numpy-base                1.20.3           py38h74d4b33_0    defaults
[conda] pytorch                   1.8.1           py3.8_cuda10.2_cudnn7.6.5_0    pytorch
[conda] pytorch-lightning         1.4.1                    pypi_0    pypi
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.1                    pypi_0    pypi
[conda] torch-complex             0.2.1                    pypi_0    pypi
[conda] torch-optimizer           0.1.0                    pypi_0    pypi
[conda] torch-stoi                0.1.2                    pypi_0    pypi
[conda] torchaudio                0.8.1                    pypi_0    pypi
[conda] torchmetrics              0.4.1                    pypi_0    pypi
[conda] torchvision               0.9.1                    pypi_0    pypi
```

**Task information:**
 - Task: ASR
 - Recipe: aishell and wsj
 - ESPnet2

**To Reproduce**
1. `cp egs2/wsj/asr1/conf/tuning/train_asr_conformer_s3prlfrontend_hubert.yaml to egs2/aishell/asr1/conf/tuning/`
1. `cd egs2/aishell/asr1`
2. change original parameter of the asr_config to new one (conf/tuning/train_asr_conformer_s3prlfrontend_hubert.yaml)
3. `run.sh --stage 10`
4. specify the error log, e.g., `exp/asr_stats_raw_zh_char_sp/logdir/stats.*.log`

**Error logs**
```
# Running on kl03
# Started at Wed Aug 11 09:04:14 CST 2021
# python3 -m espnet2.bin.asr_train --collect_stats true --use_preprocessor true --bpemodel none --token_type char --token_list data/zh_token_list/char/tokens.txt --non_linguistic_symbols none --cleaner none --g2p none --train_data_path_and_name_and_type dump/raw/train_sp/wav.scp,speech,sound --train_data_path_and_name_and_type dump/raw/train_sp/text,text,text --valid_data_path_and_name_and_type dump/raw/dev/wav.scp,speech,sound --valid_data_path_and_name_and_type dump/raw/dev/text,text,text --train_shape_file exp/asr_stats_raw_zh_char_sp/logdir/train.1.scp --valid_shape_file exp/asr_stats_raw_zh_char_sp/logdir/valid.1.scp --output_dir exp/asr_stats_raw_zh_char_sp/logdir/stats.1 --config conf/tuning/train_asr_conformer_s3prlfrontend_wav2vec2.yaml --frontend_conf fs=16k --model_conf extract_feats_in_collect_stats=false 
/share/nas167/teinhonglo/espnets/espnet-s3prl/tools/anaconda/envs/espnet/bin/python3 /share/nas167/teinhonglo/espnets/espnet-s3prl/espnet2/bin/asr_train.py --collect_stats true --use_preprocessor true --bpemodel none --token_type char --token_list data/zh_token_list/char/tokens.txt --non_linguistic_symbols none --cleaner none --g2p none --train_data_path_and_name_and_type dump/raw/train_sp/wav.scp,speech,sound --train_data_path_and_name_and_type dump/raw/train_sp/text,text,text --valid_data_path_and_name_and_type dump/raw/dev/wav.scp,speech,sound --valid_data_path_and_name_and_type dump/raw/dev/text,text,text --train_shape_file exp/asr_stats_raw_zh_char_sp/logdir/train.1.scp --valid_shape_file exp/asr_stats_raw_zh_char_sp/logdir/valid.1.scp --output_dir exp/asr_stats_raw_zh_char_sp/logdir/stats.1 --config conf/tuning/train_asr_conformer_s3prlfrontend_wav2vec2.yaml --frontend_conf fs=16k --model_conf extract_feats_in_collect_stats=false
[kl03] 2021-08-11 09:04:30,857 (asr:379) INFO: Vocabulary size: 5069
################################################################################
### WARNING, path does not exist: KALDI_ROOT=/mnt/matylda5/iveselyk/Tools/kaldi-trunk
###          (please add 'export KALDI_ROOT=<your_path>' in your $HOME/.profile)
###          (or run as: KALDI_ROOT=<your_path> python <your_script>.py)
################################################################################

[kl03] 2021-08-11 09:04:36,951 (filelock:274) INFO: Lock 22840157784960 acquired on ./hub/s3prl_cache/1c76d6e88090f01736036b28dc995fef583f47f42662d55286332557f957609f.lock
[kl03] 2021-08-11 09:04:36,959 (filelock:318) INFO: Lock 22840157784960 released on ./hub/s3prl_cache/1c76d6e88090f01736036b28dc995fef583f47f42662d55286332557f957609f.lock
Traceback (most recent call last):
  File "/share/nas167/teinhonglo/espnets/espnet-s3prl/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/share/nas167/teinhonglo/espnets/espnet-s3prl/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/share/nas167/teinhonglo/espnets/espnet-s3prl/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/share/nas167/teinhonglo/espnets/espnet-s3prl/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/share/nas167/teinhonglo/espnets/espnet-s3prl/espnet2/tasks/abs_task.py", line 994, in main
    cls.main_worker(args)
  File "/share/nas167/teinhonglo/espnets/espnet-s3prl/espnet2/tasks/abs_task.py", line 1096, in main_worker
    model = cls.build_model(args=args)
  File "/share/nas167/teinhonglo/espnets/espnet-s3prl/espnet2/tasks/asr.py", line 385, in build_model
    frontend = frontend_class(**args.frontend_conf)
  File "/share/nas167/teinhonglo/espnets/espnet-s3prl/espnet2/asr/frontend/s3prl.py", line 49, in __init__
    self.upstream, self.featurizer = self._get_upstream(frontend_conf)
  File "/share/nas167/teinhonglo/espnets/espnet-s3prl/espnet2/asr/frontend/s3prl.py", line 84, in _get_upstream
    from upstream.interfaces import Featurizer
ModuleNotFoundError: No module named 'upstream'
[hubconf] can not import .upstream.pase.hubconf: No module named 'pase'... Pass.
[Downstream] can not import .sv_voxceleb1.expert: No module named 'utility'... Pass.
[hubconf] can not import .downstream.timit_phone.hubconf: No module named 'upstream'... Pass.
Using cache found in ./hub/s3prl_cache/1c76d6e88090f01736036b28dc995fef583f47f42662d55286332557f957609f
for https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_vox_new.pt
# Accounting: time=104 threads=1
# Finished at Wed Aug 11 09:05:58 CST 2021 with status 1
```

**Comment by sw005320** [comment]
@simpleoier, can you answer it for me?
Are there some internal changes in s3prl?

**Comment by sw005320** [comment]
Thanks, @simpleoier!
Can you also add a test to detect the interface change in s3prl?
Then, we can easily fix it.

**Comment by simpleoier** [comment]
@sw005320  sure, I'll make it.
