### ISSUE TITLE
LibriSpeech/ASR CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by D-X-Y** [espnet/espnet#3496]
**Describe the bug**

**Basic environments:**
 - OS information: Linux 4.14.243-185.433.amzn2.x86_64 #1 SMP Mon Aug 9 05:55:52 UTC 2021 x86_64
 - python version: `3.7.10 (default, Jun  3 2021, 00:02:01)  [GCC 7.3.1 20180712 (Red Hat 7.3.1-13)]`
- espnet version: `espnet 0.9.10`
- pytorch version: `pytorch 1.7.1+cu110`
 

**Environments from `torch.utils.collect_env`:**
```
PyTorch version: 1.7.1+cu110
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Amazon Linux 2 (x86_64)
GCC version: (GCC) 7.3.1 20180712 (Red Hat 7.3.1-13)
Clang version: Could not collect
CMake version: version 3.20.4

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 450.119.03
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.7.1+cu110
[pip3] torch-complex==0.2.1
[pip3] torch-optimizer==0.1.0
[pip3] torchaudio==0.7.2
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py37he8ac12f_0
[conda] mkl_fft                   1.2.1            py37h54f3939_0
[conda] mkl_random                1.1.1            py37h0573a6f_0
[conda] numpy                     1.19.2           py37h54aff64_0
[conda] numpy-base                1.19.2           py37hfa32c7d_0
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
```

**Task information:**
 - Task: ASR
 - Recipe: librispeech
 - ESPnet1 or ESPnet2

**To Reproduce**
1. `cd egs2/librispeech/asr1`
2. modify the encoder part of `conf/tuning/train_asr_conformer7_n_fft512_hop_length256.yaml` as follows:
```
encoder: conformer
encoder_conf:
    input_layer: conv2d
    output_size: 144
    num_blocks: 16
    attention_heads: 4
    linear_units: 576
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    normalize_before: true
    pos_enc_layer_type: rel_pos
    rel_pos_type: latest
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    macaron_style: true
    use_cnn_module:  true
    cnn_module_kernel: 31

decoder: transformer
decoder_conf:
    input_layer: embed
    attention_heads: 4
    linear_units: 576
    num_blocks: 1
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

# hybrid CTC/attention
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false
```
3. run on 8 V100 GPUs, then the first hundreds of iterations work well, but then the CUDA error occours.

**Error logs**
```
[ip-172-31-15-245:0/8] 2021-08-21 06:55:50,549 (abs_task:1504) INFO: [train] dataset:
ESPnetDataset(
  speech: {"path": "dump/raw/librispeech_train_960_sp/wav.scp", "type": "sound"}
  text: {"path": "dump/raw/librispeech_train_960_sp/text", "type": "text"}
  preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x7f0c3052ef50>)
[ip-172-31-15-245:0/8] 2021-08-21 06:55:50,551 (abs_task:1505) INFO: [train] Batch sampler: NumElementsBatchSampler(N-batch=2779, batch_bins=140000000, sort_in_batch=descending, sort_batch=descending)
[ip-172-31-15-245:0/8] 2021-08-21 06:55:50,552 (abs_task:1507) INFO: [train] mini-batch sizes summary: N-batch=2779, mean=303.6, min=41, max=1653
[ip-172-31-15-245:0/8] 2021-08-21 06:55:50,678 (abs_task:1504) INFO: [valid] dataset:
ESPnetDataset(
  speech: {"path": "dump/raw/librispeech_dev/wav.scp", "type": "sound"}
  text: {"path": "dump/raw/librispeech_dev/text", "type": "text"}
  preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x7f0c470a98d0>)
[ip-172-31-15-245:0/8] 2021-08-21 06:55:50,678 (abs_task:1505) INFO: [valid] Batch sampler: NumElementsBatchSampler(N-batch=12, batch_bins=140000000, sort_in_batch=descending, sort_batch=descending)
[ip-172-31-15-245:0/8] 2021-08-21 06:55:50,679 (abs_task:1507) INFO: [valid] mini-batch sizes summary: N-batch=12, mean=462.6, min=77, max=1042
[ip-172-31-15-245:0/8] 2021-08-21 06:55:50,718 (abs_task:1504) INFO: [plot_att] dataset:
ESPnetDataset(
  speech: {"path": "dump/raw/librispeech_dev/wav.scp", "type": "sound"}
  text: {"path": "dump/raw/librispeech_dev/text", "type": "text"}
  preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x7f0b7f72f990>)
[ip-172-31-15-245:0/8] 2021-08-21 06:55:50,718 (abs_task:1505) INFO: [plot_att] Batch sampler: UnsortedBatchSampler(N-batch=5551, batch_size=1, key_file=snapshots/asr_stats_librispeech_train_960_sp_raw_en_bpe5000/valid/speech_shape, 
[ip-172-31-15-245:0/8] 2021-08-21 06:55:50,719 (abs_task:1507) INFO: [plot_att] mini-batch sizes summary: N-batch=3, mean=1.0, min=1, max=1
[ip-172-31-15-245:0/8] 2021-08-21 06:55:57,117 (trainer:273) INFO: 1/35epoch started
~/espnet/tools/venv/lib64/python3.7/site-packages/torch/functional.py:516: UserWarning: The function torch.rfft is deprecated and will be removed in a future PyTorch release. Use the new torch.fft module functions, instead, by importing torch.fft and calling torch.fft.fft or torch.fft.rfft. (Triggered internally at  /pytorch/aten/src/ATen/native/SpectralOps.cpp:590.)
  normalized, onesided, return_complex)
[ip-172-31-15-245:0/8] 2021-08-21 06:56:13,645 (distributed:607) INFO: Reducer buckets have been rebuilt in this iteration.
[ip-172-31-15-245:0/8] 2021-08-21 06:57:54,249 (trainer:654) INFO: 1epoch:train:1-138batch: iter_time=0.004, forward_time=0.164, loss=744.241, loss_att=321.751, loss_ctc=1.730e+03, acc=2.198e-04, backward_time=0.366, optim_step_time=0.061, optim0_lr0=4.406e-06, train_time=0.844
[ip-172-31-15-245:0/8] 2021-08-21 06:59:34,964 (trainer:654) INFO: 1epoch:train:139-276batch: iter_time=7.903e-05, forward_time=0.158, loss=458.286, loss_att=329.184, loss_ctc=759.523, acc=3.533e-04, backward_time=0.363, optim_step_time=0.061, optim0_lr0=1.303e-05, train_time=0.730
[ip-172-31-15-245:0/8] 2021-08-21 07:01:14,062 (trainer:654) INFO: 1epoch:train:277-414batch: iter_time=7.788e-05, forward_time=0.159, loss=356.214, loss_att=301.985, loss_ctc=482.747, acc=0.006, backward_time=0.361, optim_step_time=0.060, optim0_lr0=2.166e-05, train_time=0.718
[ip-172-31-15-245:0/8] 2021-08-21 07:02:51,940 (trainer:654) INFO: 1epoch:train:415-552batch: iter_time=7.711e-05, forward_time=0.157, loss=287.477, loss_att=264.993, loss_ctc=339.938, acc=0.044, backward_time=0.360, optim_step_time=0.059, optim0_lr0=3.028e-05, train_time=0.709
[ip-172-31-15-245:0/8] 2021-08-21 07:04:30,121 (trainer:654) INFO: 1epoch:train:553-690batch: iter_time=7.716e-05, forward_time=0.158, loss=252.736, loss_att=239.338, loss_ctc=283.996, acc=0.050, backward_time=0.361, optim_step_time=0.060, optim0_lr0=3.891e-05, train_time=0.711
[ip-172-31-15-245:0/8] 2021-08-21 07:06:13,661 (trainer:654) INFO: 1epoch:train:691-828batch: iter_time=7.761e-05, forward_time=0.159, loss=250.943, loss_att=238.980, loss_ctc=278.856, acc=0.055, backward_time=0.363, optim_step_time=0.060, optim0_lr0=4.753e-05, train_time=0.750
[ip-172-31-15-245:0/8] 2021-08-21 07:07:58,053 (trainer:654) INFO: 1epoch:train:829-966batch: iter_time=7.727e-05, forward_time=0.159, loss=261.135, loss_att=248.019, loss_ctc=291.737, acc=0.059, backward_time=0.364, optim_step_time=0.060, optim0_lr0=5.616e-05, train_time=0.756
[ip-172-31-15-245:0/8] 2021-08-21 07:09:41,661 (trainer:654) INFO: 1epoch:train:967-1104batch: iter_time=7.750e-05, forward_time=0.159, loss=232.536, loss_att=220.398, loss_ctc=260.858, acc=0.063, backward_time=0.359, optim_step_time=0.059, optim0_lr0=6.478e-05, train_time=0.750
[ip-172-31-15-245:0/8] 2021-08-21 07:11:23,413 (trainer:654) INFO: 1epoch:train:1105-1242batch: iter_time=7.753e-05, forward_time=0.158, loss=238.665, loss_att=225.604, loss_ctc=269.139, acc=0.069, backward_time=0.361, optim_step_time=0.060, optim0_lr0=7.341e-05, train_time=0.737
[ip-172-31-15-245:0/8] 2021-08-21 07:13:01,887 (trainer:654) INFO: 1epoch:train:1243-1380batch: iter_time=7.705e-05, forward_time=0.158, loss=253.029, loss_att=238.852, loss_ctc=286.108, acc=0.073, backward_time=0.364, optim_step_time=0.060, optim0_lr0=8.203e-05, train_time=0.713
terminate called after throwing an instance of 'c10::Errorterminate called after throwing an instance of ''
c10::Errorterminate called after throwing an instance of ''
c10::Error'
terminate called after throwing an instance of 'c10::Error'
  what():    what():  CUDA error: an illegal memory access was encountered
Exception raised from create_event_internal at /pytorch/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7fe8087518b2 in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xad2 (0x7fe8089a3952 in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7fe80873cb7d in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x60253a (0x7fe8a405853a in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x6025e6 (0x7fe8a40585e6 in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #28: __libc_start_main + 0xea (0x7fe8b03ba0ba in /lib64/libc.so.6)
frame #29: _start + 0x2a (0x40066a in ~/espnet/tools/venv/bin/python3)
  what():  CUDA error: an illegal memory access was encountered
Exception raised from create_event_internal at /pytorch/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f761a1eb8b2 in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xad2 (0x7f761a43d952 in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f761a1d6b7d in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x60253a (0x7f76b5af253a in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x6025e6 (0x7f76b5af25e6 in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #28: __libc_start_main + 0xea (0x7f76c1e540ba in /lib64/libc.so.6)
frame #29: _start + 0x2a (0x40066a in ~/espnet/tools/venv/bin/python3)

CUDA error: an illegal memory access was encountered
Exception raised from create_event_internal at /pytorch/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f0c6bca58b2 in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xad2 (0x7f0c6bef7952 in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f0c6bc90b7d in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x60253a (0x7f0d075ac53a in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x6025e6 (0x7f0d075ac5e6 in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #28: __libc_start_main + 0xea (0x7f0d1390e0ba in /lib64/libc.so.6)
frame #29: _start + 0x2a (0x40066a in ~/espnet/tools/venv/bin/python3)

  what():  
CUDA error: an illegal memory access was encountered
Exception raised from create_event_internal at /pytorch/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f24eb4128b2 in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xad2 (0x7f24eb664952 in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f24eb3fdb7d in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x60253a (0x7f2586d1953a in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x6025e6 (0x7f2586d195e6 in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #28: __libc_start_main + 0xea (0x7f259307b0ba in /lib64/libc.so.6)
frame #29: _start + 0x2a (0x40066a in ~/espnet/tools/venv/bin/python3)

terminate called after throwing an instance of 'c10::Errorterminate called after throwing an instance of ''
c10::Error'
  what():  CUDA error: an illegal memory access was encountered
Exception raised from create_event_internal at /pytorch/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7ff75b04e8b2 in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xad2 (0x7ff75b2a0952 in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7ff75b039b7d in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x60253a (0x7ff7f695553a in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x6025e6 (0x7ff7f69555e6 in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #28: __libc_start_main + 0xea (0x7ff802cb70ba in /lib64/libc.so.6)
frame #29: _start + 0x2a (0x40066a in ~/espnet/tools/venv/bin/python3)

  what():  CUDA error: an illegal memory access was encountered
Exception raised from create_event_internal at /pytorch/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f04b2d288b2 in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xad2 (0x7f04b2f7a952 in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f04b2d13b7d in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x60253a (0x7f054e62f53a in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x6025e6 (0x7f054e62f5e6 in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #28: __libc_start_main + 0xea (0x7f055a9910ba in /lib64/libc.so.6)
frame #29: _start + 0x2a (0x40066a in ~/espnet/tools/venv/bin/python3)

terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
Exception raised from create_event_internal at /pytorch/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f035ae458b2 in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xad2 (0x7f035b097952 in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f035ae30b7d in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x60253a (0x7f03f674c53a in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x6025e6 (0x7f03f674c5e6 in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #28: __libc_start_main + 0xea (0x7f0402aae0ba in /lib64/libc.so.6)
frame #29: _start + 0x2a (0x40066a in ~/espnet/tools/venv/bin/python3)

terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
Exception raised from create_event_internal at /pytorch/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f70b8a198b2 in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xad2 (0x7f70b8c6b952 in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f70b8a04b7d in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x60253a (0x7f715432053a in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x6025e6 (0x7f71543205e6 in ~/espnet/tools/venv/lib64/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #28: __libc_start_main + 0xea (0x7f71606820ba in /lib64/libc.so.6)
frame #29: _start + 0x2a (0x40066a in ~/espnet/tools/venv/bin/python3)

Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "~/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "~/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "~/espnet/espnet2/tasks/abs_task.py", line 1052, in main
    while not ProcessContext(processes, error_queues).join():
  File "~/espnet/tools/venv/lib64/python3.7/site-packages/torch/multiprocessing/spawn.py", line 107, in join
    (error_index, name)
Exception: process 7 terminated with signal SIGABRT
# Accounting: time=1118 threads=1
# Ended (code 1) at Sat Aug 21 07:13:51 UTC 2021, elapsed time 1118 seconds
```

**Comment by D-X-Y** [comment]
BTW, even jut change "input_layer: conv2d" to "input_layer: conv2d6", it will work.. May I seek some suggestions?

**Comment by sw005320** [comment]
Thanks for the report.
Could you identify which batch causes this issue, and share the shape of this batch (especially input length)?
If conv2d6 is working while conv2d is not, I'm expecting there would be some issues related to the input length.

**Comment by D-X-Y** [comment]
Thanks for your reply. For some architecture config, conv2d6 failed, for some others, conv2d6 works.. I'm currently on debugging this issue.

**Comment by sw005320** [comment]
Thanks, and that sounds very strange.
It would be great if you figure out the issue, and share it with us!

**Comment by D-X-Y** [comment]
I tried to reproduce this error on a single GPU machine by removing the distribution-related commands (https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/asr1/asr.sh#L1068-L1074).
But it works well, on another 8 GPU machine with distribution training this error occurs...
Do u have any suggestions to debug this issue?

**Comment by D-X-Y** [comment]
@Fhrozen That is a good point, I will have a try,

**Comment by nellorebhanuteja** [comment]
@sw005320 
I am facing the same issue
Any solution ??
