### ISSUE TITLE
s3prl pretrained model inference

### ISSUE THREAD

**Issue by abnerLing** [espnet/espnet#3610]
I am trying to just test the inference of the pretrained hubert-conformer mode using the model uploaded on HuggingFace, but I get an error regarding state_dict keys.
```
Using cache found in ./hub/s3prl_cache/4a54d64fa42b41e39db994c958d8107d5785a100f38c6eba680b6a3cc79babb3
for https://dl.fbaipublicfiles.com/hubert/hubert_large_ll60k.pt
[Featurizer] - Take a list of 25 features and weighted sum them.
[Featurizer] - The selected feature hidden_states's downsample rate is 320
WARNING:root:Using legacy_rel_pos and it will be deprecated in the future.
WARNING:root:Using legacy_rel_selfattn and it will be deprecated in the future.
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    "espnet/xuankai_chang_librispeech_asr_train_asr_conformer7_hubert_960hr_large_raw_en_bpe5000_sp_26epoch")
  File "/home/hernandez/work/espnet/espnet2/bin/asr_inference.py", line 275, in from_pretrained
    return Speech2Text(**kwargs)
  File "/home/hernandez/work/espnet/espnet2/bin/asr_inference.py", line 80, in __init__
    asr_train_config, asr_model_file, device
  File "/home/hernandez/work/espnet/espnet2/tasks/abs_task.py", line 1800, in build_model_from_file
    model.load_state_dict(torch.load(model_file, map_location=device))
  File "/home/hernandez/miniconda3/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ESPnetASRModel:
	Missing key(s) in state_dict: "frontend.upstream.model.label_embs_concat".

```
I'm simply using the below code.

```
from espnet2.bin.asr_inference import Speech2Text
    
model = Speech2Text.from_pretrained(
  "espnet/xuankai_chang_librispeech_asr_train_asr_conformer7_hubert_960hr_large_raw_en_bpe5000_sp_26epoch"
)

speech, rate = soundfile.read("speech.wav")
text, *_ = model(speech)
```

```
 python version: `3.7.11 (default, Jul 27 2021, 14:32:16)  [GCC 7.5.0]`
- espnet version: `espnet 0.10.3a3`
- pytorch version: `pytorch 1.7.1`
- Git hash: `a9c032b0bb3dcc64f1cb27896fd0746f8e1e4a59`
  - Commit date: `Mon Sep 20 09:49:48 2021 +0200`
```

**Comment by simpleoier** [comment]
@abnerLing Thanks for reporting this. Actually, I also met this error last week when I tried decoding with pretrained model. It is because a parameter `label_embs_concat` was missing in the pretrained models (could be due to the fairseq version issues). I need some further discussion with the original author who provided the model. There is a solution which worked in my case:  In `espnet/tools/s3prl/s3prl/upstream/hubert/expert.py`
```python
    model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task(
         [ckpt]
    )
```
to 
```python
    model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task(
         [ckpt],
         strict=False,
    )
```
