### ISSUE TITLE
poetry update failed with {path = espnet, develop=true} 

### ISSUE THREAD

**Issue by keiouok** [espnet/espnet#3640]
Hello. 

I tried to install espnet in python poetry environment.  
Then I did `poetry add` with this `pyproject.toml`. However I had the following error. 

(Now I'm using this environment with `pip3 install -e ./espnet`. It was no problem. ) 

After this error, I did `poetry add {numpy, Cython, scipy}` in this poetry env and `pip3 install {numpy, Cython, scipy}` in pyenv. However the same error still occurs. 

I also sent this issue to poetry. According to them, it would be because espnet package doesn't have building information in PEP 518. https://github.com/python-poetry/poetry/issues/4555

If there are any solutions for installing espnet with poetry, please tell me. 

Thank you. 

## environment
Ubuntu 18.04
pyenv 3.7.4
poetry 1.1.6 (pyenv' poetry installed by `pip3 install poetry`)
espnet v.0.9.10 (https://github.com/espnet/espnet . We just did `git clone` and didn't revise it.)

## pyproject.toml
```
[tool.poetry]
name = "<mypackage>"
version = "0.1.0"
description = ""
authors = ["<author>"]

[tool.poetry.dependencies]
python = "^3.7"
espnet = { path = "./espnet", develop = true }

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

## Error
```
$ poetry update
Updating dependencies
Resolving dependencies... (21.3s)

  PackageInfoError

  Unable to determine package info for path: /tmp/pypoetry-git-pb_bssxywff8p2

  Fallback egg_info generation failed.

  Command ['/tmp/tmpimlopw3b/.venv/bin/python', 'setup.py', 'egg_info'] errored with the following return code 1, and output:
  Traceback (most recent call last):
    File "setup.py", line 3, in <module>
      import numpy as np
  ModuleNotFoundError: No module named 'numpy'

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "setup.py", line 15, in <module>
      """) from e
  ModuleNotFoundError:
  This package has some Cython files that will be compilled,

  when you install this package. The Cython files use numpy and scipy.

  Please install them before you install this packges:

      'conda install numpy Cython scipy'
  or
      'pip install numpy Cython scipy'

  at ~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/poetry/inspection/info.py:503 in _pep517_metadata
      499│                     venv.run("python", "setup.py", "egg_info")
      500│                     return cls.from_metadata(path)
      501│                 except EnvCommandError as fbe:
      502│                     raise PackageInfoError(
    → 503│                         path, "Fallback egg_info generation failed.", fbe
      504│                     )
      505│                 finally:
      506│                     os.chdir(cwd.as_posix())
      507│
```

**Comment by kamo-naoyuki** [comment]
@kan-bayashi I don't know poetry, but, probably, https://github.com/espnet/espnet/tree/master/espnet2/gan_tts/vits/monotonic_align has the problem because they don't appear in setup.py, but I don't also think it's good idea to build cython files directly in our espnet setup.py.

How about moving them as an external module, like https://github.com/lumaku/ctc-segmentation?

**Comment by kan-bayashi** [comment]
I added pyproject.toml file in #3657.
@keiouok Could you test it?
