### ISSUE TITLE
StopIteration exception was raised when running vcc20

### ISSUE THREAD

**Issue by zzxiang** [espnet/espnet#3645]
**Describe the bug**
When running stage 4 of [egs/vcc20/tts1_en_zh/run.sh](https://github.com/espnet/espnet/blob/66facd2859977d23349cf74d5c8f5394e5cb6784/egs/vcc20/tts1_en_zh/run.sh), StopIteration exception was raised and the training process failed.

**Basic environments:**
 - OS information: Linux 5.11.0-1020-gcp 20.04.1-Ubuntu SMP x86_64
 - python version: 3.8.10
 - cudatoolkit version: 11.1.1
 - espnet version: 0.10.0
 - Git hash 06335e6a427e174d1db5e68c97fba944451426f5
   - Commit date Mon Jul 12 23:40:03 2021 -0400
 - pytorch version: 1.9.0
 
I also tried
- python version: 3.8.11
- cudatoolkit version: 10.1.243
- pytorch version: 1.4.0

but the same problem occurred.

You can obtain them by the following command
```
cd <espnet-root>/egs/vcc20/tts1_en_zh
./run.sh --stop-stage 3
./run.sh --stage 4 --stop-stage 4
```

**Environments from `torch.utils.collect_env` (pytorch 1.9.0):**
```
Collecting environment information...
PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-3ubuntu2) 8.4.0
Clang version: Could not collect
CMake version: version 3.19.6
Libc version: glibc-2.31

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.11.0-1020-gcp-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.1.74
GPU models and configuration: 
GPU 0: Tesla T4
GPU 1: Tesla T4

Nvidia driver version: 460.91.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.0
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.9.0
[pip3] torch-complex==0.2.1
[pip3] torch-optimizer==0.1.0
[pip3] torchaudio==0.9.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.1.1               h6406543_8    conda-forge
[conda] mkl                       2021.2.0           h06a4308_296  
[conda] numpy                     1.21.0                   pypi_0    pypi
[conda] pytorch                   1.9.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.1                    pypi_0    pypi
[conda] torch-complex             0.2.1                    pypi_0    pypi
[conda] torch-optimizer           0.1.0                    pypi_0    pypi
[conda] torchaudio                0.9.0                    pypi_0    pypi
```

**Environments from `torch.utils.collect_env` (pytorch 1.4.0):**
```
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 20.04.3 LTS
GCC version: (Ubuntu 8.4.0-3ubuntu2) 8.4.0
CMake version: Could not collect

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla T4
GPU 1: Tesla T4

Nvidia driver version: 460.91.03
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.4.0
[pip3] torchvision==0.5.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.3.0           h06a4308_520  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] pytorch                   1.4.0           py3.8_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.5.0                py38_cu101    pytorch
```

You can obtain them by the following command

```
cd <espnet-root>/tools
. ./activate_python.sh
python3 -m torch.utils.collect_env
```

**Task information:**
 - Task: VC
 - Recipe: vcc20/tts1_en_zh
 - ESPnet1

**To Reproduce**
1. move to a recipe directory: `cd  vcc20/tts1_en_zh`
2. execute `run.sh` to stage 4 (inclusive)
3. check the error log: `exp/train_pytorch_train_pytorch_transformer+spkemb/train.log`

**Error logs**
```
Exception in main training loop: Caught StopIteration in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/sshu/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/sshu/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sshu/espnet/espnet/nets/pytorch_backend/e2e_tts_transformer.py", line 717, in forward
    x_masks = self._source_mask(ilens)
  File "/home/sshu/espnet/espnet/nets/pytorch_backend/e2e_tts_transformer.py", line 1095, in _source_mask
    x_masks = make_non_pad_mask(ilens).to(next(self.parameters()).device)
StopIteration

Traceback (most recent call last):
  File "/home/sshu/anaconda3/envs/espnet/lib/python3.8/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/home/sshu/espnet/espnet/tts/pytorch_backend/tts.py", line 171, in update
    self.update_core()
  File "/home/sshu/espnet/espnet/tts/pytorch_backend/tts.py", line 151, in update_core
    loss = self.model(**x).mean() / self.accum_grad
  File "/home/sshu/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sshu/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/sshu/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/sshu/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/sshu/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/home/sshu/espnet/egs/vcc20/tts1_en_zh/../../../espnet/bin/tts_train.py", line 359, in <module>
    main(sys.argv[1:])
  File "/home/sshu/espnet/egs/vcc20/tts1_en_zh/../../../espnet/bin/tts_train.py", line 353, in main
    train(args)
  File "/home/sshu/espnet/espnet/tts/pytorch_backend/tts.py", line 565, in train
    trainer.run()
  File "/home/sshu/anaconda3/envs/espnet/lib/python3.8/site-packages/chainer/training/trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "/home/sshu/anaconda3/envs/espnet/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/sshu/anaconda3/envs/espnet/lib/python3.8/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/home/sshu/espnet/espnet/tts/pytorch_backend/tts.py", line 171, in update
    self.update_core()
  File "/home/sshu/espnet/espnet/tts/pytorch_backend/tts.py", line 151, in update_core
    loss = self.model(**x).mean() / self.accum_grad
  File "/home/sshu/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sshu/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/sshu/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/sshu/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/sshu/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
StopIteration: Caught StopIteration in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/sshu/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/sshu/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sshu/espnet/espnet/nets/pytorch_backend/e2e_tts_transformer.py", line 717, in forward
    x_masks = self._source_mask(ilens)
  File "/home/sshu/espnet/espnet/nets/pytorch_backend/e2e_tts_transformer.py", line 1095, in _source_mask
    x_masks = make_non_pad_mask(ilens).to(next(self.parameters()).device)
StopIteration
```

**Comment by zzxiang** [comment]
I found the reason. It's because I set `ngpu` to 2 to try to use 2 GPUs.
I overcame this issue by using only 1 GPU.

The same problem is also mentioned in https://github.com/espnet/espnet/issues/2169
But it's strange that the problem still occurred even if I downgraded pytorch to 1.4.0.
