### ISSUE TITLE
use_teacher_forcing mode error

### ISSUE THREAD

**Issue by adsf0078** [espnet/espnet#3777]
Hi,
Thank you for your good work.
I 'd like to train hifigan vocoder with GTA from fastspeech2 results.
When I run fastspeech2 in use_teacher_forcing mode for GTA, I get the following error regarding durations.
What was wrong? 
Prior to fastspeech2 training, there was no problem when I ran the same stage, i.e. 7 in tacotron2. 
Please any advices.
Thank you in advance!
```
(espnet) verona:/data1/simon/espnet/egs2/mrspeech/read$ CUDA_VISIBLE_DEVICES=5 ./run.sh --test_sets "tr_no_dev dev"  --inference_args "--use_teacher_forcing true"
2021-11-11T10:03:18 (tts.sh:190:main) ./tts.sh --lang en --feats_type raw --fs 22050 --n_fft 1024 --n_shift 256 --token_type phn --cleaner tocotron --g2p g2p_en --train_config conf/tuning/train_fastspeech2.yaml --inference_config conf/tuning/decode_fastspeech.yaml --train_set tr_no_dev --valid_set dev --test_sets eval1 --srctexts data/tr_no_dev/text --audio_format wav --test_sets tr_no_dev dev --inference_args --use_teacher_forcing true
2021-11-11T10:03:19 (tts.sh:805:main) Stage 7: Decoding: training_dir=exp/tts_train_fastspeech2_raw_phn_tacotron_g2p_en
2021-11-11T10:03:19 (tts.sh:854:main) Generate 'exp/tts_train_fastspeech2_raw_phn_tocotron_g2p_en/decode_fastspeech_use_teacher_forcingtrue_train.loss.ave/run.sh'. You can resume the process from stage 7 using this script
2021-11-11T10:03:19 (tts.sh:892:main) Decoding started... log: 'exp/tts_train_fastspeech2_raw_phn_tocotron_g2p_en/decode_fastspeech_use_teacher_forcingtrue_train.loss.ave/tr_no_dev/log/tts_inference.*.log'
/home/simon/anaconda3/envs/espnet/bin/python3 /data1/simon/espnet/espnet2/bin/tts_inference.py --ngpu 1 --data_path_and_name_and_type dump/raw/tr_no_dev/text,text,text --data_path_and_name_and_type dump/raw/tr_no_dev/wav.scp,speech,sound --key_file exp/tts_train_fastspeech2_raw_phn_tacotron_g2p_en/decode_fastspeech_use_teacher_forcingtrue_train.loss.ave/tr_no_dev/log/keys.1.scp --model_file exp/tts_train_fastspeech2_raw_phn_tacotron_g2p_en/train.loss.ave.pth --train_config exp/tts_train_fastspeech2_raw_phn_tacotron_g2p_en/config.yaml --output_dir exp/tts_train_fastspeech2_raw_phn_tacotron_g2p_en/decode_fastspeech_use_teacher_forcingtrue_train.loss.ave/tr_no_dev/log/output.1 --vocoder_conf griffin_lim_iters=4 --config conf/tuning/decode_fastspeech.yaml --use_teacher_forcing true
2021-11-11 10:03:22,579 (tts:273) INFO: Vocabulary size: 54
2021-11-11 10:03:22,694 (encoder:148) INFO: encoder self-attention layer type = self-attention
2021-11-11 10:03:22,864 (encoder:148) INFO: encoder self-attention layer type = self-attention
2021-11-11 10:03:26,685 (tts_inference:90) INFO: Normalization:
GlobalMVN(stats_file=exp/tts_train_raw_phn_tacotron_g2p_en/decode_tacotron2_use_teacher_forcingtrue_train.loss.ave/stats/train/feats_stats.npz, norm_means=True, norm_vars=True)
2021-11-11 10:03:27,841 (hifigan:203) INFO: Successfully registered stats as buffer.
tts inference
/home/simon/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/functional.py:516: UserWarning: stft will require the return_complex parameter be explicitly  specified in a future PyTorch release. Use return_complex=False  to preserve the current behavior or return_complex=True to return  a complex output. (Triggered internally at  /pytorch/aten/src/ATen/native/SpectralOps.cpp:653.)
  normalized, onesided, return_complex)
/home/simon/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/functional.py:516: UserWarning: The function torch.rfft is deprecated and will be removed in a future PyTorch release. Use the new torch.fft module functions, instead, by importing torch.fft and calling torch.fft.fft or torch.fft.rfft. (Triggered internally at  /pytorch/aten/src/ATen/native/SpectralOps.cpp:590.)
  normalized, onesided, return_complex)
Traceback (most recent call last):
  File "/home/simon/anaconda3/envs/espnet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/simon/anaconda3/envs/espnet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data1/simon/espnet/espnet2/bin/tts_inference.py", line 569, in <module>
    main()
  File "/data1/simon/espnet/espnet2/bin/tts_inference.py", line 565, in main
    inference(**kwargs)
  File "/data1/simon/espnet/espnet2/bin/tts_inference.py", line 317, in inference
    **batch
  File "/home/simon/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/data1/simon/espnet/espnet2/bin/tts_inference.py", line 159, in __call__
    **batch, **self.decode_config
  File "/data1/simon/espnet/espnet2/tts/espnet_model.py", line 185, in inference
    durations=durations[None],
TypeError: 'NoneType' object is not subscriptable
```

**Comment by kan-bayashi** [comment]
Since groundtruth `durations` must be provided, you need to specify `--teacher_dumpdir`.

**Comment by adsf0078** [comment]
> Since groundtruth `durations�` must be provided, you need to specify `--teacher_dumpdir` as well.

Thank you, for your quick reply. 

then do  I use the durations from tacotron2 results  as teacher_dumpdir ?

**Comment by kan-bayashi** [comment]
> then do I use the durations from tacotron2 results as teacher_dumpdir ?

Right. Same as the training stage.

**Comment by adsf0078** [comment]
> Right. Same as the training stage.

Thank you.
