### ISSUE TITLE
Tried replicating AIShell recipe with a custom dataset and failed due to an error

### ISSUE THREAD

**Issue by tarunsaib1997** [espnet/espnet#3835]
# asr_train.py --config conf/train_conformer.yaml --preprocess-conf --ngpu 1 --backend pytorch --outdir exp/train_IISC_pytorch_train_conformer/results --tensorboard-dir tensorboard/train_IISC_pytorch_train_conformer --debugmode 1 --dict data/lang_1char/train_IISC_units.txt --debugdir exp/train_IISC_pytorch_train_conformer --minibatches 0 --verbose 0 --resume --train-json dump/train_IISC/deltafalse/data.json --valid-json dump/dev/deltafalse/data.json 
# Started at Wed Dec  1 19:09:58 IST 2021
#
2021-12-01 20:06:07,712 (asr_train:563) WARNING: Skip DEBUG/INFO messages
2021-12-01 20:06:22,853 (ctc:38) WARNING: CTC was set to builtin due to PyTorch version.
2021-12-01 20:06:36,562 (asr:503) WARNING: num. model params: 43,112,732 (num. trained: 43,112,732 (100.0%))
epoch       iteration   main/loss   main/loss_ctc  main/loss_att  validation/main/loss  validation/main/loss_ctc  validation/main/loss_att  main/acc    validation/main/acc  main/cer_ctc  validation/main/cer_ctc  elapsed_time
[J0           100         295.608     489.762        212.399                                                                                  0.00909221                                                              504.339       
[J     total [..................................................]  0.08%
this epoch [##................................................]  4.07%
       100 iter, 0 epoch / 50 epochs
       inf iters/sec. Estimated time to finish: 0:00:00.
[4A[J0           200         221.104     232.721        216.125                                                                                  0.0144449                                                               937.849       
[J     total [..................................................]  0.16%
this epoch [####..............................................]  8.15%
       200 iter, 0 epoch / 50 epochs
   0.23067 iters/sec. Estimated time to finish: 6 days, 3:32:47.418440.
[4A[J0           300         187.596     184.985        188.715                                                                                  0.0429184                                                               1394.47       
[J     total [..................................................]  0.24%
this epoch [######............................................] 12.22%
       300 iter, 0 epoch / 50 epochs
   0.22468 iters/sec. Estimated time to finish: 6 days, 7:21:14.824984.
[4A[J0           400         180.17      180.994        179.816                                                                                  0.15135                                                                 1817.09       
[J     total [..................................................]  0.33%
this epoch [########..........................................] 16.30%
       400 iter, 0 epoch / 50 epochs
   0.22853 iters/sec. Estimated time to finish: 6 days, 4:41:11.511320.
[4A[J0           500         185.251     193.933        181.53                                                                                   0.186138                                                                2231.07       
[J     total [..................................................]  0.41%
this epoch [##########........................................] 20.37%
       500 iter, 0 epoch / 50 epochs
   0.23165 iters/sec. Estimated time to finish: 6 days, 2:33:41.714599.
[4A[J0           600         166.412     181.078        160.127                                                                                  0.190111                                                                2669.47       
[J     total [..................................................]  0.49%
this epoch [############......................................] 24.44%
       600 iter, 0 epoch / 50 epochs
   0.23093 iters/sec. Estimated time to finish: 6 days, 2:53:52.717241.
[4A[J0           700         154.674     172.98         146.828                                                                                  0.212874                                                                3101.21       
[J     total [..................................................]  0.57%
this epoch [##############....................................] 28.52%
       700 iter, 0 epoch / 50 epochs
   0.23105 iters/sec. Estimated time to finish: 6 days, 2:42:21.052563.
[4A[JException in main training loop: Calculated padded input size per channel: (1 x 41). Kernel size: (3 x 3). Kernel size can't be greater than actual input size
Traceback (most recent call last):
  File "/home/taruns/.conda/envs/espnetenv/lib/python3.7/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/home/taruns/espnet/espnet/asr/pytorch_backend/asr.py", line 235, in update
    self.update_core()
  File "/home/taruns/espnet/espnet/asr/pytorch_backend/asr.py", line 199, in update_core
    data_parallel(self.model, x, range(self.ngpu)).mean() / self.accum_grad
  File "/home/taruns/.conda/envs/espnetenv/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 228, in data_parallel
    return module(*inputs[0], **module_kwargs[0])
  File "/home/taruns/.conda/envs/espnetenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/taruns/espnet/espnet/nets/pytorch_backend/e2e_asr_transformer.py", line 190, in forward
    hs_pad, hs_mask, hs_intermediates = self.encoder(xs_pad, src_mask)
  File "/home/taruns/.conda/envs/espnetenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/taruns/espnet/espnet/nets/pytorch_backend/conformer/encoder.py", line 245, in forward
    xs, masks = self.embed(xs, masks)
  File "/home/taruns/.conda/envs/espnetenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/taruns/espnet/espnet/nets/pytorch_backend/transformer/subsampling.py", line 84, in forward
    x = self.conv(x)
  File "/home/taruns/.conda/envs/espnetenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/taruns/.conda/envs/espnetenv/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/taruns/.conda/envs/espnetenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/taruns/.conda/envs/espnetenv/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/taruns/.conda/envs/espnetenv/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    self.padding, self.dilation, self.groups)
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/home/taruns/espnet/espnet/bin/asr_train.py", line 639, in <module>
    main(sys.argv[1:])
  File "/home/taruns/espnet/espnet/bin/asr_train.py", line 625, in main
    train(args)
  File "/home/taruns/espnet/espnet/asr/pytorch_backend/asr.py", line 967, in train
    trainer.run()
  File "/home/taruns/.conda/envs/espnetenv/lib/python3.7/site-packages/chainer/training/trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "/home/taruns/.conda/envs/espnetenv/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/taruns/.conda/envs/espnetenv/lib/python3.7/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/home/taruns/espnet/espnet/asr/pytorch_backend/asr.py", line 235, in update
    self.update_core()
  File "/home/taruns/espnet/espnet/asr/pytorch_backend/asr.py", line 199, in update_core
    data_parallel(self.model, x, range(self.ngpu)).mean() / self.accum_grad
  File "/home/taruns/.conda/envs/espnetenv/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 228, in data_parallel
    return module(*inputs[0], **module_kwargs[0])
  File "/home/taruns/.conda/envs/espnetenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/taruns/espnet/espnet/nets/pytorch_backend/e2e_asr_transformer.py", line 190, in forward
    hs_pad, hs_mask, hs_intermediates = self.encoder(xs_pad, src_mask)
  File "/home/taruns/.conda/envs/espnetenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/taruns/espnet/espnet/nets/pytorch_backend/conformer/encoder.py", line 245, in forward
    xs, masks = self.embed(xs, masks)
  File "/home/taruns/.conda/envs/espnetenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/taruns/espnet/espnet/nets/pytorch_backend/transformer/subsampling.py", line 84, in forward
    x = self.conv(x)
  File "/home/taruns/.conda/envs/espnetenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/taruns/.conda/envs/espnetenv/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/taruns/.conda/envs/espnetenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/taruns/.conda/envs/espnetenv/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/taruns/.conda/envs/espnetenv/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Calculated padded input size per channel: (1 x 41). Kernel size: (3 x 3). Kernel size can't be greater than actual input size
# Accounting: time=6595 threads=1
# Ended (code 1) at Wed Dec  1 20:59:53 IST 2021, elapsed time 6595 seconds

**Comment by sw005320** [comment]
As the error message says, there would be an issue with the input data.
Can you check whether your audio data have enough length or feature extraction configuration is correctly set?

**Comment by tarunsaib1997** [comment]
I checked the audio files and the feature extraction configuration.  There was a similar issue with audio files length https://github.com/espnet/espnet/issues/2746. You have rectified in espnet2 folder but not in espnet. Could you please help this out?

**Comment by sw005320** [comment]
As #2746, this is due to too short sentences, which would not produce meaningful recognition results during inference or would be just harmful during training.
You seem to encounter this issue during training, but if you follow our recipe, these files should be removed https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/asr1/asr.sh#L570 unless you set the wrong feature configurations.

**Comment by tarunsaib1997** [comment]
Thanks, it's worked.
