### ISSUE TITLE
OSError: /tmp/tmpy4lr98to/libespeak-ng.so.1.1.49: cannot change memory protections

### ISSUE THREAD

**Issue by 123srikanth** [espnet/espnet#3858]
I'm running espnet/egs2/ljspeech/tts1 model in the 4th stage of training I'm getting the following error can someone please help in figuring this out 

`Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/srikanth/espnet/espnet2/bin/tokenize_text.py", line 271, in <module>
    main()
  File "/home/srikanth/espnet/espnet2/bin/tokenize_text.py", line 267, in main
    tokenize(**kwargs)
  File "/home/srikanth/espnet/espnet2/bin/tokenize_text.py", line 129, in tokenize
    tokens = tokenizer.text2tokens(line)
  File "/home/srikanth/espnet/espnet2/text/phoneme_tokenizer.py", line 512, in text2tokens
    tokens = self.g2p(line)
  File "/home/srikanth/espnet/espnet2/text/phoneme_tokenizer.py", line 336, in __call__
    tokens = self.phonemize(
  File "/usr/lib/python3.9/phonemizer/phonemize.py", line 217, in phonemize
    phonemizer = BACKENDS[backend](
  File "/usr/lib/python3.9/phonemizer/backend/espeak/espeak.py", line 44, in __init__
    super().__init__(
  File "/usr/lib/python3.9/phonemizer/backend/espeak/base.py", line 36, in __init__
    self._espeak = EspeakWrapper()
  File "/usr/lib/python3.9/phonemizer/backend/espeak/wrapper.py", line 59, in __init__
    self._espeak = EspeakAPI(self.library())
  File "/usr/lib/python3.9/phonemizer/backend/espeak/api.py", line 80, in __init__
    self._library = ctypes.cdll.LoadLibrary(str(espeak_copy))
  File "/usr/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /tmp/tmpy4lr98to/libespeak-ng.so.1.1.49: cannot change memory protections`

**Comment by kan-bayashi** [comment]
It seems on-the-fly processing with phonemizer is not stable.
Could you try to dump the phonemized text in data prep stage as follows (see command section)?
https://github.com/espnet/espnet/tree/master/egs2/ljspeech/tts1#ljspeech_tts_train_vits_raw_phn_tacotron_espeak_ng_english_us_vits_traintotal_countave

**Comment by 123srikanth** [comment]
yeah I have tried it but my entire system is getting stuck totally with this output

srikanth@simpragma147:~/Desktop/workspace/TTS/espnet/egs2/ljspeech/tts1$ ./run.sh --stage 1 --stop-stage 1
apply_map.pl: undefined key LJ001-0001|एयरटेल in data/tr_no_dev_phn/utt_map

**Comment by Mortyzhou-Shef-BIT** [comment]
> phonemizer

Hii, Do you solve this problem, I also met it when I transferring the India language named hindi and telguru, Thank you

**Comment by 78Alpha** [comment]
Oddly enough, running into these issues in 2024, didn't think the issue would be so old.

**Comment by KeiKinn** [comment]
I reinstall phonemizer to version 2.2.1 and it works

**Comment by ZodiacFRA** [comment]
Got this error with phonemizer version 3.3.0 (python 3.10.12, ubuntu 22.04)

```
 File "/home/foo/main.py", line 31, in bar
    phonemes = phonemize(word, language="fr-fr", backend="espeak", strip=True)
  File "/home/foo/.local/lib/python3.10/site-packages/phonemizer/phonemize.py", line 206, in phonemize
    phonemizer = BACKENDS[backend](
  File "/home/foo/.local/lib/python3.10/site-packages/phonemizer/backend/espeak/espeak.py", line 45, in __init__
    super().__init__(
  File "/home/foo/.local/lib/python3.10/site-packages/phonemizer/backend/espeak/base.py", line 39, in __init__
    super().__init__(
  File "/home/foo/.local/lib/python3.10/site-packages/phonemizer/backend/base.py", line 76, in __init__
    if not self.is_available():
  File "/home/foo/.local/lib/python3.10/site-packages/phonemizer/backend/espeak/base.py", line 87, in is_available
    EspeakWrapper()
  File "/home/foo/.local/lib/python3.10/site-packages/phonemizer/backend/espeak/wrapper.py", line 60, in __init__
    self._espeak = EspeakAPI(self.library())
  File "/home/foo/.local/lib/python3.10/site-packages/phonemizer/backend/espeak/api.py", line 84, in __init__
    self._library = ctypes.cdll.LoadLibrary(str(espeak_copy))
  File "/usr/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /tmp/tmp345ht1yz/libespeak.so.1.1.48: cannot change memory protections
```

**Comment by pabloriera** [comment]
One solution is to init the phonemizer backend only once, and then usit as many times as wanted. For example as done here
https://github.com/huggingface/transformers/blob/v4.46.0/src/transformers/models/wav2vec2_phoneme/tokenization_wav2vec2_phoneme.py#L175
