### ISSUE TITLE
error in statistics generation

### ISSUE THREAD

**Issue by sravani40** [espnet/espnet#3924]
```
2021-12-28T14:44:45 (tts.sh:205:main) ./tts.sh --lang en --feats_type raw --fs 22050 --n_fft 1024 --n_shift 256 --token_type phn --cleaner none --g2p none --train_config conf/train.yaml --inference_config conf/decode.yaml --train_set tr_no_dev --valid_set dev --test_sets dev eval1 --srctexts data/tr_no_dev/text --audio_format wav --stage 5 --stop-stage 5
2021-12-28T14:44:45 (tts.sh:532:main) Stage 5: TTS collect stats: train_set=dump/raw/tr_no_dev, valid_set=dump/raw/dev
2021-12-28T14:44:45 (tts.sh:619:main) Generate 'exp/tts_stats_raw_phn_none/run.sh'. You can resume the process from stage 5 using this script
2021-12-28T14:44:45 (tts.sh:623:main) TTS collect_stats started... log: 'exp/tts_stats_raw_phn_none/logdir/stats.*.log'
run.pl: 32 / 32 failed, log is in exp/tts_stats_raw_phn_none/logdir/stats.*.log
# python3 -m espnet2.bin.tts_train --collect_stats true --write_collected_feats false --use_preprocessor true --token_type phn --token_list dump/token_list/phn_none/tokens.txt --non_linguistic_symbols none --cleaner none --g2p none --normalize none --pitch_normalize none --energy_normalize none --train_data_path_and_name_and_type dump/raw/tr_no_dev/text,text,text --train_data_path_and_name_and_type dump/raw/tr_no_dev/wav.scp,speech,sound --valid_data_path_and_name_and_type dump/raw/dev/text,text,text --valid_data_path_and_name_and_type dump/raw/dev/wav.scp,speech,sound --train_shape_file exp/tts_stats_raw_phn_none/logdir/train.1.scp --valid_shape_file exp/tts_stats_raw_phn_none/logdir/valid.1.scp --output_dir exp/tts_stats_raw_phn_none/logdir/stats.1 --config conf/train.yaml --feats_extract fbank --feats_extract_conf n_fft=1024 --feats_extract_conf hop_length=256 --feats_extract_conf win_length=null --feats_extract_conf fs=22050 --feats_extract_conf fmin=80 --feats_extract_conf fmax=7600 --feats_extract_conf n_mels=80 --pitch_extract_conf fs=22050 --pitch_extract_conf n_fft=1024 --pitch_extract_conf hop_length=256 --pitch_extract_conf f0max=400 --pitch_extract_conf f0min=80 --energy_extract_conf fs=22050 --energy_extract_conf n_fft=1024 --energy_extract_conf hop_length=256 --energy_extract_conf win_length=null 
# Started at Tue Dec 28 14:44:45 UTC 2021
#
/usr/bin/python3 /home/ubuntu/.local/lib/python3.7/site-packages/espnet2/bin/tts_train.py --collect_stats true --write_collected_feats false --use_preprocessor true --token_type phn --token_list dump/token_list/phn_none/tokens.txt --non_linguistic_symbols none --cleaner none --g2p none --normalize none --pitch_normalize none --energy_normalize none --train_data_path_and_name_and_type dump/raw/tr_no_dev/text,text,text --train_data_path_and_name_and_type dump/raw/tr_no_dev/wav.scp,speech,sound --valid_data_path_and_name_and_type dump/raw/dev/text,text,text --valid_data_path_and_name_and_type dump/raw/dev/wav.scp,speech,sound --train_shape_file exp/tts_stats_raw_phn_none/logdir/train.1.scp --valid_shape_file exp/tts_stats_raw_phn_none/logdir/valid.1.scp --output_dir exp/tts_stats_raw_phn_none/logdir/stats.1 --config conf/train.yaml --feats_extract fbank --feats_extract_conf n_fft=1024 --feats_extract_conf hop_length=256 --feats_extract_conf win_length=null --feats_extract_conf fs=22050 --feats_extract_conf fmin=80 --feats_extract_conf fmax=7600 --feats_extract_conf n_mels=80 --pitch_extract_conf fs=22050 --pitch_extract_conf n_fft=1024 --pitch_extract_conf hop_length=256 --pitch_extract_conf f0max=400 --pitch_extract_conf f0min=80 --energy_extract_conf fs=22050 --energy_extract_conf n_fft=1024 --energy_extract_conf hop_length=256 --energy_extract_conf win_length=null
[ip-172-31-26-159] 2021-12-28 14:44:47,761 (tts:285) INFO: Vocabulary size: 135
[ip-172-31-26-159] 2021-12-28 14:44:48,375 (abs_task:1157) INFO: pytorch.version=1.9.1+cu102, cuda.available=True, cudnn.version=7605, cudnn.benchmark=False, cudnn.deterministic=True
[ip-172-31-26-159] 2021-12-28 14:44:48,378 (abs_task:1158) INFO: Model structure:
ESPnetTTSModel(
  (feats_extract): LogMelFbank(
    (stft): Stft(n_fft=1024, win_length=1024, hop_length=256, center=True, normalized=False, onesided=True)
    (logmel): LogMel(sr=22050, n_fft=1024, n_mels=80, fmin=80, fmax=7600, htk=False)
  )
  (tts): Tacotron2(
    (enc): Encoder(
      (embed): Embedding(135, 512, padding_idx=0)
      (convs): ModuleList(
        (0): Sequential(
          (0): Conv1d(512, 512, kernel_size=(5,), stride=(1,), padding=(2,), bias=False)
          (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU()
          (3): Dropout(p=0.5, inplace=False)
        )
        (1): Sequential(
          (0): Conv1d(512, 512, kernel_size=(5,), stride=(1,), padding=(2,), bias=False)
          (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU()
          (3): Dropout(p=0.5, inplace=False)
        )
        (2): Sequential(
          (0): Conv1d(512, 512, kernel_size=(5,), stride=(1,), padding=(2,), bias=False)
          (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU()
          (3): Dropout(p=0.5, inplace=False)
        )
      )
      (blstm): LSTM(512, 256, batch_first=True, bidirectional=True)
    )
    (dec): Decoder(
      (att): AttLoc(
        (mlp_enc): Linear(in_features=512, out_features=512, bias=True)
        (mlp_dec): Linear(in_features=1024, out_features=512, bias=False)
        (mlp_att): Linear(in_features=32, out_features=512, bias=False)
        (loc_conv): Conv2d(1, 32, kernel_size=(1, 31), stride=(1, 1), padding=(0, 15), bias=False)
        (gvec): Linear(in_features=512, out_features=1, bias=True)
      )
      (lstm): ModuleList(
        (0): ZoneOutCell(
          (cell): LSTMCell(768, 1024)
        )
        (1): ZoneOutCell(
          (cell): LSTMCell(1024, 1024)
        )
      )
      (prenet): Prenet(
        (prenet): ModuleList(
          (0): Sequential(
            (0): Linear(in_features=80, out_features=256, bias=True)
            (1): ReLU()
          )
          (1): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): ReLU()
          )
        )
      )
      (postnet): Postnet(
        (postnet): ModuleList(
          (0): Sequential(
            (0): Conv1d(80, 512, kernel_size=(5,), stride=(1,), padding=(2,), bias=False)
            (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): Tanh()
            (3): Dropout(p=0.5, inplace=False)
          )
          (1): Sequential(
            (0): Conv1d(512, 512, kernel_size=(5,), stride=(1,), padding=(2,), bias=False)
            (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): Tanh()
            (3): Dropout(p=0.5, inplace=False)
          )
          (2): Sequential(
            (0): Conv1d(512, 512, kernel_size=(5,), stride=(1,), padding=(2,), bias=False)
            (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): Tanh()
            (3): Dropout(p=0.5, inplace=False)
          )
          (3): Sequential(
            (0): Conv1d(512, 512, kernel_size=(5,), stride=(1,), padding=(2,), bias=False)
            (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): Tanh()
            (3): Dropout(p=0.5, inplace=False)
          )
          (4): Sequential(
            (0): Conv1d(512, 80, kernel_size=(5,), stride=(1,), padding=(2,), bias=False)
            (1): BatchNorm1d(80, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): Dropout(p=0.5, inplace=False)
          )
        )
      )
      (feat_out): Linear(in_features=1536, out_features=80, bias=False)
      (prob_out): Linear(in_features=1536, out_features=1, bias=True)
    )
    (taco2_loss): Tacotron2Loss(
      (l1_criterion): L1Loss()
      (mse_criterion): MSELoss()
      (bce_criterion): BCEWithLogitsLoss()
    )
    (attn_loss): GuidedAttentionLoss()
  )
)

Model summary:
    Class Name: ESPnetTTSModel
    Total Number of model parameters: 26.69 M
    Number of trainable parameters: 26.69 M (100.0%)
    Size: 106.75 MB
    Type: torch.float32
[ip-172-31-26-159] 2021-12-28 14:44:48,378 (abs_task:1161) INFO: Optimizer:
Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-06
    lr: 0.001
    weight_decay: 0.0
)
[ip-172-31-26-159] 2021-12-28 14:44:48,378 (abs_task:1162) INFO: Scheduler: None
[ip-172-31-26-159] 2021-12-28 14:44:48,378 (abs_task:1172) INFO: Saving the configuration in exp/tts_stats_raw_phn_none/logdir/stats.1/config.yaml
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/espnet2/bin/tts_train.py", line 22, in <module>
    main()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/espnet2/bin/tts_train.py", line 18, in main
    TTSTask.main(cmd=cmd)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/espnet2/tasks/abs_task.py", line 1019, in main
    cls.main_worker(args)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/espnet2/tasks/abs_task.py", line 1174, in main_worker
    yaml_no_alias_safe_dump(vars(args), f, indent=4, sort_keys=False)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/espnet2/utils/yaml_no_alias_safe_dump.py", line 13, in yaml_no_alias_safe_dump
    data, stream, allow_unicode=True, Dumper=NoAliasSafeDumper, **kwargs
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 200, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
TypeError: dump_all() got an unexpected keyword argument 'sort_keys'
# Accounting: time=3 threads=1
# Ended (code 1) at Tue Dec 28 14:44:48 UTC 2021, elapsed time 3 seconds
```

**Comment by kan-bayashi** [comment]
It seems PyYaml version is old.
Could you check your pyyaml version?

```bash
cd egs2/<recipe_name>/tts1
. ./path.sh
pip3 list | grep PyYAML

# Maybe upgrading the latest version solves this issue.
pip3 install -U pyyaml
```

Maybe upgrading the latest
