### ISSUE TITLE
Fine-tune asr model in ESPNET 1

### ISSUE THREAD

**Issue by sarasesar** [espnet/espnet#3989]
Hi,
I wanna fine-tune the asr model. When I run "bash run.sh --resume trained_model/snapshot.ep.50", at stage 4 an error appear in "exp/train_fa_pytorch_train/train.log".
The error is:

```Traceback (most recent call last):
File "/espnet/egs/dataset/asr1/../../../espnet/bin/asr_train.py", line 637, in <module>
main(sys.argv[1:])
File "/espnet/egs/dataset/asr1/../../../espnet/bin/asr_train.py", line 623, in main
train(args)
File "/espnet/espnet/asr/pytorch_backend/asr.py", line 650, in train
torch_resume(args.resume, trainer)
File "/espnet/espnet/asr/asr_utils.py", line 775, in torch_resume
trainer.updater.model.load_state_dict(snapshot_dict["model"])
KeyError: 'model'
```

also I give it model instead of snapshot but the error appears:
```KeyError: 'model' ```

I use common_voice recipe in espnet1.

What should I do?
Can anyone help me to solve it?

**Comment by Sreyan88** [comment]
Hi @sarasesar ,

I might be able to help you here. Can you please confirm the existing keys in the snapshot you are trying to load?
