### ISSUE TITLE
ASR training hangs in epoch 0, after few iterations

### ISSUE THREAD

**Issue by sameerkhurana10** [espnet/espnet#404]
Hi,

using
Espnet commit: 18ed8b0d76ae4bb32ce901152fdb35d1fc7484e4 - Tue Aug 28 10:56:46 2018 -0400
Pytorch: 0.4.1

Trying out librispeech. The training just stops (hangs) in epoch 0 after few iterations.

I am using pytorch backend with ngpus=4. There is no error in the log.

`tail -f train.log 
0           300         288.4       324.985        251.815                                                                                  0.343726                         456.825       1e-08       
     total [#.................................................]  3.62%
this epoch [###########################.......................] 54.35%
       300 iter, 0 epoch / 15 epochs
   0.69902 iters/sec. Estimated time to finish: 3:10:15.971187.`

Output of nvidia-smi. GPU utilization remains at zero after few iterations

<img width="643" alt="screen shot 2018-09-01 at 3 48 54 pm" src="https://user-images.githubusercontent.com/7698301/44949410-9cdfa100-adfe-11e8-92db-4633c0435432.png">

using cuda-8.0.61 and cudnn-6

Any comments on this?

**Comment by kan-bayashi** [comment]
Hi @sameerkhurana10. Thank you for your report.
Which python do you use?

And could you try to change following lines as follows?
https://github.com/espnet/espnet/blob/afe1fe80a51d41d229baf476ca88e3c1e1a74590/src/asr/asr_pytorch.py#L267-L272
```python
# Now
    train_iter = chainer.iterators.MultiprocessIterator(
        TransformDataset(train, converter.transform),
        batch_size=1, n_processes=1, n_prefetch=8, maxtasksperchild=20)
    valid_iter = chainer.iterators.SerialIterator(
        TransformDataset(valid, converter.transform),
        batch_size=1, repeat=False, shuffle=False)

# Change like this
    train_iter = chainer.iterators.SerialIterator(
        TransformDataset(valid, converter.transform),
        batch_size=1)
    valid_iter = chainer.iterators.SerialIterator(
        TransformDataset(valid, converter.transform),
        batch_size=1, repeat=False, shuffle=False)
```
I'm not sure, but I doubt that data has not been sent from iterator.

**Comment by sameerkhurana10** [comment]
thanks @kan-bayashi 

using python-3.6. 

With the suggested changes, the epoch 0 is finished successfully.

**Comment by kan-bayashi** [comment]
Thank you for your quick report.
If the training hangs with upper snippets, please let me know.
Maybe Multiprocessor has a bug if we use python3.

@jnishi, do you have any idea to fix it?

**Comment by jnishi** [comment]
Thanks for reporting.

@kan-bayashi I have not heard about bugs related to MultiprocessIterator and python3. There are only open issues about MultiprocessIterator with OpenCV.

https://github.com/chainer/chainer/issues/4412
https://docs.chainer.org/en/latest/tips.html?highlight=Multiprocess#my-training-process-gets-stuck-when-using-multiprocessiterator

Anyway, I will try to run with multi-GPU and python 3. If it stopped, I check it.

**Comment by kan-bayashi** [comment]
I also confirmed this phenomena.
It should be fixed.

**Comment by sameerkhurana10** [comment]
Hi,

After training for 12 epochs, I get the error:

`Exception in main training loop: [Errno 2] No such file or directory: train_trim/deltafalse/feats.24.ark`

But the file exists...

Something wrong with the iterator?

`Traceback (most recent call last):
  File "/data/sls/u/sameerk/zen/icassp2018/e2e_pt/tools/espnet/tools/venv/lib/python3.6/site-packages/chainer/training/trainer.py", line 306, in run
  File "/data/sls/u/sameerk/zen/icassp2018/e2e_pt/tools/espnet/tools/venv/lib/python3.6/site-packages/chainer/training/updaters/standard_updater.py", line 149, in update
  File "/data/sls/qcri/asr/sameer_v1/scratch/e2e_pt/tools/espnet/src/asr/asr_pytorch.py", line 118, in update_core
    batch = train_iter.next()
  File "/data/sls/u/sameerk/zen/icassp2018/e2e_pt/tools/espnet/tools/venv/lib/python3.6/site-packages/chainer/iterators/serial_iterator.py", line 57, in __next__
  File "/data/sls/u/sameerk/zen/icassp2018/e2e_pt/tools/espnet/tools/venv/lib/python3.6/site-packages/chainer/iterators/serial_iterator.py", line 57, in <listcomp>
  File "/data/sls/u/sameerk/zen/icassp2018/e2e_pt/tools/espnet/tools/venv/lib/python3.6/site-packages/chainer/dataset/dataset_mixin.py", line 67, in __getitem__
  File "/data/sls/u/sameerk/zen/icassp2018/e2e_pt/tools/espnet/tools/venv/lib/python3.6/site-packages/chainer/datasets/transform_dataset.py", line 52, in get_example
  File "/data/sls/qcri/asr/sameer_v1/scratch/e2e_pt/tools/espnet/src/asr/asr_pytorch.py", line 147, in transform
    return load_inputs_and_targets(item)
  File "/data/sls/qcri/asr/sameer_v1/scratch/e2e_pt/tools/espnet/src/asr/asr_utils.py", line 76, in load_inputs_and_targets
    xs = [kaldi_io_py.read_mat(b[1]['input'][0]['feat']) for b in batch]
  File "/data/sls/qcri/asr/sameer_v1/scratch/e2e_pt/tools/espnet/src/asr/asr_utils.py", line 76, in <listcomp>
    xs = [kaldi_io_py.read_mat(b[1]['input'][0]['feat']) for b in batch]
  File "/data/sls/qcri/asr/sameer_v1/scratch/e2e_pt/tools/espnet/src/utils/kaldi_io_py.py", line 364, in read_mat
    fd = open_or_fd(file_or_fd)
  File "/data/sls/qcri/asr/sameer_v1/scratch/e2e_pt/tools/espnet/src/utils/kaldi_io_py.py", line 60, in open_or_fd
    fd = open(file, mode)
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/data/sls/qcri/asr/sameer_v1/scratch/e2e_pt/tools/espnet/egs/mgb2/asr1/../../../src/bin/asr_train.py", line 194, in <module>
    main()
  File "/data/sls/qcri/asr/sameer_v1/scratch/e2e_pt/tools/espnet/egs/mgb2/asr1/../../../src/bin/asr_train.py", line 188, in main
    train(args)
  File "/data/sls/qcri/asr/sameer_v1/scratch/e2e_pt/tools/espnet/src/asr/asr_pytorch.py", line 361, in train
    trainer.run()
  File "/data/sls/u/sameerk/zen/icassp2018/e2e_pt/tools/espnet/tools/venv/lib/python3.6/site-packages/chainer/training/trainer.py", line 320, in run
  File "/data/sls/u/sameerk/zen/icassp2018/e2e_pt/tools/espnet/tools/venv/lib/python3.6/site-packages/six.py", line 693, in reraise
  File "/data/sls/u/sameerk/zen/icassp2018/e2e_pt/tools/espnet/tools/venv/lib/python3.6/site-packages/chainer/training/trainer.py", line 306, in run
  File "/data/sls/u/sameerk/zen/icassp2018/e2e_pt/tools/espnet/tools/venv/lib/python3.6/site-packages/chainer/training/updaters/standard_updater.py", line 149, in update
  File "/data/sls/qcri/asr/sameer_v1/scratch/e2e_pt/tools/espnet/src/asr/asr_pytorch.py", line 118, in update_core
    batch = train_iter.next()`

**Comment by oadams** [comment]
I can confirm that: (a) this bug is not python3 specific, I have run into the same issue with python2; (b) Replacing MultiprocessIterator with SerialIterator fixes the problem for me.

**Comment by sw005320** [comment]
We just started to use SerialIterator as a default (#424)

**Comment by kobenaxie** [comment]
@creatorscan thanks ~

**Comment by bobchennan** [comment]
same problem still. Considering re-write IO part with pytorch dataloader.

**Comment by sw005320** [comment]
@jnishi, could you take a look at it again?

**Comment by kan-bayashi** [comment]
I met the same problem.
`MultiProcessIterator` is a buggy, I agree with @bobchennan.
