### ISSUE TITLE
An error occurred when I ran stage 4 on the Aishell dataset.

### ISSUE THREAD

**Issue by CrazyTaobean** [espnet/espnet#4046]
**Describe the bug**
This error occurred when I ran stage 4 on the Aishell dataset.

**Basic environments:**
 - OS information: Linux 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64
 - python version: 3.7
 - espnet version: espnet 0.10.6a1
 - pytorch version pytorch 1.10.1+cu102
 

the train.log is show below:
`[J     total [..................................................]  1.97%
this epoch [#################################################.] 98.58%
      1800 iter, 0 epoch / 50 epochs
   0.65912 iters/sec. Estimated time to finish: 1 day, 13:43:06.996285.
[4A[J/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb/lib/python3.7/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb/lib/python3.7/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
/home/SuXiangDong/GPU20StuA/zdb/espnet/espnet/nets/pytorch_backend/transformer/plot.py:43: MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "dpi" which is no longer supported as of 3.3 and will become an error two minor releases later
  fig.tight_layout()
Exception in main training loop: The number of FixedLocator locations (14), usually from a call to set_ticks, does not match the number of ticklabels (15).
Traceback (most recent call last):
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb/lib/python3.7/site-packages/chainer/training/trainer.py", line 319, in run
    entry.extension(self)
  File "/home/SuXiangDong/GPU20StuA/zdb/espnet/espnet/nets/pytorch_backend/transformer/plot.py", line 136, in __call__
    self.plotfn(self.data_dict, uttid_list, attn_dict, self.outdir, suffix, savefig)
  File "/home/SuXiangDong/GPU20StuA/zdb/espnet/espnet/nets/pytorch_backend/transformer/plot.py", line 131, in plotfn
    plot_multi_head_attention(*args, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/zdb/espnet/espnet/nets/pytorch_backend/transformer/plot.py", line 120, in plot_multi_head_attention
    fig = _plot_and_save_attention(att_w, filename, xtokens, ytokens)
  File "/home/SuXiangDong/GPU20StuA/zdb/espnet/espnet/nets/pytorch_backend/transformer/plot.py", line 38, in _plot_and_save_attention
    ax.set_xticklabels(xtokens + [""], rotation=40)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 63, in wrapper
    return get_method(self)(*args, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 451, in wrapper
    return func(*args, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb/lib/python3.7/site-packages/matplotlib/axis.py", line 1796, in _set_ticklabels
    return self.set_ticklabels(labels, minor=minor, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb/lib/python3.7/site-packages/matplotlib/axis.py", line 1718, in set_ticklabels
    "The number of FixedLocator locations"
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/home/SuXiangDong/GPU20StuA/zdb/espnet/egs/aishell/asr1/../../../espnet/bin/asr_train.py", line 639, in <module>
    main(sys.argv[1:])
  File "/home/SuXiangDong/GPU20StuA/zdb/espnet/egs/aishell/asr1/../../../espnet/bin/asr_train.py", line 625, in main
    train(args)
  File "/home/SuXiangDong/GPU20StuA/zdb/espnet/espnet/asr/pytorch_backend/asr.py", line 965, in train
    trainer.run()
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb/lib/python3.7/site-packages/chainer/training/trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb/lib/python3.7/site-packages/chainer/training/trainer.py", line 319, in run
    entry.extension(self)
  File "/home/SuXiangDong/GPU20StuA/zdb/espnet/espnet/nets/pytorch_backend/transformer/plot.py", line 136, in __call__
    self.plotfn(self.data_dict, uttid_list, attn_dict, self.outdir, suffix, savefig)
  File "/home/SuXiangDong/GPU20StuA/zdb/espnet/espnet/nets/pytorch_backend/transformer/plot.py", line 131, in plotfn
    plot_multi_head_attention(*args, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/zdb/espnet/espnet/nets/pytorch_backend/transformer/plot.py", line 120, in plot_multi_head_attention
    fig = _plot_and_save_attention(att_w, filename, xtokens, ytokens)
  File "/home/SuXiangDong/GPU20StuA/zdb/espnet/espnet/nets/pytorch_backend/transformer/plot.py", line 38, in _plot_and_save_attention
    ax.set_xticklabels(xtokens + [""], rotation=40)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 63, in wrapper
    return get_method(self)(*args, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 451, in wrapper
    return func(*args, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb/lib/python3.7/site-packages/matplotlib/axis.py", line 1796, in _set_ticklabels
    return self.set_ticklabels(labels, minor=minor, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb/lib/python3.7/site-packages/matplotlib/axis.py", line 1718, in set_ticklabels
    "The number of FixedLocator locations"
ValueError: The number of FixedLocator locations (14), usually from a call to set_ticks, does not match the number of ticklabels (15).
# Accounting: time=2982 threads=1
# Ended (code 1) at Tue Feb  8 13:55:14 CST 2022, elapsed time 2982 seconds`

**Task information:**
 - Task: ASR
 - Recipe: aishell
 - ESPnet1 or ESPnet2

**Comment by sw005320** [comment]
It seems that matplotlib causes an error.
According to https://github.com/espnet/espnet/blob/master/setup.py#L42, we use  "matplotlib==3.1.0", while the error message says " which is no longer supported as of 3.3".
So, can you check your matplotlib installation?

**Comment by CrazyTaobean** [comment]
> It seems that matplotlib causes an error. According to https://github.com/espnet/espnet/blob/master/setup.py#L42, we use "matplotlib==3.1.0", while the error message says " which is no longer supported as of 3.3". So, can you check your matplotlib installation?

It does work. This spend me almost whole day, tks a lot!!
