### ISSUE TITLE
How to train conformer-transducer asr with espnet2

### ISSUE THREAD

**Issue by wyunj** [espnet/espnet#4054]
Hi,
I'm using ESPnet v0.10.5 and I want to train asr conformer-transducer or RNN-T with espnet2. Can someone guide me to the appropriate  recipe to start for this? How can I configure or do extra implement? 
Thanks in advance!

**Comment by wyunj** [comment]
Thanks, and I train the asr conformer-transducer as #3943 with aishell recipe (espnet2), but got this:
2022-02-20 08:34:19,177 (trainer:675) INFO: 50epoch:train:34695-36520batch: iter_time=1.669e-04, forward_time=0.080, loss_transducer=0.050, loss=0.050, backward_time=0.066, optim_step_time=0.096, optim0_lr0=9.932e-04, train_time=6.430
2022-02-20 08:36:26,031 (trainer:334) INFO: 50epoch results: [train] iter_time=1.554e-04, forward_time=0.080, loss_transducer=0.050, loss=0.050, backward_time=0.067, optim_step_time=0.092, optim0_lr0=9.980e-04, train_time=6.423, time=2 hours, 2 minutes and 16.41 seconds, total_count=1826950, gpu_max_cached_mem_GB=9.574, [valid] loss_transducer=5.344, cer_transducer=nan, wer_transducer=nan, loss=5.344, time=1 minute and 32.83 seconds, total_count=72500, gpu_max_cached_mem_GB=9.574, [att_plot] time=28.48 seconds, total_count=0, gpu_max_cached_mem_GB=9.574
2022-02-20 08:36:36,249 (trainer:380) INFO: There are no improvements in this epoch
2022-02-20 08:36:36,310 (trainer:435) INFO: The model files were removed: exp/asr_train_rnnt_conformer_raw_zh_char_sp/49epoch.pth
2022-02-20 08:36:36,310 (trainer:453) INFO: The training was finished at 50 epochs 
2022-02-20 08:36:36,346 (average_nbest_models:64) INFO: Averaging 10best models: criterion="valid.loss": exp/asr_train_rnnt_conformer_raw_zh_char_sp/valid.loss.ave_10best.pth
Traceback (most recent call last):
  File "/Share/lli/espnet2/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Share/lli/espnet2/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Share/lli/espnet2/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/Share/lli/espnet2/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/Share/lli/espnet2/espnet2/tasks/abs_task.py", line 1019, in main
    cls.main_worker(args)
  File "/Share/lli/espnet2/espnet2/tasks/abs_task.py", line 1326, in main_worker
    if wandb.run:
AttributeError: 'NoneType' object has no attribute 'run'
# Accounting: time=401864 threads=1
# Ended (code 1) at Sun Feb 20 08:37:15 CST 2022, elapsed time 401864 seconds
I change ngpu=1
Can someone help me?

**Comment by gowtham1997** [comment]
I tried to use this recipe with librispeech and librispeech_100 and in both cases, I am getting ` cer_transducer=nan, wer_transducer=nan`  in the first few epochs but the loss is decreasing.

Is this normal? @sw005320 

```
[scn21-mn] 2022-04-24 21:53:54,379 (trainer:334) INFO: 1epoch results: [train] iter_time=0.003, forward_time=0.071, loss_transducer=16.965, loss=16.965, backward_time=0.048, optim_step_time=0.036, optim0_lr0=2.277e-05, train_time=4.292, time=54 minutes and 6.72 seconds, total_count=24204, gpu_max_cached_mem_GB=36.082, [valid] loss_transducer=150.716, **cer_transducer=nan, wer_transducer=nan**, loss=150.716, time=37.73 seconds, total_count=902, gpu_max_cached_mem_GB=36.082, [att_plot] time=44.17 seconds, total_count=0, gpu_max_cached_mem_GB=36.082
[scn21-mn] 2022-04-24 21:53:59,085 (trainer:382) INFO: The best model has been updated: valid.loss
[scn21-mn] 2022-04-24 21:53:59,085 (trainer:268) INFO: 2/100epoch started. Estimated time to finish: 3 days, 19 hours and 40 minutes

....

[scn21-mn] 2022-04-24 22:40:29,784 (trainer:334) INFO: 2epoch results: [train] iter_time=0.002, forward_time=0.056, loss_transducer=7.639, loss=7.639, backward_time=0.043, optim_step_time=0.035, optim0_lr0=6.813e-05, train_time=3.595, time=45 minutes and 19.65 seconds, total_count=48408, gpu_max_cached_mem_GB=36.082, [valid] loss_transducer=115.060, **cer_transducer=nan, wer_transducer=nan,** loss=115.060, time=35.24 seconds, total_count=1804, gpu_max_cached_mem_GB=36.082, [att_plot] time=35.67 seconds, total_count=0, gpu_max_cached_mem_GB=36.082
[scn21-mn] 2022-04-24 22:40:34,246 (trainer:382) INFO: The best model has been updated: valid.loss
[scn21-mn] 2022-04-24 22:40:34,247 (trainer:268) INFO: 3/100epoch started. Estimated time to finish: 3 days, 11 hours and 25 minutes
```

^ first 2 epochs logs for librispeech_100

**Comment by gowtham1997** [comment]
^ @b-flo / @kan-bayashi Do you think this is a known issue?  (cer and wer of transducer being nan?).

I also get loss of 0 or `src/binding.cpp:151: unsupported data type` (related [issue](https://github.com/HawkAaron/warp-transducer/issues/92) at warp-transducer repo) when I try to use rnnt with fp16 (--use_amp true in asr.sh step 10)

Please let me know if I'm missing some documentation regarding these issues?

**Comment by b-flo** [comment]
Hi,

> Do you think this is a known issue? (cer and wer of transducer being nan?).

If I'm not mistaken (didn't use this version in a while) `nan` is only used when CER/WER reporting is disabled? Otherwise, it should display a float value (<= 1.0). 

> I also get loss of 0 or src/binding.cpp:151: unsupported data type (related https://github.com/HawkAaron/warp-transducer/issues/92 at warp-transducer repo) when I try to use rnnt with fp16 (--use_amp true in asr.sh step 10)

This issue is known and on my TODO but it's not a priority right now. Btw, please do not open or link an issue from ESPnet to Mingkun's warp-transducer:

> **Important: If you encounter any issue related to Transducer loss, please open an issue in [our fork of warp-transducer](https://github.com/b-flo/warp-transducer).**
> (From our [ESPnet1 documentation](https://espnet.github.io/espnet/tutorial.html#transducer)).

The original repo is not maintained anymore and our version has some minor differences.

**Comment by gowtham1997** [comment]
> If I'm not mistaken (didn't use this version in a while) nan is only used when CER/WER reporting is disabled?
I guess I missed adding `--report-cer --report-wer` flags when running asr.sh.

I will try it out
Thanks
