### ISSUE TITLE
An error occurred while training fs2

### ISSUE THREAD

**Issue by unparalleled-ysj** [espnet/espnet#4113]
@kan-bayashi   I use MFA to extract durations to train fs2, and the error message is as follows. Can you tell me which aspect of the problem is this?  thank you！

Traceback (most recent call last):
  File "/root/anaconda3/envs/espnet/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/espnet/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/work/ysj/espnet/espnet2/tasks/abs_task.py", line 1323, in main_worker
    distributed_option=distributed_option,
  File "/work/ysj/espnet/espnet2/train/trainer.py", line 290, ### in run
    distributed_option=distributed_option,
  File "/work/ysj/espnet/espnet2/train/trainer.py", line 515, in train_one_epoch
    retval = model(**batch)
  File "/root/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/root/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/work/ysj/espnet/espnet2/tts/espnet_model.py", line 152, in forward
    return self.tts(**batch)
  File "/root/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/work/ysj/espnet/espnet2/tts/fastspeech2/fastspeech2.py", line 559, in forward
    is_inference=False,
  File "/work/ysj/espnet/espnet2/tts/fastspeech2/fastspeech2.py", line 686, in _forward
    zs, _ = self.decoder(hs, h_masks)  # (B, T_feats, adim)
  File "/root/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/work/ysj/espnet/espnet/nets/pytorch_backend/conformer/encoder.py", line 258, in forward
    xs, masks = self.encoders(xs, masks)
  File "/root/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/work/ysj/espnet/espnet/nets/pytorch_backend/transformer/repeat.py", line 18, in forward
    args = m(*args)
  File "/root/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/work/ysj/espnet/espnet/nets/pytorch_backend/conformer/encoder_layer.py", line 140, in forward
    x_att = self.self_attn(x_q, x, x, pos_emb, mask)
  File "/root/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/work/ysj/espnet/espnet/nets/pytorch_backend/transformer/attention.py", line 209, in forward
    return self.forward_attention(v, scores, mask)
  File "/work/ysj/espnet/espnet/nets/pytorch_backend/transformer/attention.py", line 83, in forward_attention
    scores = scores.masked_fill(mask, min_value)
RuntimeError: The size of tensor a (565) must match the size of tensor b (566) at non-singleton dimension 3

**Comment by kan-bayashi** [comment]
Sorry, I miss your post.
Maybe this is caused by eos symbol, which is added in the forward.
You can add 0 at the last of each line in durations file.

**Comment by unparalleled-ysj** [comment]
> Sorry, I miss your post.
> Maybe this is caused by eos symbol, which is added in the forward.
> You can add 0 at the last of each line in durations file.

Thank you for your answer, it is a case where my sum(duration) and feat_length are not equal.
