### ISSUE TITLE
In librispeech recipe i stop in stage 4 but i can not resume.

### ISSUE THREAD

**Issue by CrazyTaobean** [espnet/espnet#4135]
**Describe the bug**
I used CTRL + C to exit the training while I was training the network in stage 4, but when I tried to continue training the network, I got an error.
 

**Error logs**
I key in 
`bash run.sh --resume /home/SuXiangDong/GPU20StuA/zdb/espnet/egs/librispeech/asr1/exp/train_rnnlm_pytorch_lm_unigram5000_ngpu4/snapshot.ep.17 --ngpu 4 --stage 4`

the snapshot is in here :
![image](https://user-images.githubusercontent.com/37605608/156884667-2559db36-c285-4a89-9bb5-72f643aa119b.png)

And the error log output in **"/home/SuXiangDong/GPU20StuA/zdb/espnet/egs/librispeech/asr1/exp/train_960_pytorch_train_specaug/train.log"**

 asr_train.py --config conf/train.yaml --preprocess-conf conf/specaug.yaml --ngpu 4 --backend pytorch --outdir exp/train_960_pytorch_train_specaug/results --tensorboard-dir tensorboard/train_960_pytorch_train_specaug --debugmode 1 --dict data/lang_char/train_960_unigram5000_units.txt --debugdir exp/train_960_pytorch_train_specaug --minibatches 0 --verbose 0 --resume /home/SuXiangDong/GPU20StuA/zdb/espnet/egs/librispeech/asr1/exp/train_rnnlm_pytorch_lm_unigram5000_ngpu4/snapshot.ep.16 --train-json dump/train_sp/deltafalse/data_unigram5000.json --valid-json dump/dev/deltafalse/data_unigram5000.json 
 Started at Sat Mar  5 21:00:22 CST 2022

Accounting: time=25 threads=1
Ended (code 1) at Sat Mar  5 21:00:23 CST 2022, elapsed time 25 seconds
2022-03-05 21:00:25,695 (asr_train:563) WARNING: Skip DEBUG/INFO messages
2022-03-05 21:00:25,932 (ctc:38) WARNING: CTC was set to builtin due to PyTorch version.
2022-03-05 21:00:26,540 (argument:79) WARNING: Using legacy_rel_pos and it will be deprecated in the future.
2022-03-05 21:00:26,541 (argument:84) WARNING: Using legacy_rel_selfattn and it will be deprecated in the future.
2022-03-05 21:00:27,185 (asr:471) WARNING: batch size is automatically increased (64 -> 256)
2022-03-05 21:00:30,432 (asr:499) WARNING: num. model params: 116,412,180 (num. trained: 116,412,180 (100.0%))
2022-03-05 21:00:50,302 (io_utils:59) WARNING: [Experimental feature] Some preprocessing will be done for the mini-batch creation using Transformation(
    0: TimeWarp(max_time_warp=5, inplace=True, mode=PIL)
    1: FreqMask(F=30, n_mask=2, replace_with_zero=False, inplace=True)
    2: TimeMask(T=40, n_mask=2, replace_with_zero=False, inplace=True))
2022-03-05 21:00:50,305 (io_utils:59) WARNING: [Experimental feature] Some preprocessing will be done for the mini-batch creation using Transformation(
    0: TimeWarp(max_time_warp=5, inplace=True, mode=PIL)
    1: FreqMask(F=30, n_mask=2, replace_with_zero=False, inplace=True)
    2: TimeMask(T=40, n_mask=2, replace_with_zero=False, inplace=True))
Traceback (most recent call last):
  File "/home/SuXiangDong/GPU20StuA/zdb/espnet/egs/librispeech/asr1/../../../espnet/bin/asr_train.py", line 639, in <module>
    main(sys.argv[1:])
  File "/home/SuXiangDong/GPU20StuA/zdb/espnet/egs/librispeech/asr1/../../../espnet/bin/asr_train.py", line 625, in main
    train(args)
  File "/home/SuXiangDong/GPU20StuA/zdb/espnet/espnet/asr/pytorch_backend/asr.py", line 667, in train
    torch_resume(args.resume, trainer)
  File "/home/SuXiangDong/GPU20StuA/zdb/espnet/espnet/asr/asr_utils.py", line 798, in torch_resume
    d.load(trainer)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb/lib/python3.7/site-packages/chainer/serializer.py", line 83, in load
    obj.serialize(self)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb/lib/python3.7/site-packages/chainer/training/trainer.py", line 361, in serialize
    self.updater.serialize(serializer['updater'])
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb/lib/python3.7/site-packages/chainer/training/updaters/standard_updater.py", line 199, in serialize
    iterator.serialize(serializer['iterator:' + name])
  File "/home/SuXiangDong/GPU20StuA/zdb/espnet/espnet/utils/dataset.py", line 81, in serialize
    current_position = serializer("current_position", self.current_position)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb/lib/python3.7/site-packages/chainer/serializers/npz.py", line 175, in __call__
    dataset = self.npz[key]
KeyError: 'updater/iterator:main/current_position'
Accounting: time=41 threads=1
Ended (code 1) at Sat Mar  5 21:01:03 CST 2022, elapsed time 41 seconds

**Comment by CrazyTaobean** [comment]
i found bug occur in the line of 798 in asr_utils.py.
发生异常: AttributeError
'str' object has no attribute 'serialize'
![image](https://user-images.githubusercontent.com/37605608/156885781-4e88c35d-2f56-4123-b09c-d083bc9c752b.png)

**Comment by CrazyTaobean** [comment]
i should start from stage 3, my bad..
