### ISSUE TITLE
k2 with the latest espnet(version mismatch)

### ISSUE THREAD

**Issue by arunbaby0** [espnet/espnet#4166]
The default conda installer is using an old version of k2 that is not being supported.
while installing, I am getting the following error:
`[WARNING] k2=1.10.dev20211103 doesn't provide conda package for pytorch=1.10.1. Skip k2-installation
`

So, I removed this version and installed the latest k2 version. It looks like some API changes happened from k2 side and the decode is breaking.

`Traceback (most recent call last):
  File "/miniconda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/miniconda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/espnet2/espnet2/bin/asr_inference_k2.py", line 767, in <module>
    main()
  File "/opt/espnet2/espnet2/bin/asr_inference_k2.py", line 763, in main
    inference(**kwargs)
  File "/opt/espnet2/espnet2/bin/asr_inference_k2.py", line 574, in inference
    results = speech2text(batch)
  File "/miniconda/envs/espnet/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/opt/espnet2/espnet2/bin/asr_inference_k2.py", line 374, in __call__
    nnlm_nll, x_lengths = self.lm.batchify_nll(
AttributeError: 'k2Speech2Text' object has no attribute 'lm'
`

Which is the correct k2 version to be used along with espnet version 0.10.6?

**Comment by sw005320** [comment]
I see.
Please use the older PyTorch version.
But thanks for pointing out the interface issue for the latest k2.
We will fix this in the near future.
