### ISSUE TITLE
data2vec integration

### ISSUE THREAD

**Issue by arunbaby0** [espnet/espnet#4167]
Any short-term plans to integrate data2vec models into the toolkit?
https://github.com/pytorch/fairseq/tree/main/examples/data2vec

**Comment by sw005320** [comment]
If s3prl supports it, we can support it. @leo19941227
We could support it directly through fairseq if we have more requests. @simpleoier

**Comment by simpleoier** [comment]
I asked @leo19941227 before, s3prl had a plan to integrate it.
Definitely, we can support it in ESPnet as well. I'll work on it as we support hubert and wav2vec2.

**Comment by leo19941227** [comment]
Hi @simpleoier and @sw005320 

Yes we are running some exps to verify whether we port it correctly, so it will be available soon in S3PRL.

**Comment by xiyue961** [comment]
I tried to integrate data2vec in ESPnet. It now works for single-GPU training. But when training on multiple GPUs, I got the following errors:
 
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/root/miniconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/root/espnet/espnet2/tasks/abs_task.py", line 1291, in main_worker
    distributed_option=distributed_option,
  File "/root/espnet/espnet2/train/trainer.py", line 239, in run
    find_unused_parameters=trainer_options.unused_parameters,
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 580, in __init__
    self._sync_params_and_buffers(authoritative_rank=0)
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 598, in _sync_params_and_buffers
    module_states, self.broadcast_bucket_size, authoritative_rank
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 1335, in _distributed_broadcast_coalesced
    self.process_group, tensors, buffer_size, authoritative_rank
TypeError: _broadcast_coalesced(): incompatible function arguments. The following argument types are supported:
    1. (process_group: torch._C._distributed_c10d.ProcessGroup, tensors: List[at::Tensor], buffer_size: int, src: int = 0) -> None

Invoked with: <torch._C._distributed_c10d.ProcessGroupNCCL object at 0x7eff36eda5a8>, [tensor([ 3.5248e-02,  7.0038e-03,  2.0645e-02,  5.5176e-02, -4.5357e-03,
         3.9581e-02,  1.2352e-02, -9.6283e-03,  9.3323e-02,  6.1218e-02,

Any suggestions for solving this error?

**Comment by simpleoier** [comment]
Cool. Can you also share some of your experience / resuts or whatever related to the usage of data2vec?

Trying to understand some context. Did you freeze the data2vec parameters? If yes, did you have this [line](https://github.com/espnet/espnet/blob/16f2cd333a994e49fc8fb69b32a1894f87e51a13/egs2/librispeech/asr1/conf/tuning/train_asr_conformer7_hubert_ll60k_large.yaml#L13) in your config?
