### ISSUE TITLE
multi speaker VITS training error (Multi speaker with SID 22.05 khz case)

### ISSUE THREAD

**Issue by heeyounglee** [espnet/espnet#4195]
I followed the VITS training recipe here:
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#vits-training
LJSpeech training work ok, but VCTK training fails.

**Basic environments:**
- OS information: Linux 5.13.0-37-generic #42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64
- python version: `3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0]`
- espnet version: `espnet 0.10.3`
- pytorch version: `pytorch 1.10.1`
- Git hash: `1991a25855821b8b61d775681aa0cdfd6161bbc8`
  - Commit date: `Mon Mar 21 22:19:19 2022 +0800`

**Environments from `torch.utils.collect_env`:**
e.g.,
```
Collecting environment information...
PyTorch version: 1.10.1
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.13.0-37-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 470.103.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.10.1
[pip3] torch-complex==0.4.3
[pip3] torch-optimizer==0.3.0
[pip3] torchaudio==0.10.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.21.2           py39h20f2e39_0  
[conda] numpy-base                1.21.2           py39h79a1101_0  
[conda] pytorch                   1.10.1          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.1                    pypi_0    pypi
[conda] torch-complex             0.4.3                    pypi_0    pypi
[conda] torch-optimizer           0.3.0                    pypi_0    pypi
[conda] torchaudio                0.10.1               py39_cu113    pytorch
```

**Task information:**
 - Task: TTS
 - Recipe: VCTK
 - ESPnet2

**To Reproduce**
```
1. cd egs2/vctk/tts1
2. run.sh --stage 1 --stop-stage 1
3. run.sh --stage 2 --stop-stage 4 \
    --use_sid true \
    --ngpu 1 \
    --fs 22050 \
    --n_fft 1024 \
    --n_shift 256 \
    --win_length null \
    --dumpdir dump/22k \
    --expdir exp/22k \
    --tts_task gan_tts \
    --feats_extract linear_spectrogram \
    --feats_normalize none \
    --train_config ./conf/tuning/train_multi_spk_vits.yaml \
    --inference_config ./conf/tuning/decode_vits.yaml \
    --inference_model latest.pth
4. run.sh --stage 5 --stop-stage 5 \
    --use_sid true \
    --ngpu 1 \
    --fs 22050 \
    --n_fft 1024 \
    --n_shift 256 \
    --win_length null \
    --dumpdir dump/22k \
    --expdir exp/22k \
    --tts_task gan_tts \
    --feats_extract linear_spectrogram \
    --feats_normalize none \
    --train_config ./conf/tuning/train_multi_spk_vits.yaml \
    --inference_config ./conf/tuning/decode_vits.yaml \
    --inference_model latest.pth --nj 12
5. run.sh --stage 6 --stop-stage 6 \
    --use_sid true \
    --ngpu 1 \
    --fs 22050 \
    --n_fft 1024 \
    --n_shift 256 \
    --win_length null \
    --dumpdir dump/22k \
    --expdir exp/22k \
    --tts_task gan_tts \
    --feats_extract linear_spectrogram \
    --feats_normalize none \
    --train_config ./conf/tuning/train_multi_spk_vits.yaml \
    --inference_config ./conf/tuning/decode_vits.yaml \
    --inference_model latest.pth
6. error log: exp/22k/tts_train_multi_spk_vits_raw_phn_tacotron_g2p_en_no_space/train.log
```

**Error logs**
```
[220-5800] 2022-03-23 17:27:31,741 (trainer:273) INFO: 1/1000epoch started
/home/heeyoung/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/espnet2/layers/stft.py:119: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  olens = (ilens - self.win_length) // self.hop_length + 1
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
/home/heeyoung/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/espnet2/layers/stft.py:119: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  olens = (ilens - self.win_length) // self.hop_length + 1
[220-5800] 2022-03-23 17:28:03,211 (gan_trainer:306) INFO: 1epoch:train:1-50batch: iter_time=0.015, discriminator_forward_time=0.169, discriminator_loss=3.021, discriminator_real_loss=1.763, discriminator_fake_loss=1.258, discriminator_backward_time=0.031, discriminator_optim_step_time=0.066, optim1_lr0=2.000e-04, discriminator_train_time=0.296, generator_forward_time=0.050, generator_loss=407.385, generator_mel_loss=61.174, generator_kl_loss=340.818, generator_dur_loss=1.874, generator_adv_loss=2.083, generator_feat_match_loss=1.437, generator_backward_time=0.213, generator_optim_step_time=0.044, optim0_lr0=2.000e-04, generator_train_time=0.312, train_time=0.628
[220-5800] 2022-03-23 17:28:32,558 (gan_trainer:306) INFO: 1epoch:train:51-100batch: iter_time=6.711e-05, discriminator_forward_time=0.144, discriminator_loss=2.680, discriminator_real_loss=1.509, discriminator_fake_loss=1.171, discriminator_backward_time=0.019, discriminator_optim_step_time=0.075, optim1_lr0=2.000e-04, discriminator_train_time=0.270, generator_forward_time=0.051, generator_loss=192.259, generator_mel_loss=55.928, generator_kl_loss=128.778, generator_dur_loss=1.825, generator_adv_loss=2.451, generator_feat_match_loss=3.276, generator_backward_time=0.216, generator_optim_step_time=0.043, optim0_lr0=2.000e-04, generator_train_time=0.316, train_time=0.587
[220-5800] 2022-03-23 17:29:01,347 (gan_trainer:306) INFO: 1epoch:train:101-150batch: iter_time=6.310e-05, discriminator_forward_time=0.140, discriminator_loss=2.514, discriminator_real_loss=1.531, discriminator_fake_loss=0.983, discriminator_backward_time=0.018, discriminator_optim_step_time=0.074, optim1_lr0=2.000e-04, discriminator_train_time=0.264, generator_forward_time=0.051, generator_loss=125.706, generator_mel_loss=53.740, generator_kl_loss=63.997, generator_dur_loss=1.743, generator_adv_loss=2.613, generator_feat_match_loss=3.614, generator_backward_time=0.211, generator_optim_step_time=0.043, optim0_lr0=2.000e-04, generator_train_time=0.310, train_time=0.576
Traceback (most recent call last):
  File "/home/heeyoung/espnet/tools/anaconda/envs/espnet/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/heeyoung/espnet/tools/anaconda/envs/espnet/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/heeyoung/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/espnet2/bin/gan_tts_train.py", line 22, in <module>
    main()
  File "/home/heeyoung/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/espnet2/bin/gan_tts_train.py", line 18, in main
    GANTTSTask.main(cmd=cmd)
  File "/home/heeyoung/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/espnet2/tasks/abs_task.py", line 994, in main
    cls.main_worker(args)
  File "/home/heeyoung/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/espnet2/tasks/abs_task.py", line 1283, in main_worker
    cls.trainer.run(
  File "/home/heeyoung/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/espnet2/train/trainer.py", line 279, in run
    all_steps_are_invalid = cls.train_one_epoch(
  File "/home/heeyoung/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/espnet2/train/gan_trainer.py", line 161, in train_one_epoch
    retval = model(forward_generator=turn == "generator", **batch)
  File "/home/heeyoung/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/heeyoung/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/espnet2/gan_tts/espnet_model.py", line 162, in forward
    return self.tts(**batch)
  File "/home/heeyoung/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/heeyoung/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/espnet2/gan_tts/vits/vits.py", line 315, in forward
    return self._forward_discrminator(
  File "/home/heeyoung/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/espnet2/gan_tts/vits/vits.py", line 478, in _forward_discrminator
    outs = self.generator(
  File "/home/heeyoung/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/heeyoung/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/espnet2/gan_tts/vits/generator.py", line 395, in forward
    z_segments, z_start_idxs = get_random_segments(
  File "/home/heeyoung/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/espnet2/gan_tts/utils/get_random_segments.py", line 33, in get_random_segments
    segments = get_segments(x, start_idxs, segment_size)
  File "/home/heeyoung/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/espnet2/gan_tts/utils/get_random_segments.py", line 56, in get_segments
    segments[i] = x[i, :, start_idx : start_idx + segment_size]
RuntimeError: The expanded size of the tensor (32) must match the existing size (0) at non-singleton dimension 1.  Target sizes: [192, 32].  Tensor sizes: [192, 0]
# Accounting: time=100 threads=1
# Ended (code 1) at Wed Mar 23 17:29:06 PDT 2022, elapsed time 100 seconds

```

**Comment by mindmapper15** [comment]
Check your dataset and make sure that all utterances in the dataset is longer than segment_size

**Comment by kan-bayashi** [comment]
As @mindmapper15 said, your training data included shorter uttarances, which is less than segment_size.
You can filter out the short utterance with `--min_wav_duration` option.
Please check the command as an example in the following link.
https://github.com/espnet/espnet/tree/master/egs2/vctk/tts1#vctk_tts_train_multi_spk_vits_raw_phn_tacotron_g2p_en_no_space_traintotal_countave

**Comment by heeyounglee** [comment]
It works, thank you!
