### ISSUE TITLE
Runtime Error in inference stage on ASR Task.

### ISSUE THREAD

**Issue by lin-nerd** [espnet/espnet#4276]
I have trained the HuBERT+Streaming Model in ESPnet2, and I have the following problems during the inference stage. I would like to ask if anyone has encountered this issue？
How to solve this problem.

```
Using cache found in ./hub/s3prl_cache/4a54d64fa42b41e39db994c958d8107d5785a100f38c6eba680b6a3cc79babb3
for https://dl.fbaipublicfiles.com/hubert/hubert_large_ll60k.pt
Traceback (most recent call last):
  File "/home/ec5017b/.conda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ec5017b/.conda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ec5017b/media-lab/espnet_ha/espnet/espnet2/bin/asr_inference_streaming.py", line 585, in <module>
    main()
  File "/home/ec5017b/media-lab/espnet_ha/espnet/espnet2/bin/asr_inference_streaming.py", line 581, in main
    inference(**kwargs)
  File "/home/ec5017b/media-lab/espnet_ha/espnet/espnet2/bin/asr_inference_streaming.py", line 417, in inference
    speech2text(
  File "/home/ec5017b/.conda/envs/espnet/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/ec5017b/media-lab/espnet_ha/espnet/espnet2/bin/asr_inference_streaming.py", line 265, in __call__
    feats, feats_lengths, self.frontend_states = self.apply_frontend(
  File "/home/ec5017b/media-lab/espnet_ha/espnet/espnet2/bin/asr_inference_streaming.py", line 235, in apply_frontend
    feats = feats.narrow(1, 0, feats.size(1) - 2)
RuntimeError: start (0) + length (-1) exceeds dimension size (1).
# Accounting: time=27 threads=1
# Ended (code 1) at Thu Apr 14 10:40:53 CST 2022, elapsed time 27 seconds
```

**Comment by sw005320** [comment]
Thanks for the report.
@D-Keqi, I think it is a good idea to support the HuBERT+Streaming model.
Can you take a look at this?

**Comment by D-Keqi** [comment]
> narrow(1, 0, feats.size(1) - 2)

Sure! 
It seems that the length of your feats is only 1, thus resulting your issue. Please check the size of your feature extracted by hubert. @lin-nerd

**Comment by lin-nerd** [comment]
@D-Keqi @sw005320 thanks for your reply.
I have confirmed my config file, the config of hubert is as follows:

#hubert
freeze_param: [
"frontend.upstream"
]

frontend_conf:
  n_fft: 512
  hop_length: 128

frontend: s3prl
frontend_conf:
    frontend_conf:
        upstream: hubert_large_ll60k  # Note: If the upstream is changed, please change the input_size in the preencoder.
    download_dir: ./hub
    multilayer_feature: True

preencoder: linear
preencoder_conf:
    input_size: 1024  # Note: If the upstream is changed, please change this value accordingly.
    output_size: 80

**Comment by D-Keqi** [comment]
> feats.size(1)

I mean the size of your extracted feature 'feats.size(1)' = 1, this is weird.

**Comment by joazoa** [comment]
@lin-nerd  did you get this to work in the end ?
