### ISSUE TITLE
tts multilingual language ID embedding

### ISSUE THREAD

**Issue by rrr613** [espnet/espnet#4301]
### Hi,
I want to add language ID embedding to my FastSpeech2 model.

The file says that i have to add this to my config file.
`tts_conf:
    langs: 4  # Number of languages` 

But I want to ask that should I write these commands into both the config file of Tacotron and FastSpeech2？

I train the Tacotron first as a teacher model. Then use knowledge distillation to train FastSpeech2.

There is another question. Should I run the command below both in Tacotron and FastSpeech2？
`$ ./run.sh --stage 2 --stop-stage 3 --use_lid true`
How do I run this command in FastSpeech2?

Thanks

**Comment by kan-bayashi** [comment]
> But I want to ask that should I write these commands into both the config file of Tacotron and FastSpeech2？

You should add to both models.

> Should I run the command below both in Tacotron and FastSpeech2？

Once you run the command, `utt2lid` will be created in dump dir.
Then, you can run the training stage with `--use_lid true` option.

**Comment by rrr613** [comment]
Thanks!

I ran the command to get the `utt2lid`.
But that's not work if I start training from stage 6.
It seems that I should do the token stage.

Does that mean I should do all the process start from stage 2 to stage 7 with `--use_lid true`?

**Comment by rrr613** [comment]
> Once you run the command, `utt2lid` will be created in dump dir. Then, you can run the training stage with 
`--use_lid true` option.

I ran the `$ ./run.sh --stage 2 --stop-stage 3 --use_sid true`
and then ran this command
`$ ./run.sh --stage 6 --use_sid true --train_config /path/to/your_multi_spk_config.yaml`

Then got this Error.

`Traceback (most recent call last):
  File "/data/espnet/tools/espnet/envs/3.8/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/espnet/tools/espnet/envs/3.8/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/espnet/espnet2/bin/tts_train.py", line 22, in <module>
    main()
  File "/data/espnet/espnet2/bin/tts_train.py", line 18, in main
    TTSTask.main(cmd=cmd)
  File "/data/espnet/espnet2/tasks/abs_task.py", line 1019, in main
    cls.main_worker(args)
  File "/data/espnet/espnet2/tasks/abs_task.py", line 1315, in main_worker
    cls.trainer.run(
  File "/data/espnet/espnet2/train/trainer.py", line 286, in run
    all_steps_are_invalid = cls.train_one_epoch(
  File "/data/espnet/espnet2/train/trainer.py", line 522, in train_one_epoch
    retval = model(**batch)
  File "/data/espnet/tools/espnet/envs/3.8/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/espnet/espnet2/tts/espnet_model.py", line 152, in forward
    return self.tts(**batch)
  File "/data/espnet/tools/espnet/envs/3.8/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/espnet/espnet2/tts/tacotron2/tacotron2.py", line 329, in forward
    after_outs, before_outs, logits, att_ws = self._forward(
  File "/data/espnet/espnet2/tts/tacotron2/tacotron2.py", line 414, in _forward
    return self.dec(hs, hlens, ys)
  File "/data/espnet/tools/espnet/envs/3.8/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/espnet/espnet/nets/pytorch_backend/tacotron2/decoder.py", line 436, in forward
    att_c, att_w = self.att(hs, hlens, z_list[0], prev_att_w)
  File "/data/espnet/tools/espnet/envs/3.8/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/espnet/espnet/nets/pytorch_backend/rnn/attentions.py", line 341, in forward
    att_prev = 1.0 - make_pad_mask(enc_hs_len).to(
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.`

**Comment by kan-bayashi** [comment]
Could you run with `--ngpu 0`? It may produce more precise log.

**Comment by rrr613** [comment]
I am not sure is that a bug?

There are two different language in my dataset.
The setting I used is:
`# e.g.
tts_conf:
    langs: 2  # Number of languages`

Then it shows the error above.
So I change the command into:
`# e.g.
tts_conf:
    langs: 3  # Number of languages`

It works.

**Comment by kan-bayashi** [comment]
0 is reserved for unknown langs for + 1 is needed.
