### ISSUE TITLE
Can't run my modified model during the training stage

### ISSUE THREAD

**Issue by triumph9989** [espnet/espnet#4311]
**Describe the bug**
TypeError: forward() got an unexpected keyword argument 'lid'

**Basic environments:**
 - OS information: Linux 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64
 - python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0]
 - espnet version: espnet 0.10.6
 - Git hash 4ab6912ae80bcc4454b30b62b36f6b40c03cf8cf
 - Commit date Thu Oct 21 18:40:13 2021 +0900
 - pytorch version pytorch 1.9.0

**Environments from `torch.utils.collect_env`:**
```
Collecting environment information...
PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-6ubuntu2) 7.5.0
Clang version: 10.0.0 
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.4.0-104-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 2080 Ti
GPU 2: NVIDIA GeForce RTX 2080 Ti
GPU 3: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 510.54
cuDNN version: Probably one of the following:
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.8.2.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.9.0
[pip3] torch-complex==0.2.1
[pip3] torch-optimizer==0.1.0
[pip3] torchaudio==0.9.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2021.3.0           h06a4308_520  
[conda] numpy                     1.20.3                   pypi_0    pypi
[conda] pytorch                   1.9.0           py3.8_cuda10.2_cudnn7.6.5_0    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.1                    pypi_0    pypi
[conda] torch-complex             0.2.1                    pypi_0    pypi
[conda] torch-optimizer           0.1.0                    pypi_0    pypi
[conda] torchaudio                0.9.0                    pypi_0    pypi
```

**Task information:**
 - Task: ASR
 - Recipe: librispeech + Aishell
 - ESPnet2

**Error logs**
```
ESPnetDataset(
  lid: {"path": "dump/raw/mandarin_english_train_sp/utt2lang", "type": "text_int"}
  speech: {"path": "dump/raw/mandarin_english_train_sp/wav.scp", "type": "sound"}
  text: {"path": "dump/raw/mandarin_english_train_sp/text", "type": "text"}
  preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x7f241f5c3490>)
[hdatanode7] 2022-04-24 12:36:21,473 (abs_task:1526) INFO: [train] Batch sampler: FoldedBatchSampler(N-batch=42423, batch_size=32, shape_files=['exp/stats_Streaming_ASR_Conformer_lid01/train/speech_shape', 'exp/stats_Streaming_ASR_Conformer_lid01/train/text_shape.char'], sort_in_batch=descending, sort_batch=descending)
[hdatanode7] 2022-04-24 12:36:21,480 (abs_task:1527) INFO: [train] mini-batch sizes summary: N-batch=42423, mean=8.0, min=1, max=32
[hdatanode7] 2022-04-24 12:36:21,615 (abs_task:1525) INFO: [valid] dataset:
ESPnetDataset(
  speech: {"path": "dump/raw/mandarin_english_dev/wav.scp", "type": "sound"}
  text: {"path": "dump/raw/mandarin_english_dev/text", "type": "text"}
  lid: {"path": "dump/raw/mandarin_english_dev/utt2lang", "type": "text_int"}
  preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x7f240a5bbee0>)
[hdatanode7] 2022-04-24 12:36:21,615 (abs_task:1526) INFO: [valid] Batch sampler: FoldedBatchSampler(N-batch=696, batch_size=32, shape_files=['exp/stats_Streaming_ASR_Conformer_lid01/valid/speech_shape', 'exp/stats_Streaming_ASR_Conformer_lid01/valid/text_shape.char'], sort_in_batch=descending, sort_batch=descending)
[hdatanode7] 2022-04-24 12:36:21,615 (abs_task:1527) INFO: [valid] mini-batch sizes summary: N-batch=696, mean=7.1, min=1, max=32
[hdatanode7] 2022-04-24 12:36:21,717 (trainer:280) INFO: 1/40epoch started
Traceback (most recent call last):
  File "/home/face/espnet_tp/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/face/espnet_tp/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/face/espnet_tp/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/home/face/espnet_tp/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/home/face/espnet_tp/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/espnet2/tasks/abs_task.py", line 1019, in main
    cls.main_worker(args)
  File "/home/face/espnet_tp/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/espnet2/tasks/abs_task.py", line 1315, in main_worker
    cls.trainer.run(
  File "/home/face/espnet_tp/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/espnet2/train/trainer.py", line 286, in run
    all_steps_are_invalid = cls.train_one_epoch(
  File "/home/face/espnet_tp/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/espnet2/train/trainer.py", line 521, in train_one_epoch
    retval = model(**batch)
  File "/home/face/espnet_tp/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'lid'
# Accounting: time=17 threads=1
# Ended (code 1) at Sun Apr 24 12:36:24 CST 2022, elapsed time 17 seconds
```
**Settings of the training stage  in asr_streaming.sh**
```
        ${python} -m espnet2.bin.launch \
            --cmd "${cuda_cmd} --name ${jobname}" \
            --log "${asr_exp}"/train.log \
            --ngpu "${ngpu}" \
            --num_nodes "${num_nodes}" \
            --init_file_prefix "${asr_exp}"/.dist_init_ \
            --multiprocessing_distributed true -- \
            ${python} -m espnet2.bin.asr_train \
                --use_preprocessor true \
                --allow_variable_data_keys true \
                --bpemodel "${bpemodel}" \
                --token_type "${token_type}" \
                --token_list "${token_list}" \
                --non_linguistic_symbols "${nlsyms_txt}" \
                --cleaner "${cleaner}" \
                --g2p "${g2p}" \
                --valid_data_path_and_name_and_type "${_asr_valid_dir}/${_scp},speech,${_type}" \
                --valid_data_path_and_name_and_type "${_asr_valid_dir}/text,text,text" \
                --valid_shape_file "${asr_stats_dir}/valid/speech_shape" \
                --valid_shape_file "${asr_stats_dir}/valid/text_shape.${token_type}" \
                --train_data_path_and_name_and_type "${_asr_train_dir}/utt2lang,lid,text_int" \
                --valid_data_path_and_name_and_type "${_asr_valid_dir}/utt2lang,lid,text_int" \
                --resume true \
                --fold_length "${_fold_length}" \
                --fold_length "${asr_text_fold_length}" \
                --output_dir "${asr_exp}" \
                ${_opts} ${asr_args}
```
**The model I added in**

```
class ReversalClassifier(torch.nn.Module):
    def __init__(self, kernel_size,input_dim, hidden_dim, output_dim,attention_heads,dropout_rate,attention_dropout_rate, gradient_clipping_bounds, scale_factor=1.0):
        super(ReversalClassifier, self).__init__()
        self._lambda = scale_factor
        self._clipping = gradient_clipping_bounds
        self._output_dim = output_dim
        self._classifier = Sequential(
            Linear(input_dim, hidden_dim),
            Linear(hidden_dim, output_dim)
        )
        self._attention =MultiHeadedAttention(
            attention_heads,
            input_dim,
            attention_dropout_rate
        )
        self._multiconv1d = MultiLayeredConv1d(
            input_dim,
            hidden_dim,
            kernel_size,
            dropout_rate
        )

    def forward(self, x):
        x = self._attention(x,x,x,None)
        #x = GradientReversalFunction.apply(x, self._lambda, self._clipping)
        x = self._multiconv1d(x)
        x = torch.mean(x,1)
        x = self._classifier(x)
       
        return x

    @staticmethod
    def loss(input_lengths, lans, prediction, embedings=None):
        
        return F.cross_entropy(prediction, lans.view(-1))
```

**Comment by kan-bayashi** [comment]
If you want to use additional inputs, you need to modify here
https://github.com/espnet/espnet/blob/a3c7c50bccf84c1f40bf79d40bdd735f1b02d79f/espnet2/tasks/asr.py#L378-L395
TTS case might be helpful:
https://github.com/espnet/espnet/blob/a3c7c50bccf84c1f40bf79d40bdd735f1b02d79f/espnet2/tasks/tts.py#L247-L267
And since the `lid` is not sequence, you need to add not_sequence option here.
https://github.com/espnet/espnet/blob/a3c7c50bccf84c1f40bf79d40bdd735f1b02d79f/espnet2/tasks/asr.py#L341
E.g., 
https://github.com/espnet/espnet/blob/a3c7c50bccf84c1f40bf79d40bdd735f1b02d79f/espnet2/tasks/tts.py#L221-L225

**Comment by triumph9989** [comment]
Thanks, I have modified the asr.py, but it seems still appearing the same error. Moreover, I try to use the same method on another server without modifying the part you indicated and it can work. It makes me confused.

Following is the modified code,
```
    def required_data_names(
        cls, train: bool = True, inference: bool = False
    ) -> Tuple[str, ...]:
        if not inference:
            retval = ("speech", "text", "lid")
        else:
            # Recognition mode
            retval = ("speech",)
        return retval
```

```
     return CommonCollateFn( 
         float_pad_value=0.0, 
         int_pad_value=0, 
         not_sequence=["lid"]
     ) 
```

> If you want to use additional inputs, you need to modify here
> 
> https://github.com/espnet/espnet/blob/a3c7c50bccf84c1f40bf79d40bdd735f1b02d79f/espnet2/tasks/asr.py#L378-L395
> 
> 
> TTS case might be helpful:
> https://github.com/espnet/espnet/blob/a3c7c50bccf84c1f40bf79d40bdd735f1b02d79f/espnet2/tasks/tts.py#L247-L267
> 
> 
> And since the `lid` is not sequence, you need to add not_sequence option here.
> https://github.com/espnet/espnet/blob/a3c7c50bccf84c1f40bf79d40bdd735f1b02d79f/espnet2/tasks/asr.py#L341
> 
> 
> E.g.,
> https://github.com/espnet/espnet/blob/a3c7c50bccf84c1f40bf79d40bdd735f1b02d79f/espnet2/tasks/tts.py#L221-L225

**Comment by kan-bayashi** [comment]
Oh sorry, you have already done it.
Then, `lid` is pass to `espnet_model` class:
https://github.com/espnet/espnet/blob/4323c523b4583671346b2d0532b0ddcbb99aa49f/espnet2/asr/espnet_model.py#L158-L165
`lid` will be stored in `kwargs`. You need to modify this function to pass lid for your own module.

**Comment by triumph9989** [comment]
> Oh sorry, you have already done it. Then, `lid` is pass to `espnet_model` class:
> 
> https://github.com/espnet/espnet/blob/4323c523b4583671346b2d0532b0ddcbb99aa49f/espnet2/asr/espnet_model.py#L158-L165
> 
> 
> `lid` will be stored in `kwargs`. You need to modify this function to pass lid for your own module.
Not matter :)
It seems the same error.
It's odd that I can train on another server.
```
    def forward(
        self,
        speech: torch.Tensor,
        speech_lengths: torch.Tensor,
        text: torch.Tensor,
        text_lengths: torch.Tensor,
#         lid: torch.Tensor,
#         lid_lengths: torch.Tensor,
        **kwargs,
    ) -> Tuple[torch.Tensor, Dict[str, torch.Tensor], torch.Tensor]:
```
