### ISSUE TITLE
The additional model doesn't appear in ESPnetASRModel

### ISSUE THREAD

**Issue by triumph9989** [espnet/espnet#4325]
Recently, I train a modified ASR on a server.
But the additional model doesn't appear in ESPnetASRModel and an error occurs.

```
ESPnetASRModel(
  (frontend): DefaultFrontend(
    (stft): Stft(n_fft=512, win_length=512, hop_length=128, center=True, normalized=False, onesided=True)
    (frontend): Frontend()
    (logmel): LogMel(sr=16000, n_fft=512, n_mels=80, fmin=0, fmax=8000.0, htk=False)
  )
  (specaug): SpecAug(
    (time_warp): TimeWarp(window=5, mode=bicubic)
    (freq_mask): MaskAlongAxis(mask_width_range=[0, 30], num_mask=2, axis=freq)
    (time_mask): MaskAlongAxis(mask_width_range=[0, 40], num_mask=2, axis=time)
  )
  (normalize): GlobalMVN(stats_file=exp/stats_Streaming_ASR_Conformer_lid01/train/feats_stats.npz, norm_means=True, norm_vars=True)
  (encoder): ContextualBlockConformerEncoder(
    (pos_enc): StreamPositionalEncoding(
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (embed): Conv2dSubsamplingWOPosEnc(
      (conv): Sequential(
        (0): Conv2d(1, 256, kernel_size=(3, 3), stride=(2, 2))
        (1): ReLU()
        (2): Conv2d(256, 256, kernel_size=(3, 3), stride=(2, 2))
        (3): ReLU()
      )
      (out): Linear(in_features=4864, out_features=256, bias=True)
    )
.
.
.
.
Traceback (most recent call last):
  File "/home/face/espnet_tp2/espnet/tools/anaconda/envs/tp/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/face/espnet_tp2/espnet/tools/anaconda/envs/tp/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/face/espnet_tp2/espnet/tools/anaconda/envs/tp/lib/python3.9/site-packages/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/home/face/espnet_tp2/espnet/tools/anaconda/envs/tp/lib/python3.9/site-packages/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/home/face/espnet_tp2/espnet/tools/anaconda/envs/tp/lib/python3.9/site-packages/espnet2/tasks/abs_task.py", line 1019, in main
    cls.main_worker(args)
  File "/home/face/espnet_tp2/espnet/tools/anaconda/envs/tp/lib/python3.9/site-packages/espnet2/tasks/abs_task.py", line 1315, in main_worker
    cls.trainer.run(
  File "/home/face/espnet_tp2/espnet/tools/anaconda/envs/tp/lib/python3.9/site-packages/espnet2/train/trainer.py", line 286, in run
    all_steps_are_invalid = cls.train_one_epoch(
  File "/home/face/espnet_tp2/espnet/tools/anaconda/envs/tp/lib/python3.9/site-packages/espnet2/train/trainer.py", line 521, in train_one_epoch
    retval = model(**batch)
  File "/home/face/espnet_tp2/espnet/tools/anaconda/envs/tp/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1103, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'lid'
# Accounting: time=11 threads=1
# Ended (code 1) at Wed Apr 27 17:48:44 CST 2022, elapsed time 11 seconds
```

The following is the same method I tried and worked successfully on another server, but the espnet version is almost the same.
```
ESPnetASRModel(
  (lan_cls): ReversalClassifier(
    (_classifier): Sequential(
      (0): Linear(in_features=256, out_features=1024, bias=True)
      (1): Linear(in_features=1024, out_features=3, bias=True)
    )
    (_attention): MultiHeadedAttention(
      (linear_q): Linear(in_features=256, out_features=256, bias=True)
      (linear_k): Linear(in_features=256, out_features=256, bias=True)
      (linear_v): Linear(in_features=256, out_features=256, bias=True)
      (linear_out): Linear(in_features=256, out_features=256, bias=True)
      (dropout): Dropout(p=0.0, inplace=False)
    )
    (_multiconv1d): MultiLayeredConv1d(
      (w_1): Conv1d(256, 1024, kernel_size=(3,), stride=(1,), padding=(1,))
      (w_2): Conv1d(1024, 256, kernel_size=(3,), stride=(1,), padding=(1,))
      (dropout): Dropout(p=0.1, inplace=False)
    )
  )
  (frontend): DefaultFrontend(
    (stft): Stft(n_fft=512, win_length=512, hop_length=128, center=True, normalized=False, onesided=True)
    (frontend): Frontend()
    (logmel): LogMel(sr=16000, n_fft=512, n_mels=80, fmin=0, fmax=8000.0, htk=False)
  )
  (specaug): SpecAug(
    (time_warp): TimeWarp(window=5, mode=bicubic)
    (freq_mask): MaskAlongAxis(mask_width_range=[0, 30], num_mask=2, axis=freq)
    (time_mask): MaskAlongAxis(mask_width_range=[0, 40], num_mask=2, axis=time)
  )
```
I don't have any idea to solve this weird bug.

**Comment by sw005320** [comment]
Can you tell me each version?

**Comment by triumph9989** [comment]
> Can you tell me each version?

Of course. 
espnet: 0.10.6

**Comment by triumph9989** [comment]
> > Can you tell me each version?
>
>
 ```
Collecting environment information...
PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-6ubuntu2) 7.5.0
Clang version: 10.0.0 
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.4.0-104-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 2080 Ti
GPU 2: NVIDIA GeForce RTX 2080 Ti
GPU 3: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 510.54
cuDNN version: Probably one of the following:
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.8.2.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.9.0
[pip3] torch-complex==0.2.1
[pip3] torch-optimizer==0.1.0
[pip3] torchaudio==0.9.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2021.3.0           h06a4308_520  
[conda] numpy                     1.20.3                   pypi_0    pypi
[conda] pytorch                   1.9.0           py3.8_cuda10.2_cudnn7.6.5_0    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.1                    pypi_0    pypi
[conda] torch-complex             0.2.1                    pypi_0    pypi
[conda] torch-optimizer           0.1.0                    pypi_0    pypi
[conda] torchaudio                0.9.0                    pypi_0    pypi
 ```

**Comment by triumph9989** [comment]
> > > Can you tell me each version?
> 
Of course.
espnet: 0.10.6
> ```
> Collecting environment information...
> PyTorch version: 1.9.0
> Is debug build: False
> CUDA used to build PyTorch: 10.2
> ROCM used to build PyTorch: N/A
> 
> OS: Ubuntu 20.04.3 LTS (x86_64)
> GCC version: (Ubuntu 7.5.0-6ubuntu2) 7.5.0
> Clang version: 10.0.0 
> CMake version: version 3.16.3
> Libc version: glibc-2.31
> 
> Python version: 3.8 (64-bit runtime)
> Python platform: Linux-5.4.0-104-generic-x86_64-with-glibc2.17
> Is CUDA available: True
> CUDA runtime version: 10.2.89
> GPU models and configuration: 
> GPU 0: NVIDIA GeForce RTX 2080 Ti
> GPU 1: NVIDIA GeForce RTX 2080 Ti
> GPU 2: NVIDIA GeForce RTX 2080 Ti
> GPU 3: NVIDIA GeForce RTX 2080 Ti
> 
> Nvidia driver version: 510.54
> cuDNN version: Probably one of the following:
> /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.8.2.4
> /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.4
> /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.4
> /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.4
> /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.4
> /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.4
> /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.4
> HIP runtime version: N/A
> MIOpen runtime version: N/A
> 
> Versions of relevant libraries:
> [pip3] numpy==1.20.3
> [pip3] pytorch-ranger==0.1.1
> [pip3] pytorch-wpe==0.0.1
> [pip3] torch==1.9.0
> [pip3] torch-complex==0.2.1
> [pip3] torch-optimizer==0.1.0
> [pip3] torchaudio==0.9.0
> [conda] blas                      1.0                         mkl  
> [conda] cudatoolkit               10.2.89              hfd86e86_1  
> [conda] mkl                       2021.3.0           h06a4308_520  
> [conda] numpy                     1.20.3                   pypi_0    pypi
> [conda] pytorch                   1.9.0           py3.8_cuda10.2_cudnn7.6.5_0    pytorch
> [conda] pytorch-ranger            0.1.1                    pypi_0    pypi
> [conda] pytorch-wpe               0.0.1                    pypi_0    pypi
> [conda] torch-complex             0.2.1                    pypi_0    pypi
> [conda] torch-optimizer           0.1.0                    pypi_0    pypi
> [conda] torchaudio                0.9.0                    pypi_0    pypi
> ```
