### ISSUE TITLE
Joint GAN-TTS learning problem in fastspeech with multi GPU

### ISSUE THREAD

**Issue by IrisLhy** [espnet/espnet#4326]
**Describe the bug**
The model can be launched on single GPU, but not multiples.

**Basic environments:**
 - python version: [e.g. 3.8.5 (default, Mar 27 2019, 22:11:17) [GCC 7.3.0]]
 - espnet version: [e.g. espnet 0.8.5]
 - Git hash [e.g. b88e89fc7246fed4c2842b55baba884fe1b4ecc2]
   - Commit date [e.g. Tue Sep 1 09:32:54 2020 -0400]
 - pytorch version [e.g. pytorch 1.7.1]
 
Is CUDA available: Yes
CUDA runtime version: 11.1

**Task information:**
 - Task: GAN-TTS
 - Recipe: [e.g. librispeech]
 - ESPnet2

**Error logs**

tensor([117.5469], device='cuda:2', grad_fn=<UnsqueezeBackward0>)
tensor([139.6633], device='cuda:1', grad_fn=<UnsqueezeBackward0>)
tensor([114.5397], device='cuda:0', grad_fn=<UnsqueezeBackward0>)
tensor([131.6933], device='cuda:3', grad_fn=<UnsqueezeBackward0>)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/user/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/user/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/user/train_gan_tts.py", line 148, in <module>
    retval = model(forward_generator=turn == "generator",
  File "/home/user/miniconda3/envs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/miniconda3/envs/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 162, in forward
    return self.gather(outputs, self.output_device)
  File "/home/user/miniconda3/envs/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 174, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/user/miniconda3/envs/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    res = gather_map(outputs)
  File "/home/user/miniconda3/envs/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 61, in gather_map
    return type(out)(((k, gather_map([d[k] for d in outputs]))
  File "/home/user/miniconda3/envs/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 61, in <genexpr>
    return type(out)(((k, gather_map([d[k] for d in outputs]))
  File "/home/user/miniconda3/envs/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
TypeError: 'int' object is not iterable

**Comment by IrisLhy** [comment]
I solve this problem，
 `return loss, stats, after_outs if after_outs is not None else before_outs` in [tts](https://github.com/espnet/espnet/blob/9c523be4b81e90ce69ed0c423ddae308382b3654/espnet2/tts/fastspeech/fastspeech.py) need to change to
`            loss, stats, after_outs = force_gatherable(
                (loss, stats, after_outs), loss.device
            )`

**Comment by IrisLhy** [comment]
code in need to change https://github.com/espnet/espnet/blob/9c523be4b81e90ce69ed0c423ddae308382b3654/espnet2/tts/fastspeech/fastspeech.py        

optim_idx = 1
        loss, stats, weight, optim_idx = force_gatherable((loss, stats, batch_size, optim_idx), loss.device)

        # reset cache
        if reuse_cache or not self.training:
            self._cache = None
        return {
            "loss": loss,
            "stats": stats,
            "weight": weight,
            "optim_idx": optim_idx,  # needed for trainer
        }
