### ISSUE TITLE
TTS lid=true bug

### ISSUE THREAD

**Issue by unparalleled-ysj** [espnet/espnet#4354]
@kan-bayashi  Hi when I set use_lid=true , the following error occurs, like the support for lid is incomplete
`RuntimeError: The data-name must be one of ('text', 'speech', 'spembs', 'sids', 'durations', 'pitch', 'energy') for GANTTSTask: "lids" is not allowed.`

**Comment by kan-bayashi** [comment]
Thank you for your report! That is a bug. I will fix it.

**Comment by kan-bayashi** [comment]
Fixed in #4355

**Comment by unparalleled-ysj** [comment]
@kan-bayashi I found another bug, when I set both use_xvector=true and use_lid=true, the following problem occurs，but when I just set use_xvector=true everything works fine
`Traceback (most recent call last):
  File "/root/anaconda3/envs/espnet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/espnet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/work/ysj/espnet/espnet2/bin/gan_tts_train.py", line 22, in <module>
    main()
  File "/work/ysj/espnet/espnet2/bin/gan_tts_train.py", line 18, in main
    GANTTSTask.main(cmd=cmd)
  File "/work/ysj/espnet/espnet2/tasks/abs_task.py", line 1019, in main
    cls.main_worker(args)
  File "/work/ysj/espnet/espnet2/tasks/abs_task.py", line 1323, in main_worker
    distributed_option=distributed_option,
  File "/work/ysj/espnet/espnet2/train/trainer.py", line 290, in run
    distributed_option=distributed_option,
  File "/work/ysj/espnet/espnet2/train/gan_trainer.py", line 160, in train_one_epoch
    retval = model(forward_generator=turn == "generator", **batch)
  File "/root/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/work/ysj/espnet/espnet2/gan_tts/espnet_model.py", line 162, in forward
    return self.tts(**batch)
  File "/root/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/work/ysj/espnet/espnet2/gan_tts/vits/vits.py", line 324, in forward
    lids=lids,
  File "/work/ysj/espnet/espnet2/gan_tts/vits/vits.py", line 485, in _forward_discrminator
    lids=lids,
  File "/root/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/work/ysj/espnet/espnet2/gan_tts/vits/generator.py", line 338, in forward
    z, m_q, logs_q, y_mask = self.posterior_encoder(feats, feats_lengths, g=g)
  File "/root/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/work/ysj/espnet/espnet2/gan_tts/vits/posterior_encoder.py", line 104, in forward
    make_non_pad_mask(x_lengths)
  File "/work/ysj/espnet/espnet/nets/pytorch_backend/nets_utils.py", line 269, in make_non_pad_mask
    return ~make_pad_mask(lengths, xs, length_dim)
  File "/work/ysj/espnet/espnet/nets/pytorch_backend/nets_utils.py", line 154, in make_pad_mask
    lengths = lengths.tolist()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
# Accounting: time=30 threads=1
# Ended (code 1) at Wed May 11 15:37:48 CST 2022, elapsed time 30 seconds`

**Comment by kan-bayashi** [comment]
Maybe the same question: https://github.com/espnet/espnet/issues/4301
