### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by xgp0602** [espnet/espnet#437]
dictionary: data/lang_1char/train_nodev_units.txt
stage 2: Dictionary and Json Data Preparation
28 data/lang_1char/train_nodev_units.txt
/root/espnet/egs/an4/asr1/../../../src/utils/data2json.sh: line 52: bc: command not found
Traceback (most recent call last):
  File "/root/espnet/egs/an4/asr1/../../../src/utils/mergejson.py", line 64, in <module>
    out_dic[unicode('shape', 'utf-8')] = (int(dic[unicode('olen', 'utf-8')]), int(dic[unicode('odim', 'utf-8')]))
ValueError: invalid literal for int() with base 10: ''
/root/espnet/egs/an4/asr1/../../../src/utils/data2json.sh: line 52: bc: command not found
Traceback (most recent call last):
  File "/root/espnet/egs/an4/asr1/../../../src/utils/mergejson.py", line 64, in <module>
    out_dic[unicode('shape', 'utf-8')] = (int(dic[unicode('olen', 'utf-8')]), int(dic[unicode('odim', 'utf-8')]))
ValueError: invalid literal for int() with base 10: ''
/root/espnet/egs/an4/asr1/../../../src/utils/data2json.sh: line 52: bc: command not found
Traceback (most recent call last):
  File "/root/espnet/egs/an4/asr1/../../../src/utils/mergejson.py", line 64, in <module>
    out_dic[unicode('shape', 'utf-8')] = (int(dic[unicode('olen', 'utf-8')]), int(dic[unicode('odim', 'utf-8')]))
ValueError: invalid literal for int() with base 10: ''
/root/espnet/egs/an4/asr1/../../../src/utils/data2json.sh: line 52: bc: command not found
Traceback (most recent call last):
  File "/root/espnet/egs/an4/asr1/../../../src/utils/mergejson.py", line 64, in <module>
    out_dic[unicode('shape', 'utf-8')] = (int(dic[unicode('olen', 'utf-8')]), int(dic[unicode('odim', 'utf-8')]))
ValueError: invalid literal for int() with base 10: ''
stage 3: Network Training
run.pl: job failed, log is in exp/train_nodev_pytorch_blstmp_e4_subsample1_2_2_1_1_unit320_proj320_d1_unit300_location_aconvc10_aconvf100_mtlalpha0.5_adadelta_sampprob0.0_bs30_mli800_mlo150/train.log

exp/train_nodev_pytorch_blstmp_e4_subsample1_2_2_1_1_unit320_proj320_d1_unit300_location_aconvc10_aconvf100_mtlalpha0.5_adadelta_sampprob0.0_bs30_mli800_mlo150/train.log  is :

Traceback (most recent call last):
  File "/root/espnet/egs/an4/asr1/../../../src/bin/asr_train.py", line 197, in <module>
    main()
  File "/root/espnet/egs/an4/asr1/../../../src/bin/asr_train.py", line 191, in main
    train(args)
  File "/root/espnet/src/asr/asr_pytorch.py", line 194, in train
    valid_json = json.load(f)['utts']
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
# Accounting: time=1 threads=1
# Ended (code 1) at Thu Oct 18 18:07:46 UTC 2018, elapsed time 1 seconds

**Comment by Fhrozen** [comment]
I observe that you have this output:
> /root/espnet/egs/an4/asr1/../../../src/utils/data2json.sh: line 52: bc: command not found.

Did you try to install first bc with: `sudo apt install bc` and then execute stage 2??

**Comment by xgp0602** [comment]
thank you very much,the issue has now been resolved by install bc
