### ISSUE TITLE
Error while training joint TTS

### ISSUE THREAD

**Issue by nellorebhanuteja** [espnet/espnet#4405]
i am trying to run the recipe provided in this [page](https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/tts1/README.md#joint-text2wav-training). 
However,  I run the following command
```
./run.sh \
    --stage 6 \
    --tts_task gan_tts \
    --train_config ./conf/tuning/train_joint_conformer_fastspeech2_hifigan.yaml
```

I am getting following error
```Traceback (most recent call last):
  File "/data0/anaconda3/envs/espnet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data0/anaconda3/envs/espnet/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data0/espnet/espnet2/tasks/abs_task.py", line 1121, in main_worker
    model = cls.build_model(args=args)
  File "/data0/espnet/espnet2/tasks/gan_tts.py", line 334, in build_model
    pitch_normalize = pitch_normalize_class(
TypeError: __init__() missing 1 required positional argument: 'stats_file'
Process SpawnProcess-4:
Traceback (most recent call last):
  File "/data0/anaconda3/envs/espnet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data0/anaconda3/envs/espnet/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data0/espnet/espnet2/tasks/abs_task.py", line 1121, in main_worker
    model = cls.build_model(args=args)
  File "/data0/espnet/espnet2/tasks/gan_tts.py", line 334, in build_model
    pitch_normalize = pitch_normalize_class(
TypeError: __init__() missing 1 required positional argument: 'stats_file'
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/data0/anaconda3/envs/espnet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data0/anaconda3/envs/espnet/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data0/espnet/espnet2/tasks/abs_task.py", line 1121, in main_worker
    model = cls.build_model(args=args)
  File "/data0/espnet/espnet2/tasks/gan_tts.py", line 334, in build_model
    pitch_normalize = pitch_normalize_class(
TypeError: __init__() missing 1 required positional argument: 'stats_file'
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/data0/anaconda3/envs/espnet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data0/anaconda3/envs/espnet/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data0/espnet/espnet2/tasks/abs_task.py", line 1121, in main_worker
    model = cls.build_model(args=args)
  File "/data0/espnet/espnet2/tasks/gan_tts.py", line 334, in build_model
    pitch_normalize = pitch_normalize_class(
TypeError: __init__() missing 1 required positional argument: 'stats_file'
Traceback (most recent call last):
  File "/data0/anaconda3/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data0/anaconda3/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data0/espnet/espnet2/bin/gan_tts_train.py", line 22, in <module>
    main()
  File "/data0/espnet/espnet2/bin/gan_tts_train.py", line 18, in main
    GANTTSTask.main(cmd=cmd)
  File "/data0/espnet/espnet2/tasks/abs_task.py", line 1069, in main
    while not ProcessContext(processes, error_queues).join():
  File "/data0/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 139, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 3 terminated with exit code 1
# Accounting: time=17 threads=1
# Ended (code 1) at Sun May 29 17:12:20 UTC 2022, elapsed time 17 seconds
```

**Comment by kan-bayashi** [comment]
Sorry for ambiguous README.
Could you add the options `tts_stats_dir` and `teacher_dumpdir` as the same as fastspeech2 case?

**Comment by nellorebhanuteja** [comment]
It works now
thanks!
