### ISSUE TITLE
Espnet ST transformer model GPU decoding problem

### ISSUE THREAD

**Issue by Xiaoliang1223** [espnet/espnet#4422]
Hello, when I use ST Transformer  for GPU decoding, there is an error RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same . I have tried to change run.sh like this:
        ${decode_cmd} JOB=1:${nj} ${expdir}/${decode_dir}/log/decode.JOB.log \
            st_trans.py \
            --config ${decode_config} \
            --ngpu ${dec_ngpu} \
            --backend ${backend} \
            --batchsize 1 \
            --trans-json ${feat_trans_dir}/split${nj}utt/data_${bpemode}${nbpe}.JOB.json \
            --result-label ${expdir}/${decode_dir}/data.JOB.json \
            --model ${expdir}/results/${trans_model}
Yet the error would be like:
NotImplementedError: Batch decoding is not supported yet.

Then I tried to change decode.yaml to
batchsize: 1
beam-size: 10
penalty: 0.6
maxlenratio: 0.3
minlenratio: 0.0
api: v2
But the RuntimeError remains.

**Comment by sw005320** [comment]
Can you try that with `batchsize: 0`?

**Comment by Xiaoliang1223** [comment]
> 

Yes I have since the default batchsize was 0 and the error was the same.
I found issue #1848 very similar so I tried to change batchsize and api version but nothing happened.

**Comment by sw005320** [comment]
`st_trans.py` may not support GPU decoding.
@brianyan918, can you answer it for me?

**Comment by brianyan918** [comment]
Can you provide the full trace of the errors that you are facing?

**Comment by Xiaoliang1223** [comment]
Sure.
2022-06-06 23:55:26,164 (st_trans:149) WARNING: CUDA_VISIBLE_DEVICES is not set.
2022-06-06 23:55:26,164 (st_trans:160) INFO: python path = /home/zlm/espnet-master/tools/s3prl:
2022-06-06 23:55:26,164 (st_trans:165) INFO: set random seed = 1
2022-06-06 23:55:26,164 (st_trans:168) INFO: backend = pytorch
2022-06-06 23:55:27,344 (deterministic_utils:26) INFO: torch type check is disabled
2022-06-06 23:55:27,344 (asr_utils:694) INFO: reading a config file from exp/train_sp.en-de.de_tc_pytorch_train_bpe8000_specaug/results/model.json
2022-06-06 23:55:27,345 (asr_init:215) INFO: Reading model parameters from exp/train_sp.en-de.de_tc_pytorch_train_bpe8000_specaug/results/model.val5.avg.best
2022-06-06 23:55:27,442 (encoder:172) INFO: encoder self-attention layer type = self-attention
2022-06-06 23:55:27,535 (decoder:127) INFO: decoder self-attention layer type = self-attention
2022-06-06 23:55:27,680 (st:611) INFO: gpu id: [0]
2022-06-06 23:55:29,927 (io_utils:59) WARNING: [Experimental feature] Some preprocessing will be done for the mini-batch creation using Transformation(
    0: TimeWarp(max_time_warp=5, inplace=True, mode=PIL)
    1: FreqMask(F=30, n_mask=2, replace_with_zero=False, inplace=True)
    2: TimeMask(T=40, n_mask=2, replace_with_zero=False, inplace=True))
2022-06-06 23:55:29,927 (st:632) INFO: (1/1423) decoding ted_00767_0012750_0016260
2022-06-06 23:55:29,928 (e2e_st_transformer:411) INFO: <sos> index: 7981
2022-06-06 23:55:29,928 (e2e_st_transformer:412) INFO: <sos> mark: <eos>
2022-06-06 23:55:29,928 (e2e_st_transformer:413) INFO: input lengths: 349
Traceback (most recent call last):
  File "/home/zlm/espnet-master/egs/must_c/st1/../../../espnet/bin/st_trans.py", line 183, in <module>
    main(sys.argv[1:])
  File "/home/zlm/espnet-master/egs/must_c/st1/../../../espnet/bin/st_trans.py", line 177, in main
    trans(args)
  File "/home/zlm/espnet-master/espnet/st/pytorch_backend/st.py", line 638, in trans
    train_args.char_list,
  File "/home/zlm/espnet-master/espnet/nets/pytorch_backend/e2e_st_transformer.py", line 415, in translate
    enc_output = self.encode(x).unsqueeze(0)
  File "/home/zlm/espnet-master/espnet/nets/pytorch_backend/e2e_st_transformer.py", line 388, in encode
    enc_output, _ = self.encoder(x, None)
  File "/home/zlm/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zlm/espnet-master/espnet/nets/pytorch_backend/transformer/encoder.py", line 316, in forward
    xs, masks = self.embed(xs, masks)
  File "/home/zlm/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zlm/espnet-master/espnet/nets/pytorch_backend/transformer/subsampling.py", line 84, in forward
    x = self.conv(x)
  File "/home/zlm/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zlm/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/zlm/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zlm/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/zlm/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 396, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same
# Accounting: time=4 threads=1
# Ended (code 1) at Mon Jun  6 23:55:30 CST 2022, elapsed time 4 seconds

>

**Comment by brianyan918** [comment]
May I see the error when using batchsize 1?

**Comment by Xiaoliang1223** [comment]
> 

# st_trans.py --config conf/decode.yaml --ngpu 1 --backend pytorch --batchsize 1 --trans-json dump/dev_org.en-de.de/deltafalse/split1utt/data_bpe8000.1.json --result-label exp/train_sp.en-de.de_tc_pytorch_train_bpe8000_specaug/decode_dev_org.en-de.de_decode/data.1.json --model exp/train_sp.en-de.de_tc_pytorch_train_bpe8000_specaug/results/model.val5.avg.best 
# Started at Tue Jun  7 00:34:52 CST 2022
#
2022-06-07 00:34:52,969 (st_trans:149) WARNING: CUDA_VISIBLE_DEVICES is not set.
2022-06-07 00:34:52,969 (st_trans:160) INFO: python path = /home/zlm/espnet-master/tools/s3prl:
2022-06-07 00:34:52,969 (st_trans:165) INFO: set random seed = 1
2022-06-07 00:34:52,969 (st_trans:168) INFO: backend = pytorch
2022-06-07 00:34:54,160 (deterministic_utils:26) INFO: torch type check is disabled
2022-06-07 00:34:54,160 (asr_utils:694) INFO: reading a config file from exp/train_sp.en-de.de_tc_pytorch_train_bpe8000_specaug/results/model.json
2022-06-07 00:34:54,161 (asr_init:215) INFO: Reading model parameters from exp/train_sp.en-de.de_tc_pytorch_train_bpe8000_specaug/results/model.val5.avg.best
2022-06-07 00:34:54,265 (encoder:172) INFO: encoder self-attention layer type = self-attention
2022-06-07 00:34:54,358 (decoder:127) INFO: decoder self-attention layer type = self-attention
2022-06-07 00:34:54,498 (st:611) INFO: gpu id: [0]
2022-06-07 00:34:56,778 (io_utils:59) WARNING: [Experimental feature] Some preprocessing will be done for the mini-batch creation using Transformation(
    0: TimeWarp(max_time_warp=5, inplace=True, mode=PIL)
    1: FreqMask(F=30, n_mask=2, replace_with_zero=False, inplace=True)
    2: TimeMask(T=40, n_mask=2, replace_with_zero=False, inplace=True))
Traceback (most recent call last):
  File "/home/zlm/espnet-master/egs/must_c/st1/../../../espnet/bin/st_trans.py", line 183, in <module>
    main(sys.argv[1:])
  File "/home/zlm/espnet-master/egs/must_c/st1/../../../espnet/bin/st_trans.py", line 177, in main
    trans(args)
  File "/home/zlm/espnet-master/espnet/st/pytorch_backend/st.py", line 665, in trans
    train_args.char_list,
  File "/home/zlm/espnet-master/espnet/nets/st_interface.py", line 37, in translate_batch
    raise NotImplementedError("Batch decoding is not supported yet.")
NotImplementedError: Batch decoding is not supported yet.
Accounting: time=5 threads=1
Ended (code 1) at Tue Jun  7 00:34:57 CST 2022, elapsed time 5 seconds

**Comment by Xiaoliang1223** [comment]
> 

Ok thanks a lot
