### ISSUE TITLE
Try to use Hubert as front end but got error 'stack expects each tensor to be equal size' in stage 10

### ISSUE THREAD

**Issue by Tonyyouyou** [espnet/espnet#4434]
**Describe the bug**

**Basic environments:**
 - OS information: [ubuntu 18.04.6]
 - espnet version: [202205]
 - torch version [1.11.0]
 
**Bug detail**
```
Traceback (most recent call last):
  File "/home/tony/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tony/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tony/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/home/tony/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/home/tony/espnet/espnet2/tasks/abs_task.py", line 1011, in main
    cls.main_worker(args)
  File "/home/tony/espnet/espnet2/tasks/abs_task.py", line 1113, in main_worker
    model = cls.build_model(args=args)
  File "/home/tony/espnet/espnet2/tasks/asr.py", line 405, in build_model
    frontend = frontend_class(**args.frontend_conf)
  File "/home/tony/espnet/espnet2/asr/frontend/s3prl.py", line 47, in __init__
    self.upstream, self.featurizer = self._get_upstream(frontend_conf)
  File "/home/tony/espnet/espnet2/asr/frontend/s3prl.py", line 91, in _get_upstream
    s3prl_featurizer = Featurizer(
  File "/home/tony/espnet/tools/s3prl/s3prl/upstream/interfaces.py", line 180, in __init__
    feature = self._weighted_sum([f.cpu() for f in feature])
  File "/home/tony/espnet/tools/s3prl/s3prl/upstream/interfaces.py", line 233, in _weighted_sum
    stacked_feature = torch.stack(feature, dim=0)
RuntimeError: stack expects each tensor to be equal size, but got [1, 50, 1024] at entry 0 and [1, 49, 1024] at entry 24
```

**Comment by 1chimaruGin** [comment]
Reinstall s3prl by using 
```
cd ~/espnet/tools
./installers/install_s3prl.sh
```

**Comment by Tonyyouyou** [comment]
I try to return espnet version back to 202204, then the hubert is working now. I think the reason is due to the update of espnet
