### ISSUE TITLE
CUDA out of memory. I have a gpu with a quite enough memory (32 GB). CUDA is out of memory during the training ASR conformer. Which parameters should be decreased to complete training?

### ISSUE THREAD

**Issue by Yerzhaisang** [espnet/espnet#4450]
Traceback (most recent call last):
  File "/raid/yerzhaisang_taskali/my_work/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/raid/yerzhaisang_taskali/my_work/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/raid/yerzhaisang_taskali/my_work/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/raid/yerzhaisang_taskali/my_work/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/raid/yerzhaisang_taskali/my_work/espnet/espnet2/tasks/abs_task.py", line 1011, in main
    cls.main_worker(args)
  File "/raid/yerzhaisang_taskali/my_work/espnet/espnet2/tasks/abs_task.py", line 1307, in main_worker
    cls.trainer.run(
  File "/raid/yerzhaisang_taskali/my_work/espnet/espnet2/train/trainer.py", line 280, in run
    all_steps_are_invalid = cls.train_one_epoch(
  File "/raid/yerzhaisang_taskali/my_work/espnet/espnet2/train/trainer.py", line 518, in train_one_epoch
    retval = model(**batch)
  File "/raid/yerzhaisang_taskali/my_work/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/raid/yerzhaisang_taskali/my_work/espnet/espnet2/asr/espnet_model.py", line 257, in forward
    loss_att, acc_att, cer_att, wer_att = self._calc_att_loss(
  File "/raid/yerzhaisang_taskali/my_work/espnet/espnet2/asr/espnet_model.py", line 476, in _calc_att_loss
    decoder_out, _ = self.decoder(
  File "/raid/yerzhaisang_taskali/my_work/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/raid/yerzhaisang_taskali/my_work/espnet/espnet2/asr/decoder/transformer_decoder.py", line 136, in forward
    x, tgt_mask, memory, memory_mask = self.decoders(
  File "/raid/yerzhaisang_taskali/my_work/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/raid/yerzhaisang_taskali/my_work/espnet/espnet/nets/pytorch_backend/transformer/repeat.py", line 18, in forward
    args = m(*args)
  File "/raid/yerzhaisang_taskali/my_work/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/raid/yerzhaisang_taskali/my_work/espnet/espnet/nets/pytorch_backend/transformer/decoder_layer.py", line 127, in forward
    x = residual + self.dropout(self.feed_forward(x))
  File "/raid/yerzhaisang_taskali/my_work/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/raid/yerzhaisang_taskali/my_work/espnet/espnet/nets/pytorch_backend/transformer/positionwise_feed_forward.py", line 32, in forward
    return self.w_2(self.dropout(self.activation(self.w_1(x))))
  File "/raid/yerzhaisang_taskali/my_work/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/raid/yerzhaisang_taskali/my_work/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "/raid/yerzhaisang_taskali/my_work/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/functional.py", line 1692, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA out of memory. Tried to allocate 746.00 MiB (GPU 0; 31.72 GiB total capacity; 26.10 GiB already allocated; 306.38 MiB free; 30.26 GiB reserved in total by PyTorch)
Accounting: time=1112 threads=1
Ended (code 1) at Wed Jun 15 13:39:02 +06 2022, elapsed time 1112 seconds

**Comment by Yerzhaisang** [comment]
I can't allow multi-GPU training, because I have access to only one GPU. I have created a recipe from template egs2. My run.sh and config.yaml of ASR are located here: https://github.com/Yerzhaisang/Exp_espnet

**Comment by Emrys365** [comment]
I mean where is your configuration file copied from? If the original config file is used for multi-GPU training, you will need to modify the hyperparameters to fit the single GPU environment.

Anyway, can you try reducing the value of `batch_bins`?

**Comment by Yerzhaisang** [comment]
Thank you so much. I am using 2 gpu's, and it's working.
