### ISSUE TITLE
Decoding error for Joint TTS

### ISSUE THREAD

**Issue by nellorebhanuteja** [espnet/espnet#4484]
Hi 

I am trying to run Stage 7 of the TTS recipe.
I trained my model using Joint Conformer FastSpeech2 HifiFAN config
I am getting following error while decoding
```
2022-06-30 10:54:34,012 (tts:285) INFO: Vocabulary size: 78
2022-06-30 10:54:34,235 (encoder:171) INFO: encoder self-attention layer type = relative self-attention
2022-06-30 10:54:34,615 (encoder:171) INFO: encoder self-attention layer type = relative self-attention
Traceback (most recent call last):
  File "/data0/anaconda3/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data0/anaconda3/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data0/espnet/espnet2/bin/tts_inference.py", line 759, in <module>
    main()
  File "/data0/espnet/espnet2/bin/tts_inference.py", line 755, in main
    inference(**kwargs)
  File "/data0/espnet/espnet2/bin/tts_inference.py", line 387, in inference
    text2speech = Text2Speech.from_pretrained(
  File "/data0/espnet/espnet2/bin/tts_inference.py", line 315, in from_pretrained
    return Text2Speech(**kwargs)
  File "/data0/espnet/espnet2/bin/tts_inference.py", line 101, in __init__
    model, train_args = TTSTask.build_model_from_file(
  File "/data0/espnet/espnet2/tasks/abs_task.py", line 1832, in build_model_from_file
    model.load_state_dict(torch.load(model_file, map_location=device))
  File "/data0/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/data0/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/data0/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'exp/tts_train_joint_conformer_fastspeech2_hifigan_raw_phn_tacotron_g2p_en_no_space/train.loss.ave.pth'
# Accounting: time=10 threads=1
# Ended (code 1) at Thu Jun 30 10:54:37 UTC 2022, elapsed time 10 seconds

```

**Comment by kan-bayashi** [comment]
Please pass the option `--inference_model latest.pth` for `run.sh`
