### ISSUE TITLE
Big dataset cause mergejson.py out of memory

### ISSUE THREAD

**Issue by fanlu** [espnet/espnet#449]
My dataset's volumn is 2900h, all data is 8k telephone audio, and do perturb to 3 times than original.
the part of mergejson.py in data2json.sh recipe will cause an out of memory error.
```
Traceback (most recent call last):
  File "/espnet/egs/kefu/asr1/../../../src/utils/mergejson.py", line 74, in <module>                                                                                  
    jsonstring = json.dumps({'utts': new_dic}, indent=4, ensure_ascii=False, sort_keys=True).encode('utf_8')                                                                                      
  File "/miniconda3/envs/py2/lib/python2.7/json/__init__.py", line 251, in dumps                                                                                      
    sort_keys=sort_keys, **kw).encode(obj)
  File "/miniconda3/envs/py2/lib/python2.7/json/encoder.py", line 210, in encode                                                                                      
    return ''.join(chunks)
MemoryError
```
So can we change the style of data.json file to one json per line? @sw005320

**Comment by sw005320** [comment]
Thanks for pointing out it.
This is an expected issue.
We'll work it later, but if you solve it and make a PR, that is great.

**Comment by sw005320** [comment]
#450 solved the issue.
