### ISSUE TITLE
got a gradient error in first epoch

### ISSUE THREAD

**Issue by fanlu** [espnet/espnet#452]
Have you met this error before? @sw005320 
```
./run.sh --stage 4 --queue g.q --ngpu 4 --etype vggblstm --elayers 3 --eunits 1024 --eprojs 1024 --batchsize 16 --train_set train_nodev_perturb --maxlen_in 2200
```
```
0           19700       14.31       15.7234        12.8966                                                                                  0.871656                         70311         1e-08
Exception in main training loop: invalid gradient at index 0 - expected shape [2] but got [4]
Traceback (most recent call last):............................] 18.09%
  File "/mnt/cephfs2/asr/users/fanlu/miniconda3/envs/py2/lib/python2.7/site-packages/chainer/training/trainer.py", line 306, in run                                                               
    update()ters/sec. Estimated time to finish: 102 days, 21:11:27.119712.
  File "/mnt/cephfs2/asr/users/fanlu/miniconda3/envs/py2/lib/python2.7/site-packages/chainer/training/updaters/standard_updater.py", line 149, in update                                          
    self.update_core()
  File "/mnt/cephfs2/asr/users/fanlu/espnet/src/asr/asr_pytorch.py", line 123, in update_core
    loss.backward(loss.new_ones(self.ngpu))  # Backprop
  File "/mnt/cephfs2/asr/users/fanlu/miniconda3/envs/py2/lib/python2.7/site-packages/torch/tensor.py", line 93, in backward                                                                       
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/mnt/cephfs2/asr/users/fanlu/miniconda3/envs/py2/lib/python2.7/site-packages/torch/autograd/__init__.py", line 90, in backward                                                            
    allow_unreachable=True)  # allow_unreachable flag
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/mnt/cephfs2/asr/users/fanlu/espnet/egs/kefu/asr1/../../../src/bin/asr_train.py", line 197, in <module>                                                                                   
    main()
  File "/mnt/cephfs2/asr/users/fanlu/espnet/egs/kefu/asr1/../../../src/bin/asr_train.py", line 191, in main                                                                                       
    train(args)
  File "/mnt/cephfs2/asr/users/fanlu/espnet/src/asr/asr_pytorch.py", line 365, in train
    trainer.run()
  File "/mnt/cephfs2/asr/users/fanlu/miniconda3/envs/py2/lib/python2.7/site-packages/chainer/training/trainer.py", line 320, in run                                                               
    six.reraise(*sys.exc_info())
  File "/mnt/cephfs2/asr/users/fanlu/miniconda3/envs/py2/lib/python2.7/site-packages/chainer/training/trainer.py", line 306, in run                                                               
    update()
  File "/mnt/cephfs2/asr/users/fanlu/miniconda3/envs/py2/lib/python2.7/site-packages/chainer/training/updaters/standard_updater.py", line 149, in update                                          
    self.update_core()
  File "/mnt/cephfs2/asr/users/fanlu/espnet/src/asr/asr_pytorch.py", line 123, in update_core
    loss.backward(loss.new_ones(self.ngpu))  # Backprop
  File "/mnt/cephfs2/asr/users/fanlu/miniconda3/envs/py2/lib/python2.7/site-packages/torch/tensor.py", line 93, in backward                                                                       
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/mnt/cephfs2/asr/users/fanlu/miniconda3/envs/py2/lib/python2.7/site-packages/torch/autograd/__init__.py", line 90, in backward                                                            
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: invalid gradient at index 0 - expected shape [2] but got [4]
# Accounting: time=71697 threads=1
# Finished at Thu Nov 8 13:12:38 CST 2018 with status 1
```
```
Exception in main training loop: invalid gradient at index 0 - expected shape [3] but got [4]
Traceback (most recent call last):............................] 37.67%
  File "/mnt/cephfs2/asr/users/fanlu/miniconda3/envs/py2/lib/python2.7/site-packages/chainer/training/trainer.py", line 306, in run
    update()ters/sec. Estimated time to finish: 8 days, 21:37:22.134266.
  File "/mnt/cephfs2/asr/users/fanlu/miniconda3/envs/py2/lib/python2.7/site-packages/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/mnt/cephfs2/asr/users/fanlu/espnet/src/asr/asr_pytorch.py", line 123, in update_core
    loss.backward(loss.new_ones(self.ngpu))  # Backprop
  File "/mnt/cephfs2/asr/users/fanlu/miniconda3/envs/py2/lib/python2.7/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/mnt/cephfs2/asr/users/fanlu/miniconda3/envs/py2/lib/python2.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/mnt/cephfs2/asr/users/fanlu/espnet/egs/kefu/asr1/../../../src/bin/asr_train.py", line 197, in <module>
    main()
  File "/mnt/cephfs2/asr/users/fanlu/espnet/egs/kefu/asr1/../../../src/bin/asr_train.py", line 191, in main
    train(args)
  File "/mnt/cephfs2/asr/users/fanlu/espnet/src/asr/asr_pytorch.py", line 362, in train
    trainer.run()
  File "/mnt/cephfs2/asr/users/fanlu/miniconda3/envs/py2/lib/python2.7/site-packages/chainer/training/trainer.py", line 320, in run
    six.reraise(*sys.exc_info())
  File "/mnt/cephfs2/asr/users/fanlu/miniconda3/envs/py2/lib/python2.7/site-packages/chainer/training/trainer.py", line 306, in run
    update()
  File "/mnt/cephfs2/asr/users/fanlu/miniconda3/envs/py2/lib/python2.7/site-packages/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/mnt/cephfs2/asr/users/fanlu/espnet/src/asr/asr_pytorch.py", line 123, in update_core
    loss.backward(loss.new_ones(self.ngpu))  # Backprop
  File "/mnt/cephfs2/asr/users/fanlu/miniconda3/envs/py2/lib/python2.7/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/mnt/cephfs2/asr/users/fanlu/miniconda3/envs/py2/lib/python2.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: invalid gradient at index 0 - expected shape [3] but got [4]
# Accounting: time=15618 threads=1
# Finished at Sun Oct 28 02:59:52 CST 2018 with status 1
```

**Comment by sw005320** [comment]
No.
Did it happen in some particular utterance?
Then you might need to check it to see if it is broken or not.

**Comment by sw005320** [comment]
Can you tell me more detailed information (input and output lengths)?
My suggestion is to remove these sentences. This may be just harmful. 
`remove_longshortdata.sh` (e.g., used in https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/run.sh#L137) can also remove short utterances.

**Comment by fanlu** [comment]
the lengths of input and output is 89 and 1/3
```
((89, 83), (1,))
((89, 83), (3,))
```
this is my training script
```
./run.sh --stage 4 --queue g.q --ngpu 4 --etype vggblstm --elayers 3 --eunits 1024 --eprojs 1024 --batchsize 16 --train_set train_nodev_perturb --maxlen_in 2200
```
I don't know the data preparation and maxlen_in strategy，there is no error when using default maxlen_in 800.

**Comment by sw005320** [comment]
I think it comes from the multiple GPU issue, and it might assign blank utterance to some GPU (it would be a bug). @kan-bayashi, @bobchennan, do you have any idea? Also, I don't recommend to use `--maxlen_in 2200`. `--maxlen_in YYY` will be used to reduce the batch size if the input lengths in a minibatch is more than YYY. So your setup will require very large GPU memory. I usually do not touch this parameter so much, but I change the batchsize instead.

**Comment by kan-bayashi** [comment]
I think this is the same problem in #419.
As I mentioned in #419, Idoubt that the batchsize become less than the number of gpus due to adaptive batchsize.

**Comment by sw005320** [comment]
I see. @kan-bayashi, can you fix it?
We may set the minimum batch size parameter when we build the minibatch by using the number of GPUs.

**Comment by kan-bayashi** [comment]
OK. I will do it tomorrow.
But in #419, it has still the same error even if we set the minimum batchsize as #gpus.
So I do not have confidence on the reason...

**Comment by sw005320** [comment]
#gpus x 2

**Comment by fanlu** [comment]
I just add try except on loss.backward to avoid this problem. I will try it again after @kan-bayashi 's fix.thanks
```
-            loss.backward(loss.new_ones(self.ngpu))  # Backprop
+            try:
+                loss.backward(loss.new_ones(self.ngpu))  # Backprop
+            except:
+                xs, ys = batch[0]
+                for i in range(len(xs)):
+                    print(xs[i].shape, ys[i].shape)
+                print(batch)
```

**Comment by kan-bayashi** [comment]
@fanlu Could you test the patch #463?
