### ISSUE TITLE
Problem decoding with a Transformer LM.

### ISSUE THREAD

**Issue by picheny-nyu** [espnet/espnet#4527]
**Describe the bug**
Training seems to work fine for the RNNT but then I get this error. Please help! I can attach whatever files you need to examine. 

Thanks
Michael

**Error logs**

```bash
# python3 -m espnet2.bin.asr_inference --batch_size 1 --ngpu 0 --data_path_and_name_and_type dump/raw/dev2/wav.scp,speech,sound --key_file exp/asr_train_rnnt_conformer_raw_en_bpe100_sp/decode_rnnt_conformer_lm_lm_train_lm_transformer2_en_bpe100_valid.loss.ave_asr_model_valid.loss.ave/dev2/logdir/keys.1.scp --asr_train_config exp/asr_train_rnnt_conformer_raw_en_bpe100_sp/config.yaml --asr_model_file exp/asr_train_rnnt_conformer_raw_en_bpe100_sp/valid.loss.ave.pth --output_dir exp/asr_train_rnnt_conformer_raw_en_bpe100_sp/decode_rnnt_conformer_lm_lm_train_lm_transformer2_en_bpe100_valid.loss.ave_asr_model_valid.loss.ave/dev2/logdir/output.1 --config conf/decode_rnnt_conformer.yaml --lm_train_config exp/lm_train_lm_transformer2_en_bpe100/config.yaml --lm_file exp/lm_train_lm_transformer2_en_bpe100/valid.loss.ave.pth 
# Started at Sat Jul 23 18:12:18 EDT 2022
#
/ext3/miniconda3/bin/python3 /vast/map22/espnet/espnet2/bin/asr_inference.py --batch_size 1 --ngpu 0 --data_path_and_name_and_type dump/raw/dev2/wav.scp,speech,sound --key_file exp/asr_train_rnnt_conformer_raw_en_bpe100_sp/decode_rnnt_conformer_lm_lm_train_lm_transformer2_en_bpe100_valid.loss.ave_asr_model_valid.loss.ave/dev2/logdir/keys.1.scp --asr_train_config exp/asr_train_rnnt_conformer_raw_en_bpe100_sp/config.yaml --asr_model_file exp/asr_train_rnnt_conformer_raw_en_bpe100_sp/valid.loss.ave.pth --output_dir exp/asr_train_rnnt_conformer_raw_en_bpe100_sp/decode_rnnt_conformer_lm_lm_train_lm_transformer2_en_bpe100_valid.loss.ave_asr_model_valid.loss.ave/dev2/logdir/output.1 --config conf/decode_rnnt_conformer.yaml --lm_train_config exp/lm_train_lm_transformer2_en_bpe100/config.yaml --lm_file exp/lm_train_lm_transformer2_en_bpe100/valid.loss.ave.pth
2022-07-23 18:12:32,602 (asr:411) INFO: Vocabulary size: 100
2022-07-23 18:12:32,714 (conformer_encoder:137) WARNING: Using legacy_rel_pos and it will be deprecated in the future.
2022-07-23 18:12:32,783 (conformer_encoder:237) WARNING: Using legacy_rel_selfattn and it will be deprecated in the future.
2022-07-23 18:12:36,016 (lm:199) INFO: Vocabulary size: 100
2022-07-23 18:12:36,017 (encoder:172) INFO: encoder self-attention layer type = self-attention
2022-07-23 18:12:37,565 (asr_inference:199) INFO: Text tokenizer: SentencepiecesTokenizer(model="data/en_token_list/bpe_unigram100/bpe.model")
/vast/map22/espnet/espnet2/layers/stft.py:166: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  olens = (ilens - self.n_fft) // self.hop_length + 1
Traceback (most recent call last):
  File "/ext3/miniconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/ext3/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/vast/map22/espnet/espnet2/bin/asr_inference.py", line 609, in <module>
    main()
  File "/vast/map22/espnet/espnet2/bin/asr_inference.py", line 605, in main
    inference(**kwargs)
  File "/vast/map22/espnet/espnet2/bin/asr_inference.py", line 425, in inference
    results = speech2text(**batch)
  File "/ext3/miniconda3/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/vast/map22/espnet/espnet2/bin/asr_inference.py", line 255, in __call__
    nbest_hyps = self.beam_search_transducer(enc[0])
  File "/vast/map22/espnet/espnet2/asr/transducer/beam_search_transducer.py", line 142, in __call__
    nbest_hyps = self.search_algorithm(enc_out)
  File "/vast/map22/espnet/espnet2/asr/transducer/beam_search_transducer.py", line 281, in default_beam_search
    lm_scores, lm_state = self.lm.score(
  File "/vast/map22/espnet/espnet2/lm/transformer_lm.py", line 86, in score
    h, _, cache = self.encoder.forward_one_step(
  File "/vast/map22/espnet/espnet/nets/pytorch_backend/transformer/encoder.py", line 370, in forward_one_step
    xs, masks = e(xs, masks, cache=c)
  File "/ext3/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/vast/map22/espnet/espnet/nets/pytorch_backend/transformer/encoder_layer.py", line 95, in forward
    assert cache.shape == (x.shape[0], x.shape[1] - 1, self.size)
AssertionError
# Accounting: time=23 threads=1
# Ended (code 1) at Sat Jul 23 18:12:41 EDT 2022, elapsed time 23 seconds
```

**Comment by b-flo** [comment]
Hi,

It seems that your repo is not up-to-date. Could you pull the changes and test again, please?

**Comment by picheny-nyu** [comment]
That worked, thank you, though I did need to install fast_bss_eval for it to work.

I notice with the rnnt I am getting high deletion rates compared to the transformer model for the same amount of data. Any suggestions for how to tune to reduce this effect? 

Thanks
Michael

**Comment by b-flo** [comment]
> That worked, thank you, though I did need to install fast_bss_eval for it to work.

Note that `fast_bss_eval` is unrelated to your issue, it's for speech enhancement. What you were missing is some fixes related to Transformer LM.

> I notice with the rnnt I am getting high deletion rates compared to the transformer model for the same amount of data. Any suggestions for how to tune to reduce this effect?

Sorry, it's a bit difficult to help you without any information on task, models (AM, LM), decoding process, etc.

I'm closing this issue. Feel free to open a new one if you need help on the performance part!
