### ISSUE TITLE
Training on own dataset

### ISSUE THREAD

**Issue by wflrz123** [espnet/espnet#4533]
```
Traceback (most recent call last):
  File "/root/anaconda3/envs/espnet_test/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/espnet_test/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/i_liaoruizhi/test/espnet/espnet2/bin/tts_train.py", line 22, in <module>
    main()
  File "/root/i_liaoruizhi/test/espnet/espnet2/bin/tts_train.py", line 18, in main
    TTSTask.main(cmd=cmd)
  File "/root/i_liaoruizhi/test/espnet/espnet2/tasks/abs_task.py", line 1013, in main
    cls.main_worker(args)
  File "/root/i_liaoruizhi/test/espnet/espnet2/tasks/abs_task.py", line 1317, in main_worker
    distributed_option=distributed_option,
  File "/root/i_liaoruizhi/test/espnet/espnet2/train/trainer.py", line 290, in run
    distributed_option=distributed_option,
  File "/root/i_liaoruizhi/test/espnet/espnet2/train/trainer.py", line 550, in train_one_epoch
    retval = model(**batch)
  File "/root/anaconda3/envs/espnet_test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/i_liaoruizhi/test/espnet/espnet2/tts/espnet_model.py", line 151, in forward
    return self.tts(**batch)
  File "/root/anaconda3/envs/espnet_test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/i_liaoruizhi/test/espnet/espnet2/tts/tacotron2/tacotron2.py", line 332, in forward
    lids=lids,
  File "/root/i_liaoruizhi/test/espnet/espnet2/tts/tacotron2/tacotron2.py", line 410, in _forward
    return self.dec(hs, hlens, ys)
  File "/root/anaconda3/envs/espnet_test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/i_liaoruizhi/test/espnet/espnet/nets/pytorch_backend/tacotron2/decoder.py", line 438, in forward
    xs = torch.cat([att_c, prenet_out], dim=1)
RuntimeError: Tensors must have same number of dimensions: got 3 and 2
feats: torch.Size([33, 241, 2, 80])
```

When I was training with my own dataset, the shape of the speech became [33, 241, 2, 80]. It should have been [33, 241, 80], which is normal. I don't know where the setting caused this situation?Or is it caused by the preprocessing of the dataset?

**Comment by kan-bayashi** [comment]
It seems that your audio has 2 channel. Please convert your audio to mono.
