### ISSUE TITLE
Error in fs2 + hifigan joint finetuning with torch automatic mixed precision training

### ISSUE THREAD

**Issue by adsf0078** [espnet/espnet#4589]
Dear, 

Thank you for your great works.
I followed the procedure to train our TTS by the fs2 + hifigan joint training approach using the corresponding pretrained models with the config provided in egs2/ljspeech/tts1/conf/tuning/finetune_joint_conformer_fastspeech2_hifigan.yaml: Joint fine-tuning of conformer fastspeech2 + hifigan.
It took considerable time (more than five days in our task) with our two RTX3090 GPUs. Thus to save the training time, I tried to train it in mixed precision using torch automaic mixed precision by setting use_amp: true in the config.
However, I only met the following error as:

```
sys3:17769:17769 [0] NCCL INFO Launch mode Parallel
[sys3:0/2] 2022-08-22 06:20:29,763 (trainer:273) INFO: 1/700epoch started
[W reducer.cpp:1289] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[W reducer.cpp:1289] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/data1/moris/espnet/espnet2/layers/stft.py:166: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  olens = (ilens - self.win_length) // self.hop_length + 1
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/data1/moris/anaconda3/envs/espnet/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/data1/moris/anaconda3/envs/espnet/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/moris/espnet/espnet2/tasks/abs_task.py", line 1291, in main_worker
    distributed_option=distributed_option,
  File "/data1/moris/espnet/espnet2/train/trainer.py", line 288, in run
    distributed_option=distributed_option,
  File "/data1/moris/espnet/espnet2/train/gan_trainer.py", line 222, in train_one_epoch
    scaler.scale(loss).backward()
  File "/data1/moris/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/data1/moris/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: view_as_complex is only supported for float and double tensors, but got a tensor of scalar type: Half
/data1/moris/espnet/espnet2/layers/stft.py:166: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  olens = (ilens - self.win_length) // self.hop_length + 1
```

Doesn't this tts version support torch automatic mixed precision?
Please help!

**Comment by adsf0078** [comment]
Hi,
It worked as I disabled autocast as you hinted just after the line '# calculate losses' or especially at the line 
'mel_loss = self.mel_loss(speech_hat_.float(), speech_.float())' alone with type casting to float to the two passing parameters in espnet2/gan_tts/joint/joint_text2wav.py
However, acceleration in training speed seems almost negligible in our case.
Thank you sincerely for your help!

**Comment by kan-bayashi** [comment]
@adsf0078 Thank you for your kind report.
