### ISSUE TITLE
Feature extraction is not working

### ISSUE THREAD

**Issue by yoni-jj** [espnet/espnet#4630]
2022-09-10T08:53:47 (asr.sh:254:main) ./asr.sh --stage 3 --stop_stage 3 --train_set train_nodev --valid_set train_dev --test_sets train_dev test --nj 4
2022-09-10T08:53:47 (asr.sh:474:main) Stage 3: Format wav.scp: data/ -> dump/raw
utils/copy_data_dir.sh: copied data from data/train_nodev to dump/raw/org/train_nodev
utils/validate_data_dir.sh: Successfully validated data-directory dump/raw/org/train_nodev
2022-09-10T08:53:48 (format_wav_scp.sh:42:main) scripts/audio/format_wav_scp.sh --nj 4 --cmd run.pl --audio-format flac --fs 16k data/train_nodev/wav.scp dump/raw/org/train_nodev
2022-09-10T08:53:48 (format_wav_scp.sh:110:main) [info]: without segments
run.pl: 4 / 4 failed, log is in dump/raw/org/train_nodev/logs/format_wav_scp.*.log

When i tried running the espnet2 tutorial on colab it gave this error
and when i opened the log files it says:
 pyscripts/audio/format_wav_scp.py --fs 16k --audio-format flac dump/raw/org/train_nodev/logs/wav.1.scp dump/raw/org/train_nodev/data/format.1 
 Started at Sat Sep 10 08:53:49 UTC 2022

Traceback (most recent call last):
  File "pyscripts/audio/format_wav_scp.py", line 11, in <module>
    import resampy
  File "/content/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/resampy/__init__.py", line 7, in <module>
    from .core import *
  File "/content/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/resampy/core.py", line 7, in <module>
    import numba
  File "/content/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/numba/__init__.py", line 200, in <module>
    _ensure_critical_deps()
  File "/content/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/numba/__init__.py", line 140, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.21 or less")
ImportError: Numba needs NumPy 1.21 or less
 Accounting: time=1 threads=1
Ended (code 1) at Sat Sep 10 08:53:50 UTC 2022, elapsed time 1 seconds

**Comment by kamo-naoyuki** [comment]
Upgrade numba or downgrade numpy
