### ISSUE TITLE
use chainer to train wordlm 

### ISSUE THREAD

**Issue by shanguanma** [espnet/espnet#466]
Error log:
# lm_train.py --ngpu 1 --backend chainer --verbose 1 --outdir exp/train_rnnlm_chainer_1layer_unit700_sgd_bs128_word20000 --train-label data/local/wordlm_train/train.txt --valid-label data/local/wordlm_train/valid.txt --test-label data/local/wordlm_train/test.txt --resume --layer 1 --unit 700 --opt sgd --batchsize 128 --epoch 20 --maxlen 40 --dict data/local/wordlm_train/wordlist_20000.txt 
# Invoked at Fri Nov 16 16:51:53 SGT 2018 from node07
#
# Started at Fri Nov 16 16:52:13 SGT 2018 on node05
2018-11-16 16:52:13,446 (lm_train:98) INFO: python path = /cm/local/apps/cuda/libs/current/pynvml:/home4/md510/kaldi/tools/jieba/./lib/python2.7/site-packages:/home4/md510/kaldi/tools/jieba/./lib/python2.7/site-packages
2018-11-16 16:52:13,475 (lm_train:115) INFO: backend = chainer
2018-11-16 16:52:14,026 (lm_chainer:228) INFO: chainer version = 5.0.0
2018-11-16 16:52:14,026 (lm_chainer:233) INFO: chainer seed = 1
2018-11-16 16:52:14,026 (lm_chainer:241) INFO: chainer type check is disabled
2018-11-16 16:52:14,528 (lm_chainer:264) INFO: #vocab = 15613
2018-11-16 16:52:14,528 (lm_chainer:265) INFO: #sentences in the training data = 1
2018-11-16 16:52:14,528 (lm_chainer:266) INFO: #tokens in the training data = 1396260
2018-11-16 16:52:14,529 (lm_chainer:267) INFO: oov rate in the training data = 0.00 %
2018-11-16 16:52:14,529 (lm_chainer:268) INFO: #sentences in the validation data = 1
2018-11-16 16:52:14,529 (lm_chainer:269) INFO: #tokens in the validation data = 1455
2018-11-16 16:52:14,529 (lm_chainer:270) INFO: oov rate in the validation data = 0.00 %
2018-11-16 16:52:14,529 (lm_chainer:277) INFO: #iterations per epoch = 1
2018-11-16 16:52:14,529 (lm_chainer:278) INFO: #total iterations = 20
2018-11-16 16:52:37,904 (lm_chainer:295) INFO: writing a model config file to exp/train_rnnlm_chainer_1layer_unit700_sgd_bs128_word20000/model.json
Exception in main training loop: out of memory to allocate 124928 bytes (total 10688858112 bytes)
Traceback (most recent call last):
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/training/trainer.py", line 315, in run
    update()
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/training/updaters/standard_updater.py", line 165, in update
    self.update_core()
  File "/home4/md510/espnet/espnet/lm/lm_chainer.py", line 184, in update_core
    chainer.Variable(t[:, i]))
  File "/home4/md510/espnet/espnet/lm/lm_chainer.py", line 98, in __call__
    state, self.y = self.predictor(state, *args, **kwargs)
  File "/home4/md510/espnet/espnet/lm/lm_chainer.py", line 153, in __call__
    y = self.lo(F.dropout(h[-1]))
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/link.py", line 242, in __call__
    out = forward(*args, **kwargs)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/links/connection/linear.py", line 138, in forward
    return linear.linear(x, self.W, self.b, n_batch_axes=n_batch_axes)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/functions/connection/linear.py", line 289, in linear
    y, = LinearFunction().apply(args)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/function_node.py", line 263, in apply
    outputs = self.forward(in_data)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/functions/connection/linear.py", line 89, in forward
    y = xp.empty((x.shape[0], W.shape[0])).astype(x.dtype)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/cupy/creation/basic.py", line 20, in empty
    return cupy.ndarray(shape, dtype, order=order)
  File "cupy/core/core.pyx", line 150, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 517, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1064, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1085, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 899, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 920, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 694, in cupy.cuda.memory._try_malloc
Will finalize trainer extensions and updater before reraising the exception.
^[[JTraceback (most recent call last):
  File "/home4/md510/espnet/espnet/bin/lm_train.py", line 127, in <module>
    main()
  File "/home4/md510/espnet/espnet/bin/lm_train.py", line 118, in main
    train(args)
  File "/home4/md510/espnet/espnet/lm/lm_chainer.py", line 326, in train
    trainer.run()
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/training/trainer.py", line 329, in run
    six.reraise(*sys.exc_info())
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/training/trainer.py", line 315, in run
    update()
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/training/updaters/standard_updater.py", line 165, in update
    self.update_core()
  File "/home4/md510/espnet/espnet/lm/lm_chainer.py", line 184, in update_core
    chainer.Variable(t[:, i]))
  File "/home4/md510/espnet/espnet/lm/lm_chainer.py", line 98, in __call__
    state, self.y = self.predictor(state, *args, **kwargs)
  File "/home4/md510/espnet/espnet/lm/lm_chainer.py", line 153, in __call__
    y = self.lo(F.dropout(h[-1]))
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/link.py", line 242, in __call__
out = forward(*args, **kwargs)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/links/connection/linear.py", line 138, in forward
    return linear.linear(x, self.W, self.b, n_batch_axes=n_batch_axes)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/functions/connection/linear.py", line 289, in linear
    y, = LinearFunction().apply(args)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/function_node.py", line 263, in apply
    outputs = self.forward(in_data)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/functions/connection/linear.py", line 89, in forward
    y = xp.empty((x.shape[0], W.shape[0])).astype(x.dtype)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/cupy/creation/basic.py", line 20, in empty
    return cupy.ndarray(shape, dtype, order=order)
  File "cupy/core/core.pyx", line 150, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 517, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1064, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1085, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 899, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 920, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 694, in cupy.cuda.memory._try_malloc
cupy.cuda.memory.OutOfMemoryError: out of memory to allocate 124928 bytes (total 10688858112 bytes)
# Ended (code 256) at Fri Nov 16 16:56:01 SGT 2018, elapsed time 248 seconds

$ nvidia-smi
Fri Nov 16 20:53:27 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.46                 Driver Version: 390.46                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K40m          On   | 00000000:02:00.0 Off |                    0 |
| N/A   44C    P0   170W / 235W |  10410MiB / 11441MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K40m          On   | 00000000:03:00.0 Off |                    0 |
| N/A   41C    P0    99W / 235W |   9366MiB / 11441MiB |     91%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K40m          On   | 00000000:83:00.0 Off |                    0 |
| N/A   29C    P0    61W / 235W |    593MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K40m          On   | 00000000:84:00.0 Off |                    0 |
| N/A   22C    P8    20W / 235W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                   
I don't know what's wrong. I hope you can help solve this problem.

**Comment by Fhrozen** [comment]
Did you try to set the CUDA_VISIBLE_DEVICES to target the GPU ID 2 or 3. GPU 0 or 1 seems to be already used. Before lm_train.py  use CUDA_VISIBLE_DEVICE=2 and report the output please.

**Comment by shanguanma** [comment]
> Did you try to set the CUDA_VISIBLE_DEVICES to target the GPU ID 2 or 3. GPU 0 or 1 seems to be already used. Before lm_train.py use CUDA_VISIBLE_DEVICE=2 and report the output please.

I changed the back end to pytorch, which is the same problem. I changed batch from 300 to 180, then to 20, and then to 2, which is the same problem of insufficient memory.
error log :
# lm_train.py --ngpu 1 --backend chainer --verbose 1 --outdir exp/train_rnnlm_chainer_1layer_unit700_sgd_bs2_word10000 --train-label data/local/wordlm_train/train.txt --valid-label data/local/wordlm_train/valid.txt --resume --layer 1 --unit 700 --opt sgd --batchsize 2 --epoch 20 --maxlen 40 --dict data/local/wordlm_train/wordlist_10000.txt 
# Invoked at Sat Nov 17 12:56:03 SGT 2018 from node05
#
# Started at Sat Nov 17 12:56:27 SGT 2018 on node01
2018-11-17 12:56:27,770 (lm_train:98) INFO: python path = /cm/local/apps/cuda/libs/current/pynvml:/home4/md510/kaldi/tools/jieba/./lib/python2.7/site-packages:/home4/md510/kaldi/tools/jieba/./lib/python2.7/site-packages
2018-11-17 12:56:27,792 (lm_train:115) INFO: backend = chainer
2018-11-17 12:56:28,445 (lm_chainer:228) INFO: chainer version = 5.0.0
2018-11-17 12:56:28,446 (lm_chainer:233) INFO: chainer seed = 1
2018-11-17 12:56:28,446 (lm_chainer:241) INFO: chainer type check is disabled
2018-11-17 12:56:28,970 (lm_chainer:264) INFO: #vocab = 10003
2018-11-17 12:56:28,970 (lm_chainer:265) INFO: #sentences in the training data = 1
2018-11-17 12:56:28,970 (lm_chainer:266) INFO: #tokens in the training data = 1396260
2018-11-17 12:56:28,970 (lm_chainer:267) INFO: oov rate in the training data = 0.46 %
2018-11-17 12:56:28,970 (lm_chainer:268) INFO: #sentences in the validation data = 1
2018-11-17 12:56:28,970 (lm_chainer:269) INFO: #tokens in the validation data = 1455
2018-11-17 12:56:28,970 (lm_chainer:270) INFO: oov rate in the validation data = 0.41 %
2018-11-17 12:56:28,970 (lm_chainer:277) INFO: #iterations per epoch = 1
2018-11-17 12:56:28,970 (lm_chainer:278) INFO: #total iterations = 20
2018-11-17 12:56:49,625 (lm_chainer:295) INFO: writing a model config file to exp/train_rnnlm_chainer_1layer_unit700_sgd_bs2_word10000/model.json
Exception in main training loop: out of memory to allocate 80384 bytes (total 5708742656 bytes)
Traceback (most recent call last):
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/training/trainer.py", line 315, in run
    update()
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/training/updaters/standard_updater.py", line 165, in update
    self.update_core()
  File "/home4/md510/espnet/espnet/lm/lm_chainer.py", line 184, in update_core
    chainer.Variable(t[:, i]))
  File "/home4/md510/espnet/espnet/lm/lm_chainer.py", line 98, in __call__
    state, self.y = self.predictor(state, *args, **kwargs)
  File "/home4/md510/espnet/espnet/lm/lm_chainer.py", line 153, in __call__
    y = self.lo(F.dropout(h[-1]))
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/link.py", line 242, in __call__
    out = forward(*args, **kwargs)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/links/connection/linear.py", line 138, in forward
    return linear.linear(x, self.W, self.b, n_batch_axes=n_batch_axes)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/functions/connection/linear.py", line 289, in linear
    y, = LinearFunction().apply(args)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/function_node.py", line 263, in apply
    outputs = self.forward(in_data)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/functions/connection/linear.py", line 89, in forward
    y = xp.empty((x.shape[0], W.shape[0])).astype(x.dtype)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/cupy/creation/basic.py", line 20, in empty
    return cupy.ndarray(shape, dtype, order=order)
  File "cupy/core/core.pyx", line 150, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 517, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1064, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1085, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 899, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 920, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 694, in cupy.cuda.memory._try_malloc
Will finalize trainer extensions and updater before reraising the exception.
^[[JTraceback (most recent call last):
  File "/home4/md510/espnet/espnet/bin/lm_train.py", line 127, in <module>
    main()
  File "/home4/md510/espnet/espnet/bin/lm_train.py", line 118, in main
    train(args)
  File "/home4/md510/espnet/espnet/lm/lm_chainer.py", line 326, in train
    trainer.run()
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/training/trainer.py", line 329, in run
    six.reraise(*sys.exc_info())
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/training/trainer.py", line 315, in run
    update()
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/training/updaters/standard_updater.py", line 165, in update
    self.update_core()
  File "/home4/md510/espnet/espnet/lm/lm_chainer.py", line 184, in update_core
    chainer.Variable(t[:, i]))
  File "/home4/md510/espnet/espnet/lm/lm_chainer.py", line 98, in __call__
    state, self.y = self.predictor(state, *args, **kwargs)
  File "/home4/md510/espnet/espnet/lm/lm_chainer.py", line 153, in __call__
    y = self.lo(F.dropout(h[-1]))
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/link.py", line 242, in __call__
 out = forward(*args, **kwargs)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/links/connection/linear.py", line 138, in forward
    return linear.linear(x, self.W, self.b, n_batch_axes=n_batch_axes)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/functions/connection/linear.py", line 289, in linear
    y, = LinearFunction().apply(args)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/function_node.py", line 263, in apply
    outputs = self.forward(in_data)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/functions/connection/linear.py", line 89, in forward
    y = xp.empty((x.shape[0], W.shape[0])).astype(x.dtype)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/cupy/creation/basic.py", line 20, in empty
    return cupy.ndarray(shape, dtype, order=order)
  File "cupy/core/core.pyx", line 150, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 517, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1064, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1085, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 899, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 920, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 694, in cupy.cuda.memory._try_malloc
cupy.cuda.memory.OutOfMemoryError: out of memory to allocate 80384 bytes (total 5708742656 bytes)
# Ended (code 256) at Sat Nov 17 12:59:03 SGT 2018, elapsed time 180 seconds

backend is pythorch 
# lm_train.py --ngpu 1 --backend pytorch --verbose 1 --outdir exp/train_rnnlm_pytorch_1layer_unit700_sgd_bs2_word10000 --train-label data/local/wordlm_train/train.txt --valid-label data/local/wordlm_train/valid.txt --resume --layer 1 --unit 700 --opt sgd --batchsize 2 --epoch 20 --maxlen 40 --dict data/local/wordlm_train/wordlist_10000.txt 
# Invoked at Sat Nov 17 12:47:09 SGT 2018 from node05
#
# Started at Sat Nov 17 12:47:28 SGT 2018 on node01
2018-11-17 12:47:30,771 (lm_train:98) INFO: python path = /cm/local/apps/cuda/libs/current/pynvml:/home4/md510/kaldi/tools/jieba/./lib/python2.7/site-packages:/home4/md510/kaldi/tools/jieba/./lib/python2.7/site-packages
2018-11-17 12:47:30,802 (lm_train:115) INFO: backend = pytorch
2018-11-17 12:47:40,380 (lm_pytorch:271) INFO: torch version = 0.4.1
2018-11-17 12:47:40,393 (lm_pytorch:276) INFO: torch seed = 1
2018-11-17 12:47:40,988 (lm_pytorch:301) INFO: #vocab = 10003
2018-11-17 12:47:40,988 (lm_pytorch:302) INFO: #sentences in the training data = 1
2018-11-17 12:47:40,988 (lm_pytorch:303) INFO: #tokens in the training data = 1396260
2018-11-17 12:47:40,988 (lm_pytorch:304) INFO: oov rate in the training data = 0.46 %
2018-11-17 12:47:40,988 (lm_pytorch:305) INFO: #sentences in the validation data = 1
2018-11-17 12:47:40,988 (lm_pytorch:306) INFO: #tokens in the validation data = 1455
2018-11-17 12:47:40,988 (lm_pytorch:307) INFO: oov rate in the validation data = 0.41 %
2018-11-17 12:47:40,988 (lm_pytorch:314) INFO: #iterations per epoch = 1
2018-11-17 12:47:40,988 (lm_pytorch:315) INFO: #total iterations = 20
2018-11-17 12:47:47,987 (lm_pytorch:331) INFO: writing a model config file to exp/train_rnnlm_pytorch_1layer_unit700_sgd_bs2_word10000/model.json
Exception in main training loop: CUDA error: out of memory
Traceback (most recent call last):
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/training/trainer.py", line 315, in run
    update()
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/training/updaters/standard_updater.py", line 165, in update
    self.update_core()
  File "/home4/md510/espnet/espnet/lm/lm_pytorch.py", line 225, in update_core
    non_zeros = torch.sum(x[:, i] != 0, dtype=torch.float)
Will finalize trainer extensions and updater before reraising the exception.
^[[JTraceback (most recent call last):
  File "/home4/md510/espnet/espnet/bin/lm_train.py", line 127, in <module>
    main()
  File "/home4/md510/espnet/espnet/bin/lm_train.py", line 121, in main
    train(args)
  File "/home4/md510/espnet/espnet/lm/lm_pytorch.py", line 365, in train
    trainer.run()
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/training/trainer.py", line 329, in run
    six.reraise(*sys.exc_info())
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/training/trainer.py", line 315, in run
    update()
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/chainer/training/updaters/standard_updater.py", line 165, in update
    self.update_core()
  File "/home4/md510/espnet/espnet/lm/lm_pytorch.py", line 225, in update_core
    non_zeros = torch.sum(x[:, i] != 0, dtype=torch.float)
RuntimeError: CUDA error: out of memory
# Ended (code 256) at Sat Nov 17 12:48:38 SGT 2018, elapsed time 89 seconds

**Comment by takaaki-hori** [comment]
Log message: `2018-11-17 12:56:28,970 (lm_chainer:265) INFO: #sentences in the training data = 1` implies that sentences are not separated by line breaks in `train.txt`.
The input text format for `lm_train.py` has been changed by PR #406 , in which sentences need to be separated line by line, and do not require `<eos>` symbol at the end of each sentence.
I think `out of memory` could happen due to a very long sequence including all sentences written in one line.
Please take a look at the text preprocessing part in recent recipes, e.g. wsj.
