### ISSUE TITLE
Error on Training

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [espnet/espnet#4693]
I tried to run espnet training.
But, the following error occurred.

```
! ./run.sh \
      --stage 1 \
      --stop-stage 5 \
      --g2p pyopenjtalk_accent_with_pause \
      --min_wav_duration 0.38 \
      --fs 44100 \
      --n_fft 2048 \
      --n_shift 512 \
      --dumpdir dump/44k \
      --win_length null \
      --tts_task gan_tts \
      --feats_extract linear_spectrogram \
      --feats_normalize none \
      --train_config ./conf/tuning/finetune_full_band_vits.yaml

2022-10-06T00:48:33 (tts.sh:211:main) ./tts.sh --lang jp --feats_type raw --fs 24000 --n_fft 2048 --n_shift 300 --win_length 1200 --token_type phn --cleaner jaconv --g2p pyopenjtalk --train_config conf/finetune.yaml --inference_config conf/decode.yaml --train_set tr_no_dev --valid_set dev --test_sets dev eval1 --srctexts data/tr_no_dev/text --audio_format flac --stage 1 --stop-stage 5 --g2p pyopenjtalk_accent_with_pause --min_wav_duration 0.38 --fs 44100 --n_fft 2048 --n_shift 512 --dumpdir dump/44k --win_length null --tts_task gan_tts --feats_extract linear_spectrogram --feats_normalize none --train_config ./conf/tuning/finetune_full_band_vits.yaml
2022-10-06T00:48:33 (tts.sh:307:main) Stage 1: Data preparation for data/tr_no_dev, data/dev, etc.
2022-10-06T00:48:33 (data.sh:18:main) local/data.sh 
2022-10-06T00:48:33 (data.sh:46:main) stage 0: local/data_prep.sh
Successfully finished making wav.scp, utt2spk, spk2utt.
Successfully finished making text.
fix_data_dir.sh: kept all 100 utterances.
fix_data_dir.sh: old files are kept in data/all/.backup
Successfully finished preparing data directory.
2022-10-06T00:48:37 (data.sh:51:main) stage 1: scripts/audio/trim_silence.sh
fix_data_dir.sh: kept all 100 utterances.
fix_data_dir.sh: old files are kept in data/all/.backup
2022-10-06T00:49:12 (trim_silence.sh:85:main) Successfully finished silence trimming. [elapsed=35s]
2022-10-06T00:49:12 (data.sh:64:main) stage 2: utils/subset_data_dir.sh
utils/subset_data_dir.sh: reducing #utt from 100 to 40
utils/subset_data_dir.sh: reducing #utt from 40 to 20
utils/subset_data_dir.sh: reducing #utt from 40 to 20
utils/copy_data_dir.sh: copied data from data/all to data/tr_no_dev
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory data/tr_no_dev
utils/fix_data_dir.sh: filtered data/tr_no_dev/segments from 100 to 60 lines based on filter /tmp/kaldi.zIU5/recordings.
fix_data_dir.sh: kept 60 utterances out of 100
fix_data_dir.sh: old files are kept in data/tr_no_dev/.backup
2022-10-06T00:49:13 (data.sh:73:main) Successfully finished. [elapsed=40s]
2022-10-06T00:49:13 (tts.sh:323:main) Stage 2: Format wav.scp: data/ -> dump/44k/raw/
utils/copy_data_dir.sh: copied data from data/tr_no_dev to dump/44k/raw/org/tr_no_dev
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory dump/44k/raw/org/tr_no_dev
2022-10-06T00:49:14 (format_wav_scp.sh:42:main) scripts/audio/format_wav_scp.sh --nj 32 --cmd run.pl --audio-format flac --fs 44100 --segments data/tr_no_dev/segments data/tr_no_dev/wav.scp dump/44k/raw/org/tr_no_dev
2022-10-06T00:49:14 (format_wav_scp.sh:90:main) [info]: using data/tr_no_dev/segments
2022-10-06T00:49:32 (format_wav_scp.sh:142:main) Successfully finished. [elapsed=18s]
utils/copy_data_dir.sh: copied data from data/dev to dump/44k/raw/org/dev
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory dump/44k/raw/org/dev
2022-10-06T00:49:33 (format_wav_scp.sh:42:main) scripts/audio/format_wav_scp.sh --nj 32 --cmd run.pl --audio-format flac --fs 44100 --segments data/dev/segments data/dev/wav.scp dump/44k/raw/org/dev
2022-10-06T00:49:33 (format_wav_scp.sh:90:main) [info]: using data/dev/segments
2022-10-06T00:49:44 (format_wav_scp.sh:142:main) Successfully finished. [elapsed=11s]
utils/copy_data_dir.sh: copied data from data/dev to dump/44k/raw/org/dev
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory dump/44k/raw/org/dev
2022-10-06T00:49:45 (format_wav_scp.sh:42:main) scripts/audio/format_wav_scp.sh --nj 32 --cmd run.pl --audio-format flac --fs 44100 --segments data/dev/segments data/dev/wav.scp dump/44k/raw/org/dev
2022-10-06T00:49:45 (format_wav_scp.sh:90:main) [info]: using data/dev/segments
2022-10-06T00:49:58 (format_wav_scp.sh:142:main) Successfully finished. [elapsed=13s]
utils/copy_data_dir.sh: copied data from data/eval1 to dump/44k/raw/eval1
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory dump/44k/raw/eval1
2022-10-06T00:49:58 (format_wav_scp.sh:42:main) scripts/audio/format_wav_scp.sh --nj 32 --cmd run.pl --audio-format flac --fs 44100 --segments data/eval1/segments data/eval1/wav.scp dump/44k/raw/eval1
2022-10-06T00:49:58 (format_wav_scp.sh:90:main) [info]: using data/eval1/segments
2022-10-06T00:50:12 (format_wav_scp.sh:142:main) Successfully finished. [elapsed=14s]
2022-10-06T00:50:12 (tts.sh:468:main) Stage 3: Remove long/short data: dump/44k/raw/org -> dump/44k/raw
utils/copy_data_dir.sh: copied data from dump/44k/raw/org/tr_no_dev to dump/44k/raw/tr_no_dev
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory dump/44k/raw/tr_no_dev
fix_data_dir.sh: kept all 60 utterances.
fix_data_dir.sh: old files are kept in dump/44k/raw/tr_no_dev/.backup
utils/copy_data_dir.sh: copied data from dump/44k/raw/org/dev to dump/44k/raw/dev
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory dump/44k/raw/dev
fix_data_dir.sh: kept all 20 utterances.
fix_data_dir.sh: old files are kept in dump/44k/raw/dev/.backup
2022-10-06T00:50:13 (tts.sh:523:main) Stage 4: Generate token_list from data/tr_no_dev/text
/usr/bin/python3 /content/espnet/espnet2/bin/tokenize_text.py --token_type phn -f 2- --input dump/44k/raw/srctexts --output dump/44k/token_list/phn_jaconv_pyopenjtalk_accent_with_pause/tokens.txt --non_linguistic_symbols none --cleaner jaconv --g2p pyopenjtalk_accent_with_pause --write_vocabulary true --add_symbol '<blank>:0' --add_symbol '<unk>:1' --add_symbol '<sos/eos>:-1'
Downloading: "https://github.com/r9y9/open_jtalk/releases/download/v1.11.1/open_jtalk_dic_utf_8-1.11.tar.gz"
dic.tar.gz: 100% 22.6M/22.6M [00:00<00:00, 34.1MB/s]
Extracting tar file /usr/local/lib/python3.7/dist-packages/pyopenjtalk/dic.tar.gz
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/espnet/espnet2/bin/tokenize_text.py", line 269, in <module>
    main()
  File "/content/espnet/espnet2/bin/tokenize_text.py", line 265, in main
    tokenize(**kwargs)
  File "/content/espnet/espnet2/bin/tokenize_text.py", line 127, in tokenize
    tokens = tokenizer.text2tokens(line)
  File "/content/espnet/espnet2/text/phoneme_tokenizer.py", line 560, in text2tokens
    tokens = self.g2p(line)
  File "/content/espnet/espnet2/text/phoneme_tokenizer.py", line 80, in pyopenjtalk_g2p_accent_with_pause
    if labels.split("-")[1].split("+")[0] == "pau":
IndexError: list index out of range
```

**Comment by HoneyMack** [comment]
Hello, I have the same issue and I solved it.
The error is because the return type of "pyopenjtalk.run_frontend" has been changed when the package "pyopenjtalk" was updated to version 0.3.0.
You can find the details of the changes at this [site](https://github.com/r9y9/pyopenjtalk/pull/40)

By the way, the quick solution is to downgrade the version of the package "pyopenjtalk" to 0.2.0 as bellow.
```pip install pyopenjtalk==0.2.0```

I hope it will work.

**Comment by Ishihara-Masabumi** [comment]
Thank you very much!
