### ISSUE TITLE
Error in training enahncement model when using a different model config file

### ISSUE THREAD

**Issue by bunny-sung** [espnet/espnet#4716]
Hi,

I am running experiment derivied from the egs2/librimix/enh_diar1 and egs2/wsj0_2mix/enh1 directory. There is no error when I was using the default `conf/tuning/train_enh_conv_tasnet.yaml` and `train_enh_dprnn_tasnet.yaml`.

However when I switched to DPT network: `conf/tuning/train_enh_dptnet.yaml` in the `run.sh` for wsj0_2mix, I got this error at the training stage:

```
<DIR>/tools/anaconda/envs/espnet_enh_2022/bin/python3 <DIR>/espnet2/bin/enh_train.py --collect_stats true --train_data_path_and_name_and_type dump/raw/train/wav.scp,speech_mix,sound --train_data_path_and_name_and_type dump/raw/train/spk1.scp,speech_ref1,sound --train_data_path_and_name_and_type dump/raw/train/spk2.scp,speech_ref2,sound --valid_data_path_and_name_and_type dump/raw/dev/wav.scp,speech_mix,sound --valid_data_path_and_name_and_type dump/raw/dev/spk1.scp,speech_ref1,sound --valid_data_path_and_name_and_type dump/raw/dev/spk2.scp,speech_ref2,sound --train_shape_file exp_dptnet/enh_stats_8k/logdir/train.9.scp --valid_shape_file exp_dptnet/enh_stats_8k/logdir/valid.9.scp --output_dir exp_dptnet/enh_stats_8k/logdir/stats.9 --config conf/tuning/train_enh_dptnet.yaml
Traceback (most recent call last):
  File "<DIR>/tools/anaconda/envs/espnet_enh_2022/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "<DIR>/tools/anaconda/envs/espnet_enh_2022/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "<DIR>/espnet2/bin/enh_train.py", line 23, in <module>
    main()
  File "<DIR>/espnet2/bin/enh_train.py", line 19, in main
    EnhancementTask.main(cmd=cmd)
  File "<DIR>/espnet2/tasks/abs_task.py", line 1019, in main
    cls.main_worker(args)
  File "<DIR>/espnet2/tasks/abs_task.py", line 1121, in main_worker
    model = cls.build_model(args=args)
  File "<DIR>/espnet2/tasks/enh.py", line 468, in build_model
    separator = separator_choices.get_class(args.separator)(
TypeError: __init__() got an unexpected keyword argument 'feature_dim'
# Accounting: time=45 threads=1
```

The repo is cloned and build on Oct 7. Any help will be appreciated. Thanks!

**Comment by Emrys365** [comment]
Sorry for the outdated configuration file. You could make it work by removing the following line from `conf/tuning/train_enh_dptnet.yaml`:
```yaml
    feature_dim: 64
```

**Comment by bunny-sung** [comment]
Thanks! It works.
