### ISSUE TITLE
CUDA out of memory error in ASR

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [espnet/espnet#4731]
CUDA out of memory error in ASR occurred.

```
$ cd espnet/egs2/jsut/asr1
$ ./run.sh

...
...
...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/masabumi_ishihara/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/home/masabumi_ishihara/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/home/masabumi_ishihara/espnet/espnet2/tasks/abs_task.py", line 1019, in main
    cls.main_worker(args)
  File "/home/masabumi_ishihara/espnet/espnet2/tasks/abs_task.py", line 1315, in main_worker
    cls.trainer.run(
  File "/home/masabumi_ishihara/espnet/espnet2/train/trainer.py", line 282, in run
    all_steps_are_invalid = cls.train_one_epoch(
  File "/home/masabumi_ishihara/espnet/espnet2/train/trainer.py", line 556, in train_one_epoch
    retval = model(**batch)
  File "/home/masabumi_ishihara/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/masabumi_ishihara/espnet/espnet2/asr/espnet_model.py", line 257, in forward
    loss_att, acc_att, cer_att, wer_att = self._calc_att_loss(
  File "/home/masabumi_ishihara/espnet/espnet2/asr/espnet_model.py", line 481, in _calc_att_loss
    loss_att = self.criterion_att(decoder_out, ys_out_pad)
  File "/home/masabumi_ishihara/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/masabumi_ishihara/espnet/espnet/nets/pytorch_backend/transformer/label_smoothing_loss.py", line 61, in forward
    kl = self.criterion(torch.log_softmax(x, dim=1), true_dist)
  File "/home/masabumi_ishihara/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/masabumi_ishihara/.local/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 465, in forward
    return F.kl_div(input, target, reduction=self.reduction, log_target=self.log_target)
  File "/home/masabumi_ishihara/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 2916, in kl_div
    reduced = torch.kl_div(input, target, reduction_enum, log_target=log_target)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 14.56 GiB total capacity; 13.19 GiB already allocated; 14.44 MiB free; 13.51 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
# Accounting: time=19 threads=1
# Ended (code 1) at Wed Oct 19 21:15:02 UTC 2022, elapsed time 19 seconds
```

Please tell me how to reduce amount to use of GPU memory.

**Comment by dohe0342** [comment]
I think you should reduce batch bins in config file.

**Comment by Ishihara-Masabumi** [comment]
Thank you.
