### ISSUE TITLE
egs2/seame/asr1/run.sh fails at Stage 3

### ISSUE THREAD

**Issue by shcxlee** [espnet/espnet#4776]
**Describe the bug**
I am trying to train ASR model using the existing SEAME recipe, but `run.sh` fails at `Stage 3`
```bash
2022-11-21T21:55:50 (asr.sh:474:main) Stage 3: Format wav.scp: data/ -> dump/raw
utils/copy_data_dir.sh: copied data from data/train_sp to dump/raw/org/train_sp
utils/validate_data_dir.sh: Successfully validated data-directory dump/raw/org/train_sp
2022-11-21T21:55:59 (format_wav_scp.sh:42:main) scripts/audio/format_wav_scp.sh --nj 32 --cmd run.pl --audio-format flac --fs 16k --segments data/train_sp/segments data/train_sp/wav.scp dump/raw/org/train_sp
2022-11-21T21:55:59 (format_wav_scp.sh:90:main) [info]: using data/train_sp/segments
run.pl: 32 / 32 failed, log is in dump/raw/org/train_sp/logs/format_wav_scp.*.log
```

**Basic environments:**
 - OS information: Linux 4.15.0-192-generic #203-Ubuntu SMP
 - python version: `3.9.15 (main, Nov  4 2022, 16:13:54)  [GCC 11.2.0]`
 - espnet version: `espnet 202209`
 - Git hash: 209ffa0aea77757b9ee6882f06edfbba3aa261ee
   - Commit date: Fri Nov 11 10:24:24 2022 -0500
 - pytorch version: `pytorch 1.12.1+cu102`
 

**Environments from `torch.utils.collect_env`:**
```
Collecting environment information...
PyTorch version: 1.12.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.9.15 (main, Nov  4 2022, 16:13:54)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.15.0-192-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 440.82
cuDNN version: /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.3
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.12.1
[pip3] torch-complex==0.4.3
[pip3] torch-optimizer==0.3.0
[pip3] torchaudio==0.12.1
[pip3] torchvision==0.11.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              hfd86e86_1
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.23.3           py39h14f4228_1
[conda] numpy-base                1.23.3           py39h31eccc5_1
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.1                    pypi_0    pypi
[conda] torch                     1.12.1                   pypi_0    pypi
[conda] torch-complex             0.4.3                    pypi_0    pypi
[conda] torch-optimizer           0.3.0                    pypi_0    pypi
[conda] torchaudio                0.12.1                   pypi_0    pypi
[conda] torchvision               0.11.0               py39_cu102    pytorch
```
You can obtain them by the following command

```
cd <espnet-root>/tools
. ./activate_python.sh
python3 -m torch.utils.collect_env
```

**Task information:**
 - Task: ASR
 - Recipe: SEAME
 - ESPnet2

**To Reproduce**
1. move to a recipe directory: `cd egs2/seame/asr1`
2. execute `asr.sh` with specific arguments, e.g., `run.sh --stage 3 --ngp 2`
3. error log: `/dump/raw/org/train/logs/format_wav_scp.1.log`

**Error logs**
```bash
# pyscripts/audio/format_wav_scp.py --fs 16k --audio-format flac --segment=dump/raw/org/train/logs/segments.1 data/train/wav.scp dump/raw/org/train/data/format.1
# Started at Mon Nov 21 21:26:58 CST 2022
#
2022-11-21 21:26:59,845 (format_wav_scp:43) INFO: /env/esp/bin/python3 pyscripts/audio/format_wav_scp.py --fs 16k --audio-format flac --segment=dump/raw/org/train/logs/segments.1 data/train/wav.scp dump/raw/org/train/data/format.1
0it [00:00, ?it/s]/bin/sh: 1: flac: not found
/env/esp/lib/python3.9/site-packages/kaldiio/utils.py:482: UserWarning: An error happens at loading "flac -c -d -s /espnet/egs2/seame/asr1/data/seame/data/conversation/audio/01NC01FBX_0101.flac |"
  warnings.warn('An error happens at loading "{}"'.format(ark_name))
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/espnet/egs2/seame/asr1/pyscripts/audio/format_wav_scp.py", line 243, in <module>
    main()
  File "/espnet/egs2/seame/asr1/pyscripts/audio/format_wav_scp.py", line 102, in main
    for uttid, (rate, wave) in tqdm(loader):
  File "/env/esp/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/env/esp/lib/python3.9/site-packages/kaldiio/matio.py", line 138, in load_scp_sequential
    for data in SegmentsExtractor(
  File "/env/esp/lib/python3.9/site-packages/kaldiio/matio.py", line 187, in generator
    cached[recodeid] = self.wav_loader[recodeid]
  File "/env/esp/lib/python3.9/site-packages/kaldiio/utils.py", line 480, in __getitem__
    return self._loader(ark_name)
  File "/env/esp/lib/python3.9/site-packages/kaldiio/matio.py", line 241, in load_mat
    return _load_mat(fd, offset, slices, endian=endian)
  File "/env/esp/lib/python3.9/site-packages/kaldiio/matio.py", line 331, in _load_mat
    array = read_kaldi(fd, endian)
  File "/env/esp/lib/python3.9/site-packages/kaldiio/matio.py", line 441, in read_kaldi
    array = read_ascii_mat(fd)
  File "/env/esp/lib/python3.9/site-packages/kaldiio/matio.py", line 605, in read_ascii_mat
    assert len(string) != 0
AssertionError
# Accounting: time=2 threads=1
# Ended (code 1) at Mon Nov 21 21:27:00 CST 2022, elapsed time 2 seconds
```

**Comment by kamo-naoyuki** [comment]
>/bin/sh: 1: flac: not found

You don't have flac command.
