### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'use_ddp'

### ISSUE THREAD

**Issue by lunar333** [espnet/espnet#4779]
when I use asr_trian.py to train a model, it has a error as followed 
~
~
"exp/train_raw_nodev_25ms_pytorch_train/train.log" 17L, 1295C                                                                        6,1           All
# asr_train.py --config conf/train.yaml --ngpu 1 --backend pytorch --outdir exp/train_raw_nodev_25ms_pytorch_train/results --tensorboard-dir tensorboard/train_raw_nodev_25ms_pytorch_train --debugmode 1 --dict data/lang_1char/train_nodev_units.txt --debugdir exp/train_raw_nodev_25ms_pytorch_train --minibatches 0 --verbose 1 --resume --train-json dump_raw_25ms/train_raw_nodev_25ms/data.json --valid-json dump_raw_25ms/train_raw_dev_25ms/data.json
# Started at Wed Nov 23 01:43:45 UTC 2022
#
2022-11-23 01:43:48,198 (asr_train:316) INFO: ngpu: 1
2022-11-23 01:43:48,198 (asr_train:319) INFO: python path = (None)
2022-11-23 01:43:48,198 (asr_train:322) INFO: random seed = 1
2022-11-23 01:43:48,198 (asr_train:339) INFO: backend = pytorch
Traceback (most recent call last):
  File "/disk2/zhh/E2E-SincNet-master/espnet/bin/asr_train.py", line 366, in <module>
    main(sys.argv[1:])
  File "/disk2/zhh/E2E-SincNet-master/espnet/bin/asr_train.py", line 347, in main
    train(args)
  File "/disk2/zhh/miniconda3/envs/pytorch/lib/python3.7/site-packages/espnet/asr/pytorch_backend/asr.py", line 465, in train
    if args.use_ddp:
AttributeError: 'Namespace' object has no attribute 'use_ddp'
# Accounting: time=3 threads=1
# Ended (code 1) at Wed Nov 23 01:43:48 UTC 2022, elapsed time 3 seconds

**Comment by kamo-naoyuki** [comment]
> /disk2/zhh/E2E-SincNet-master/espnet/bin/asr_train.py

> "/disk2/zhh/miniconda3/envs/pytorch/lib/python3.7/site-packages/espnet/asr/pytorch_backend/asr.py

The module paths are mismatched. You may have different versions for each path.
