### ISSUE TITLE
asr_inference.py error

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [espnet/espnet#4784]
In asr_inference.py file, there is the following description.

```
    Examples:
        >>> import soundfile
        >>> speech2text = Speech2Text("asr_config.yml", "asr.pth")
        >>> audio, rate = soundfile.read("speech.wav")
        >>> speech2text(audio)
        [(text, token, token_int, hypothesis object), ...]
```

According to the description, I tried to use Speech2Text for inference.
But the following error has ocurred.

```
:/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "speech2text.py", line 9, in <module>
    speech2text = Speech2Text(config, model)
  File "/home/********/espnet/espnet2/bin/asr_inference.py", line 108, in __init__
    asr_model, asr_train_args = task.build_model_from_file(
  File "/home/********/espnet/espnet2/tasks/abs_task.py", line 1822, in build_model_from_file
    model = cls.build_model(args)
  File "/home/********/espnet/espnet2/tasks/asr.py", line 440, in build_model
    normalize = normalize_class(**args.normalize_conf)
  File "/home/********/espnet/espnet2/layers/global_mvn.py", line 40, in __init__
    stats = np.load(stats_file)
  File "/home/********/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'exp/asr_stats_raw_jp_char_sp/train/feats_stats.npz'
```

Please fix this error or let me know an alternative method.

**Comment by sw005320** [comment]
Which model are you using?
You need to specify the model correctly.

**Comment by Ishihara-Masabumi** [comment]
I used sample recipe of ASR for JSUT corpus at the directory of ~/espnet/egs2/jsut/asr1.
The command line is as follows:
```
./run.sh --gpu 1
```

**Comment by kamo-naoyuki** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'exp/asr_stats_raw_jp_char_sp/train/feats_stats.npz'

You don't have 'exp/asr_stats_raw_jp_char_sp/train/feats_stats.npz' simplly.

**Comment by Ishihara-Masabumi** [comment]
Then, please let me know how to get feats_stats.npz?

**Comment by kamo-naoyuki** [comment]
I think you have it at ~/espnet/egs2/jsut/asr1/exp/asr_stats_raw_jp_char_sp/train/feats_stats.npz

Please solve it by yourself.

**Comment by Ishihara-Masabumi** [comment]
Thank you for your information.
Using "ln -s " command , this error disappeared.

BTW, there is another error happened.
This error is as follows:
```
$ python3 speech2text.py
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
WARNING:root:Using legacy_rel_pos and it will be deprecated in the future.
WARNING:root:Using legacy_rel_selfattn and it will be deprecated in the future.
Traceback (most recent call last):
  File "speech2text.py", line 10, in <module>
    audio, rate = soundfile.read("~/test1.wav")
  File "/home/********/.local/lib/python3.8/site-packages/soundfile.py", line 282, in read
    with SoundFile(file, 'r', samplerate, channels,
  File "/home/********/.local/lib/python3.8/site-packages/soundfile.py", line 655, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/home/********/.local/lib/python3.8/site-packages/soundfile.py", line 1213, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening '~/speech.wav': System error.
```

This  '~/speech.wav' file information is as follows:
![image](https://user-images.githubusercontent.com/23301778/203861756-d40b19e3-e24c-4a7e-9418-eb82942524a2.png)

What's wrong with this?
