### ISSUE TITLE
RuntimeError when creating a recipe for a new dataset

### ISSUE THREAD

**Issue by LiuHeyang0114** [espnet/espnet#4787]
Hi, I've just made a new speech dataset and created recipe based on espnet2. However, RuntimeError occurred on stage 10(ASR collect stats).   

`
Traceback (most recent call last):
  File "/DB/rhome/heyangliu/anaconda3/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/DB/rhome/heyangliu/anaconda3/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/DB/rhome/heyangliu/espnet/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/DB/rhome/heyangliu/espnet/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/DB/rhome/heyangliu/espnet/espnet/espnet2/tasks/abs_task.py", line 976, in main
    cls.main_worker(args)
  File "/DB/rhome/heyangliu/espnet/espnet/espnet2/tasks/abs_task.py", line 1166, in main_worker
    collect_stats(
  File "/DB/rhome/heyangliu/espnet/espnet/tools/venv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
File "/DB/rhome/heyangliu/espnet/espnet/espnet2/main_funcs/collect_stats.py", line 55, in collect_stats                                                              
    for iiter, (keys, batch) in enumerate(itr, 1):                                                                                                                     
  File "/DB/rhome/heyangliu/espnet/espnet/tools/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__                                
    data = self._next_data()                                                                                                                                           
  File "/DB/rhome/heyangliu/espnet/espnet/tools/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data                             
    return self._process_data(data)                                                                                                                                    
  File "/DB/rhome/heyangliu/espnet/espnet/tools/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data                          
    data.reraise()                                                                                                                                                     
  File "/DB/rhome/heyangliu/espnet/espnet/tools/venv/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise                                                
    raise self.exc_type(msg)                                                                                                                                           
RuntimeError: Caught RuntimeError in DataLoader worker process 0.                                                                                                      
Original Traceback (most recent call last):
  File "/DB/rhome/heyangliu/espnet/espnet/tools/venv/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)   
  File "/DB/rhome/heyangliu/espnet/espnet/tools/venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 35, in fetch
    return self.collate_fn(data)              
  File "/DB/rhome/heyangliu/espnet/espnet/espnet2/train/collate_fn.py", line 38, in __call__    
    return common_collate_fn(
  File "/DB/rhome/heyangliu/espnet/espnet/espnet2/train/collate_fn.py", line 94, in common_collate_fn
    tensor = pad_list(tensor_list, pad_value)
  File "/DB/rhome/heyangliu/espnet/espnet/espnet/nets/pytorch_backend/nets_utils.py", line 52, in pad_list
    pad[i, : xs[i].size(0)] = xs[i]
RuntimeError: expand(torch.FloatTensor{[18560, 2]}, size=[18560]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)                      
`

It's little strange for this error happened only on few split. If I set nj=128, only stats2 and stats3 meet this error; If I set nj=16, only stat1 meet this error. For example, stats1 have this error, then 'exp/.../logdir/stats.2/train' only has two files(speech_shape and text_shape). text_shape ends prematurely.

At first, I think part of my dataset  is dirty, which caused the error. However, after I deleted utterances where text_file ends, the error happens earlier, which means "clean" utterance becomes "dirty". So I think my thinking is wrong. 

I don't think this should be a problem with the code, as I've run recipe on gigaspeech and librispeech. However, it seems to me that my data and code are similar to recipe on the above dataset. Could you give some advice on the cause of this error and how to fix it? Thanks a lot.

**Comment by kamo-naoyuki** [comment]
I suppose that some of your audio files have multi-channels, but some have single or different number of channels.   

Please check your audio files one by one.

e.g. 
```
<your.scp awk  '{ print $2 }' | soxi
```

**Comment by LiuHeyang0114** [comment]
> I suppose that some of your audio files have multi-channels, but some have single or different number of channels.
> 
> Please check your audio files one by one.
> 
> e.g.
> 
> ```
> <your.scp awk  '{ print $2 }' | soxi
> ```
Thanks for your advice. I'm sure part of my dataset has improper wav file, for I delete more and it works. I'll check it.
