### ISSUE TITLE
Bug in espnet2.main_funcs.pack_funcs.get_dict_from_cache: outpath = meta.parent.parent

### ISSUE THREAD

**Issue by boeddeker** [espnet/espnet#4835]
**Describe the bug**

`espnet_model_zoo` changes downloaded files in second run, while it should only read the files -> Not process safe, when it should only read.

I tried to use https://zenodo.org/record/3966501 and got `EOFError: Ran out of input` errors from torch, when I started multiple experiments simultaneously with the same network file system.
To avoid, that each experiment downloads and writes the downloaded files (A lockfile don't work reliably on every network file systems), I executed the ASR system once before to trigger the download.

Now I found in `espnet2.main_funcs.pack_funcs.get_dict_from_cache` the code 
https://github.com/espnet/espnet/blob/aa5cc02cf830620a5c517a9efddaaadd1bf803ad/espnet2/main_funcs/pack_funcs.py#L161
, but in https://zenodo.org/record/3966501 is the `meta.yaml` in the root folder, so `outpath` will be the parent folder of the extracted files and not the folder, where the files are extracted. Here, the folder on my system with the downloaded files:

```
$ ~/deploy/espnet_model_zoo/espnet_model_zoo/653d10049fdc264f694f57b49849343e$ ls -1
asr_train_asr_transformer_e18_raw_bpe_sp_valid.acc.best.zip
asr_train_asr_transformer_e18_raw_bpe_sp_valid.acc.best.zip.lock
data
exp
meta.yaml
meta.yaml.lock
url
$ ~/deploy/espnet_model_zoo/espnet_model_zoo/653d10049fdc264f694f57b49849343e$ cat meta.yaml
espnet: 0.8.0
files:
  asr_model_file: exp/asr_train_asr_transformer_e18_raw_bpe_sp/54epoch.pth
  lm_file: exp/lm_train_lm_adam_bpe/17epoch.pth
python: "3.7.3 (default, Mar 27 2019, 22:11:17) \n[GCC 7.3.0]"
timestamp: 1600169559.061977
torch: 1.6.0
yaml_files:
  asr_train_config: exp/asr_train_asr_transformer_e18_raw_bpe_sp/config.yaml
  lm_train_config: exp/lm_train_lm_adam_bpe/config.yaml
```

so the following checks, if the files exist fails:

https://github.com/espnet/espnet/blob/aa5cc02cf830620a5c517a9efddaaadd1bf803ad/espnet2/main_funcs/pack_funcs.py#L174-L176

and the `download_and_unpack` executes the `unpack` function, which will overwrite the existing files:

https://github.com/espnet/espnet_model_zoo/blob/4d5855ac04fa137da6ba2c45f3f5aab7a1b398a6/espnet_model_zoo/downloader.py#L402-L412

And this can break another process.

**Task information:**
 - Task: ASR
 - Recipe: librispeech
 - ESPnet2

**To Reproduce**

Execute this
```python
from espnet_model_zoo.downloader import ModelDownloader
d = ModelDownloader()
d.download_and_unpack('Shinji Watanabe/librispeech_asr_train_asr_transformer_e18_raw_bpe_sp_valid.acc.best')
```
and go to the download dir (In my case `.../espnet_model_zoo/653d10049fdc264f694f57b49849343e`) and check the timestamps of the files (i.e. `ls -ahl`).
Execute the code snippet again in a fresh python shell and check again the time stamps.
All files, except `url` and the folders, will have a new time stamp.

Btw.: Is there an alternative to `download_and_unpack` with the same return value, but without download or unpack?

**Error logs**
```
Traceback (most recent call last):
  File "/.../python3.9/[runpy.py](http://runpy.py/)", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File ".../python3.9/[runpy.py](http://runpy.py/)", line 87, in _run_code
    exec(code, run_globals)
  File "...", line 118, in <module>
    [fire.Fire](http://fire.fire/)(main)
  File ".../python3.9/site-packages/fire/[core.py](http://core.py/)", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File ".../fire/[core.py](http://core.py/)", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File ".../fire/[core.py](http://core.py/)", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "...", line 54, in main
    apply_asr = ESPnetASR(model_tag=model_tag).apply_asr
  File "...", line 143, in __init__
    speech2text = Speech2Text(  # Speech2Text.from_pretrained
  File ".../espnet2/bin/asr_[inference.py](http://inference.py/)", line 98, in __init__
    asr_model, asr_train_args = [task.build](http://task.build/)_model_from_file(
  File ".../espnet2/tasks/abs_[task.py](http://task.py/)", line 1826, in build_model_from_file
    model.load_state_dict(torch.load(model_file, map_location=device))
  File ".../torch/[serialization.py](http://serialization.py/)", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File ".../torch/[serialization.py](http://serialization.py/)", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
```

**Comment by sw005320** [comment]
I see. Thanks for the report!
@kamo-naoyuki, can you take a look at this?

**Comment by kamo-naoyuki** [comment]
@boeddeker Thank you for pointing out! I have also met the same problem, but I couldn't figure out the problem ( and I forgot it for a long time...)

I'll check it.

**Comment by boeddeker** [comment]
I am not sure, how you want to fix it, but here my workaround (may give you an inspiration for a fix):

```python
# File espnet_model_zoo/downloader.py
    def download_and_unpack(..):
        ...
                info = get_dict_from_cache(meta_yaml, outpath=outdir)
        ...
```
and
```python
# File espnet2/main_funcs/pack_funcs/downloader.py
def get_dict_from_cache(meta: Union[Path, str], outpath=None) -> Optional[Dict[str, str]]:
    if outpath is None:
        outpath = meta.parent.parent
    ...
```
where I added `outpath` as argument for `get_dict_from_cache`.
Sadly, this fix is scattered across two packages: A new `espnet_model_zoo` with this fix  wouldn't work with an old `espnet` without this fix.
