### ISSUE TITLE
problem running fastspeech2+hifigan

### ISSUE THREAD

**Issue by roholazandie** [espnet/espnet#4897]
I am running the following command to train the fastspeech2+hifigan:

```
./run.sh \
    --stage 6 \
    --tts_task gan_tts \
    --train_config ./conf/tuning/train_joint_conformer_fastspeech2_hifigan.yaml
```
but get the following error. I have the `stats_file` but I think it can't find it. I already trained both fastspeech2, fastspeech, tacotron and hifigan and parallelwavgan without any problem 

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rohola/codes/espnet/espnet2/bin/gan_tts_train.py", line 22, in <module>
    main()
  File "/home/rohola/codes/espnet/espnet2/bin/gan_tts_train.py", line 18, in main
    GANTTSTask.main(cmd=cmd)
  File "/home/rohola/codes/espnet/espnet2/tasks/abs_task.py", line 1019, in main
    cls.main_worker(args)
  File "/home/rohola/codes/espnet/espnet2/tasks/abs_task.py", line 1121, in main_worker
    model = cls.build_model(args=args)
  File "/home/rohola/codes/espnet/espnet2/tasks/gan_tts.py", line 342, in build_model
    pitch_normalize = pitch_normalize_class(
TypeError: __init__() missing 1 required positional argument: 'stats_file'
# Accounting: time=5 threads=1
# Ended (code 1) at Mon Jan 30 12:55:37 MST 2023, elapsed time 5 seconds

```

**Comment by kan-bayashi** [comment]
Maybe you forgot to specify tts_stats_dir, which including stats of pitch and energy features.
