### ISSUE TITLE
s3prl inference issue (wav2vec2) 

### ISSUE THREAD

**Issue by SatwikDutta** [espnet/espnet#4910]
**Describe the bug**
ASR model has been trained and packed along with other required materials (stage 14) to be used for inference in another cluster/system. During inference "RuntimeError: Error(s) in loading state_dict for ESPnetASRModel" error is encountered, even though the model reflected by asr_model_file argument is present. 

**Basic environments:**
- OS information: Linux 5.15.0-48-generic #54~20.04.1-Ubuntu SMP Thu Sep 1 16:17:26 UTC 2022 x86_64
- python version: `3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0]`
- espnet version: `espnet 0.10.7a1`
- pytorch version: `pytorch 1.10.1+cu113`
- Git hash: `18ca0993d53b8ec4a6ec44de87d2bd663734b06d`
  - Commit date: `Tue Feb 8 21:40:17 2022 +0900`
 
**Environments from `torch.utils.collect_env`:**
e.g.,
```
Collecting environment information...
PyTorch version: 1.10.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-48-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration: 
GPU 0: Tesla K80
GPU 1: Tesla K80
GPU 2: Tesla K80
GPU 3: Tesla K80
GPU 4: Tesla K80
GPU 5: Tesla K80

Nvidia driver version: 470.141.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.1
[pip3] numpydoc==1.1.0
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.10.1+cu113
[pip3] torch-complex==0.2.1
[pip3] torch-optimizer==0.1.0
[pip3] torchaudio==0.10.1+cu113
[pip3] warpctc-pytorch==0.2.2+torch16.cuda92
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.2.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.21.1                   pypi_0    pypi
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1  
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.1                    pypi_0    pypi
[conda] torch                     1.10.1+cu113             pypi_0    pypi
[conda] torch-complex             0.2.1                    pypi_0    pypi
[conda] torch-optimizer           0.1.0                    pypi_0    pypi
[conda] torchaudio                0.10.1+cu113             pypi_0    pypi
[conda] warpctc-pytorch           0.2.2+torch16.cuda92          pypi_0    pypi
```

**Task information:**
 - Task: ASR
 - Recipe: Referred from WSJ (using my own data)
 - ESPnet2

**To Reproduce**
1. Training successfully finished on a GPU cluster 
2. Due to memory constraints on GPU cluster, moving the inference stage to another cluster 
3. Steps followed: Create & move the zipped model (done using stage 14, just ignore the Results.md)
4. Model trained using asr_config: conf/tuning/train_asr_conformer_s3prlfrontend_wav2vec2.yaml
5. Re-run from Stage 12
6. Specify the error log, e.g., `exp/asr_**/lm_3b_am_1d/test_**/logdir/asr_inference.1.log`

**Error logs**
Paste the error logs. If applicable, add screenshots to help explain your problem.

```
# Started at Fri Feb  3 22:35:30 CST 2023
#
/scratch/sxd180020/anaconda3/bin/python3 /scratch2/sxd180020/espnet/espnet2/bin/asr_inference.py --batch_size 1 --ngpu 0 --data_path_and_name_and_type dump/raw/test_v2/wav.scp,speech,sound --key_file exp/asr_3d/lm_3b_am_1d/test_v2/keys.1.scp --asr_train_config exp/asr_3d/config.yaml --asr_model_file exp/asr_3d/valid.acc.ave.pth --output_dir exp/asr_3d/lm_3b_am_1d/test_v2/logdir/output.1 --config conf/decode.yaml
2023-02-03 22:35:36,155 (asr:399) INFO: Vocabulary size: 160
2023-02-03 22:35:36,959 (download:100) INFO: Requesting URL: https://huggingface.co/s3prl/converted_ckpts/resolve/main/wav2vec_vox_new.pt
2023-02-03 22:35:36,960 (filelock:274) INFO: Lock 140550979605552 acquired on /home/sxd180020/.cache/s3prl/download/70a1c0d7bd4d235fe73bc359f70cc91a165d2405f6608fb01c504b8ba1244ac6.wav2vec_vox_new.pt.lock
2023-02-03 22:35:36,960 (filelock:318) INFO: Lock 140550979605552 released on /home/sxd180020/.cache/s3prl/download/70a1c0d7bd4d235fe73bc359f70cc91a165d2405f6608fb01c504b8ba1244ac6.wav2vec_vox_new.pt.lock
2023-02-03 22:35:36,960 (download:108) INFO: Using URL's local file: /home/sxd180020/.cache/s3prl/download/70a1c0d7bd4d235fe73bc359f70cc91a165d2405f6608fb01c504b8ba1244ac6.wav2vec_vox_new.pt
[Featurizer] - Take a list of 25 features and weighted sum them.
[Featurizer] - The selected feature hidden_states's downsample rate is 320
2023-02-03 22:35:54,493 (s3prl:143) INFO: Pretrained S3PRL frontend model parameters reloaded!
Traceback (most recent call last):
  File "/scratch/sxd180020/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/scratch/sxd180020/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/scratch2/sxd180020/espnet/espnet2/bin/asr_inference.py", line 606, in <module>
    main()
  File "/scratch2/sxd180020/espnet/espnet2/bin/asr_inference.py", line 602, in main
    inference(**kwargs)
  File "/scratch2/sxd180020/espnet/espnet2/bin/asr_inference.py", line 392, in inference
    speech2text = Speech2Text.from_pretrained(
  File "/scratch2/sxd180020/espnet/espnet2/bin/asr_inference.py", line 314, in from_pretrained
    return Speech2Text(**kwargs)
  File "/scratch2/sxd180020/espnet/espnet2/bin/asr_inference.py", line 85, in __init__
    asr_model, asr_train_args = ASRTask.build_model_from_file(
  File "/scratch2/sxd180020/espnet/espnet2/tasks/abs_task.py", line 1832, in build_model_from_file
    model.load_state_dict(torch.load(model_file, map_location=device))
  File "/scratch/sxd180020/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ESPnetASRModel:
        Missing key(s) in state_dict: "frontend.upstream.model.mask_emb", "frontend.upstream.model.feature_extractor.conv_layers.0.0.weight", "frontend.upstream.model.feature_extractor.conv_layers.0.0.bias", "frontend.upstream.mode>
        Unexpected key(s) in state_dict: "frontend.upstream.upstream.model.mask_emb", "frontend.upstream.upstream.model.feature_extractor.conv_layers.0.0.weight", "frontend.upstream.upstream.model.feature_extractor.conv_layers.0.0.>
# Accounting: time=27 threads=1
# Ended (code 1) at Fri Feb  3 22:35:57 CST 2023, elapsed time 27 seconds
```

**Comment by boeddeker** [comment]
I had a similar issue: `Missing keys` had two times "upstream" and `Unexpected keys` just ones.

My workaround was to modify in `espnet2/tasks/abs_task.py` the code
```python
    def build_model_from_file(...):
        ...
            model.load_state_dict(torch.load(model_file, map_location=device))
        ...
```
to
```python
    def build_model_from_file(...):
        ...
            state_dict = torch.load(model_file, map_location=device)
            try:
                model.load_state_dict(state_dict)
            except RuntimeError:
                if any(['frontend.upstream.model' in k for k in state_dict.keys()]):
                    if any(['frontend.upstream.upstream.model' in k for k in dict(model.named_parameters())]):
                        state_dict = {
                            k.replace(
                                'frontend.upstream.model',
                                'frontend.upstream.upstream.model'
                            ): v
                            for k, v in state_dict.items()
                        }
                        model.load_state_dict(state_dict)
                    else:
                        raise
                else:
                    raise
        ...
```

And here is a toy example to reproduce:

```python
    from espnet_model_zoo.downloader import ModelDownloader
    from espnet2.bin.asr_inference import Speech2Text
    d = ModelDownloader()
    try:
        d.download_and_unpack('espnet/simpleoier_librispeech_asr_train_asr_conformer7_wavlm_large_raw_en_bpe5000_sp')
    except FileNotFoundError:
        # FileNotFoundError: [Errno 2] No such file or directory: '/projects/tir5/users/xuankaic/experiments/espnet/egs2/librispeech/asr1/exp/asr_train_asr_conformer7_wavlm_large_raw_en_bpe5000_sp/config.yaml'
        pass

    base = Path(f'{d.cachedir}/models--espnet--simpleoier_librispeech_asr_train_asr_conformer7_wavlm_large_raw_en_bpe5000_sp/snapshots/18573cae75cd4ecc952ebbf8c0e22ebbfecb95e0/projects/tir5/users/xuankaic/experiments/espnet/egs2/librispeech/asr1/')
    espnet_model_kwargs = {
        'asr_train_config': str(base / 'exp/asr_train_asr_conformer7_wavlm_large_raw_en_bpe5000_sp/config.yaml'),
        'lm_train_config': str(base / 'exp/lm_train_lm_transformer2_en_bpe5000/config.yaml'),
        'asr_model_file': str(base / 'exp/asr_train_asr_conformer7_wavlm_large_raw_en_bpe5000_sp/valid.acc.ave_10best.pth'),
        'lm_file': str(base / 'exp/lm_train_lm_transformer2_en_bpe5000/4epoch.pth'),
    }
    speech2text = Speech2Text(**espnet_model_kwargs)

# RuntimeError: Error(s) in loading state_dict for ESPnetASRModel:
#     	Missing key(s) in state_dict: "frontend.upstream.upstream.model.mask_emb", "frontend.upstream.upstream.model.feature_extractor.conv_layers.0.0.weight", ...
#     	Unexpected key(s) in state_dict: "frontend.upstream.model.mask_emb", "frontend.upstream.model.feature_extractor.conv_layers.0.0.weight", ...

```

**Comment by sw005320** [comment]
Thanks for the report.
@simpleoier, do you have any ideas?

**Comment by boeddeker** [comment]
How about adding some backward compatibility code, similar to my workaround?
I guess it will take a while until everyone uses the new s3prl and has the models trained with the new s3prl. 
So users will hit for a while both error combinations (old code new model and new code old model).

Initially I wanted to "patch" espnet from outside, but sadly the dispatch in Speech2Text is hard-coded and from outside it is not possible to "fix" it via inheritance.

**Comment by simpleoier** [comment]
Hi @boeddeker , thanks for the suggestion! I am thinking about adding a check when loading a pretrained checkpoint. If it has an error when loading, I'll check if it is due to the upstream name. If so, it will replace the name with `upstream.upstream`.
