### ISSUE TITLE
How2-2000h recipe

### ISSUE THREAD

**Issue by chlorane** [espnet/espnet#4924]
Sorry for another issue on how2-2000h recipe.
The former bug related to data loading has been fixed.
However, when I trying to run the script, I found another error:
2023-02-08T13:03:33 (asr.sh:605:main) Stage 3: extracted extract: data/ -> dump/extracted
utils/copy_data_dir.sh: copied data from data/tr_2000h_utt to dump/extracted/org/tr_2000h_utt
utils/validate_data_dir.sh: Error: in dump/extracted/org/tr_2000h_utt, recording-ids extracted from segments and wav.scp
utils/validate_data_dir.sh: differ, partial diff is:
--- /tmp/kaldi.8kht/recordings  2023-02-08 13:04:05.006497798 +0900
+++ /tmp/kaldi.8kht/recordings.wav      2023-02-08 13:04:05.270492504 +0900
@@ -1,68333 +1,950026 @@
---7E2sU6zP4
---8pSDeC-fg
---KGmgr2HZA
...
+zzxz7iG81kI_4
+zzxz7iG81kI_5
+zzxz7iG81kI_6
+zzxz7iG81kI_7
+zzxz7iG81kI_8
+zzxz7iG81kI_9
[Lengths are /tmp/kaldi.8kht/recordings=68333 versus /tmp/kaldi.8kht/recordings.wav=950026]

I checked the files and found that asr1/data/tr_2000h_utt/wav.scp will be modified at the beginning of stage 3:
There used to be
--7E2sU6zP4 <DUMMY>
--8pSDeC-fg <DUMMY>
--KGmgr2HZA <DUMMY>
--LqJz1hVo4 <DUMMY>
--MPytKoRmA <DUMMY>
--QuVyRhuK4 <DUMMY>
--Qy-dG1a8c <DUMMY>
--U9mKsZi2Y <DUMMY>
--Z6x1PHoLA <DUMMY>
--dANj_01AU <DUMMY>
--hnpduVMzE <DUMMY>
but to be modified as
--7E2sU6zP4_1 <DUMMY>
--7E2sU6zP4_10 <DUMMY>
--7E2sU6zP4_11 <DUMMY>
--7E2sU6zP4_12 <DUMMY>
--7E2sU6zP4_13 <DUMMY>
--7E2sU6zP4_14 <DUMMY>
--7E2sU6zP4_2 <DUMMY>
--7E2sU6zP4_3 <DUMMY>
--7E2sU6zP4_4 <DUMMY>
--7E2sU6zP4_5 <DUMMY>
--7E2sU6zP4_6 <DUMMY>
--7E2sU6zP4_7 <DUMMY>
--7E2sU6zP4_8 <DUMMY>
--7E2sU6zP4_9 <DUMMY>
--8pSDeC-fg_10 <DUMMY>
--8pSDeC-fg_11 <DUMMY>
--8pSDeC-fg_12 <DUMMY>
--8pSDeC-fg_13 <DUMMY>
--8pSDeC-fg_14 <DUMMY>
--8pSDeC-fg_15 <DUMMY>
--8pSDeC-fg_16 <DUMMY>
--8pSDeC-fg_17 <DUMMY>
--8pSDeC-fg_2 <DUMMY>
--8pSDeC-fg_3 <DUMMY>
--8pSDeC-fg_4 <DUMMY>
--8pSDeC-fg_5 <DUMMY>
--8pSDeC-fg_6 <DUMMY>
--8pSDeC-fg_7 <DUMMY>
--8pSDeC-fg_8 <DUMMY>
--8pSDeC-fg_9 <DUMMY>

I tried to copy the original wav.scp from backup files and the program can process training data, but the same thing happens to cv05_utt directory.
2023-02-08T13:11:42 (asr.sh:605:main) Stage 3: extracted extract: data/ -> dump/extracted
utils/copy_data_dir.sh: copied data from data/tr_2000h_utt to dump/extracted/org/tr_2000h_utt
utils/validate_data_dir.sh: Successfully validated data-directory dump/extracted/org/tr_2000h_utt
scripts/feats/feat_to_shape.sh --nj 32 --cmd run.pl dump/extracted/org/tr_2000h_utt/feats.scp dump/extracted/org/tr_2000h_utt/feats_shape
utils/copy_data_dir.sh: copied data from data/cv05_utt to dump/extracted/org/cv05_utt
utils/validate_data_dir.sh: Error: in dump/extracted/org/cv05_utt, recording-ids extracted from segments and wav.scp
utils/validate_data_dir.sh: differ, partial diff is:
--- /tmp/kaldi.d3q3/recordings  2023-02-08 13:16:21.043631597 +0900
+++ /tmp/kaldi.d3q3/recordings.wav      2023-02-08 13:16:21.063631192 +0900
@@ -1,2520 +1,34687 @@
---qXJuDtHPw
--0adCyrTpPE
--0ot068wyoc
...
+zzo6B3VV5ks_4
+zzo6B3VV5ks_5
+zzo6B3VV5ks_6
+zzo6B3VV5ks_7
+zzo6B3VV5ks_8
+zzo6B3VV5ks_9
[Lengths are /tmp/kaldi.d3q3/recordings=2520 versus /tmp/kaldi.d3q3/recordings.wav=34687]

So I guess there is still something wrong in the script.

**Comment by sw005320** [comment]
Can you remove the `data` directory and run stage 1 again?

**Comment by chlorane** [comment]
> Can you remove the `data` directory and run stage 1 again?

In fact, I carefully checked the script and commented the following line:
(asr.sh, near line 615)
#                <data/"${dset}"/feats.scp awk ' { print($1,"<DUMMY>") }' > data/"${dset}"/wav.scp
It seems the following progress goes smoothly.
Now I'm wondering whether the training is smooth (The 1100G memory required is too large for our computer).

**Comment by sw005320** [comment]
I see.
@roshansh-cmu, could I ask you to check https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/asr1/asr.sh#L623 ?
We do not use the feature input so often, and some bugs may be inserted....

**Comment by roshansh-cmu** [comment]
Thanks for the catch @chlorane- regarding memory issues, you should trim the features to fit the GPU capability you have- we used a custom Python script and didn't release that since different users may have different GPUs. We can discuss if this is very challenging for you. 

@sw005320 - I believe fix #4926 should work

**Comment by chlorane** [comment]
> Thanks for the catch @chlorane- regarding memory issues, you should trim the features to fit the GPU capability you have- we used a custom Python script and didn't release that since different users may have different GPUs. We can discuss if this is very challenging for you.
> 
> @sw005320 - I believe fix #4926 should work

I'm now adjusting num_splits_lm parameter to try the training.

**Comment by chlorane** [comment]
I received the following error. Does this mean I need to use Cuda 10.0? Now I'm using Cuda 11.3.
[compute04] 2023-02-09 10:22:49,083 (abs_task:1527) INFO: [valid] Batch sampler: LengthBatchSampler(N-batch=2, batch_bins=60000000, sort_in_batch=descending, sort_batch=descending)
[compute04] 2023-02-09 10:22:49,083 (abs_task:1528) INFO: [valid] mini-batch sizes summary: N-batch=2, mean=16884.5, min=477, max=33292
[compute04] 2023-02-09 10:22:49,373 (abs_task:1526) INFO: [plot_att] dataset:
ESPnetDataset(
  speech: {"path": "dump/extracted/cv05_utt/feats.scp", "type": "kaldi_ark"}
  text: {"path": "dump/extracted/cv05_utt/text", "type": "text"}
  preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x7ff73b660940>)
[compute04] 2023-02-09 10:22:49,373 (abs_task:1527) INFO: [plot_att] Batch sampler: UnsortedBatchSampler(N-batch=33769, batch_size=1, key_file=exp/asr_stats_extracted_en_bpe1000/valid/speech_shape, 
[compute04] 2023-02-09 10:22:49,373 (abs_task:1528) INFO: [plot_att] mini-batch sizes summary: N-batch=3, mean=1.0, min=1, max=1
[compute04] 2023-02-09 10:22:50,265 (trainer:276) INFO: 1/100epoch started
[compute04] 2023-02-09 10:22:50,357 (multiple_iter_factory:32) INFO: Building 0th iter-factory...
[compute04] 2023-02-09 10:22:50,361 (abs_task:1526) INFO: [train] dataset:
ESPnetDataset(
  speech: {"path": "exp/asr_stats_extracted_en_bpe1000/splits65536/feats.scp/split.35180", "type": "kaldi_ark"}
  text: {"path": "exp/asr_stats_extracted_en_bpe1000/splits65536/text/split.35180", "type": "text"}
  preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x7ff6c75c10a0>)
[compute04] 2023-02-09 10:22:50,362 (abs_task:1527) INFO: [train] Batch sampler: LengthBatchSampler(N-batch=1, batch_bins=60000000, sort_in_batch=descending, sort_batch=descending)
[compute04] 2023-02-09 10:22:50,362 (abs_task:1528) INFO: [train] mini-batch sizes summary: N-batch=1, mean=14.0, min=14, max=14
Traceback (most recent call last):
  File "/home/nas02home/conda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/nas02home/conda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/nas02/homes/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/nas02/homes/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/nas02/homes/espnet/espnet2/tasks/abs_task.py", line 1019, in main
    cls.main_worker(args)
  File "/nas02/homes/espnet/espnet2/tasks/abs_task.py", line 1315, in main_worker
    cls.trainer.run(
  File "/nas02/homes/espnet/espnet2/train/trainer.py", line 282, in run
    all_steps_are_invalid = cls.train_one_epoch(
  File "/nas02/homes/espnet/espnet2/train/trainer.py", line 556, in train_one_epoch
    retval = model(**batch)
  File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nas02/homes/espnet/espnet2/asr/espnet_model.py", line 202, in forward
    encoder_out, encoder_out_lens = self.encode(speech, speech_lengths)
  File "/nas02/homes/espnet/espnet2/asr/espnet_model.py", line 352, in encode
    encoder_out, encoder_out_lens, _ = self.encoder(feats, feats_lengths)
  File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nas02/homes/espnet/espnet2/asr/encoder/longformer_encoder.py", line 336, in forward
    xs_pad, masks = self.encoders(xs_pad, masks)
  File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nas02/homes/espnet/espnet/nets/pytorch_backend/transformer/repeat.py", line 18, in forward
    args = m(*args)
  File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nas02/homes/espnet/espnet/nets/pytorch_backend/conformer/encoder_layer.py", line 141, in forward
    x_att = self.self_attn(x_q, x, x, mask)
  File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nas02/homes/espnet/espnet/nets/pytorch_backend/transformer/longformer_attention.py", line 49, in forward
    output, self.attention = self.attention_layer(
  File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nas02home/conda/envs/espnet/lib/python3.8/site-packages/longformer/longformer.py", line 149, in forward
    attn_weights = diagonaled_mm_tvm(q, k, self.attention_window, self.attention_dilation, False, 0, False)
  File "/home/nas02home/conda/envs/espnet/lib/python3.8/site-packages/longformer/diagonaled_mm_tvm.py", line 261, in forward
    output = DiagonaledMM._diagonaled_mm(t1, t2, w, d, is_t1_diagonaled=is_t1_diagonaled, padding=padding, autoregressive=autoregressive)
  File "/home/nas02home/conda/envs/espnet/lib/python3.8/site-packages/longformer/diagonaled_mm_tvm.py", line 191, in _diagonaled_mm
    _diagonaled_mm_function = DiagonaledMM._get_function(dtype=dtype, device=device)
  File "/home/nas02home/conda/envs/espnet/lib/python3.8/site-packages/longformer/diagonaled_mm_tvm.py", line 143, in _get_function
    diagonaled_mm = DiagonaledMM._load_compiled_function(dtype, device)  # try to load from disk
  File "/home/nas02home/conda/envs/espnet/lib/python3.8/site-packages/longformer/diagonaled_mm_tvm.py", line 126, in _load_compiled_function
    from tvm.module import load  # this can be the small runtime python library, and doesn't need to be the whole thing
  File "/home/nas02home/conda/envs/espnet/lib/python3.8/site-packages/tvm/module.py", line 23, in <module>
    from ._ffi.function import ModuleBase, _set_class_module
  File "/home/nas02home/conda/envs/espnet/lib/python3.8/site-packages/tvm/_ffi/function.py", line 24, in <module>
    from .base import _LIB, check_call, py_str, c_str, string_types, _FFI_MODE
  File "/home/nas02home/conda/envs/espnet/lib/python3.8/site-packages/tvm/_ffi/base.py", line 60, in <module>
    _LIB, _LIB_NAME = _load_lib()
  File "/home/nas02home/conda/envs/espnet/lib/python3.8/site-packages/tvm/_ffi/base.py", line 52, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/home/nas02home/conda/envs/espnet/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.10.0: cannot open shared object file: No such file or directory
# Accounting: time=90 threads=1
# Ended (code 1) at Thu Feb  9 10:23:03 JST 2023, elapsed time 90 seconds

I tried to use Cuda 10.0, Python 3.6 and make the file in espnet/tools, another error happens:
2023-02-09T10:51:52 (install_torch.sh:149:main) [INFO] python_version=3.6.13
2023-02-09T10:51:52 (install_torch.sh:150:main) [INFO] torch_version=1.1.0
2023-02-09T10:51:52 (install_torch.sh:151:main) [INFO] cuda_version=10.0
2023-02-09T10:51:53 (install_torch.sh:288:main) [ERROR] This script doesn't support pytorch=1.1.0

**Comment by roshansh-cmu** [comment]
Yes you do. 

Alternatively, you can create a custom cuda kernel for Cuda 11.3 using steps outlined in https://github.com/allenai/longformer/blob/master/scripts/cheatsheet.txt

**Comment by chlorane** [comment]
> Yes you do.
> 
> Alternatively, you can create a custom cuda kernel for Cuda 11.3 using steps outlined in https://github.com/allenai/longformer/blob/master/scripts/cheatsheet.txt

Will the script run on cuda 10.2?

**Comment by roshansh-cmu** [comment]
No

**Comment by chlorane** [comment]
However, when using Cuda 10.0 and python 3.6, the following error happens when I install espnet using make TH_VERSION=1.2.0 CUDA_VERSION=10.0 command.
Collecting colorama
  Using cached colorama-0.4.5-py2.py3-none-any.whl (16 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
  Using cached colorama-0.4.3-py2.py3-none-any.whl (15 kB)
  Using cached colorama-0.4.1-py2.py3-none-any.whl (15 kB)
  Using cached colorama-0.4.0-py2.py3-none-any.whl (21 kB)
  Using cached colorama-0.3.9-py2.py3-none-any.whl (20 kB)
  Using cached colorama-0.3.8-py2.py3-none-any.whl (20 kB)
INFO: pip is looking at multiple versions of colorama to determine which version is compatible with other requirements. This could take a while.
  Using cached colorama-0.3.7-py2.py3-none-any.whl (19 kB)
  Using cached colorama-0.3.6-py2.py3-none-any.whl (19 kB)
  Using cached colorama-0.3.5-py2.py3-none-any.whl (20 kB)
  Using cached colorama-0.3.4.zip (36 kB)
  Using cached colorama-0.3.3.tar.gz (22 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Using cached colorama-0.3.2.zip (32 kB)
  Using cached colorama-0.3.1.zip (31 kB)
  Using cached colorama-0.3.0.zip (24 kB)
  Using cached colorama-0.2.7.zip (24 kB)
  Using cached colorama-0.2.6.zip (25 kB)
  Using cached colorama-0.2.5.zip (23 kB)
  Using cached colorama-0.2.4.zip (21 kB)
  Using cached colorama-0.2.3.zip (23 kB)
  Using cached colorama-0.2.2.zip (23 kB)
  Using cached colorama-0.2.1.zip (23 kB)
  Using cached colorama-0.2.0.zip (16 kB)
  Using cached colorama-0.1.18.zip (14 kB)
  Using cached colorama-0.1.17.zip (15 kB)
  Using cached colorama-0.1.16.zip (14 kB)
  Using cached colorama-0.1.15.zip (4.6 kB)
ERROR: File "setup.py" not found for legacy project colorama from https://files.pythonhosted.org/packages/ca/c2/6910ba3f0de55091bf88e96b94475bf72056d08aa0ce2e45f6a7c5d4e725/colorama-0.1.15.zip#sha256=fb55091e0dd982edcfa99f039f8ae85f7acd538626c15de71fed39a6b7faa3fd (from sacrebleu>=1.5.1->espnet==202209).

**Comment by chlorane** [comment]
I tried Cuda 10.0 and Python 3.7 following the set of longformer package. Now, esp-net can be installed. However, when I run how2_2000h/asr1/run.sh, the following error happens

[compute04] 2023-02-10 11:59:29,289 (abs_task:1527) INFO: [train] Batch sampler: LengthBatchSampler(N-batch=1, batch_bins=60000000, sort_in_batch=descending, sort_batch=descending)
[compute04] 2023-02-10 11:59:29,289 (abs_task:1529) INFO: [train] mini-batch sizes summary: N-batch=1, mean=14.0, min=14, max=14
Traceback (most recent call last):
  File "/home/nas02home/conda/envs/espnet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/nas02home/conda/envs/espnet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nas02/homes/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/nas02/homes/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/nas02/homes/espnet/espnet2/tasks/abs_task.py", line 1019, in main
    cls.main_worker(args)
  File "/nas02/homes/espnet/espnet2/tasks/abs_task.py", line 1323, in main_worker
    distributed_option=distributed_option,
  File "/nas02/homes/espnet/espnet2/train/trainer.py", line 291, in run
    distributed_option=distributed_option,
  File "/nas02/homes/espnet/espnet2/train/trainer.py", line 556, in train_one_epoch
    retval = model(**batch)
  File "/home/nas02home/conda/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nas02/homes/espnet/espnet2/asr/espnet_model.py", line 202, in forward
    encoder_out, encoder_out_lens = self.encode(speech, speech_lengths)
  File "/nas02/homes/espnet/espnet2/asr/espnet_model.py", line 352, in encode
    encoder_out, encoder_out_lens, _ = self.encoder(feats, feats_lengths)
  File "/home/nas02home/conda/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nas02/homes/espnet/espnet2/asr/encoder/longformer_encoder.py", line 336, in forward
    xs_pad, masks = self.encoders(xs_pad, masks)
  File "/home/nas02home/conda/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nas02/homes/espnet/espnet/nets/pytorch_backend/transformer/repeat.py", line 18, in forward
    args = m(*args)
  File "/home/nas02home/conda/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nas02/homes/espnet/espnet/nets/pytorch_backend/conformer/encoder_layer.py", line 141, in forward
    x_att = self.self_attn(x_q, x, x, mask)
  File "/home/nas02home/conda/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nas02/homes/espnet/espnet/nets/pytorch_backend/transformer/longformer_attention.py", line 53, in forward
    output_attentions=True,
  File "/home/nas02home/conda/envs/espnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nas02home/conda/envs/espnet/lib/python3.7/site-packages/longformer/longformer.py", line 168, in forward
    d_mask = diagonaled_mm_tvm(ones, float_mask, self.attention_window, self.attention_dilation, False, 0, False)
  File "/home/nas02home/conda/envs/espnet/lib/python3.7/site-packages/longformer/diagonaled_mm_tvm.py", line 261, in forward
    output = DiagonaledMM._diagonaled_mm(t1, t2, w, d, is_t1_diagonaled=is_t1_diagonaled, padding=padding, autoregressive=autoregressive)
  File "/home/nas02home/conda/envs/espnet/lib/python3.7/site-packages/longformer/diagonaled_mm_tvm.py", line 202, in _diagonaled_mm
    _diagonaled_mm_function(t1, t2, r, d, w, w_upper, padding, transpose_t1, m if is_t1_diagonaled else c)
  File "/home/nas02home/conda/envs/espnet/lib/python3.7/site-packages/tvm/contrib/dlpack.py", line 40, in _wrapper
    return tvm_func(*args)
  File "/home/nas02home/conda/envs/espnet/lib/python3.7/site-packages/tvm/_ffi/function.py", line 143, in __call__
    return self._entry(*args)
  File "/home/nas02home/conda/envs/espnet/lib/python3.7/site-packages/tvm/_ffi/_ctypes/function.py", line 210, in __call__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  [bt] (1) /nas02/homes/conda/envs/espnet/lib/python3.7/site-packages/tvm/libtvm_runtime.so(TVMFuncCall+0x61) [0x7f8278b12681]
  [bt] (0) /nas02/homes/conda/envs/espnet/lib/python3.7/site-packages/tvm/libtvm_runtime.so(+0x5cfdc) [0x7f8278b34fdc]
  File "/code/tvm/src/runtime/module_util.cc", line 73
TVMError: Check failed: ret == 0 (-1 vs. 0) : Assert fail: ((((1 == int32(arg2.strides[3])) && (t3d3 == int32(arg2.strides[2]))) && ((t3d3*h) == int32(arg2.strides[1]))) && (((t3d3*h)*n) == int32(arg2.strides[0]))), arg2.strides: expected to be compact array
Loading tvm binary from: /home/nas02home/conda/envs/espnet/lib/python3.7/site-packages/longformer/../longformer/lib/lib_diagonaled_mm_float32_cuda.so
# Accounting: time=106 threads=1

**Comment by roshansh-cmu** [comment]
You have a TVM error it appears. It appears that this issue is resolved on your end, so we can close this issue.
