### ISSUE TITLE
Error of Librispeech feature extraction

### ISSUE THREAD

**Issue by Happydici** [espnet/espnet#4959]
Hi,

I tried to learn to use Librispeech corpus to train a small asr model. At the third stage, I faced a problem as follows,

2023-02-23T17:09:09 (asr.sh:526:main) Stage 3: Format wav.scp: data/ -> dump/raw
utils/copy_data_dir.sh: copied data from data/train_clean_100_sp to dump/raw/org/train_clean_100_sp
utils/validate_data_dir.sh: Successfully validated data-directory dump/raw/org/train_clean_100_sp
2023-02-23T17:09:15 (format_wav_scp.sh:43:main) scripts/audio/format_wav_scp.sh --nj 32 --cmd run.pl --audio-format flac --fs 16k data/train_clean_100_sp/wav.scp dump/raw/org/train_clean_100_sp
2023-02-23T17:09:15 (format_wav_scp.sh:112:main) [info]: without segments
run.pl: 22 / 32 failed, log is in dump/raw/org/train_clean_100_sp/logs/format_wav_scp.*.log

Why some of the files are successfully processed while some are failed?

Thank you.

**Comment by sw005320** [comment]
Can you check the log file to find errors in more detail?
Also, it may be good to reduce the number of jobs.
This might come from too much file access.

**Comment by Happydici** [comment]
Thank you for your help.
I check one of the log files. The content is as follows,

2023-02-23 20:40:31,636 (format_wav_scp:68) INFO: /home/qy/dialog/espnet/tools/anaconda/envs/espnet/bin/python3 pyscripts/audio/format_wav_scp.py --fs 16k --audio-format flac dump/raw/org/train_clean_100_sp/logs/wav.12.scp dump/raw/org/train_clean_100_sp/data/format.12
^M0it [00:00, ?it/s]sox FAIL formats: no handler for detected file type `flac'
^M0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/qy/dialog/espnet/egs2/librispeech/asr1/pyscripts/audio/format_wav_scp.py", line 289, in <module>
    main()
  File "/home/qy/dialog/espnet/egs2/librispeech/asr1/pyscripts/audio/format_wav_scp.py", line 187, in main
    wave, rate = soundfile.read(g, dtype=np.int16)
  File "/home/qy/dialog/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/soundfile.py", line 285, in read
    with SoundFile(file, 'r', samplerate, channels,
  File "/home/qy/dialog/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/home/qy/dialog/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening <_io.BytesIO object at 0x7f25620cc2c0>: Format not recognised.
# Accounting: time=2 threads=1
# Ended (code 1) at Thu Feb 23 20:40:32 CST 2023, elapsed time 2 seconds

The current nj is set 32. Is it too big?

Thanks.

**Comment by sw005320** [comment]
> The current nj is set 32. Is it too big?

I think so (in your setup).
It is difficult to guess from this log only, but my expectation is that it comes from disk access.
Reducing the number of jobs will mitigate the issues. 
You can set it 4 or 8.

**Comment by Happydici** [comment]
Great!  I reduced the nj to 4. The error disappeared.  Thank you.

**Comment by sw005320** [comment]
cool!
