### ISSUE TITLE
Decoding Speech with ESPNet2: it is not possible integrating CTC

### ISSUE THREAD

**Issue by david-gimeno** [espnet/espnet#4996]
Hello,

First of all, thank you so much for your amazing toolkit!

I am developing an ASR model based on the pytorch backend of "espnet2". Specifically, I designed a hybrid CTC/Attention model using the script "/espnet2/asr/espnet_model.py". Everything is going well during training. However, when I try to decode speech to evaluate my model on the test set of the database, this message errors appears:

> Traceback (most recent call last):
>   File "vsr_main.py", line 257, in <module>
>     inference(test_loader, e2e, beam_search, char_list, args, "test")
>   File "vsr_main.py", line 71, in inference
>     transcription = predict(xs_pad, ilens, e2e, beam_search, char_list, args)
>   File "vsr_main.py", line 84, in predict
>     nbest_hyps = beam_search(
>   File "/home/dgimeno/.conda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/dgimeno/espnet/espnet/nets/beam_search.py", line 377, in forward
>     running_hyps = self.init_hyp(x)
>   File "/home/dgimeno/espnet/espnet/nets/batch_beam_search.py", line 125, in init_hyp
>     init_states[k] = d.batch_init_state(x)
>   File "/home/dgimeno/espnet/espnet/nets/scorers/ctc.py", line 98, in batch_init_state
>     self.impl = CTCPrefixScoreTH(logp, xlen, 0, self.eos)
>   File "/home/dgimeno/espnet/espnet/nets/ctc_prefix_score.py", line 53, in __init__
>     xb = xn[:, :, self.blank].unsqueeze(2).expand(-1, -1, self.odim)
> RuntimeError: expand(torch.cuda.FloatTensor{[1, 1, 1, 41]}, size=[-1, -1, 62]): the number of sizes provided (3) must be greater or equal to the number of dimensions in the tensor (4)

It seems that the problem is the CTC-based branch. I was looking for a CTCPrefixScorer implemented in the new version of the toolkit "espnet2" but I did not find it. So, I decided to use the CTCPrefixScorer imported from the previous version "from espnet.nets.scorers.ctc import CTCPrefixScorer". Well, actually, I am using the BatchBeamSearch from the previous version "from espnet.nets.batch_beam_search import BatchBeamSearch" for the same reason.

If I run my script with no CTC-based branch, there is no error.

How can I solved this issue? Is there other way to integrate the CTC-based branch? Thanks in advance,

David.

**Comment by sw005320** [comment]
Thanks for the report.
espnet2 uses CTCPrefixScorer implementation in espnet1 as it is (with some slight modifications in the interface when needed).
So, what you're checking is correct, and please continue to check it.

**Comment by sw005320** [comment]
> where can I find a good example of .yaml file to construct, for example, an ESPnetASRModel?

ESPnetASRModel (or other models) is built under the task
https://github.com/espnet/espnet/blob/master/espnet2/tasks/asr.py#L476
