### ISSUE TITLE
whisper_multilingual tokenizer error

### ISSUE THREAD

**Issue by sameerkhurana10** [espnet/espnet#5016]
Hi,

I was to fine-tune whisper small.

When I use `--tokenizer whisper_multilingual` as input to run.sh, I get the following error:

```
2023-03-15T22:19:28 (asr.sh:267:main) ./asr.sh --lang all --ngpu 1 --nj 16 --gpu_inference true --inference_nj 2 --nbpe 6500 --max_wav_duration 30 --speed_perturb_factors  --audio_format flac.ark --feats_type raw --use_lm false --asr_config conf/tuning/train_asr_whisper_full.yaml --inference_config conf/decode_asr_whisper_noctc_greedy.yaml --train_set train_all --valid_set dev_all --test_sets test_all --lm_train_text data/train_all/text --bpe_train_text data/train_all/text --stage 5 --stop-stage 8 --token_type whisper_multilingual --nj 32 --speed_perturb_factors  --use_lm false --asr_config conf/tuning/train_asr_whisper_full.yaml --num_nodes 1 --ngpu 8 --inference_nj 100 --lm_train_text data/train_all/text --bpe_train_text data/train_all/text --asr_stats_dir exp/asr_stats_bpe6k_whisper_small_all --asr_tag whisper_small_all --bpe_nlsyms data/train_all/bpe_nlsyms.txt
2023-03-15T22:19:29 (asr.sh:788:main) Stage 5: Generate whisper token_list from whisper_multilingual tokenizer
data/all_token_list/whisper_multilingual/tokens.txt
/gpfswork/rech/iqh/upp27cx/conda-envs/espnet_mar142023_whisper/bin/python3 /gpfsdswork/projects/rech/iqh/upp27cx/sameerk/espnet_mar142023_whisper/espnet/espnet2/bin/whisper_export_vocabulary.py --whisper_model whisper_multilingual --output data/all_token_list/whisper_multilingual/tokens.txt
Traceback (most recent call last):
  File "/gpfswork/rech/iqh/upp27cx/conda-envs/espnet_mar142023_whisper/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/gpfswork/rech/iqh/upp27cx/conda-envs/espnet_mar142023_whisper/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfsdswork/projects/rech/iqh/upp27cx/sameerk/espnet_mar142023_whisper/espnet/espnet2/bin/whisper_export_vocabulary.py", line 96, in <module>
    main()
  File "/gpfsdswork/projects/rech/iqh/upp27cx/sameerk/espnet_mar142023_whisper/espnet/espnet2/bin/whisper_export_vocabulary.py", line 92, in main
    export_vocabulary(**kwargs)
  File "/gpfsdswork/projects/rech/iqh/upp27cx/sameerk/espnet_mar142023_whisper/espnet/espnet2/bin/whisper_export_vocabulary.py", line 45, in export_vocabulary
    vocab_size = tokenizer.tokenizer.vocab_size + len(
AttributeError: 'Tokenizer' object has no attribute 'tokenizer'
```

Any ideas on how to fix this?

Using: 
espnet version 202301
pytorch 1.13.1
Cuda 11.7
whisper version 20230308

Thanks,
Sameer

**Comment by sw005320** [comment]
Can you use the old whisper version?
check https://github.com/espnet/espnet/pull/5004
they changed the tokenzer and for now, we just use the old version.
I think it is fine for most cases.

**Comment by sw005320** [comment]
oh, sorry you're using 20230308.

**Comment by sw005320** [comment]
@slSeanWU, do you know what's happening?
The error looks similar to what you have fixed, but maybe, I'm wrong.

**Comment by slSeanWU** [comment]
Hi @sameerkhurana10, could you try `pip uninstall openai-whisper` and then re-install with `pip install openai-whisper==20230308`?

**Comment by sameerkhurana10** [comment]
that worked, thanks.
