### ISSUE TITLE
whisper fine-tuning error in the decoder

### ISSUE THREAD

**Issue by sameerkhurana10** [espnet/espnet#5018]
Hi,

espnet: 202301
cuda: 11.7
pytorch: 1.13.1
whisper: 20230308
GPUs: 8 A100

I am trying to perform multilingual fine-tuning of the pre-trained whisper model on the fleurs dataset. I am using whisper_multilingual tokenizer. I get the following error:

```
Traceback (most recent call last):
  File "/gpfswork/rech/iqh/upp27cx/conda-envs/espnet_mar142023_whisper/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/gpfswork/rech/iqh/upp27cx/conda-envs/espnet_mar142023_whisper/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/gpfsdswork/projects/rech/iqh/upp27cx/sameerk/espnet_mar142023_whisper/espnet/espnet2/tasks/abs_task.py", line 1359, in main_worker
    cls.trainer.run(
  File "/gpfsdswork/projects/rech/iqh/upp27cx/sameerk/espnet_mar142023_whisper/espnet/espnet2/train/trainer.py", line 290, in run
    all_steps_are_invalid = cls.train_one_epoch(
  File "/gpfsdswork/projects/rech/iqh/upp27cx/sameerk/espnet_mar142023_whisper/espnet/espnet2/train/trainer.py", line 567, in train_one_epoch
    retval = model(**batch)
  File "/gpfswork/rech/iqh/upp27cx/conda-envs/espnet_mar142023_whisper/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/gpfswork/rech/iqh/upp27cx/conda-envs/espnet_mar142023_whisper/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/gpfswork/rech/iqh/upp27cx/conda-envs/espnet_mar142023_whisper/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/gpfswork/rech/iqh/upp27cx/conda-envs/espnet_mar142023_whisper/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/gpfsdswork/projects/rech/iqh/upp27cx/sameerk/espnet_mar142023_whisper/espnet/espnet2/asr/espnet_model.py", line 315, in forward
    loss_att, acc_att, cer_att, wer_att = self._calc_att_loss(
  File "/gpfsdswork/projects/rech/iqh/upp27cx/sameerk/espnet_mar142023_whisper/espnet/espnet2/asr/espnet_model.py", line 539, in _calc_att_loss
    decoder_out, _ = self.decoder(
  File "/gpfswork/rech/iqh/upp27cx/conda-envs/espnet_mar142023_whisper/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/gpfsdswork/projects/rech/iqh/upp27cx/sameerk/espnet_mar142023_whisper/espnet/espnet2/asr/decoder/whisper_decoder.py", line 92, in forward
    self.decoders.token_embedding(tgt)
RuntimeError: The size of tensor a (468) must match the size of tensor b (448) at non-singleton dimension 1
```
The error seems to be coming from this line: https://github.com/espnet/espnet/blob/master/espnet2/asr/decoder/whisper_decoder.py#L92

Is it because I have some small utterances in my training set? The minimum wav duration that I am accepting is 0.1 seconds. I tried increasing this to up to 3 seconds, but its not helping.

An example of the training transcript is as follows:
```
10000156097013738607_sw <|sw|> <|transcribe|> <|notimestamps|> AKAWATUMIA WANAFUNZI WA CHUO KIKUU CHAA NDANI BARUA PEPE NA AKAPATA MATOLEO MENGI SANA YA MALAZI YA BURE
```

Also, the smallest utterance in my training set has 100480 samples.

I am fine-tuning the whisper small model on 8 GPUs.

I tried setting `do_pad_trim=true,` but the error persists.

I did not get the above error with the same dataset when I ran fine-tuning with `--tokenizer_type bpe` instead of `whisper_multilingual`.

**Comment by slSeanWU** [comment]
Hi Sameer,

The tensor mismatch error is actually because some of your inputs are too long. Whisper decoder uses absolute positional encoding and only supports up to 448 (not very sure, I remember it was 440) positions. You can skip training examples whose transcripts are obviously too long and try again.

Regarding transcript, I think this is related to #5017. ESPnet Whisper tokenizer now prepends `<|en|> <|transcribe|> <|notimestamps|>` to the transcript by default, I'll check how to turn it off to suit your multilingual use case and get back to you.

**Comment by slSeanWU** [comment]
To get rid of the default prefix, you can change the function at https://github.com/espnet/espnet/blob/master/espnet2/text/whisper_token_id_converter.py#L53-L56

from
```
def tokens2ids(self, tokens: Iterable[str]) -> List[int]:
        return list(
            self.tokenizer.sot_sequence_including_notimestamps[1:]
        ) + self.tokenizer.tokenizer.convert_tokens_to_ids(tokens)
```

to
```
def tokens2ids(self, tokens: Iterable[str]) -> List[int]:
        return self.tokenizer.tokenizer.convert_tokens_to_ids(tokens)
```

Hope this help!

**Comment by sameerkhurana10** [comment]
yes, thanks!
