### ISSUE TITLE
How to change loss_type for si_snr to ci_sdr?

### ISSUE THREAD

**Issue by Taruguchi** [espnet/espnet#5056]
In #4473, I asked about if I can get separated voice and noise wav files, and I could that by using the code of #4476.
I usually use the si_snr loss in voice enhancement learning, but now, I want to try noise cancelling learning by using another loss, for examle, ci_sdr.
I tried change the setting as below, but it was not good.

```
# A list for criterions
# The overlall loss in the multi-task learning will be:
# loss = weight_1 * loss_1 + ... + weight_N * loss_N
# The default `weight` for each sub-loss is 1.0
criterions:
  # The first criterion
  - name: ci_sdr
    conf:
      clamp_db: 70
    wrapper: pit
    wrapper_conf:
      weight: 1.0
      independent_perm: True
  # The second criterion (for noise estimation)
  - name: si_snr
    conf:
      clamp_db: 70
      is_noise_loss: true
      name: si_snr_noise
    wrapper: pit
    wrapper_conf:
      weight: 1.0
      independent_perm: True

```

The code showed
`TypeError: __init__() got an unexpected keyword argument 'clamp_db'`

Please tell me how to use another loss_type?

**Comment by Emrys365** [comment]
There are two solutions.

One is to use the loss `sdr` instead of `ci_sdr`, which is a different implementation of the same loss. It accepts the `clamp_db` argument.

The other is to remove the `clamp_db` argument for the `ci_sdr` loss.

> Refer to https://github.com/espnet/espnet/blob/master/espnet2/enh/loss/criterions/time_domain.py for the supported arguments for each loss.

**Comment by Taruguchi** [comment]
@Emrys365 
Thank you for your answer.
I tried to use `sdr` loss and successed in few data learning.
But I tried to  learning by using many data (about 40GB), the code showed such error.

~~~
/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/functional.py:647: UserWarning: istft will require a complex-valued input tensor in a future PyTorch release. Matching the output from stft with return_complex=True.  (Triggered internally at  /opt/conda/conda-bld/pytorch_1639180588308/work/aten/src/ATen/native/SpectralOps.cpp:811.)
  return _VF.istft(input, n_fft, hop_length, win_length, window, center,  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/espnet/espnet2/bin/enh_train.py", line 23, in <module>
    main()
  File "/root/espnet/espnet2/bin/enh_train.py", line 19, in main
    EnhancementTask.main(cmd=cmd)
  File "/root/espnet/espnet2/tasks/abs_task.py", line 1013, in main
    cls.main_worker(args)
  File "/root/espnet/espnet2/tasks/abs_task.py", line 1309, in main_worker
    cls.trainer.run(
  File "/root/espnet/espnet2/train/trainer.py", line 281, in run
    all_steps_are_invalid = cls.train_one_epoch(
  File "/root/espnet/espnet2/train/trainer.py", line 550, in train_one_epoch
    retval = model(**batch)
  File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/espnet/espnet2/enh/espnet_model.py", line 161, in forward
    loss, stats, weight = self.forward_loss(
  File "/root/espnet/espnet2/enh/espnet_model.py", line 276, in forward_loss
    l, s, o = loss_wrapper(sref, spre, {**others, **o})
  File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/espnet/espnet2/enh/loss/wrappers/pit_solver.py", line 80, in forward
    losses = torch.stack([pair_loss(p) for p in all_permutations], dim=1)
  File "/root/espnet/espnet2/enh/loss/wrappers/pit_solver.py", line 80, in <listcomp>
    losses = torch.stack([pair_loss(p) for p in all_permutations], dim=1)
  File "/root/espnet/espnet2/enh/loss/wrappers/pit_solver.py", line 70, in pair_loss
    [
  File "/root/espnet/espnet2/enh/loss/wrappers/pit_solver.py", line 71, in <listcomp>
    pre_hook(self.criterion, ref[s], inf[t])
  File "/root/espnet/espnet2/enh/loss/wrappers/pit_solver.py", line 63, in pre_hook
    ret = func(*args, **kwargs)
  File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/espnet/espnet2/enh/loss/criterions/time_domain.py", line 201, in forward
    sdr_loss = fast_bss_eval.sdr_loss(
  File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/fast_bss_eval/__init__.py", line 509, in sdr_loss
    return _dispatch_backend(
  File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/fast_bss_eval/__init__.py", line 302, in _dispatch_backend
    return f_torch(*args, **kwargs)
  File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/fast_bss_eval/torch/metrics.py", line 266, in sdr_loss
    sol = solve(R_mat, xcorr)
  File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/fast_bss_eval/torch/compatibility.py", line 144, in solve
    return torch.linalg.solve(*args, **kwargs)
RuntimeError: linalg_solve: (Batch element 7): The diagonal element 1 is zero, the solve could not be completed because the input matrix is singular.
~~~

If you know how to solve this problem, I want you to tell me.

**Comment by Taruguchi** [comment]
@Emrys365 
Sorry, I can't understand the mean of `clamp_db`, what is this?
I found below in the documentation, but I can't  understand.
~~~
clamp_db: float
clamp the output value in [-clamp_db, clamp_db]
~~~
In default, `clamp_db` is 70.
Should I change this value more higher to mitigate this issue?

**Comment by Taruguchi** [comment]
I also removed the clamp_db argument for the ci_sdr loss, but it showed same error.
~~~
# A list for criterions
# The overlall loss in the multi-task learning will be:
# loss = weight_1 * loss_1 + ... + weight_N * loss_N
# The default `weight` for each sub-loss is 1.0
criterions: 
  # The first criterion
  - name: ci_sdr
    wrapper: pit
    wrapper_conf:
      weight: 1.0
      independent_perm: True
  # The second criterion (for noise estimation)
  - name: si_snr
    conf:
      is_noise_loss: true
      name: si_snr_noise
    wrapper: pit
    wrapper_conf:
      weight: 1.0
      independent_perm: True
~~~

**Comment by Emrys365** [comment]
After a second thought, I don't think `clamp_db` will fix the singular matrix issue as it is only applied afterwards.

Anyway, I personally found the CI-SDR loss to be friendly only to a small range of models that are intrinsically constrained (such as beamformers).

https://github.com/fakufaku/fast_bss_eval/blob/main/fast_bss_eval/torch/metrics.py#L266

**Comment by Taruguchi** [comment]
@Emrys365 
Thank you. I tried to use `sdr` instead of `ci_sdr`, and showed another error..
This error mean the lack of my machine's GPU power?(ex. out of memory)

When I tried to learning by using `si_snr` loss and same dataset, it successed.
All I hace done is change `si_snr` to `sdr` in `.yaml` file, but sholud I change another parameter or code?


~~~
[a085d954b429] 2023-03-29 03:43:27,873 (trainer:536) WARNING: summary_writer.add_graph() is failed for the model. The graph can't be added for tensorboard.
/root/espnet/espnet2/layers/stft.py:164: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  olens = (ilens - self.n_fft) // self.hop_length + 1
Traceback (most recent call last):
  File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/espnet/espnet2/bin/enh_train.py", line 23, in <module>
    main()
  File "/root/espnet/espnet2/bin/enh_train.py", line 19, in main
    EnhancementTask.main(cmd=cmd)
  File "/root/espnet/espnet2/tasks/abs_task.py", line 1013, in main
    cls.main_worker(args)
  File "/root/espnet/espnet2/tasks/abs_task.py", line 1309, in main_worker
    cls.trainer.run(
  File "/root/espnet/espnet2/train/trainer.py", line 281, in run
    all_steps_are_invalid = cls.train_one_epoch(
  File "/root/espnet/espnet2/train/trainer.py", line 550, in train_one_epoch
    retval = model(**batch)
  File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/espnet/espnet2/enh/espnet_model.py", line 156, in forward
    speech_pre, feature_mix, feature_pre, others = self.forward_enhance(
  File "/root/espnet/espnet2/enh/espnet_model.py", line 181, in forward_enhance
    feature_pre, flens, others = self.separator(feature_mix, flens, additional)
  File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/espnet/espnet2/enh/separator/transformer_separator.py", line 141, in forward
    x, ilens = self.transformer(feature, pad_mask)
  File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/espnet/espnet/nets/pytorch_backend/transformer/encoder.py", line 323, in forward
    xs = self.embed(xs)
  File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
# Accounting: time=10 threads=1
# Ended (code 1) at Wed Mar 29 03:43:29 UTC 2023, elapsed time 10 seconds
~~~

**Comment by Emrys365** [comment]
Are you using chunk-based iterator? If not, the error can be caused by a long batch in the middle of the training process. Also, could you try with a smaller batch size?

**Comment by Emrys365** [comment]
> After a second thought, I don't think `clamp_db` will fix the singular matrix issue as it is only applied afterwards.
>
> Anyway, I personally found the CI-SDR loss to be friendly only to a small range of models that are intrinsically constrained (such as beamformers).
>
> https://github.com/fakufaku/fast_bss_eval/blob/main/fast_bss_eval/torch/metrics.py#L266

OK, it's then still related to the issue I mentioned above. Could you check whether your model output is all-zero in this case? If so, I think we can work around it by adding a tiny constant to the model output.

**Comment by Taruguchi** [comment]
@Emrys365 
Thank you. I tried with a smaller batch size (default 8→4 or 2), but it wasnt success.
So I'll check the model output as you said.

I understood that I should confim the contents of `xcorr` in `metrics.py`, line 266. right?
And I dont know where is 'metrics.py' that I shoild check because there are some of same name programs in espnet project.
Im sorry but plase tell me.

**Comment by Emrys365** [comment]
I think you could find the location of the file by running the following command:

```bash
python -c 'import fast_bss_eval; print(fast_bss_eval.__file__)'
```

**Comment by Taruguchi** [comment]
@Emrys365 
Such error occurred.
I use v.202207 version of espnet, that is reason?

~~~
# python -c 'import fast_bss_eval; print(fast_bss_eval.__file__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'fast_bss_eval'
~~~

**Comment by Emrys365** [comment]
> ~~~
> 
> # python -c 'import fast_bss_eval; print(fast_bss_eval.__file__)'
> 
> Traceback (most recent call last):
> 
>   File "<string>", line 1, in <module>
> 
> ModuleNotFoundError: No module named 'fast_bss_eval'
> 
> ~~~

Can you run `. ./path.sh` first to load your ESPnet python environment? (Run the command under any recipe directory where path.sh is present)

**Comment by Emrys365** [comment]
> @Emrys365 I could run `. ./path.sh`, and ` python -c 'import fast_bss_eval; print(fast_bss_eval.__file__)'`.
> 
> ```
> /root/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/fast_bss_eval/__init__.py
> ```
> 
> The code showed the place of `__init__.py`, not `metrics.py`, OK?
> 
> I found `sdr_loss` method in `__init__.py,` but such column doesnt exist.
> 
> ```
> sol = solve(R_mat, xcorr)
> ```

Yes. I suppose you could find the path to `metrics.py` after locating the path of the `fast_bss_eval` used in ESPnet.

So according to the link above

```
https://github.com/fakufaku/fast_bss_eval/blob/main/fast_bss_eval/torch/metrics.py#L266
```

the `metrics.py` file should be located at
```
/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/fast_bss_eval/torch/metrics.py
```

**Comment by Taruguchi** [comment]
@Emrys365 
Thank you. I found `metrics.py` and confirmed the contents of `R_mat` and `xcorr`.
They were printed several times while the program was runnning, and the error code showed in the middle.
It seems that there isn't all zero case.
~~~
R_mat
tensor([[[ 1.0000,  0.9155,  0.7635,  ..., -0.0393, -0.0390, -0.0343],
         [ 0.9155,  1.0000,  0.9155,  ..., -0.0349, -0.0393, -0.0390],
         [ 0.7635,  0.9155,  1.0000,  ..., -0.0241, -0.0349, -0.0393],
         ...,
         [-0.0393, -0.0349, -0.0241,  ...,  1.0000,  0.9155,  0.7635],
         [-0.0390, -0.0393, -0.0349,  ...,  0.9155,  1.0000,  0.9155],
         [-0.0343, -0.0390, -0.0393,  ...,  0.7635,  0.9155,  1.0000]],

        [[ 1.0000,  0.9227,  0.7815,  ..., -0.0218, -0.0253, -0.0237],
         [ 0.9227,  1.0000,  0.9227,  ..., -0.0149, -0.0218, -0.0253],
         [ 0.7815,  0.9227,  1.0000,  ..., -0.0041, -0.0149, -0.0218],
         ...,
         [-0.0218, -0.0149, -0.0041,  ...,  1.0000,  0.9227,  0.7815],
         [-0.0253, -0.0218, -0.0149,  ...,  0.9227,  1.0000,  0.9227],
         [-0.0237, -0.0253, -0.0218,  ...,  0.7815,  0.9227,  1.0000]],

        [[ 1.0000,  0.9165,  0.7639,  ..., -0.0363, -0.0322, -0.0238],
         [ 0.9165,  1.0000,  0.9165,  ..., -0.0357, -0.0363, -0.0322],
         [ 0.7639,  0.9165,  1.0000,  ..., -0.0283, -0.0357, -0.0363],
         ...,
         [-0.0363, -0.0357, -0.0283,  ...,  1.0000,  0.9165,  0.7639],
         [-0.0322, -0.0363, -0.0357,  ...,  0.9165,  1.0000,  0.9165],
         [-0.0238, -0.0322, -0.0363,  ...,  0.7639,  0.9165,  1.0000]],

        ...,

        [[ 1.0000,  0.9514,  0.8752,  ..., -0.0252, -0.0251, -0.0184],
         [ 0.9514,  1.0000,  0.9514,  ..., -0.0224, -0.0252, -0.0251],
         [ 0.8752,  0.9514,  1.0000,  ..., -0.0187, -0.0224, -0.0252],
         ...,
         [-0.0252, -0.0224, -0.0187,  ...,  1.0000,  0.9514,  0.8752],
         [-0.0251, -0.0252, -0.0224,  ...,  0.9514,  1.0000,  0.9514],
         [-0.0184, -0.0251, -0.0252,  ...,  0.8752,  0.9514,  1.0000]],

        [[ 1.0000,  0.9534,  0.8766,  ...,  0.0530,  0.0571,  0.0641],
         [ 0.9534,  1.0000,  0.9534,  ...,  0.0491,  0.0530,  0.0571],
         [ 0.8766,  0.9534,  1.0000,  ...,  0.0445,  0.0491,  0.0530],
         ...,
         [ 0.0530,  0.0491,  0.0445,  ...,  1.0000,  0.9534,  0.8766],
         [ 0.0571,  0.0530,  0.0491,  ...,  0.9534,  1.0000,  0.9534],
         [ 0.0641,  0.0571,  0.0530,  ...,  0.8766,  0.9534,  1.0000]],

        [[ 1.0000,  0.9510,  0.8749,  ..., -0.0254, -0.0254, -0.0187],
         [ 0.9510,  1.0000,  0.9510,  ..., -0.0226, -0.0254, -0.0254],
         [ 0.8749,  0.9510,  1.0000,  ..., -0.0190, -0.0226, -0.0254],
         ...,
         [-0.0254, -0.0226, -0.0190,  ...,  1.0000,  0.9510,  0.8749],
         [-0.0254, -0.0254, -0.0226,  ...,  0.9510,  1.0000,  0.9510],
         [-0.0187, -0.0254, -0.0254,  ...,  0.8749,  0.9510,  1.0000]]],
       device='cuda:0')
xcorr
tensor([[ 0.0718,  0.0705,  0.0666,  ..., -0.0121, -0.0125, -0.0129],
        [ 0.7475,  0.7222,  0.6703,  ..., -0.0107, -0.0168, -0.0215],
        [ 0.2613,  0.2544,  0.2382,  ..., -0.0212, -0.0198, -0.0176],
        ...,
        [ 0.8496,  0.8364,  0.8082,  ..., -0.0206, -0.0197, -0.0183],
        [ 0.5977,  0.5884,  0.5676,  ...,  0.0440,  0.0439,  0.0430],
        [ 0.3648,  0.3574,  0.3434,  ..., -0.0147, -0.0111, -0.0075]],
       device='cuda:0', grad_fn=<SliceBackward0>)
~~~
~~~
…
 File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/fast_bss_eval/torch/metrics.py", line 267, in sdr_loss
    sol = solve(R_mat, xcorr)
  File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/fast_bss_eval/torch/compatibility.py", line 144, in solve
    return torch.linalg.solve(*args, **kwargs)
RuntimeError: linalg_solve: (Batch element 7): The diagonal element 1 is zero, the solve could not be completed because the input matrix is singular.
~~~

**Comment by Taruguchi** [comment]
@Emrys365 
I tring to confirm the whole of `R_mat` and `xcorr` when the error occurs,  but it's not good until now.
For now, I show you the part of these value when the error occurs, and it's seems that there are all-zero case, as you said.
If there are all-zero case, should I add code for adding a tiny constant to the model output, right?
Or, do you already have the sample code that can solve this problem?
~~~
R_mat
tensor([[[ 1.0000,  0.3435,  0.4236,  ..., -0.0082, -0.0098, -0.0149],
         [ 0.3435,  1.0000,  0.3435,  ..., -0.0073, -0.0082, -0.0098],
         [ 0.4236,  0.3435,  1.0000,  ...,  0.0047, -0.0073, -0.0082],
         ...,
         [-0.0082, -0.0073,  0.0047,  ...,  1.0000,  0.3435,  0.4236],
         [-0.0098, -0.0082, -0.0073,  ...,  0.3435,  1.0000,  0.3435],
         [-0.0149, -0.0098, -0.0082,  ...,  0.4236,  0.3435,  1.0000]],

        [[ 1.0000,  0.6796,  0.5993,  ...,  0.0231, -0.0013, -0.0351],
         [ 0.6796,  1.0000,  0.6796,  ...,  0.0507,  0.0231, -0.0013],
         [ 0.5993,  0.6796,  1.0000,  ...,  0.0828,  0.0507,  0.0231],
         ...,
         [ 0.0231,  0.0507,  0.0828,  ...,  1.0000,  0.6796,  0.5993],
         [-0.0013,  0.0231,  0.0507,  ...,  0.6796,  1.0000,  0.6796],
         [-0.0351, -0.0013,  0.0231,  ...,  0.5993,  0.6796,  1.0000]],

        [[ 1.0000,  0.9752,  0.9240,  ...,  0.0907,  0.1005,  0.1103],
         [ 0.9752,  1.0000,  0.9752,  ...,  0.0812,  0.0907,  0.1005],
         [ 0.9240,  0.9752,  1.0000,  ...,  0.0719,  0.0812,  0.0907],
         ...,
         [ 0.0907,  0.0812,  0.0719,  ...,  1.0000,  0.9752,  0.9240],
         [ 0.1005,  0.0907,  0.0812,  ...,  0.9752,  1.0000,  0.9752],
         [ 0.1103,  0.1005,  0.0907,  ...,  0.9240,  0.9752,  1.0000]],

        ...,

        [[ 1.0000,  0.9596,  0.8814,  ..., -0.2662, -0.2800, -0.2895],
         [ 0.9596,  1.0000,  0.9596,  ..., -0.2478, -0.2662, -0.2800],
         [ 0.8814,  0.9596,  1.0000,  ..., -0.2245, -0.2478, -0.2662],
         ...,
         [-0.2662, -0.2478, -0.2245,  ...,  1.0000,  0.9596,  0.8814],
         [-0.2800, -0.2662, -0.2478,  ...,  0.9596,  1.0000,  0.9596],
         [-0.2895, -0.2800, -0.2662,  ...,  0.8814,  0.9596,  1.0000]],

        [[ 1.0000,  0.8545,  0.6601,  ..., -0.1058, -0.0777, -0.0445],
         [ 0.8545,  1.0000,  0.8545,  ..., -0.1178, -0.1058, -0.0777],
         [ 0.6601,  0.8545,  1.0000,  ..., -0.1140, -0.1178, -0.1058],
         ...,
         [-0.1058, -0.1178, -0.1140,  ...,  1.0000,  0.8545,  0.6601],
         [-0.0777, -0.1058, -0.1178,  ...,  0.8545,  1.0000,  0.8545],
         [-0.0445, -0.0777, -0.1058,  ...,  0.6601,  0.8545,  1.0000]],

        [[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         ...,
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],
       device='cuda:0')
~~~
~~~
xcorr
tensor([[ 0.5108,  0.3334,  0.3411,  ..., -0.0176, -0.0183, -0.0178],
        [ 0.4269,  0.1809,  0.1483,  ..., -0.0025, -0.0134, -0.0355],
        [ 0.7017,  0.6969,  0.6872,  ...,  0.1307,  0.1401,  0.1493],
        ...,
        [ 0.6703,  0.6631,  0.6507,  ..., -0.3365, -0.3446, -0.3529],
        [ 0.4934,  0.4616,  0.4208,  ..., -0.1730, -0.1622, -0.1503],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],
       device='cuda:0', grad_fn=<SliceBackward0>)
~~~

**Comment by Emrys365** [comment]
@fakufaku Could you provide some suggestions on this?

**Comment by fakufaku** [comment]
@Taruguchi @Emrys365 
Usually the error you are seeing wrt `R_mat` happens when the correlation matrix of the target signals is rank deficient. This typically happens if one of the inputs is all zero.

The computations are batched, so if you want to print only the problematic element, check the batch element in the error message (element 7 here)
```
RuntimeError: linalg_solve: (Batch element 7): The diagonal element 1 is zero
```
Also, the message indicates that the diagonal element is zero.
The diagonal elements of `R_mat` should be non-negative, so a zero value strongly suggests the target signal is all zero.

You have two solutions.
1. Check your inputs and discard when one of them is all zero
2. Add a very small amount of noise so that the inputs are never zero (e.g. 40 dB noise)
3. Provide the option `load_diag=eps` to the `sdr` loss, with `eps` being a small value, e.g. `1e-5`. This will add a diagonal loading factor to `R_mat`. This should not affect much the value when the target is non-zero and will avoid failure when the target is zero.

**Comment by Taruguchi** [comment]
@fakufaku @Emrys365 
Thank you. I modified `metrics.py` to add a small value to `load_diag`, and learning finished successfully.

By the way, I added code in `def sdr_loss` as below, but it wasn't good.
~~~
def sdr_loss(
    est: torch.Tensor,
    ref: torch.Tensor,
    filter_length: Optional[int] = 512,
    use_cg_iter: Optional[int] = None,
    zero_mean: Optional[bool] = False,
    clamp_db: Optional[float] = None,
    load_diag: Optional[float] = 1e-5,
    pairwise: Optional[bool] = False,
) -> torch.Tensor:
~~~
…
~~~
    if filter_length == 1:
        coh = square_cosine_metrics_length_one_filter(
            ref,
            est,
            zero_mean=zero_mean,
            load_diag=1e-5,
            pairwise=pairwise,
            with_coh_sar=False,
        )
~~~
So, I added temporary code as below, and it was good.
~~~
        # compute auto-correlation and cross-correlation
        acf, xcorr = compute_stats(ref, est, length=filter_length, pairwise=pairwise)

        load_diag = 1e-5  ←added code
        if load_diag is not None:
            print("load_diag OK")
            # the diagonal factor of the Toeplitz matrix is the first
            # coefficient of the acf
            acf[..., 0] += load_diag
~~~
I think, this way is not correct method.
Would you tell me where should I change and add the code or `.yaml` file for use `load_diag` option?

**Comment by fakufaku** [comment]
You should be able to add it as an extra option to the criterion in the yaml file:
```yaml
criterions:
  # The first criterion
  - name: sdr
    conf:
      clamp_db: 70
      load_diag: 1e-5
    wrapper: pit
    wrapper_conf:
      weight: 1.0
      independent_perm: True
```

**Comment by Taruguchi** [comment]
@fakufaku @Emrys365 
Thank you. I'll try it.
