### ISSUE TITLE
Unable to run mfa.sh to train fastspeech2

### ISSUE THREAD

**Issue by Kodhandarama** [espnet/espnet#5058]
Unable to run mfa.sh to train fastspeech2

Environment :
OS : Operating System: Red Hat Enterprise Linux 9.1 (Plow)   
python version : 3. 8.16
libraries :
Python modules:
[x] torch=1.13.1
[x] torch cuda=11.7
[x] torch cudnn=8500
[x] torch nccl
[x] chainer=6.0.0
[ ] chainer cuda
[ ] chainer cudnn
[ ] cupy
[x] torchaudio=0.13.1
[x] torch_optimizer=0.3.0
[ ] warprnnt_pytorch
[ ] chainer_ctc
[x] pyopenjtalk=0.3.0
[ ] tdmelodic_pyopenjtalk
[ ] kenlm
[ ] mmseg
[x] espnet=202301
[x] numpy=1.23.5
[ ] fairseq
[x] phonemizer=3.2.1
[ ] gtn
[ ] s3prl
[ ] transformers
[ ] speechbrain
[ ] k2
[ ] longformer
[ ] nlg-eval
[ ] datasets
[ ] pykeops
[ ] whisper
[ ] RawNet3
[ ] reazonspeech
[ ] muskits
[ ] Kaldi

Executables:
[ ] sclite
[ ] sph2pipe
[ ] PESQ
[ ] BeamformIt
[ ] spm_train
[ ] spm_encode
[ ] spm_decode
[x] sox=14.4.2
[x] ffmpeg=4.2.2
[x] flac=1.3.4
[x] cmake=3.22.1

git hash :
commit 666dd77fa7cf8069ffbb84f275ec056d36e8151f (HEAD -> master, origin/master, origin/HEAD)
Merge: 4d4959c24 aec4a6f0e
Author: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>
Date:   Mon Mar 20 10:39:05 2023 +0000

    Merge pull request #5038 from espnet/kamo-naoyuki-patch-2
    
    Fix for  format_wav_scp.py
Task : 
egs2/ljspeech/tts1

steps to reproduce :
1) cd to egs2/ljspeech/tts1 and run local/mfa.sh

error log file : (espnet/egs2/ljspeech/tts1/data/local/mfa/tmp/logs/train_g2p.log)

# mfa train_g2p -j 12 --clean --phonetisaurus -t data/local/mfa/tmp data/local/mfa/train_dict.txt data/local/mfa/g2p/english_us_espeak.zip 
# Started at Fri Mar 24 20:30:15 CDT 2023
#
/home/eng/s/sxc220013/Documents/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
Traceback (most recent call last):
  File "/home/eng/s/sxc220013/Documents/espnet/tools/anaconda/envs/espnet/bin/mfa", line 5, in <module>
    from montreal_forced_aligner.command_line.mfa import main
  File "/home/eng/s/sxc220013/Documents/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/montreal_forced_aligner/__init__.py", line 6, in <module>
    import montreal_forced_aligner.command_line as command_line
  File "/home/eng/s/sxc220013/Documents/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/montreal_forced_aligner/command_line/__init__.py", line 13, in <module>
    from montreal_forced_aligner.command_line.mfa import create_parser, main
  File "/home/eng/s/sxc220013/Documents/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 18, in <module>
    from montreal_forced_aligner.command_line.model import run_model
  File "/home/eng/s/sxc220013/Documents/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/montreal_forced_aligner/command_line/model.py", line 8, in <module>
    from montreal_forced_aligner.config import get_temporary_directory
  File "/home/eng/s/sxc220013/Documents/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/montreal_forced_aligner/config.py", line 228, in <module>
    USE_COLORS = load_global_config().get("terminal_colors", True)
  File "/home/eng/s/sxc220013/Documents/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/montreal_forced_aligner/config.py", line 221, in load_global_config
    data = yaml.safe_load(f)
  File "/home/eng/s/sxc220013/Documents/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/home/eng/s/sxc220013/Documents/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/home/eng/s/sxc220013/Documents/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/home/eng/s/sxc220013/Documents/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/home/eng/s/sxc220013/Documents/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/eng/s/sxc220013/Documents/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/home/eng/s/sxc220013/Documents/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/eng/s/sxc220013/Documents/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  ******File "/home/eng/s/sxc220013/Documents/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/yaml/constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:pathlib.PosixPath'

  in "/home/eng/s/sxc220013/Documents/MFA/global_config.yaml", line 16, column 22
# Accounting: time=0 threads=1
# Ended (code 1) at Fri Mar 24 20:30:15 CDT 2023, elapsed time 0 seconds******

I read that sqlalchemy and prratio versions were causing trouble in https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/issues/551
I changed the versions to praatio=5.1.1 sqlachemy=1.4.3
The error message changed to the one mentioned above(mentioned in bold).
[train_g2p.log](https://github.com/espnet/espnet/files/11067718/train_g2p.log)

**Comment by Fhrozen** [comment]
I am currently check this, But you may test pretrained model:
`./local/run_mfa.sh --train false --language "" --g2p_model english_us_mfa`

**Comment by Fhrozen** [comment]
As you mention, sqlachemy=1.4.3 is the error.

Just remember to delete `/home/eng/s/sxc220013/Documents/MFA/global_config.yaml` before executing again, this will generate a new yaml that matches the sqlalchemy version

also: `pip install sqlalchemy==1.4.45` is fine I have no problem with the praatio version (Using praatio ver 6.0.0)
