### ISSUE TITLE
Issue with OmegaConf - ASR using Wav2Vec Upstream

### ISSUE THREAD

**Issue by iamsashank09** [espnet/espnet#5064]
Task: ASR
Data: Custom Data

Config: Using Wav2Vec as feature extractor
https://github.com/espnet/espnet/blob/master/egs2/librispeech/asr1/conf/tuning/train_asr_conformer7_wav2vec2_960hr_large.yaml

To start with, this was the first issue I ran into, running Stage 10 - 

```
ModuleNotFoundError: No module named 's3prl'
Error: S3PRL is not properly installed.
Please install S3PRL: cd ${MAIN_ROOT}/tools && make s3prl.done
```

So I went ahead and did what was suggested, which installed s3prl properly, but left this message in red. 

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
hydra-core 1.0.7 requires antlr4-python3-runtime==4.8, but you have antlr4-python3-runtime 4.9.3 which is incompatible.
hydra-core 1.0.7 requires omegaconf<2.1,>=2.0.5, but you have omegaconf 2.3.0 which is incompatible.
fairseq 1.0.0a0+313ff05 requires omegaconf<2.1, but you have omegaconf 2.3.0 which is incompatible.
Successfully installed antlr4-python3-runtime-4.9.3 omegaconf-2.3.0 s3prl-0.4.10 setuptools-59.5.0 transformers-4.27.3
```

I am now running into this error, when I run Stage 10 - 

`ImportError: cannot import name 'get_ref_type' from 'omegaconf._utils' (/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/omegaconf/_utils.py)`

I would really help any advice on this error, Thanks a lot.

**Comment by sw005320** [comment]
@simpleoier, can you check this?

**Comment by simpleoier** [comment]
@iamsashank09 I think it is because your omegaconf version is high. Can you try to install omegaconf=2.0.6? It works well on my side.

**Comment by iamsashank09** [comment]
Hi @simpleoier, 

I tried installing omegaconf == 2.0.6 and this is what PIP gave me -> 

`s3prl 0.4.10 requires omegaconf>=2.1.1, but you have omegaconf 2.0.6 which is incompatible.`

That would be a problem with s3prl, right?

**Comment by simpleoier** [comment]
Yeah. S3PRL requires to install omegaconf>2.1, but it is not compatible with wav2vec2 models.
Anyway, installing omegaconf=2.0.6 should be ok. Did you try to run the training again?

**Comment by iamsashank09** [comment]
Thanks @simpleoier , I went back to omegaconf = 2.0.6, even with S3PRL installed, ran my recipe again. It looks like that error is resolved. 

I'm guessing its unrelated, but running into this error:

`Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [232, 1, 80256, 2]`

**Comment by iamsashank09** [comment]
Hi @simpleoier , I am actually trying to figure that out. Unable to identify what the 4th dimension is, actually. Where do I suggest the issue could possibly be?
I have trained on this exact data, from scratch earlier, using the `train_asr_transformer.yaml`, and it seemed to run. Is there something silly I'm missing?

**Comment by iamsashank09** [comment]
I'm trying to trace this issue, from the error log, I found that it has input being passed in this file named s3prl.py

```
Traceback (most recent call last):
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/skakarap/Research/espnet/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/home/skakarap/Research/espnet/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/home/skakarap/Research/espnet/espnet/espnet2/tasks/abs_task.py", line 1043, in main
    cls.main_worker(args)
  File "/home/skakarap/Research/espnet/espnet/espnet2/tasks/abs_task.py", line 1348, in main_worker
    cls.trainer.run(
  File "/home/skakarap/Research/espnet/espnet/espnet2/train/trainer.py", line 290, in run
    all_steps_are_invalid = cls.train_one_epoch(
  File "/home/skakarap/Research/espnet/espnet/espnet2/train/trainer.py", line 567, in train_one_epoch
    retval = model(**batch)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/skakarap/Research/espnet/espnet/espnet2/asr/espnet_model.py", line 217, in forward
    encoder_out, encoder_out_lens = self.encode(speech, speech_lengths)
  File "/home/skakarap/Research/espnet/espnet/espnet2/asr/espnet_model.py", line 358, in encode
    feats, feats_lengths = self._extract_feats(speech, speech_lengths)
  File "/home/skakarap/Research/espnet/espnet/espnet2/asr/espnet_model.py", line 423, in _extract_feats
    feats, feats_lengths = self.frontend(speech, speech_lengths)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/skakarap/Research/espnet/espnet/espnet2/asr/frontend/s3prl.py", line 103, in forward
    feats, feats_lens = self.upstream(input, input_lengths)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/s3prl/nn/upstream.py", line 209, in forward
    hidden_states = self.upstream(wavs_list)["hidden_states"]
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/s3prl/upstream/interfaces.py", line 103, in __call__
    result = super().__call__(wavs, *args, **kwargs) or {}
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/s3prl/upstream/wav2vec2/expert.py", line 77, in forward
    results = self.model.extract_features(
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/s3prl/upstream/wav2vec2/wav2vec2_model.py", line 2820, in extract_features
    res = self.forward(
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/s3prl/upstream/wav2vec2/wav2vec2_model.py", line 2648, in forward
    features = self.feature_extractor(source)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/s3prl/upstream/wav2vec2/wav2vec2_model.py", line 2937, in forward
    x = conv(x)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [232, 1, 80256, 2]
```

I just checked out the size of the input before it is passed to this function, in s3prl (below are the lines of code mentioned in the error, line 103 of `espnet/espnet2/asr/frontend/s3prl.py`)

```
    def forward(
        self, input: torch.Tensor, input_lengths: torch.Tensor
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        feats, feats_lens = self.upstream(input, input_lengths)
```

I printed out the shape of the 'input', being passed to self.upstream() and it prints out `torch.Size([232, 80256, 2])`

So, that means the input is of the 3D shape expected, but where are things changing into the 4th dimension? Does it have anything to do with s3prl? 

Appreciate your advice and guidance.

**Comment by simpleoier** [comment]
@iamsashank09 Sorry, I forgot to reply. The input shouldn't have 2 at the 3rd dimension. It is probably your channel number of the speech. Upstream model [here](https://github.com/s3prl/s3prl/blob/main/s3prl/nn/upstream.py#L184) only accept single-channel speech input.
