### ISSUE TITLE
ASR on own data, Wav2Vec2 as upstream - Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [232, 1, 80256, 2]

### ISSUE THREAD

**Issue by iamsashank09** [espnet/espnet#5089]
Task: ASR
Data: Custom data

Config: Using Wav2Vec as feature extractor
https://github.com/espnet/espnet/blob/master/egs2/librispeech/asr1/conf/tuning/train_asr_conformer7_wav2vec2_960hr_large.yaml

Here's the command I use to run Stage 11. 

```
./asr.sh --stage 11 --stop_stage 11 --train_set traindir --valid_set validdir --test_sets testdir \
 --asr_config "conf/tuning/train_asr_conformer7_wav2vec2_960hr_large.yaml" --asr_tag "$ASR_FOLDER_NAME" \
 --ngpu 1 --feats_normalize utterance_mvn
```
I'm unable to figure out where I should be looking, to solve this issue. What should I be focusing on?

I have been able to train my model with the same data, when I've trained it with config: https://github.com/espnet/espnet/blob/master/egs2/librispeech/asr1/conf/tuning/train_asr_transformer.yaml

It's the same process, all the stages 1 to 5, then running a fresh stage 10 and 11 using the wav2vec2 config for using SSLR. 

The stage 10 runs fine, this is the output from Stage 10 - 

```
2023-04-07T16:02:03 (asr.sh:267:main) ./asr.sh --stage 10 --stop_stage 10 --train_set traindir --valid_set validdir --test_sets testdir --asr_config conf/tuning/train_asr_conformer7_wav2vec2_960hr_large.yaml --feats_normalize utterance_mvn
2023-04-07T16:02:04 (asr.sh:1021:main) Stage 10: ASR collect stats: train_set=dump/raw/traindir, valid_set=dump/raw/validdir
2023-04-07T16:02:04 (asr.sh:1071:main) Generate 'exp/asr_stats_raw_bpe500/run.sh'. You can resume the process from stage 10 using this script
2023-04-07T16:02:04 (asr.sh:1075:main) ASR collect-stats started... log: 'exp/asr_stats_raw_bpe500/logdir/stats.*.log'
2023-04-07T16:04:21 (asr.sh:1621:main) Skip the uploading stage
2023-04-07T16:04:21 (asr.sh:1673:main) Skip the uploading to HuggingFace stage
2023-04-07T16:04:21 (asr.sh:1676:main) Successfully finished. [elapsed=138s]
```

This is the error I get in Stage 11, from the train.log:

```
[gpu004] 2023-04-07 16:04:37,860 (abs_task:1195) INFO: Scheduler: WarmupLR(warmup_steps=40000)
[gpu004] 2023-04-07 16:04:37,864 (abs_task:1204) INFO: Saving the configuration in exp/asr_cordi_wav2vec_upstream_50wav_500token_training/config.yaml
[gpu004] 2023-04-07 16:04:38,086 (asr:471) INFO: Optional Data Names: ('text_spk2', 'text_spk3', 'text_spk4')
[gpu004] 2023-04-07 16:04:38,170 (abs_task:1559) INFO: [train] dataset:
ESPnetDataset(
  speech: {"path": "dump/raw/traindir/wav.scp", "type": "sound"}
  text: {"path": "dump/raw/traindir/text", "type": "text"}
  preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x7f23d5413220>)
[gpu004] 2023-04-07 16:04:38,170 (abs_task:1560) INFO: [train] Batch sampler: NumElementsBatchSampler(N-batch=20, batch_bins=40000000, sort_in_batch=descending, sort_batch=descending)
[gpu004] 2023-04-07 16:04:38,171 (abs_task:1561) INFO: [train] mini-batch sizes summary: N-batch=20, mean=388.1, min=2, max=1037
[gpu004] 2023-04-07 16:04:38,188 (asr:471) INFO: Optional Data Names: ('text_spk2', 'text_spk3', 'text_spk4')
[gpu004] 2023-04-07 16:04:38,194 (abs_task:1559) INFO: [valid] dataset:
ESPnetDataset(
  speech: {"path": "dump/raw/validdir/wav.scp", "type": "sound"}
  text: {"path": "dump/raw/validdir/text", "type": "text"}
  preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x7f23d5413670>)
[gpu004] 2023-04-07 16:04:38,194 (abs_task:1560) INFO: [valid] Batch sampler: NumElementsBatchSampler(N-batch=3, batch_bins=40000000, sort_in_batch=descending, sort_batch=descending)
[gpu004] 2023-04-07 16:04:38,194 (abs_task:1561) INFO: [valid] mini-batch sizes summary: N-batch=3, mean=322.7, min=152, max=489
[gpu004] 2023-04-07 16:04:38,196 (asr:471) INFO: Optional Data Names: ('text_spk2', 'text_spk3', 'text_spk4')
[gpu004] 2023-04-07 16:04:38,212 (abs_task:1559) INFO: [plot_att] dataset:
ESPnetDataset(
  speech: {"path": "dump/raw/validdir/wav.scp", "type": "sound"}
  text: {"path": "dump/raw/validdir/text", "type": "text"}
  preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x7f23d5413dc0>)
[gpu004] 2023-04-07 16:04:38,212 (abs_task:1560) INFO: [plot_att] Batch sampler: UnsortedBatchSampler(N-batch=968, batch_size=1, key_file=exp/asr_stats_raw_bpe500/valid/speech_shape, 
[gpu004] 2023-04-07 16:04:38,212 (abs_task:1561) INFO: [plot_att] mini-batch sizes summary: N-batch=3, mean=1.0, min=1, max=1
[gpu004] 2023-04-07 16:04:38,273 (trainer:284) INFO: 1/35epoch started
Traceback (most recent call last):
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/skakarap/Research/espnet/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/home/skakarap/Research/espnet/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/home/skakarap/Research/espnet/espnet/espnet2/tasks/abs_task.py", line 1043, in main
    cls.main_worker(args)
  File "/home/skakarap/Research/espnet/espnet/espnet2/tasks/abs_task.py", line 1348, in main_worker
    cls.trainer.run(
  File "/home/skakarap/Research/espnet/espnet/espnet2/train/trainer.py", line 290, in run
    all_steps_are_invalid = cls.train_one_epoch(
  File "/home/skakarap/Research/espnet/espnet/espnet2/train/trainer.py", line 567, in train_one_epoch
    retval = model(**batch)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/skakarap/Research/espnet/espnet/espnet2/asr/espnet_model.py", line 217, in forward
    encoder_out, encoder_out_lens = self.encode(speech, speech_lengths)
  File "/home/skakarap/Research/espnet/espnet/espnet2/asr/espnet_model.py", line 358, in encode
    feats, feats_lengths = self._extract_feats(speech, speech_lengths)
  File "/home/skakarap/Research/espnet/espnet/espnet2/asr/espnet_model.py", line 423, in _extract_feats
    feats, feats_lengths = self.frontend(speech, speech_lengths)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/skakarap/Research/espnet/espnet/espnet2/asr/frontend/s3prl.py", line 103, in forward
    feats, feats_lens = self.upstream(input, input_lengths)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/s3prl/nn/upstream.py", line 209, in forward
    hidden_states = self.upstream(wavs_list)["hidden_states"]
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/s3prl/upstream/interfaces.py", line 103, in __call__
    result = super().__call__(wavs, *args, **kwargs) or {}
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/s3prl/upstream/wav2vec2/expert.py", line 77, in forward
    results = self.model.extract_features(
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/s3prl/upstream/wav2vec2/wav2vec2_model.py", line 2820, in extract_features
    res = self.forward(
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/s3prl/upstream/wav2vec2/wav2vec2_model.py", line 2648, in forward
    features = self.feature_extractor(source)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/s3prl/upstream/wav2vec2/wav2vec2_model.py", line 2937, in forward
    x = conv(x)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [232, 1, 80256, 2]
# Accounting: time=19 threads=1
# Ended (code 1) at Fri Apr  7 16:04:41 EDT 2023, elapsed time 19 seconds
```

Truly appreciate any help and guidance on this, Thank you.

**Comment by iamsashank09** [comment]
I'm trying to trace this issue, from the error log, I found that it has input being passed in this file named s3prl.py

I just checked out the size of the input before it is passed to this function, in s3prl (below are the lines of code mentioned in the error, line 103 of `espnet/espnet2/asr/frontend/s3prl.py`)

```
    def forward(
        self, input: torch.Tensor, input_lengths: torch.Tensor
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        feats, feats_lens = self.upstream(input, input_lengths)
```

I printed out the shape of the 'input', being passed to self.upstream() and it prints out `torch.Size([232, 80256, 2])`

So, that means the input is of the 3D shape expected, but where are things changing into the 4th dimension? Does it have anything to do with s3prl? 

Appreciate your advice and guidance.

**Comment by sw005320** [comment]
Thanks for your report.
@simpleoier, could you take a look at this issue?

**Comment by simpleoier** [comment]
@iamsashank09 The wav2vec2 model accepts 1-channel speech and the expected size of input is `(batch_size, length)`. In wav2vec2, the model would expand the size to `(batch_size, 1, length)` at [here](https://github.com/s3prl/s3prl/blob/main/s3prl/upstream/wav2vec2/wav2vec2_model.py#L2934).
You need to figure out where the 3rd dimension whose value is 2 is from.

**Comment by iamsashank09** [comment]
It all came down to the data! 
I somehow missed that we require mono channel audio, which is what the issue was. 

I converted my stereo audio into mono channel and that fixed it. Thanks a lot!
