### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory

### ISSUE THREAD

**Issue by ben-8878** [espnet/espnet#5135]
I am using whsiper finetuning script to do finetuning base on whisper_large_V2 model
command:
`./asr.sh --skip_data_prep false --skip_train false --skip_eval true --lang zh --fs 16000 --ngpu 4 --nj 16 --stage 10 --stop_stage 13 --gpu_inference true --inference_nj 4 --token_type whisper_multilingual --feats_normalize '' --max_wav_duration 30 --audio_format wav --feats_type raw --use_lm false --asr_tag whisper_large_V2_finetune_lr1e-5_adamw_wd1e-2_3epochs --asr_config conf/tuning/train_asr_whisper_full.yaml --inference_config conf/decode_asr_whisper_noctc_greedy.yaml --inference_asr_model valid.acc.ave.pth --train_set train --valid_set dev --test_sets test --stage 10`

error:
```
Traceback (most recent call last):
  File "/home/ybZhang/miniconda3/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ybZhang/miniconda3/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/disk2/ybZhang/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/data/disk2/ybZhang/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/data/disk2/ybZhang/espnet/espnet2/tasks/abs_task.py", line 1054, in main
    cls.main_worker(args)
  File "/data/disk2/ybZhang/espnet/espnet2/tasks/abs_task.py", line 1164, in main_worker
    model = cls.build_model(args=args)
  File "/data/disk2/ybZhang/espnet/espnet2/tasks/asr.py", line 540, in build_model
    encoder = encoder_class(input_size=input_size, **args.encoder_conf)
  File "/data/disk2/ybZhang/espnet/espnet2/asr/encoder/whisper_encoder.py", line 53, in __init__
    _model = whisper.load_model(whisper_model, download_root=download_dir)
  File "/home/ybZhang/miniconda3/envs/espnet/lib/python3.8/site-packages/whisper/__init__.py", line 144, in load_model
    checkpoint = torch.load(fp, map_location=device)
  File "/home/ybZhang/miniconda3/envs/espnet/lib/python3.8/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/ybZhang/miniconda3/envs/espnet/lib/python3.8/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/home/ybZhang/miniconda3/envs/espnet/lib/python3.8/site-packages/torch/serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/home/ybZhang/miniconda3/envs/espnet/lib/python3.8/site-packages/torch/serialization.py", line 1083, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/home/ybZhang/miniconda3/envs/espnet/lib/python3.8/site-packages/torch/serialization.py", line 1052, in restore_location
    return default_restore_location(storage, map_location)
  File "/home/ybZhang/miniconda3/envs/espnet/lib/python3.8/site-packages/torch/serialization.py", line 215, in default_restore_location
    result = fn(storage, location)
  File "/home/ybZhang/miniconda3/envs/espnet/lib/python3.8/site-packages/torch/serialization.py", line 187, in _cuda_deserialize
    return obj.cuda(device)
  File "/home/ybZhang/miniconda3/envs/espnet/lib/python3.8/site-packages/torch/_utils.py", line 80, in _cuda
    untyped_storage = torch.UntypedStorage(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 31.75 GiB total capacity; 1.05 GiB already allocated; 19.75 MiB free; 1.13 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by iamsashank09** [comment]
Ran into the exact issue a little while ago, solution would be to got to your config file, and reduce the number of bins. It would be a parameter with name `batch_bins` . 

My understanding is, it dictates the amount of data in a single batch, which is loaded onto the GPU, so reducing that will reduce the memory overload on the GPU at a given instance. The trade-off would probably be longer training time, since you're loading lesser items at once. 

Please feel free to correct me if I've gotten my understanding wrong.

**Comment by v-yunbin** [comment]
I think it's caused by the model being too large, because it happens when the model is loaded, so modifying the bin may not work, but I will try  more smaller batch_bins.

**Comment by sw005320** [comment]
Yes, if the model size is too large, the memory consumption becomes large, and reducing `batch_bins` is a solution for this.
In this case, the batch size becomes smaller, which makes training unstable. So, please also increase `accum_grad` (e.g., if you reduce `batch_bins` by half, you can increase `accum_grad` to be double and make `batch_bins * accum_grad` to be equivalent).

**Comment by v-yunbin** [comment]
I reduce batch_bins to 200000， but it stll not work. When I reduce nj from 16 to 2, it work but slowly. 
another thing is that zh_token_list just include english character not chinese character.  it is strange, because my transciption include chinese and english character .
