### ISSUE TITLE
ASR on own data, XLS-R as Upstream, ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 512, 1])

### ISSUE THREAD

**Issue by iamsashank09** [espnet/espnet#5136]
Task: ASR
Data: Custom data

Config: Using Wav2Vec as feature extractor
https://github.com/espnet/espnet/blob/master/egs2/mr_openslr64/asr1/conf/tuning/train_asr_conformer_xlsr.yaml

Here's the command I use to run Stage 11.

./asr.sh --stage 11 --stop_stage 11 --train_set traindir --valid_set validdir --test_sets testdir \
 --asr_config "conf/tuning/train_asr_conformer_xlsr.yaml" --asr_tag "$ASR_FOLDER_NAME" \
 --ngpu 2 --nj 64 --feats_normalize utterance_mvn

I've ran on the same data with Wav2Vec and from scratch.

It's the same process, all the stages 1 to 5, then running a fresh stage 10 and 11 using the XLSR config for using SSLR.

The stage 10 runs fine, this is the output from Stage 10 -

```
2023-04-23T09:26:47 (asr.sh:267:main) ./asr.sh --stage 10 --stop_stage 10 --train_set traindir --valid_set validdir --test_sets testdir --asr_config conf/tuning/train_asr_conformer_xlsr.yaml --ngpu 3 --nj 64 --feats_normalize utterance_mvn
2023-04-23T09:26:48 (asr.sh:1021:main) Stage 10: ASR collect stats: train_set=dump/raw/traindir, valid_set=dump/raw/validdir
2023-04-23T09:26:49 (asr.sh:1071:main) Generate 'exp/asr_stats_raw_bpe500/run.sh'. You can resume the process from stage 10 using this script
2023-04-23T09:26:49 (asr.sh:1075:main) ASR collect-stats started... log: 'exp/asr_stats_raw_bpe500/logdir/stats.*.log'
2023-04-23T09:29:37 (asr.sh:1621:main) Skip the uploading stage
2023-04-23T09:29:37 (asr.sh:1673:main) Skip the uploading to HuggingFace stage
2023-04-23T09:29:37 (asr.sh:1676:main) Successfully finished. [elapsed=170s]


```

However, Stage 11 throws:
```
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/skakarap/Research/espnet/espnet/espnet2/tasks/abs_task.py", line 1348, in main_worker
    cls.trainer.run(
  File "/home/skakarap/Research/espnet/espnet/espnet2/train/trainer.py", line 290, in run
    all_steps_are_invalid = cls.train_one_epoch(
  File "/home/skakarap/Research/espnet/espnet/espnet2/train/trainer.py", line 567, in train_one_epoch
    retval = model(**batch)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/skakarap/Research/espnet/espnet/espnet2/asr/espnet_model.py", line 217, in forward
    encoder_out, encoder_out_lens = self.encode(speech, speech_lengths)
  File "/home/skakarap/Research/espnet/espnet/espnet2/asr/espnet_model.py", line 380, in encode
    encoder_out, encoder_out_lens, _ = self.encoder(feats, feats_lengths)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/skakarap/Research/espnet/espnet/espnet2/asr/encoder/conformer_encoder.py", line 343, in forward
    xs_pad, masks = self.encoders(xs_pad, masks)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/skakarap/Research/espnet/espnet/espnet/nets/pytorch_backend/transformer/repeat.py", line 30, in forward
    args = m(*args)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/skakarap/Research/espnet/espnet/espnet/nets/pytorch_backend/conformer/encoder_layer.py", line 156, in forward
    x = residual + stoch_layer_coeff * self.dropout(self.conv_module(x))
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/skakarap/Research/espnet/espnet/espnet/nets/pytorch_backend/conformer/convolution.py", line 75, in forward
    x = self.activation(self.norm(x))
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py", line 171, in forward
    return F.batch_norm(
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/functional.py", line 2448, in batch_norm
    _verify_batch_size(input.size())
  File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/functional.py", line 2416, in _verify_batch_size
    raise ValueError("Expected more than 1 value per channel when training, got input size {}".format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 512, 1])
```

Appreciate any guidance on this!

**Comment by iamsashank09** [comment]
Changed something up, went through old issues and reduced the number of GPU's to 1, because an old issue suggested this was because of multiple GPU's. 

Now I have a new error:

`espnet.nets.pytorch_backend.transformer.subsampling.TooShortUttError: has 6 frames and is too short for subsampling (it needs more than 7 frames), return empty results`

Which, by it's looks is not related to the error above. So did using a single GPU help?

**Comment by sw005320** [comment]
As the error message says, it is better to remove the very short sentences.
