### ISSUE TITLE
Problem with DataLoader when adapting enh_diar1 to flexible speakers in LibriMix. Fixed with batch size = 1

### ISSUE THREAD

**Issue by egruttadauria98** [espnet/espnet#5145]
**Describe the bug**
Premise: I am using the adapt script when training from scratch, as opposed to training first a 2 speaker model and then finetuning it with a flexible number of speakers.

First of all, let me start thanking you for your work with espnet!

My understanding of the error is that it is problematic when in the same batch there are samples coming from both Libri2Mix and Libri3Mix and the error happens when the dimension needs to be expanded.

Using batch_size=1 and accumulating the gradient fixes the problem. 

**Basic environments:**
- OS information: Linux 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64
- python version: `3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC 11.2.0]`
- espnet version: `espnet 202301`
- pytorch version: `pytorch 1.10.1`
- Git hash: `78db412a34efb28f6a48688666236ded736a3c6f`
  - Commit date: `Sat Apr 1 19:27:08 2023 +0000`

**Environments from `torch.utils.collect_env`:**
```
Collecting environment information...
PyTorch version: 1.10.1
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-53-generic-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.10.1
[pip3] torch-complex==0.4.3
[pip3] torch-optimizer==0.3.0
[pip3] torchaudio==0.10.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.23.5           py38h14f4228_0  
[conda] numpy-base                1.23.5           py38h31eccc5_0  
[conda] pytorch                   1.10.1          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.1                    pypi_0    pypi
[conda] torch-complex             0.4.3                    pypi_0    pypi
[conda] torch-optimizer           0.3.0                    pypi_0    pypi
[conda] torchaudio                0.10.1               py38_cu113    pytorch
```

**Task information:**
 - Task: enh_diar1, adapt to flexible number of speakers
 - Recipe: Libri2Mix and Libri3Mix
 - ESPnet2

**To Reproduce**
1. move to a recipe directory, e.g., `cd egs2/librimix/enh_diar1`
2. execute `local/run_adapt.sh` but without a checkpoint/pretrained model (i.e. from scratch)

**Error logs**
Traceback (most recent call last):
  File "/tsi/clusterhome/gruttadauria/espnet/tools/miniconda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tsi/clusterhome/gruttadauria/espnet/tools/miniconda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tsi/clusterhome/gruttadauria/espnet/espnet2/bin/enh_s2t_train.py", line 23, in <module>
    main()
  File "/tsi/clusterhome/gruttadauria/espnet/espnet2/bin/enh_s2t_train.py", line 19, in main
    EnhS2TTask.main(cmd=cmd)
  File "/tsi/clusterhome/gruttadauria/espnet/espnet2/tasks/abs_task.py", line 1054, in main
    cls.main_worker(args)
  File "/tsi/clusterhome/gruttadauria/espnet/espnet2/tasks/abs_task.py", line 1240, in main_worker
    collect_stats(
  File "/tsi/clusterhome/gruttadauria/espnet/tools/miniconda/envs/espnet/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/tsi/clusterhome/gruttadauria/espnet/espnet2/main_funcs/collect_stats.py", line 51, in collect_stats
    for iiter, (keys, batch) in enumerate(itr, 1):
  File "/tsi/clusterhome/gruttadauria/espnet/tools/miniconda/envs/espnet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/tsi/clusterhome/gruttadauria/espnet/tools/miniconda/envs/espnet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/tsi/clusterhome/gruttadauria/espnet/tools/miniconda/envs/espnet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/tsi/clusterhome/gruttadauria/espnet/tools/miniconda/envs/espnet/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/tsi/clusterhome/gruttadauria/espnet/tools/miniconda/envs/espnet/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/tsi/clusterhome/gruttadauria/espnet/tools/miniconda/envs/espnet/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 40, in fetch
    return self.collate_fn(data)
  File "/tsi/clusterhome/gruttadauria/espnet/espnet2/train/collate_fn.py", line 34, in __call__
    return common_collate_fn(
  File "/tsi/clusterhome/gruttadauria/espnet/espnet2/train/collate_fn.py", line 208, in common_collate_fn
    tensor = pad_list(tensor_list, pad_value)
  File "/tsi/clusterhome/gruttadauria/espnet/espnet/nets/pytorch_backend/nets_utils.py", line 59, in pad_list
    pad[i, : xs[i].size(0)] = xs[i]
RuntimeError: The expanded size of the tensor (3) must match the existing size (2) at non-singleton dimension 1.  Target sizes: [94800, 3].  Tensor sizes: [94800, 2]

**Comment by sw005320** [comment]
Thanks for the report!
Yeah, `batch_size=1` may solve the issue, but this is inefficient.
Let us check this issue, and we will get back to you.
@soumimaiti

**Comment by egruttadauria98** [comment]
Hi! Are there any updates on the potential timeline to fix this bug?
Thank you.

**Comment by sw005320** [comment]
@soumimaiti told me that she is preparing a PR.
@soumimaiti, can you tell us the status?
