### ISSUE TITLE
RuntimeError: Tensors must have same number of dimensions: got 2 and 3 for mp3 files on LJSpeech recipe or any other recipe

### ISSUE THREAD

**Issue by ramiKammoun** [espnet/espnet#5174]
""
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/espnet/espnet2/bin/tts_train.py", line 22, in <module>
    main()
  File "/content/espnet/espnet2/bin/tts_train.py", line 18, in main
    TTSTask.main(cmd=cmd)
  File "/content/espnet/espnet2/tasks/abs_task.py", line 1054, in main
    cls.main_worker(args)
  File "/content/espnet/espnet2/tasks/abs_task.py", line 1359, in main_worker
    cls.trainer.run(
  File "/content/espnet/espnet2/train/trainer.py", line 290, in run
    all_steps_are_invalid = cls.train_one_epoch(
  File "/content/espnet/espnet2/train/trainer.py", line 567, in train_one_epoch
    retval = model(**batch)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/espnet/espnet2/tts/espnet_model.py", line 151, in forward
    return self.tts(**batch)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/espnet/espnet2/tts/tacotron2/tacotron2.py", line 324, in forward
    after_outs, before_outs, logits, att_ws = self._forward(
  File "/content/espnet/espnet2/tts/tacotron2/tacotron2.py", line 409, in _forward
    return self.dec(hs, hlens, ys)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/espnet/espnet/nets/pytorch_backend/tacotron2/decoder.py", line 437, in forward
    xs = torch.cat([att_c, prenet_out], dim=1)
RuntimeError: Tensors must have same number of dimensions: got 2 and 3
\# Accounting: time=14 threads=1
\# Ended (code 1) at Wed May 17 10:08:03 UTC 2023, elapsed time 14 seconds
"" 
So I have a problem with ESPnet, the LJSpeech recipe, when I use it but I use mp3 files, for some reason it's always printing these problems of tensors dimensions not being the same. I changed them and converted them to WAV format but it still doesn't accept them. 
On the other hands, when i use official dataset from any language, they get accepted and passed on and the training starts.

**Comment by ramiKammoun** [comment]
I have fixed the problem by changing the "channels" characteristic in my converted audio files from _**stereo**_ to _**mono**_
