### ISSUE TITLE
I want to train fastspeech using espeak-ng module.

### ISSUE THREAD

**Issue by soonguKwon** [espnet/espnet#5176]
**Describe the bug**

**Basic environments:**
 - OS information: Linux 4.15.0-176-generic #185-Ubuntu SMP Tue Mar 29 17:40:04 UTC 2022 x86_64
 - python version: `3.7.4 (default, Aug 13 2019, 20:35:49)  [GCC 7.3.0]`
 - espnet version: `espnet 202301`
 - pytorch version `pytorch 1.11.0+cu102`

You can obtain them by the following command
```
cd <espnet-root>/tools
. ./activate_python.sh

echo "- OS information: `uname -mrsv`"
python3 << EOF
import sys, espnet, torch
pyversion = sys.version.replace('\n', ' ')
print(f"""- python version: \`{pyversion}\`
- espnet version: \`espnet {espnet.__version__}\`
- pytorch version: \`pytorch {torch.__version__}\`""")
EOF
cat << EOF
- Git hash: \`$(git rev-parse HEAD)\`
  - Commit date: \`$(git log -1 --format='%cd')\`
EOF
```

**Environments from `torch.utils.collect_env`:**

PyTorch version: 1.11.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
Clang version: Could not collect
CMake version: version 3.19.2
Libc version: glibc-2.10

Python version: 3.7.4 (default, Aug 13 2019, 20:35:49)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-176-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 11.3.58
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 525.85.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.11.0
[pip3] torch-complex==0.4.3
[pip3] torch-optimizer==0.3.0
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he8ac12f_0  
[conda] mkl_fft                   1.3.0            py37h54f3939_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] numpydoc                  0.9.1                      py_0  
[conda] torch                     1.13.1                   pypi_0    pypi
[conda] torch-complex             0.4.3                    pypi_0    pypi
[conda] torch2trt                 0.4.0                    pypi_0    pypi
[conda] torchaudio                0.9.0                    pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.10.0+cu111             pypi_0    pypi

```
You can obtain them by the following command

```
cd <espnet-root>/tools
. ./activate_python.sh
python3 -m torch.utils.collect_env
```

**Task information:**
 - Task: TTS
 - Recipe: ljspeech
 - ESPnet2

**To Reproduce**
Steps to reproduce the behavior:
1.
./run.sh --stage 1 --stop-stage 1

for dset in tr_no_dev dev eval1; do
    utils/copy_data_dir.sh data/"${dset}"{,_phn}
    ./pyscripts/utils/convert_text_to_phn.py \
        --nj 32 \
        --g2p espeak_ng_english_us_vits \
        --cleaer tacotron \
        data/"${dset}"{,_phn}/text
done
2. train tacotron2
  ./run.sh \
    --train_set tr_no_dev_phn \
    --valid_set dev_phn \
    --test_sets "dev_phn eval1_phn" \
    --srctexts "data/tr_no_dev_phn/text" \
    --stage 2 \
    --ngpu 4 \
    --g2p none \
    --cleaner none \
2. decoding
   ./run.sh --stage 7 --tts_exp exp/tts_train_tacotron2_raw_phn_none --test_sets "tr_no_dev_phn dev_phn eval1_phn" --cleaner tacotron --g2p espeak_ng_english_us_vits
4. train fastspeech
  ./run.sh --stage 6 --train_config conf/tuning/train_fastspeech.yaml --teacher_dumpdir exp/tts_train_tacotron2_raw_phn_none/decode_train.loss.ave --train_set tr_no_dev_phn --valid_set dev_phn --test_sets "dev_phn eval1_phn" --srctexts "data/tr_no_dev_phn/text" --g2p none --cleaner none

**Error logs**
Traceback (most recent call last):
  File "/home/choiwh/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/choiwh/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/choiwh/espnet/espnet2/tasks/abs_task.py", line 1367, in main_worker
    distributed_option=distributed_option,
  File "/home/choiwh/espnet/espnet2/train/trainer.py", line 299, in run
    distributed_option=distributed_option,
  File "/home/choiwh/espnet/espnet2/train/trainer.py", line 566, in train_one_epoch
    retval = model(**batch)
  File "/home/choiwh/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/choiwh/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 963, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/choiwh/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/choiwh/espnet/espnet2/tts/espnet_model.py", line 151, in forward
    return self.tts(**batch)
  File "/home/choiwh/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/choiwh/espnet/espnet2/tts/fastspeech/fastspeech.py", line 532, in forward
    is_inference=False,
  File "/home/choiwh/espnet/espnet2/tts/fastspeech/fastspeech.py", line 448, in _forward
    hs = self.length_regulator(hs, ds)  # (B, T_feats, adim)
  File "/home/choiwh/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/choiwh/espnet/espnet/nets/pytorch_backend/fastspeech/length_regulator.py", line 66, in forward
    repeat = [torch.repeat_interleave(x, d, dim=0) for x, d in zip(xs, ds)]
  File "/home/choiwh/espnet/espnet/nets/pytorch_backend/fastspeech/length_regulator.py", line 66, in <listcomp>
    repeat = [torch.repeat_interleave(x, d, dim=0) for x, d in zip(xs, ds)]
RuntimeError: repeats must have the same size as input along dim

**Comment by Fhrozen** [comment]
There are two ways to get the duration of the phonemes if you want to train fastspeech:
1. Use the pre-trained model as described in your comment.
Check for the duration files and that the `reduce factor == 1` in your config files https://github.com/espnet/espnet/blob/d1074cef03725e5a73efffd0ab2467f18952e1e8/egs2/ljspeech/tts1/conf/tuning/train_fastspeech2.yaml#LL36C5-L36C57
2. Use MFA to get the alignments and durations.
There is an execution sample at: https://github.com/espnet/espnet/blob/master/egs2/ljspeech/tts1/local/run_mfa.sh
change `g2p_model` to apply our desired g2p.

**Comment by Fhrozen** [comment]
then, use the configuration: https://github.com/espnet/espnet/blob/master/egs2/ljspeech/tts1/conf/tuning/train_fastspeech.yaml.
It does not matter the model, but you need to check the reduction factor and that the audio frames are the same as the sum of the duration file.
