### ISSUE TITLE
Numpy version incompatibility during installation

### ISSUE THREAD

**Issue by jctian98** [espnet/espnet#5208]
**Describe the issue**
This is a known problem for Espnet installation. When conducting the command ` make TH_VERSION=1.13.1 CUDA_VERSION=11.7`, It raises the error:
```
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '<espnet>/tools/miniconda/envs/espnet/lib/python3.9/site-packages/numpy-1.24.3.dist-info/METADATA'
```
A simple solution is:
```
rm -r <espnet>/tools/miniconda/envs/espnet/lib/python3.9/site-packages/numpy*
pip3 install numpy==1.23
```
Note: `numpy` cannot be `1.24` due to the requirement `numpy<1.24` in `setup.py`.
After this, the installation can run well. Below is template information.

**Show the `check_install.py` status by using the following command**
```
cd <espnet-root>/tools
. ./activate_python.sh; python3 check_install.py
```

```
[x] python=3.9.16 (main, Mar  8 2023, 14:00:05)  [GCC 11.2.0]

Python modules:
[x] torch=1.13.1
[ ] torch cuda
[x] torch cudnn=8500
[x] torch nccl
Traceback (most recent call last):
  File "/scratch/bbjs/jtian1/espnet_master/espnet/tools/check_install.py", line 197, in <module>
    main()
  File "/scratch/bbjs/jtian1/espnet_master/espnet/tools/check_install.py", line 93, in main
    print(f"[x] chainer={chainer.__version__}")
AttributeError: module 'chainer' has no attribute '__version__'
```

**Basic environments:**
- OS information: Linux 4.18.0-372.46.1.el8_6.x86_64 #1 SMP Thu Feb 16 13:46:57 EST 2023 x86_64
- python version: `3.9.16 (main, Mar  8 2023, 14:00:05)  [GCC 11.2.0]`
- espnet version: `espnet 202304`
- pytorch version: `pytorch 1.13.1`
- Git hash: `d9ae3f7e4c9a964fbc365911bd712e6ad1f1425f`
  - Commit date: `Sat Jun 3 02:16:27 2023 +0000`

**Environments from `torch.utils.collect_env`:**
e.g.,
```
Collecting environment information...
PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux release 8.6 (Ootpa) (x86_64)
GCC version: (Spack GCC) 11.2.0
Clang version: Could not collect
CMake version: version 3.20.2
Libc version: glibc-2.28

Python version: 3.9.16 (main, Mar  8 2023, 14:00:05)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-372.46.1.el8_6.x86_64-x86_64-with-glibc2.28
Is CUDA available: False
CUDA runtime version: 11.6.112
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.13.1
[pip3] torch-complex==0.4.3
[pip3] torchaudio==0.13.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-service               2.4.0            py39h5eee18b_1  
[conda] mkl_fft                   1.3.6            py39h417a72b_1  
[conda] mkl_random                1.2.2            py39h417a72b_1  
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] numpy-base                1.24.3           py39h060ed82_1  
[conda] pytorch                   1.13.1          py3.9_cuda11.7_cudnn8.5.0_0    pytorch
[conda] pytorch-cuda              11.7                 h778d358_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-wpe               0.0.1                    pypi_0    pypi
[conda] torch-complex             0.4.3                    pypi_0    pypi
[conda] torchaudio                0.13.1               py39_cu117    pytorch
```

**To Reproduce**
Steps to reproduce the behavior by showing us the specific installation commands with their arguments, e.g.,
```
cd <espnet-root>/tools
make TH_VERSION=1.13.1 CUDA_VERSION=11.7
```

**Error logs**
```
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '<espnet>/tools/miniconda/envs/espnet/lib/python3.9/site-packages/numpy-1.24.3.dist-info/METADATA'
```

**Comment by sw005320** [comment]
Thanks a lot for the report.
This is an annoying issue.

It would be great if someone help to fix the issue.
Actually, I also faced the same issue and I have to manually delete/install Numpy :(

**Comment by FLabbaf97** [comment]
Can you explain more about how to resolve this problem? I am getting an error like this. 
I am running on macOs (m1 chip)
The error from running `make` is:

```
Perform on CPU mode: CPU_ONLY=0
PYTHON=/usr/local/bin/python3
PYTHON_VERSION=Python 3.12.2
USE_CONDA=1
TH_VERSION=2.1.0
WITH_OMP=ON
. ./activate_python.sh && conda install -y "numpy<1.24"
Channels:
 - conda-forge
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: \ warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package numpy-1.21.3-py310h6e1bb13_1 requires python >=3.10,<3.11.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ numpy <1.24  is installable with the potential options
│  ├─ numpy [1.19.2|1.19.4|...|1.23.5] would require
│  │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  ├─ numpy [1.19.2|1.19.4|...|1.23.5] would require
│  │  └─ python >=3.9,<3.10.0a0 , which can be installed;
│  ├─ numpy [1.21.3|1.21.4|...|1.23.5] would require
│  │  └─ python >=3.10,<3.11.0a0 , which can be installed;
│  └─ numpy [1.23.4|1.23.5] would require
│     └─ python >=3.11,<3.12.0a0 , which can be installed;
└─ pin-1 is not installable because it requires
   └─ python 3.12.* , which conflicts with any installable versions previously reported.

Pins seem to be involved in the conflict. Currently pinned specs:
 - python 3.12.* (labeled as 'pin-1')
 
 ```

**Comment by ROBERT-MCDOWELL** [comment]
espnet seems not to be compatible with python 3.12 actually.

**Comment by MiCaptain** [comment]
> espnet seems not to be compatible with python 3.12 actually.

Did u get it? Cause I been wrestling for quite some time here

**Comment by sw005320** [comment]
Do you need to use Python 3.12?
It has an issue, and we only support 3.11 and 3.10.
We'll investigate Python 3.12 issues in the future

<img width="944" alt="image" src="https://github.com/user-attachments/assets/c58ea241-92d2-4d34-af21-94dc60c883e6">

**Comment by MiCaptain** [comment]
> Do you need to use Python 3.12? It has an issue, and we only support 3.11 and 3.10. We'll investigate Python 3.12 issues in the future
>
No, I don't :(

I'm not the best at coding and handling Visual Studio. After that message yesterday, I downgraded to 3.11.9, but it still didn’t work for me :( 
I'm considering trying it out on Colab or something because I'm kind of a noob :( 
The "make" thing is driving me crazy. 
By the way, thank you for taking the time to address this message.

**Comment by Hitori-de** [comment]
Does ESPnet support python3.10/conda on windows?

**Comment by sw005320** [comment]
We don't include it in our support.
I think the basic function (e.g., inference) should work, but not sure about training.
Also, many utility scripts are running on Linux (but in this case, we may use WSL).

**Comment by ROBERT-MCDOWELL** [comment]
yes it would be nice to support python 3.12, numpy 2
