### ISSUE TITLE
ML Superb benchmark inference error

### ISSUE THREAD

**Issue by freddy5566** [espnet/espnet#5214]
**Describe the bug**

For some reason, the recipe could not properly produce the results during decoding. It raises an error of 
````
soundfile.LibsndfileError: <exception str() failed>
````
See a detailed error log at the bottom of this issue.

**Basic environments:**
 - OS information: Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-73-generic x86_64)
 - python version: 3.8.16
 - espnet version:  202304
 - Git hash 279ccfef219f563f2b68946ff0ee7614359230ba
   - Commit date Thu Jun 1 22:50:07 2023 -0700
 - pytorch version 1.13.1

**Environments from `torch.utils.collect_env`:**
e.g.,
```
Collecting environment information...
PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-73-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.5.119
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA RTX A5000
GPU 1: NVIDIA RTX A5000
GPU 2: NVIDIA RTX A5000
GPU 3: NVIDIA RTX A5000

Nvidia driver version: 530.41.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.13.1
[pip3] torch-complex==0.4.3
[pip3] torch-optimizer==0.3.0
[pip3] torchaudio==0.13.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2023.1.0         h6d00ec8_46342
[conda] mkl-service               2.4.0            py38h5eee18b_1
[conda] mkl_fft                   1.3.6            py38h417a72b_1
[conda] mkl_random                1.2.2            py38h417a72b_1
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch                   1.13.1          py3.8_cuda11.7_cudnn8.5.0_0    pytorch
[conda] pytorch-cuda              11.7                 h778d358_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.1                    pypi_0    pypi
[conda] torch-complex             0.4.3                    pypi_0    pypi
[conda] torch-optimizer           0.3.0                    pypi_0    pypi
[conda] torchaudio                0.13.1               py38_cu117    pytorch


**Task information:**
 - Task: Multilingual ASR
 - Recipe: ML Superb
 - ESPnet2

**To Reproduce**
Steps to reproduce the behavior:
1. move to a recipe directory, e.g., `cd egs2/ml_superb/asr1`
2. execute `run_multi.sh` with specific arguments, e.g., `run.sh --duration 10min --only_lid false --lid false `

Training processing is fine, but after training has been done. The inference process would encounter the following error.

**Error logs**
Paste the error logs. If applicable, add screenshots to help explain your problem.

```
File "/home/my_id/miniconda3/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/my_id/miniconda3/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/md2/my_id/tools/espnet/espnet2/bin/asr_inference.py", line 968, in <module>
    main()
  File "/mnt/md2/my_id/tools/espnet/espnet2/bin/asr_inference.py", line 964, in main
    inference(**kwargs)
  File "/mnt/md2/my_id/tools/espnet/espnet2/bin/asr_inference.py", line 684, in inference
    for keys, batch in loader:
  File "/home/my_id/miniconda3/envs/espnet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/my_id/miniconda3/envs/espnet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
File "/home/my_id/miniconda3/envs/espnet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/my_id/miniconda3/envs/espnet/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
soundfile.LibsndfileError: <exception str() failed>
\# Accounting: time=7041 threads=1
\# Ended (code 1) at Sun Jun  4 11:19:11 UTC 2023, elapsed time 7041 seconds
```

**Comment by sw005320** [comment]
Thanks for your report.
@ftshijt, can you check this?

**Comment by ftshijt** [comment]
Many thanks for sharing the info! I actually also got similar issues from collaborators today. 

The major issue is from the empty wav file named as `swc_eng_001553.wav` in the dev set. It is supposed to be filtered by ESPnet during the stage 4 (remove long short utterances) and will not be used in the following inference.

However, a moment back, a modification over https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/asr1/asr.sh#L1509-L1511 ask the inference to directly conducted over the original data, which cause the issue.

A user-level fix for now is set https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/asr1/asr.sh#L1512 from including the `org/${valid_set}` to include ${valid_set}. 

As the organizer, I will mannually remove the file in the ML-SUPERB public release since it is not used anyway.

Thanks for the report.

**Comment by ftshijt** [comment]
I uploaded a newer version of dataset to https://drive.google.com/file/d/1zslKQwadZaYWXAmfBCvlos9BVQ9k6PHT/view?usp=sharing which remove the corrupted files.

**Comment by freddy5566** [comment]
Hello @ftshijt,

Thank you for your quick update. I encountered another error while pre-processing the sixth edition data set.

```
2023-06-06T08:11:44 (data.sh:50:main) stage2: Preparing data for multilingual SUPERB
Traceback (most recent call last):
  File "local/data_prep.py", line 251, in <module>
  train_transcript = open(
  NotADirectoryError: [Errno 20] Not a directory: '/path_to_sixth_edition/swc/.DS_Store/transcript_10min_train.txt'
```

**Comment by ftshijt** [comment]
Thanks for the note! It must be from the issue of MacOS, I will update the version soon!

**Comment by ftshijt** [comment]
I've updated a new version that removes  `.DS_Store` and also checked to process from scratch which seem to work for me. Please feel free to let me know if you continue find any issues with the dataset . Many thanks!

**Comment by ftshijt** [comment]
It shall be with the same link

**Comment by freddy5566** [comment]
Thank you for your update! The error was resolved.

**Comment by ftshijt** [comment]
Sounds great! Thank you again for telling us the issue
