### ISSUE TITLE
decoding error AttributeError: 'NoneType' object has no attribute 'log_softmax'

### ISSUE THREAD

**Issue by vivektyagiibm** [espnet/espnet#5296]
**Describe the bug**
I\m training a seq2seq transformer model in librispeech_100 egs2 dir. 
I ahve set ctc_weight =0.0 to disable ctc in model training and I expect that to hold for decoding too. 

However when I reacjh stage 12 i.e decoding I get the followoing error which seemed to be linked to ctc decoding. 

here's conf/train_asr.yaml 
# Trained with A40 (48 GB) x 1 GPUs.
encoder: e_branchformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    attention_layer_type: rel_selfattn
    pos_enc_layer_type: rel_pos
    rel_pos_type: latest
    cgmlp_linear_units: 1024
    cgmlp_conv_kernel: 31
    use_linear_after_conv: false
    gate_activation: identity
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    layer_drop_rate: 0.0
    linear_units: 1024
    positionwise_layer_type: linear
    use_ffn: true
    macaron_ffn: true
    merge_conv_kernel: 31

decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1
    layer_drop_rate: 0.0

model_conf:
    ctc_weight: 0.0
    lsm_weight: 0.1
    length_normalized_loss: false
frontend_conf:
    n_fft: 512
    win_length: 400
    hop_length: 160

seed: 2022
num_workers: 4
batch_type: numel
batch_bins: 4000000
accum_grad: 4
max_epoch: 25
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10
use_amp: true

optim: adam
optim_conf:
    lr: 0.002
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 15000

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
              apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 5
                              

2023-07-12 05:13:54,305 (asr_inference:325) INFO: Decoding device=cuda, dtype=float32
2023-07-12 05:13:54,379 (asr_inference:354) INFO: Text tokenizer: CharTokenizer(space_symbol="<space>"non_linguistic_symbols="set()"nonsplit_symbols="set()")
2023-07-12 05:13:54,538 (asr:471) INFO: Optional Data Names: ('text_spk2', 'text_spk3', 'text_spk4')
2023-07-12 05:13:54,768 (asr_inference:403) INFO: speech length: 74400
/home/vivek/espnet/tools/venv/lib/python3.10/site-packages/torch/functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:862.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
2023-07-12 05:13:56,000 (beam_search:377) INFO: decoder input length: 115
2023-07-12 05:13:56,000 (beam_search:378) INFO: max output length: 115
2023-07-12 05:13:56,000 (beam_search:379) INFO: min output length: 0
Traceback (most recent call last):
  File "/home/vivek/anaconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/vivek/anaconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/vivek/espnet/espnet2/bin/asr_inference.py", line 968, in <module>
    main()
  File "/home/vivek/espnet/espnet2/bin/asr_inference.py", line 964, in main
    inference(**kwargs)
  File "/home/vivek/espnet/espnet2/bin/asr_inference.py", line 693, in inference
    results = speech2text(**batch)
  File "/home/vivek/espnet/tools/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/vivek/espnet/espnet2/bin/asr_inference.py", line 441, in __call__
    results = self._decode_single_sample(enc[0])
  File "/home/vivek/espnet/espnet2/bin/asr_inference.py", line 508, in _decode_single_sample
    nbest_hyps = self.beam_search(
  File "/home/vivek/espnet/tools/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/vivek/espnet/espnet/nets/beam_search.py", line 382, in forward
    running_hyps = self.init_hyp(x)
  File "/home/vivek/espnet/espnet/nets/batch_beam_search.py", line 125, in init_hyp
    init_states[k] = d.batch_init_state(x)
  File "/home/vivek/espnet/espnet/nets/scorers/ctc.py", line 96, in batch_init_state
    logp = self.ctc.log_softmax(x.unsqueeze(0))  # assuming batch_size = 1
AttributeError: 'NoneType' object has no attribute 'log_softmax'
# Accounting: time=7 threads=1
# Ended (code 1) at Wed Jul 12 05:13:57 IST 2023, elapsed time 7 seconds

**Basic environments:**
 - OS information: [e.g., Linux 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64]
 - python version: [e.g. 3.7.3 (default, Mar 27 2019, 22:11:17) [GCC 7.3.0]]
 - espnet version: [e.g. espnet 0.8.0]
 - Git hash [e.g. b88e89fc7246fed4c2842b55baba884fe1b4ecc2]
   - Commit date [e.g. Tue Sep 1 09:32:54 2020 -0400]
 - pytorch version [e.g. pytorch 1.4.0]

You can obtain them by the following command
```
cd <espnet-root>/tools
. ./activate_python.sh

echo "- OS information: `uname -mrsv`"
python3 << EOF
import sys, espnet, torch
pyversion = sys.version.replace('\n', ' ')
print(f"""- python version: \`{pyversion}\`
- espnet version: \`espnet {espnet.__version__}\`
- pytorch version: \`pytorch {torch.__version__}\`""")
EOF
cat << EOF
- Git hash: \`$(git rev-parse HEAD)\`
  - Commit date: \`$(git log -1 --format='%cd')\`
EOF
```

**Environments from `torch.utils.collect_env`:**
e.g.,
```
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: CentOS Linux release 7.5.1804 (Core)
GCC version: (GCC) 7.2.0
CMake version: version 2.8.12.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: TITAN RTX
GPU 1: TITAN RTX
GPU 2: TITAN RTX
GPU 3: TITAN RTX

Nvidia driver version: 440.33.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.0
[pip3] torch==1.4.0
[pip3] torch-complex==0.1.1
[pip3] torch-optimizer==0.0.1a14
[pip3] torchaudio==0.4.0
[pip3] warprnnt-pytorch==0.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.1                      217
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.1.0            py37h23d657b_0
[conda] mkl_random                1.1.1            py37h0573a6f_0
[conda] pytorch                   1.4.0           py3.7_cuda10.0.130_cudnn7.6.3_0    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.0                    pypi_0    pypi
[conda] torch-complex             0.1.1                    pypi_0    pypi
[conda] torch-optimizer           0.0.1a14                 pypi_0    pypi
[conda] torchaudio                0.4.0                    pypi_0    pypi
[conda] warprnnt-pytorch          0.1                      pypi_0    pypi
```
You can obtain them by the following command

```
cd <espnet-root>/tools
. ./activate_python.sh
python3 -m torch.utils.collect_env
```

**Task information:**
 - Task: [e.g., ASR, TTS, ST, ENH]
 - Recipe: [e.g. librispeech]
 - ESPnet1 or ESPnet2

**To Reproduce**
1. move to a recipe directory, e.g., `cd egs/librispeech/asr1`
2. execute `run.sh` with specific arguments, e.g., `run.sh --stage 3 --ngp 1`
3. specify the error log, e.g., `exp/xxx/yyy.log`

**Error logs**
Paste the error logs. If applicable, add screenshots to help explain your problem.

**Comment by sw005320** [comment]
Can you paste the decoding config?
When you use pure attention, you also have to set `ctc_weight: 1.0` in the decoding config.
Also, `maxlenratio` and `minlenratio` should be set appropriately (e.g., 0.5 and 0.1)

**Comment by vivektyagiibm** [comment]
Dear Prof. Shinji Watanabe, 

Thank you for prompt reply and you are right and I saw from the long stdout that a separate conf/decode_asr.yaml  arg is also being passed to the decoder. I was under the impression that that conf/train_asr.yaml setting will apply as we are running  a common ./run.sh script. Please mention this important point in the espnet documentation. 

So I had updated the decoder-asr.yaml and set the ctc_weight=0.0 as follows, 
cat conf/decode_asr.yaml 
beam_size: 20
ctc_weight: 0.0
lm_weight: 0.0
maxlenratio: 0.0
minlenratio: 0.0
penalty: 0.0


However the decoder is outputting same transcript for all the test files, which indicates that some thing further is wrong. I trained just on librispeech_100 and so I don't expect the CER to be very low but in this case  the CER may be 100% or even higher due to insertions/deletions. 


Also the lm_weight=0.0 in my decode.yaml . maxlenratio and minlenratio are by default 0.0 in the decode.yaml. I will try changing them as you suggested but probably they control insertions and deletions and are likely not causing the issue that similar transcript is being outputted for each wav file as below. 

 venv) (base) vivek@vivek-deeplearning:~/espnet/egs2/librispeech_100/asr1$ head -10 exp/asr_train_asr_raw_en_char_sp/decode_asr_asr_model_valid.acc.ave/test_clean/logdir/output.1/1best_recog/text
1089-134686-0000 AND THERE WAS NO LONGER THAN THE OLD MAN WHO HAD BEEN COMPLETELY CONSIDERED THAT HE WOULD NOT HAVE BEEN DONE
1089-134686-0001 AND THERE WAS NO LONGER THAN THE OTHER
1089-134686-0002 AND THERE WAS NO LONGER THAN THE OLD MAN WHO HAD BEEN COMPLETELY CONSIDERED
1089-134686-0003 AND THERE WAS NO ONE OF THEM
1089-134686-0004 AND THERE WAS NO LONGER THAN THE OTHER SIDE OF THE WORLD
1089-134686-0005 AND THERE WAS NO LONGER THAN THE OLD MAN WHO HAD BEEN COMPLETELY CONSIDERED THAT THERE WAS NO LONGER
1089-134686-0006 AND THERE WAS NO LONGER THAN THE OLD MAN WHO HAD BEEN COMPLETELY CONSIDERED THAT HE HAD SEEN HIMSELF
1089-134686-0007 AND THERE WAS NO LONGER THAN ANY ONE OF THEM
1089-134686-0008 AND THERE WAS NO LONGER THAN THE OLD MAN WHO HAD BEEN COMPLETELY CONSIDERED
1089-134686-0009 AND THERE WAS NO LONGER THAN THE OLD MAN WHO HAD BEEN COMPLETELY CONSIDERED THAT HE HAD SEEN HIMSELF


I trained for 25 epoch and I had set ctc_weight =0.0 in the train_config.yaml and I also set the token type to char in asr.sh and still the character accuracy on train set is at most 60% i.e acc= 0.60, which also seems low as this is perhaps computed on the train set. 
venv) (base) vivek@vivek-deeplearning:~/espnet/egs2/librispeech_100/asr1$ tail  exp/asr_train_asr_raw_en_char_sp/train.log
[vivek-deeplearning] 2023-07-12 05:09:37,203 (trainer:732) INFO: 25epoch:train:3707-3924batch: iter_time=9.195e-04, forward_time=0.140, loss_att=41.611, acc=0.629, loss=41.611, backward_time=0.154, grad_norm=19.141, clip=100.000, loss_scale=5.369e+08, optim_step_time=0.022, optim0_lr0=0.001, train_time=1.571
[vivek-deeplearning] 2023-07-12 05:11:02,608 (trainer:732) INFO: 25epoch:train:3925-4142batch: iter_time=9.500e-04, forward_time=0.140, loss_att=44.580, acc=0.632, loss=44.580, backward_time=0.155, grad_norm=19.326, clip=100.000, loss_scale=5.369e+08, optim_step_time=0.022, optim0_lr0=0.001, train_time=1.568
[vivek-deeplearning] 2023-07-12 05:12:28,137 (trainer:732) INFO: 25epoch:train:4143-4360batch: iter_time=9.046e-04, forward_time=0.140, loss_att=43.420, acc=0.629, loss=43.420, backward_time=0.154, grad_norm=18.814, clip=100.000, loss_scale=5.369e+08, optim_step_time=0.022, optim0_lr0=0.001, train_time=1.568
[vivek-deeplearning] 2023-07-12 05:13:38,363 (trainer:338) INFO: 25epoch results: [train] iter_time=6.576e-04, forward_time=0.140, loss_att=43.926, acc=0.630, loss=43.926, backward_time=0.154, grad_norm=19.238, clip=100.000, loss_scale=5.369e+08, optim_step_time=0.023, optim0_lr0=0.001, train_time=1.568, time=28 minutes and 35.87 seconds, total_count=109400, gpu_max_cached_mem_GB=10.189, [valid] loss_att=101.971, acc=0.609, cer=0.530, wer=0.942, loss=101.971, time=29.42 seconds, total_count=3800, gpu_max_cached_mem_GB=10.189, [att_plot] time=34.26 seconds, total_count=0, gpu_max_cached_mem_GB=10.189
[vivek-deeplearning] 2023-07-12 05:13:40,593 (trainer:386) INFO: The best model has been updated: valid.acc
[vivek-deeplearning] 2023-07-12 05:13:40,607 (trainer:440) INFO: The model files were removed: exp/asr_train_asr_raw_en_char_sp/15epoch.pth
[vivek-deeplearning] 2023-07-12 05:13:40,607 (trainer:458) INFO: The training was finished at 25 epochs 
[vivek-deeplearning] 2023-07-12 05:13:40,645 (average_nbest_models:69) INFO: Averaging 10best models: criterion="valid.acc": exp/asr_train_asr_raw_en_char_sp/valid.acc.ave_10best.pth
# Accounting: time=17839 threads=1
# Ended (code 0) at Wed Jul 12 05:13:44 IST 2023, elapsed time 17839 seconds

in asr.sh, I had set
# Tokenization related
#token_type=bpe      # Tokenization type (char or bpe).
token_type=char      # Tokenization type (char or bpe).
nbpe=30             # The number of BPE vocabulary.
bpemode=unigram     # Mode of BPE (unigram or bpe).
oov="<unk>"         # Out of vocabulary symbol.
blank="<blank>"     # CTC blank symbol
sos_eos="<sos/eos>" # sos and eos symbole



Finally I have request for the future design of espnet2/egs2 

As you are now doing feature extraction from either librosa and not dependent on kaldi, why not even get rid of kaldi's data set structure which is very complex and confusing. For examples we don't need arks, or speaker level stats or speaker level files organization as that was required for speaker adaptation in the HMM-GMM (Kaldi) systems but end2end asr system trains on each wav file independently irrespective of whether it's spoke by the a particular speaker or not. 

This will simplify the ./run.sh and ./asr.sh scripts a lot and you will not need your users to install kaldi which creates a very complex experimental dir structure and superfluous arguments to be passed such as speaker level stats, speaker level .scp file etc. 

Kind regards
Vivek

**Comment by sw005320** [comment]
I think your training failed. The decoder network was over-trained, and it does care about audio features.
It's working as a language model.
Please revisit your training.

Also, thanks for your input.
The data format reconsideration is one of the TODOs.

**Comment by StressMMb** [comment]
did you solve the problem? i also met the same problem :(
can you share your solution?
THANKS!!!
