### ISSUE TITLE
"Issues encountered when reproducing https://github.com/espnet/espnet/tree/master/egs2/how2_2000h/sum1 ↗"

### ISSUE THREAD

**Issue by qipotianMFXT** [espnet/espnet#5305]
Excuse me, according to the information displayed on espnet's official docker hub, espnet depends on **Pytorch 1.13.1 and cuda11.7.1.**
However, after I configured the relevant deep learning environment, when executing to the 11th stage of data preprocessing, there will be the following error information: 
**OSError: libcudart.so.10.0: cannot open shared object file**: No such file or directory# Accounting: time=13 threads=1# Ended (code 1) at Sat Jul 15 02:56:28 CST 2023, elapsed time 13 seconds
According to the source code information of install_longformer, **longformer requires PyTorch version 1.8 or higher**, which is incompatible with cuda10.0. Why does it need libcudart.so.10.0? And when I try to **conda install cudatoolkit=10.0, a tvm error occurs**:
tvm._ffi.base.TVMError: Traceback (most recent call last):
[bt] (1) /root/autodl-tmp/conda/envs/espnet/lib/python3.9/site-packages/tvm/libtvm_runtime.so(TVMFuncCall+0x61) [0x7fd533c3a681]
[bt] (0) /root/autodl-tmp/conda/envs/espnet/lib/python3.9/site-packages/tvm/libtvm_runtime.so(+0x5cfdc) [0x7fd533c5cfdc]
File "/code/tvm/src/runtime/module_util.cc", line 73
TVMError: Check failed: ret == 0 (-1 vs. 0) : Assert fail: ((((1 == int32(arg2.strides[3])) && (t3d3 == int32(arg2.strides[2]))) && ((t3d3*h) == int32(arg2.strides[1]))) && (((t3d3*h)*n) == int32(arg2.strides[0]))), arg2.strides: expected to be compact arrayLoading tvm binary from: /root/autodl-tmp/conda/envs/espnet/lib/python3.9/site-packages/longformer/../longformer/lib/lib_diagonaled_mm_float32_cuda.so # Accounting: time=11 threads=1# Ended (code 1) at Sat Jul 15 16:43:34 CST 2023, elapsed time 11 seconds
So **it seems that the deep learning environments depended by espnet and longformer are conflicting**. How did you make them compatible?

**Comment by sw005320** [comment]
Thanks for the report.
I added @Fhrozen and @roshansh-cmu for this issue.
@Fhrozen and @roshansh-cmu, do you have any ideas to fix this issue?

**Comment by Fhrozen** [comment]
You can build your own container using `./build.sh --build-ver gpu --th_ver <torch> --cuda_ver <cuda> local`
I would like to know if you tested outside the container and that the container is having issues with longformer.
However, I am not sure why is asking for cudart.10 if the container was built using 11.7:
`NV_CUDA_CUDART_DEV_VERSION 11.7.99-1`
Are you using the latest container? I will try to check this later in my terminal.

**Comment by qipotianMFXT** [comment]
Yes, I'm using the latest espnet docker, I think the problem may lie with longformer.I also tried not using Docker and manually configuring the environment following the official website's tutorial, here are the steps I took:

(base)root@autodl-container-fac242a21a-94239247:~/autodl-tmp/espnet/tools# ./setup_anaconda.sh /root/autodl-tmp/off_env/ esp 3.8

(base) root@autodl-container-fac242a21a-94239247:~/autodl-tmp/espnet/tools# conda activate esp 

(esp) root@autodl-container-fac242a21a-94239247:~/autodl-tmp/espnet/tools# make TH_VERSION=1.10.1 CUDA_VERSION=11.3

(esp) root@autodl-container-fac242a21a-94239247:~/autodl-tmp/espnet/tools# bash -c ". activate_python.sh; ./installers/install_longformer.sh"

(esp)root@autodl-container-fac242a21a-94239247:~/autodl-tmp/espnet/egs2/how2_2000h/sum1# ./run.sh --local_data_opts "--data_url <link>"

These steps would result in the following error:
[autodl-container-fac242a21a-94239247] 2023-07-17 10:51:57,344 (trainer:284) INFO: 1/100epoch started
Traceback (most recent call last):
  File "/root/autodl-tmp/conda/envs/esp/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/autodl-tmp/conda/envs/esp/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/autodl-tmp/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/root/autodl-tmp/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/root/autodl-tmp/espnet/espnet2/tasks/abs_task.py", line 1056, in main
    cls.main_worker(args)
  File "/root/autodl-tmp/espnet/espnet2/tasks/abs_task.py", line 1365, in main_worker
    cls.trainer.run(
  File "/root/autodl-tmp/espnet/espnet2/train/trainer.py", line 290, in run
    all_steps_are_invalid = cls.train_one_epoch(
  File "/root/autodl-tmp/espnet/espnet2/train/trainer.py", line 567, in train_one_epoch
    retval = model(**batch)
  File "/root/autodl-tmp/conda/envs/esp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/espnet/espnet2/asr/espnet_model.py", line 237, in forward
    encoder_out, encoder_out_lens = self.encode(speech, speech_lengths)
  File "/root/autodl-tmp/espnet/espnet2/asr/espnet_model.py", line 400, in encode
    encoder_out, encoder_out_lens, _ = self.encoder(feats, feats_lengths)
  File "/root/autodl-tmp/conda/envs/esp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/espnet/espnet2/asr/encoder/longformer_encoder.py", line 345, in forward
    xs_pad, masks = self.encoders(xs_pad, masks)
  File "/root/autodl-tmp/conda/envs/esp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/espnet/espnet/nets/pytorch_backend/transformer/repeat.py", line 30, in forward
    args = m(*args)
  File "/root/autodl-tmp/conda/envs/esp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/espnet/espnet/nets/pytorch_backend/conformer/encoder_layer.py", line 141, in forward
    x_att = self.self_attn(x_q, x, x, mask)
  File "/root/autodl-tmp/conda/envs/esp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/espnet/espnet/nets/pytorch_backend/transformer/longformer_attention.py", line 49, in forward
    output, self.attention = self.attention_layer(
  File "/root/autodl-tmp/conda/envs/esp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/conda/envs/esp/lib/python3.8/site-packages/longformer/longformer.py", line 149, in forward
    attn_weights = diagonaled_mm_tvm(q, k, self.attention_window, self.attention_dilation, False, 0, False)
  File "/root/autodl-tmp/conda/envs/esp/lib/python3.8/site-packages/longformer/diagonaled_mm_tvm.py", line 261, in forward
    output = DiagonaledMM._diagonaled_mm(t1, t2, w, d, is_t1_diagonaled=is_t1_diagonaled, padding=padding, autoregressive=autoregressive)
  File "/root/autodl-tmp/conda/envs/esp/lib/python3.8/site-packages/longformer/diagonaled_mm_tvm.py", line 191, in _diagonaled_mm
    _diagonaled_mm_function = DiagonaledMM._get_function(dtype=dtype, device=device)
  File "/root/autodl-tmp/conda/envs/esp/lib/python3.8/site-packages/longformer/diagonaled_mm_tvm.py", line 143, in _get_function
    diagonaled_mm = DiagonaledMM._load_compiled_function(dtype, device)  # try to load from disk
  File "/root/autodl-tmp/conda/envs/esp/lib/python3.8/site-packages/longformer/diagonaled_mm_tvm.py", line 126, in _load_compiled_function
    from tvm.module import load  # this can be the small runtime python library, and doesn't need to be the whole thing
  File "/root/autodl-tmp/conda/envs/esp/lib/python3.8/site-packages/tvm/module.py", line 23, in <module>
    from ._ffi.function import ModuleBase, _set_class_module
  File "/root/autodl-tmp/conda/envs/esp/lib/python3.8/site-packages/tvm/_ffi/function.py", line 24, in <module>
    from .base import _LIB, check_call, py_str, c_str, string_types, _FFI_MODE
  File "/root/autodl-tmp/conda/envs/esp/lib/python3.8/site-packages/tvm/_ffi/base.py", line 60, in <module>
    _LIB, _LIB_NAME = _load_lib()
  File "/root/autodl-tmp/conda/envs/esp/lib/python3.8/site-packages/tvm/_ffi/base.py", line 52, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/root/autodl-tmp/conda/envs/esp/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.10.0: cannot open shared object file: No such file or directory
\#Accounting: time=13 threads=1
\# Ended (code 1) at Mon Jul 17 10:52:00 CST 2023, elapsed time 13 seconds

**Comment by roshansh-cmu** [comment]
The Longformer TVM kernel was built with Cuda 10.0 and currently, it works only with Cuda 10.0. 

There is an option to build this TVM kernel with other versions of Cuda - instructions are here : https://github.com/allenai/longformer/blob/master/scripts/cheatsheet.txt

We may revisit compatibility with later versions of Cuda in a bit - but this could help you get started. We would appreciate any contributions of TVM kernels if you manage to compile it for later Cuda builds. 

Thanks !

**Comment by qipotianMFXT** [comment]
> The Longformer TVM kernel was built with Cuda 10.0 and currently, it works only with Cuda 10.0.
> 
> There is an option to build this TVM kernel with other versions of Cuda - instructions are here : https://github.com/allenai/longformer/blob/master/scripts/cheatsheet.txt
> 
> We may revisit compatibility with later versions of Cuda in a bit - but this could help you get started. We would appreciate any contributions of TVM kernels if you manage to compile it for later Cuda builds.
> 
> Thanks !

Thank you so much for your answer. Could I ask another question, how much GPU memory is required to run the entire sum1 code if ngpu is set to 1? Based on my own trials, it seems that a 32GB GPU is not enough, so I'm wondering if you used a GPU with a higher memory capacity or used a multi-GPU mode.

**Comment by roshansh-cmu** [comment]
Soon, we will merge a PR for FNet Support in ESPNet - we recommend using FNet post that time.

**Comment by qipotianMFXT** [comment]
> Soon, we will merge a PR for FNet Support in ESPNet - we recommend using FNet post that time.

Excuse me, is the addition of FNet intended to address the issue of CUDA out-of-memory error during CUDA runtime?

**Comment by qipotianMFXT** [comment]
> 很快，我们将在 ESPNet 中合并 FNet 支持的 PR - 我们建议届时使用 FNet 帖子。

I used V100 GPU with 32GB of memory. Unfortunately,the 'CUDA out of memory' error also occured.Can using FNet alleviate GPU memory consumption to some extent?

**Comment by roshansh-cmu** [comment]
Yes, that is right.

**Comment by qipotianMFXT** [comment]
> Yes, that is right.

Excuse me,will the updated code be placed in the 'sum2' and 'asr2' directories under 'how2_2000h'? Currently, in the 'espnet/blob/master/egs2/how2_2000h/sum1' link, only 'score.sh' and 'path.sh' have been recently updated, and it appears that Fnet cannot be directly used through the 'sum1' directory.

**Comment by qipotianMFXT** [comment]
> 对就这样。

Hello, currently I have only found the branches for sum2 and asr2, but the process and steps to reproduce the code haven't been updated yet. Could you please update the readme.md for these two projects as soon as possible?

**Comment by smilepokemmo** [comment]
@qipotianMFXT Hello, thank you for your work! May I ask if you still have a backup of the How2_2000h dataset? The official sources no longer provide this dataset and suggest obtaining it from other downloaders. Unfortunately, the dataset I downloaded earlier is missing some files - specifically, I may be missing cv05utt, cv05_sum, utt2spk, and spk2utt. Additionally, could you provide the complete dataset structure? This will help me further confirm which parts are missing.
