### ISSUE TITLE
Help! Installation issue

### ISSUE THREAD

**Issue by baixf-xyz** [espnet/espnet#5432]
**Describe the issue**
I use conda environment with python 3.8 TH_VERSION=1.12.1 CUDA_VERSION=11.3 to install it

**Error logs**

(espnet) :~/espnet/tools$ make TH_VERSION=1.12.1 CUDA_VERSION=11.3
CUDA_VERSION=11.3
PYTHON=/home/yhl522/miniconda3/envs/espnet/bin/python3
PYTHON_VERSION=Python 3.8.18
USE_CONDA=1
TH_VERSION=1.12.1
WITH_OMP=ON
NUMPY_VERSION=1.24.3
. ./activate_python.sh && python3 -m pip install -e "..[train, recipe]"  # Install editable mode by default
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Obtaining file:///s6home/yhl522/espnet
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      WARNING: The repository located at mirrors.aliyun.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.aliyun.com'.
      ERROR: Could not find a version that satisfies the requirement pytest-runner (from versions: none)
      ERROR: No matching distribution found for pytest-runner
      /home/yhl522/miniconda3/envs/espnet/lib/python3.8/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        File "/home/yhl522/miniconda3/envs/espnet/lib/python3.8/site-packages/setuptools/installer.py", line 96, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "/home/yhl522/miniconda3/envs/espnet/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/home/yhl522/miniconda3/envs/espnet/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpifliwnyb', '--quiet', 'pytest-runner']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/s6home/yhl522/espnet/setup.py", line 134, in <module>
          setup(
        File "/home/yhl522/miniconda3/envs/espnet/lib/python3.8/site-packages/setuptools/__init__.py", line 106, in setup
          _install_setup_requires(attrs)
        File "/home/yhl522/miniconda3/envs/espnet/lib/python3.8/site-packages/setuptools/__init__.py", line 79, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/home/yhl522/miniconda3/envs/espnet/lib/python3.8/site-packages/setuptools/__init__.py", line 84, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/home/yhl522/miniconda3/envs/espnet/lib/python3.8/site-packages/setuptools/dist.py", line 907, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/home/yhl522/miniconda3/envs/espnet/lib/python3.8/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/home/yhl522/miniconda3/envs/espnet/lib/python3.8/site-packages/pkg_resources/__init__.py", line 829, in resolve
          dist = self._resolve_dist(
        File "/home/yhl522/miniconda3/envs/espnet/lib/python3.8/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/home/yhl522/miniconda3/envs/espnet/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1135, in best_match
          return self.obtain(req, installer)
        File "/home/yhl522/miniconda3/envs/espnet/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1147, in obtain
          return installer(requirement)
        File "/home/yhl522/miniconda3/envs/espnet/lib/python3.8/site-packages/setuptools/installer.py", line 98, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/home/yhl522/miniconda3/envs/espnet/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpifliwnyb', '--quiet', 'pytest-runner']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
make: *** [Makefile:113: espnet.done] Error 1

**Comment by baixf-xyz** [comment]
I have solved the problems with the command
```
pip install pytest-runner

```

**Comment by sw005320** [comment]
Thanks for the report!
