### ISSUE TITLE
OS error while installation

### ISSUE THREAD

**Issue by Naramkeshav59** [espnet/espnet#5471]
Hello,
I have installed espnet toolkit as mentioned in the documentation and created a new recipe to perform self-supervised learning representations task. But, I am not sure why I'm always getting this error. 
```bash
/data/anaconda3/envs/Kespnet/etc/conda/activate.d/libblas_mkl_activate.sh: line 1: MKL_INTERFACE_LAYER: unbound variable
```
I'm sure that I have used correct CUDA_VERSION while installing.  After this happened I have freshly installed espnet and was getting another error
```bash
OSError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory
make: *** [Makefile:252: check_install] Error 1
```

**More information regarding the above**:

** `check_install.py` status by using the following command**
```
cd <espnet-root>/tools
. ./activate_python.sh; python3 check_install.py
```
```bash
(Kespnet) iitdh-ms@iitd:/data/Sougata/Btech_intern/espnet/tools$ . ./activate_python.sh; python3 check_install.py
[x] python=3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:49:32)  [GCC 12.3.0]

Python modules:
[x] torch=1.12.1.post201
[x] torch cuda=11.2
[x] torch cudnn=8401
[x] torch nccl
[x] chainer=6.0.0
[ ] chainer cuda
[ ] chainer cudnn
[ ] cupy
Traceback (most recent call last):
  File "/data/Sougata/Btech_intern/espnet/tools/check_install.py", line 197, in <module>
    main()
  File "/data/Sougata/Btech_intern/espnet/tools/check_install.py", line 129, in main
    m = importlib.import_module(name)
  File "/data/anaconda3/envs/Kespnet/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/data/anaconda3/envs/Kespnet/lib/python3.9/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/data/anaconda3/envs/Kespnet/lib/python3.9/site-packages/torchaudio/_extension.py", line 103, in <module>
    _init_extension()
  File "/data/anaconda3/envs/Kespnet/lib/python3.9/site-packages/torchaudio/_extension.py", line 88, in _init_extension
    _load_lib("libtorchaudio")
  File "/data/anaconda3/envs/Kespnet/lib/python3.9/site-packages/torchaudio/_extension.py", line 51, in _load_lib
    torch.ops.load_library(path)
  File "/data/anaconda3/envs/Kespnet/lib/python3.9/site-packages/torch/_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "/data/anaconda3/envs/Kespnet/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory
```
**Basic environments:**
 - OS information: Linux 5.11.0-46-generic #51~20.04.1-Ubuntu SMP Fri Jan 7 06:51:40 UTC 2022 x86_64
- python version: \`3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:49:32)  [GCC 12.3.0]\`
- espnet version: \`espnet 202308\`
- pytorch version: \`pytorch 1.12.1.post201\`
 - Git hash `d2f7234b2a759de62968609e89aa420c13d757d3`

**Environments from `torch.utils.collect_env`:**
```
Collecting environment information...
PyTorch version: 1.12.1.post201
Is debug build: False
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.27.2
Libc version: glibc-2.31bash

Python version: 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:49:32)  [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.11.0-46-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration:
GPU 0: Quadro RTX 6000
GPU 1: Quadro RTX 6000
GPU 2: NVIDIA GeForce RTX 2080 Ti
GPU 3: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 510.39.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.12.1.post201
[pip3] torch-complex==0.4.3
[pip3] torch-optimizer==0.3.0
[pip3] torchaudio==0.12.1
[conda] cudatoolkit               11.6.2              hfc3e2af_12    conda-forge
[conda] magma                     2.5.4                hc72dce7_4    conda-forge
[conda] mkl                       2022.1.0           hc2b9512_224
[conda] numpy                     1.23.5           py39h3d75532_0    conda-forge
[conda] pytorch                   1.12.1          cuda112py39hb0b7ed5_201    conda-forge
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.1                    pypi_0    pypi
[conda] torch-complex             0.4.3                    pypi_0    pypi
[conda] torch-optimizer           0.3.0                    pypi_0    pypi
[conda] torchaudio                0.12.1               py39_cu116    pytorch
```
**To Reproduce**
Steps to reproduce the behavior by showing us the specific installation commands with their arguments, e.g.,
```
git clone https://github.com/espnet/espnet
cd <espnet-root>/tools
./setup_anaconda.sh ${CONDA_ROOT}  Kespnet 3.9
make TH_VERSION=1.12.1 CUDA_VERSION=11.6
```

**Comment by Naramkeshav59** [comment]
@sw005320 sir, can you please guide me on what to do?

**Comment by kamo-naoyuki** [comment]
@mukherjeesougata @Naramkeshav59  Are you sharing a same conda, `/data/anaconda3`?

Basically, I recommend you preparing a new conda,  I mean creating a conda under `espnet/tools` instead of using  `/data/anaconda3`. 

To be precise, if you create a environment in `/data/anaconda3`, the environment inherits the packages from the `root` env of `/data/anaconda3` but we can't control them because they are unexpected for us.

 We are not experts of conda and I think we can't solve your issues directly.

**Comment by mukherjeesougata** [comment]
I have resolved ```/data/anaconda3/envs/Kespnet/etc/conda/activate.d/libblas_mkl_activate.sh: line 1: MKL_INTERFACE_LAYER: unbound variable``` using [this](https://github.com/espnet/espnet/issues/5473#issuecomment-1759501695). I don't how to resolve the other error, it seems to be an installation error.

**Comment by juice500ml** [comment]
More stable way to fix the libblas issue is not interchanging the lines, but slightly modifying it: https://github.com/conda-forge/blas-feedstock/commit/64c7360fec35520751cb8f268669b670ff804012
Not sure, but the above implies that it might be solved using more recent version of libblas.

**Comment by juice500ml** [comment]
Also, `CUDA used to build PyTorch: 11.2` but you used `CUDA_VERSION=11.6`. There's a possiblity that unifying the version (ex. setting as CUDA_VERSION=11.2) should resolve the issue.
