### ISSUE TITLE
ASR DECODING: maxlenratio & minlenratio

### ISSUE THREAD

**Issue by david-gimeno** [espnet/espnet#5534]
Once my ASR model is trained, I run the `espnet2/bin/asr_inference.py` script for decoding. However, I am a bit confused about these warning that I getting quite oftenly:

```WARNING:root:decoding may be stopped by the max output length limitation, please consider to increase the maxlenratio```

Based on the code found in `espnet/nets/beam_search.py` I can figure out what the purpose of these factors is.
```
if maxlenratio == 0:
    maxlen = inp.shape[0]
elif maxlenratio < 0:
    maxlen = -1 * int(maxlenratio)
else:
    maxlen = max(1, int(maxlenratio * inp.size(0)))
```
 **However, when I am defining a `maxlenratio` greater than 1, I am getting an error because the length is greater than the actual lenght of the input**. I do not understand why. Where can I find more information about how to set these factors?

Thanks in advance,

David

**Comment by sw005320** [comment]
Thanks for the report.
Can you tell me the details about the error messages?
`maxlenratio` greater than 1 is widely used (especially for speech translation) and I want to identify the issue.

**Comment by david-gimeno** [comment]
It is true, I forgot to include the error trace!! Please find it here:
```
Traceback (most recent call last):
  File "vsr_main.py", line 230, in <module>
    inference(args.output_dir, speech2text, test_loader, f"test+lm+full-time-masking+maxlenratio1.2")
  File "vsr_main.py", line 78, in inference
    result = speech2text(torch.squeeze(xs_pad, 0))
  File "/home/david/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/david/phd/E2E-SPEECH-RECOGNITION/src/bin/asr_inference.py", line 430, in __call__
    results = self._decode_single_sample(enc[0])
  File "/home/david/phd/E2E-SPEECH-RECOGNITION/src/bin/asr_inference.py", line 474, in _decode_single_sample
    nbest_hyps = self.beam_search(
  File "/home/david/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/david/espnet/espnet/nets/beam_search.py", line 424, in forward
    best = self.search(running_hyps, x, pre_x=pre_x)
  File "/home/david/espnet/espnet/nets/batch_beam_search.py", line 310, in search
    part_scores, part_states = self.score_partial(running_hyps, part_ids, x, pre_x)
  File "/home/david/espnet/espnet/nets/batch_beam_search.py", line 231, in score_partial
    scores[k], states[k] = d.batch_score_partial(
  File "/home/david/espnet/espnet/nets/scorers/ctc.py", line 126, in batch_score_partial
    return self.impl(y, batch_state, ids)
  File "/home/david/espnet/espnet/nets/ctc_prefix_score.py", line 176, in __call__
    torch.cat((log_phi_x[start:end], r[start - 1, 0].unsqueeze(0)), dim=0),
IndexError: index 62 is out of bounds for dimension 0 with size 62
```

**Comment by sw005320** [comment]
Oh, OK.
The issue comes from the CTC scoring, which is not used in speech translation.
One option is to turn off joint CTC/attention scoring.
Please check https://espnet.github.io/espnet/tutorial.html and set `ctc_weight: 0.0`
Also, in this case, please tune `maxlenratio` and `minlenratio` to provide the appropriate hypothesis length.

Curiosity: can you share the inference option?

**Comment by david-gimeno** [comment]
Thanks for sharing that tutorial, it helped me understand how to set the ```maxlenratio``` and ```minlenratio``` in a more proper way depending on whether the hypothesis I am getting suffered from more deletions than insertions, etc. However, it is a pity the fact that I have to discard the CTC paradigm when decoding :(

Regarding the inference option, do you mean the configuration I was using for my experiments? It is as follows:

```
inference_conf:
  maxlenratio: 0.0
  minlenratio: 0.0
  batch_size: 1
  beam_size: 40
  ctc_weight: 0.1
  lm_weight: 0.6
  penalty: 0.5
  nbest: 1
```

**Comment by sw005320** [comment]
The CTC score is mainly used to adjust the length. If we appropriately set the length-related hyper-parameters (it's a bit painful, though), we usually get reasonable performance only with attention.

I'll check it in more detail, but since CTC prefix scores are based on the CTC alignment algorithm (which requires the input length to be longer than the output length), it may not work algorithmically.
Anyway, thanks for sharing it.

@brianyan918, do you encounter the issue when you use CTC in ST?
Do you have some comments about it?
