### ISSUE TITLE
Query regarding whisper.

### ISSUE THREAD

**Issue by Naramkeshav59** [espnet/espnet#5550]
Hello,
Is there any way to use whisper model as frontend ?  As I cannot find whisper in s3prl hub.

**Comment by Naramkeshav59** [comment]
what I have tried as config:
```batch_type: numel
batch_bins: 8000000
accum_grad: 4
max_epoch: 10
patience: none
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 3

encoder: conformer
encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d2
    normalize_before: true
    macaron_style: true
    pos_enc_layer_type: "rel_pos"
    selfattention_layer_type: "rel_selfattn"
    activation_type: "swish"
    use_cnn_module:  true
    cnn_module_kernel: 31
    interctc_layer_idx: [3, 6, 9,]
    interctc_use_conditioning: true

decoder: transformer
decoder_conf:
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    interctc_weight: 0.5
    length_normalized_loss: false
    extract_feats_in_collect_stats: false

optim: adam
optim_conf:
    lr: 0.0002
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2

freeze_param: [
"frontend.upstream"
]

frontend: whisper
frontend_conf:
    whisper_model: "large-v2"  # Note: If the upstream is changed, please change the input_size in the preencoder.
        #path_or_url: /DATA/Sougata/BTech/espnet/egs2/xlsr128minilibrispeech/asr1/large.pt
    download_dir: ./hub
    

preencoder: linear
preencoder_conf:
   input_size: 1024  # Note: If the upstream is changed, please change this value accordingly.
   output_size: 80
```
# !/usr/bin/env bash
# Set bash to 'debug' mode, it will exit on :
# -e 'error', -u 'undefined variable', -o ... 'error in pipeline', -x 'print commands',
set -e
set -u
set -o pipefail

running command
```
CUDA_VISIBLE_DEVICES=0 ./asr.sh \
    --stage 2 \
    --stop_stage 13 \
    --nj 4 \
    --ngpu 1 \
    --gpu_inference true \
    --inference_nj 1 \
    --use_lm false \
    --feats_normalize utt_mvn \
    --audio_format wav \
    --token_type word \
    --asr_config conf/train_asr_conformer_scctc.yaml \
    --inference_args "--beam_size 10 --ctc_weight 0.3" \
    --train_set train_nodev \
    --valid_set train_dev \
    --test_sets "train_dev test" \
    --bpe_train_text "data/train/text" \
#    --lm_train_text "data/train/text" "$@"

```

**Comment by Naramkeshav59** [comment]
```
[Traceback (most recent call last):
  File "/DATA/anaconda3/envs/KeshavEspnet/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/DATA/anaconda3/envs/KeshavEspnet/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/DATA/Sougata/BTech/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/DATA/Sougata/BTech/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/DATA/Sougata/BTech/espnet/espnet2/tasks/abs_task.py", line 1082, in main
    cls.main_worker(args)
  File "/DATA/Sougata/BTech/espnet/espnet2/tasks/abs_task.py", line 1192, in main_worker
    model = cls.build_model(args=args)
  File "/DATA/Sougata/BTech/espnet/espnet2/tasks/asr.py", line 496, in build_model
    frontend = frontend_class(**args.frontend_conf)
TypeError: __init__() got an unexpected keyword argument 'fs'
# Accounting: time=4 threads=1
# Ended (code 1) at Wed Nov 15 18:21:34 IST 2023, elapsed time 4 seconds](url)
```
I was getting this error

**Comment by mukherjeesougata** [comment]
> ```
> [Traceback (most recent call last):
>   File "/DATA/anaconda3/envs/KeshavEspnet/lib/python3.9/runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/DATA/anaconda3/envs/KeshavEspnet/lib/python3.9/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/DATA/Sougata/BTech/espnet/espnet2/bin/asr_train.py", line 23, in <module>
>     main()
>   File "/DATA/Sougata/BTech/espnet/espnet2/bin/asr_train.py", line 19, in main
>     ASRTask.main(cmd=cmd)
>   File "/DATA/Sougata/BTech/espnet/espnet2/tasks/abs_task.py", line 1082, in main
>     cls.main_worker(args)
>   File "/DATA/Sougata/BTech/espnet/espnet2/tasks/abs_task.py", line 1192, in main_worker
>     model = cls.build_model(args=args)
>   File "/DATA/Sougata/BTech/espnet/espnet2/tasks/asr.py", line 496, in build_model
>     frontend = frontend_class(**args.frontend_conf)
> TypeError: __init__() got an unexpected keyword argument 'fs'
> # Accounting: time=4 threads=1
> # Ended (code 1) at Wed Nov 15 18:21:34 IST 2023, elapsed time 4 seconds](url)
> ```
> 
> I was getting this error

I am also facing the same issue. Kindly please help.

**Comment by siddhu001** [comment]
I am able to reproduce this error. Thanks a lot for pointing this out. I create a small PR to quickly fix this: https://github.com/espnet/espnet/pull/5760

Also input_size should be 1280 instead of 1024 in the config.

**Comment by mukherjeesougata** [comment]
Yes I have assiged the preencoder input_size value as 1280 only #5759. 
In order to fix this issue I have to replace the `<espnet-root>/espnet/espnet2/asr/frontend/whisper.py` with the modified [whisper frontend](https://github.com/espnet/espnet/pull/5760/commits/297ec9a9933cb69f508f88910a371d1f72a83149) script. Is is so?
