### ISSUE TITLE
RuntimeError: All sequences must has same length: 76640 != 76544

### ISSUE THREAD

**Issue by rookie0607** [espnet/espnet#5560]
when i run egs2/chime4/enh1/run.sh --stage 6 --stop_stage 6 ; i get the follwing erro:

[2a97b06ea3da] 2023-11-21 15:19:14,927 (chunk_iter_factory:171) WARNING: The length of '005376-005936' is 8960, but it is shorter than any candidates of chunk-length: [24000]
[2a97b06ea3da] 2023-11-21 15:19:14,930 (chunk_iter_factory:171) WARNING: The length of '496196-497656' is 23360, but it is shorter than any candidates of chunk-length: [24000]
[2a97b06ea3da] 2023-11-21 15:19:14,932 (chunk_iter_factory:171) WARNING: The length of '490906-492036' is 18080, but it is shorter than any candidates of chunk-length: [24000]
Traceback (most recent call last):
  File "/opt/miniconda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/miniconda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/huangsk/tools/espnet/espnet2/bin/enh_train.py", line 23, in <module>
    main()
  File "/home/huangsk/tools/espnet/espnet2/bin/enh_train.py", line 19, in main
    EnhancementTask.main(cmd=cmd)
  File "/home/huangsk/tools/espnet/espnet2/tasks/abs_task.py", line 1117, in main
    cls.main_worker(args)
  File "/home/huangsk/tools/espnet/espnet2/tasks/abs_task.py", line 1430, in main_worker
    cls.trainer.run(
  File "/home/huangsk/tools/espnet/espnet2/train/trainer.py", line 304, in run
    all_steps_are_invalid = cls.train_one_epoch(
  File "/home/huangsk/tools/espnet/espnet2/train/trainer.py", line 531, in train_one_epoch
    for iiter, (utt_id, batch) in enumerate(
  File "/home/huangsk/tools/espnet/espnet2/train/reporter.py", line 267, in measure_iter_time
    retval = next(iterator)
  File "/home/huangsk/tools/espnet/espnet2/iterators/chunk_iter_factory.py", line 156, in build_iter
    raise RuntimeError(
RuntimeError: All sequences must has same length: 76640 != 76544

how to do solved it ? thanks!

**Comment by Emrys365** [comment]
The error indicates that one sample in your dataset contains signals that have different lengths, which should not happen normally. My guess is something went wrong during the dataset downloading or preparation.

Could you try to print the utterance ID when such an error occurs? That can tell you which sample is causing this error.

**Comment by rookie0607** [comment]
> The error indicates that one sample in your dataset contains signals that have different lengths, which should not happen normally. My guess is something went wrong during the dataset downloading or preparation.
> 
> Could you try to print the utterance ID when such an error occurs? That can tell you which sample is causing this error.

Thank you for your reply. Following your instructions, I have resolved the issue
