### ISSUE TITLE
Train egs2/chime4/enh_asr1 occur CUDA out of memory

### ISSUE THREAD

**Issue by rookie0607** [espnet/espnet#5564]
When train egs2/chime4/enh_asr1, ./run --stage 11  --stop_stage 11 
The configuration file I am using is：https://github.com/espnet/espnet/blob/master/egs2/chime4/enh_asr1/conf/tuning/train_enh_asr_convtasnet_init_noenhloss_wavlm_transformer_init_lr1e-4_accum1_adam_specaug_bypass0.yaml
I set batch to 1 and still report CUDA out of memory error. How can I solve this problem？

Traceback (most recent call last):
  File "/opt/miniconda/envs/espnet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/miniconda/envs/espnet/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/huangsk/tools/espnet/espnet2/tasks/abs_task.py", line 1430, in main_worker
    cls.trainer.run(
  File "/home/huangsk/tools/espnet/espnet2/train/trainer.py", line 304, in run
    all_steps_are_invalid = cls.train_one_epoch(
  File "/home/huangsk/tools/espnet/espnet2/train/trainer.py", line 588, in train_one_epoch
    retval = model(**batch)
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/huangsk/tools/espnet/espnet2/enh/espnet_enh_s2t_model.py", line 268, in forward
    loss_s2t, stats, weight = self.asr_pit_loss(
  File "/home/huangsk/tools/espnet/espnet2/enh/espnet_enh_s2t_model.py", line 447, in asr_pit_loss
    loss, stats, weight = self.s2t_model(
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/huangsk/tools/espnet/espnet2/asr/espnet_model.py", line 237, in forward
    encoder_out, encoder_out_lens = self.encode(speech, speech_lengths)
  File "/home/huangsk/tools/espnet/espnet2/asr/espnet_model.py", line 378, in encode
    feats, feats_lengths = self._extract_feats(speech, speech_lengths)
  File "/home/huangsk/tools/espnet/espnet2/asr/espnet_model.py", line 445, in _extract_feats
    feats, feats_lengths = self.frontend(speech, speech_lengths)
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/huangsk/tools/espnet/espnet2/asr/frontend/s3prl.py", line 99, in forward
    feats, feats_lens = self.upstream(input, input_lengths)
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/s3prl/nn/upstream.py", line 208, in forward
    hidden_states = self.upstream(wavs_list)["hidden_states"]
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/s3prl/upstream/interfaces.py", line 103, in __call__
    result = super().__call__(wavs, *args, **kwargs) or {}
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/s3prl/upstream/hubert/expert.py", line 68, in forward
    features, feat_padding_mask = self.model.extract_features(
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/s3prl/upstream/hubert/hubert_model.py", line 574, in extract_features
    res = self.forward(
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/s3prl/upstream/hubert/hubert_model.py", line 506, in forward
    x, _ = self.encoder(
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/s3prl/upstream/wav2vec2/wav2vec2_model.py", line 3040, in forward
    x, layer_results = self.extract_features(x, padding_mask, layer)
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/s3prl/upstream/wav2vec2/wav2vec2_model.py", line 3086, in extract_features
    x, (z, lr) = layer(
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/s3prl/upstream/wav2vec2/wav2vec2_model.py", line 3270, in forward
    x, attn = self.self_attn(
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/s3prl/upstream/wav2vec2/wav2vec2_model.py", line 1146, in forward
    return F.multi_head_attention_forward(
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/torch/nn/functional.py", line 5373, in multi_head_attention_forward
    attn_output = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 3; 23.69 GiB total capacity; 22.94 GiB already allocated; 16.75 MiB free; 23.12 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by Fhrozen** [comment]
If you check at https://github.com/espnet/espnet/blob/d3254133c595ea8271072ee49a1b4ceb3ed4fd7a/egs2/chime4/enh_asr1/conf/tuning/train_enh_asr_convtasnet_init_noenhloss_wavlm_transformer_init_lr1e-4_accum1_adam_specaug_bypass0.yaml#L3C17-L3C24
you will see that the batch is 16 for an A6000 with 48GB. If you have a 24GB GPU, then you need to reduce to 8, also, to keep the same batch size, you can use 
```yaml
batch_size: 8 
accum_grad: 2
```
the model will be backpropagated after accumulating 2 gradients, simulating a batch size of 16 even with low memory.

**Comment by KarolinaPondel** [comment]
Hi, you worked with chime4 dataset, so please help me understand it. I am trying to run egs2/chime4/enh_asr1 recepie. I downloaded the dataset (https://www.chimechallenge.org/challenges/chime4/download) and it doesn't look like the official site (https://www.chimechallenge.org/challenges/chime4/data#Audio):

Image
There is no
├── audio
├── transcriptions
└── WSJ0
only
├── annotations

same in with huggingface dataset card (https://huggingface.co/datasets/ksbai123/Chime4).
How can I access the missing data and made train, dev, test split?

**Comment by Emrys365** [comment]
> Hi, you worked with chime4 dataset, so please help me understand it. I am trying to run egs2/chime4/enh_asr1 recepie. I downloaded the dataset (https://www.chimechallenge.org/challenges/chime4/download) and it doesn't look like the official site (https://www.chimechallenge.org/challenges/chime4/data#Audio)
> 
> There is no
> ├── audio
> ├── transcriptions
> └── WSJ0
> only
> ├── annotations
> 
> same in with huggingface dataset card (https://huggingface.co/datasets/ksbai123/Chime4).
> How can I access the missing data and make train, dev, test split?

Hi, as mentioned in the official website, you have to download the audio data from LDC: https://catalog.ldc.upenn.edu/LDC2017S24

**Comment by KarolinaPondel** [comment]
Thanks, now I understand ! :)
