### ISSUE TITLE
torch._C._LinAlgError: torch.linalg.solve: (Batch element 9): The solver failed because the input matrix is singular.

### ISSUE THREAD

**Issue by rookie0607** [espnet/espnet#5565]
**Describe the bug**
**Basic environments:**
 - OS information: Linux 3.10.0-1160.95.1.el7.x86_64 #1 SMP Mon Jul 24 13:59:37 UTC 2023 x86_64
 - python version: 3.8.18 (default, Sep 11 2023, 13:40:15)  [GCC 11.2.0]
 - espnet version: 202310
 - pytorch version 2.0.1

Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.27.7
Libc version: glibc-2.31

Python version: 3.8.18 (default, Sep 11 2023, 13:40:15)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.95.1.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA Graphics Device
GPU 1: NVIDIA Graphics Device
GPU 2: NVIDIA Graphics Device
GPU 3: NVIDIA Graphics Device

Nvidia driver version: 520.61.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.1
[pip3] torch==2.0.1
[pip3] torch-complex==0.4.3
[pip3] torch-optimizer==0.3.0
[pip3] torchaudio==2.0.2
[conda] blas                      1.0                         mkl    defaults
[conda] mkl                       2023.1.0         h213fc3f_46344    defaults
[conda] mkl-service               2.4.0            py38h5eee18b_1    defaults
[conda] mkl_fft                   1.3.8            py38h5eee18b_0    defaults
[conda] mkl_random                1.2.4            py38hdb19cb5_0    defaults
[conda] numpy                     1.24.4                   pypi_0    pypi
[conda] numpy-base                1.23.5           py38h060ed82_1    defaults
[conda] pytorch                   2.0.1           py3.8_cuda11.8_cudnn8.7.0_0    pytorch
[conda] pytorch-cuda              11.8                 h7e8668a_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.1                    pypi_0    pypi
[conda] torch                     2.0.1                    pypi_0    pypi
[conda] torch-complex             0.4.3                    pypi_0    pypi
[conda] torch-optimizer           0.3.0                    pypi_0    pypi
[conda] torchaudio                2.0.2                py38_cu118    pytorch
[conda] torchtriton               2.0.0                      py38    pytorch

**Task information:**
 - Task: ENH
 - Recipe:chime4
 - ESPnet2

**To Reproduce**
1.  cd egs2/chime4/enh1
2. run.sh --stage 6 --stop_stage 6
3. exp/enh_train_enh_beamformer_wpd_ci_sdr_shorttap_raw/train.log

**Error logs**
The configuration file I am using is：https://github.com/espnet/espnet/blob/master/egs2/chime4/enh1/conf/tuning/train_enh_beamformer_wpd_ci_sdr_shorttap.yaml
But l get the follwing erro:

Process SpawnProcess-4:
Traceback (most recent call last):
  File "/opt/miniconda/envs/espnet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/miniconda/envs/espnet/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/huangsk/tools/espnet/espnet2/tasks/abs_task.py", line 1430, in main_worker
    cls.trainer.run(
  File "/home/huangsk/tools/espnet/espnet2/train/trainer.py", line 304, in run
    all_steps_are_invalid = cls.train_one_epoch(
  File "/home/huangsk/tools/espnet/espnet2/train/trainer.py", line 588, in train_one_epoch
    retval = model(**batch)
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1139, in forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by
making sure all `forward` function outputs participate in calculating loss.
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 3: 32 33
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error

I added parameters  **--unused_parameters true**

But l get the follwing erro:

[2a97b06ea3da:0/4] 2023-11-27 03:21:22,371 (trainer:753) INFO: 1epoch:train:115-228batch: iter_time=0.257, forward_time=0.120, ci_sdr_loss=1.721, loss=1.721, backward_time=0.135, grad_norm=0.422, clip=0.000e+00, loss_scale=1.000, optim_step_time=0.003, optim0_lr0=4.000e-04, train_time=0.591
[2a97b06ea3da:0/4] 2023-11-27 03:21:24,241 (trainer:684) WARNING: The grad norm is nan. Skipping updating the model.
[2a97b06ea3da:0/4] 2023-11-27 03:21:24,828 (trainer:684) WARNING: The grad norm is nan. Skipping updating the model.
[2a97b06ea3da:0/4] 2023-11-27 03:21:28,253 (trainer:684) WARNING: The grad norm is nan. Skipping updating the model.
[2a97b06ea3da:0/4] 2023-11-27 03:21:33,487 (trainer:684) WARNING: The grad norm is nan. Skipping updating the model.
[2a97b06ea3da:0/4] 2023-11-27 03:21:35,278 (trainer:684) WARNING: The grad norm is nan. Skipping updating the model.
[2a97b06ea3da:0/4] 2023-11-27 03:21:39,331 (trainer:684) WARNING: The grad norm is nan. Skipping updating the model.
[2a97b06ea3da:0/4] 2023-11-27 03:21:42,440 (trainer:684) WARNING: The grad norm is nan. Skipping updating the model.
[2a97b06ea3da:0/4] 2023-11-27 03:21:45,480 (trainer:684) WARNING: The grad norm is nan. Skipping updating the model.
[2a97b06ea3da:0/4] 2023-11-27 03:21:46,270 (trainer:684) WARNING: The grad norm is nan. Skipping updating the model.
[2a97b06ea3da:0/4] 2023-11-27 03:21:46,918 (trainer:684) WARNING: The grad norm is nan. Skipping updating the model.
Process SpawnProcess-3:
Traceback (most recent call last):
  File "/opt/miniconda/envs/espnet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/miniconda/envs/espnet/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/huangsk/tools/espnet/espnet2/tasks/abs_task.py", line 1430, in main_worker
    cls.trainer.run(
  File "/home/huangsk/tools/espnet/espnet2/train/trainer.py", line 304, in run
    all_steps_are_invalid = cls.train_one_epoch(
  File "/home/huangsk/tools/espnet/espnet2/train/trainer.py", line 588, in train_one_epoch
    retval = model(**batch)
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/huangsk/tools/espnet/espnet2/enh/espnet_model.py", line 299, in forward
    loss, stats, weight, perm = self.forward_loss(
  File "/home/huangsk/tools/espnet/espnet2/enh/espnet_model.py", line 451, in forward_loss
    l, s, o = loss_wrapper(sref, spre, {**others, **o})
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/huangsk/tools/espnet/espnet2/enh/loss/wrappers/fixed_order.py", line 33, in forward
    loss += torch.mean(self.criterion(r, i)) / num_spk
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/huangsk/tools/espnet/espnet2/enh/loss/criterions/time_domain.py", line 106, in forward
    return ci_sdr.pt.ci_sdr_loss(
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/ci_sdr/pt/sdr.py", line 73, in ci_sdr_loss
    return ci_sdr(
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/ci_sdr/pt/sdr.py", line 349, in ci_sdr
    reverberated = wiener_filter_predict_single_input(
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/ci_sdr/pt/wiener_filter.py", line 401, in wiener_filter_predict_single_input
    w = torch_linalg_solve(R, p[..., None])
torch._C._LinAlgError: torch.linalg.solve: (Batch element 9): The solver failed because the input matrix is singular.
2a97b06ea3da:55380:55426 [2] NCCL INFO [Service thread] Connection closed by localRank 2
2a97b06ea3da:55380:55380 [2] NCCL INFO comm 0xd050090 rank 2 nranks 4 cudaDev 2 busId 89000 - Abort COMPLETE
Traceback (most recent call last):
  File "/opt/miniconda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/miniconda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/huangsk/tools/espnet/espnet2/bin/enh_train.py", line 23, in <module>
    main()
  File "/home/huangsk/tools/espnet/espnet2/bin/enh_train.py", line 19, in main
    EnhancementTask.main(cmd=cmd)
  File "/home/huangsk/tools/espnet/espnet2/tasks/abs_task.py", line 1167, in main
    while not ProcessContext(processes, error_queues).join():
  File "/opt/miniconda/envs/espnet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 149, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 2 terminated with exit code 1
# Accounting: time=196 threads=1
# Ended (code 1) at Mon Nov 27 03:21:59 UTC 2023, elapsed time 196 seconds

**Comment by sw005320** [comment]
@Emrys365, do you have any ideas?

**Comment by Emrys365** [comment]
I think this is related to the CI-SDR implementation in the package [ci-sdr](https://github.com/fgnt/ci_sdr). Could you try the alternative implementation [`sdr`](https://github.com/espnet/espnet/blob/master/espnet2/tasks/enh.py#L149)? It provides an additional argument `load_diag` to avoid the above error you encountered.

You could also check the similar discussion in https://github.com/espnet/espnet/issues/5056.

**Comment by rookie0607** [comment]
> I think this is related to the CI-SDR implementation in the package [ci-sdr](https://github.com/fgnt/ci_sdr). Could you try the alternative implementation [`sdr`](https://github.com/espnet/espnet/blob/master/espnet2/tasks/enh.py#L149)? It provides an additional argument `load_diag` to avoid the above error you encountered.
> 
> You could also check the similar discussion in #5056.

Thank you very much. Following your instructions, I have successfully resolved the issue.
