### ISSUE TITLE
network training failed on CTC

### ISSUE THREAD

**Issue by vjdtao** [espnet/espnet#559]
I run egg/csj/asr1, and failed on the stage 4, network training. exp/train_nodup_chainer_vggblstm_e4_subsample1_2_2_1_1_unit1024_proj320_d1_unit1024_location_adim320_aconvc10_aconvf100_mtlalpha0.5_adadelta_sampprob0.0_bs32_mli800_mlo150/train.log shows as follows, but not very informative. I'd really appreciate if anyone help resolve it

```# asr_train.py --ngpu 1 --backend chainer --outdir exp/train_nodup_chainer_vggblstm_e4_subsample1_2_2_1_1_unit1024_proj320_d1_unit1024_location_adim320_aconvc10_aconvf100_mtlalpha0.5_adadelta_sampprob0.0_bs32_mli800_mlo150/results --debugmode 1 --dict data/lang_1char/train_nodup_units.txt --debugdir exp/train_nodup_chainer_vggblstm_e4_subsample1_2_2_1_1_unit1024_proj320_d1_unit1024_location_adim320_aconvc10_aconvf100_mtlalpha0.5_adadelta_sampprob0.0_bs32_mli800_mlo150 --minibatches 0 --seed 1 --verbose 0 --resume --train-json dump/train_nodup/deltafalse/data.json --valid-json dump/train_dev/deltafalse/data.json --etype vggblstm --elayers 4 --eunits 1024 --eprojs 320 --subsample 1_2_2_1_1 --dlayers 1 --dunits 1024 --atype location --adim 320 --awin 5 --aheads 4 --aconv-chans 10 --aconv-filts 100 --mtlalpha 0.5 --batch-size 32 --maxlen-in 800 --maxlen-out 150 --sampling-probability 0.0 --opt adadelta --epochs 15 
# Started at Tue Jan 22 18:09:10 EST 2019
#
2019-01-22 18:09:10,573 (asr_train:169) WARNING: Skip DEBUG/INFO messages
2019-01-22 18:09:10,583 (asr_train:187) WARNING: CUDA_VISIBLE_DEVICES is not set.
2019-01-22 18:09:10,982 (e2e_asr:119) WARNING: Subsampling is not performed for vgg*. It is performed in max pooling layers at CNN.
Exception in main training loop: CTC_STATUS_EXECUTION_FAILED: execution failed
Traceback (most recent call last):
  File "/home/espnet/01212019/tools/venv/lib/python2.7/site-packages/chainer/training/trainer.py", line 315, in run
    update()
  File "/home/espnet/01212019/tools/venv/lib/python2.7/site-packages/chainer/training/updaters/standard_updater.py", line 165, in update
    self.update_core()
  File "/home/espnet/01212019/espnet/asr/asr_chainer.py", line 88, in update_core
    loss = optimizer.target(*x)
  File "/home/espnet/01212019/espnet/nets/e2e_asr.py", line 74, in __call__
    loss_ctc, loss_att, acc = self.predictor(xs, ilens, ys)
  File "/home/espnet/01212019/espnet/nets/e2e_asr.py", line 172, in __call__
    loss_ctc = self.ctc(hs, ys)
  File "/home/espnet/01212019/espnet/nets/e2e_asr.py", line 310, in __call__
    self.loss = warp_ctc(y_hat, ilens, [cuda.to_cpu(l.data) for l in ys])[0]
  File "/home/espnet/01212019/tools/venv/lib/python2.7/site-packages/chainer_ctc/warpctc.py", line 125, in ctc
    return CTC(seq_lengths, labels)(x)
  File "/home/espnet/01212019/tools/venv/lib/python2.7/site-packages/chainer/function.py", line 235, in __call__
    ret = node.apply(inputs)
  File "/home/espnet/01212019/tools/venv/lib/python2.7/site-packages/chainer/function_node.py", line 263, in apply
    outputs = self.forward(in_data)
  File "/home/espnet/01212019/tools/venv/lib/python2.7/site-packages/chainer/function.py", line 135, in forward
    return self._function.forward(inputs)
  File "/home/espnet/01212019/tools/venv/lib/python2.7/site-packages/chainer_ctc/warpctc.py", line 77, in forward
    raise e
Will finalize trainer extensions and updater before reraising the exception.
[JTraceback (most recent call last):
  File "/home/espnet/01212019/espnet/bin/asr_train.py", line 225, in <module>
    main()
  File "/home/espnet/01212019/espnet/bin/asr_train.py", line 216, in main
    train(args)
  File "/home/espnet/01212019/espnet/asr/asr_chainer.py", line 437, in train
    trainer.run()
  File "/home/espnet/01212019/tools/venv/lib/python2.7/site-packages/chainer/training/trainer.py", line 329, in run
    six.reraise(*sys.exc_info())
  File "/home/espnet/01212019/tools/venv/lib/python2.7/site-packages/chainer/training/trainer.py", line 315, in run
    update()
  File "/home/espnet/01212019/tools/venv/lib/python2.7/site-packages/chainer/training/updaters/standard_updater.py", line 165, in update
    self.update_core()
  File "/home/espnet/01212019/espnet/asr/asr_chainer.py", line 88, in update_core
    loss = optimizer.target(*x)
  File "/home/espnet/01212019/espnet/nets/e2e_asr.py", line 74, in __call__
    loss_ctc, loss_att, acc = self.predictor(xs, ilens, ys)
  File "/home/espnet/01212019/espnet/nets/e2e_asr.py", line 172, in __call__
    loss_ctc = self.ctc(hs, ys)
  File "/home/espnet/01212019/espnet/nets/e2e_asr.py", line 310, in __call__
    self.loss = warp_ctc(y_hat, ilens, [cuda.to_cpu(l.data) for l in ys])[0]
  File "/home/espnet/01212019/tools/venv/lib/python2.7/site-packages/chainer_ctc/warpctc.py", line 125, in ctc
    return CTC(seq_lengths, labels)(x)
  File "/home/espnet/01212019/tools/venv/lib/python2.7/site-packages/chainer/function.py", line 235, in __call__
    ret = node.apply(inputs)
  File "/home/espnet/01212019/tools/venv/lib/python2.7/site-packages/chainer/function_node.py", line 263, in apply
    outputs = self.forward(in_data)
  File "/home/espnet/01212019/tools/venv/lib/python2.7/site-packages/chainer/function.py", line 135, in forward
    return self._function.forward(inputs)
  File "/home/espnet/01212019/tools/venv/lib/python2.7/site-packages/chainer_ctc/warpctc.py", line 77, in forward
    raise e
chainer_ctc.src.warp_ctc.CTCError: CTC_STATUS_EXECUTION_FAILED: execution failed
# Accounting: time=21 threads=1
# Ended (code 1) at Tue Jan 22 18:09:31 EST 2019, elapsed time 21 seconds
```

**Comment by sw005320** [comment]
warpctc may not be correctly installed. Please check https://github.com/espnet/espnet#step-3-installation-check

**Comment by vjdtao** [comment]
Here is the output of installation check, but it looks fine.
```
INFO: python version = 2.7.5 (default, Jul 13 2018, 13:06:57) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
INFO: library availableness check start.
INFO: # libraries to be checked = 8
INFO: --> espnet is installed.
INFO: --> kaldi_io_py is installed.
INFO: --> matplotlib is installed.
INFO: --> torch is installed.
INFO: --> chainer is installed.
INFO: --> cupy is installed.
INFO: --> chainer_ctc is installed.
INFO: --> warpctc_pytorch is installed.
INFO: library availableness check done.
INFO: 8 / 8 libraries are correctly installed.
INFO: library version check start.
INFO: # libraries to be checked = 4
INFO: --> torch version is matched.
INFO: --> chainer version is matched.
INFO: --> cupy version is matched.
INFO: --> warpctc_pytorch version is matched.
INFO: library version check done.
INFO: 4 / 4 libraries are correct version.
INFO: cuda availableness check start.
INFO: --> cuda is available in torch.
INFO: --> cudnn is available in torch.
INFO: --> cuda is available in chainer.
INFO: --> cudnn is available in chainer.
WARNING: --> it seems that nccl is not installed. multi-gpu is not enabled.
WARNING: --> if you want to use multi-gpu, please install it and then re-setup.
INFO: --> multi-gpu is available (#gpus = 2).
INFO: cuda availableness check done.
```

**Comment by sw005320** [comment]
Hmm. It seems to be similar to the problem in https://github.com/espnet/espnet/issues/270. Could you check your installation again?

**Comment by vjdtao** [comment]
It seems to be similar. I just simply followed the step 2-A) installation with compiled Kaldi, and the Makefile is under the tools/ directory. I'm not sure where I did incorrectly.

**Comment by gtache** [comment]
@vjdtao I'm using 9.2 so it shouldn't be the problem. Have you tried simply rebuilding warp-ctc and chainer-ctc ?

**Comment by vjdtao** [comment]
@gtache to rebuild warp-ctc and chainer-ctc, are the following command lines correct?
```
cd tools
make warp-ctc
make chainer_ctc
```
