### ISSUE TITLE
RuntimeError: Internal: src/trainer_interface.cc(580) [(static_cast<int>(required_chars_.size() + meta_pieces_.size())) <= (trainer_spec_.vocab_size())] Vocabulary size is smaller than required_chars. 30 vs 65. Increase vocab_size or decrease character_coverage with --character_coverage option.

### ISSUE THREAD

**Issue by mukherjeesougata-eros** [espnet/espnet#5591]
I am carrying out an asr task so for that I have run the following commands:-
1. ./asr.sh --stage 2 --stop_stage 2 --train_set train_nodev --valid_set train_dev --test_sets "train_dev test"
2. ./asr.sh --stage 3 --stop_stage 3 --train_set train_nodev --valid_set train_dev --test_sets "train_dev test" --nj 4
3. ./asr.sh --stage 4 --stop_stage 4 --train_set train_nodev --valid_set train_dev --test_sets "train_dev test"
4. ./asr.sh --stage 5 --stop_stage 5 --train_set train_nodev --valid_set train_dev --test_sets "train_dev test"
After running the stage 5 I have encountered the following error:-
```
2023-12-13T12:20:22 (asr.sh:283:main) ./asr.sh --stage 5 --stop_stage 5 --train_set train_nodev --valid_set train_dev --test_sets train_dev test
2023-12-13T12:20:23 (asr.sh:321:main) Info: The valid_set 'train_dev' is included in the test_sets. '--eval_valid_set true' is set and 'train_dev' is removed from the test_sets
2023-12-13T12:20:23 (asr.sh:565:main) Skipped stages:  9 14 15 16 
2023-12-13T12:20:23 (asr.sh:878:main) Stage 5: Generate token_list from dump/raw/org/train_nodev/text using BPE
sentencepiece_trainer.cc(177) LOG(INFO) Running command: --input=data/token_list/bpe_unigram30/train.txt --vocab_size=30 --model_type=unigram --model_prefix=data/token_list/bpe_unigram30/bpe --character_coverage=1.0 --input_sentence_size=100000000
sentencepiece_trainer.cc(77) LOG(INFO) Starts training with : 
trainer_spec {
  input: data/token_list/bpe_unigram30/train.txt
  input_format: 
  model_prefix: data/token_list/bpe_unigram30/bpe
  model_type: UNIGRAM
  vocab_size: 30
  self_test_sample_size: 0
  character_coverage: 1
  input_sentence_size: 100000000
  shuffle_input_sentence: 1
  seed_sentencepiece_size: 1000000
  shrinking_factor: 0.75
  max_sentence_length: 4192
  num_threads: 16
  num_sub_iterations: 2
  max_sentencepiece_length: 16
  split_by_unicode_script: 1
  split_by_number: 1
  split_by_whitespace: 1
  split_digits: 0
  treat_whitespace_as_suffix: 0
  allow_whitespace_only_pieces: 0
  required_chars: 
  byte_fallback: 0
  vocabulary_output_piece_score: 1
  train_extremely_large_corpus: 0
  hard_vocab_limit: 1
  use_all_vocab: 0
  unk_id: 0
  bos_id: 1
  eos_id: 2
  pad_id: -1
  unk_piece: <unk>
  bos_piece: <s>
  eos_piece: </s>
  pad_piece: <pad>
  unk_surface:  ⁇ 
  enable_differential_privacy: 0
  differential_privacy_noise_level: 0
  differential_privacy_clipping_threshold: 0
}
normalizer_spec {
  name: nmt_nfkc
  add_dummy_prefix: 1
  remove_extra_whitespaces: 1
  escape_whitespaces: 1
  normalization_rule_tsv: 
}
denormalizer_spec {}
trainer_interface.cc(350) LOG(INFO) SentenceIterator is not specified. Using MultiFileSentenceIterator.
trainer_interface.cc(181) LOG(INFO) Loading corpus: data/token_list/bpe_unigram30/train.txt
trainer_interface.cc(406) LOG(INFO) Loaded all 4140 sentences
trainer_interface.cc(422) LOG(INFO) Adding meta_piece: <unk>
trainer_interface.cc(422) LOG(INFO) Adding meta_piece: <s>
trainer_interface.cc(422) LOG(INFO) Adding meta_piece: </s>
trainer_interface.cc(427) LOG(INFO) Normalizing sentences...
trainer_interface.cc(536) LOG(INFO) all chars count=172310
trainer_interface.cc(557) LOG(INFO) Alphabet size=62
trainer_interface.cc(558) LOG(INFO) Final character coverage=1
Traceback (most recent call last):
  File "/home/sp5/sougata/espnet/tools/sentencepiece_commands/spm_train", line 12, in <module>
    spm.SentencePieceTrainer.Train(" ".join(sys.argv[1:]))
  File "/home/sp5/anaconda3/envs/espnet/lib/python3.8/site-packages/sentencepiece/__init__.py", line 989, in Train
    SentencePieceTrainer._Train(arg=arg, **kwargs)
  File "/home/sp5/anaconda3/envs/espnet/lib/python3.8/site-packages/sentencepiece/__init__.py", line 945, in _Train
    return SentencePieceTrainer._TrainFromString(arg)
  File "/home/sp5/anaconda3/envs/espnet/lib/python3.8/site-packages/sentencepiece/__init__.py", line 923, in _TrainFromString
    return _sentencepiece.SentencePieceTrainer__TrainFromString(arg)
RuntimeError: Internal: src/trainer_interface.cc(580) [(static_cast<int>(required_chars_.size() + meta_pieces_.size())) <= (trainer_spec_.vocab_size())] Vocabulary size is smaller than required_chars. 30 vs 65. Increase vocab_size or decrease character_coverage with --character_coverage option.
```
Can anybody kindly please suggest how to increase vocab_size or decrease character_coverage?

**Comment by sw005320** [comment]
Please increase the vocabulary size by using `--nbpe` option

**Comment by mukherjeesougata** [comment]
If I put any number which is greater than 65 by using --nbpe option then will it be appropriate(for example --nbpe 75) and will it affect the decoded results after training?

**Comment by sw005320** [comment]
Yes, the `--nbpe` option affects the result.
I suggest you test it to see it.
(I could not answer more than that without the information about the data).

**Comment by mukherjeesougata** [comment]
I am attaching the files which were generated in the train_nodev set after the data preparation stage for providing information regarding data
[spk2utt.txt](https://github.com/espnet/espnet/files/13676936/spk2utt.txt)
[text.txt](https://github.com/espnet/espnet/files/13676937/text.txt)
[utt2spk.txt](https://github.com/espnet/espnet/files/13676938/utt2spk.txt)
[wav_scp.txt](https://github.com/espnet/espnet/files/13676939/wav_scp.txt)
So, @sw005320 can you kindly please state the appropriate number to be chosen against ```--nbpe``` option in order to get the best result?
I also need to know which is a better option between increasing vocab_size and decreasing character_coverage for best result?
