### ISSUE TITLE
ValueError: /data/Sougata/Btech_intern/checkpoints/finetuned/xlsr53minilibrispeech/checkpoint_best.pt is not a valid checkpoint since the required key: task_cfg is missing

### ISSUE THREAD

**Issue by mukherjeesougata** [espnet/espnet#5602]
I have finetuned xlsr-128 pretrained model on my own dataset using fairseq toolkit. After that I wanted 'checkpoint_best.pt' to be used as a frontend for CTC/attention based architechture for asr task for which I am using [config](https://github.com/espnet/espnet/blob/8a8709e6579a593eef2e98433a7e69a6ae1c828f/egs2/fleurs/asr1/conf/tuning/train_asr_conformer_scctc.yaml) with the following changes:-
```
frontend: s3prl
frontend_conf:
    frontend_conf:
        upstream: wav2vec2_local  # Note: If the upstream is changed, please change the input_size in the preencoder.
        path_or_url: <path to checkpoint_best.pt>
    #download_dir: ./hub
    multilayer_feature: True
```
It is giving me the following error:-
```
2023-12-19T14:14:46 (asr.sh:283:main) ./asr.sh --stage 11 --stop_stage 11 --train_set train_nodev --valid_set train_dev --test_sets train_dev test --ngpu 2 --asr_config conf/train_asr_conformer_scctc.yaml --feats_normalize uttmvn
2023-12-19T14:14:46 (asr.sh:321:main) Info: The valid_set 'train_dev' is included in the test_sets. '--eval_valid_set true' is set and 'train_dev' is removed from the test_sets
2023-12-19T14:14:46 (asr.sh:565:main) Skipped stages:  9 14 15 16 
2023-12-19T14:14:46 (asr.sh:1309:main) Stage 11: ASR Training: train_set=dump/raw/train_nodev, valid_set=dump/raw/train_dev
2023-12-19T14:14:46 (asr.sh:1408:main) Generate 'exp/asr_train_asr_conformer_scctc_raw_bpe30/run.sh'. You can resume the process from stage 11 using this script
2023-12-19T14:14:46 (asr.sh:1412:main) ASR training started... log: 'exp/asr_train_asr_conformer_scctc_raw_bpe30/train.log'
2023-12-19 14:14:46,914 (launch:94) INFO: /data/anaconda3/envs/espnet_wo_cat_feats/bin/python3 /data/Sougata/espnet/espnet2/bin/launch.py --cmd 'run.pl --name exp/asr_train_asr_conformer_scctc_raw_bpe30/train.log' --log exp/asr_train_asr_conformer_scctc_raw_bpe30/train.log --ngpu 2 --num_nodes 1 --init_file_prefix exp/asr_train_asr_conformer_scctc_raw_bpe30/.dist_init_ --multiprocessing_distributed true -- python3 -m espnet2.bin.asr_train --use_preprocessor true --bpemodel data/token_list/bpe_unigram30/bpe.model --token_type bpe --token_list data/token_list/bpe_unigram30/tokens.txt --non_linguistic_symbols none --cleaner none --g2p none --valid_data_path_and_name_and_type dump/raw/train_dev/wav.scp,speech,sound --valid_shape_file exp/asr_stats_raw_bpe30/valid/speech_shape --resume true --ignore_init_mismatch false --fold_length 80000 --output_dir exp/asr_train_asr_conformer_scctc_raw_bpe30 --config conf/train_asr_conformer_scctc.yaml --frontend_conf fs=16k --train_data_path_and_name_and_type dump/raw/train_nodev/wav.scp,speech,sound --train_shape_file exp/asr_stats_raw_bpe30/train/speech_shape --fold_length 150 --train_data_path_and_name_and_type dump/raw/train_nodev/text,text,text --train_shape_file exp/asr_stats_raw_bpe30/train/text_shape.bpe --valid_data_path_and_name_and_type dump/raw/train_dev/text,text,text --valid_shape_file exp/asr_stats_raw_bpe30/valid/text_shape.bpe
2023-12-19 14:14:46,944 (launch:237) INFO: single-node with 2gpu on distributed mode
2023-12-19 14:14:46,949 (launch:348) INFO: log file: exp/asr_train_asr_conformer_scctc_raw_bpe30/train.log
run.pl: job failed, log is in exp/asr_train_asr_conformer_scctc_raw_bpe30/train.log
Command '['run.pl', '--name', 'exp/asr_train_asr_conformer_scctc_raw_bpe30/train.log', '--gpu', '2', 'exp/asr_train_asr_conformer_scctc_raw_bpe30/train.log', 'python3', '-m', 'espnet2.bin.asr_train', '--use_preprocessor', 'true', '--bpemodel', 'data/token_list/bpe_unigram30/bpe.model', '--token_type', 'bpe', '--token_list', 'data/token_list/bpe_unigram30/tokens.txt', '--non_linguistic_symbols', 'none', '--cleaner', 'none', '--g2p', 'none', '--valid_data_path_and_name_and_type', 'dump/raw/train_dev/wav.scp,speech,sound', '--valid_shape_file', 'exp/asr_stats_raw_bpe30/valid/speech_shape', '--resume', 'true', '--ignore_init_mismatch', 'false', '--fold_length', '80000', '--output_dir', 'exp/asr_train_asr_conformer_scctc_raw_bpe30', '--config', 'conf/train_asr_conformer_scctc.yaml', '--frontend_conf', 'fs=16k', '--train_data_path_and_name_and_type', 'dump/raw/train_nodev/wav.scp,speech,sound', '--train_shape_file', 'exp/asr_stats_raw_bpe30/train/speech_shape', '--fold_length', '150', '--train_data_path_and_name_and_type', 'dump/raw/train_nodev/text,text,text', '--train_shape_file', 'exp/asr_stats_raw_bpe30/train/text_shape.bpe', '--valid_data_path_and_name_and_type', 'dump/raw/train_dev/text,text,text', '--valid_shape_file', 'exp/asr_stats_raw_bpe30/valid/text_shape.bpe', '--ngpu', '2', '--multiprocessing_distributed', 'True']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/data/anaconda3/envs/espnet_wo_cat_feats/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/anaconda3/envs/espnet_wo_cat_feats/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/Sougata/espnet/espnet2/bin/launch.py", line 384, in <module>
    main()
  File "/data/Sougata/espnet/espnet2/bin/launch.py", line 375, in main
    raise RuntimeError(
RuntimeError: 
################### The last 1000 lines of exp/asr_train_asr_conformer_scctc_raw_bpe30/train.log ###################
# python3 -m espnet2.bin.asr_train --use_preprocessor true --bpemodel data/token_list/bpe_unigram30/bpe.model --token_type bpe --token_list data/token_list/bpe_unigram30/tokens.txt --non_linguistic_symbols none --cleaner none --g2p none --valid_data_path_and_name_and_type dump/raw/train_dev/wav.scp,speech,sound --valid_shape_file exp/asr_stats_raw_bpe30/valid/speech_shape --resume true --ignore_init_mismatch false --fold_length 80000 --output_dir exp/asr_train_asr_conformer_scctc_raw_bpe30 --config conf/train_asr_conformer_scctc.yaml --frontend_conf fs=16k --train_data_path_and_name_and_type dump/raw/train_nodev/wav.scp,speech,sound --train_shape_file exp/asr_stats_raw_bpe30/train/speech_shape --fold_length 150 --train_data_path_and_name_and_type dump/raw/train_nodev/text,text,text --train_shape_file exp/asr_stats_raw_bpe30/train/text_shape.bpe --valid_data_path_and_name_and_type dump/raw/train_dev/text,text,text --valid_shape_file exp/asr_stats_raw_bpe30/valid/text_shape.bpe --ngpu 2 --multiprocessing_distributed True 
# Started at Tue Dec 19 14:14:47 IST 2023
#
/data/anaconda3/envs/espnet_wo_cat_feats/bin/python3 /data/Sougata/espnet/espnet2/bin/asr_train.py --use_preprocessor true --bpemodel data/token_list/bpe_unigram30/bpe.model --token_type bpe --token_list data/token_list/bpe_unigram30/tokens.txt --non_linguistic_symbols none --cleaner none --g2p none --valid_data_path_and_name_and_type dump/raw/train_dev/wav.scp,speech,sound --valid_shape_file exp/asr_stats_raw_bpe30/valid/speech_shape --resume true --ignore_init_mismatch false --fold_length 80000 --output_dir exp/asr_train_asr_conformer_scctc_raw_bpe30 --config conf/train_asr_conformer_scctc.yaml --frontend_conf fs=16k --train_data_path_and_name_and_type dump/raw/train_nodev/wav.scp,speech,sound --train_shape_file exp/asr_stats_raw_bpe30/train/speech_shape --fold_length 150 --train_data_path_and_name_and_type dump/raw/train_nodev/text,text,text --train_shape_file exp/asr_stats_raw_bpe30/train/text_shape.bpe --valid_data_path_and_name_and_type dump/raw/train_dev/text,text,text --valid_shape_file exp/asr_stats_raw_bpe30/valid/text_shape.bpe --ngpu 2 --multiprocessing_distributed True
[iitd:0/2] 2023-12-19 14:14:55,352 (distributed_c10d:432) INFO: Added key: store_based_barrier_key:1 to store for rank: 0
[iitd:0/2] 2023-12-19 14:14:55,352 (distributed_c10d:466) INFO: Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
[iitd:0/2] 2023-12-19 14:14:55,384 (asr:523) INFO: Vocabulary size: 30
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/data/anaconda3/envs/espnet_wo_cat_feats/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data/anaconda3/envs/espnet_wo_cat_feats/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/Sougata/espnet/espnet2/tasks/abs_task.py", line 1219, in main_worker
    model = cls.build_model(args=args)
  File "/data/Sougata/espnet/espnet2/tasks/asr.py", line 529, in build_model
    frontend = frontend_class(**args.frontend_conf)
  File "/data/Sougata/espnet/espnet2/asr/frontend/s3prl.py", line 47, in __init__
    upstream = S3PRLUpstream(
  File "/data/anaconda3/envs/espnet_wo_cat_feats/lib/python3.8/site-packages/s3prl/nn/upstream.py", line 117, in __init__
    self.upstream = getattr(hub, name)(**upstream_conf)
  File "/data/anaconda3/envs/espnet_wo_cat_feats/lib/python3.8/site-packages/s3prl/upstream/wav2vec2/hubconf.py", line 69, in wav2vec2_local
    return wav2vec2_custom(*args, **kwargs)
  File "/data/anaconda3/envs/espnet_wo_cat_feats/lib/python3.8/site-packages/s3prl/upstream/wav2vec2/hubconf.py", line 65, in wav2vec2_custom
    return _UpstreamExpert(ckpt, **kwargs)
  File "/data/anaconda3/envs/espnet_wo_cat_feats/lib/python3.8/site-packages/s3prl/upstream/interfaces.py", line 30, in __call__
    instance = super().__call__(*args, **kwargs)
  File "/data/anaconda3/envs/espnet_wo_cat_feats/lib/python3.8/site-packages/s3prl/upstream/wav2vec2/expert.py", line 23, in __init__
    model, task_cfg = load_converted_model(ckpt)
  File "/data/anaconda3/envs/espnet_wo_cat_feats/lib/python3.8/site-packages/s3prl/upstream/wav2vec2/convert.py", line 31, in load_converted_model
    raise ValueError(
ValueError: /data/Sougata/Btech_intern/checkpoints/finetuned/xlsr53minilibrispeech/checkpoint_best.pt is not a valid checkpoint since the required key: task_cfg is missing
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/data/anaconda3/envs/espnet_wo_cat_feats/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data/anaconda3/envs/espnet_wo_cat_feats/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/Sougata/espnet/espnet2/tasks/abs_task.py", line 1219, in main_worker
    model = cls.build_model(args=args)
  File "/data/Sougata/espnet/espnet2/tasks/asr.py", line 529, in build_model
    frontend = frontend_class(**args.frontend_conf)
  File "/data/Sougata/espnet/espnet2/asr/frontend/s3prl.py", line 47, in __init__
    upstream = S3PRLUpstream(
  File "/data/anaconda3/envs/espnet_wo_cat_feats/lib/python3.8/site-packages/s3prl/nn/upstream.py", line 117, in __init__
    self.upstream = getattr(hub, name)(**upstream_conf)
  File "/data/anaconda3/envs/espnet_wo_cat_feats/lib/python3.8/site-packages/s3prl/upstream/wav2vec2/hubconf.py", line 69, in wav2vec2_local
    return wav2vec2_custom(*args, **kwargs)
  File "/data/anaconda3/envs/espnet_wo_cat_feats/lib/python3.8/site-packages/s3prl/upstream/wav2vec2/hubconf.py", line 65, in wav2vec2_custom
    return _UpstreamExpert(ckpt, **kwargs)
  File "/data/anaconda3/envs/espnet_wo_cat_feats/lib/python3.8/site-packages/s3prl/upstream/interfaces.py", line 30, in __call__
    instance = super().__call__(*args, **kwargs)
  File "/data/anaconda3/envs/espnet_wo_cat_feats/lib/python3.8/site-packages/s3prl/upstream/wav2vec2/expert.py", line 23, in __init__
    model, task_cfg = load_converted_model(ckpt)
  File "/data/anaconda3/envs/espnet_wo_cat_feats/lib/python3.8/site-packages/s3prl/upstream/wav2vec2/convert.py", line 31, in load_converted_model
    raise ValueError(
ValueError: /data/Sougata/Btech_intern/checkpoints/finetuned/xlsr53minilibrispeech/checkpoint_best.pt is not a valid checkpoint since the required key: task_cfg is missing
Traceback (most recent call last):
  File "/data/anaconda3/envs/espnet_wo_cat_feats/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/anaconda3/envs/espnet_wo_cat_feats/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/Sougata/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/data/Sougata/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/data/Sougata/espnet/espnet2/tasks/abs_task.py", line 1159, in main
    while not ProcessContext(processes, error_queues).join():
  File "/home/iitdh-ms/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 149, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 1
# Accounting: time=26 threads=1
# Ended (code 1) at Tue Dec 19 14:15:13 IST 2023, elapsed time 26 seconds
```
I have also the printed the model dictionary by running the following piece of code:-
```
import fairseq
model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task(['checkpoint_best.pt'])
print(model)
```
It gave me the following output:-
```
[Wav2VecCtc(
  (w2v_encoder): Wav2VecEncoder(
    (w2v_model): Wav2Vec2Model(
      (feature_extractor): ConvFeatureExtractionModel(
        (conv_layers): ModuleList(
          (0): Sequential(
            (0): Conv1d(1, 512, kernel_size=(10,), stride=(5,))
            (1): Dropout(p=0.0, inplace=False)
            (2): Sequential(
              (0): TransposeLast()
              (1): Fp32LayerNorm((512,), eps=1e-05, elementwise_affine=True)
              (2): TransposeLast()
            )
            (3): GELU(approximate='none')
          )
          (1-4): 4 x Sequential(
            (0): Conv1d(512, 512, kernel_size=(3,), stride=(2,))
            (1): Dropout(p=0.0, inplace=False)
            (2): Sequential(
              (0): TransposeLast()
              (1): Fp32LayerNorm((512,), eps=1e-05, elementwise_affine=True)
              (2): TransposeLast()
            )
            (3): GELU(approximate='none')
          )
          (5-6): 2 x Sequential(
            (0): Conv1d(512, 512, kernel_size=(2,), stride=(2,))
            (1): Dropout(p=0.0, inplace=False)
            (2): Sequential(
              (0): TransposeLast()
              (1): Fp32LayerNorm((512,), eps=1e-05, elementwise_affine=True)
              (2): TransposeLast()
            )
            (3): GELU(approximate='none')
          )
        )
      )
      (post_extract_proj): Linear(in_features=512, out_features=1024, bias=True)
      (dropout_input): Dropout(p=0.0, inplace=False)
      (dropout_features): Dropout(p=0.0, inplace=False)
      (quantizer): None
      (project_q): None
      (encoder): TransformerEncoder(
        (pos_conv): Sequential(
          (0): Conv1d(1024, 1024, kernel_size=(128,), stride=(1,), padding=(64,), groups=16)
          (1): SamePad()
          (2): GELU(approximate='none')
        )
        (layers): ModuleList(
          (0-23): 24 x TransformerSentenceEncoderLayer(
            (self_attn): MultiheadAttention(
              (dropout_module): FairseqDropout()
              (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
              (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
              (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
              (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (dropout1): Dropout(p=0.0, inplace=False)
            (dropout2): Dropout(p=0.1, inplace=False)
            (dropout3): Dropout(p=0.0, inplace=False)
            (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (fc1): Linear(in_features=1024, out_features=4096, bias=True)
            (fc2): Linear(in_features=4096, out_features=1024, bias=True)
            (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          )
        )
        (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
      )
      (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      (final_proj): None
    )
    (final_dropout): Dropout(p=0.0, inplace=False)
    (proj): Linear(in_features=1024, out_features=31, bias=True)
  )
)]
```
Here the model dictionary doesn't contain any key ```task_cfg```. So, how can the error be rectified?

**Comment by mukherjeesougata** [comment]
@sw005320 can you kindly please suggest how can I use my own finetuned model as a frontend?

**Comment by mukherjeesougata** [comment]
A gentle reminder for the same.

**Comment by fzyfky** [comment]
请问您问题解决了么，我也遇到了相似的问题
