### ISSUE TITLE
While trying to espnet2.bin.asr_inference import Speech2Text, "Namespace' object has no attribute 'token_list'"

### ISSUE THREAD

**Issue by hohosznta** [espnet/espnet#5634]
**Describe your question**

I'm trying to make predictions for my ASR model by putting an wav. file, it keeps getting an error. 

import torch
from espnet2.bin.asr_inference import Speech2Text
import argparse

import soundfile

# Define default values for config and model paths
config_path = "/content/espnet/egs2/config.yaml"
model_path = "/content/config.pth"

# Initialize Speech2Text with provided or default paths
speech2text = Speech2Text(config_path, model_path)
print(args)  # Check if 'token_list' is present in the printed output

# Read audio file
audio, rate = soundfile.read("speech.wav")

# Perform speech-to-text inference
result = speech2text(audio)

# Print or use the result as needed
print(result)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-38-1a69b1b7490d>](https://localhost:8080/#) in <cell line: 12>()
     10 print(args)
     11 # Initialize Speech2Text with provided or default paths
---> 12 speech2text = Speech2Text(config_path, model_path)
     13 print(args)  # Check if 'token_list' is present in the printed output
     14 

2 frames
[/content/espnet/espnet2/tasks/asr.py](https://localhost:8080/#) in build_model(cls, args)
    499     def build_model(cls, args: argparse.Namespace) -> ESPnetASRModel:
    500         assert check_argument_types()
--> 501         if isinstance(args.token_list, str):
    502             with open(args.token_list, encoding="utf-8") as f:
    503                 token_list = [line.rstrip() for line in f]

AttributeError: 'Namespace' object has no attribute 'token_list'

I tried making a token_list like this, 
!python /content/espnet/egs2/ss/asr1/pyscripts/utils/make_token_list_from_config.py /content/espnet/egs2/ss/asr1/conf/tuning/config.yaml,
 
but it keeps getting this error too. 

raceback (most recent call last):
  File "/content/espnet/egs2/ss/asr1/pyscripts/utils/make_token_list_from_config.py", line 33, in <module>
    main()
  File "/content/espnet/egs2/ss/asr1/pyscripts/utils/make_token_list_from_config.py", line 24, in main
    raise AttributeError("token_list is not found in config.")
AttributeError: token_list is not found in config.

What more can I try?

**Comment by hohosznta** [comment]
I just added token_list to .yaml and it worked!! got more errors but not related to this i think
