### ISSUE TITLE
don,t have model h5py when docker run example 

### ISSUE THREAD

**Issue by liuchenbaidu** [espnet/espnet#565]
don,t have model h5py when docker run example 
cd docker
sh -x run.sh --docker_gpu 0 --docker_egs ami/asr1 --docker_folders /export/corpora4/CHiME4/CHiME3 --dlayers 1 --ngpu 1 
raceback (most recent call last):
  File "/espnet/egs/ami/asr1/../../../utils/splitjson.py", line 20, in <module>
    from espnet.utils.cli_utils import get_commandline_args
  File "/espnet/espnet/utils/cli_utils.py", line 4, in <module>
    import h5py
ImportError: No module named h5py
Traceback (most recent call last):
  File "/espnet/egs/ami/asr1/../../../utils/splitjson.py", line 20, in <module>
    from espnet.utils.cli_utils import get_commandline_args
  File "/espnet/espnet/utils/cli_utils.py", line 4, in <module>
    import h5py
ImportError: No module named h5py

**Comment by liuchenbaidu** [comment]
using docker images ,the images don't have h5py

**Comment by sw005320** [comment]
This should be fixed by #568.
