### ISSUE TITLE
Slue voxpopuli 

### ISSUE THREAD

**Issue by maherr13** [espnet/espnet#5656]
Hello, 

Can you tell me how can i reproduce the results mentioned in the following directory [slue-voxpopuli](https://github.com/espnet/espnet/tree/master/egs2/slue-voxpopuli/slu1) ?? 

Thanks for your great work

**Comment by sw005320** [comment]
You can just specify the config files written in the README.md file when you run the experiments i.e., change https://github.com/espnet/espnet/blob/master/egs2/slue-voxpopuli/slu1/run.sh#L12 to the specific config file and `./run.sh`

**Comment by maherr13** [comment]
Thanks for the response,

I just did that for the first experiment, and it seems the dataset is not downloaded automatically. 
```
2024-02-11T18:49:40 (slu.sh:238:main) ./slu.sh --lang en --ngpu 1 --use_lm false --token_type bpe --gpu_inference true --nbpe 1000 --bpe_nlsyms FILL,SEP,PLACE,QUANT,ORG,WHEN,NORP,PERSON,LAW --feats_type raw --audio_format flac.ark --speed_perturb_factors 0.9 1.0 1.1 --max_wav_duration 30 --feats_normalize utterance_mvn --slu_config conf/tuning/train_asr_no_pretrain.yaml --inference_config conf/decode_asr.yaml --train_set train --valid_set devel --test_sets test devel --lm_train_text dump/raw/train_sp/text --lm_train_transcript dump/raw/train_sp/transcript --bpe_train_text data/train/text
2024-02-11T18:49:41 (slu.sh:447:main) Stage 1: Data preparation for data/train, data/devel, etc.
2024-02-11T18:49:41 (data.sh:17:main) local/data.sh 
stage 1: Download data to downloads
2024-02-11T18:49:41 (data.sh:45:main) stage 2: Data Preparation
/content/espnet/egs2/slue-voxpopuli/slu1/local/data_prep_original_slue_format.py:7: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd
Traceback (most recent call last):
  File "/content/espnet/egs2/slue-voxpopuli/slu1/local/data_prep_original_slue_format.py", line 47, in <module>
    transcript_df = pd.read_csv(os.path.join(root, dir_dict[x]), sep="\t")
  File "/content/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1024, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/content/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 618, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/content/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1618, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/content/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1878, in _make_engine
    self.handles = get_handle(
  File "/content/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'downloads/slue-voxpopuli_fine-tune.tsv'
```

I checked `db.sh` and I found that `VOXPOPULI` has the value downloads so I excepted everything was fine. 
Are there other steps I need to do to make `run.sh` automatically?

**Comment by sw005320** [comment]
It seems that this recipe does not include the downloading part.
You may need to do it manually.
@siddhu001, can you confirm it?

**Comment by maherr13** [comment]
I did download it manually and skipped stage 1 in the slu.sh and processed the data using the same script used in the bash script `data_prep_original_slue_format.py`
the pipeline broke in the next stage as its looking for `spk2utt` file
```
/content/espnet/egs2/slue-voxpopuli/slu1
2024-02-12T17:26:43 (slu.sh:238:main) ./slu.sh --lang en --ngpu 1 --use_lm false --token_type bpe --gpu_inference true --nbpe 1000 --bpe_nlsyms FILL,SEP,PLACE,QUANT,ORG,WHEN,NORP,PERSON,LAW --feats_type raw --audio_format flac.ark --speed_perturb_factors 0.9 1.0 1.1 --max_wav_duration 30 --feats_normalize utterance_mvn --slu_config conf/train_asr.yaml --inference_config conf/decode_asr.yaml --train_set train --valid_set devel --test_sets test devel --lm_train_text dump/raw/train_sp/text --lm_train_transcript dump/raw/train_sp/transcript --bpe_train_text data/train/text
[INFO] /content/espnet/egs2/slue-voxpopuli/slu1/../../../tools/activate_python.sh is not present
2024-02-12T17:26:43 (slu.sh:447:main) Stage 1: Data preparation for data/train, data/devel, etc.
2024-02-12T17:26:43 (slu.sh:454:main) Stage 2: Speed perturbation: data/train -> data/train_sp
scripts/utils/perturb_data_dir_speed.sh: line 60: data/train/spk2utt: No such file or directory
```

I check the processing output folder and i found that they output three file `spk2utt` is not one of them.
![image](https://github.com/espnet/espnet/assets/83926003/b09df5d1-f46a-4ebf-9bf4-053026f80539)

**Comment by siddhu001** [comment]
Yes, recipe does not include downloading data part.

You should not skip stage1. You basically need to download data from here: https://huggingface.co/datasets/asapp/slue/tree/main/data/voxceleb, mention the path of downloaded data as "VOXCELEB" in db.sh. Then run stage 1 so to convert data into kaldi format which can then be used in the next stages.

**Comment by maherr13** [comment]
Thanks for the tips and sorry for bothering you. 

I did what you mentioned and I got the following error for another missing file. 
```
/content/espnet/egs2/slue-voxpopuli/slu1
2024-02-12T20:49:23 (slu.sh:238:main) ./slu.sh --lang en --ngpu 1 --use_lm false --token_type bpe --gpu_inference true --nbpe 1000 --bpe_nlsyms FILL,SEP,PLACE,QUANT,ORG,WHEN,NORP,PERSON,LAW --feats_type raw --audio_format flac.ark --speed_perturb_factors 0.9 1.0 1.1 --max_wav_duration 30 --feats_normalize utterance_mvn --slu_config conf/train_asr.yaml --inference_config conf/decode_asr.yaml --train_set train --valid_set devel --test_sets test devel --lm_train_text dump/raw/train_sp/text --lm_train_transcript dump/raw/train_sp/transcript --bpe_train_text data/train/text
2024-02-12T20:49:24 (slu.sh:447:main) Stage 1: Data preparation for data/train, data/devel, etc.
2024-02-12T20:49:24 (data.sh:17:main) local/data.sh 
stage 1: Download data to /content/slue-voxpopuli
2024-02-12T20:49:24 (data.sh:45:main) stage 2: Data Preparation
/content/espnet/egs2/slue-voxpopuli/slu1/local/data_prep_original_slue_format.py:7: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd
Missing Entities {'EVENT', 'LANGUAGE', 'WORK_OF_ART', 'FAC', 'PRODUCT'}
Missing Count 133
utils/validate_data_dir.sh: Successfully validated data-directory data/test
utils/validate_data_dir.sh: Successfully validated data-directory data/devel
utils/validate_data_dir.sh: Successfully validated data-directory data/train
2024-02-12T20:49:26 (data.sh:69:main) Successfully finished. [elapsed=2s]
2024-02-12T20:49:26 (slu.sh:454:main) Stage 2: Speed perturbation: data/train -> data/train_sp
text
utt2lang
transcript
scripts/utils/perturb_data_dir_speed.sh: generated speed-perturbed version of data in data/train, in data/train_sp0.9
fix_data_dir.sh: kept all 5000 utterances.
fix_data_dir.sh: old files are kept in data/train_sp0.9/.backup
utils/validate_data_dir.sh: Successfully validated data-directory data/train_sp0.9
text
utt2lang
transcript
scripts/utils/perturb_data_dir_speed.sh: generated speed-perturbed version of data in data/train, in data/train_sp1.1
fix_data_dir.sh: kept all 5000 utterances.
fix_data_dir.sh: old files are kept in data/train_sp1.1/.backup
utils/validate_data_dir.sh: Successfully validated data-directory data/train_sp1.1
utils/combine_data.sh --extra_files transcript data/train_sp data/train_sp0.9 data/train data/train_sp1.1
utils/combine_data.sh: combined utt2uniq
utils/combine_data.sh [info]: not combining segments as it does not exist
utils/combine_data.sh: combined utt2spk
utils/combine_data.sh [info]: not combining utt2lang as it does not exist
utils/combine_data.sh [info]: not combining utt2dur as it does not exist
utils/combine_data.sh [info]: not combining utt2num_frames as it does not exist
utils/combine_data.sh [info]: not combining reco2dur as it does not exist
utils/combine_data.sh [info]: not combining feats.scp as it does not exist
utils/combine_data.sh: combined text
utils/combine_data.sh [info]: not combining cmvn.scp as it does not exist
utils/combine_data.sh [info]: not combining vad.scp as it does not exist
utils/combine_data.sh [info]: not combining reco2file_and_channel as it does not exist
utils/combine_data.sh: combined wav.scp
utils/combine_data.sh [info]: not combining spk2gender as it does not exist
utils/combine_data.sh [info]: not combining transcript as it does not exist
fix_data_dir.sh: kept all 15000 utterances.
fix_data_dir.sh: old files are kept in data/train_sp/.backup
Traceback (most recent call last):
  File "/content/espnet/egs2/slue-voxpopuli/slu1/pyscripts/utils/remove_duplicate_keys.py", line 49, in <module>
    main()
  File "/content/espnet/egs2/slue-voxpopuli/slu1/pyscripts/utils/remove_duplicate_keys.py", line 45, in main
    read_2columns_text(args.index_file)
  File "/content/espnet/egs2/slue-voxpopuli/slu1/pyscripts/utils/remove_duplicate_keys.py", line 23, in read_2columns_text
    with Path(path).open("r", encoding="utf-8") as f:
  File "/content/espnet/tools/anaconda/envs/espnet/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/content/espnet/tools/anaconda/envs/espnet/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'data/train_sp/transcript'
```

here is the data directory
![image](https://github.com/espnet/espnet/assets/83926003/8f76530b-636c-4291-aa62-1f79e84bb12c)

**Comment by siddhu001** [comment]
Hi,

I looked into this and  I discovered a minor bug related to speed perturbation when not using the transcript. To address this issue, I've opened a small PR at https://github.com/espnet/espnet/pull/5671, which should resolve the issue. Thanks for letting me know!

**Comment by sw005320** [comment]
Thanks @maherr13 for pointing out the issue!
Thanks @siddhu001 for fixing it!

**Comment by maherr13** [comment]
Awesome, 

I tried the pipeline and it worked fine, now I want to try these approaches in a different language (Arabic), would changing the dataset into Arabic (same format), and replacing the base models with Arabic models do the trick? or do I need to do further work?
