### ISSUE TITLE
I am having issues with tts implementation

### ISSUE THREAD

**Issue by Waggles77** [espnet/espnet#5798]
What I have done
1. conda create --name espnet python=3.10
2. conda activate espnet
3. git clone git clone https://github.com/espnet/espnet.git
4. pip install -q espnet==202308 pypinyin==0.44.0 parallel_wavegan==0.5.4 gdown==4.4.0 espnet_model_zoo
5. pip install pyopenjtalk

This is the code I ran

lang = 'Japanese'
tag = 'mio/amadeus'
vocoder_tag = 'none'

from espnet2.bin.tts_inference import Text2Speech
from espnet2.utils.types import str_or_none

text2speech = Text2Speech.from_pretrained(
    model_tag=str_or_none(tag),
    vocoder_tag=str_or_none(vocoder_tag),
    device="cuda",
    # Only for Tacotron 2 & Transformer
    threshold=0.5,
    # Only for Tacotron 2
    minlenratio=0.0,
    maxlenratio=10.0,
    use_att_constraint=False,
    backward_window=1,
    forward_window=3,
    # Only for FastSpeech & FastSpeech2 & VITS
    speed_control_alpha=1.0,
    # Only for VITS
    noise_scale=0.333,
    noise_scale_dur=0.333,
)

This is the error message

C:\Users\User\anaconda3\python.exe C:\Users\User\PycharmProjects\pythonProject\Arona\espnet\Amadeus.py 
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\pythonProject\Arona\espnet\Amadeus.py", line 6, in <module>
    from espnet2.bin.tts_inference import Text2Speech
  File "C:\Users\User\PycharmProjects\pythonProject\Arona\espnet\espnet2\bin\tts_inference.py", line 21, in <module>
    from espnet2.tasks.tts import TTSTask
  File "C:\Users\User\PycharmProjects\pythonProject\Arona\espnet\espnet2\tasks\tts.py", line 22, in <module>
    from espnet2.train.preprocessor import CommonPreprocessor
  File "C:\Users\User\PycharmProjects\pythonProject\Arona\espnet\espnet2\train\preprocessor.py", line 17, in <module>
    from espnet2.text.cleaner import TextCleaner
  File "C:\Users\User\PycharmProjects\pythonProject\Arona\espnet\espnet2\text\cleaner.py", line 3, in <module>
    import tacotron_cleaner.cleaners
ModuleNotFoundError: No module named 'tacotron_cleaner'

Process finished with exit code 1

how do i resolve this?

**Comment by sw005320** [comment]
Thanks for your report.

@kan-bayashi, can you check this?

**Comment by Waggles77** [comment]
> Thanks for your report.
> 
> @kan-bayashi, can you check this?

I tried changing my environment to one that uses python 3.8 and ran the script after uninstalling and reinstalling the files stated above in addition to IPython and a new kind of error message appeared
C:\Users\User\anaconda3\envs\espnet\python.exe C:\Users\User\PycharmProjects\pythonProject\espnet\test.py 
C:\Users\User\anaconda3\envs\espnet\lib\site-packages\typeguard\__init__.py:1016: UserWarning: no type annotations present -- not typechecking espnet2.fileio.score_scp.XMLReader.__init__
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
C:\Users\User\anaconda3\envs\espnet\lib\site-packages\typeguard\__init__.py:1016: UserWarning: no type annotations present -- not typechecking espnet2.fileio.score_scp.MIDReader.__init__
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
C:\Users\User\anaconda3\envs\espnet\lib\site-packages\typeguard\__init__.py:1016: UserWarning: no type annotations present -- not typechecking espnet2.fileio.score_scp.SingingScoreReader.__init__
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
C:\Users\User\anaconda3\envs\espnet\lib\site-packages\typeguard\__init__.py:1016: UserWarning: no type annotations present -- not typechecking espnet2.train.dataset.AdapterForSoundScpReader.__init__
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
C:\Users\User\anaconda3\envs\espnet\lib\site-packages\typeguard\__init__.py:1016: UserWarning: no type annotations present -- not typechecking espnet2.train.dataset.AdapterForSingingScoreScpReader.__init__
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
C:\Users\User\anaconda3\envs\espnet\lib\site-packages\typeguard\__init__.py:1016: UserWarning: no type annotations present -- not typechecking espnet2.train.dataset.AdapterForLabelScpReader.__init__
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))
Fetching 28 files: 100%|##########| 28/28 [00:00<?, ?it/s]
C:\Users\User\PycharmProjects\pythonProject\espnet\espnet2\gan_tts\vits\monotonic_align\__init__.py:19: UserWarning: Cython version is not available. Fallback to 'EXPERIMETAL' numba version. If you want to use the cython version, please build it as follows: `cd espnet2/gan_tts/vits/monotonic_align; python setup.py build_ext --inplace`
  warnings.warn(
WARNING:root:It seems weight norm is not applied in the pretrained model but the current model uses it. To keep the compatibility, we remove the norm from the current model. This may cause unexpected behavior due to the parameter mismatch in finetuning. To avoid this issue, please change the following parameters in config to false:
 - discriminator_params.follow_official_norm
 - discriminator_params.scale_discriminator_params.use_weight_norm
 - discriminator_params.scale_discriminator_params.use_spectral_norm

See also:
 - https://github.com/espnet/espnet/pull/5240
 - https://github.com/espnet/espnet/pull/5249

Process finished with exit code 0

**Comment by kan-bayashi** [comment]
This is warning, not error. You can ignore it.

**Comment by Waggles77** [comment]
> This is warning, not error. You can ignore it.

how do I get or play the soundfile?
