### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for ESPnetASRModel

### ISSUE THREAD

**Issue by ponymhc** [espnet/espnet#5812]
I used the Lora fine-tuning configure from the Aishell recipe to tune Whisper.  After I finished training, when I tried to use the Speech2Text class to infer any audio:

> from espnet2.bin.asr_inference import Speech2Text
> s2t = Speech2Text(asr_model_file='exp/asr_train_asr_whisper_small_lora_finetune_raw_zh_whisper_multilingual/valid.acc.best.pth',
>                   asr_train_config='exp/asr_train_asr_whisper_small_lora_finetune_raw_zh_whisper_multilingual/config.yaml',
>                   beam_size=10,
>                 ctc_weight=0.0,
>                 lm_weight=0.0,
>                 maxlenratio=0.3,
>                 minlenratio=0.0,
>                 penalty=0.0)

I encountered the following error:

> RuntimeError: Error(s) in loading state_dict for ESPnetASRModel:
> Unexpected key(s) in state_dict: "encoder.encoders.blocks.0.attn.query.lora_A", "encoder.encoders.blocks.0.attn.query.lora_B".....

Do I need to manually merge the Lora adapter into the model to use this interface for inference?

**Comment by sw005320** [comment]
@simpleoier, can you answer this?

**Comment by simpleoier** [comment]
Hi @ponymhc , thanks for reporting the issue!
However, it is a bit difficult to understand your situation. Can you provide more context? For example, you listed the errors about `unexpected keys in state_dict`. What about the `expected keys for the model`?

**Comment by ponymhc** [comment]
Hi, @simpleoier , thank you for your reply. I fine-tuned the Whisper model using the configure below:

```
normalize: null

encoder: whisper
encoder_conf:
    whisper_model: small
    dropout_rate: 0.0
    use_specaug: true
    specaug_conf:
        apply_time_warp: true
        time_warp_window: 5
        time_warp_mode: bicubic
        apply_freq_mask: true
        freq_mask_width_range:
        - 0
        - 40
        num_freq_mask: 2
        apply_time_mask: true
        time_mask_width_ratio_range:
        - 0.
        - 0.12
        num_time_mask: 5


decoder: whisper
decoder_conf:
    whisper_model: small
    dropout_rate: 0.0

preprocessor: default
preprocessor_conf:
    whisper_language: "zh"
    whisper_task: "transcribe"

model_conf:
    ctc_weight: 0.0
    lsm_weight: 0.1
    length_normalized_loss: false
    extract_feats_in_collect_stats: false
    sym_sos: "<|startoftranscript|>"
    sym_eos: "<|endoftext|>"
    # do_pad_trim: true         # should be set when doing zero-shot inference

frontend: null
input_size: 1                   # to prevent build_model() from complaining

seed: 2022
log_interval: 100
num_att_plot: 0
num_workers: 4
sort_in_batch: descending       # how to sort data in making batch
sort_batch: descending          # how to sort created batches
batch_type: numel
batch_bins: 9000000            # good for 8 * RTX 3090 24G
accum_grad: 2
max_epoch: 10
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 5

use_amp: true
cudnn_deterministic: false
cudnn_benchmark: false

# LoRA finetune related
use_adapter: true
adapter: lora
freeze_param:
- encoder
- decoder
adapter_conf:
    rank: 4
    alpha: 8
    dropout_rate: 0.05
    target_modules:
    - query
    - key
    - value
    - attn.out

optim: adamw
grad_clip: 1.0
optim_conf:
    lr: 5.0e-04
    weight_decay: 0.01
    betas:
    - 0.9
    - 0.99
    eps: 1.0e-06
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 1500
```
After I finished training, I used the following code for inference:
```
from espnet2.bin.asr_inference import Speech2Text
import soundfile

s2t = Speech2Text(asr_model_file='exp/asr_train_asr_whisper_small_lora_finetune_raw_zh_whisper_multilingual/valid.acc.best.pth',
                  asr_train_config='exp/asr_train_asr_whisper_small_lora_finetune_raw_zh_whisper_multilingual/config.yaml',
                  beam_size=10,
                ctc_weight=0.0,
                lm_weight=0.0,
                maxlenratio=0.3,
                minlenratio=0.0,
                penalty=0.0)
fs = 16000
speech, rate = soundfile.read('downloads/data_aishell/wav/dev/S0724/BAC009S0724W0121.wav')
assert rate == fs, "mismatch in sampling rate"
nbests = s2t(speech)
text, *_ = nbests[0]
print(text)
```
And then encountered the following error:
```
Traceback (most recent call last):
  File "espnet/egs2/aishell/asr1/tmp.py", line 4, in <module>
    s2t = Speech2Text(asr_model_file='exp/asr_train_asr_whisper_small_lora_finetune_raw_zh_whisper_multilingual/valid.acc.best.pth',
  File "miniconda3/envs/cal/lib/python3.10/site-packages/espnet2/bin/asr_inference.py", line 136, in __init__
    asr_model, asr_train_args = task.build_model_from_file(
  File "miniconda3/envs/cal/lib/python3.10/site-packages/espnet2/tasks/abs_task.py", line 2068, in build_model_from_file
    model.load_state_dict(
  File "miniconda3/envs/cal/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ESPnetASRModel:
        Unexpected key(s) in state_dict: "encoder.encoders.blocks.0.attn.query.lora_A", "encoder.encoders.blocks.0.attn.query.lora_B", "encoder.encoders.blocks.0.attn.key.lora_A", "encoder.encoders.blocks.0.attn.key.lora_B", "encoder.encoders.blocks.0.attn.value.lora_A", "encoder.encoders.blocks.0.attn.value.lora_B", "encoder.encoders.blocks.0.attn.out.lora_A", "encoder.encoders.blocks.0.attn.out.lora_B", "encoder.encoders.blocks.1.attn.query.lora_A", "encoder.encoders.blocks.1.attn.query.lora_B", "encoder.encoders.blocks.1.attn.key.lora_A", "encoder.encoders.blocks.1.attn.key.lora_B", "encoder.encoders.blocks.1.attn.value.lora_A", "encoder.encoders.blocks.1.attn.value.lora_B", "encoder.encoders.blocks.1.attn.out.lora_A", "encoder.encoders.blocks.1.attn.out.lora_B", "encoder.encoders.blocks.2.attn.query.lora_A", "encoder.encoders.blocks.2.attn.query.lora_B", "encoder.encoders.blocks.2.attn.key.lora_A", "encoder.encoders.blocks.2.attn.key.lora_B", "encoder.encoders.blocks.2.attn.value.lora_A", "encoder.encoders.blocks.2.attn.value.lora_B", "encoder.encoders.blocks.2.attn.out.lora_A", "encoder.encoders.blocks.2.attn.out.lora_B", "encoder.encoders.blocks.3.attn.query.lora_A", "encoder.encoders.blocks.3.attn.query.lora_B", "encoder.encoders.blocks.3.attn.key.lora_A", "encoder.encoders.blocks.3.attn.key.lora_B", "encoder.encoders.blocks.3.attn.value.lora_A", "encoder.encoders.blocks.3.attn.value.lora_B", "encoder.encoders.blocks.3.attn.out.lora_A", "encoder.encoders.blocks.3.attn.out.lora_B", "encoder.encoders.blocks.4.attn.query.lora_A", "encoder.encoders.blocks.4.attn.query.lora_B", "encoder.encoders.blocks.4.attn.key.lora_A", "encoder.encoders.blocks.4.attn.key.lora_B", "encoder.encoders.blocks.4.attn.value.lora_A", "encoder.encoders.blocks.4.attn.value.lora_B", "encoder.encoders.blocks.4.attn.out.lora_A", "encoder.encoders.blocks.4.attn.out.lora_B", "encoder.encoders.blocks.5.attn.query.lora_A", "encoder.encoders.blocks.5.attn.query.lora_B", "encoder.encoders.blocks.5.attn.key.lora_A", "encoder.encoders.blocks.5.attn.key.lora_B", "encoder.encoders.blocks.5.attn.value.lora_A", "encoder.encoders.blocks.5.attn.value.lora_B", "encoder.encoders.blocks.5.attn.out.lora_A", "encoder.encoders.blocks.5.attn.out.lora_B", "encoder.encoders.blocks.6.attn.query.lora_A", "encoder.encoders.blocks.6.attn.query.lora_B", "encoder.encoders.blocks.6.attn.key.lora_A", "encoder.encoders.blocks.6.attn.key.lora_B", "encoder.encoders.blocks.6.attn.value.lora_A", "encoder.encoders.blocks.6.attn.value.lora_B", "encoder.encoders.blocks.6.attn.out.lora_A", "encoder.encoders.blocks.6.attn.out.lora_B", "encoder.encoders.blocks.7.attn.query.lora_A", "encoder.encoders.blocks.7.attn.query.lora_B", "encoder.encoders.blocks.7.attn.key.lora_A", "encoder.encoders.blocks.7.attn.key.lora_B", "encoder.encoders.blocks.7.attn.value.lora_A", "encoder.encoders.blocks.7.attn.value.lora_B", "encoder.encoders.blocks.7.attn.out.lora_A", "encoder.encoders.blocks.7.attn.out.lora_B", "encoder.encoders.blocks.8.attn.query.lora_A", "encoder.encoders.blocks.8.attn.query.lora_B", "encoder.encoders.blocks.8.attn.key.lora_A", "encoder.encoders.blocks.8.attn.key.lora_B", "encoder.encoders.blocks.8.attn.value.lora_A", "encoder.encoders.blocks.8.attn.value.lora_B", "encoder.encoders.blocks.8.attn.out.lora_A", "encoder.encoders.blocks.8.attn.out.lora_B", "encoder.encoders.blocks.9.attn.query.lora_A", "encoder.encoders.blocks.9.attn.query.lora_B", "encoder.encoders.blocks.9.attn.key.lora_A", "encoder.encoders.blocks.9.attn.key.lora_B", "encoder.encoders.blocks.9.attn.value.lora_A", "encoder.encoders.blocks.9.attn.value.lora_B", "encoder.encoders.blocks.9.attn.out.lora_A", "encoder.encoders.blocks.9.attn.out.lora_B", "encoder.encoders.blocks.10.attn.query.lora_A", "encoder.encoders.blocks.10.attn.query.lora_B", "encoder.encoders.blocks.10.attn.key.lora_A", "encoder.encoders.blocks.10.attn.key.lora_B", "encoder.encoders.blocks.10.attn.value.lora_A", "encoder.encoders.blocks.10.attn.value.lora_B", "encoder.encoders.blocks.10.attn.out.lora_A", "encoder.encoders.blocks.10.attn.out.lora_B", "encoder.encoders.blocks.11.attn.query.lora_A", "encoder.encoders.blocks.11.attn.query.lora_B", "encoder.encoders.blocks.11.attn.key.lora_A", "encoder.encoders.blocks.11.attn.key.lora_B", "encoder.encoders.blocks.11.attn.value.lora_A", "encoder.encoders.blocks.11.attn.value.lora_B", "encoder.encoders.blocks.11.attn.out.lora_A", "encoder.encoders.blocks.11.attn.out.lora_B", "decoder.decoders.blocks.0.attn.query.lora_A", "decoder.decoders.blocks.0.attn.query.lora_B", "decoder.decoders.blocks.0.attn.key.lora_A", "decoder.decoders.blocks.0.attn.key.lora_B", "decoder.decoders.blocks.0.attn.value.lora_A", "decoder.decoders.blocks.0.attn.value.lora_B", "decoder.decoders.blocks.0.attn.out.lora_A", "decoder.decoders.blocks.0.attn.out.lora_B", "decoder.decoders.blocks.0.cross_attn.query.lora_A", "decoder.decoders.blocks.0.cross_attn.query.lora_B", "decoder.decoders.blocks.0.cross_attn.key.lora_A", "decoder.decoders.blocks.0.cross_attn.key.lora_B", "decoder.decoders.blocks.0.cross_attn.value.lora_A", "decoder.decoders.blocks.0.cross_attn.value.lora_B", "decoder.decoders.blocks.0.cross_attn.out.lora_A", "decoder.decoders.blocks.0.cross_attn.out.lora_B", "decoder.decoders.blocks.1.attn.query.lora_A", "decoder.decoders.blocks.1.attn.query.lora_B", "decoder.decoders.blocks.1.attn.key.lora_A", "decoder.decoders.blocks.1.attn.key.lora_B", "decoder.decoders.blocks.1.attn.value.lora_A", "decoder.decoders.blocks.1.attn.value.lora_B", "decoder.decoders.blocks.1.attn.out.lora_A", "decoder.decoders.blocks.1.attn.out.lora_B", "decoder.decoders.blocks.1.cross_attn.query.lora_A", "decoder.decoders.blocks.1.cross_attn.query.lora_B", "decoder.decoders.blocks.1.cross_attn.key.lora_A", "decoder.decoders.blocks.1.cross_attn.key.lora_B", "decoder.decoders.blocks.1.cross_attn.value.lora_A", "decoder.decoders.blocks.1.cross_attn.value.lora_B", "decoder.decoders.blocks.1.cross_attn.out.lora_A", "decoder.decoders.blocks.1.cross_attn.out.lora_B", "decoder.decoders.blocks.2.attn.query.lora_A", "decoder.decoders.blocks.2.attn.query.lora_B", "decoder.decoders.blocks.2.attn.key.lora_A", "decoder.decoders.blocks.2.attn.key.lora_B", "decoder.decoders.blocks.2.attn.value.lora_A", "decoder.decoders.blocks.2.attn.value.lora_B", "decoder.decoders.blocks.2.attn.out.lora_A", "decoder.decoders.blocks.2.attn.out.lora_B", "decoder.decoders.blocks.2.cross_attn.query.lora_A", "decoder.decoders.blocks.2.cross_attn.query.lora_B", "decoder.decoders.blocks.2.cross_attn.key.lora_A", "decoder.decoders.blocks.2.cross_attn.key.lora_B", "decoder.decoders.blocks.2.cross_attn.value.lora_A", "decoder.decoders.blocks.2.cross_attn.value.lora_B", "decoder.decoders.blocks.2.cross_attn.out.lora_A", "decoder.decoders.blocks.2.cross_attn.out.lora_B", "decoder.decoders.blocks.3.attn.query.lora_A", "decoder.decoders.blocks.3.attn.query.lora_B", "decoder.decoders.blocks.3.attn.key.lora_A", "decoder.decoders.blocks.3.attn.key.lora_B", "decoder.decoders.blocks.3.attn.value.lora_A", "decoder.decoders.blocks.3.attn.value.lora_B", "decoder.decoders.blocks.3.attn.out.lora_A", "decoder.decoders.blocks.3.attn.out.lora_B", "decoder.decoders.blocks.3.cross_attn.query.lora_A", "decoder.decoders.blocks.3.cross_attn.query.lora_B", "decoder.decoders.blocks.3.cross_attn.key.lora_A", "decoder.decoders.blocks.3.cross_attn.key.lora_B", "decoder.decoders.blocks.3.cross_attn.value.lora_A", "decoder.decoders.blocks.3.cross_attn.value.lora_B", "decoder.decoders.blocks.3.cross_attn.out.lora_A", "decoder.decoders.blocks.3.cross_attn.out.lora_B", "decoder.decoders.blocks.4.attn.query.lora_A", "decoder.decoders.blocks.4.attn.query.lora_B", "decoder.decoders.blocks.4.attn.key.lora_A", "decoder.decoders.blocks.4.attn.key.lora_B", "decoder.decoders.blocks.4.attn.value.lora_A", "decoder.decoders.blocks.4.attn.value.lora_B", "decoder.decoders.blocks.4.attn.out.lora_A", "decoder.decoders.blocks.4.attn.out.lora_B", "decoder.decoders.blocks.4.cross_attn.query.lora_A", "decoder.decoders.blocks.4.cross_attn.query.lora_B", "decoder.decoders.blocks.4.cross_attn.key.lora_A", "decoder.decoders.blocks.4.cross_attn.key.lora_B", "decoder.decoders.blocks.4.cross_attn.value.lora_A", "decoder.decoders.blocks.4.cross_attn.value.lora_B", "decoder.decoders.blocks.4.cross_attn.out.lora_A", "decoder.decoders.blocks.4.cross_attn.out.lora_B", "decoder.decoders.blocks.5.attn.query.lora_A", "decoder.decoders.blocks.5.attn.query.lora_B", "decoder.decoders.blocks.5.attn.key.lora_A", "decoder.decoders.blocks.5.attn.key.lora_B", "decoder.decoders.blocks.5.attn.value.lora_A", "decoder.decoders.blocks.5.attn.value.lora_B", "decoder.decoders.blocks.5.attn.out.lora_A", "decoder.decoders.blocks.5.attn.out.lora_B", "decoder.decoders.blocks.5.cross_attn.query.lora_A", "decoder.decoders.blocks.5.cross_attn.query.lora_B", "decoder.decoders.blocks.5.cross_attn.key.lora_A", "decoder.decoders.blocks.5.cross_attn.key.lora_B", "decoder.decoders.blocks.5.cross_attn.value.lora_A", "decoder.decoders.blocks.5.cross_attn.value.lora_B", "decoder.decoders.blocks.5.cross_attn.out.lora_A", "decoder.decoders.blocks.5.cross_attn.out.lora_B", "decoder.decoders.blocks.6.attn.query.lora_A", "decoder.decoders.blocks.6.attn.query.lora_B", "decoder.decoders.blocks.6.attn.key.lora_A", "decoder.decoders.blocks.6.attn.key.lora_B", "decoder.decoders.blocks.6.attn.value.lora_A", "decoder.decoders.blocks.6.attn.value.lora_B", "decoder.decoders.blocks.6.attn.out.lora_A", "decoder.decoders.blocks.6.attn.out.lora_B", "decoder.decoders.blocks.6.cross_attn.query.lora_A", "decoder.decoders.blocks.6.cross_attn.query.lora_B", "decoder.decoders.blocks.6.cross_attn.key.lora_A", "decoder.decoders.blocks.6.cross_attn.key.lora_B", "decoder.decoders.blocks.6.cross_attn.value.lora_A", "decoder.decoders.blocks.6.cross_attn.value.lora_B", "decoder.decoders.blocks.6.cross_attn.out.lora_A", "decoder.decoders.blocks.6.cross_attn.out.lora_B", "decoder.decoders.blocks.7.attn.query.lora_A", "decoder.decoders.blocks.7.attn.query.lora_B", "decoder.decoders.blocks.7.attn.key.lora_A", "decoder.decoders.blocks.7.attn.key.lora_B", "decoder.decoders.blocks.7.attn.value.lora_A", "decoder.decoders.blocks.7.attn.value.lora_B", "decoder.decoders.blocks.7.attn.out.lora_A", "decoder.decoders.blocks.7.attn.out.lora_B", "decoder.decoders.blocks.7.cross_attn.query.lora_A", "decoder.decoders.blocks.7.cross_attn.query.lora_B", "decoder.decoders.blocks.7.cross_attn.key.lora_A", "decoder.decoders.blocks.7.cross_attn.key.lora_B", "decoder.decoders.blocks.7.cross_attn.value.lora_A", "decoder.decoders.blocks.7.cross_attn.value.lora_B", "decoder.decoders.blocks.7.cross_attn.out.lora_A", "decoder.decoders.blocks.7.cross_attn.out.lora_B", "decoder.decoders.blocks.8.attn.query.lora_A", "decoder.decoders.blocks.8.attn.query.lora_B", "decoder.decoders.blocks.8.attn.key.lora_A", "decoder.decoders.blocks.8.attn.key.lora_B", "decoder.decoders.blocks.8.attn.value.lora_A", "decoder.decoders.blocks.8.attn.value.lora_B", "decoder.decoders.blocks.8.attn.out.lora_A", "decoder.decoders.blocks.8.attn.out.lora_B", "decoder.decoders.blocks.8.cross_attn.query.lora_A", "decoder.decoders.blocks.8.cross_attn.query.lora_B", "decoder.decoders.blocks.8.cross_attn.key.lora_A", "decoder.decoders.blocks.8.cross_attn.key.lora_B", "decoder.decoders.blocks.8.cross_attn.value.lora_A", "decoder.decoders.blocks.8.cross_attn.value.lora_B", "decoder.decoders.blocks.8.cross_attn.out.lora_A", "decoder.decoders.blocks.8.cross_attn.out.lora_B", "decoder.decoders.blocks.9.attn.query.lora_A", "decoder.decoders.blocks.9.attn.query.lora_B", "decoder.decoders.blocks.9.attn.key.lora_A", "decoder.decoders.blocks.9.attn.key.lora_B", "decoder.decoders.blocks.9.attn.value.lora_A", "decoder.decoders.blocks.9.attn.value.lora_B", "decoder.decoders.blocks.9.attn.out.lora_A", "decoder.decoders.blocks.9.attn.out.lora_B", "decoder.decoders.blocks.9.cross_attn.query.lora_A", "decoder.decoders.blocks.9.cross_attn.query.lora_B", "decoder.decoders.blocks.9.cross_attn.key.lora_A", "decoder.decoders.blocks.9.cross_attn.key.lora_B", "decoder.decoders.blocks.9.cross_attn.value.lora_A", "decoder.decoders.blocks.9.cross_attn.value.lora_B", "decoder.decoders.blocks.9.cross_attn.out.lora_A", "decoder.decoders.blocks.9.cross_attn.out.lora_B", "decoder.decoders.blocks.10.attn.query.lora_A", "decoder.decoders.blocks.10.attn.query.lora_B", "decoder.decoders.blocks.10.attn.key.lora_A", "decoder.decoders.blocks.10.attn.key.lora_B", "decoder.decoders.blocks.10.attn.value.lora_A", "decoder.decoders.blocks.10.attn.value.lora_B", "decoder.decoders.blocks.10.attn.out.lora_A", "decoder.decoders.blocks.10.attn.out.lora_B", "decoder.decoders.blocks.10.cross_attn.query.lora_A", "decoder.decoders.blocks.10.cross_attn.query.lora_B", "decoder.decoders.blocks.10.cross_attn.key.lora_A", "decoder.decoders.blocks.10.cross_attn.key.lora_B", "decoder.decoders.blocks.10.cross_attn.value.lora_A", "decoder.decoders.blocks.10.cross_attn.value.lora_B", "decoder.decoders.blocks.10.cross_attn.out.lora_A", "decoder.decoders.blocks.10.cross_attn.out.lora_B", "decoder.decoders.blocks.11.attn.query.lora_A", "decoder.decoders.blocks.11.attn.query.lora_B", "decoder.decoders.blocks.11.attn.key.lora_A", "decoder.decoders.blocks.11.attn.key.lora_B", "decoder.decoders.blocks.11.attn.value.lora_A", "decoder.decoders.blocks.11.attn.value.lora_B", "decoder.decoders.blocks.11.attn.out.lora_A", "decoder.decoders.blocks.11.attn.out.lora_B", "decoder.decoders.blocks.11.cross_attn.query.lora_A", "decoder.decoders.blocks.11.cross_attn.query.lora_B", "decoder.decoders.blocks.11.cross_attn.key.lora_A", "decoder.decoders.blocks.11.cross_attn.key.lora_B", "decoder.decoders.blocks.11.cross_attn.value.lora_A", "decoder.decoders.blocks.11.cross_attn.value.lora_B", "decoder.decoders.blocks.11.cross_attn.out.lora_A", "decoder.decoders.blocks.11.cross_attn.out.lora_B".
```
is the issue caused by the failure to initialize the adapter from the configuration during the execution of build_model_from_file?

**Comment by simpleoier** [comment]
Hi @ponymhc , it seems that lora adapter was not properly initialized during inference. Did you modify the codebase by yourself?

**Comment by ponymhc** [comment]
I did not modify the code, to properly begin training, I only modified the training configuration, as mentioned in this: https://github.com/espnet/espnet/issues/5779.

**Comment by simpleoier** [comment]
@ponymhc , can you check if this [line](https://github.com/espnet/espnet/blob/master/espnet2/tasks/abs_task.py#L2099) was executed in your experiment?

**Comment by ponymhc** [comment]
Hi, @simpleoier , I checked the script and found that I was using the abs_task.py script from espnet installed by pip. There are some differences as follows:
abs_task.py from espnet installed by pip:
```
use_lora = getattr(args, "use_lora", False)
if use_lora:
    create_lora_adapter(model, **args.lora_conf)
```
abs_task.py from this repo:
```
use_adapter = getattr(args, "use_adapter", False)
if use_adapter:
    create_adapter(model, args.adapter, args.adapter_conf)
```
After pip uninstall espnet and then re-run the script from this repo, the Lora adapter can be initialized properly and successfully complete inference. Thank you for your patience.
