### ISSUE TITLE
Issues Encountered During Fine-tuning on OWSMV3.1

### ISSUE THREAD

**Issue by teinhonglo** [espnet/espnet#5927]
**Describe the bug**

**Basic environments:**
- python version: `3.10.15 (main, Oct  3 2024, 07:27:34) [GCC 11.2.0]`
- espnet version: `espnet 202402`
- pytorch version: `pytorch 1.13.1`
- Git hash: `bffa3bbde968396c8558009a7b2307268b046abf`
  - Commit date: `Fri Oct 4 15:07:53 2024 +0300`

**Environments from `torch.utils.collect_env`:**
```
PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.27.2
Libc version: glibc-2.31

Python version: 3.10.15 (main, Oct  3 2024, 07:27:34) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-196-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
GPU 3: NVIDIA GeForce RTX 3090

Nvidia driver version: 465.19.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.13.1
[pip3] torch-complex==0.4.4
[pip3] torch-optimizer==0.3.0
[pip3] torchaudio==0.13.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2023.1.0         h213fc3f_46344
[conda] mkl-service               2.4.0           py310h5eee18b_1
[conda] mkl_fft                   1.3.10          py310h5eee18b_0
[conda] mkl_random                1.2.7           py310h1128e8f_0
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] numpy-base                2.1.1           py310hb5e798b_0
[conda] pytorch                   1.13.1          py3.10_cuda11.6_cudnn8.3.2_0    pytorch
[conda] pytorch-cuda              11.6                 h867d48c_1    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] torch-complex             0.4.4                    pypi_0    pypi
[conda] torch-optimizer           0.3.0                    pypi_0    pypi
[conda] torchaudio                0.13.1              py310_cu116    pytorch
```

**Task information:**
 - Task: ASR
 - ESPnet2

**To Reproduce**
I created a fine-tuning file based on [this ESPnet guide](https://espnet.github.io/espnet/notebook/ESPnetEZ/ASR/ASR_finetune_owsm.html) and encountered some errors. 
Do you have any suggestions?"

```
vi finetue_owsm.py
```
```
import os
from glob import glob

import numpy as np
import librosa

import torch
from espnet2.bin.s2t_inference import Speech2Text
from espnet2.layers.create_adapter_fn import create_lora_adapter
import espnetez as ez
import pandas as pd
# https://espnet.github.io/espnet/notebook/ESPnetEZ/ASR/ASR_finetune_owsm.html
# Define hyper parameters
DUMP_DIR = f"./dump"
CSV_DIR = f"./transcription"
EXP_DIR = f"./exp/finetune"
STATS_DIR = f"./exp/stats_finetune"
TRAIN_DATA_DIR = f"data/train_l2"
VALID_DATA_DIR = f"data/dev"
TEST_DATA_DIR = f"data/test"

FINETUNE_MODEL = "espnet/owsm_v3.1_ebf"
LORA_TARGET = [
    "w_1", "w_2", "merge_proj"
]
LANGUAGE = "en"

pretrained_model = Speech2Text.from_pretrained(
    FINETUNE_MODEL,
    beam_size=10,
) # Load model to extract configs.
pretrain_config = vars(pretrained_model.s2t_train_args)
tokenizer = pretrained_model.tokenizer
converter = pretrained_model.converter
del pretrained_model

# For the configuration, please refer to the last cell in this notebook.
finetune_config = ez.config.update_finetune_config(
    's2t',
    pretrain_config,
    f"conf/finetune_with_lora.yaml"
)

# When you don't use yaml file, you can load finetune_config in the following way.
# task_class = ez.task.get_ez_task("s2t")
# default_config = task_class.get_default_config()
# training_config = default_config.update(your_config_in_dict)

# define model loading function
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

def build_model_fn(args):
    pretrained_model = Speech2Text.from_pretrained(
        FINETUNE_MODEL,
        beam_size=10,
    )
    model = pretrained_model.s2t_model
    model.train()
    print(f'Trainable parameters: {count_parameters(model)}')
    # apply lora
    create_lora_adapter(model, target_modules=LORA_TARGET)
    print(f'Trainable parameters after LORA: {count_parameters(model)}')
    return model

# custom dataset class
class CustomDataset(torch.utils.data.Dataset):
    def __init__(self, data_list):
        # data_list is a list of tuples (audio_path, text, text_ctc)
        self.data = data_list

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self._parse_single_data(self.data[idx])

    def _parse_single_data(self, d):
        text = f"<{LANGUAGE}><asr><notimestamps> {d['text']}"
        return {
            "audio_path": d["audio_path"],
            "text": text,
            "text_prev": "<en><asr>",
            "text_ctc": d['text_ctc'],
        }

train_data_list = pd.read_csv(os.path.join(TRAIN_DATA_DIR, "transcription.csv")).to_dict('records')
valid_data_list = pd.read_csv(os.path.join(VALID_DATA_DIR, "transcription.csv")).to_dict('records')
test_data_list = pd.read_csv(os.path.join(TEST_DATA_DIR, "transcription.csv")).to_dict('records')

train_dataset = CustomDataset(train_data_list)
valid_dataset = CustomDataset(valid_data_list)
test_dataset = CustomDataset(test_data_list)

def tokenize(text):
    return np.array(converter.tokens2ids(tokenizer.text2tokens(text)))

# The output of CustomDatasetInstance[idx] will converted to np.array
# with the functions defined in the data_info dictionary.
data_info = {
    "speech": lambda d: librosa.load(d["audio_path"], sr=16000)[0],
    "text": lambda d: tokenize(d["text"]),
    "text_prev": lambda d: tokenize(d["text_prev"]),
    "text_ctc": lambda d: tokenize(d["text_ctc"]),
}


# Convert into ESPnet-EZ dataset format
train_dataset = ez.dataset.ESPnetEZDataset(train_dataset, data_info=data_info)
valid_dataset = ez.dataset.ESPnetEZDataset(valid_dataset, data_info=data_info)
test_dataset = ez.dataset.ESPnetEZDataset(test_dataset, data_info=data_info)

trainer = ez.Trainer(
    task='s2t',
    train_config=finetune_config,
    train_dataset=train_dataset,
    valid_dataset=valid_dataset,
    build_model_fn=build_model_fn, # provide the pre-trained model
    data_info=data_info,
    output_dir=EXP_DIR,
    stats_dir=STATS_DIR,
    ngpu=1
)
trainer.collect_stats()
trainer.train()
```

```
python finetue_owsm.py
```

**Error logs**

```
Traceback (most recent call last):
  File "/share/nas167/teinhonglo/espnets/espnet-20241006/egs2/owsm_v3.1/s2t1/local/finetune_owsm.py", line 125, in <module>
    trainer.train()
  File "/share/nas167/teinhonglo/espnets/espnet-20241006/tools/miniconda/envs/espnet/lib/python3.10/site-packages/espnetez/trainer.py", line 161, in train
    self.task_class.main(self.train_config)
  File "/share/nas167/teinhonglo/espnets/espnet-20241006/tools/miniconda/envs/espnet/lib/python3.10/site-packages/espnet2/tasks/abs_task.py", line 1197, in main
    cls.main_worker(args)
  File "/share/nas167/teinhonglo/espnets/espnet-20241006/tools/miniconda/envs/espnet/lib/python3.10/site-packages/espnet2/tasks/abs_task.py", line 1441, in main_worker
    train_iter_factory = cls.build_multiple_iter_factory(
  File "/share/nas167/teinhonglo/espnets/espnet-20241006/tools/miniconda/envs/espnet/lib/python3.10/site-packages/espnet2/tasks/abs_task.py", line 1988, in build_multiple_iter_factory
    raise RuntimeError(f"{path} is not a directory")
RuntimeError: exp/s2t_stats_raw_bpe50000/splits12/wav.scp is not a directory
```

**Comment by sw005320** [comment]
@Masao-Someki, can you respond to this?

**Comment by teinhonglo** [comment]
@Masao-Someki 
Hi Masao-Someki,

Thank you for your prompt response and suggestion! 
My transcription.csv file does not include exp/s2t_stats_raw_bpe50000/splits12/wav.scp. 
I followed your advice and set "finetune_config['multiple_iterator'] = False", and now it works.

I appreciate your assistance.


Best,
Tien-Hong

**Comment by a2d8a4v** [comment]
Hi, I'd like to share if wanna training from the checkpoint:

```

    if args.get("resume_from_checkpoint"):
        if args["resume_from_checkpoint"] == "auto":
            # Find the latest experiment directory
            exp_dirs = [d for d in exp_dir.glob(f"{args['exp_name']}_*") if d.is_dir()]
            if exp_dirs:
                latest_exp = max(exp_dirs, key=lambda x: x.stat().st_mtime)
                checkpoint_path = latest_exp / "checkpoints" / "last.ckpt"
                if checkpoint_path.exists():
                    print(f"Resuming from: {checkpoint_path}")
                else:
                    print("No checkpoint found, starting from scratch")
                    checkpoint_path = None
        else:
            # Use specific checkpoint path
            checkpoint_path = Path(args["resume_from_checkpoint"])
            if not checkpoint_path.exists():
                raise FileNotFoundError(f"Checkpoint not found: {checkpoint_path}")

    # trainer = Trainer(
    #     accelerator="gpu" if args["devices"] > 0 else "cpu",
    #     devices=args["devices"],
    #     fast_dev_run=args["fast_dev_run"],
    #     max_epochs=args["max_epochs"],
    #     callbacks=[checkpoint_callback, early_stop_callback],
    #     deterministic="warn",
    #     default_root_dir=f"{getcwd()}/exps/{args['exp_name']}_{datetime.today().isoformat()}"
    # )
    trainer = Trainer(
        accelerator="gpu" if args["devices"] > 0 else "cpu",
        devices=args["devices"],
        fast_dev_run=args["fast_dev_run"],
        max_epochs=args["max_epochs"],
        callbacks=[checkpoint_callback, early_stop_callback],
        deterministic="warn",
        default_root_dir=f"{getcwd()}/exps/{args['exp_name']}_{datetime.today().isoformat()}"
    )
    # trainer.fit(model, datamodule=datamodule)
    trainer.fit(model, datamodule=datamodule, ckpt_path=checkpoint_path)

```
