### ISSUE TITLE
Conda setup error

### ISSUE THREAD

**Issue by Ksauxion** [espnet/espnet#5929]
Can't install via conda script (as well as others). I tried to reinstall whole espnet, particular miniconda and install tdqm manually, but nothing happened. Also tried with python 3.12, 3.9 and 3.10.
- OS information: Linux 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64
**To Reproduce**
```
cd <espnet-root>/tools
./setup_anaconda.sh miniconda espnet 3.8
```

**Error logs**
```
--2024-10-16 19:18:34--  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.32.241, 104.16.191.158, 2606:4700::6810:20f1, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.32.241|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 148981743 (142M) [application/octet-stream]
Saving to: ‘Miniconda3-latest-Linux-x86_64.sh’

Miniconda3-latest-Linux-x86_6 100%[=================================================>] 142.08M  10.7MB/s    in 14s

2024-10-16 19:18:52 (9.83 MB/s) - ‘Miniconda3-latest-Linux-x86_64.sh’ saved [148981743/148981743]

PREFIX=/mnt/d/NeuralNetworks/espnet/tools/miniconda
Unpacking payload ...

Installing base environment...

Preparing transaction: ...working... done
Executing transaction: ...working... done
installation finished.

EnvironmentNameNotFound: Could not find conda environment: espnet
You can list all discoverable environments with `conda info --envs`.


Channels:
 - defaults
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /mnt/d/NeuralNetworks/espnet/tools/miniconda/envs/espnet



Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate espnet
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Channels:
 - defaults
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /mnt/d/NeuralNetworks/espnet/tools/miniconda/envs/espnet

  added / updated specs:
    - conda
    - python=3.8


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    boltons-23.0.0             |   py38h06a4308_0         426 KB
    brotli-python-1.0.9        |   py38h6a678d5_8         356 KB
    ca-certificates-2024.9.24  |       h06a4308_0         130 KB
    certifi-2024.8.30          |   py38h06a4308_0         162 KB
    cffi-1.17.1                |   py38h1fdaa30_0         253 KB
    conda-24.9.1               |   py38h06a4308_0         909 KB
    conda-libmamba-solver-24.9.0|     pyhd3eb1b0_0          40 KB
    conda-package-handling-2.3.0|   py38h06a4308_0         269 KB
    conda-package-streaming-0.10.0|   py38h06a4308_0          27 KB
    distro-1.9.0               |   py38h06a4308_0          31 KB
    frozendict-2.4.2           |   py38h5eee18b_0          55 KB
    idna-3.7                   |   py38h06a4308_0         113 KB
    jsonpatch-1.33             |   py38h06a4308_1          31 KB
    ld_impl_linux-64-2.40      |       h12ee557_0         710 KB
    libarchive-3.7.4           |       hfab0078_0         920 KB
    libcurl-8.9.1              |       h251f7ec_0         439 KB
    libmamba-1.5.8             |       hfe524e5_3         1.8 MB
    libmambapy-1.5.8           |   py38h2dafd23_3         332 KB
    menuinst-2.1.2             |   py38h06a4308_0         224 KB
    openssl-3.0.15             |       h5eee18b_0         5.2 MB
    packaging-24.1             |   py38h06a4308_0         147 KB
    pip-24.2                   |   py38h06a4308_0         2.2 MB
    platformdirs-3.10.0        |   py38h06a4308_0          33 KB
    pluggy-1.0.0               |   py38h06a4308_1          28 KB
    pybind11-abi-4             |       hd3eb1b0_1          14 KB
    pycosat-0.6.6              |   py38h5eee18b_1          93 KB
    pysocks-1.7.1              |   py38h06a4308_0          31 KB
    python-3.8.20              |       he870216_0        23.8 MB
    requests-2.32.3            |   py38h06a4308_0         100 KB
    ruamel.yaml-0.18.6         |   py38h5eee18b_0         202 KB
    ruamel.yaml.clib-0.2.8     |   py38h5eee18b_0         161 KB
    setuptools-75.1.0          |   py38h06a4308_0         1.7 MB
    tqdm-4.66.5                |   py38h2f386ee_0         133 KB
    urllib3-2.2.3              |   py38h06a4308_0         181 KB
    wheel-0.44.0               |   py38h06a4308_0         108 KB
    zstandard-0.23.0           |   py38h2c38b39_0         432 KB
    zstd-1.5.6                 |       hc292b87_0         664 KB
    ------------------------------------------------------------
                                           Total:        42.3 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu
  archspec           pkgs/main/noarch::archspec-0.2.3-pyhd3eb1b0_0
  boltons            pkgs/main/linux-64::boltons-23.0.0-py38h06a4308_0
  brotli-python      pkgs/main/linux-64::brotli-python-1.0.9-py38h6a678d5_8
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h5eee18b_6
  c-ares             pkgs/main/linux-64::c-ares-1.19.1-h5eee18b_0
  ca-certificates    pkgs/main/linux-64::ca-certificates-2024.9.24-h06a4308_0
  certifi            pkgs/main/linux-64::certifi-2024.8.30-py38h06a4308_0
  cffi               pkgs/main/linux-64::cffi-1.17.1-py38h1fdaa30_0
  charset-normalizer pkgs/main/noarch::charset-normalizer-3.3.2-pyhd3eb1b0_0
  conda              pkgs/main/linux-64::conda-24.9.1-py38h06a4308_0
  conda-libmamba-so~ pkgs/main/noarch::conda-libmamba-solver-24.9.0-pyhd3eb1b0_0
  conda-package-han~ pkgs/main/linux-64::conda-package-handling-2.3.0-py38h06a4308_0
  conda-package-str~ pkgs/main/linux-64::conda-package-streaming-0.10.0-py38h06a4308_0
  distro             pkgs/main/linux-64::distro-1.9.0-py38h06a4308_0
  fmt                pkgs/main/linux-64::fmt-9.1.0-hdb19cb5_1
  frozendict         pkgs/main/linux-64::frozendict-2.4.2-py38h5eee18b_0
  icu                pkgs/main/linux-64::icu-73.1-h6a678d5_0
  idna               pkgs/main/linux-64::idna-3.7-py38h06a4308_0
  jsonpatch          pkgs/main/linux-64::jsonpatch-1.33-py38h06a4308_1
  jsonpointer        pkgs/main/noarch::jsonpointer-2.1-pyhd3eb1b0_0
  krb5               pkgs/main/linux-64::krb5-1.20.1-h143b758_1
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.40-h12ee557_0
  libarchive         pkgs/main/linux-64::libarchive-3.7.4-hfab0078_0
  libcurl            pkgs/main/linux-64::libcurl-8.9.1-h251f7ec_0
  libedit            pkgs/main/linux-64::libedit-3.1.20230828-h5eee18b_0
  libev              pkgs/main/linux-64::libev-4.33-h7f8727e_1
  libffi             pkgs/main/linux-64::libffi-3.4.4-h6a678d5_1
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-11.2.0-h1234567_1
  libgomp            pkgs/main/linux-64::libgomp-11.2.0-h1234567_1
  libmamba           pkgs/main/linux-64::libmamba-1.5.8-hfe524e5_3
  libmambapy         pkgs/main/linux-64::libmambapy-1.5.8-py38h2dafd23_3
  libnghttp2         pkgs/main/linux-64::libnghttp2-1.57.0-h2d74bed_0
  libsolv            pkgs/main/linux-64::libsolv-0.7.24-he621ea3_1
  libssh2            pkgs/main/linux-64::libssh2-1.11.0-h251f7ec_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-11.2.0-h1234567_1
  libxml2            pkgs/main/linux-64::libxml2-2.13.1-hfdd30dd_2
  lz4-c              pkgs/main/linux-64::lz4-c-1.9.4-h6a678d5_1
  menuinst           pkgs/main/linux-64::menuinst-2.1.2-py38h06a4308_0
  ncurses            pkgs/main/linux-64::ncurses-6.4-h6a678d5_0
  openssl            pkgs/main/linux-64::openssl-3.0.15-h5eee18b_0
  packaging          pkgs/main/linux-64::packaging-24.1-py38h06a4308_0
  pcre2              pkgs/main/linux-64::pcre2-10.42-hebb0a14_1
  pip                pkgs/main/linux-64::pip-24.2-py38h06a4308_0
  platformdirs       pkgs/main/linux-64::platformdirs-3.10.0-py38h06a4308_0
  pluggy             pkgs/main/linux-64::pluggy-1.0.0-py38h06a4308_1
  pybind11-abi       pkgs/main/noarch::pybind11-abi-4-hd3eb1b0_1
  pycosat            pkgs/main/linux-64::pycosat-0.6.6-py38h5eee18b_1
  pycparser          pkgs/main/noarch::pycparser-2.21-pyhd3eb1b0_0
  pysocks            pkgs/main/linux-64::pysocks-1.7.1-py38h06a4308_0
  python             pkgs/main/linux-64::python-3.8.20-he870216_0
  readline           pkgs/main/linux-64::readline-8.2-h5eee18b_0
  reproc             pkgs/main/linux-64::reproc-14.2.4-h6a678d5_2
  reproc-cpp         pkgs/main/linux-64::reproc-cpp-14.2.4-h6a678d5_2
  requests           pkgs/main/linux-64::requests-2.32.3-py38h06a4308_0
  ruamel.yaml        pkgs/main/linux-64::ruamel.yaml-0.18.6-py38h5eee18b_0
  ruamel.yaml.clib   pkgs/main/linux-64::ruamel.yaml.clib-0.2.8-py38h5eee18b_0
  setuptools         pkgs/main/linux-64::setuptools-75.1.0-py38h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.45.3-h5eee18b_0
  tk                 pkgs/main/linux-64::tk-8.6.14-h39e8969_0
  tqdm               pkgs/main/linux-64::tqdm-4.66.5-py38h2f386ee_0
  urllib3            pkgs/main/linux-64::urllib3-2.2.3-py38h06a4308_0
  wheel              pkgs/main/linux-64::wheel-0.44.0-py38h06a4308_0
  xz                 pkgs/main/linux-64::xz-5.4.6-h5eee18b_1
  yaml-cpp           pkgs/main/linux-64::yaml-cpp-0.8.0-h6a678d5_1
  zlib               pkgs/main/linux-64::zlib-1.2.13-h5eee18b_1
  zstandard          pkgs/main/linux-64::zstandard-0.23.0-py38h2c38b39_0
  zstd               pkgs/main/linux-64::zstd-1.5.6-hc292b87_0



Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/mnt/d/NeuralNetworks/espnet/tools/miniconda/lib/python3.12/site-packages/conda/exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/mnt/d/NeuralNetworks/espnet/tools/miniconda/lib/python3.12/site-packages/conda/cli/main.py", line 84, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/mnt/d/NeuralNetworks/espnet/tools/miniconda/lib/python3.12/site-packages/conda/cli/conda_argparse.py", line 200, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/mnt/d/NeuralNetworks/espnet/tools/miniconda/lib/python3.12/site-packages/conda/notices/core.py", line 132, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/mnt/d/NeuralNetworks/espnet/tools/miniconda/lib/python3.12/site-packages/conda/cli/main_install.py", line 152, in execute
        return install(args, parser, "install")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/mnt/d/NeuralNetworks/espnet/tools/miniconda/lib/python3.12/site-packages/conda/cli/install.py", line 461, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "/mnt/d/NeuralNetworks/espnet/tools/miniconda/lib/python3.12/site-packages/conda/cli/install.py", line 532, in handle_txn
        unlink_link_transaction.execute()
      File "/mnt/d/NeuralNetworks/espnet/tools/miniconda/lib/python3.12/site-packages/conda/core/link.py", line 348, in execute
        self.verify()
      File "/mnt/d/NeuralNetworks/espnet/tools/miniconda/lib/python3.12/site-packages/conda/common/io.py", line 86, in decorated
        return f(*args, **kwds)
               ^^^^^^^^^^^^^^^^
      File "/mnt/d/NeuralNetworks/espnet/tools/miniconda/lib/python3.12/site-packages/conda/core/link.py", line 304, in verify
        exceptions = self._verify(self.prefix_setups, self.prefix_action_groups)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/mnt/d/NeuralNetworks/espnet/tools/miniconda/lib/python3.12/site-packages/conda/core/link.py", line 810, in _verify
        for exc in self.verify_executor.map(
      File "/mnt/d/NeuralNetworks/espnet/tools/miniconda/lib/python3.12/site-packages/conda/common/io.py", line 591, in map
        yield func(thing)
              ^^^^^^^^^^^
      File "/mnt/d/NeuralNetworks/espnet/tools/miniconda/lib/python3.12/site-packages/conda/core/link.py", line 587, in _verify_individual_level
        error_result = axn.verify()
                       ^^^^^^^^^^^^
      File "/mnt/d/NeuralNetworks/espnet/tools/miniconda/lib/python3.12/site-packages/conda/core/path_actions.py", line 394, in verify
        source_size_in_bytes = getsize(self.source_full_path)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<frozen genericpath>", line 62, in getsize
    OSError: [Errno 40] Too many levels of symbolic links: '/mnt/d/NeuralNetworks/espnet/tools/miniconda/pkgs/ncurses-6.4-h6a678d5_0/share/terminfo/n/ncr260vt300wpp'

`$ /mnt/d/NeuralNetworks/espnet/tools/miniconda/bin/conda install -y conda python=3.8`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=espnet
                CONDA_EXE=/mnt/d/NeuralNetworks/espnet/tools/miniconda/bin/conda
             CONDA_PREFIX=/mnt/d/NeuralNetworks/espnet/tools/miniconda/envs/espnet
    CONDA_PROMPT_MODIFIER=(espnet)
         CONDA_PYTHON_EXE=/mnt/d/NeuralNetworks/espnet/tools/miniconda/bin/python
               CONDA_ROOT=/mnt/d/NeuralNetworks/espnet/tools/miniconda
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/mnt/d/NeuralNetworks/espnet/tools/miniconda/envs/espnet/bin:/home/ksi
                          on/.local/bin:/home/ksion/miniconda3/condabin:/usr/local/sbin:/usr/loc
                          al/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/
                          lib/wsl/lib:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : espnet
    active env location : /mnt/d/NeuralNetworks/espnet/tools/miniconda/envs/espnet
            shell level : 1
       user config file : /home/ksion/.condarc
 populated config files : /home/ksion/.condarc
          conda version : 24.7.1
    conda-build version : not installed
         python version : 3.12.4.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake
                          __conda=24.7.1=0
                          __cuda=12.5=0
                          __glibc=2.35=0
                          __linux=5.15.153.1=0
                          __unix=0=0
       base environment : /mnt/d/NeuralNetworks/espnet/tools/miniconda  (writable)
      conda av data dir : /mnt/d/NeuralNetworks/espnet/tools/miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /mnt/d/NeuralNetworks/espnet/tools/miniconda/pkgs
                          /home/ksion/.conda/pkgs
       envs directories : /mnt/d/NeuralNetworks/espnet/tools/miniconda/envs
                          /home/ksion/.conda/envs
               platform : linux-64
             user-agent : conda/24.7.1 requests/2.32.3 CPython/3.12.4 Linux/5.15.153.1-microsoft-standard-WSL2 ubuntu/22.04.3 glibc/2.35 solver/libmamba conda-libmamba-solver/24.7.0 libmambapy/1.5.8 aau/0.4.4 c/. s/. e/.
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

Upload did not complete.
```

**Comment by Fhrozen** [comment]
In your errors, it says `  OSError: [Errno 40] Too many levels of symbolic links:` 
It will be better if you try to executing or install conda in a different path, using HOME or root `/`
like: `./setup_anaconda.sh /opt/miniconda espnet 3.8`
