### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by CriDora** [espnet/espnet#5956]
**Describe the bug**
When training fastspeech2 with my own data, I encountered this problem in stage5:
Traceback (most recent call last):
  File "/home/lhw523/anaconda3/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/lhw523/anaconda3/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/s1home/lhw523/espnet/espnet2/bin/tts_train.py", line 22, in <module>
    main()
  File "/s1home/lhw523/espnet/espnet2/bin/tts_train.py", line 18, in main
    TTSTask.main(cmd=cmd)
  File "/s1home/lhw523/espnet/espnet2/tasks/abs_task.py", line 1082, in main
    cls.main_worker(args)
  File "/s1home/lhw523/espnet/espnet2/tasks/abs_task.py", line 1272, in main_worker
    collect_stats(
  File "/home/lhw523/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/s1home/lhw523/espnet/espnet2/main_funcs/collect_stats.py", line 69, in collect_stats
    data = model.collect_feats(**batch)
  File "/s1home/lhw523/espnet/espnet2/tts/espnet_model.py", line 198, in collect_feats
    pitch, pitch_lengths = self.pitch_extract(
  File "/home/lhw523/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/s1home/lhw523/espnet/espnet2/tts/feats_extract/dio.py", line 110, in forward
    durations = durations * self.reduction_factor
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

**Basic environments:**
- OS information: Linux 5.4.0-200-generic #220-Ubuntu SMP Fri Sep 27 13:19:16 UTC 2024 x86_64
- python version: `3.8.18 (default, Sep 11 2023, 13:40:15)  [GCC 11.2.0]`
- espnet version: `espnet 202308`
- pytorch version: `pytorch 2.0.1`
- Git hash: `5d0758e2a7063b82d1f10a8ac2de98eb6cf8a352`
  - Commit date: `Wed Aug 30 18:03:42 2023 -0400`

**Environments from `torch.utils.collect_env`:**
e.g.,
```
Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.31

Python version: 3.8.18 (default, Sep 11 2023, 13:40:15)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-200-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
GPU 3: NVIDIA GeForce RTX 3090

Nvidia driver version: 535.54.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      46 bits physical, 48 bits virtual
CPU(s):                             40
On-line CPU(s) list:                0-39
Thread(s) per core:                 2
Core(s) per socket:                 10
Socket(s):                          2
NUMA node(s):                       2
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              79
Model name:                         Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
Stepping:                           1
CPU MHz:                            1198.870
CPU max MHz:                        3100.0000
CPU min MHz:                        1200.0000
BogoMIPS:                           4394.88
Virtualization:                     VT-x
L1d cache:                          640 KiB
L1i cache:                          640 KiB
L2 cache:                           5 MiB
L3 cache:                           50 MiB
NUMA node0 CPU(s):                  0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38
NUMA node1 CPU(s):                  1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        KVM: Mitigation: Split huge pages
Vulnerability L1tf:                 Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:                  Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:             Mitigation; PTI
Vulnerability Mmio stale data:      Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines; IBPB conditional; IBRS_FW; STIBP conditional; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Mitigation; Clear CPU buffers; SMT vulnerable
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.1
[pip3] torch==2.0.1
[pip3] torch-complex==0.4.3
[pip3] torch-optimizer==0.3.0
[pip3] torchaudio==2.0.2
[conda] blas                      1.0                         mkl    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
[conda] mkl                       2023.1.0         h213fc3f_46343    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
[conda] mkl-service               2.4.0            py38h5eee18b_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
[conda] mkl_fft                   1.3.8            py38h5eee18b_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
[conda] mkl_random                1.2.4            py38hdb19cb5_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
[conda] numpy                     1.24.4                   pypi_0    pypi
[conda] pytorch                   2.0.1           py3.8_cuda11.7_cudnn8.5.0_0    pytorch
[conda] pytorch-cuda              11.7                 h778d358_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.1                    pypi_0    pypi
[conda] torch-complex             0.4.3                    pypi_0    pypi
[conda] torch-optimizer           0.3.0                    pypi_0    pypi
[conda] torchaudio                2.0.2                py38_cu117    pytorch
[conda] torchtriton               2.0.0                      py38    pytorch
```

**Task information:**
 - Task: [TTS]
 - Recipe: [libritts, fastspeech2]
 - ESPnet2

**To Reproduce**
1.  `cd egs2/ug`
2. `bash run.sh`
3.  the error log: `slurm-16414.out`

**Error logs**
Paste the error logs. If applicable, add screenshots to help explain your problem.
[slurm-16371.zip](https://github.com/user-attachments/files/17749125/slurm-16371.zip)

**Comment by sw005320** [comment]
> When training fastspeech2 with my own data, I encountered this problem in stage5:

Would it work on the existing data (e.g., ljspeech)?

**Comment by CriDora** [comment]
> > When training fastspeech2 with my own data, I encountered this problem in stage5:
> 
> Would it work on the existing data (e.g., ljspeech)?

Sorry I'm not sure, this is my first time using fastspeech2

**Comment by ftshijt** [comment]
It is likely to be the problem from no duration information. It would be great if you could check the doc on how to get the duration information (i.e., teacher model in the context) for training at https://espnet.github.io/espnet/recipe/tts1.html#fastspeech-training
