### ISSUE TITLE
CUDA out of memory when use whisper model

### ISSUE THREAD

**Issue by Zilai-WANG** [espnet/espnet#5958]
**Describe the bug**
CUDA out of memory when use whisper model. For example, when use whisper-tiny.en on small dataset like an4, even using  GPU: A6000 (48GB) will encourter CUDA out of memeory issue. 

**Task information:**
 - Task: [ASR]
 - Recipe: [an4]
 - Python: 3.11
 - CUDA: 2.3.0
 - ESPnet2

**To Reproduce**
in stage 11 of asr.sh. 

**Configuration (conf/whisper.yaml)**
<details><summary>Details</summary>
<p>

batch_type: numel
batch_bins: 10000
batch_size: 4
accum_grad: 4
max_epoch: 5
patience: none
init: none
num_att_plot: 0

val_scheduler_criterion:
    - valid
    - loss
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 5

model_conf:
    ctc_weight: 0.0 # Set to 0.0 to disable CTC loss
    report_cer: False
    report_wer: true

encoder: whisper
encoder_conf:
  whisper_model: "tiny.en"  # Replace 

decoder: whisper
decoder_conf:
    whisper_model: "tiny.en"  

optim: adam
optim_conf:
    lr: 0.0015
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 2500

frontend: Null
input_size: 80  # Specify the number of Mel bands
use_amp: true

</p>
</details> 

**Error logs**
<details><summary>Details</summary>
<p>

python3 -m espnet2.bin.asr_train --use_preprocessor true --bpemodel data/token_list/bpe_unigram32/bpe.model --token_type bpe --token_list data/token_list/bpe_unigram32/tokens.txt --non_linguistic_symbols none --cleaner none --g2p none --valid_data_path_and_name_and_type dump/raw/development/wav.scp,speech,sound --valid_shape_file exp/asr_stats_raw_bpe32/valid/speech_shape --resume true --ignore_init_mismatch false --fold_length 80000 --output_dir exp/asr_whisper_raw_bpe32 --config conf/whisper.yaml --frontend_conf fs=16k --normalize=global_mvn --normalize_conf stats_file=exp/asr_stats_raw_bpe32/train/feats_stats.npz --train_data_path_and_name_and_type dump/raw/train/wav.scp,speech,sound --train_shape_file exp/asr_stats_raw_bpe32/train/speech_shape --fold_length 150 --train_data_path_and_name_and_type dump/raw/train/text,text,text --train_shape_file exp/asr_stats_raw_bpe32/train/text_shape.bpe --valid_data_path_and_name_and_type dump/raw/development/text,text,text --valid_shape_file exp/asr_stats_raw_bpe32/valid/text_shape.bpe --ngpu 1 --multiprocessing_distributed True 

[lambda-Lambda-Vector] 2024-11-14 14:58:41,504 (asr:523) INFO: Vocabulary size: 32
[lambda-Lambda-Vector] 2024-11-14 14:58:43,166 (abs_task:1383) INFO: pytorch.version=2.3.0, cuda.available=True, cudnn.version=8902, cudnn.benchmark=False, cudnn.deterministic=True
[lambda-Lambda-Vector] 2024-11-14 14:58:43,168 (abs_task:1384) INFO: Model structure:
ESPnetASRModel(
  (normalize): GlobalMVN(stats_file=exp/asr_stats_raw_bpe32/train/feats_stats.npz, norm_means=True, norm_vars=True)
  (encoder): OpenAIWhisperEncoder(
    (dropout): Dropout(p=0.0, inplace=False)
    (encoders): AudioEncoder(
      (conv1): Conv1d(80, 384, kernel_size=(3,), stride=(1,), padding=(1,))
      (conv2): Conv1d(384, 384, kernel_size=(3,), stride=(2,), padding=(1,))
      (blocks): ModuleList(
        (0-3): 4 x ResidualAttentionBlock(
          (attn): MultiHeadAttention(
            (query): Linear(in_features=384, out_features=384, bias=True)
            (key): Linear(in_features=384, out_features=384, bias=False)
            (value): Linear(in_features=384, out_features=384, bias=True)
            (out): Linear(in_features=384, out_features=384, bias=True)
          )
          (attn_ln): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
          (mlp): Sequential(
            (0): Linear(in_features=384, out_features=1536, bias=True)
            (1): GELU(approximate='none')
            (2): Linear(in_features=1536, out_features=384, bias=True)
          )
          (mlp_ln): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
        )
      )
      (ln_post): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
    )
  )
  (decoder): OpenAIWhisperDecoder(
    (decoders): TextDecoder(
      (token_embedding): Embedding(32, 384)
      (blocks): ModuleList(
        (0-3): 4 x ResidualAttentionBlock(
          (attn): MultiHeadAttention(
            (query): Linear(in_features=384, out_features=384, bias=True)
            (key): Linear(in_features=384, out_features=384, bias=False)
            (value): Linear(in_features=384, out_features=384, bias=True)
            (out): Linear(in_features=384, out_features=384, bias=True)
          )
          (attn_ln): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
          (cross_attn): MultiHeadAttention(
            (query): Linear(in_features=384, out_features=384, bias=True)
            (key): Linear(in_features=384, out_features=384, bias=False)
            (value): Linear(in_features=384, out_features=384, bias=True)
            (out): Linear(in_features=384, out_features=384, bias=True)
          )
          (cross_attn_ln): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
          (mlp): Sequential(
            (0): Linear(in_features=384, out_features=1536, bias=True)
            (1): GELU(approximate='none')
            (2): Linear(in_features=1536, out_features=384, bias=True)
          )
          (mlp_ln): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
        )
      )
      (ln): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
    )
    (dropout): Dropout(p=0.0, inplace=False)
  )
  (criterion_att): LabelSmoothingLoss(
    (criterion): KLDivLoss()
  )
)

Model summary:
    Class Name: ESPnetASRModel
    Total Number of model parameters: 17.28 M
    Number of trainable parameters: 17.28 M (100.0%)
    Size: 69.12 MB
    Type: torch.float32

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/data/zilai/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/data/zilai/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/data/zilai/espnet/espnet2/tasks/abs_task.py", line 1210, in main
    cls.main_worker(args)
  File "/data/zilai/espnet/espnet2/tasks/abs_task.py", line 1568, in main_worker
    cls.trainer.run(
  File "/data/zilai/espnet/espnet2/train/trainer.py", line 317, in run
    all_steps_are_invalid = cls.train_one_epoch(
                            ^^^^^^^^^^^^^^^^^^^^
  File "/data/zilai/espnet/espnet2/train/trainer.py", line 614, in train_one_epoch
    retval = model(**batch)
             ^^^^^^^^^^^^^^
  File "/data/zilai/espnet/tools/anaconda3/envs/py311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/zilai/espnet/tools/anaconda3/envs/py311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/zilai/espnet/espnet2/asr/espnet_model.py", line 237, in forward
    encoder_out, encoder_out_lens = self.encode(speech, speech_lengths)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/zilai/espnet/espnet2/asr/espnet_model.py", line 386, in encode
    feats, feats_lengths = self.normalize(feats, feats_lengths)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/zilai/espnet/tools/anaconda3/envs/py311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/zilai/espnet/tools/anaconda3/envs/py311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/zilai/espnet/espnet2/layers/global_mvn.py", line 88, in forward
    mask = make_pad_mask(ilens, x, 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/zilai/espnet/espnet/nets/pytorch_backend/nets_utils.py", line 168, in make_pad_mask
    return _make_pad_mask_traceable(lengths, xs, length_dim, maxlen)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/zilai/espnet/espnet/nets/pytorch_backend/nets_utils.py", line 249, in _make_pad_mask_traceable
    mask = triu_onnx(mask)[1:, :-1]  # onnx cannot handle diagonal argument.
           ^^^^^^^^^^^^^^^
  File "/data/zilai/espnet/espnet/nets/pytorch_backend/nets_utils.py", line 260, in triu_onnx
    mask = arange.unsqueeze(-1).expand(-1, x.size(0)) <= arange
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 8.87 GiB. GPU 

</p>
</details>

**Comment by Zilai-WANG** [comment]
Thank you for your suggest. I have set the batch_size to be 4 and the max_wav_length = 20 second. It uses around  30000MiB /  49140MiB for whisper-base model on an4 dataset. Since size of an4 is really small, if change to other custom dataset, its CUDA memory usage will be a lot.
