### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/config.yaml'

### ISSUE THREAD

**Issue by mukherjeesougata-eros** [espnet/espnet#5965]
I am trying to finetune the whisper pre-trained model using my custom dataset. I have prepared a run_whisper.sh script after following [this](https://huggingface.co/espnet/shihlun_asr_whisper_medium_finetuned_librispeech100) which has been previously carried out on librispech_100 dataset. My run.sh script contains the following:-
```
set -e
set -u
set -o pipefail

train_set="train"
valid_set="dev"
test_sets="test"
asr_tag=whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs
asr_config=conf/train_asr_whisper_full.yaml
inference_config=conf/decode_asr_whisper_noctc_greedy.yaml

./asr.sh \
    --skip_data_prep false \
    --skip_train true \
    --skip_eval false \
    --ngpu 2 \
    --nj 4 \
    --stage 2 \
    --stop_stage 13 \
    --gpu_inference true \
    --inference_nj 1 \
    --token_type whisper_multilingual \
    --feats_normalize '' \
    --max_wav_duration 288.96 \
    --speed_perturb_factors "0.9 1.0 1.1" \
    --audio_format "wav" \
    --feats_type raw \
    --use_lm false \
    --cleaner whisper_en \
    --asr_tag "${asr_tag}" \
    --asr_config "${asr_config}" \
    --inference_config "${inference_config}" \
    --inference_asr_model valid.acc.ave.pth \
    --train_set "${train_set}" \
    --valid_set "${valid_set}" \
    --test_sets "${test_sets}" "$@"
```
But when I am running the run_whisper.sh script it is giving me the following error:-
```
./run_whisper.sh 
2024-11-24T18:25:54 (asr.sh:283:main) ./asr.sh --skip_data_prep false --skip_train true --skip_eval false --ngpu 2 --nj 4 --stage 2 --stop_stage 13 --gpu_inference true --inference_nj 1 --token_type whisper_multilingual --feats_normalize  --max_wav_duration 288.96 --speed_perturb_factors 0.9 1.0 1.1 --audio_format wav --feats_type raw --use_lm false --cleaner whisper_en --asr_tag whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs --asr_config conf/train_asr_whisper_full.yaml --inference_config conf/decode_asr_whisper_noctc_greedy.yaml --inference_asr_model valid.acc.ave.pth --train_set train --valid_set dev --test_sets test
2024-11-24T18:25:54 (asr.sh:565:main) Skipped stages:  2 4 5 6 7 8 9 10 11 14 15 16 
2024-11-24T18:25:54 (asr.sh:615:main) Stage 3: Format wav.scp: data/ -> dump/raw
utils/copy_data_dir.sh: copied data from data/test to dump/raw/test
utils/validate_data_dir.sh: Successfully validated data-directory dump/raw/test
2024-11-24T18:25:54 (format_wav_scp.sh:46:main) scripts/audio/format_wav_scp.sh --nj 4 --cmd run.pl --audio-format wav --fs 16k --multi-columns-input false --multi-columns-output false data/test/wav.scp dump/raw/test
2024-11-24T18:25:54 (format_wav_scp.sh:118:main) [info]: without segments
2024-11-24T18:25:55 (format_wav_scp.sh:153:main) Successfully finished. [elapsed=1s]
2024-11-24T18:25:55 (asr.sh:1481:main) Stage 12: Decoding: training_dir=exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs
2024-11-24T18:25:55 (asr.sh:1509:main) Generate 'exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/decode_asr_whisper_noctc_greedy_asr_model_valid.acc.ave/run.sh'. You can resume the process from stage 12 using this script
2024-11-24T18:25:55 (asr.sh:1574:main) Decoding started... log: 'exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/decode_asr_whisper_noctc_greedy_asr_model_valid.acc.ave/test/logdir/asr_inference.*.log'
run.pl: job failed, log is in exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/decode_asr_whisper_noctc_greedy_asr_model_valid.acc.ave/test/logdir/asr_inference.1.log
# python3 -m espnet2.bin.asr_inference --batch_size 1 --ngpu 1 --data_path_and_name_and_type dump/raw/test/wav.scp,speech,sound --key_file exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/decode_asr_whisper_noctc_greedy_asr_model_valid.acc.ave/test/logdir/keys.1.scp --asr_train_config exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/config.yaml --asr_model_file exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/valid.acc.ave.pth --output_dir exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/decode_asr_whisper_noctc_greedy_asr_model_valid.acc.ave/test/logdir/output.1 --config conf/decode_asr_whisper_noctc_greedy.yaml 
# Started at Sun Nov 24 18:25:55 IST 2024
#
/DATA/anaconda3/envs/espnet/lib/python3.8/site-packages/whisper/timing.py:57: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
/DATA/anaconda3/envs/espnet/bin/python3 /DATA/Sougata/espnet/espnet2/bin/asr_inference.py --batch_size 1 --ngpu 1 --data_path_and_name_and_type dump/raw/test/wav.scp,speech,sound --key_file exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/decode_asr_whisper_noctc_greedy_asr_model_valid.acc.ave/test/logdir/keys.1.scp --asr_train_config exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/config.yaml --asr_model_file exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/valid.acc.ave.pth --output_dir exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/decode_asr_whisper_noctc_greedy_asr_model_valid.acc.ave/test/logdir/output.1 --config conf/decode_asr_whisper_noctc_greedy.yaml
2024-11-24 18:25:59,303 (abs_task:2083) INFO: config file: exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/config.yaml
Traceback (most recent call last):
  File "/DATA/anaconda3/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/DATA/anaconda3/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/DATA/Sougata/espnet/espnet2/bin/asr_inference.py", line 1115, in <module>
    main()
  File "/DATA/Sougata/espnet/espnet2/bin/asr_inference.py", line 1111, in main
    inference(**kwargs)
  File "/DATA/Sougata/espnet/espnet2/bin/asr_inference.py", line 783, in inference
    speech2text = Speech2Text.from_pretrained(
  File "/DATA/Sougata/espnet/espnet2/bin/asr_inference.py", line 679, in from_pretrained
    return Speech2Text(**kwargs)
  File "/DATA/Sougata/espnet/espnet2/bin/asr_inference.py", line 136, in __init__
    asr_model, asr_train_args = task.build_model_from_file(
  File "/DATA/Sougata/espnet/espnet2/tasks/abs_task.py", line 2084, in build_model_from_file
    with config_file.open("r", encoding="utf-8") as f:
  File "/DATA/anaconda3/envs/espnet/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/DATA/anaconda3/envs/espnet/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/config.yaml'
# Accounting: time=4 threads=1
# Ended (code 1) at Sun Nov 24 18:25:59 IST 2024, elapsed time 4 seconds

```

**Comment by sw005320** [comment]
The errors come from `FileNotFoundError: [Errno 2] No such file or directory: 'exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/config.yaml`
Please check that the directories/files are created appropriately.

**Comment by mukherjeesougata** [comment]
I have run the exact same script as mentioned in the following [link](https://huggingface.co/espnet/shihlun_asr_whisper_medium_finetuned_librispeech100) after copying the following commands in a ```run_whisper.sh``` script to check what extra files and folders are getting created in case of librispeech_100. The contents of the ```run_whisper.sh``` script are as follows:- 

```
#!/usr/bin/env bash
# Set bash to 'debug' mode, it will exit on :
# -e 'error', -u 'undefined variable', -o ... 'error in pipeline', -x 'print commands',
# cd espnet
# pip install -e .
# cd egs2/librispeech_100/asr1

set -e
set -u
set -o pipefail

train_set="train_clean_100"
valid_set="dev"
test_sets="test_clean test_other dev_clean dev_other"
asr_tag=whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs
asr_config=conf/tuning/train_asr_whisper_full.yaml
inference_config=conf/decode_asr_whisper_noctc_greedy.yaml

./asr.sh \
    --skip_data_prep false \
    --skip_train true \
    --skip_eval false \
    --lang en \
    --ngpu 1 \
    --nj 4 \
    --stage 1 \
    --stop_stage 13 \
    --gpu_inference true \
    --inference_nj 1 \
    --token_type whisper_multilingual \
    --feats_normalize '' \
    --max_wav_duration 30 \
    --speed_perturb_factors "0.9 1.0 1.1" \
    --audio_format "flac.ark" \
    --feats_type raw \
    --use_lm false \
    --cleaner whisper_en \
    --asr_tag "${asr_tag}" \
    --asr_config "${asr_config}" \
    --inference_config "${inference_config}" \
    -ut-inference_asr_model valid.acc.ave.pth \
    --train_set "${train_set}" \
    --valid_set "${valid_set}" \
    --test_sets "${test_sets}" "$@"

```
But still it is giving the following error:-
```
./run_whisper.sh 
2024-11-28T00:00:30 (asr.sh:283:main) ./asr.sh --skip_data_prep false --skip_train true --skip_eval false --lang en --ngpu 1 --nj 4 --stage 1 --stop_stage 13 --gpu_inference true --inference_nj 1 --token_type whisper_multilingual --feats_normalize  --max_wav_duration 30 --speed_perturb_factors 0.9 1.0 1.1 --audio_format flac.ark --feats_type raw --use_lm false --cleaner whisper_en --asr_tag whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs --asr_config conf/tuning/train_asr_whisper_full.yaml --inference_config conf/decode_asr_whisper_noctc_greedy.yaml --inference_asr_model valid.acc.ave.pth --train_set train_clean_100 --valid_set dev --test_sets test_clean test_other dev_clean dev_other
2024-11-28T00:00:31 (asr.sh:565:main) Skipped stages:  2 4 5 6 7 8 9 10 11 14 15 16 
2024-11-28T00:00:31 (asr.sh:572:main) Stage 1: Data preparation for data/train_clean_100, data/dev, etc.
2024-11-28T00:00:31 (data.sh:20:main) local/data.sh 
2024-11-28T00:00:31 (data.sh:47:main) stage 1: downloads/LibriSpeech/LICENSE.TXT is already existing. Skip data downloading
2024-11-28T00:00:31 (data.sh:52:main) stage 2: Data Preparation
utils/validate_data_dir.sh: Successfully validated data-directory data/dev_clean
local/data_prep.sh: successfully prepared data in data/dev_clean
utils/validate_data_dir.sh: Successfully validated data-directory data/test_clean
local/data_prep.sh: successfully prepared data in data/test_clean
utils/validate_data_dir.sh: Successfully validated data-directory data/dev_other
local/data_prep.sh: successfully prepared data in data/dev_other
utils/validate_data_dir.sh: Successfully validated data-directory data/test_other
local/data_prep.sh: successfully prepared data in data/test_other
utils/validate_data_dir.sh: Successfully validated data-directory data/train_clean_100
local/data_prep.sh: successfully prepared data in data/train_clean_100
2024-11-28T00:01:16 (data.sh:60:main) stage 3: combine all training and development sets
utils/combine_data.sh --extra_files utt2num_frames data/dev data/dev_clean data/dev_other
utils/combine_data.sh [info]: not combining utt2uniq as it does not exist
utils/combine_data.sh [info]: not combining segments as it does not exist
utils/combine_data.sh: combined utt2spk
utils/combine_data.sh [info]: not combining utt2lang as it does not exist
utils/combine_data.sh [info]: not combining utt2dur as it does not exist
utils/combine_data.sh [info]: not combining utt2num_frames as it does not exist
utils/combine_data.sh [info]: not combining reco2dur as it does not exist
utils/combine_data.sh [info]: not combining feats.scp as it does not exist
utils/combine_data.sh: combined text
utils/combine_data.sh [info]: not combining cmvn.scp as it does not exist
utils/combine_data.sh [info]: not combining vad.scp as it does not exist
utils/combine_data.sh [info]: not combining reco2file_and_channel as it does not exist
utils/combine_data.sh: combined wav.scp
utils/combine_data.sh: combined spk2gender
utils/combine_data.sh [info]: not combining utt2num_frames as it does not exist
fix_data_dir.sh: kept all 5567 utterances.
fix_data_dir.sh: old files are kept in data/dev/.backup
2024-11-28T00:01:17 (data.sh:78:main) Successfully finished. [elapsed=46s]
2024-11-28T00:01:17 (asr.sh:615:main) Stage 3: Format wav.scp: data/ -> dump/raw
utils/copy_data_dir.sh: copied data from data/test_clean to dump/raw/test_clean
utils/validate_data_dir.sh: Successfully validated data-directory dump/raw/test_clean
2024-11-28T00:01:17 (format_wav_scp.sh:46:main) scripts/audio/format_wav_scp.sh --nj 4 --cmd run.pl --audio-format flac.ark --fs 16k --multi-columns-input false --multi-columns-output false data/test_clean/wav.scp dump/raw/test_clean
2024-11-28T00:01:17 (format_wav_scp.sh:118:main) [info]: without segments
2024-11-28T00:01:30 (format_wav_scp.sh:153:main) Successfully finished. [elapsed=13s]
utils/copy_data_dir.sh: copied data from data/test_other to dump/raw/test_other
utils/validate_data_dir.sh: Successfully validated data-directory dump/raw/test_other
2024-11-28T00:01:30 (format_wav_scp.sh:46:main) scripts/audio/format_wav_scp.sh --nj 4 --cmd run.pl --audio-format flac.ark --fs 16k --multi-columns-input false --multi-columns-output false data/test_other/wav.scp dump/raw/test_other
2024-11-28T00:01:30 (format_wav_scp.sh:118:main) [info]: without segments
2024-11-28T00:01:42 (format_wav_scp.sh:153:main) Successfully finished. [elapsed=12s]
utils/copy_data_dir.sh: copied data from data/dev_clean to dump/raw/dev_clean
utils/validate_data_dir.sh: Successfully validated data-directory dump/raw/dev_clean
2024-11-28T00:01:42 (format_wav_scp.sh:46:main) scripts/audio/format_wav_scp.sh --nj 4 --cmd run.pl --audio-format flac.ark --fs 16k --multi-columns-input false --multi-columns-output false data/dev_clean/wav.scp dump/raw/dev_clean
2024-11-28T00:01:42 (format_wav_scp.sh:118:main) [info]: without segments
2024-11-28T00:01:54 (format_wav_scp.sh:153:main) Successfully finished. [elapsed=12s]
utils/copy_data_dir.sh: copied data from data/dev_other to dump/raw/dev_other
utils/validate_data_dir.sh: Successfully validated data-directory dump/raw/dev_other
2024-11-28T00:01:54 (format_wav_scp.sh:46:main) scripts/audio/format_wav_scp.sh --nj 4 --cmd run.pl --audio-format flac.ark --fs 16k --multi-columns-input false --multi-columns-output false data/dev_other/wav.scp dump/raw/dev_other
2024-11-28T00:01:55 (format_wav_scp.sh:118:main) [info]: without segments
2024-11-28T00:02:07 (format_wav_scp.sh:153:main) Successfully finished. [elapsed=13s]
2024-11-28T00:02:07 (asr.sh:1481:main) Stage 12: Decoding: training_dir=exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs
2024-11-28T00:02:07 (asr.sh:1509:main) Generate 'exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/decode_asr_whisper_noctc_greedy_asr_model_valid.acc.ave/run.sh'. You can resume the process from stage 12 using this script
2024-11-28T00:02:07 (asr.sh:1574:main) Decoding started... log: 'exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/decode_asr_whisper_noctc_greedy_asr_model_valid.acc.ave/test_clean/logdir/asr_inference.*.log'
run.pl: job failed, log is in exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/decode_asr_whisper_noctc_greedy_asr_model_valid.acc.ave/test_clean/logdir/asr_inference.1.log
# python3 -m espnet2.bin.asr_inference --batch_size 1 --ngpu 1 --data_path_and_name_and_type dump/raw/test_clean/wav.scp,speech,kaldi_ark --key_file exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/decode_asr_whisper_noctc_greedy_asr_model_valid.acc.ave/test_clean/logdir/keys.1.scp --asr_train_config exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/config.yaml --asr_model_file exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/valid.acc.ave.pth --output_dir exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/decode_asr_whisper_noctc_greedy_asr_model_valid.acc.ave/test_clean/logdir/output.1 --config conf/decode_asr_whisper_noctc_greedy.yaml 
# Started at Thu Nov 28 00:02:07 IST 2024
#
/DATA/anaconda3/envs/espnet/lib/python3.8/site-packages/whisper/timing.py:57: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
/DATA/anaconda3/envs/espnet/bin/python3 /DATA/Sougata/espnet/espnet2/bin/asr_inference.py --batch_size 1 --ngpu 1 --data_path_and_name_and_type dump/raw/test_clean/wav.scp,speech,kaldi_ark --key_file exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/decode_asr_whisper_noctc_greedy_asr_model_valid.acc.ave/test_clean/logdir/keys.1.scp --asr_train_config exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/config.yaml --asr_model_file exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/valid.acc.ave.pth --output_dir exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/decode_asr_whisper_noctc_greedy_asr_model_valid.acc.ave/test_clean/logdir/output.1 --config conf/decode_asr_whisper_noctc_greedy.yaml
2024-11-28 00:02:12,307 (abs_task:2083) INFO: config file: exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/config.yaml
Traceback (most recent call last):
  File "/DATA/anaconda3/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/DATA/anaconda3/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/DATA/Sougata/espnet/espnet2/bin/asr_inference.py", line 1115, in <module>
    main()
  File "/DATA/Sougata/espnet/espnet2/bin/asr_inference.py", line 1111, in main
    inference(**kwargs)
  File "/DATA/Sougata/espnet/espnet2/bin/asr_inference.py", line 783, in inference
    speech2text = Speech2Text.from_pretrained(
  File "/DATA/Sougata/espnet/espnet2/bin/asr_inference.py", line 679, in from_pretrained
    return Speech2Text(**kwargs)
  File "/DATA/Sougata/espnet/espnet2/bin/asr_inference.py", line 136, in __init__
    asr_model, asr_train_args = task.build_model_from_file(
  File "/DATA/Sougata/espnet/espnet2/tasks/abs_task.py", line 2084, in build_model_from_file
    with config_file.open("r", encoding="utf-8") as f:
  File "/DATA/anaconda3/envs/espnet/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/DATA/anaconda3/envs/espnet/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'exp/asr_whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs/config.yaml'
# Accounting: time=5 threads=1
# Ended (code 1) at Thu Nov 28 00:02:12 IST 2024, elapsed time 5 seconds

```

**Comment by Fhrozen** [comment]
@dosubot
