### ISSUE TITLE
Installation bug in ESPnet after trying to install flash attn and s3prl

### ISSUE THREAD

**Issue by uwanny** [espnet/espnet#5981]
**Describe the issue**
I suspect there is some installation bug in the current ESPnet, especially when it is related to flash-attn and s3prl. I will continuously report them, I think I kind of broke the original espnet conda environment, so I started from the new espnet2 environment from the beginning installation to ask for some safe advice to proceed. Thank you.

**Show the `check_install.py` status by using the following command**
```
cd <espnet-root>/tools
. ./activate_python.sh; python3 check_install.py
```
```
(espnet2) [jsunc@bridges2-login014 tools]$ . ./activate_python.sh; python3 check_install.py
[x] python=3.10.16 (main, Dec 11 2024, 16:24:50) [GCC 11.2.0]

Python modules:
[x] torch=2.3.0
[ ] torch cuda
[x] torch cudnn=8902
[x] torch nccl
[x] chainer=6.0.0
[ ] chainer cuda
[ ] chainer cudnn
[ ] cupy
[x] torchaudio=2.3.0
[x] torch_optimizer=0.3.0
[ ] warprnnt_pytorch
[ ] chainer_ctc
[ ] pyopenjtalk
[ ] tdmelodic_pyopenjtalk
[ ] kenlm
[ ] mmseg
[x] espnet=202412
[x] numpy=1.23.5
[ ] fairseq
[ ] phonemizer
[ ] gtn
[x] s3prl=0.4.16
[x] transformers=4.47.0
[ ] speechbrain
[ ] k2
[ ] longformer
[ ] nlg-eval
[ ] datasets
[ ] pykeops
[ ] whisper
[ ] RawNet3
[ ] reazonspeech
[ ] discrete_speech_metrics
[ ] muskits

Executables:
[ ] sclite
[x] sph2pipe
[ ] PESQ
[ ] BeamformIt
[ ] spm_train
[ ] spm_encode
[ ] spm_decode
[x] sox=14.4.2
[x] ffmpeg=6.1.1
[x] flac=1.3.4
[x] cmake=3.26.5
[ ] Kaldi
```

```
**Basic environments:**
- OS information: Linux 4.18.0-553.22.1.el8_10.x86_64 #1 SMP Wed Sep 11 18:02:00 EDT 2024 x86_64
- python version: \`3.10.16 (main, Dec 11 2024, 16:24:50) [GCC 11.2.0]\`
- espnet version: \`espnet 202412\`
- pytorch version: \`pytorch 2.3.0\`
- Git hash: `70d2c9cd76ea066fe5c84d148799b6c94e58f57c`
- Commit date: `Thu Dec 12 00:28:13 2024 -0500`
```
You can obtain them by the following command
```
cd <espnet-root>/tools
. ./activate_python.sh

echo "- OS information: `uname -mrsv`"

python3 << EOF
import sys, espnet, torch
pyversion = sys.version.replace('\n', ' ')
print(f"""- python version: \`{pyversion}\`
- espnet version: \`espnet {espnet.__version__}\`
- pytorch version: \`pytorch {torch.__version__}\`""")
EOF
cat << EOF
- Git hash: \`$(git rev-parse HEAD)\`
  - Commit date: \`$(git log -1 --format='%cd')\`
EOF
```

**Environments from `torch.utils.collect_env`:**
e.g.,
```
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: CentOS Linux release 7.5.1804 (Core)
GCC version: (GCC) 7.2.0
CMake version: version 2.8.12.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: TITAN RTX
GPU 1: TITAN RTX
GPU 2: TITAN RTX
GPU 3: TITAN RTX

Nvidia driver version: 440.33.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.0
[pip3] torch==1.4.0
[pip3] torch-complex==0.1.1
[pip3] torch-optimizer==0.0.1a14
[pip3] torchaudio==0.4.0
[pip3] warprnnt-pytorch==0.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.1                      217
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.1.0            py37h23d657b_0
[conda] mkl_random                1.1.1            py37h0573a6f_0
[conda] pytorch                   1.4.0           py3.7_cuda10.0.130_cudnn7.6.3_0    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.0                    pypi_0    pypi
[conda] torch-complex             0.1.1                    pypi_0    pypi
[conda] torch-optimizer           0.0.1a14                 pypi_0    pypi
[conda] torchaudio                0.4.0                    pypi_0    pypi
[conda] warprnnt-pytorch          0.1                      pypi_0    pypi
```
You can obtain them by the following command

```
cd <espnet-root>/tools
. ./activate_python.sh
python3 -m torch.utils.collect_env
```
```
CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              40
On-line CPU(s) list: 0-39
Thread(s) per core:  1
Core(s) per socket:  20
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz                                                
Stepping:            4
CPU MHz:             2400.000
BogoMIPS:            4800.00
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            28160K
NUMA node0 CPU(s):   0-19
NUMA node1 CPU(s):   20-39
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi
mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl smx est tm2 ssse3 sdbg fma cx16
xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm
3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke md_clear flush_l1d arch_capabilities                             

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-ranger==0.1.1
[pip3] torch==2.3.0
[pip3] torch-complex==0.4.4
[pip3] torch-optimizer==0.3.0
[pip3] torchaudio==2.3.0
[pip3] triton==2.3.0
[conda] blas                      1.0                         mkl                                            
[conda] mkl                       2023.1.0         h213fc3f_46344                                            
[conda] mkl-service               2.4.0           py310h5eee18b_1                                            
[conda] mkl_fft                   1.3.11          py310h5eee18b_0                                            
[conda] mkl_random                1.2.8           py310h1128e8f_0                                            
[conda] numpy                     1.23.5                   pypi_0    pypi                                    
[conda] pytorch                   2.3.0           py3.10_cuda12.1_cudnn8.9.2_0    pytorch                    
[conda] pytorch-cuda              12.1                 ha16c6d3_6    pytorch                                 
[conda] pytorch-mutex             1.0                        cuda    pytorch                                 
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi                                    
[conda] torch-complex             0.4.4                    pypi_0    pypi                                    
[conda] torch-optimizer           0.3.0                    pypi_0    pypi                                    
[conda] torchaudio                2.3.0               py310_cu121    pytorch                                 
[conda] torchtriton               2.3.0                     py310    pytorch     
```

**To Reproduce**
Steps to reproduce the behavior by showing us the specific installation commands with their arguments, e.g.,
```
cd <espnet-root>/tools
make TH_VERSION
```
```
**Error logs**
Paste the error logs. If applicable, add screenshots to help explain your problem.
This is the error when I tried to run the training use the external wavLM in s3prl library, actually I installed the s3prl as shown in the checklist 
```
```
/ocean/projects/cis210027p/jsunc/espnet/tools/miniconda/envs/espnet2/bin/python3 /ocean/projects/cis210027p/jsunc/espnet/espnet2/bin/asr_train.py --use_preprocessor true --bpemodel data/en_token_list/bpe_unigram3436/bpe.model --token_type bpe --token_list data/en_token_list/bpe_unigram3436/tokens.txt --non_linguistic_symbols none --cleaner none --g2p none --valid_data_path_and_name_and_type dump/raw/dev_non_train/wav.scp,speech,kaldi_ark --valid_shape_file exp/asr_stats_raw_en_bpe3436_sp/valid/speech_shape --resume true --ignore_init_mismatch false --fold_length 80000 --output_dir exp/asr_train_asr_wavlm_transformer_raw_en_bpe3436_sp --config conf/train_asr_wavlm_transformer.yaml --frontend_conf fs=16k --train_data_path_and_name_and_type dump/raw/dev_train_sp/wav.scp,speech,kaldi_ark --train_shape_file exp/asr_stats_raw_en_bpe3436_sp/train/speech_shape --fold_length 150 --train_data_path_and_name_and_type dump/raw/dev_train_sp/text,text,text --train_shape_file exp/asr_stats_raw_en_bpe3436_sp/train/text_shape.bpe --valid_data_path_and_name_and_type dump/raw/dev_non_train/text,text,text --valid_shape_file exp/asr_stats_raw_en_bpe3436_sp/valid/text_shape.bpe --ngpu 1 --multiprocessing_distributed True
Failed to import Flash Attention, using ESPnet default: No module named 'flash_attn_2_cuda'
Vocabulary size: 3436
/ocean/projects/cis210027p/jsunc/espnet/tools/miniconda/envs/espnet2/lib/python3.10/site-packages/s3prl/upstream/byol_s/byol_a/common.py:20: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("sox_io")
Traceback (most recent call last):
  File "/ocean/projects/cis210027p/jsunc/espnet/tools/miniconda/envs/espnet2/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1793, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/ocean/projects/cis210027p/jsunc/espnet/tools/miniconda/envs/espnet2/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/ocean/projects/cis210027p/jsunc/espnet/tools/miniconda/envs/espnet2/lib/python3.10/site-packages/transformers/models/hubert/modeling_hubert.py", line 44, in <module>
    from ...modeling_flash_attention_utils import _flash_attention_forward
  File "/ocean/projects/cis210027p/jsunc/espnet/tools/miniconda/envs/espnet2/lib/python3.10/site-packages/transformers/modeling_flash_attention_utils.py", line 30, in <module>
    from flash_attn.bert_padding import index_first_axis, pad_input, unpad_input  # noqa
  File "/ocean/projects/cis210027p/jsunc/espnet/tools/miniconda/envs/espnet2/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/ocean/projects/cis210027p/jsunc/espnet/tools/miniconda/envs/espnet2/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 15, in <module>
    import flash_attn_2_cuda as flash_attn_gpu
ModuleNotFoundError: No module named 'flash_attn_2_cuda'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ocean/projects/cis210027p/jsunc/espnet/tools/miniconda/envs/espnet2/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/ocean/projects/cis210027p/jsunc/espnet/tools/miniconda/envs/espnet2/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/ocean/projects/cis210027p/jsunc/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/ocean/projects/cis210027p/jsunc/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/ocean/projects/cis210027p/jsunc/espnet/espnet2/tasks/abs_task.py", line 1210, in main
    cls.main_worker(args)
  File "/ocean/projects/cis210027p/jsunc/espnet/espnet2/tasks/abs_task.py", line 1342, in main_worker
    model = cls.build_model(args=args)
  File "/ocean/projects/cis210027p/jsunc/espnet/espnet2/tasks/asr.py", line 532, in build_model
    frontend = frontend_class(**args.frontend_conf)
  File "/ocean/projects/cis210027p/jsunc/espnet/espnet2/asr/frontend/s3prl.py", line 32, in __init__
    raise e
  File "/ocean/projects/cis210027p/jsunc/espnet/espnet2/asr/frontend/s3prl.py", line 28, in __init__
    from s3prl.nn import Featurizer, S3PRLUpstream
  File "/ocean/projects/cis210027p/jsunc/espnet/tools/miniconda/envs/espnet2/lib/python3.10/site-packages/s3prl/nn/__init__.py", line 12, in <module>
    from .upstream import Featurizer, S3PRLUpstream
  File "/ocean/projects/cis210027p/jsunc/espnet/tools/miniconda/envs/espnet2/lib/python3.10/site-packages/s3prl/nn/upstream.py", line 14, in <module>
    from s3prl import hub
  File "/ocean/projects/cis210027p/jsunc/espnet/tools/miniconda/envs/espnet2/lib/python3.10/site-packages/s3prl/hub.py", line 16, in <module>
    from s3prl.upstream.hf_hubert.hubconf import *
  File "/ocean/projects/cis210027p/jsunc/espnet/tools/miniconda/envs/espnet2/lib/python3.10/site-packages/s3prl/upstream/hf_hubert/hubconf.py", line 1, in <module>
    from .expert import UpstreamExpert as _UpstreamExpert
  File "/ocean/projects/cis210027p/jsunc/espnet/tools/miniconda/envs/espnet2/lib/python3.10/site-packages/s3prl/upstream/hf_hubert/expert.py", line 4, in <module>
    from transformers import HubertModel, Wav2Vec2FeatureExtractor
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/ocean/projects/cis210027p/jsunc/espnet/tools/miniconda/envs/espnet2/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1782, in __getattr__
    value = getattr(module, name)
  File "/ocean/projects/cis210027p/jsunc/espnet/tools/miniconda/envs/espnet2/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1781, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/ocean/projects/cis210027p/jsunc/espnet/tools/miniconda/envs/espnet2/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1795, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.hubert.modeling_hubert because of the following error (look up to see its traceback):
No module named 'flash_attn_2_cuda'
Error: S3PRL is not properly installed.
Please install S3PRL: cd ${MAIN_ROOT}/tools && make s3prl.done
# Accounting: time=22 threads=1
# Ended (code 1) at Thu Dec 12 19:28:42 EST 2024, elapsed time 22 seconds
```

**Comment by uwanny** [comment]
Acutally, thanks @ftshijt and @jctian98 solution. I am using the V100 GPU, according to https://github.com/Dao-AILab/flash-attention/issues/1222, V100 does not support flash-attn, so it's meaningless to debug on problem related to flash-attn. The easiest solution is just "pip uninstall flash-attn" and run again, in this case, transformers package will not detect the flash-attn and will use default attn.
