### ISSUE TITLE
Cannot find `_kalpy` required by MFA

### ISSUE THREAD

**Issue by unilight** [espnet/espnet#5985]
**Describe the bug**
I am trying to apply MFA to the JVS corpus. I installed MFA with `make mfa.done`.
Then I modified `egs2/ljspeech/tts1/local/run_mfa.sh` to make it work on JVS.
The error log (see below) says that it cannot find `_kalpy`.
I checked `tools/venv/lib/python3.10/site-packages`, and indeed it is not installed.

I see in `tools/installers/install_mfa.sh` that MFA is installed through pip, but not conda, as the official homepage recommends.
I am guessing this is the reason why kalpy is not properly installed, because when I ran `tools/installers/install_mfa.sh`, I did not see kalpy get installed either.
The official homepage of kalpy https://pypi.org/project/kalpy-kaldi/ also recommends to install by conda.
I tried to install MFA in my local conda environment, and `mfa validate` runs successfully (which means kalpy is also properly installed and found).

I am truly grateful to whoever wrote this function in ESPnet, but I am just wondering how you got it working...???

**Basic environments:**
 - OS information: Linux
 - python version: python3.10
 - espnet version: latest
 - pytorch version: 2.3.0, but does not matter anyway

**Task information:**
 - Task: TTS
 - Recipe: jvs/tts1
 - ESPnet2

**Error logs**
```
# mfa validate -j 12 --clean --skip_acoustics -t data/local/mfa/tmp data/local/mfa/corpus japanese_mfa japanese_mfa --brackets "" 
# Started at Tue Dec 17 17:24:26 JST 2024
#
Traceback (most recent call last):
  File "/data/group1/z44476r/Experiments/espnet/tools/venv/bin/mfa", line 5, in <module>
    from montreal_forced_aligner.command_line.mfa import mfa_cli
  File "/data/group1/z44476r/Experiments/espnet/tools/venv/lib/python3.10/site-packages/montreal_forced_aligner/__init__.py", line 4, in <module>
    import montreal_forced_aligner.acoustic_modeling as acoustic_modeling
  File "/data/group1/z44476r/Experiments/espnet/tools/venv/lib/python3.10/site-packages/montreal_forced_aligner/acoustic_modeling/__init__.py", line 7, in <module>
    from montreal_forced_aligner.acoustic_modeling.base import AcousticModelTrainingMixin  # noqa
  File "/data/group1/z44476r/Experiments/espnet/tools/venv/lib/python3.10/site-packages/montreal_forced_aligner/acoustic_modeling/base.py", line 11, in <module>
    from _kalpy.gmm import AccumAmDiagGmm
ModuleNotFoundError: No module named '_kalpy'
```

**Comment by Fhrozen** [comment]
@sw005320 Got it.

**Comment by unilight** [comment]
@Fhrozen Thank you for responding. Yes I am aware of that issue, but that's not the error I encountered. It's simply that `_kalpy` is not installed. I wonder if `_kalpy` can be installed by installing MFA from the github repo, instead of from conda.

I also tried modifying this line from https://github.com/espnet/espnet/blob/master/tools/installers/install_mfa.sh#L23:
```
pip install --ignore-requires-python git+https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner.git@v2.0.6
```
to
```
pip install --ignore-requires-python git+https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner.git
```
But I still get the same error: the system cannot find `_kalpy`, and I just cannot find it in `tools/venv/lib/python3.10/site-packages`.

I tried to install MFA from conda, and I can locate `_kalpy` in `~/miniconda3/lib/python3.10/site-packages/kalpy`.

Hope these information help.

**Comment by sarem-h** [comment]
@unilight, ever fixed the issue?

**Comment by Fhrozen** [comment]
@sarem-h Still under review. 
I will be adding a PR around this week.

**Comment by ruobingli1103** [comment]
conda create -n aligner python=3.10 -y
conda activate aligner

conda install -c conda-forge mamba -y
mamba install -c conda-forge montreal-forced-aligner -y --override-channels

mfa --help # done

**Comment by sw005320** [comment]
Thanks for the TIPS, @ruobingli1103 

@Fhrozen, what is the status of this issue?

**Comment by Fhrozen** [comment]
I will be reviewing this week

**Comment by Fhrozen** [comment]
@ruobingli1103 
I finished the initial evaluation of MFA and included some comments in the installation.
You can follow PR at #6441

@sw005320
Some details about MFA that may affect the support and usage of this tool:
- MFA has changed, and recent versions require additional modification to use it. Also, I found some issues when I tried to use the latest version (3.3.9), including the removal of "brackets" and problems with the temporary directory.
- Currently, the easy approach is to keep the current version. However, the current version also has some compatibility issues because it requires the package `imp,` which seems to be deprecated since Python >= 3.11. Installing with pip is complicated because it requires missing packages; therefore, conda is the simplest way to use MFA.
- ESPnet is moving towards a Kaldi-free environment. However, MFA needs Kaldi. I would recommend developing a different alignment tool that can be used similarly to MFA. 

I am testing (implementing) a tool that could replace MFA. Of course, this is only a proposal.

**Comment by ruobingli1103** [comment]
@Fhrozen Thanks for the evaluation!
