### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by zh794390558** [espnet/espnet#605]
What can do with this error?

```
You should consider upgrading via the 'pip install --upgrade pip' command.
612 . venv/bin/activate && pip install cupy==5.0.0
Collecting cupy==5.0.0
614   Downloading http://mirrors.aliyun.com/pypi/packages/cc/60/74bce24d1570cd974567599862ebf15d8719504b09766a6cc1a0d10435a5/cupy-5.0.0.tar.gz (2.4MB)
615     Complete output from command python setup.py egg_info:
616     Options: {'package_name': 'cupy', 'long_description': None, 'wheel_libs': [], 'no_rpath': False, 'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False}
617     **************************************************
618     *** WARNING: nvcc path != CUDA_PATH
619     *** WARNING: nvcc path: /usr/local/cuda
620     *** WARNING: CUDA_PATH: /nfs/project/tools/anaconda3/pkgs/cudnn-7.2.1-cuda9.2_0/
621     **************************************************
622 
623     -------- Configuring Module: cuda --------
624     cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
625     /tmp/tmpje1vjwke/a.cpp:1:23: fatal error: cublas_v2.h: No such file or directory
626      #include <cublas_v2.h>
627                            ^
628     compilation terminated.
629     command 'gcc' failed with exit status 1
630 
631     ************************************************************
632     * CuPy Configuration Summary                               *
633     ************************************************************
634 
635     Build Environment:
636       Include directories: ['/nfs/project/tools/anaconda3/pkgs/cudnn-7.2.1-cuda9.2_0/include']
637       Library directories: ['/nfs/project/tools/anaconda3/pkgs/cudnn-7.2.1-cuda9.2_0/lib']
638       nvcc command       : (not found)
639 
640     Environment Variables:
641       CFLAGS          : (none)
642       LDFLAGS         : (none)
643       LIBRARY_PATH    : (none)
644       CUDA_PATH       : /nfs/project/tools/anaconda3/pkgs/cudnn-7.2.1-cuda9.2_0/
645       NVTOOLSEXT_PATH : (none)
646       NVCC            : (none)
647 
648     Modules:
649       cuda      : No
650         -> Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'cufft.h', 'curand.h', 'cusparse.h', 'nvrtc.h']
651         -> Check your CFLAGS environment variable.
652 
653     ERROR: CUDA could not be found on your system.
654     Please refer to the Installation Guide for details:
655     https://docs-cupy.chainer.org/en/stable/install.html
656 
657     ************************************************************
658 
659     Traceback (most recent call last):
660       File "<string>", line 1, in <module>
661       File "/tmp/pip-build-3d1ehm5b/cupy/setup.py", line 118, in <module>
662         ext_modules = cupy_setup_build.get_ext_modules()
663       File "/tmp/pip-build-3d1ehm5b/cupy/cupy_setup_build.py", line 588, in get_ext_modules
664         extensions = make_extensions(arg_options, compiler, use_cython)
665       File "/tmp/pip-build-3d1ehm5b/cupy/cupy_setup_build.py", line 384, in make_extensions
666         raise Exception('Your CUDA environment is invalid. '
667     Exception: Your CUDA environment is invalid. Please check above error log.
668 
669     ----------------------------------------
670 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3d1ehm5b/cupy/
671 You are using pip version 9.0.1, however version 19.0.3 is available.
672 You should consider upgrading via the 'pip install --upgrade pip' command.
673 make: *** [espnet.done] Error 1
```

**Comment by zh794390558** [comment]
```
CUDA_PATH=/usr/local/cuda pip install --pre cupy-cuda100
```
this work for cuda10 on my host

**Comment by zh794390558** [comment]
```
. venv/bin/activate; cd warp-ctc/pytorch_binding && python setup.py install # maybe need to: apt-get install python-dev
running install
running bdist_egg
running egg_info
creating warpctc_pytorch.egg-info
writing warpctc_pytorch.egg-info/PKG-INFO
writing dependency_links to warpctc_pytorch.egg-info/dependency_links.txt
writing top-level names to warpctc_pytorch.egg-info/top_level.txt
writing manifest file 'warpctc_pytorch.egg-info/SOURCES.txt'
reading manifest file 'warpctc_pytorch.egg-info/SOURCES.txt'
writing manifest file 'warpctc_pytorch.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/warpctc_pytorch
copying warpctc_pytorch/__init__.py -> build/lib.linux-x86_64-3.6/warpctc_pytorch
running build_ext
Traceback (most recent call last):
  File "setup.py", line 64, in <module>
    cmdclass={'build_ext': BuildExtension}
  File "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
    _build_ext.run(self)
  File "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 232, in build_extensions
    self._check_abi()
  File "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 370, in _check_abi
    check_compiler_abi_compatibility(compiler)
  File "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 162, in check_compiler_abi_compatibility
    if not check_compiler_ok_for_platform(compiler):
  File "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 138, in check_compiler_ok_for_platform
    which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
  File "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['which', 'x86_64-conda_cos6-linux-gnu-c++']' returned non-zero exit status 1.
make: *** [warp-ctc.done] Error 1
```

**Comment by zh794390558** [comment]
Need gcc >= 4.9 , using this to update gcc on centOS7
```
[root@ ~]# yum install centos-release-scl -y
[root@ ~]# yum install devtoolset-3-toolchain -y
[root@ ~]# scl enable devtoolset-3 bash
```

**Comment by zh794390558** [comment]
https://github.com/RcppCore/Rcpp/issues/770

`conda install gxx_linux-64`
provides x86_64-conda_cos6-linux-gnu-c++

**Comment by zh794390558** [comment]
```
. venv/bin/activate; cd chainer_ctc && pip install .
Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Processing /nfs/cold_project/dataset/opensource/librispeech/espnet/tools/chainer_ctc
Building wheels for collected packages: chainer-ctc
  Building wheel for chainer-ctc (setup.py) ... error
  Complete output from command /nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-gc6qbh07/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-e1b4_nsy --python-tag cp36:
  /nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/distutils/extension.py:131: UserWarning: Unknown Extension options: 'include'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/chainer_ctc
  copying chainer_ctc/gpu_kernel.py -> build/lib.linux-x86_64-3.6/chainer_ctc
  copying chainer_ctc/ctc.py -> build/lib.linux-x86_64-3.6/chainer_ctc
  copying chainer_ctc/warpctc.py -> build/lib.linux-x86_64-3.6/chainer_ctc
  copying chainer_ctc/__init__.py -> build/lib.linux-x86_64-3.6/chainer_ctc
  creating build/lib.linux-x86_64-3.6/chainer_ctc/src
  copying chainer_ctc/src/__init__.py -> build/lib.linux-x86_64-3.6/chainer_ctc/src
  running build_ext
  cythoning chainer_ctc/src/ctc_cpu.pyx to chainer_ctc/src/ctc_cpu.cpp
  /nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib/python3.6/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-req-build-gc6qbh07/chainer_ctc/src/ctc_cpu.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  warning: chainer_ctc/src/ctc_cpu.pyx:60:12: Unsigned index type not allowed before OpenMP 3.0
  warning: chainer_ctc/src/ctc_cpu.pyx:104:12: Unsigned index type not allowed before OpenMP 3.0
  warning: chainer_ctc/src/ctc_cpu.pyx:149:8: Unsigned index type not allowed before OpenMP 3.0
  building 'chainer_ctc.src.ctc_cpu' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/chainer_ctc
  creating build/temp.linux-x86_64-3.6/chainer_ctc/src
  /nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -fPIC -I/home/luban/.local/lib/python3.6/site-packages/numpy/core/include -I/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/include/python3.6m -c chainer_ctc/src/ctc_cpu.cpp -o build/temp.linux-x86_64-3.6/chainer_ctc/src/ctc_cpu.o
  cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
  In file included from /home/luban/.local/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1821:0,
                   from /home/luban/.local/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                   from /home/luban/.local/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from chainer_ctc/src/ctc_cpu.cpp:607:
  /home/luban/.local/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it by " \
    ^~~~~~~
  chainer_ctc/src/ctc_cpu.cpp: In function 'PyObject* __pyx_pf_11chainer_ctc_3src_7ctc_cpu_c_calc_alpha(PyObject*, PyArrayObject*, PyArrayObject*, int)':
  chainer_ctc/src/ctc_cpu.cpp:2467:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                     from /home/luban/.local/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /home/luban/.local/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from chainer_ctc/src/ctc_cpu.cpp:607:
    /home/luban/.local/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^~~~~~~
    chainer_ctc/src/ctc_cpu.cpp: In function 'PyObject* __pyx_pf_11chainer_ctc_3src_7ctc_cpu_c_calc_alpha(PyObject*, PyArrayObject*, PyArrayObject*, int)':
    chainer_ctc/src/ctc_cpu.cpp:2467:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (__pyx_t_8 = 0; __pyx_t_8 < __pyx_t_7; __pyx_t_8+=1) {
                           ~~~~~~~~~~^~~~~~~~~~~
    chainer_ctc/src/ctc_cpu.cpp:2604:66: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                                       __pyx_t_20 = (((__pyx_v_l % 2) == __pyx_v_blank_symbol) != 0);
                                                      ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
    chainer_ctc/src/ctc_cpu.cpp: In function 'PyObject* __pyx_pf_11chainer_ctc_3src_7ctc_cpu_2c_calc_beta(PyObject*, PyArrayObject*, PyArrayObject*, int)':
    chainer_ctc/src/ctc_cpu.cpp:3215:56: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                                   __pyx_t_11 = ((__pyx_v_t == (__pyx_v_T - 1)) != 0);
                                                  ~~~~~~~~~~^~~~~~~~~~~~~~~~~~
    chainer_ctc/src/ctc_cpu.cpp:3225:58: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                                     __pyx_t_11 = ((__pyx_v_l > (__pyx_v_L - 3)) != 0);
                                                    ~~~~~~~~~~^~~~~~~~~~~~~~~~~
    chainer_ctc/src/ctc_cpu.cpp:3283:58: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                                     __pyx_t_11 = ((__pyx_v_l < (__pyx_v_L - 2)) != 0);
                                                    ~~~~~~~~~~^~~~~~~~~~~~~~~~~
    chainer_ctc/src/ctc_cpu.cpp:3293:66: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                                       __pyx_t_18 = (((__pyx_v_l % 2) == __pyx_v_blank_symbol) != 0);
                                                      ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
    chainer_ctc/src/ctc_cpu.cpp:3419:58: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                                     __pyx_t_11 = ((__pyx_v_l == (__pyx_v_L - 2)) != 0);
                                                    ~~~~~~~~~~^~~~~~~~~~~~~~~~~~
    chainer_ctc/src/ctc_cpu.cpp: In function 'PyObject* __pyx_pf_11chainer_ctc_3src_7ctc_cpu_4c_calc_label_grads(PyObject*, PyArrayObject*, PyArrayObject*, PyArrayObject*, PyArrayObject*)':
    chainer_ctc/src/ctc_cpu.cpp:3903:61: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                                 for (__pyx_t_11 = 0; __pyx_t_11 < __pyx_t_10; __pyx_t_11+=1) {
                                                      ~~~~~~~~~~~^~~~~~~~~~~~
    chainer_ctc/src/ctc_cpu.cpp:3957:61: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                                 for (__pyx_t_11 = 0; __pyx_t_11 < __pyx_t_10; __pyx_t_11+=1) {
                                                      ~~~~~~~~~~~^~~~~~~~~~~~
    chainer_ctc/src/ctc_cpu.cpp: In function 'PyObject* __pyx_pf_11chainer_ctc_3src_7ctc_cpu_8c_best_path(PyObject*, PyArrayObject*)':
    chainer_ctc/src/ctc_cpu.cpp:4497:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (__pyx_t_14 = 1; __pyx_t_14 < __pyx_t_8; __pyx_t_14+=1) {
                            ~~~~~~~~~~~^~~~~~~~~~~
    /nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/bin/x86_64-conda_cos6-linux-gnu-c++ -pthread -shared -L/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib -Wl,-rpath=/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib,--no-as-needed -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 build/temp.linux-x86_64-3.6/chainer_ctc/src/ctc_cpu.o -L/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib -lpython3.6m -o build/lib.linux-x86_64-3.6/chainer_ctc/src/ctc_cpu.cpython-36m-x86_64-linux-gnu.so
    skipping 'chainer_ctc/src/warp_ctc.cpp' Cython extension (up-to-date)
    building 'chainer_ctc.src.warp_ctc' extension
    /nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -fPIC -Iext/warp-ctc/include -I/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/include/python3.6m -c chainer_ctc/src/warp_ctc.cpp -o build/temp.linux-x86_64-3.6/chainer_ctc/src/warp_ctc.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    /nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/bin/x86_64-conda_cos6-linux-gnu-c++ -pthread -shared -L/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib -Wl,-rpath=/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib,--no-as-needed -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 build/temp.linux-x86_64-3.6/chainer_ctc/src/warp_ctc.o -Lext/warp-ctc/build -L/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/lib -lwarpctc -lpython3.6m -o build/lib.linux-x86_64-3.6/chainer_ctc/src/warp_ctc.cpython-36m-x86_64-linux-gnu.so
    /nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lwarpctc
    collect2: error: ld returned 1 exit status
    error: command '/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/bin/x86_64-conda_cos6-linux-gnu-c++' failed with exit status 1
    
    ----------------------------------------
Command "/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-gc6qbh07/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-3uz5aa0w/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-gc6qbh07/
make: *** [chainer_ctc.done] Error 1
```

**Comment by zh794390558** [comment]
too hard to install

` make KALDI=/packages/kaldi-master PYTHON_VERSION=3.6 `

**Comment by zh794390558** [comment]
download ` pytorch-1.0.0-py3.6_cuda9.0.176_cudnn7.4.1_1.tar.bz2` and `mkl-2019.1-144.tar.bz2` manual.

**Comment by zh794390558** [comment]
`cd chainer_ctc && chmod +x install_warp-ctc.sh && ./install_warp-ctc.sh` error when `scl enable devtoolset-3 bash`

```
/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/type_traits(2971): error: "constexpr" is not valid here

/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/type_traits(2974): error: "is_default_constructible_v" is not a function or static data member

/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/type_traits(2974): error: "constexpr" is not valid here

/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/type_traits(2977): error: "is_copy_constructible_v" is not a function or static data member

/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/type_traits(2977): error: "constexpr" is not valid here

/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/type_traits(2980): error: "is_move_constructible_v" is not a function or static data member

/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/type_traits(2980): error: "constexpr" is not valid here

/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/type_traits(2983): error: "is_assignable_v" is not a function or static data member

/nfs/cold_project/dataset/opensource/librispeech/espnet/tools/venv/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/type_traits(2983): error: "constexpr" is not valid here

Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_00001bec_00000000-12_reduce.compute_62.cpp1.ii".
Compilation terminated.
CMake Error at warpctc_generated_reduce.cu.o.cmake:264 (message):
  Error generating file
  /nfs/cold_project/dataset/opensource/librispeech/espnet/tools/chainer_ctc/ext/warp-ctc/build/CMakeFiles/warpctc.dir/src/./warpctc_generated_reduce.cu.o


make[2]: *** [CMakeFiles/warpctc.dir/src/./warpctc_generated_reduce.cu.o] Error 1
make[1]: *** [CMakeFiles/warpctc.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by zh794390558** [comment]
```
[install-mecab-ipadic-NEologd] : Start..
[install-mecab-ipadic-NEologd] : Check the existance of libraries
[install-mecab-ipadic-NEologd] :     find => ok
[install-mecab-ipadic-NEologd] :     sort => ok
[install-mecab-ipadic-NEologd] :     head => ok
[install-mecab-ipadic-NEologd] :     cut => ok
[install-mecab-ipadic-NEologd] :     egrep => ok
[install-mecab-ipadic-NEologd] :     mecab => ok
[install-mecab-ipadic-NEologd] :     mecab-config => ok
[install-mecab-ipadic-NEologd] :     make => ok
[install-mecab-ipadic-NEologd] :     curl => ok
[install-mecab-ipadic-NEologd] :     sed => ok
[install-mecab-ipadic-NEologd] :     cat => ok
[install-mecab-ipadic-NEologd] :     diff => ok
[install-mecab-ipadic-NEologd] :     tar => ok
[install-mecab-ipadic-NEologd] :     unxz => ok
[install-mecab-ipadic-NEologd] :     xargs => ok
[install-mecab-ipadic-NEologd] :     grep => ok
[install-mecab-ipadic-NEologd] :     iconv => ok
[install-mecab-ipadic-NEologd] :     patch => ok
[install-mecab-ipadic-NEologd] :     which => ok
[install-mecab-ipadic-NEologd] :     file => ok
[install-mecab-ipadic-NEologd] :     openssl => ok
[install-mecab-ipadic-NEologd] :     awk => ok

[install-mecab-ipadic-NEologd] : mecab-ipadic-NEologd is already up-to-date

[install-mecab-ipadic-NEologd] : mecab-ipadic-NEologd will be install to /nfs/cold_project/dataset/opensource/librispeech/espnet/tools/mecab/mecab-ipadic-neologd

[install-mecab-ipadic-NEologd] : Make mecab-ipadic-NEologd
[make-mecab-ipadic-NEologd] : Start..
[make-mecab-ipadic-NEologd] : Check local seed directory
[make-mecab-ipadic-NEologd] : Check local seed file
[make-mecab-ipadic-NEologd] : Check local build directory
[make-mecab-ipadic-NEologd] : create /nfs/cold_project/dataset/opensource/librispeech/espnet/tools/mecab/mecab-ipadic-neologd/libexec/../build
[make-mecab-ipadic-NEologd] : Download original mecab-ipadic file
make: *** [mecab.done] Error 7
```

**Comment by zh794390558** [comment]
```
INFO: library availableness check start.
INFO: # libraries to be checked = 8
INFO: --> espnet is installed.
INFO: --> kaldiio is installed.
INFO: --> matplotlib is installed.
INFO: --> torch is installed.
INFO: --> chainer is installed.
INFO: --> cupy is installed.
INFO: --> chainer_ctc is installed.
INFO: --> warpctc_pytorch is installed.
INFO: library availableness check done.
INFO: 8 / 8 libraries are correctly installed.
INFO: library version check start.
INFO: # libraries to be checked = 4
WARNING: --> torch version is not matched (1.0.0==0.4.1).
INFO: --> chainer version is matched.
WARNING: --> cupy version is not matched (5.2.0==5.0.0).
INFO: --> warpctc_pytorch version is matched.
INFO: library version check done.
INFO: 2 / 4 libraries are correct version.
INFO: please try to setup again and then re-run this script.
```
Does this matter?

**Comment by kan-bayashi** [comment]
torch version is OK. This is my bug. I will fix it.
cupy version should be the same as the chainer version (v5.0.0)
But if you want to use pytorch backend, maybe it is OK.

**Comment by zh794390558** [comment]
@kan-bayashi Thanks.

```
diff --git a/tools/Makefile b/tools/Makefile
index 1dc0a4c..53d2df3 100644
--- a/tools/Makefile
+++ b/tools/Makefile
@@ -53,10 +53,14 @@ venv: miniconda.sh
        . venv/bin/activate && conda install -y python=$(PYTHON_VERSION)
        . venv/bin/activate && conda info -a
 espnet.done: venv
-       . venv/bin/activate && conda install -y pytorch=$(TH_VERSION) -c pytorch
-       . venv/bin/activate && conda install -y matplotlib
+       . venv/bin/activate && conda install -y matplotlib -c conda-forge
+       . venv/bin/activate && pip install --upgrade pip 
        . venv/bin/activate && pip install -e ..
-       . venv/bin/activate && pip install cupy==$(CUPY_VERSION) 
+       . venv/bin/activate && conda install -y gxx_linux-64
+       . venv/bin/activate && CUDA_PATH=/usr/local/cuda pip install --pre cupy-cuda100
+       . venv/bin/activate && conda install --offline ./mkl-2019.1-144.tar.bz2 
+       . venv/bin/activate && conda install --offline ./pytorch-1.0.0-py3.6_cuda9.0.176_cudnn7.4.1_1.tar.bz2 
+       #. venv/bin/activate && conda install -y pytorch=$(TH_VERSION) -c pytorch -c conda-forge  -c local
        touch espnet.done
 endif
 
@@ -78,9 +82,9 @@ warp-ctc.done: espnet.done
        if . venv/bin/activate && python -c 'import torch as t;assert t.__version__[0] == "1"' &> /dev/null; then \
         cd warp-ctc; git checkout -b pytorch-1.0.0 remotes/origin/pytorch-1.0.0; \
     fi
-       . venv/bin/activate; cd warp-ctc && mkdir build && cd build && cmake .. && make -j4 ; true
-       . venv/bin/activate; pip install cffi
-       . venv/bin/activate; cd warp-ctc/pytorch_binding && python setup.py install # maybe need to: apt-get install python-dev
+       . venv/bin/activate && cd warp-ctc && mkdir -p build && cd build && cmake .. && make -j4 ; true
+       . venv/bin/activate && pip install cffi
+       . venv/bin/activate && cd warp-ctc/pytorch_binding && python setup.py install # maybe need to: apt-get install python-dev
        touch warp-ctc.done
 
 chainer_ctc.done: espnet.done
```

**Comment by zh794390558** [comment]
@kan-bayashi If I have kaldi , pytorch with conda install on my host,  I only want to use pytorch backend, which target under Makefile should be installed? 

Which targets is only for egs ?

**Comment by kan-bayashi** [comment]
You should run `make KALDI=<your_kaldi_path>`.
Our scripts uses both chainer and pytorch even in the case of `backend=pytorch`.
And our scripts assume that python environment should be located in `tools/venv`.
So you should not use your conda located in other places.

**Comment by zh794390558** [comment]
Thanks, I see.
