### ISSUE TITLE
cannot wrapctc error for pytorch 1.0

### ISSUE THREAD

**Issue by eastonYi** [espnet/espnet#647]
I found this error when training the model with wrapctc under pytorch 1.0.0
```
Traceback (most recent call last):
  File "espnet/egs/hkust/asr1/../../../espnet/bin/asr_train.py", line 258, in <module>
    main(sys.argv[1:])
  File "espnet/egs/hkust/asr1/../../../espnet/bin/asr_train.py", line 246, in main
    train(args)
  File "espnet-0.3.0-py3.6.egg/espnet/asr/pytorch_backend/asr.py", line 234, in train
  File "espnet-0.3.0-py3.6.egg/espnet/nets/pytorch_backend/e2e_asr.py", line 99, in __init__
  File "/espnet-0.3.0-py3.6.egg/espnet/nets/pytorch_backend/ctc.py", line 116, in ctc_for
  File "espnet-0.3.0-py3.6.egg/espnet/nets/pytorch_backend/ctc.py", line 32, in __init__
TypeError: __init__() got an unexpected keyword argument 'reduce'
```
It is used in `espnet` as blew:
``` python
...
        elif self.ctc_type == 'warpctc':
            import warpctc_pytorch as warp_ctc
            self.ctc_loss = warp_ctc.CTCLoss(size_average=True, reduce=reduce)
...
```
However, I checked the up-to-date [wraper-ctc api](https://github.com/SeanNaren/warp-ctc/blob/pytorch_bindings/pytorch_binding/warpctc_pytorch/__init__.py) and 
``` python
...
class CTCLoss(Module):
    """
    Parameters:
        size_average (bool): normalize the loss by the batch size
            (default: `False`)
        length_average (bool): normalize the loss by the total number of frames
            in the batch. If `True`, supersedes `size_average`
            (default: `False`)
    """
    def __init__(self, blank=0, size_average=False, length_average=False):
...
```
It seems that espnet-0.3.0 is incompatible with wraper-ctc.

**Comment by kan-bayashi** [comment]
How did you install pytorch 1.0.0?
We change to warp-ctc version according to pytorch version during `make`.
https://github.com/espnet/espnet/blob/fc9037e432cbd496850b497af0e73d6525485ba0/tools/Makefile#L68-L81

So if you manually update pytorch version after setup, it will cause some errors.

**Comment by eastonYi** [comment]
I install Pytorch externally from it's official website. I will try the corresponding warp-ctc version. Thanks for your remind!
