### ISSUE TITLE
When infer the audio file with lang_model : AttributeError: 'list' object has no attribute 'char_list_dict'

### ISSUE THREAD

**Issue by jennifer1995** [espnet/espnet#732]
When I infer the audio file with lang_model, I come to the problem as below
```
stage 3: Decoding
run.pl: job failed, log is in /espnet/egs/aishell/asr1/decode/ID1058W0426/log/decode.log
```
The log is 
```
Traceback (most recent call last):
  File "/espnet/egs/aishell/asr1/decode/asr_recog.py", line 140, in <module>
    main(sys.argv[1:])
  File "/espnet/egs/aishell/asr1/decode/asr_recog.py", line 125, in main
    recog(args)
  File "/espnet/espnet/asr/chainer_backend/asr.py", line 508, in recog
    word_dict = rnnlm_args.char_list_dict
AttributeError: 'list' object has no attribute 'char_list_dict'
```

My command is as below
```
./recog_wav.sh \
--cmvn /espnet/egs/aishell/asr1/decode/cmvn.ark  \
--recog_model /espnet/egs/aishell/asr1/decode/model.acc.best  \
--lang_model /espnet/egs/aishell/asr1/decode/rnnlm.model.best  \
ID1058W0426.wav

```

**Comment by jennifer1995** [comment]
I got it
I should set `use_wordlm =false` to use lang_model
