### ISSUE TITLE
no module 'warpctc_pytorch'

### ISSUE THREAD

**Issue by desothier1** [espnet/espnet#741]
1.In spite of the comments read in this thread I keep getting the issue No module named 'warpctc_pytorch'
2.In espnet/tools/warp-ctc/build 'make' worked for cpu, but not for gpu:
CMakeFiles/test_gpu.dir/all » failed

2019-05-21 16:59:57,957 (asr_train:235) INFO: python path = (None)
2019-05-21 16:59:57,958 (asr_train:238) INFO: random seed = 1
2019-05-21 16:59:57,958 (asr_train:255) INFO: backend = pytorch
2019-05-21 17:00:08,476 (deterministic_utils:24) INFO: torch type check is disabled
2019-05-21 17:00:08,492 (asr:220) INFO: #input dims : 83
2019-05-21 17:00:08,493 (asr:221) INFO: #output dims: 30
2019-05-21 17:00:08,493 (asr:232) INFO: Multitask learning mode
2019-05-21 17:00:08,494 (e2e_asr:86) INFO: subsample: 1 2 2 1 1
2019-05-21 17:00:08,585 (encoders:236) INFO: BLSTM with every-layer projection for encoder
Traceback (most recent call last):
  File "/home/getalp/desotth/virtenv_pytorch/espnet3/espnet/egs/an4/asr1/../../../espnet/bin/asr_train.py", line 274, in <module>
    main(sys.argv[1:])
  File "/home/getalp/desotth/virtenv_pytorch/espnet3/espnet/egs/an4/asr1/../../../espnet/bin/asr_train.py", line 262, in main
    train(args)
  File "/data1/home/getalp/desotth/virtenv_pytorch/espnet3/espnet/espnet/asr/pytorch_backend/asr.py", line 235, in train
    model = E2E(idim, odim, args)
  File "/data1/home/getalp/desotth/virtenv_pytorch/espnet3/espnet/espnet/nets/pytorch_backend/e2e_asr.py", line 99, in __init__
    self.ctc = ctc_for(args, odim)
  File "/data1/home/getalp/desotth/virtenv_pytorch/espnet3/espnet/espnet/nets/pytorch_backend/ctc.py", line 116, in ctc_for
    ctc_type=args.ctc_type, reduce=reduce)
  File "/data1/home/getalp/desotth/virtenv_pytorch/espnet3/espnet/espnet/nets/pytorch_backend/ctc.py", line 31, in __init__
    import warpctc_pytorch as warp_ctc
ModuleNotFoundError: No module named 'warpctc_pytorch'

**Comment by sw005320** [comment]
Could you share the information more?
(Which version of ESPnet, conda or system python, python version, cuda version, Linux version, and distributions).

**Comment by desothier1** [comment]
Hi,
I finally managed to install it on a server with gcc 4.9.2 in one fell swoop, with all components functional :)

However, on several other servers on which i work, the  gcc version is higher than 4.9.2.
On one of the servers with gcc higher than 4.9.2, i can use the functionality of using several gpu s

I did the complete installation on a server with gcc 4.9.2.
About the usage + possibility to use several gpu s:
-I generate the fbank features on the 4.9.2 gcc server,
-and if I want to use several gpu s for training, I run it on the server with several gpu s (with a gcc compiler > 4.9.2), which seems to work

Initially, I tried an installation setup on a server with gcc >  4.9.2, where the 4.9.2 gcc compiler was in my home directory on a shared server. However, the warp ctc was not well installed and I had to install it separately... using https://github.com/SeanNaren/warp-ctc

ESPnet is a great tool, my compliments!

Are there any plans to adapt it to install it with a compiler > 4.9.2 ?

Thanks

**Comment by sw005320** [comment]
Good to know that you solved the issue by yourself, and thanks for your TIPS.

I'm actually using gcc 6.3,
```
$ gcc --version
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
```
and I don't have such installation issues.
(We have some error messages in pytorch warp-ctc for test code, but we just ignored them).

**Comment by Arafat4341** [comment]
Hello! 
I am setting up espnet. I don't have GPU.
I ran `make check_install CUPY_VERSION=''`

I get:
`WARNING: --> warpctc_pytorch is not installed.
INFO: library availableness check done.
INFO: 7 / 8 libraries are correctly installed.
INFO: please try to setup again and then re-run this script.
Makefile:163: recipe for target 'check_install' failed
make: *** [check_install] Error 1`

I can't find accurate way to install warpctc_pytorch.
Please help!
