### ISSUE TITLE
Chainer 6.0.0 caused some errors.

### ISSUE THREAD

**Issue by jnishi** [espnet/espnet#760]
There are several internal modification in version 6.0.0 and they cause errors when running with pytorch backends.

For example, `Evaluator.device` returns `GpuDevice` instead of `int` (in Chainer version 5.0.0).
This causes following error in `lm/pytorch_backend/lm.py`.
```
Exception in main training loop: '>=' not supported between instances of 'GpuDevice' and 'int'
Traceback (most recent call last):
  File "/home/christopher/gitrepos/espnet-1/tools/venv/lib/python3.6/site-packages/chainer/training/trainer.py", line 319, in run
    entry.extension(self)
  File "/home/christopher/gitrepos/espnet-1/tools/venv/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py", line 161, in __call__
    result = self.evaluate()
  File "/home/christopher/gitrepos/espnet-1/espnet/lm/pytorch_backend/lm.py", line 309, in evaluate
    x, t = concat_examples(batch, device=self.device, padding=(0, -100))
  File "/home/christopher/gitrepos/espnet-1/espnet/lm/pytorch_backend/lm.py", line 229, in concat_examples
    if device is not None and device >= 0:
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/home/christopher/gitrepos/espnet-1/egs/an4/asr1/../../../espnet/bin/lm_train.py", line 145, in <module>
    main(sys.argv[1:])
  File "/home/christopher/gitrepos/espnet-1/egs/an4/asr1/../../../espnet/bin/lm_train.py", line 139, in main
    train(args)
  File "/home/christopher/gitrepos/espnet-1/espnet/lm/pytorch_backend/lm.py", line 421, in train
    trainer.run()
  File "/home/christopher/gitrepos/espnet-1/tools/venv/lib/python3.6/site-packages/chainer/training/trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "/home/christopher/gitrepos/espnet-1/tools/venv/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/christopher/gitrepos/espnet-1/tools/venv/lib/python3.6/site-packages/chainer/training/trainer.py", line 319, in run
    entry.extension(self)
  File "/home/christopher/gitrepos/espnet-1/tools/venv/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py", line 161, in __call__
    result = self.evaluate()
  File "/home/christopher/gitrepos/espnet-1/espnet/lm/pytorch_backend/lm.py", line 309, in evaluate
    x, t = concat_examples(batch, device=self.device, padding=(0, -100))
  File "/home/christopher/gitrepos/espnet-1/espnet/lm/pytorch_backend/lm.py", line 229, in concat_examples
    if device is not None and device >= 0:
TypeError: '>=' not supported between instances of 'GpuDevice' and 'int'
```

There seems also to be some change to serialization. The following error happened.
```
Exception in main training loop: 'ClassifierWithState' object has no attribute 'serialize'
Traceback (most recent call last):
  File "/home/christopher/gitrepos/espnet-1/tools/venv/lib/python3.6/site-packages/chainer/training/trainer.py", line 319, in run
    entry.extension(self)
  File "/home/christopher/gitrepos/espnet-1/tools/venv/lib/python3.6/site-packages/chainer/training/extensions/_snapshot.py", line 224, in __call__
    self._make_snapshot(trainer)
  File "/home/christopher/gitrepos/espnet-1/tools/venv/lib/python3.6/site-packages/chainer/training/extensions/_snapshot.py", line 228, in _make_snapshot
    serialized_target = npz.serialize(target)
  File "/home/christopher/gitrepos/espnet-1/tools/venv/lib/python3.6/site-packages/chainer/serializers/npz.py", line 79, in serialize
    s.save(obj)
  File "/home/christopher/gitrepos/espnet-1/tools/venv/lib/python3.6/site-packages/chainer/serializer.py", line 67, in save
    obj.serialize(self)
  File "/home/christopher/gitrepos/espnet-1/tools/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/home/christopher/gitrepos/espnet-1/egs/an4/asr1/../../../espnet/bin/lm_train.py", line 145, in <module>
    main(sys.argv[1:])
  File "/home/christopher/gitrepos/espnet-1/egs/an4/asr1/../../../espnet/bin/lm_train.py", line 139, in main
    train(args)
  File "/home/christopher/gitrepos/espnet-1/espnet/lm/pytorch_backend/lm.py", line 421, in train
    trainer.run()
  File "/home/christopher/gitrepos/espnet-1/tools/venv/lib/python3.6/site-packages/chainer/training/trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "/home/christopher/gitrepos/espnet-1/tools/venv/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/christopher/gitrepos/espnet-1/tools/venv/lib/python3.6/site-packages/chainer/training/trainer.py", line 319, in run
    entry.extension(self)
  File "/home/christopher/gitrepos/espnet-1/tools/venv/lib/python3.6/site-packages/chainer/training/extensions/_snapshot.py", line 224, in __call__
    self._make_snapshot(trainer)
  File "/home/christopher/gitrepos/espnet-1/tools/venv/lib/python3.6/site-packages/chainer/training/extensions/_snapshot.py", line 228, in _make_snapshot
    serialized_target = npz.serialize(target)
  File "/home/christopher/gitrepos/espnet-1/tools/venv/lib/python3.6/site-packages/chainer/serializers/npz.py", line 79, in serialize
    s.save(obj)
  File "/home/christopher/gitrepos/espnet-1/tools/venv/lib/python3.6/site-packages/chainer/serializer.py", line 67, in save
    obj.serialize(self)
  File "/home/christopher/gitrepos/espnet-1/tools/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'ClassifierWithState' object has no attribute 'serialize'
```

I'm going to create PR that reverts #753 .

**Comment by ShigekiKarita** [comment]
Maybe we should add the `master` or `nightly` version of chainer and pytorch in Travis-CI. We can ignore their failure but keep them in touch.

**Comment by sw005320** [comment]
I agree. Let me check #763.

**Comment by sw005320** [comment]
If this is the only reason, I think we can fix it easily. Can someone do it?

**Comment by sw005320** [comment]
#772 fixed this issue.
