### ISSUE TITLE
chainer_ctc installation

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#96]
@jheymann85, I have the following error message when installing it. Do you have any ideas?
```
    Complete output from command python setup.py egg_info:
    /usr/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'include'
      warnings.warn(msg)
    zip_safe flag not set; analyzing archive contents...

    Installed /tmp/pip-0PFC4n-build/setuptools_cython-0.2.1-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-0PFC4n-build/setup.py", line 29, in <module>
        language='c++')
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/export/a08/shinji/201707e2e/espnet_conda/tools/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 266, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/export/a08/shinji/201707e2e/espnet_conda/tools/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 301, in finalize_options
        ep.load()(self, ep.name, value)
      File "/export/a08/shinji/201707e2e/espnet_conda/tools/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2190, in load
        ['__name__'])
      File "build/bdist.linux-x86_64/egg/setuptools_cython.py", line 21, in <module>
    AttributeError: 'module' object has no attribute 'Distutils'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-0PFC4n-build/
Makefile:41: recipe for target 'chainer_ctc' failed
```

**Comment by jheymann85** [comment]
Hm, seems to be an issue with Cython, does it work if you delete this line: https://github.com/espnet/espnet/blob/master/tools/Makefile#L42 ?

**Comment by sw005320** [comment]
It does not solve my issue. BTW, the conda version (`make -f conda.mk`) seems to work. It might be an issue of a system python in the CLSP cluster. We may think of only using the conda version. @ShigekiKarita, what do you think?

**Comment by sw005320** [comment]
I think I solved the issue by upgrading `setuptools`. I'll add `setuptools>=38.5.1` in `requirements.txt`.

**Comment by sw005320** [comment]
I believe #99 fixed the issue.

**Comment by sw005320** [comment]
Do you have the exactly same error message? Can you put it here?

**Comment by shunfeichen** [comment]
Sorry, I can't download the error message? I have two errors when installing. Fisrtly, when installing cupy, it have the following error message: 
File "build/bdist.linux-x86_64/egg/setuptools_cython.py", line 21, in <module>
    AttributeError: 'module' object has no attribute 'Distutils'
Secondly, when installing chainer_ctc, it have the following error message:
File "build/bdist.linux-x86_64/egg/setuptools_cython.py", line 7, in <module>
    KeyError:'Cython'

I think the two errors seem to be related the path of Cython. But I still don't know how to solve it.
